// Country/area → UN M49 region and sub-region classification.
// Source: United Nations Statistics Division, "Standard Country or Area Codes
// for Statistical Use (M49)", https://unstats.un.org/unsd/methodology/m49/
// Keyed by ISO 3166-1 alpha-2 code. Region/subregion names are the M49
// "Region Name" and "Sub-region Name" columns verbatim (the coarser,
// two-level grouping — not the finer "Intermediate Region Name" column).
//
// A handful of uninhabited or disputed territories (e.g. Antarctica) have no
// M49 region assignment and are intentionally omitted; `m49For` returns
// `undefined` for any code not present here.

export type M49Entry = { region: string; subregion: string };

const NORTHERN_AFRICA = { region: 'Africa', subregion: 'Northern Africa' };
const SUB_SAHARAN_AFRICA = { region: 'Africa', subregion: 'Sub-Saharan Africa' };

const LATIN_AMERICA_AND_CARIBBEAN = { region: 'Americas', subregion: 'Latin America and the Caribbean' };
const NORTHERN_AMERICA = { region: 'Americas', subregion: 'Northern America' };

const CENTRAL_ASIA = { region: 'Asia', subregion: 'Central Asia' };
const EASTERN_ASIA = { region: 'Asia', subregion: 'Eastern Asia' };
const SOUTH_EASTERN_ASIA = { region: 'Asia', subregion: 'South-eastern Asia' };
const SOUTHERN_ASIA = { region: 'Asia', subregion: 'Southern Asia' };
const WESTERN_ASIA = { region: 'Asia', subregion: 'Western Asia' };

const EASTERN_EUROPE = { region: 'Europe', subregion: 'Eastern Europe' };
const NORTHERN_EUROPE = { region: 'Europe', subregion: 'Northern Europe' };
const SOUTHERN_EUROPE = { region: 'Europe', subregion: 'Southern Europe' };
const WESTERN_EUROPE = { region: 'Europe', subregion: 'Western Europe' };

const AUSTRALIA_AND_NEW_ZEALAND = { region: 'Oceania', subregion: 'Australia and New Zealand' };
const MELANESIA = { region: 'Oceania', subregion: 'Melanesia' };
const MICRONESIA = { region: 'Oceania', subregion: 'Micronesia' };
const POLYNESIA = { region: 'Oceania', subregion: 'Polynesia' };

export const M49: Record<string, M49Entry> = {
  // --- Africa: Northern Africa ---
  DZ: NORTHERN_AFRICA, EG: NORTHERN_AFRICA, LY: NORTHERN_AFRICA, MA: NORTHERN_AFRICA,
  SD: NORTHERN_AFRICA, TN: NORTHERN_AFRICA, EH: NORTHERN_AFRICA,

  // --- Africa: Sub-Saharan Africa ---
  BI: SUB_SAHARAN_AFRICA, KM: SUB_SAHARAN_AFRICA, DJ: SUB_SAHARAN_AFRICA, ER: SUB_SAHARAN_AFRICA,
  ET: SUB_SAHARAN_AFRICA, IO: SUB_SAHARAN_AFRICA, KE: SUB_SAHARAN_AFRICA, MG: SUB_SAHARAN_AFRICA,
  MW: SUB_SAHARAN_AFRICA, MU: SUB_SAHARAN_AFRICA, YT: SUB_SAHARAN_AFRICA, MZ: SUB_SAHARAN_AFRICA,
  RE: SUB_SAHARAN_AFRICA, RW: SUB_SAHARAN_AFRICA, SC: SUB_SAHARAN_AFRICA, SO: SUB_SAHARAN_AFRICA,
  SS: SUB_SAHARAN_AFRICA, TZ: SUB_SAHARAN_AFRICA, UG: SUB_SAHARAN_AFRICA, ZM: SUB_SAHARAN_AFRICA,
  ZW: SUB_SAHARAN_AFRICA, TF: SUB_SAHARAN_AFRICA,
  AO: SUB_SAHARAN_AFRICA, CM: SUB_SAHARAN_AFRICA, CF: SUB_SAHARAN_AFRICA, TD: SUB_SAHARAN_AFRICA,
  CG: SUB_SAHARAN_AFRICA, CD: SUB_SAHARAN_AFRICA, GQ: SUB_SAHARAN_AFRICA, GA: SUB_SAHARAN_AFRICA,
  ST: SUB_SAHARAN_AFRICA,
  BW: SUB_SAHARAN_AFRICA, SZ: SUB_SAHARAN_AFRICA, LS: SUB_SAHARAN_AFRICA, NA: SUB_SAHARAN_AFRICA,
  ZA: SUB_SAHARAN_AFRICA, BV: SUB_SAHARAN_AFRICA,
  BJ: SUB_SAHARAN_AFRICA, BF: SUB_SAHARAN_AFRICA, CV: SUB_SAHARAN_AFRICA, CI: SUB_SAHARAN_AFRICA,
  GM: SUB_SAHARAN_AFRICA, GH: SUB_SAHARAN_AFRICA, GN: SUB_SAHARAN_AFRICA, GW: SUB_SAHARAN_AFRICA,
  LR: SUB_SAHARAN_AFRICA, ML: SUB_SAHARAN_AFRICA, MR: SUB_SAHARAN_AFRICA, NE: SUB_SAHARAN_AFRICA,
  NG: SUB_SAHARAN_AFRICA, SH: SUB_SAHARAN_AFRICA, SN: SUB_SAHARAN_AFRICA, SL: SUB_SAHARAN_AFRICA,
  TG: SUB_SAHARAN_AFRICA,

  // --- Americas: Latin America and the Caribbean ---
  AI: LATIN_AMERICA_AND_CARIBBEAN, AG: LATIN_AMERICA_AND_CARIBBEAN, AW: LATIN_AMERICA_AND_CARIBBEAN,
  BS: LATIN_AMERICA_AND_CARIBBEAN, BB: LATIN_AMERICA_AND_CARIBBEAN, BQ: LATIN_AMERICA_AND_CARIBBEAN,
  VG: LATIN_AMERICA_AND_CARIBBEAN, KY: LATIN_AMERICA_AND_CARIBBEAN, CU: LATIN_AMERICA_AND_CARIBBEAN,
  CW: LATIN_AMERICA_AND_CARIBBEAN, DM: LATIN_AMERICA_AND_CARIBBEAN, DO: LATIN_AMERICA_AND_CARIBBEAN,
  GD: LATIN_AMERICA_AND_CARIBBEAN, GP: LATIN_AMERICA_AND_CARIBBEAN, HT: LATIN_AMERICA_AND_CARIBBEAN,
  JM: LATIN_AMERICA_AND_CARIBBEAN, MQ: LATIN_AMERICA_AND_CARIBBEAN, MS: LATIN_AMERICA_AND_CARIBBEAN,
  PR: LATIN_AMERICA_AND_CARIBBEAN, BL: LATIN_AMERICA_AND_CARIBBEAN, KN: LATIN_AMERICA_AND_CARIBBEAN,
  LC: LATIN_AMERICA_AND_CARIBBEAN, MF: LATIN_AMERICA_AND_CARIBBEAN, VC: LATIN_AMERICA_AND_CARIBBEAN,
  SX: LATIN_AMERICA_AND_CARIBBEAN, TT: LATIN_AMERICA_AND_CARIBBEAN, TC: LATIN_AMERICA_AND_CARIBBEAN,
  VI: LATIN_AMERICA_AND_CARIBBEAN,
  BZ: LATIN_AMERICA_AND_CARIBBEAN, CR: LATIN_AMERICA_AND_CARIBBEAN, SV: LATIN_AMERICA_AND_CARIBBEAN,
  GT: LATIN_AMERICA_AND_CARIBBEAN, HN: LATIN_AMERICA_AND_CARIBBEAN, MX: LATIN_AMERICA_AND_CARIBBEAN,
  NI: LATIN_AMERICA_AND_CARIBBEAN, PA: LATIN_AMERICA_AND_CARIBBEAN,
  AR: LATIN_AMERICA_AND_CARIBBEAN, BO: LATIN_AMERICA_AND_CARIBBEAN, BR: LATIN_AMERICA_AND_CARIBBEAN,
  CL: LATIN_AMERICA_AND_CARIBBEAN, CO: LATIN_AMERICA_AND_CARIBBEAN, EC: LATIN_AMERICA_AND_CARIBBEAN,
  FK: LATIN_AMERICA_AND_CARIBBEAN, GF: LATIN_AMERICA_AND_CARIBBEAN, GY: LATIN_AMERICA_AND_CARIBBEAN,
  PY: LATIN_AMERICA_AND_CARIBBEAN, PE: LATIN_AMERICA_AND_CARIBBEAN, SR: LATIN_AMERICA_AND_CARIBBEAN,
  UY: LATIN_AMERICA_AND_CARIBBEAN, VE: LATIN_AMERICA_AND_CARIBBEAN, GS: LATIN_AMERICA_AND_CARIBBEAN,

  // --- Americas: Northern America ---
  BM: NORTHERN_AMERICA, CA: NORTHERN_AMERICA, GL: NORTHERN_AMERICA, PM: NORTHERN_AMERICA,
  US: NORTHERN_AMERICA,

  // --- Asia: Central Asia ---
  KZ: CENTRAL_ASIA, KG: CENTRAL_ASIA, TJ: CENTRAL_ASIA, TM: CENTRAL_ASIA, UZ: CENTRAL_ASIA,

  // --- Asia: Eastern Asia ---
  CN: EASTERN_ASIA, HK: EASTERN_ASIA, MO: EASTERN_ASIA, JP: EASTERN_ASIA, KP: EASTERN_ASIA,
  KR: EASTERN_ASIA, MN: EASTERN_ASIA, TW: EASTERN_ASIA,

  // --- Asia: South-eastern Asia ---
  BN: SOUTH_EASTERN_ASIA, KH: SOUTH_EASTERN_ASIA, ID: SOUTH_EASTERN_ASIA, LA: SOUTH_EASTERN_ASIA,
  MY: SOUTH_EASTERN_ASIA, MM: SOUTH_EASTERN_ASIA, PH: SOUTH_EASTERN_ASIA, SG: SOUTH_EASTERN_ASIA,
  TH: SOUTH_EASTERN_ASIA, TL: SOUTH_EASTERN_ASIA, VN: SOUTH_EASTERN_ASIA,

  // --- Asia: Southern Asia ---
  AF: SOUTHERN_ASIA, BD: SOUTHERN_ASIA, BT: SOUTHERN_ASIA, IN: SOUTHERN_ASIA, IR: SOUTHERN_ASIA,
  MV: SOUTHERN_ASIA, NP: SOUTHERN_ASIA, PK: SOUTHERN_ASIA, LK: SOUTHERN_ASIA,

  // --- Asia: Western Asia ---
  AM: WESTERN_ASIA, AZ: WESTERN_ASIA, BH: WESTERN_ASIA, CY: WESTERN_ASIA, GE: WESTERN_ASIA,
  IQ: WESTERN_ASIA, IL: WESTERN_ASIA, JO: WESTERN_ASIA, KW: WESTERN_ASIA, LB: WESTERN_ASIA,
  OM: WESTERN_ASIA, PS: WESTERN_ASIA, QA: WESTERN_ASIA, SA: WESTERN_ASIA, SY: WESTERN_ASIA,
  TR: WESTERN_ASIA, AE: WESTERN_ASIA, YE: WESTERN_ASIA,

  // --- Europe: Eastern Europe ---
  BY: EASTERN_EUROPE, BG: EASTERN_EUROPE, CZ: EASTERN_EUROPE, HU: EASTERN_EUROPE, MD: EASTERN_EUROPE,
  PL: EASTERN_EUROPE, RO: EASTERN_EUROPE, RU: EASTERN_EUROPE, SK: EASTERN_EUROPE, UA: EASTERN_EUROPE,

  // --- Europe: Northern Europe ---
  DK: NORTHERN_EUROPE, EE: NORTHERN_EUROPE, FO: NORTHERN_EUROPE, FI: NORTHERN_EUROPE,
  IS: NORTHERN_EUROPE, IE: NORTHERN_EUROPE, IM: NORTHERN_EUROPE, LV: NORTHERN_EUROPE,
  LT: NORTHERN_EUROPE, NO: NORTHERN_EUROPE, SJ: NORTHERN_EUROPE, SE: NORTHERN_EUROPE,
  GB: NORTHERN_EUROPE, AX: NORTHERN_EUROPE, GG: NORTHERN_EUROPE, JE: NORTHERN_EUROPE,

  // --- Europe: Southern Europe ---
  AL: SOUTHERN_EUROPE, AD: SOUTHERN_EUROPE, BA: SOUTHERN_EUROPE, HR: SOUTHERN_EUROPE,
  GI: SOUTHERN_EUROPE, GR: SOUTHERN_EUROPE, IT: SOUTHERN_EUROPE, XK: SOUTHERN_EUROPE,
  MT: SOUTHERN_EUROPE, ME: SOUTHERN_EUROPE, MK: SOUTHERN_EUROPE, PT: SOUTHERN_EUROPE,
  SM: SOUTHERN_EUROPE, RS: SOUTHERN_EUROPE, SI: SOUTHERN_EUROPE, ES: SOUTHERN_EUROPE,
  VA: SOUTHERN_EUROPE,

  // --- Europe: Western Europe ---
  AT: WESTERN_EUROPE, BE: WESTERN_EUROPE, FR: WESTERN_EUROPE, DE: WESTERN_EUROPE,
  LI: WESTERN_EUROPE, LU: WESTERN_EUROPE, MC: WESTERN_EUROPE, NL: WESTERN_EUROPE, CH: WESTERN_EUROPE,

  // --- Oceania: Australia and New Zealand ---
  AU: AUSTRALIA_AND_NEW_ZEALAND, NZ: AUSTRALIA_AND_NEW_ZEALAND, NF: AUSTRALIA_AND_NEW_ZEALAND,
  CC: AUSTRALIA_AND_NEW_ZEALAND, CX: AUSTRALIA_AND_NEW_ZEALAND, HM: AUSTRALIA_AND_NEW_ZEALAND,

  // --- Oceania: Melanesia ---
  FJ: MELANESIA, NC: MELANESIA, PG: MELANESIA, SB: MELANESIA, VU: MELANESIA,

  // --- Oceania: Micronesia ---
  GU: MICRONESIA, KI: MICRONESIA, MH: MICRONESIA, FM: MICRONESIA, NR: MICRONESIA,
  MP: MICRONESIA, PW: MICRONESIA, UM: MICRONESIA,

  // --- Oceania: Polynesia ---
  AS: POLYNESIA, CK: POLYNESIA, PF: POLYNESIA, NU: POLYNESIA, PN: POLYNESIA, WS: POLYNESIA,
  TK: POLYNESIA, TO: POLYNESIA, TV: POLYNESIA, WF: POLYNESIA,
};

export function m49For(countryCode: string): M49Entry | undefined {
  return M49[countryCode];
}
