// Thin runtime accessor over the pool `data:curate` generates. Reads the
// generated JSON — never the curated TS source directly — so the running
// game and `data:curate` agree on exactly one artefact. The JSON files are
// gitignored and regenerated by `postinstall` (`npm run data:curate`); if
// they are missing, `npm install` (or a manual `npm run data:curate`) is
// what's needed, not a change to this file.
import buildingsData from '@/data/curated-buildings.json';
import architectsData from '@/data/curated-architects.json';
import type { Building } from '@/types/building';
import type { Architect } from '@/types/architect';

export const BUILDINGS: Building[] = buildingsData as Building[];
export const ARCHITECTS: Architect[] = architectsData as Architect[];

export class ArchitectNotFoundError extends Error {
  constructor(id: string) {
    super(`No architect found with id "${id}"`);
    this.name = 'ArchitectNotFoundError';
  }
}

export function architectById(id: string): Architect {
  const found = ARCHITECTS.find((a) => a.id === id);
  if (!found) throw new ArchitectNotFoundError(id);
  return found;
}

export function buildingBySlug(slug: string): Building | undefined {
  return BUILDINGS.find((b) => b.id === slug);
}

export function canonBuildings(): Building[] {
  return BUILDINGS.filter((b) => b.tier === 'canon');
}

// Every architect referenced by at least one building — and nothing else,
// so an `architect-orphan` violation (Task 3) is the only thing that could
// ever make this differ from `ARCHITECTS` itself.
export function roster(): Architect[] {
  const referencedIds = new Set(BUILDINGS.map((b) => b.architectId));
  return ARCHITECTS.filter((a) => referencedIds.has(a.id));
}
