import type { Building } from '@/types/building';

// Wave 5 curator agent (West Africa): real, sourced Building entries for this slice.
//
// Countries in scope: NG, GH, SN, BF, ML, CI, BJ, TG, GN, SL, LR, GM, NE, MR.
//
// Every image licence below was read from the rendered Wikimedia Commons file
// page (not the API's extmetadata field) on 2026-08-26, and the photographer is
// recorded exactly as the file page credits them.
//
// Two structural constraints shaped this set and are documented in the task
// report. First, thirteen of the fourteen countries have no Freedom of
// Panorama provision compatible with Wikimedia Commons, so buildings whose
// architecture is still in copyright are only representable in Nigeria, and
// there only through photographs uploaded to Commons before 17 March 2023,
// when the repealed Copyright Act 2004 still permitted "the reproduction and
// distribution of copies of any artistic work permanently situated in a place
// where it can be viewed by the public". The fourteenth, Mauritania, in fact
// has full commercial-compatible FoP under Law No. 2012-038 (17 July 2012),
// Article 47 — confirmed on Commons' own Commons:CRT/Mauritania page — but no
// Mauritanian building with both a named architect/builder and a licence-clean,
// well-attributed Commons image was found; see the task report for what was
// searched. Second, a live Wikidata query on 2026-08-26 returned 39 buildings
// with an attributed architect across all fourteen countries; the metadata
// below is largely hand-authored from published scholarship.
export const AFRICA_WEST_BUILDINGS: Building[] = [
  {
    id: 'sankore-madrasa-timbuktu',
    wikidataId: 'Q1265294',
    name: {
      en: 'Sankoré Madrasa',
      es: 'Medersa de Sankoré',
      it: 'Madrasa di Sankoré',
    },
    architectId: 'al-aqib-ibn-mahmud',
    location: { city: 'Timbuktu', countryCode: 'ML', lat: 16.775833, lon: -3.005556 },
    inception: 1578,
    completed: 1582,
    demolished: null,
    typology: 'sacral',
    materials: ['earth', 'timber'],
    structure: {
      en: 'Load-bearing walls of sun-dried mud brick rendered in banco, with palm-wood beams left projecting through the faces as permanent scaffolding for replastering, carrying a flat earth roof over a hypostyle prayer hall.',
      es: 'Muros de carga de adobe secado al sol y revocados con banco, con vigas de madera de palmera que sobresalen de los paramentos como andamiaje permanente para el revoco, sosteniendo una cubierta plana de tierra sobre una sala de oración hipóstila.',
      it: 'Muri portanti in mattoni crudi essiccati al sole e intonacati in banco, con travi di legno di palma lasciate sporgere dai paramenti come impalcatura permanente per la rintonacatura, che reggono una copertura piana in terra su una sala di preghiera ipostila.',
    },
    program: {
      en: "A congregational mosque in the Sankoré quarter that became the focal point of Timbuktu's scholarly community, where individual jurists taught their own students rather than a single institution enrolling them.",
      es: 'Una mezquita congregacional del barrio de Sankoré que se convirtió en el centro de la comunidad erudita de Tombuctú, donde cada jurista enseñaba a sus propios alumnos en lugar de haber una institución única que los matriculara.',
      it: "Una moschea congregazionale del quartiere di Sankoré che divenne il fulcro della comunità dei dotti di Timbuctù, dove i singoli giuristi insegnavano ai propri allievi anziché esistere un'unica istituzione che li iscrivesse.",
    },
    heritage: 'unesco',
    currentUse: {
      en: 'Working mosque and Quranic school; part of the Timbuktu World Heritage Site, on the List of World Heritage in Danger since 2012.',
      es: 'Mezquita en uso y escuela coránica; forma parte del sitio del Patrimonio Mundial de Tombuctú, inscrito en la Lista del Patrimonio Mundial en Peligro desde 2012.',
      it: 'Moschea in uso e scuola coranica; fa parte del sito Patrimonio dell’Umanità di Timbuctù, iscritto nella Lista del patrimonio in pericolo dal 2012.',
    },
    detailRect: { x: 0.36, y: 0.28, w: 0.30, h: 0.34 },
    image: {
      commonsFile: 'File:Sankore Mosque in Timbuktu.jpg',
      photographer: 'upyernoz',
      license: 'CC BY 2.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Sankore_Mosque_in_Timbuktu.jpg',
      width: 1600,
      height: 1038,
    },
    dossier: {
      en: "Sankoré was founded in the fourteenth or early fifteenth century, financed by a Tuareg woman of the Aghlal tribe, and grew into the mosque most closely associated with teaching in Timbuktu. The building standing today is not that first mosque. Between 1578 and 1582 the chief qadi of the city, al-Aqib ibn Mahmud ibn Umar, had the sanctuary demolished and rebuilt; the seventeenth-century chronicle Ta'rikh al-Sudan records that he had measured the Kaaba with a rope on pilgrimage and set out the new prayer hall to those dimensions. The result is a squat pyramidal minaret and a mud-brick hall bristling with toron, the palm beams that let masons climb the wall to replaster it. Timbuktu's scholars were deported to Morocco after the Songhai defeat at Tondibi in 1591, and the mosque's long decline dates from then.",
      es: 'Sankoré se fundó en el siglo XIV o a comienzos del XV, financiada por una mujer tuareg de la tribu aghlal, y llegó a ser la mezquita más ligada a la enseñanza en Tombuctú. El edificio que hoy se ve no es aquella primera mezquita. Entre 1578 y 1582, el cadí mayor de la ciudad, al-Aqib ibn Mahmud ibn Umar, hizo demoler y reconstruir el santuario; la crónica del siglo XVII Ta’rikh al-Sudan cuenta que había medido la Kaaba con una cuerda durante su peregrinación y trazó la nueva sala de oración con esas dimensiones. El resultado es un alminar piramidal y achaparrado y una sala de adobe erizada de toron, las vigas de palmera que permiten a los albañiles trepar por el muro para revocarlo. Los sabios de Tombuctú fueron deportados a Marruecos tras la derrota songhai de Tondibi en 1591, y de ahí arranca el largo declive de la mezquita.',
      it: "Sankoré fu fondata nel Trecento o agli inizi del Quattrocento, finanziata da una donna tuareg della tribù aghlal, e divenne la moschea più legata all'insegnamento a Timbuctù. L'edificio che oggi si vede non è quella prima moschea. Tra il 1578 e il 1582 il qadi capo della città, al-Aqib ibn Mahmud ibn Umar, fece demolire e ricostruire il santuario; la cronaca secentesca Ta'rikh al-Sudan racconta che egli aveva misurato la Kaaba con una corda durante il pellegrinaggio e tracciò la nuova sala di preghiera secondo quelle misure. Ne risultano un minareto piramidale e tozzo e una sala in mattoni crudi irta di toron, le travi di palma che permettono ai muratori di arrampicarsi sul muro per rintonacarlo. I dotti di Timbuctù furono deportati in Marocco dopo la sconfitta songhai di Tondibi nel 1591, e da allora data il lungo declino della moschea.",
    },
    context: null,
    sources: [
      {
        kind: 'wikipedia',
        url: 'https://en.wikipedia.org/wiki/Sankor%C3%A9_Madrasah',
        title: 'Sankoré Madrasah',
        license: 'CC BY-SA 4.0',
      },
      {
        kind: 'institution',
        url: 'https://whc.unesco.org/en/list/119/',
        title: 'Timbuktu — UNESCO World Heritage Centre',
        license: null,
      },
      {
        kind: 'wikidata',
        url: 'https://www.wikidata.org/wiki/Q1265294',
        title: 'Sankoré Madrasah (Q1265294)',
        license: null,
      },
    ],
    tier: 'canon',
  },
  {
    id: 'maison-des-esclaves-goree',
    wikidataId: 'Q691908',
    name: {
      en: 'House of Slaves, Gorée',
      es: 'Casa de los Esclavos de Gorea',
      it: 'Casa degli Schiavi di Gorée',
    },
    architectId: 'nicolas-pepin',
    location: { city: 'Gorée', countryCode: 'SN', lat: 14.66778, lon: -17.39722 },
    inception: 1776,
    completed: null,
    demolished: null,
    typology: 'domestic',
    materials: ['mixed'],
    structure: {
      en: 'Load-bearing masonry in two storeys around a narrow court, the upper living floor reached by twin curved external stairs that meet at a landing, with low vaulted cells beneath and a tiled roof above.',
      es: 'Fábrica portante de dos plantas en torno a un patio estrecho; a la planta noble se accede por dos escaleras exteriores curvas que se encuentran en un rellano, con celdas abovedadas de escasa altura debajo y una cubierta de teja encima.',
      it: 'Muratura portante su due piani attorno a una corte stretta; al piano nobile si sale per due scale esterne curve che si incontrano su un pianerottolo, con celle voltate basse al di sotto e un tetto in tegole al di sopra.',
    },
    program: {
      en: 'A Gorée merchant house of the standard island type — trading family above, storage and holding cells below — built for and by a family that owned ships and dealt in enslaved people.',
      es: 'Una casa mercantil de Gorea del tipo insular habitual —la familia comerciante arriba, almacenes y celdas de retención abajo— construida para y por una familia que poseía barcos y traficaba con personas esclavizadas.',
      it: "Una casa mercantile di Gorée del tipo isolano consueto — la famiglia di commercianti sopra, magazzini e celle di detenzione sotto — costruita per e da una famiglia che possedeva navi e trafficava in persone schiavizzate.",
    },
    heritage: 'unesco',
    currentUse: {
      en: 'Museum and memorial to the victims of the Atlantic slave trade, opened in 1962 and curated by Boubacar Joseph Ndiaye until his death in 2009.',
      es: 'Museo y memorial de las víctimas de la trata atlántica, abierto en 1962 y dirigido por Boubacar Joseph Ndiaye hasta su muerte en 2009.',
      it: 'Museo e memoriale delle vittime della tratta atlantica, aperto nel 1962 e curato da Boubacar Joseph Ndiaye fino alla morte, nel 2009.',
    },
    detailRect: { x: 0.34, y: 0.32, w: 0.32, h: 0.34 },
    image: {
      commonsFile: 'File:Gorée 2024 - Maison des esclaves - 08.jpg',
      photographer: 'Fawaz.tairou',
      license: 'CC BY 4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Gor%C3%A9e_2024_-_Maison_des_esclaves_-_08.jpg',
      width: 1600,
      height: 1067,
    },
    dossier: {
      en: "The house on rue Saint-Germain was built between about 1776 and 1786 by Nicolas Pépin, son of the signare Catherine Baudet and brother of Anne Pépin. It is an ordinary Gorée type made extraordinary by what it came to stand for: a two-storey masonry block whose twin curved stairs sweep up to the merchant's floor while the ground level is given over to low cells and a seaward opening now known as the Door of No Return. The plan separates the family's rooms from the held people beneath as a matter of construction, not of retrospective symbolism. Since 1962 it has been a museum, and it is the best-known memorial to the Atlantic slave trade anywhere in Africa. How much of the trade actually passed through this particular house is disputed by historians, and the dispute is set out in the context note below.",
      es: 'La casa de la rue Saint-Germain fue construida entre 1776 y 1786 aproximadamente por Nicolas Pépin, hijo de la signare Catherine Baudet y hermano de Anne Pépin. Es un tipo goreano corriente vuelto extraordinario por lo que acabó representando: un bloque de fábrica de dos plantas cuyas dos escaleras curvas ascienden hasta la planta del comerciante mientras la baja se entrega a celdas de escasa altura y a un vano abierto al mar hoy llamado la Puerta del No Retorno. La planta separa las habitaciones de la familia de las personas retenidas abajo por razones constructivas, no por un simbolismo retrospectivo. Desde 1962 es un museo y el memorial más conocido de la trata atlántica en toda África. Cuánta trata pasó realmente por esta casa concreta es objeto de disputa entre historiadores, y esa disputa se expone en la nota de contexto.',
      it: "La casa di rue Saint-Germain fu costruita tra il 1776 e il 1786 circa da Nicolas Pépin, figlio della signare Catherine Baudet e fratello di Anne Pépin. È un tipo goreano ordinario reso straordinario da ciò che è arrivato a rappresentare: un blocco murario a due piani le cui due scale curve salgono al piano del mercante mentre il piano terra è occupato da celle basse e da un'apertura verso il mare oggi nota come la Porta del Non Ritorno. La pianta separa le stanze della famiglia dalle persone detenute sotto per ragioni costruttive, non per un simbolismo retrospettivo. Dal 1962 è un museo ed è il memoriale più noto della tratta atlantica in tutta l'Africa. Quanta parte della tratta sia realmente passata per questa casa è oggetto di disputa fra gli storici, e la disputa è esposta nella nota di contesto.",
    },
    context: {
      body: {
        en: "The Pépin family owned ships and took part in the Atlantic slave trade; the house was used to hold enslaved people before export, and accounts describe them shackled in dark, airless cells, families separated by sex and age. The scale is contested. Philip D. Curtin's 1969 statistics record enforced transports from Gorée from about 1670 to 1810 at no more than 200 to 300 a year, and argue the doorway itself was built too late to matter; Ana Lucia Araujo has said plainly that it is not the place from which people left in the numbers claimed. Boubacar Joseph Ndiaye, the museum's curator from 1962 to 2009, maintained the opposite, and a 1998 African historical conference cited Nantes records of 103,000 people — a figure later shown to describe Upper Guinea as a whole rather than Gorée. Historians who dispute the numbers still hold the island to be a legitimate memorial to a trade carried on at greater scale from ports in present-day Ghana and Benin.",
        es: 'La familia Pépin poseía barcos y participó en la trata atlántica; la casa se usó para retener a personas esclavizadas antes de su exportación, y los relatos las describen encadenadas en celdas oscuras y sin aire, con las familias separadas por sexo y edad. La escala está en disputa. Las estadísticas de Philip D. Curtin de 1969 registran para Gorea, entre 1670 y 1810 aproximadamente, un máximo de 200 a 300 personas al año, y sostienen que la propia puerta se construyó demasiado tarde para tener importancia; Ana Lucia Araujo ha dicho sin rodeos que no es el lugar del que salió la gente en las cifras que se afirman. Boubacar Joseph Ndiaye, conservador del museo entre 1962 y 2009, defendió lo contrario, y una conferencia histórica africana de 1998 citó registros de Nantes con 103.000 personas, cifra que luego se demostró referida a toda la Alta Guinea y no a Gorea. Los historiadores que discuten las cifras siguen considerando la isla un memorial legítimo de una trata que se ejerció a mayor escala desde puertos de los actuales Ghana y Benín.',
        it: "La famiglia Pépin possedeva navi e prese parte alla tratta atlantica; la casa fu usata per trattenere persone schiavizzate prima dell'imbarco, e le testimonianze le descrivono incatenate in celle buie e senz'aria, con le famiglie separate per sesso ed età. La scala del fenomeno è contesa. Le statistiche di Philip D. Curtin del 1969 registrano per Gorée, tra il 1670 e il 1810 circa, non più di 200-300 persone all'anno, e sostengono che la porta stessa fu costruita troppo tardi per contare; Ana Lucia Araujo ha detto senza giri di parole che non è il luogo da cui le persone partirono nei numeri che si affermano. Boubacar Joseph Ndiaye, curatore del museo dal 1962 al 2009, sostenne il contrario, e una conferenza storica africana del 1998 citò registri di Nantes relativi a 103.000 persone, cifra poi risultata riferita all'intera Alta Guinea e non a Gorée. Gli storici che contestano i numeri continuano a considerare l'isola un memoriale legittimo di una tratta condotta su scala assai maggiore da porti degli odierni Ghana e Benin.",
      },
      sources: [
        {
          kind: 'wikipedia',
          url: 'https://en.wikipedia.org/wiki/House_of_Slaves',
          title: 'House of Slaves',
          license: 'CC BY-SA 4.0',
        },
        {
          kind: 'institution',
          url: 'https://memoire-esclavage.org/maison-des-esclaves-ile-de-goree',
          title: "Maison des esclaves, Île de Gorée — Fondation pour la mémoire de l'esclavage",
          license: null,
        },
      ],
    },
    sources: [
      {
        kind: 'wikipedia',
        url: 'https://en.wikipedia.org/wiki/House_of_Slaves',
        title: 'House of Slaves',
        license: 'CC BY-SA 4.0',
      },
      {
        kind: 'institution',
        url: 'https://whc.unesco.org/en/list/26/',
        title: 'Island of Gorée — UNESCO World Heritage Centre',
        license: null,
      },
      {
        kind: 'wikidata',
        url: 'https://www.wikidata.org/wiki/Q691908',
        title: 'House of Slaves (Q691908)',
        license: null,
      },
    ],
    tier: 'canon',
  },
  {
    id: 'zaria-friday-mosque',
    wikidataId: null,
    name: {
      en: 'Zaria Friday Mosque',
      es: 'Mezquita del Viernes de Zaria',
      it: 'Moschea del Venerdì di Zaria',
    },
    architectId: 'babban-gwani',
    location: { city: 'Zaria', countryCode: 'NG', lat: 11.0667, lon: 7.7 },
    inception: 1834,
    completed: 1836,
    demolished: null,
    typology: 'sacral',
    materials: ['earth', 'timber'],
    structure: {
      en: 'Mud walls and piers carry ribbed vaults built up in earth over arched azara palm-timber ribs, a technique that translates the bent-pole geometry of Fulani nomadic tents into permanent load-bearing masonry.',
      es: 'Muros y pilares de barro sostienen bóvedas nervadas levantadas en tierra sobre nervios arqueados de madera de palmera azara, una técnica que traslada la geometría de varas curvadas de las tiendas nómadas fulani a una fábrica portante permanente.',
      it: 'Muri e pilastri in terra cruda reggono volte costolonate realizzate in terra su nervature arcuate di legno di palma azara, una tecnica che traduce la geometria a pertiche curvate delle tende nomadi fulani in muratura portante permanente.',
    },
    program: {
      en: "The congregational mosque of the walled old city of Zaria, built next to the Emir of Zazzau's palace and comprising a prayer hall, a sharia court and ablution chambers.",
      es: 'La mezquita congregacional de la ciudad vieja amurallada de Zaria, levantada junto al palacio del emir de Zazzau y compuesta por sala de oración, tribunal de la sharía y salas de ablución.',
      it: "La moschea congregazionale della città vecchia murata di Zaria, costruita accanto al palazzo dell'emiro di Zazzau e composta da sala di preghiera, tribunale della sharia e ambienti per le abluzioni.",
    },
    heritage: null,
    currentUse: {
      en: 'Still the Friday mosque of Zaria City; reconstruction began after part of the roof collapsed during afternoon prayers on 11 August 2023.',
      es: 'Sigue siendo la mezquita del viernes de la ciudad de Zaria; la reconstrucción comenzó tras el derrumbe de parte de la cubierta durante la oración de la tarde del 11 de agosto de 2023.',
      it: 'È tuttora la moschea del venerdì della città di Zaria; la ricostruzione è iniziata dopo il crollo di parte della copertura durante la preghiera pomeridiana dell’11 agosto 2023.',
    },
    detailRect: { x: 0.33, y: 0.32, w: 0.32, h: 0.34 },
    image: {
      commonsFile: 'File:Zaria Friday Mosque.jpg',
      photographer: 'DipoTayo',
      license: 'CC BY-SA 4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Zaria_Friday_Mosque.jpg',
      width: 1600,
      height: 1206,
    },
    dossier: {
      en: "The Friday Mosque of Zaria is the surviving masterpiece of Hausa earthen building and the earliest West African monument that can be given confidently to a named individual. It was raised in the mid-1830s, during the reign of Sarkin Zazzau Abd al-Karim, by the master builder Mallam Mikhaila, known by the title Babban Gwani, 'the great expert'. Its interior is the argument: mud vaults spanning wide rooms on arched ribs of azara palm, a structural idea taken from the bent-pole frames of Fulani tents and made permanent for an aristocracy that had recently stopped being nomadic. Mikhaila is said to have worked without drawings, improvising on site, and to have left his handprint above one of the arches. The mosque has stood for nearly two centuries and remains in use, though a section of roof collapsed in 2023.",
      es: 'La mezquita del viernes de Zaria es la obra maestra superviviente de la construcción hausa en tierra y el monumento más antiguo de África Occidental que puede atribuirse con seguridad a una persona con nombre. Se levantó a mediados de la década de 1830, durante el reinado de Sarkin Zazzau Abd al-Karim, por obra del maestro constructor Mallam Mikhaila, conocido por el título de Babban Gwani, «el gran experto». Su interior es el argumento: bóvedas de barro que cubren salas amplias sobre nervios arqueados de palmera azara, una idea estructural tomada de los armazones de varas curvadas de las tiendas fulani y hecha permanente para una aristocracia que acababa de dejar de ser nómada. Se dice que Mikhaila trabajaba sin planos, improvisando en obra, y que dejó la huella de su mano sobre uno de los arcos. La mezquita lleva en pie casi dos siglos y sigue en uso, aunque en 2023 se derrumbó parte de la cubierta.',
      it: "La moschea del venerdì di Zaria è il capolavoro superstite della costruzione hausa in terra cruda e il più antico monumento dell'Africa occidentale attribuibile con sicurezza a una persona con un nome. Fu eretta a metà degli anni Trenta dell'Ottocento, durante il regno di Sarkin Zazzau Abd al-Karim, dal capomastro Mallam Mikhaila, noto con il titolo di Babban Gwani, «il grande esperto». L'interno è l'argomento: volte in terra che coprono ambienti ampi su nervature arcuate di palma azara, un'idea strutturale ripresa dai telai a pertiche curvate delle tende fulani e resa permanente per un'aristocrazia che aveva appena smesso di essere nomade. Si racconta che Mikhaila lavorasse senza disegni, improvvisando in cantiere, e che abbia lasciato l'impronta della mano sopra uno degli archi. La moschea è in piedi da quasi due secoli ed è tuttora in uso, benché nel 2023 una parte della copertura sia crollata.",
    },
    context: {
      body: {
        en: "The mosque was built with enslaved labour. Accounts of Mikhaila's practice describe a workforce of roughly a hundred labourers, most of them enslaved, who gathered and prepared mud and thatch by day while he built at night. He worked for the emirates established after the Sokoto jihad, which sought monuments that would express the new Islamic order, and slavery was integral to their economy. Mikhaila's own end came from the same patronage relation: the Emir of Birnin Gwari commissioned a mosque from him meant to surpass the one at Zaria, and had him executed so that it could never be equalled. The account is transmitted in the Hausa building tradition and recorded in the modern literature on his career; it is not independently documented, and is reported here as the tradition reports it.",
        es: 'La mezquita se construyó con mano de obra esclavizada. Los relatos sobre el modo de trabajar de Mikhaila describen una cuadrilla de un centenar de peones, en su mayoría esclavizados, que de día reunían y preparaban el barro y la paja mientras él construía de noche. Trabajaba para los emiratos surgidos tras la yihad de Sokoto, que buscaban monumentos capaces de expresar el nuevo orden islámico, y la esclavitud era parte esencial de su economía. El propio final de Mikhaila procede de esa misma relación de mecenazgo: el emir de Birnin Gwari le encargó una mezquita destinada a superar la de Zaria y lo hizo ejecutar para que nunca pudiera ser igualada. El relato se transmite en la tradición constructiva hausa y está recogido en la literatura moderna sobre su carrera; no está documentado de forma independiente y aquí se refiere tal como la tradición lo refiere.',
        it: "La moschea fu costruita con manodopera schiavizzata. I racconti sul modo di lavorare di Mikhaila descrivono una squadra di un centinaio di operai, in maggioranza schiavizzati, che di giorno raccoglievano e preparavano terra e paglia mentre lui costruiva di notte. Lavorava per gli emirati sorti dopo la jihad di Sokoto, che cercavano monumenti capaci di esprimere il nuovo ordine islamico, e la schiavitù era parte integrante della loro economia. La fine di Mikhaila nasce dalla stessa relazione di committenza: l'emiro di Birnin Gwari gli commissionò una moschea destinata a superare quella di Zaria e lo fece giustiziare perché non potesse mai essere eguagliata. Il racconto è trasmesso dalla tradizione costruttiva hausa ed è registrato nella letteratura moderna sulla sua carriera; non è documentato in modo indipendente e viene qui riferito così come la tradizione lo riferisce.",
      },
      sources: [
        {
          kind: 'wikipedia',
          url: 'https://en.wikipedia.org/wiki/Babban_Gwani',
          title: 'Babban Gwani',
          license: 'CC BY-SA 4.0',
        },
      ],
    },
    sources: [
      {
        kind: 'wikipedia',
        url: 'https://en.wikipedia.org/wiki/Babban_Gwani',
        title: 'Babban Gwani',
        license: 'CC BY-SA 4.0',
      },
      {
        kind: 'wikidata',
        url: 'https://www.wikidata.org/wiki/Q122545893',
        title: 'Babban Gwani (Q122545893)',
        license: null,
      },
      {
        kind: 'publication',
        url: 'https://dailytrust.com/babban-gwani-life-legacy-of-zarias-legendary-builder/',
        title: "Babban Gwani: Life, legacy of Zaria's legendary builder — Daily Trust",
        license: null,
      },
      {
        kind: 'publication',
        url: 'https://doi.org/10.5220/0007439804340441',
        title: 'A Study on the Building Materials and Construction Technology of Traditional Hausa Architecture in Nigeria — Zhang & Yusuf, Proceedings of the International Workshop on Materials, Chemistry and Engineering (2018)',
        license: null,
      },
    ],
    tier: 'canon',
  },
  {
    id: 'shitta-bey-mosque-lagos',
    wikidataId: 'Q48791511',
    name: {
      en: 'Shitta-Bey Mosque',
      es: 'Mezquita Shitta-Bey',
      it: 'Moschea Shitta-Bey',
    },
    architectId: 'joao-baptista-da-costa-lagos',
    location: { city: 'Lagos', countryCode: 'NG', lat: 6.457709, lon: 3.3867 },
    inception: 1891,
    completed: 1894,
    demolished: null,
    typology: 'sacral',
    materials: ['brick'],
    structure: {
      en: 'Load-bearing brick walls rendered and moulded in lime stucco, with a symmetrical two-storey street front, balustraded galleries and glazed tile-work set into the facade.',
      es: 'Muros portantes de ladrillo revocados y moldeados en estuco de cal, con un frente a la calle simétrico de dos plantas, galerías con balaustrada y azulejos vidriados embutidos en la fachada.',
      it: 'Muri portanti in laterizio intonacati e modanati in stucco di calce, con un fronte stradale simmetrico a due piani, gallerie balaustrate e piastrelle invetriate incassate nella facciata.',
    },
    program: {
      en: 'A congregational mosque on Lagos Island paid for privately by the Sierra Leonean-born merchant Mohammed Shitta for the Muslim community of the city.',
      es: 'Una mezquita congregacional en la isla de Lagos costeada de forma privada por el comerciante Mohammed Shitta, nacido en Sierra Leona, para la comunidad musulmana de la ciudad.',
      it: "Una moschea congregazionale sull'isola di Lagos finanziata privatamente dal mercante Mohammed Shitta, nato in Sierra Leone, per la comunità musulmana della città.",
    },
    heritage: 'national',
    currentUse: {
      en: 'Working mosque and religious learning centre; declared a national monument by the National Commission for Museums and Monuments in 2013.',
      es: 'Mezquita en uso y centro de enseñanza religiosa; declarada monumento nacional por la Comisión Nacional de Museos y Monumentos en 2013.',
      it: 'Moschea in uso e centro di insegnamento religioso; dichiarata monumento nazionale dalla Commissione nazionale per i musei e i monumenti nel 2013.',
    },
    detailRect: { x: 0.28, y: 0.36, w: 0.38, h: 0.24 },
    image: {
      commonsFile: 'File:Shitta Bey Mosque, Lagos Island, Lagos.jpg',
      photographer: 'Beendy234',
      license: 'CC BY-SA 4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Shitta_Bey_Mosque,_Lagos_Island,_Lagos.jpg',
      width: 1200,
      height: 1600,
    },
    dossier: {
      en: "Construction began in 1891 on Martins Street, Lagos Island, financed by the merchant Mohammed Shitta and directed by João Baptista da Costa, a Brazilian returnee builder, with a local builder named Sanusi Aka. The result is the clearest surviving statement of the Afro-Brazilian manner in Lagos: a symmetrical stuccoed front with moulded pilasters, balustrades and imported glazed tiles, a Salvador church facade reasoned into a mosque. The opening on 4 July 1894 was a set-piece of late-nineteenth-century Lagos: the colonial governor Sir Gilbert Carter presided, Oba Oyekan I attended alongside the pan-Africanist Edward Wilmot Blyden and the English convert Abdullah Quilliam, who represented Sultan Abdul Hamid II. The Sultan made Shitta a Bey of the Ottoman Order of the Medjidie, and the compound name Shitta-Bey has attached to the building ever since.",
      es: 'Las obras comenzaron en 1891 en la calle Martins, isla de Lagos, financiadas por el comerciante Mohammed Shitta y dirigidas por João Baptista da Costa, constructor retornado de Brasil, con la ayuda de un constructor local llamado Sanusi Aka. El resultado es la muestra más nítida que se conserva de la manera afrobrasileña en Lagos: un frente simétrico estucado con pilastras moldeadas, balaustradas y azulejos vidriados importados, una fachada de iglesia de Salvador razonada como mezquita. La inauguración, el 4 de julio de 1894, fue un acontecimiento de la Lagos finisecular: presidió el gobernador colonial sir Gilbert Carter, y asistieron el oba Oyekan I junto al panafricanista Edward Wilmot Blyden y el converso inglés Abdullah Quilliam, que representaba al sultán Abdul Hamid II. El sultán nombró a Shitta bey de la Orden otomana del Medjidie, y desde entonces el nombre compuesto Shitta-Bey quedó unido al edificio.',
      it: "I lavori iniziarono nel 1891 in Martins Street, sull'isola di Lagos, finanziati dal mercante Mohammed Shitta e diretti da João Baptista da Costa, costruttore rientrato dal Brasile, con l'aiuto di un costruttore locale di nome Sanusi Aka. Il risultato è la testimonianza più nitida rimasta della maniera afro-brasiliana a Lagos: un fronte simmetrico intonacato con lesene modanate, balaustre e piastrelle invetriate d'importazione, una facciata di chiesa di Salvador ripensata come moschea. L'inaugurazione, il 4 luglio 1894, fu un evento della Lagos di fine secolo: presiedette il governatore coloniale sir Gilbert Carter, e vi presero parte l'oba Oyekan I, il panafricanista Edward Wilmot Blyden e il convertito inglese Abdullah Quilliam, che rappresentava il sultano Abdul Hamid II. Il sultano nominò Shitta bey dell'Ordine ottomano del Medjidie, e da allora il nome composto Shitta-Bey è rimasto legato all'edificio.",
    },
    context: {
      body: {
        en: "The Brazilian manner reached Lagos with the Agudá — formerly enslaved people from Brazil and their descendants who returned to the Bight of Benin across the nineteenth century, many after the 1835 Malê revolt in Salvador and the deportations that followed it. They came back carrying trades they had been forced to learn in Bahia and Pernambuco: bricklaying, carpentry, lime stucco, tile-setting. Those trades built much of nineteenth-century Lagos, and the Shitta-Bey Mosque is their most complete surviving work. The building therefore records two things at once: an architectural language carried back across the Atlantic by people who had been shipped the other way, and the patronage of a Muslim merchant elite operating inside a British colonial city — the governor presided at the opening, and a delegation from the Ottoman Sultan conferred a title. Almost nothing is recorded of da Costa's own life.",
        es: 'La manera brasileña llegó a Lagos con los agudá: personas antes esclavizadas en Brasil y sus descendientes, que a lo largo del siglo XIX regresaron a la bahía de Benín, muchos tras la revuelta malê de 1835 en Salvador y las deportaciones que la siguieron. Volvieron con los oficios que se habían visto obligados a aprender en Bahía y Pernambuco: albañilería, carpintería, estuco de cal, colocación de azulejos. Esos oficios construyeron buena parte de la Lagos decimonónica, y la mezquita Shitta-Bey es su obra conservada más completa. El edificio registra por tanto dos cosas a la vez: un lenguaje arquitectónico traído de vuelta a través del Atlántico por quienes habían sido embarcados en sentido contrario, y el mecenazgo de una élite mercantil musulmana que operaba dentro de una ciudad colonial británica —el gobernador presidió la inauguración y una delegación del sultán otomano concedió un título—. De la vida de da Costa no se conserva casi nada.',
        it: "La maniera brasiliana giunse a Lagos con gli agudá: persone già schiavizzate in Brasile e loro discendenti, tornati nel corso dell'Ottocento al golfo del Benin, molti dopo la rivolta malê del 1835 a Salvador e le deportazioni che ne seguirono. Rientrarono portando i mestieri che erano stati costretti ad apprendere a Bahia e nel Pernambuco: muratura, carpenteria, stucco di calce, posa di piastrelle. Quei mestieri costruirono buona parte della Lagos ottocentesca, e la moschea Shitta-Bey ne è l'opera superstite più completa. L'edificio registra dunque due cose insieme: un linguaggio architettonico riportato attraverso l'Atlantico da chi era stato imbarcato nella direzione opposta, e il mecenatismo di un'élite mercantile musulmana che operava dentro una città coloniale britannica — il governatore presiedette l'inaugurazione e una delegazione del sultano ottomano conferì un titolo. Della vita di da Costa non è rimasto quasi nulla.",
      },
      sources: [
        {
          kind: 'wikipedia',
          url: 'https://en.wikipedia.org/wiki/Shitta-Bey_Mosque',
          title: 'Shitta-Bey Mosque',
          license: 'CC BY-SA 4.0',
        },
        {
          kind: 'publication',
          url: 'https://doi.org/10.1163/157006012X627904',
          title: "Ostien, P. & Makinde, A.-F. 'K. (2012), 'Legal Pluralism in Colonial Lagos: The 1894 Petition of the Lagos Muslims to their British Colonial Masters', Die Welt des Islams 52(1), 51–68",
          license: null,
        },
      ],
    },
    sources: [
      {
        kind: 'wikipedia',
        url: 'https://en.wikipedia.org/wiki/Shitta-Bey_Mosque',
        title: 'Shitta-Bey Mosque',
        license: 'CC BY-SA 4.0',
      },
      {
        kind: 'wikidata',
        url: 'https://www.wikidata.org/wiki/Q48791511',
        title: 'Shitta-Bey Mosque (Q48791511)',
        license: null,
      },
    ],
    tier: 'deep',
  },
  {
    id: 'great-mosque-of-djenne',
    wikidataId: 'Q683632',
    name: {
      en: 'Great Mosque of Djenné',
      es: 'Gran Mezquita de Djenné',
      it: 'Grande Moschea di Djenné',
    },
    architectId: 'ismaila-traore',
    location: { city: 'Djenné', countryCode: 'ML', lat: 13.905278, lon: -4.555556 },
    inception: 1906,
    completed: 1907,
    demolished: null,
    typology: 'sacral',
    materials: ['earth', 'timber'],
    structure: {
      en: 'Sun-dried mud brick laid in mortar of the same earth and rendered in banco, raised on a plinth against the Bani flood, with palm-wood toron projecting from every face and three towers ranked across the qibla wall.',
      es: 'Adobe secado al sol asentado con mortero de la misma tierra y revocado con banco, alzado sobre un podio frente a las crecidas del Bani, con toron de madera de palmera que sobresalen de todos los paramentos y tres torres alineadas en el muro de la quibla.',
      it: 'Mattoni crudi essiccati al sole posati con malta della stessa terra e intonacati in banco, elevati su un basamento contro le piene del Bani, con toron di legno di palma sporgenti da ogni paramento e tre torri allineate sul muro della qibla.',
    },
    program: {
      en: 'The congregational mosque of Djenné, rebuilt on the site of the medieval mosque as the centre of the town and the object of its annual communal replastering.',
      es: 'La mezquita congregacional de Djenné, reconstruida en el emplazamiento de la mezquita medieval como centro de la ciudad y objeto de su revoco comunitario anual.',
      it: 'La moschea congregazionale di Djenné, ricostruita sul sito della moschea medievale come centro della città e oggetto della sua rintonacatura comunitaria annuale.',
    },
    heritage: 'unesco',
    currentUse: {
      en: 'Working mosque and the focus of the annual crépissage, when the town replasters the building by hand; inscribed with the Old Towns of Djenné as a World Heritage Site in 1988.',
      es: 'Mezquita en uso y centro del crépissage anual, cuando la ciudad revoca a mano el edificio; inscrita junto con las ciudades antiguas de Djenné como Patrimonio Mundial en 1988.',
      it: 'Moschea in uso e fulcro del crépissage annuale, quando la città rintonaca a mano l’edificio; iscritta con le città antiche di Djenné nel Patrimonio Mondiale nel 1988.',
    },
    detailRect: { x: 0.34, y: 0.34, w: 0.32, h: 0.32 },
    image: {
      commonsFile: 'File:Djenne great mud mosque.jpg',
      photographer: 'Ruud Zwart',
      license: 'CC BY-SA 3.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Djenne_great_mud_mosque.jpg',
      width: 1600,
      height: 1064,
    },
    dossier: {
      en: "A mosque has stood on this site since perhaps the thirteenth century, but the building everyone photographs is barely older than the aeroplane. By the time René Caillié reached Djenné in 1828 the medieval mosque was a swallow-filled ruin; Seku Amadu built a plainer replacement nearby and let the old one fall. In 1906 the town resolved to rebuild, and the work was completed in 1907 under Ismaila Traoré, head of the barey ton, Djenné's hereditary masons' guild. What is almost certainly new in his design is the symmetrical rank of three towers across the qibla wall, the silhouette that has since stood for West African architecture worldwide. The mosque is the largest mud-brick building on earth, and it survives only because the whole town replasters it every year.",
      es: 'En este emplazamiento hay una mezquita desde quizá el siglo XIII, pero el edificio que todo el mundo fotografía apenas es más antiguo que el avión. Cuando René Caillié llegó a Djenné en 1828, la mezquita medieval era una ruina llena de golondrinas; Seku Amadu levantó cerca un sustituto más austero y dejó caer la vieja. En 1906 la ciudad decidió reconstruirla, y la obra se terminó en 1907 bajo la dirección de Ismaila Traoré, jefe del barey ton, el gremio hereditario de albañiles de Djenné. Lo que casi con certeza es nuevo en su proyecto es la hilera simétrica de tres torres en el muro de la quibla, la silueta que desde entonces representa en el mundo entero la arquitectura de África Occidental. La mezquita es el mayor edificio de adobe de la Tierra, y sobrevive únicamente porque la ciudad entera la revoca cada año.',
      it: "Una moschea sorge su questo sito forse dal XIII secolo, ma l'edificio che tutti fotografano è di poco più antico dell'aeroplano. Quando René Caillié raggiunse Djenné nel 1828, la moschea medievale era una rovina piena di rondini; Seku Amadu costruì poco lontano un sostituto più spoglio e lasciò cadere la vecchia. Nel 1906 la città decise di ricostruirla, e i lavori si conclusero nel 1907 sotto la direzione di Ismaila Traoré, capo del barey ton, la corporazione ereditaria dei muratori di Djenné. Ciò che quasi certamente è nuovo nel suo progetto è la fila simmetrica di tre torri sul muro della qibla, la sagoma che da allora rappresenta nel mondo l'architettura dell'Africa occidentale. La moschea è il più grande edificio in mattoni crudi della Terra e sopravvive soltanto perché l'intera città la rintonaca ogni anno.",
    },
    context: {
      body: {
        en: "The 1907 reconstruction was carried out using forced labour, in a town that the French army under Louis Archinard had captured in 1893. Who designed it has been argued about ever since. The French journalist Félix Dubois, who had recorded the medieval ruin in 1897, returned in 1910 and was appalled, insisting the colonial administration was responsible for a building he compared to a cross between a hedgehog and a church organ. Michel Leiris, travelling through in 1931, likewise reported the new mosque as European work, and added that residents refused to replaster it until threatened with prison. Against this, Jean-Louis Bourgeois has argued that French involvement extended at most to some internal arches, and that the design is substantially African, executed by the masons' guild in its own techniques. Present scholarship follows Bourgeois, while recording the coercion under which the work was done.",
        es: 'La reconstrucción de 1907 se llevó a cabo con trabajo forzado, en una ciudad que el ejército francés de Louis Archinard había tomado en 1893. Desde entonces se discute quién la proyectó. El periodista francés Félix Dubois, que había documentado la ruina medieval en 1897, volvió en 1910 y quedó horrorizado: insistió en que la administración colonial era responsable de un edificio que comparó con un cruce entre un erizo y un órgano de iglesia. Michel Leiris, de paso en 1931, informó igualmente de que la nueva mezquita era obra europea, y añadió que los vecinos se negaron a revocarla hasta que se los amenazó con la cárcel. Frente a ello, Jean-Louis Bourgeois ha sostenido que la intervención francesa se limitó como mucho a algunos arcos interiores y que el diseño es sustancialmente africano, ejecutado por el gremio de albañiles con sus propias técnicas. La investigación actual sigue a Bourgeois, sin dejar de consignar la coacción con que se hizo la obra.',
        it: "La ricostruzione del 1907 fu realizzata con lavoro forzato, in una città che l'esercito francese di Louis Archinard aveva conquistato nel 1893. Da allora si discute su chi l'abbia progettata. Il giornalista francese Félix Dubois, che aveva documentato la rovina medievale nel 1897, tornò nel 1910 e ne fu inorridito: sostenne che l'amministrazione coloniale era responsabile di un edificio che paragonò a un incrocio tra un riccio e un organo da chiesa. Michel Leiris, di passaggio nel 1931, riferì analogamente che la nuova moschea era opera europea, e aggiunse che gli abitanti si rifiutarono di rintonacarla finché non furono minacciati di carcere. Contro questa lettura, Jean-Louis Bourgeois ha sostenuto che il coinvolgimento francese si limitò al più ad alcuni archi interni e che il progetto è sostanzialmente africano, eseguito dalla corporazione dei muratori con le proprie tecniche. Gli studi attuali seguono Bourgeois, pur registrando la coercizione con cui il lavoro fu svolto.",
      },
      sources: [
        {
          kind: 'wikipedia',
          url: 'https://en.wikipedia.org/wiki/Great_Mosque_of_Djenn%C3%A9',
          title: 'Great Mosque of Djenné',
          license: 'CC BY-SA 4.0',
        },
        {
          kind: 'institution',
          url: 'https://whc.unesco.org/en/list/116/',
          title: 'Old Towns of Djenné — UNESCO World Heritage Centre',
          license: null,
        },
      ],
    },
    sources: [
      {
        kind: 'wikipedia',
        url: 'https://en.wikipedia.org/wiki/Great_Mosque_of_Djenn%C3%A9',
        title: 'Great Mosque of Djenné',
        license: 'CC BY-SA 4.0',
      },
      {
        kind: 'wikidata',
        url: 'https://www.wikidata.org/wiki/Q683632',
        title: 'Great Mosque of Djenné (Q683632)',
        license: null,
      },
    ],
    tier: 'canon',
  },
  {
    id: 'kenneth-dike-library-ibadan',
    wikidataId: 'Q84493472',
    name: {
      en: 'Kenneth Dike Library, University of Ibadan',
      es: 'Biblioteca Kenneth Dike, Universidad de Ibadán',
      it: 'Biblioteca Kenneth Dike, Università di Ibadan',
    },
    architectId: 'jane-drew',
    coArchitects: ['maxwell-fry'],
    location: { city: 'Ibadan', countryCode: 'NG', lat: 7.4470098, lon: 3.8960989 },
    inception: 1948,
    completed: 1954,
    demolished: null,
    typology: 'educational',
    materials: ['concrete'],
    structure: {
      en: 'A reinforced-concrete frame with book stacks in the core and reading galleries on each flank, the envelope opened up by louvred screens, deep overhangs and shuttered openings so the interior is cross-ventilated rather than sealed.',
      es: 'Estructura de hormigón armado con los depósitos de libros en el núcleo y galerías de lectura a cada lado; el cerramiento se abre mediante celosías de lamas, aleros profundos y vanos con contraventanas, de modo que el interior se ventila de forma cruzada en vez de sellarse.',
      it: 'Telaio in cemento armato con i depositi librari nel nucleo e gallerie di lettura sui due lati; l’involucro è aperto da schermi a lamelle, sporti profondi e aperture con persiane, così che l’interno sia ventilato in modo incrociato anziché sigillato.',
    },
    program: {
      en: 'The main library of University College Ibadan, the first degree-awarding institution in Nigeria, founded in 1948 as a branch of the University of London.',
      es: 'La biblioteca principal del University College de Ibadán, la primera institución de Nigeria capaz de otorgar títulos, fundada en 1948 como filial de la Universidad de Londres.',
      it: "La biblioteca principale dello University College di Ibadan, la prima istituzione della Nigeria abilitata a conferire titoli, fondata nel 1948 come sede della University of London.",
    },
    heritage: null,
    currentUse: {
      en: 'Main university library, named after Kenneth Dike, the first Nigerian vice-chancellor of the university.',
      es: 'Biblioteca universitaria principal, con el nombre de Kenneth Dike, primer rector nigeriano de la universidad.',
      it: 'Biblioteca universitaria principale, intitolata a Kenneth Dike, primo rettore nigeriano dell’ateneo.',
    },
    detailRect: { x: 0.34, y: 0.32, w: 0.32, h: 0.34 },
    image: {
      commonsFile: 'File:Kenneth Dike Library, University of Ibadan, Ibadan, Nigeria.jpg',
      photographer: 'Temilolub.52021',
      license: 'CC BY-SA 4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Kenneth_Dike_Library,_University_of_Ibadan,_Ibadan,_Nigeria.jpg',
      width: 1600,
      height: 1064,
    },
    dossier: {
      en: "The library was commissioned on 17 November 1954 as the centrepiece of a campus laid out from 1948 by Maxwell Fry and Jane Drew. It is the clearest built demonstration of what they meant by Tropical Modernism. Where a European library of the period would seal its stacks behind glass, here the concrete frame is deliberately perforated: louvred screens and deep shading keep direct sun off the readers, cross-ventilation moves air through the galleries, and interior shutters protect the books from storm-driven rain rather than from air-conditioning failure. The plan puts access corridors along each bank of shelving. Drew and Fry had arrived in West Africa in 1946 on colonial-government appointments and worked out this vocabulary across a decade of Gold Coast and Nigerian schools before it reached Ibadan; the library is where it is stated at institutional scale.",
      es: 'La biblioteca se inauguró el 17 de noviembre de 1954 como pieza central de un campus trazado desde 1948 por Maxwell Fry y Jane Drew. Es la demostración construida más clara de lo que entendían por modernismo tropical. Donde una biblioteca europea de la época habría sellado sus depósitos tras el vidrio, aquí la estructura de hormigón se perfora a conciencia: las celosías de lamas y los grandes voladizos mantienen el sol directo lejos de los lectores, la ventilación cruzada mueve el aire por las galerías y las contraventanas interiores protegen los libros de la lluvia batida por el viento, no de una avería del aire acondicionado. La planta dispone corredores de acceso a lo largo de cada cuerpo de estanterías. Drew y Fry habían llegado a África Occidental en 1946 con nombramientos del gobierno colonial y afinaron este vocabulario durante una década de escuelas en Costa de Oro y Nigeria antes de que llegara a Ibadán; en la biblioteca se enuncia a escala institucional.',
      it: "La biblioteca fu inaugurata il 17 novembre 1954 come fulcro di un campus tracciato dal 1948 da Maxwell Fry e Jane Drew. È la dimostrazione costruita più chiara di ciò che intendevano per modernismo tropicale. Dove una biblioteca europea dell'epoca avrebbe sigillato i depositi dietro il vetro, qui il telaio in cemento è deliberatamente perforato: schermi a lamelle e ombreggiature profonde tengono il sole diretto lontano dai lettori, la ventilazione incrociata muove l'aria nelle gallerie e le persiane interne proteggono i libri dalla pioggia battente, non da un guasto dell'aria condizionata. La pianta dispone corridoi di accesso lungo ogni corpo di scaffalature. Drew e Fry erano giunti nell'Africa occidentale nel 1946 con incarichi del governo coloniale e misero a punto questo vocabolario in un decennio di scuole nella Costa d'Oro e in Nigeria prima che arrivasse a Ibadan; nella biblioteca è enunciato su scala istituzionale.",
    },
    context: {
      body: {
        en: "University College Ibadan was a colonial institution by design. It was created on the recommendation of the Asquith and Elliot Commissions on higher education in the British colonies, which proposed two university colleges affiliated to the University of London, one in the Gold Coast and one in Nigeria; London supervised the syllabus and awarded the degrees until 1967. Nigerian nationalists had pressed for a degree-awarding institution because the existing Yaba Higher College, founded in 1932, offered only vocational and teacher training to Africans. Fry and Drew were appointed through the same colonial apparatus, and their West African practice from 1946 was built on government commissions. The buildings are now read two ways at once: as a genuine climatic architecture worked out with local craft, and as the physical form of late colonial policy. Nigeria took the institution over in 1962.",
        es: 'El University College de Ibadán fue por diseño una institución colonial. Se creó por recomendación de las comisiones Asquith y Elliot sobre educación superior en las colonias británicas, que propusieron dos university colleges vinculados a la Universidad de Londres, uno en Costa de Oro y otro en Nigeria; Londres supervisó los planes de estudio y otorgó los títulos hasta 1967. Los nacionalistas nigerianos habían presionado por una institución capaz de dar títulos porque el Yaba Higher College existente, fundado en 1932, solo ofrecía a los africanos formación profesional y magisterio. Fry y Drew fueron nombrados por ese mismo aparato colonial, y su práctica en África Occidental desde 1946 se sostuvo en encargos gubernamentales. Los edificios se leen hoy de dos maneras a la vez: como una arquitectura climática auténtica elaborada con oficios locales y como la forma física de la política colonial tardía. Nigeria asumió la institución en 1962.',
        it: "Lo University College di Ibadan fu per progetto un'istituzione coloniale. Nacque su raccomandazione delle commissioni Asquith ed Elliot sull'istruzione superiore nelle colonie britanniche, che proposero due university college affiliati alla University of London, uno nella Costa d'Oro e uno in Nigeria; Londra ne supervisionò i programmi e ne conferì i titoli fino al 1967. I nazionalisti nigeriani avevano premuto per un'istituzione capace di rilasciare titoli perché l'esistente Yaba Higher College, fondato nel 1932, offriva agli africani solo formazione professionale e magistrale. Fry e Drew furono nominati dallo stesso apparato coloniale, e il loro studio in Africa occidentale dal 1946 si resse su commesse governative. Gli edifici oggi si leggono in due modi insieme: come un'autentica architettura climatica messa a punto con le maestranze locali e come la forma fisica della politica coloniale tarda. La Nigeria assunse l'istituzione nel 1962.",
      },
      sources: [
        {
          kind: 'wikipedia',
          url: 'https://en.wikipedia.org/wiki/University_of_Ibadan',
          title: 'University of Ibadan',
          license: 'CC BY-SA 4.0',
        },
        {
          kind: 'institution',
          url: 'https://www.vam.ac.uk/blog/museum-life/tropical-modernism-architecture-and-power-in-west-africa',
          title: 'Tropical Modernism: Architecture and power in West Africa — Victoria and Albert Museum',
          license: null,
        },
      ],
    },
    sources: [
      {
        kind: 'wikidata',
        url: 'https://www.wikidata.org/wiki/Q84493472',
        title: 'Kenneth Dike Library, University of Ibadan (Q84493472)',
        license: null,
      },
      {
        kind: 'wikipedia',
        url: 'https://en.wikipedia.org/wiki/University_of_Ibadan',
        title: 'University of Ibadan',
        license: 'CC BY-SA 4.0',
      },
      {
        kind: 'institution',
        url: 'https://c20society.org.uk/building-of-the-month/university-of-ibadan-nigeria',
        title: 'Building of the Month: University of Ibadan, Nigeria — The Twentieth Century Society',
        license: null,
      },
    ],
    tier: 'deep',
  },
  {
    id: 'dominican-chapel-ibadan',
    wikidataId: null,
    name: {
      en: 'Dominican Chapel, Ibadan',
      es: 'Capilla dominica de Ibadán',
      it: 'Cappella domenicana di Ibadan',
    },
    architectId: 'demas-nwoko',
    location: { city: 'Ibadan', countryCode: 'NG', lat: 7.43338, lon: 3.901808 },
    inception: 1970,
    completed: 1975,
    demolished: null,
    typology: 'sacral',
    materials: ['concrete'],
    structure: {
      en: 'A cast sandcrete frame of Nwoko\'s own mix — cement, sand and pebble-filled lateritic soil — carrying a top-lit hall behind a sculpted external colonnade, with a bell tower modelled as a single standing figure.',
      es: 'Una estructura de hormigón de arena de mezcla propia de Nwoko —cemento, arena y tierra laterítica con guijarros— que sostiene una sala con luz cenital tras una columnata exterior esculpida, con un campanario modelado como una única figura en pie.',
      it: 'Una struttura in sandcrete gettato di mescola propria di Nwoko — cemento, sabbia e terra lateritica con ciottoli — che regge una sala illuminata dall’alto dietro un colonnato esterno scolpito, con un campanile modellato come un’unica figura stante.',
    },
    program: {
      en: 'The chapel and community house of the Dominican Institute in Ibadan, a house of study for the Order of Preachers in Nigeria.',
      es: 'La capilla y casa comunitaria del Instituto Dominico de Ibadán, casa de estudios de la Orden de Predicadores en Nigeria.',
      it: "La cappella e la casa comunitaria dell'Istituto domenicano di Ibadan, casa di studio dell'Ordine dei Predicatori in Nigeria.",
    },
    heritage: null,
    currentUse: {
      en: 'Chapel of the Dominican Institute, in continuous religious use.',
      es: 'Capilla del Instituto Dominico, en uso religioso continuado.',
      it: 'Cappella dell’Istituto domenicano, in uso religioso continuativo.',
    },
    detailRect: { x: 0.3, y: 0.34, w: 0.32, h: 0.34 },
    image: {
      commonsFile: 'File:Dominican Chapel.jpg',
      photographer: 'Andrew Moore',
      license: 'CC BY-SA 2.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Dominican_Chapel.jpg',
      width: 1600,
      height: 1067,
    },
    dossier: {
      en: "Demas Nwoko designed and built the Dominican house and chapel at Ibadan between 1970 and 1975; the community was installed in March 1975. It is the building on which his reputation rests, and it argues a position: that a Nigerian modern architecture had to be made from Nigerian ground and Nigerian craft rather than imported as a style. The walls are cast in a sandcrete he devised himself, cement and sand loaded with pebble-filled lateritic soil, which sets the ochre of the local earth permanently into the surface and needs no paint. Outside, a line of columns is handled as sculpture — Nwoko trained as an artist, not an architect — and the tower reads as a standing figure. Inside, light is brought down from above onto a hall shaped for a congregation rather than a nave.",
      es: 'Demas Nwoko proyectó y construyó la casa y la capilla dominicas de Ibadán entre 1970 y 1975; la comunidad se instaló en marzo de 1975. Es el edificio en el que descansa su prestigio, y defiende una posición: que una arquitectura moderna nigeriana debía hacerse con el suelo y los oficios nigerianos y no importarse como estilo. Los muros están fundidos en un hormigón de arena de invención propia, cemento y arena cargados de tierra laterítica con guijarros, que fija de manera permanente el ocre de la tierra local en la superficie y no necesita pintura. Fuera, una hilera de columnas se trata como escultura —Nwoko se formó como artista, no como arquitecto— y la torre se lee como una figura en pie. Dentro, la luz baja desde arriba sobre una sala conformada para una asamblea más que para una nave.',
      it: "Demas Nwoko progettò e costruì la casa e la cappella domenicane di Ibadan tra il 1970 e il 1975; la comunità vi si insediò nel marzo 1975. È l'edificio su cui poggia la sua fama, e sostiene una tesi: che un'architettura moderna nigeriana dovesse essere fatta con il suolo e le maestranze nigeriane anziché importata come stile. I muri sono gettati in un sandcrete di sua invenzione, cemento e sabbia caricati di terra lateritica con ciottoli, che fissa in modo permanente l'ocra della terra locale nella superficie e non richiede vernice. All'esterno, una fila di colonne è trattata come scultura — Nwoko si formò come artista, non come architetto — e la torre si legge come una figura stante. All'interno, la luce scende dall'alto su una sala conformata per un'assemblea più che per una navata.",
    },
    context: null,
    sources: [
      {
        kind: 'wikipedia',
        url: 'https://en.wikipedia.org/wiki/Demas_Nwoko',
        title: 'Demas Nwoko',
        license: 'CC BY-SA 4.0',
      },
      {
        kind: 'institution',
        url: 'https://www.archnet.org/sites/4845',
        title: 'Dominican Chapel and Multi-Purpose Hall, Ibadan — Archnet, Aga Khan Documentation Center, MIT',
        license: null,
      },
      {
        kind: 'publication',
        url: 'https://www.wallpaper.com/architecture/architecture-artist-designer-demas-nwoko-nigeria',
        title: 'The pioneering architecture of Nigerian artist-designer Demas Nwoko — Wallpaper*',
        license: null,
      },
    ],
    tier: 'canon',
  },
  {
    id: 'oba-akenzua-cultural-centre',
    wikidataId: 'Q110925512',
    name: {
      en: 'Oba Akenzua II Cultural Centre',
      es: 'Centro Cultural Oba Akenzua II',
      it: 'Centro culturale Oba Akenzua II',
    },
    architectId: 'demas-nwoko',
    location: { city: 'Benin City', countryCode: 'NG', lat: 6.3333, lon: 5.6167 },
    inception: 1972,
    completed: 1993,
    demolished: null,
    typology: 'cultural',
    materials: ['concrete'],
    structure: {
      en: 'A semicircular auditorium block whose curve follows the rake of the seating, built in cast sandcrete banded with continuous horizontal ridges and coloured by the pebble-filled lateritic soil in the mix.',
      es: 'Un bloque de auditorio semicircular cuya curva sigue la pendiente del graderío, construido en hormigón de arena fundido con franjas horizontales continuas y coloreado por la tierra laterítica con guijarros de la mezcla.',
      it: 'Un corpo auditorio semicircolare la cui curva segue la pendenza della gradinata, costruito in sandcrete gettato a fasce orizzontali continue e colorato dalla terra lateritica con ciottoli presente nella mescola.',
    },
    program: {
      en: 'A public performing-arts and exhibition building for Benin City, designed in 1972 as a University of Benin theatre and completed as a government-funded civic centre.',
      es: 'Un edificio público de artes escénicas y exposiciones para la ciudad de Benín, proyectado en 1972 como teatro de la Universidad de Benín y terminado como centro cívico financiado por el gobierno.',
      it: "Un edificio pubblico per lo spettacolo e le mostre per Benin City, progettato nel 1972 come teatro dell'Università del Benin e completato come centro civico finanziato dal governo.",
    },
    heritage: null,
    currentUse: {
      en: 'Civic performing-arts and exhibition centre.',
      es: 'Centro cívico de artes escénicas y exposiciones.',
      it: 'Centro civico per lo spettacolo e le mostre.',
    },
    detailRect: { x: 0.34, y: 0.34, w: 0.32, h: 0.32 },
    image: {
      commonsFile: 'File:Oba Akenzua Cultural Centre.jpg',
      photographer: 'ID Cooln',
      license: 'CC BY-SA 4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Oba_Akenzua_Cultural_Centre.jpg',
      width: 1600,
      height: 1060,
    },
    dossier: {
      en: "Nwoko drew this building in 1972 as a theatre for the University of Benin. It was eventually built with government money and opened in 1993 as a civic cultural centre, a few streets from the Oba's palace. Two things about it are deliberately local. The colour is the red earth of Benin City itself, obtained not by paint but by casting the walls in Nwoko's sandcrete mix of cement, sand and pebble-filled lateritic soil. And the surface is worked in continuous horizontal ridges, quoting the ridged wall finish that in Benin is a royal privilege the Oba grants to chiefs. The plan, however, departs sharply from Edo precedent: instead of the rectilinear courtyard compound, a half-circle whose curve is set by the rake of the auditorium seating behind it.",
      es: 'Nwoko dibujó este edificio en 1972 como teatro para la Universidad de Benín. Acabó construyéndose con dinero público y se inauguró en 1993 como centro cultural cívico, a pocas calles del palacio del oba. Dos rasgos son deliberadamente locales. El color es la propia tierra roja de la ciudad de Benín, obtenido no con pintura sino fundiendo los muros con la mezcla de hormigón de arena de Nwoko: cemento, arena y tierra laterítica con guijarros. Y la superficie está trabajada en franjas horizontales continuas, cita del acabado de muro estriado que en Benín es un privilegio real que el oba concede a los jefes. La planta, en cambio, se aparta con nitidez del precedente edo: en lugar del recinto rectilíneo en torno a patios, un semicírculo cuya curva la fija la pendiente del graderío del auditorio.',
      it: "Nwoko disegnò questo edificio nel 1972 come teatro per l'Università del Benin. Fu infine costruito con denaro pubblico e inaugurato nel 1993 come centro culturale civico, a poche strade dal palazzo dell'oba. Due tratti sono deliberatamente locali. Il colore è la stessa terra rossa di Benin City, ottenuto non con la vernice ma gettando i muri con la mescola di sandcrete di Nwoko: cemento, sabbia e terra lateritica con ciottoli. E la superficie è lavorata a fasce orizzontali continue, citazione della finitura muraria a costoloni che nel Benin è un privilegio regale concesso dall'oba ai capi. La pianta invece si allontana nettamente dal precedente edo: al posto del recinto rettilineo attorno a corti, un semicerchio la cui curva è dettata dalla pendenza della gradinata dell'auditorio.",
    },
    context: null,
    sources: [
      {
        kind: 'institution',
        url: 'https://access.thebrightcontinent.org/items/show/7',
        title: 'Oba Akenzua Cultural Centre — Performing Arts and Exhibition Center, Bright Continent',
        license: null,
      },
      {
        kind: 'wikipedia',
        url: 'https://en.wikipedia.org/wiki/Demas_Nwoko',
        title: 'Demas Nwoko',
        license: 'CC BY-SA 4.0',
      },
    ],
    tier: 'canon',
  },
  {
    id: 'maryland-mall-lagos',
    wikidataId: null,
    name: {
      en: 'Maryland Mall',
      es: 'Maryland Mall',
      it: 'Maryland Mall',
    },
    architectId: 'tosin-oshinowo',
    location: { city: 'Lagos', countryCode: 'NG', lat: 6.5671147, lon: 3.3673102 },
    inception: 2016,
    completed: 2016,
    demolished: null,
    typology: 'commercial',
    materials: ['mixed'],
    structure: {
      en: 'A compact rectilinear retail block on the Ikorodu Road frontage, its street elevation treated as a matte black plane carrying an outdoor LED screen and signage rather than as a display window.',
      es: 'Un bloque comercial compacto y rectilíneo en el frente de la Ikorodu Road, cuyo alzado a la calle se trata como un plano negro mate que soporta una pantalla LED exterior y rótulos en lugar de como escaparate.',
      it: 'Un blocco commerciale compatto e rettilineo sul fronte della Ikorodu Road, il cui prospetto stradale è trattato come un piano nero opaco che sostiene uno schermo LED esterno e le insegne anziché come vetrina.',
    },
    program: {
      en: 'A small retail mall at the Maryland bus interchange in Lagos, built for a private developer on one of the city\'s busiest commuter corridors.',
      es: 'Un centro comercial pequeño en el intercambiador de autobuses de Maryland, en Lagos, construido para un promotor privado en uno de los corredores de cercanías más transitados de la ciudad.',
      it: 'Un piccolo centro commerciale allo scambio degli autobus di Maryland, a Lagos, costruito per un promotore privato su uno dei corridoi pendolari più trafficati della città.',
    },
    heritage: 'none',
    currentUse: {
      en: 'Shopping mall and cinema.',
      es: 'Centro comercial y cine.',
      it: 'Centro commerciale e cinema.',
    },
    detailRect: { x: 0.34, y: 0.3, w: 0.32, h: 0.34 },
    image: {
      commonsFile: 'File:Maryland Mall, Maryland, Lagos.jpg',
      photographer: 'Sho photography',
      license: 'CC BY-SA 4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Maryland_Mall,_Maryland,_Lagos.jpg',
      width: 1600,
      height: 1062,
    },
    dossier: {
      en: "Maryland Mall opened in June 2016, designed by Tosin Oshinowo as team lead at cmDesign Atelier, and it made her name in Lagos. The building is small and its programme is unremarkable; the decision that carries it is the colour. Oshinowo took a site at a bus interchange where the real audience is passing traffic, and painted the whole street elevation matte black so that the building would recede at night and only the illumination read — the signage and an outdoor LED screen described at the time as the largest in sub-Saharan Africa. It is an unusually clear piece of reasoning about what a commercial facade in Lagos is actually for, and it went against local expectation strongly enough that Oshinowo has repeatedly had to explain it. She founded cmDesign Atelier in 2012 after training in London and working at OMA.",
      es: 'Maryland Mall abrió en junio de 2016, proyectado por Tosin Oshinowo como responsable de equipo en cmDesign Atelier, y fue lo que le dio nombre en Lagos. El edificio es pequeño y su programa poco notable; la decisión que lo sostiene es el color. Oshinowo tomó un solar junto a un intercambiador de autobuses, donde el público real es el tráfico que pasa, y pintó todo el alzado a la calle de negro mate para que el edificio se retirara de noche y solo se leyera la iluminación: los rótulos y una pantalla LED exterior descrita entonces como la mayor del África subsahariana. Es un razonamiento inusualmente claro sobre para qué sirve en realidad una fachada comercial en Lagos, y fue tan contrario a la expectativa local que Oshinowo ha tenido que explicarlo una y otra vez. Fundó cmDesign Atelier en 2012, tras formarse en Londres y trabajar en OMA.',
      it: "Il Maryland Mall ha aperto nel giugno 2016, progettato da Tosin Oshinowo come capo progetto presso cmDesign Atelier, e le ha dato un nome a Lagos. L'edificio è piccolo e il programma poco notevole; la decisione che lo regge è il colore. Oshinowo ha preso un lotto presso uno scambio di autobus, dove il pubblico reale è il traffico di passaggio, e ha dipinto tutto il prospetto stradale di nero opaco affinché di notte l'edificio arretri e si legga solo l'illuminazione: le insegne e uno schermo LED esterno all'epoca descritto come il più grande dell'Africa subsahariana. È un ragionamento insolitamente limpido su ciò a cui serve davvero una facciata commerciale a Lagos, e andava così contro le aspettative locali che Oshinowo ha dovuto spiegarlo più volte. Ha fondato cmDesign Atelier nel 2012, dopo essersi formata a Londra e aver lavorato all'OMA.",
    },
    context: null,
    sources: [
      {
        kind: 'wikipedia',
        url: 'https://en.wikipedia.org/wiki/Tosin_Oshinowo',
        title: 'Tosin Oshinowo',
        license: 'CC BY-SA 4.0',
      },
      {
        kind: 'publication',
        url: 'https://guardian.ng/features/they-said-i-couldnt-but-i-designed-a-landmark-that-left-my-naysayers-mesmerized-tosin-oshinowo-principal-architect-cmdesign-atelier/',
        title: 'Tosin Oshinowo, principal architect, cmDesign Atelier — The Guardian Nigeria',
        license: null,
      },
      {
        kind: 'publication',
        url: 'https://www.livinspaces.net/projects/architecture/built-the-maryland-shopping-mall-in-ikeja-by-cmda/',
        title: 'Built: The Maryland Mall (a.k.a The Big Black Box) in Lagos by CMD+A — Livinspaces',
        license: null,
      },
    ],
    tier: 'deep',
  },
  {
    id: 'larabanga-mosque',
    wikidataId: 'Q490898',
    name: {
      en: 'Larabanga Mosque',
      es: 'Mezquita de Larabanga',
      it: 'Moschea di Larabanga',
    },
    architectId: 'ayuba',
    location: { city: 'Larabanga', countryCode: 'GH', lat: 9.2167, lon: -1.8667 },
    inception: 1421,
    completed: null,
    demolished: null,
    typology: 'sacral',
    materials: ['earth', 'timber'],
    structure: {
      en: 'A single-room prayer hall about eight metres square, its walls built up in wattle and daub over a timber armature, with two pyramidal corner towers and twelve conical buttresses reinforced by projecting horizontal timbers in the Sudano-Sahelian manner.',
      es: 'Una sala de oración de una sola nave de unos ocho metros de lado, con muros de bahareque levantados sobre una armadura de madera, dos torres piramidales angulares y doce contrafuertes cónicos reforzados con maderos horizontales salientes, a la manera sudano-saheliana.',
      it: 'Una sala di preghiera a navata unica di circa otto metri di lato, con muri in terra e canniccio alzati su un\'armatura lignea, due torri piramidali angolari e dodici contrafforti conici rinforzati da travi orizzontali sporgenti, secondo la maniera sudano-saheliana.',
    },
    program: {
      en: 'The congregational mosque of the village of Larabanga, on a historic trade route in northern Ghana, serving a Muslim community whose settlement is itself traditionally dated to the fifteenth century.',
      es: 'La mezquita congregacional de la aldea de Larabanga, en una histórica ruta comercial del norte de Ghana, al servicio de una comunidad musulmana cuyo asentamiento se data también, por tradición, en el siglo XV.',
      it: "La moschea congregazionale del villaggio di Larabanga, su un'antica via commerciale del Ghana settentrionale, al servizio di una comunità musulmana il cui insediamento è anch'esso datato per tradizione al XV secolo.",
    },
    heritage: 'national',
    currentUse: {
      en: 'Active mosque and pilgrimage site; restored repeatedly, most recently in 2023, and listed by the World Monuments Fund among its 100 Most Endangered Sites after storm damage.',
      es: 'Mezquita activa y lugar de peregrinación; restaurada varias veces, la última en 2023, e incluida por el World Monuments Fund entre sus 100 lugares más amenazados tras sufrir daños por tormenta.',
      it: "Moschea attiva e meta di pellegrinaggio; restaurata più volte, l'ultima nel 2023, e inserita dal World Monuments Fund tra i suoi 100 siti più a rischio dopo danni causati da una tempesta.",
    },
    detailRect: { x: 0.32, y: 0.3, w: 0.32, h: 0.34 },
    image: {
      commonsFile: 'File:Larabanga_Mosque.jpg',
      photographer: 'Sathyan Velumani',
      license: 'CC BY-SA 3.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Larabanga_Mosque.jpg',
      width: 1600,
      height: 1063,
    },
    dossier: {
      en: 'The mosque at Larabanga, in the West Gonja district of northern Ghana, is dated by local tradition to 1421, which would make it the oldest mosque in the country and among the oldest in West Africa; the date rests on oral tradition rather than an inscription or excavation, and should be read as such. The story told locally credits an Islamic trader named Ayuba, who is said to have dreamed, while resting near a stone still venerated nearby, that he was instructed to build a mosque on the spot; he woke to find the foundations already laid and completed the building himself. Whatever its origin, the structure that stands today is a small, single-room prayer hall roughly eight metres square, built in wattle and daub in the Sudano-Sahelian manner shared with Djenné and Zaria: two pyramidal towers flank the mihrab and minaret, and twelve conical buttresses reinforced with projecting timber ring the walls. Ayuba is said to be buried beside the mosque, under a baobab planted to mark the grave. The building has been restored repeatedly, most recently in 2023, and remains an active mosque and pilgrimage site.',
      es: 'La mezquita de Larabanga, en el distrito de West Gonja, en el norte de Ghana, se data por tradición oral en 1421, lo que la convertiría en la mezquita más antigua del país y una de las más antiguas de África Occidental; la fecha descansa en la tradición oral y no en una inscripción o una excavación, y debe leerse como tal. La historia que se cuenta localmente atribuye el origen a un comerciante musulmán llamado Ayuba, que según se dice soñó, mientras descansaba junto a una piedra todavía venerada en las cercanías, que se le ordenaba construir una mezquita en ese lugar; al despertar encontró los cimientos ya trazados y terminó él mismo el edificio. Sea cual sea su origen, la estructura que hoy se conserva es una pequeña sala de oración de una sola nave, de unos ocho metros de lado, construida en bahareque según la manera sudano-saheliana que comparte con Djenné y Zaria: dos torres piramidales flanquean el mihrab y el alminar, y doce contrafuertes cónicos reforzados con madera saliente rodean los muros. Se dice que Ayuba está enterrado junto a la mezquita, bajo un baobab plantado para señalar la tumba. El edificio ha sido restaurado varias veces, la última en 2023, y sigue siendo una mezquita activa y lugar de peregrinación.',
      it: "La moschea di Larabanga, nel distretto di West Gonja, nel nord del Ghana, è datata dalla tradizione orale al 1421, il che ne farebbe la moschea più antica del paese e una delle più antiche dell'Africa occidentale; la data poggia sulla tradizione orale e non su un'iscrizione o uno scavo, e va letta come tale. Il racconto locale attribuisce l'origine a un mercante musulmano di nome Ayuba, che si narra abbia sognato, mentre riposava presso una pietra ancora oggi venerata nei pressi, di essere stato incaricato di costruire una moschea in quel luogo; svegliatosi, trovò le fondamenta già tracciate e completò da solo l'edificio. Quale che sia la sua origine, la struttura oggi visibile è una piccola sala di preghiera a navata unica, di circa otto metri di lato, costruita in terra e canniccio secondo la maniera sudano-saheliana condivisa con Djenné e Zaria: due torri piramidali affiancano il mihrab e il minareto, e dodici contrafforti conici rinforzati con legno sporgente cingono i muri. Si narra che Ayuba sia sepolto accanto alla moschea, sotto un baobab piantato a segnarne la tomba. L'edificio è stato restaurato più volte, l'ultima nel 2023, ed è tuttora una moschea attiva e meta di pellegrinaggio.",
    },
    context: null,
    sources: [
      {
        kind: 'wikipedia',
        url: 'https://en.wikipedia.org/wiki/Larabanga_Mosque',
        title: 'Larabanga Mosque',
        license: 'CC BY-SA 4.0',
      },
      {
        kind: 'wikidata',
        url: 'https://www.wikidata.org/wiki/Q490898',
        title: 'Larabanga Mosque (Q490898)',
        license: null,
      },
    ],
    tier: 'canon',
  },
  {
    id: 'elmina-castle',
    wikidataId: 'Q55264655',
    name: {
      en: 'Elmina Castle',
      es: 'Castillo de Elmina',
      it: 'Castello di Elmina',
    },
    architectId: 'diogo-de-azambuja',
    location: { city: 'Elmina', countryCode: 'GH', lat: 5.0828, lon: -1.348 },
    inception: 1482,
    completed: 1482,
    demolished: null,
    typology: 'civic',
    materials: ['stone'],
    structure: {
      en: 'A quadrangular masonry fortress raised from stone cut and dressed in Portugal and shipped pre-fitted on twelve vessels, assembled around a courtyard with corner towers and later Dutch-added bastions, standing on a rocky promontory at the mouth of the Benya lagoon.',
      es: 'Una fortaleza de fábrica cuadrangular levantada con piedra cortada y labrada en Portugal y transportada ya ajustada en doce navíos, dispuesta en torno a un patio con torres angulares y baluartes añadidos después por los holandeses, sobre un promontorio rocoso en la desembocadura de la laguna Benya.',
      it: 'Una fortezza muraria quadrangolare eretta con pietra tagliata e lavorata in Portogallo e trasportata già predisposta su dodici navi, articolata attorno a una corte con torri angolari e baluardi aggiunti in seguito dagli olandesi, su un promontorio roccioso alla foce della laguna Benya.',
    },
    program: {
      en: 'A Portuguese Crown trading post built to secure the Gold Coast gold trade against European rivals, which became, over the following two centuries, one of the principal depots of the transatlantic slave trade on the Gulf of Guinea.',
      es: 'Un puesto comercial de la corona portuguesa construido para asegurar el comercio del oro de la Costa de Oro frente a los rivales europeos, que en los dos siglos siguientes se convirtió en uno de los principales depósitos de la trata atlántica en el golfo de Guinea.',
      it: "Un avamposto commerciale della corona portoghese costruito per assicurare il commercio dell'oro della Costa d'Oro contro i rivali europei, che nei due secoli successivi divenne uno dei principali depositi della tratta atlantica nel golfo di Guinea.",
    },
    heritage: 'unesco',
    currentUse: {
      en: 'National museum and UNESCO World Heritage Site, part of the Forts and Castles of Volta, Greater Accra, Central and Western Regions inscription of 1979.',
      es: 'Museo nacional y Patrimonio Mundial de la Unesco, dentro de la inscripción de 1979 de los Fuertes y Castillos de Volta, Gran Accra y las regiones Central y Occidental.',
      it: 'Museo nazionale e Patrimonio Mondiale dell\'Unesco, all\'interno dell\'iscrizione del 1979 dei Forti e Castelli di Volta, Grande Accra e delle regioni Centrale e Occidentale.',
    },
    detailRect: { x: 0.3, y: 0.32, w: 0.34, h: 0.3 },
    image: {
      commonsFile: 'File:Elmina Castle side view.jpg',
      photographer: 'Dieu-Donné Gameli',
      license: 'CC BY-SA 3.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Elmina_Castle_side_view.jpg',
      width: 1600,
      height: 899,
    },
    dossier: {
      en: "King John II of Portugal sent Diogo de Azambuja to the Gold Coast in December 1481 with ten caravels and two transport ships, six hundred men, and stone already cut and numbered in Portugal for reassembly — foundation blocks to roof tiles. Landing near the fishing town the Portuguese called A Mina, Azambuja negotiated for the site with the local ruler, traditionally named Kwamin Ansah (interpreted from the Portuguese as 'Caramansa'), and construction proceeded despite local resistance to a foreign fortress on the shore; the fort was substantially complete within about twenty days, an unusual speed made possible entirely by the prefabrication. São Jorge da Mina became the first permanent European trading post in sub-Saharan Africa and the anchor of Portugal's Gold Coast trade. The Dutch West India Company seized it in 1637 and held it until 1872, when it passed to Britain with the rest of the Dutch Gold Coast. What began as an installation built explicitly to protect the gold trade from becoming a slaving post did not remain one; that history is set out below.",
      es: 'El rey Juan II de Portugal envió a Diogo de Azambuja a la Costa de Oro en diciembre de 1481 con diez carabelas y dos naves de transporte, seiscientos hombres, y piedra ya cortada y numerada en Portugal para su montaje en destino, desde los sillares de cimentación hasta las tejas. Tras desembarcar cerca del pueblo pesquero que los portugueses llamaron A Mina, Azambuja negoció el emplazamiento con el gobernante local, llamado por tradición Kwamin Ansah (interpretado del portugués como «Caramansa»), y las obras avanzaron pese a la resistencia local a una fortaleza extranjera en la costa; el fuerte quedó sustancialmente terminado en unos veinte días, una rapidez inusual que la prefabricación hizo posible por completo. São Jorge da Mina se convirtió en el primer puesto comercial europeo permanente del África subsahariana y en el eje del comercio portugués del oro en la costa. La Compañía Neerlandesa de las Indias Occidentales lo tomó en 1637 y lo conservó hasta 1872, cuando pasó a Gran Bretaña junto con el resto de la Costa de Oro neerlandesa. Lo que comenzó como una instalación construida expresamente para proteger el comercio del oro de convertirse en un puesto esclavista no siguió siéndolo; esa historia se expone más abajo.',
      it: "Il re Giovanni II del Portogallo inviò Diogo de Azambuja sulla Costa d'Oro nel dicembre 1481 con dieci caravelle e due navi da trasporto, seicento uomini, e pietra già tagliata e numerata in Portogallo per essere rimontata in loco, dai blocchi di fondazione alle tegole. Sbarcato presso il villaggio di pescatori che i portoghesi chiamarono A Mina, Azambuja trattò il sito con il sovrano locale, tradizionalmente chiamato Kwamin Ansah (reso in portoghese come «Caramansa»), e i lavori proseguirono nonostante la resistenza locale a una fortezza straniera sulla costa; il forte fu sostanzialmente completato in circa venti giorni, una rapidità insolita resa possibile interamente dalla prefabbricazione. São Jorge da Mina divenne il primo insediamento commerciale europeo permanente dell'Africa subsahariana e il perno del commercio portoghese dell'oro sulla costa. La Compagnia Olandese delle Indie Occidentali lo conquistò nel 1637 e lo mantenne fino al 1872, quando passò alla Gran Bretagna insieme al resto della Costa d'Oro olandese. Ciò che nacque come un impianto costruito espressamente per proteggere il commercio dell'oro dal trasformarsi in un avamposto schiavista non rimase tale; questa storia è esposta di seguito.",
    },
    context: {
      body: {
        en: "St. George's Castle was founded explicitly to keep the gold trade separate from slaving: Portuguese policy in the fifteenth century did not want the fort drawn into the trade in captives for fear of destabilising the gold routes it existed to protect. That policy did not hold. By the seventeenth century, most West African trade at the coast had shifted to the sale of captives, and the castle became a depot where enslaved people brought from the interior by African and European traders were held before shipment across the Atlantic, in underground chambers built to hold them pending sale. The Dutch West India Company took the fort by force in 1637, absorbed the rest of the Portuguese Gold Coast in 1642, and continued the trade from Elmina until the Netherlands' abolition of its own slave trade in 1814, formalised the same year in the Anglo-Dutch treaty banning it. The castle's holding cells and the seaward gate through which captives were loaded onto ships survive and are shown to visitors today as part of its history rather than a separate chapter from its founding.",
        es: 'El castillo de San Jorge se fundó expresamente para mantener el comercio del oro al margen de la trata: la política portuguesa del siglo XV no quería que el fuerte se viera arrastrado al comercio de cautivos, por temor a desestabilizar las rutas del oro que existía para proteger. Esa política no se mantuvo. Hacia el siglo XVII, la mayor parte del comercio de África Occidental en la costa había pasado a la venta de cautivos, y el castillo se convirtió en un depósito donde se retenía, en cámaras subterráneas construidas para ese fin, a personas esclavizadas traídas del interior por comerciantes africanos y europeos antes de embarcarlas hacia el Atlántico. La Compañía Neerlandesa de las Indias Occidentales tomó el fuerte por la fuerza en 1637, absorbió el resto de la Costa de Oro portuguesa en 1642 y prosiguió la trata desde Elmina hasta la abolición neerlandesa de su propio comercio de esclavos en 1814, formalizada ese mismo año en el tratado angloneerlandés que la prohibió. Las celdas de retención del castillo y la puerta hacia el mar por la que se embarcaba a los cautivos se conservan y hoy se muestran a los visitantes como parte de su historia, no como un capítulo aparte de su fundación.',
        it: "Il castello di San Giorgio fu fondato espressamente per tenere il commercio dell'oro separato dalla tratta: la politica portoghese del Quattrocento non voleva che il forte fosse coinvolto nel commercio di prigionieri, per timore di destabilizzare le rotte dell'oro che esisteva per proteggere. Quella politica non resse. Verso il Seicento, la maggior parte del commercio dell'Africa occidentale sulla costa si era spostata verso la vendita di prigionieri, e il castello divenne un deposito dove le persone schiavizzate portate dall'interno da mercanti africani ed europei venivano trattenute, in camere sotterranee costruite a tale scopo, prima dell'imbarco verso l'Atlantico. La Compagnia Olandese delle Indie Occidentali conquistò il forte con la forza nel 1637, assorbì il resto della Costa d'Oro portoghese nel 1642 e proseguì la tratta da Elmina fino all'abolizione olandese del proprio commercio di schiavi nel 1814, formalizzata lo stesso anno nel trattato anglo-olandese che la vietava. Le celle di detenzione del castello e la porta verso il mare da cui i prigionieri venivano imbarcati si conservano e sono oggi mostrate ai visitatori come parte della sua storia, non come un capitolo separato dalla sua fondazione.",
      },
      sources: [
        {
          kind: 'wikipedia',
          url: 'https://en.wikipedia.org/wiki/Elmina_Castle',
          title: 'Elmina Castle',
          license: 'CC BY-SA 4.0',
        },
      ],
    },
    sources: [
      {
        kind: 'wikipedia',
        url: 'https://en.wikipedia.org/wiki/Elmina_Castle',
        title: 'Elmina Castle',
        license: 'CC BY-SA 4.0',
      },
      {
        kind: 'wikidata',
        url: 'https://www.wikidata.org/wiki/Q55264655',
        title: 'Elmina Castle (Q55264655)',
        license: null,
      },
    ],
    tier: 'canon',
  },
];
