import type { Building } from '@/types/building';

// Wave 5, agent 9c — Northern America (United States and Canada).
//
// Every Q-number was read off the live Wikidata entity page and every image
// licence off the live Commons file page on 2026-08-26; the licence string
// recorded here is the one in that page's licensing box, and the photographer
// is the author exactly as that page credits them.
//
// `image.width` / `image.height` are left at 0 on purpose — Task 10 records
// the real pixel dimensions. Each `detailRect` was placed by looking at the
// actual photograph, not inferred from its description.
export const AMERICAS_BUILDINGS: Building[] = [
  {
    id: 'monticello',
    wikidataId: 'Q199618',
    name: {
      en: 'Monticello',
      es: 'Monticello',
      it: 'Monticello',
    },
    architectId: 'thomas-jefferson',
    location: { city: 'Charlottesville, Virginia', countryCode: 'US', lat: 38.010306, lon: -78.452333 },
    inception: 1768,
    completed: 1809,
    demolished: null,
    typology: 'domestic',
    materials: ['brick', 'timber'],
    structure: {
      en: 'Load-bearing walls of brick made and fired on the estate carry a timber roof frame and the octagonal timber-framed dome Jefferson raised over the parlour during the second building campaign.',
      es: 'Muros de carga de ladrillo fabricado y cocido en la propia finca sostienen una armadura de madera y la cúpula octogonal, también de madera, que Jefferson levantó sobre el salón en la segunda campaña de obras.',
      it: 'Murature portanti di mattoni fabbricati e cotti nella tenuta reggono un\'orditura lignea e la cupola ottagonale, pure in legno, che Jefferson innalzò sopra il salone durante il secondo cantiere.',
    },
    program: {
      en: 'Jefferson\'s own house and the head of a 5,000-acre plantation worked by about 150 enslaved people; since 1923 it has been a museum owned by the Thomas Jefferson Foundation.',
      es: 'Casa propia de Jefferson y cabecera de una plantación de 5.000 acres trabajada por unas 150 personas esclavizadas; desde 1923 es un museo propiedad de la Thomas Jefferson Foundation.',
      it: 'Casa di Jefferson e centro di una piantagione di 5.000 acri lavorata da circa 150 persone schiavizzate; dal 1923 è un museo di proprietà della Thomas Jefferson Foundation.',
    },
    heritage: 'unesco',
    currentUse: {
      en: 'House museum and study centre, owned and operated by the Thomas Jefferson Foundation.',
      es: 'Casa museo y centro de estudios, propiedad de la Thomas Jefferson Foundation, que la gestiona.',
      it: 'Casa museo e centro di studi, di proprietà della Thomas Jefferson Foundation, che la gestisce.',
    },
    detailRect: { x: 0.40, y: 0.50, w: 0.22, h: 0.32 },
    image: {
      commonsFile: 'File:Thomas Jefferson\'s Monticello.JPG',
      photographer: 'Martin Falbisoner',
      license: 'CC BY-SA 3.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Thomas_Jefferson%27s_Monticello.JPG',
      width: 0,
      height: 0,
    },
    dossier: {
      en: 'Jefferson began building on the mountaintop he called Monticello in 1768 and never really stopped. The first house, a compact block with a stacked double portico, went up while he was reading Palladio; after five years in France he pulled much of it down and rebuilt from 1794, absorbing what he had seen at the Hôtel de Salm in Paris and adding the low dome over the parlour, the first on an American house. The result is deliberately deceptive. From the west lawn it reads as a single storey, because Jefferson hid the mezzanine behind the entablature, put the staircases in narrow side passages, and buried the kitchens, dairy and stables in service wings dug into the slope so that the household ran out of sight. Brick was fired on site and timber cut on the estate, both worked by enslaved labour. The house was substantially complete by 1809, though he kept altering it until his death in 1826.',
      es: 'Jefferson empezó a construir en 1768 sobre la cima que llamó Monticello y en rigor no dejó de hacerlo nunca. La primera casa, un bloque compacto con doble pórtico superpuesto, se levantó mientras leía a Palladio; tras cinco años en Francia derribó buena parte de ella y la rehízo desde 1794, incorporando lo visto en el Hôtel de Salm de París y añadiendo sobre el salón la cúpula rebajada, la primera en una casa estadounidense. El resultado engaña a propósito. Desde el prado occidental parece de una sola planta, porque Jefferson ocultó el entresuelo tras el entablamento, metió las escaleras en pasos laterales estrechos y enterró cocinas, lechería y cuadras en alas de servicio excavadas en la ladera, de modo que la casa funcionara sin verse. El ladrillo se coció allí mismo y la madera se cortó en la finca: ambos los trabajaron personas esclavizadas. La casa estaba prácticamente terminada en 1809, aunque siguió modificándola hasta su muerte en 1826.',
      it: 'Jefferson cominciò a costruire nel 1768 sull\'altura che chiamò Monticello e non smise mai davvero. La prima casa, un blocco compatto con doppio portico sovrapposto, sorse mentre leggeva Palladio; dopo cinque anni in Francia ne demolì gran parte e la rifece dal 1794, assorbendo quanto aveva visto all\'Hôtel de Salm di Parigi e aggiungendo sopra il salone la cupola ribassata, la prima su una casa americana. L\'esito inganna di proposito. Dal prato occidentale l\'edificio sembra di un solo piano, perché Jefferson nascose il mezzanino dietro la trabeazione, infilò le scale in stretti passaggi laterali e sotterrò cucine, caseificio e stalle in ali di servizio scavate nel pendio, così che la casa funzionasse senza mostrarsi. I mattoni furono cotti in loco e il legname tagliato nella tenuta: entrambi lavorati da persone schiavizzate. La casa era sostanzialmente compiuta nel 1809, ma Jefferson continuò a modificarla fino alla morte, nel 1826.',
    },
    context: {
      body: {
        en: 'Monticello was built by the people Jefferson enslaved. About 150 enslaved men, women and children worked the plantation at any one time, and the crafts that produced the house were theirs: enslaved workers dug the clay and fired the brick, cut and joined the timber, and from 1794 ran a nailery on Mulberry Row staffed by boys aged roughly ten to sixteen. Jefferson freed two people during his lifetime and five in his will, all members of the Hemings family. In 2000 the Thomas Jefferson Foundation, which has owned the site since 1923, concluded that he was the father of Sally Hemings\'s children; the Foundation has since restored the Mulberry Row structures and the South Wing room associated with Hemings, and its Getting Word project has recorded the testimony of descendants of the enslaved families.',
        es: 'Monticello lo construyeron las personas a las que Jefferson esclavizaba. Unas 150 personas esclavizadas —hombres, mujeres y niños— trabajaban la plantación en cada momento, y los oficios que hicieron la casa fueron suyos: extrajeron la arcilla y cocieron el ladrillo, cortaron y ensamblaron la madera y, desde 1794, atendieron una clavetería en Mulberry Row con muchachos de entre diez y dieciséis años. Jefferson liberó a dos personas en vida y a cinco en su testamento, todas de la familia Hemings. En 2000 la Thomas Jefferson Foundation, propietaria del lugar desde 1923, concluyó que fue el padre de los hijos de Sally Hemings; desde entonces ha restaurado las construcciones de Mulberry Row y la habitación del ala sur asociada a Hemings, y su proyecto Getting Word ha recogido el testimonio de descendientes de las familias esclavizadas.',
        it: 'Monticello fu costruita dalle persone che Jefferson teneva in schiavitù. Circa 150 uomini, donne e bambini schiavizzati lavoravano la piantagione in ogni momento, e i mestieri che fecero la casa furono i loro: scavarono l\'argilla e cossero i mattoni, tagliarono e assemblarono il legname e dal 1794 gestirono una chioderia a Mulberry Row con ragazzi fra i dieci e i sedici anni. Jefferson liberò due persone in vita e cinque per testamento, tutte della famiglia Hemings. Nel 2000 la Thomas Jefferson Foundation, proprietaria del sito dal 1923, concluse che egli fu il padre dei figli di Sally Hemings; da allora ha restaurato le strutture di Mulberry Row e la stanza dell\'ala sud associata a Hemings, e il suo progetto Getting Word ha raccolto le testimonianze dei discendenti delle famiglie schiavizzate.',
      },
      sources: [
        { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Thomas_Jefferson_and_slavery', title: 'Thomas Jefferson and slavery', license: 'CC BY-SA 4.0' },
        { kind: 'institution', url: 'https://www.monticello.org/thomas-jefferson/jefferson-slavery/', title: 'Thomas Jefferson Foundation — Jefferson and Slavery', license: null },
        { kind: 'institution', url: 'https://www.monticello.org/getting-word/', title: 'Getting Word African American Oral History Project', license: null },
      ],
    },
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q199618', title: 'Monticello (Q199618)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Monticello', title: 'Monticello', license: 'CC BY-SA 4.0' },
      { kind: 'institution', url: 'https://whc.unesco.org/en/list/442/', title: 'UNESCO World Heritage List — Monticello and the University of Virginia in Charlottesville', license: null },
    ],
    tier: 'canon',
  },
  {
    id: 'wainwright-building',
    wikidataId: 'Q1143548',
    name: {
      en: 'Wainwright Building',
      es: 'Wainwright Building',
      it: 'Wainwright Building',
    },
    architectId: 'louis-sullivan',
    location: { city: 'St. Louis, Missouri', countryCode: 'US', lat: 38.626944, lon: -90.192222 },
    inception: 1890,
    completed: 1891,
    demolished: null,
    typology: 'commercial',
    materials: ['brick', 'stone'],
    structure: {
      en: 'A riveted steel skeleton carries the ten floors; the red brick and terracotta skin is hung from it as cladding, standing on a base of brown sandstone at street level.',
      es: 'Un esqueleto de acero roblonado soporta las diez plantas; la piel de ladrillo rojo y terracota cuelga de él como revestimiento y arranca de un zócalo de arenisca parda a pie de calle.',
      it: 'Uno scheletro d\'acciaio chiodato regge i dieci piani; la pelle di mattoni rossi e terracotta vi è appesa come rivestimento e poggia su un basamento di arenaria bruna a livello strada.',
    },
    program: {
      en: 'Speculative offices commissioned by the brewer Ellis Wainwright to house the St Louis Brewers\' Association and let the remaining floors on the open market.',
      es: 'Oficinas de renta encargadas por el cervecero Ellis Wainwright para alojar la Asociación de Cerveceros de San Luis y alquilar el resto de las plantas en el mercado libre.',
      it: 'Uffici in locazione commissionati dal birraio Ellis Wainwright per ospitare l\'Associazione dei birrai di Saint Louis e affittare sul mercato i piani restanti.',
    },
    heritage: 'national',
    currentUse: {
      en: 'Offices; the State of Missouri used it as the Wainwright State Office Building until it was sold into private ownership in 2024.',
      es: 'Oficinas; el estado de Misuri lo usó como Wainwright State Office Building hasta su venta a manos privadas en 2024.',
      it: 'Uffici; lo Stato del Missouri lo utilizzò come Wainwright State Office Building fino alla vendita a privati nel 2024.',
    },
    detailRect: { x: 0.32, y: 0.28, w: 0.36, h: 0.26 },
    image: {
      commonsFile: 'File:Wainwright building 1995.jpg',
      photographer: 'Kenneth C. Zirkel',
      license: 'CC BY-SA 4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Wainwright_building_1995.jpg',
      width: 0,
      height: 0,
    },
    dossier: {
      en: 'Adler and Sullivan were handed ten storeys of speculative office space on a steel frame at a moment when nobody had settled what such a building should look like; most tall buildings of 1890 were tall masonry buildings, their floors stacked in visible tiers. Sullivan\'s move was to treat the shaft as one thing. A two-storey base with shop fronts, then seven identical office floors gathered into continuous brick piers that run unbroken to a deep terracotta frieze, then a heavy cornice. Only every other pier carries steel; the rest exist to keep the rhythm even, which is why the building is an argument about how tallness should look rather than a diagram of its structure. Between the windows the spandrels are recessed and filled with foliate terracotta, a different pattern on each floor. Threatened with demolition in the 1970s and saved by a campaign led by the architect John D. Randall, it has been a National Historic Landmark since 1968.',
      es: 'Adler y Sullivan recibieron diez plantas de oficinas de renta sobre estructura de acero en un momento en que nadie había fijado aún el aspecto de un edificio así; la mayoría de los edificios altos de 1890 eran edificios altos de fábrica, con los pisos apilados en franjas visibles. La jugada de Sullivan fue tratar el fuste como una sola cosa. Un zócalo de dos plantas con locales, siete plantas de oficinas idénticas reunidas en pilastras de ladrillo que suben sin interrupción hasta un friso profundo de terracota, y una cornisa pesada. Solo una de cada dos pilastras lleva acero; las demás están para que el ritmo no se rompa, y por eso el edificio es un argumento sobre cómo debe verse la altura y no un diagrama de su estructura. Entre las ventanas, los antepechos se retranquean y se llenan de terracota vegetal, con un dibujo distinto en cada planta. Amenazado de derribo en los años setenta y salvado por una campaña del arquitecto John D. Randall, es National Historic Landmark desde 1968.',
      it: 'Adler e Sullivan ricevettero dieci piani di uffici in locazione su struttura d\'acciaio in un momento in cui nessuno aveva ancora stabilito che aspetto dovesse avere un edificio simile; la maggior parte degli edifici alti del 1890 erano edifici alti in muratura, con i piani accatastati in fasce visibili. La mossa di Sullivan fu trattare il fusto come una cosa sola. Un basamento di due piani con negozi, sette piani di uffici identici raccolti in lesene di mattoni che salgono ininterrotte fino a un profondo fregio di terracotta, e infine una cornice pesante. Solo una lesena su due porta acciaio; le altre servono a non spezzare il ritmo, ed è per questo che l\'edificio è un argomento su come debba apparire l\'altezza e non un diagramma della sua struttura. Fra le finestre i parapetti arretrano e si riempiono di terracotta vegetale, con un disegno diverso a ogni piano. Minacciato di demolizione negli anni settanta e salvato da una campagna dell\'architetto John D. Randall, è National Historic Landmark dal 1968.',
    },
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q1143548', title: 'Wainwright Building (Q1143548)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Wainwright_Building', title: 'Wainwright Building', license: 'CC BY-SA 4.0' },
      { kind: 'publication', url: 'https://sah-archipedia.org/buildings/MO-01-510-0003', title: 'SAH Archipedia — Wainwright Building', license: null },
      { kind: 'publication', url: 'https://archive.org/details/lippincottsmont47phil/page/402', title: 'Louis H. Sullivan, "The Tall Office Building Artistically Considered", Lippincott\'s Magazine, March 1896', license: null },
    ],
    tier: 'canon',
  },
  {
    id: 'desert-view-watchtower',
    wikidataId: 'Q2062022',
    name: {
      en: 'Desert View Watchtower',
      es: 'Torre de Vigilancia Desert View',
      it: 'Desert View Watchtower',
    },
    architectId: 'mary-colter',
    location: { city: 'Desert View, Grand Canyon National Park, Arizona', countryCode: 'US', lat: 36.043889, lon: -111.825833 },
    inception: 1932,
    completed: 1932,
    demolished: null,
    typology: 'tower',
    materials: ['stone', 'concrete'],
    structure: {
      en: 'A concealed steel and concrete frame carries four visitor levels inside a circular drum of coursed local limestone rising from a rubble base built up off the canyon rim.',
      es: 'Una estructura oculta de acero y hormigón sostiene cuatro niveles de visita dentro de un tambor circular de caliza local aparejada por hiladas que arranca de un basamento de mampuesto sobre el borde del cañón.',
      it: 'Un\'ossatura nascosta di acciaio e calcestruzzo regge quattro livelli di visita dentro un tamburo circolare di calcare locale a corsi, impostato su un basamento di pietrame lungo l\'orlo del canyon.',
    },
    program: {
      en: 'A lookout, rest stop and curio shop built for the Fred Harvey Company, the Santa Fe Railway\'s concessionaire on the South Rim, to draw motor tourists to the eastern end of the canyon.',
      es: 'Mirador, parada de descanso y tienda de recuerdos levantada para la Fred Harvey Company, concesionaria del ferrocarril de Santa Fe en el borde sur, para atraer al turismo motorizado al extremo oriental del cañón.',
      it: 'Belvedere, punto di sosta e negozio di souvenir costruito per la Fred Harvey Company, concessionaria della ferrovia di Santa Fe sul bordo meridionale, per attirare il turismo automobilistico all\'estremità orientale del canyon.',
    },
    heritage: 'national',
    currentUse: {
      en: 'Visitor lookout inside Grand Canyon National Park, at the Desert View Inter-tribal Cultural Heritage Site.',
      es: 'Mirador para visitantes dentro del Parque Nacional del Gran Cañón, en el Desert View Inter-tribal Cultural Heritage Site.',
      it: 'Belvedere per visitatori nel Parco nazionale del Grand Canyon, presso il Desert View Inter-tribal Cultural Heritage Site.',
    },
    detailRect: { x: 0.44, y: 0.20, w: 0.30, h: 0.28 },
    image: {
      commonsFile: 'File:Desert View Watchtower Grand Canyon 09 2017 5545.jpg',
      photographer: 'Mariordo (Mario Roberto Durán Ortiz)',
      license: 'CC BY-SA 4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Desert_View_Watchtower_Grand_Canyon_09_2017_5545.jpg',
      width: 0,
      height: 0,
    },
    dossier: {
      en: 'Colter spent six months visiting Ancestral Puebloan tower sites — the round towers at Hovenweep above all — photographing and measuring them, then built a clay model before a stone was laid. The result is a drum seventy feet high whose masonry is deliberately irregular: stones of unequal size, some left projecting, a pale band running partway round, openings punched without a system, so that the tower reads as something weathered and repaired rather than designed. Behind that skin is a steel and concrete frame, because it had to carry visitors up four floors and a stair. The Hopi Room on the first level was painted by Fred Kabotie, a Hopi artist from Songòopavi, with a mural of the Snake Legend; the walls above carry petroglyph-style work by Fred Geary copying panels then disappearing in New Mexico. It has been a National Historic Landmark since 1987, one of four Colter buildings listed together.',
      es: 'Colter dedicó seis meses a recorrer torres ancestrales puebloanas —sobre todo las torres redondas de Hovenweep—, fotografiándolas y midiéndolas, y construyó una maqueta de arcilla antes de asentar una sola piedra. El resultado es un tambor de veintiún metros con una fábrica deliberadamente irregular: piedras de tamaño desigual, algunas dejadas en resalte, una banda clara que recorre parte del perímetro, huecos abiertos sin sistema, de modo que la torre se lea como algo erosionado y remendado más que proyectado. Tras esa piel hay una estructura de acero y hormigón, porque debía subir a los visitantes cuatro plantas y una escalera. La Sala Hopi del primer nivel la pintó Fred Kabotie, artista hopi de Songòopavi, con un mural de la Leyenda de la Serpiente; los muros superiores llevan grafismos de estilo petroglifo de Fred Geary, copiados de paneles que entonces se estaban perdiendo en Nuevo México. Es National Historic Landmark desde 1987, una de las cuatro obras de Colter inscritas en conjunto.',
      it: 'Colter passò sei mesi a visitare torri ancestrali puebloane — soprattutto quelle rotonde di Hovenweep — fotografandole e misurandole, e costruì un modello in argilla prima che si posasse una sola pietra. Il risultato è un tamburo di ventuno metri con una muratura volutamente irregolare: pietre di misura disuguale, alcune lasciate sporgenti, una fascia chiara che percorre parte del perimetro, aperture forate senza sistema, così che la torre si legga come qualcosa di eroso e rappezzato più che progettato. Dietro quella pelle c\'è un\'ossatura di acciaio e calcestruzzo, perché doveva portare i visitatori su quattro piani e una scala. La Sala Hopi del primo livello fu dipinta da Fred Kabotie, artista hopi di Songòopavi, con un murale della Leggenda del Serpente; le pareti superiori recano segni in stile petroglifo di Fred Geary, copiati da pannelli che allora andavano perduti in Nuovo Messico. È National Historic Landmark dal 1987, una delle quattro opere di Colter iscritte insieme.',
    },
    context: {
      body: {
        en: 'The Watchtower was a commercial building. It was designed for the Fred Harvey Company, the concessionaire that ran the hotels and shops along the Atchison, Topeka and Santa Fe Railway, and it was built to bring paying visitors to the eastern end of the South Rim; the railway supplied the engineering. Its form was taken directly from Ancestral Puebloan towers on the Colorado Plateau, and its interiors were painted by Hopi and other Native artists working to a Harvey Company brief. The National Park Service recognises eleven tribes as traditionally associated with the Grand Canyon: the Havasupai, Hopi, Hualapai, Navajo, Zuni and Yavapai-Apache, together with the Kaibab, Las Vegas, Moapa and San Juan Southern Paiute and the Paiute Indian Tribe of Utah. The Park Service, the Grand Canyon Conservancy and those eleven tribes are converting Desert View into the agency\'s first Inter-tribal Cultural Heritage Site, replacing the concession with tribal interpretation and demonstration.',
        es: 'La torre fue un edificio comercial. Se proyectó para la Fred Harvey Company, concesionaria de los hoteles y comercios a lo largo del ferrocarril de Atchison, Topeka y Santa Fe, y se levantó para llevar visitantes de pago al extremo oriental del borde sur; la ingeniería la aportó el ferrocarril. Su forma se tomó directamente de las torres ancestrales puebloanas de la meseta del Colorado, y sus interiores los pintaron artistas hopi y de otros pueblos originarios trabajando por encargo de la compañía. El Servicio de Parques Nacionales reconoce once tribus tradicionalmente asociadas al Gran Cañón: havasupai, hopi, hualapai, navajo, zuni y yavapai-apache, junto con los paiute de Kaibab, Las Vegas, Moapa y San Juan del Sur y la Paiute Indian Tribe of Utah. El Servicio de Parques, la Grand Canyon Conservancy y esas once tribus están convirtiendo Desert View en el primer Inter-tribal Cultural Heritage Site de la agencia, sustituyendo la concesión por interpretación y demostración a cargo de las propias tribus.',
        it: 'La torre fu un edificio commerciale. Venne progettata per la Fred Harvey Company, concessionaria degli alberghi e dei negozi lungo la ferrovia Atchison, Topeka and Santa Fe, e costruita per portare visitatori paganti all\'estremità orientale del bordo meridionale; l\'ingegneria fu fornita dalla ferrovia. La forma fu ripresa direttamente dalle torri ancestrali puebloane dell\'altopiano del Colorado, e gli interni furono dipinti da artisti hopi e di altri popoli nativi su incarico della compagnia. Il National Park Service riconosce undici tribù tradizionalmente associate al Grand Canyon: havasupai, hopi, hualapai, navajo, zuni e yavapai-apache, insieme ai paiute di Kaibab, Las Vegas, Moapa e San Juan Southern e alla Paiute Indian Tribe of Utah. Il Park Service, la Grand Canyon Conservancy e quelle undici tribù stanno trasformando Desert View nel primo Inter-tribal Cultural Heritage Site dell\'agenzia, sostituendo la concessione con interpretazione e dimostrazioni condotte dalle tribù stesse.',
      },
      sources: [
        { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Desert_View_Watchtower', title: 'Desert View Watchtower', license: 'CC BY-SA 4.0' },
        { kind: 'institution', url: 'https://www.grandcanyon.org/protect-grand-canyon/projects/desert-view-inter-tribal-cultural-heritage-site', title: 'Grand Canyon Conservancy — Desert View Inter-tribal Cultural Heritage Site', license: null },
      ],
    },
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q2062022', title: 'Desert View Watchtower (Q2062022)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Desert_View_Watchtower', title: 'Desert View Watchtower', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Mary_Colter', title: 'Mary Colter', license: 'CC BY-SA 4.0' },
    ],
    tier: 'deep',
  },
  {
    id: 'berkeley-city-club',
    wikidataId: 'Q4891996',
    name: {
      en: 'Berkeley City Club',
      es: 'Berkeley City Club',
      it: 'Berkeley City Club',
    },
    architectId: 'julia-morgan',
    location: { city: 'Berkeley, California', countryCode: 'US', lat: 37.8676, lon: -122.2628 },
    inception: 1929,
    completed: 1930,
    demolished: null,
    typology: 'commercial',
    materials: ['concrete'],
    structure: {
      en: 'Six storeys of steel-reinforced concrete cast in place, with the pointed arcades, quatrefoil tracery and corbel tables formed directly in the concrete rather than applied to it.',
      es: 'Seis plantas de hormigón armado ejecutadas in situ, con las arquerías apuntadas, la tracería de cuadrifolios y las ménsulas moldeadas directamente en el hormigón y no aplicadas sobre él.',
      it: 'Sei piani di calcestruzzo armato gettati in opera, con le arcate a sesto acuto, i trafori a quadrilobo e le mensole formati direttamente nel getto anziché applicati.',
    },
    program: {
      en: 'A clubhouse with dining rooms, a library, an indoor pool and residential rooms, financed by subscription among the members of the Berkeley Women\'s City Club, founded in 1927.',
      es: 'Sede social con comedores, biblioteca, piscina cubierta y habitaciones, financiada por suscripción entre las socias del Berkeley Women\'s City Club, fundado en 1927.',
      it: 'Sede sociale con sale da pranzo, biblioteca, piscina coperta e camere, finanziata per sottoscrizione fra le socie del Berkeley Women\'s City Club, fondato nel 1927.',
    },
    heritage: 'national',
    currentUse: {
      en: 'Private club, hotel and event venue, open to the public for overnight stays and functions.',
      es: 'Club privado, hotel y espacio para eventos, abierto al público para alojamiento y celebraciones.',
      it: 'Circolo privato, albergo e sede per eventi, aperto al pubblico per pernottamenti e ricevimenti.',
    },
    detailRect: { x: 0.33, y: 0.10, w: 0.32, h: 0.22 },
    image: {
      commonsFile: 'File:Berkeley Women\'s City Club (Berkeley, CA).JPG',
      photographer: 'Sanfranman59',
      license: 'CC BY-SA 3.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Berkeley_Women%27s_City_Club_(Berkeley,_CA).JPG',
      width: 0,
      height: 0,
    },
    dossier: {
      en: 'The Berkeley Women\'s City Club raised the money for its own building by subscription among its members and gave the commission to Julia Morgan, then in her late fifties and deep into the campaign at San Simeon. Ground was broken in 1929 and the club opened eleven months later. Morgan built it in reinforced concrete throughout, the material her engineering degree had taught her to trust, and then made the decoration out of the same concrete, casting quatrefoils, cusped arcades and corbelled cornices into the structure instead of hanging them on it. The plan is organised around two open courtyards so that inner rooms take daylight from both sides, and the set piece is a double-height indoor pool running under a row of concrete arches. Berkeley calls it the Little Castle. It was listed on the National Register of Historic Places in 1977 and is California Historical Landmark 908.',
      es: 'El Berkeley Women\'s City Club reunió por suscripción entre sus socias el dinero para su propia sede y encargó el proyecto a Julia Morgan, que rondaba los sesenta y estaba plenamente ocupada en la campaña de San Simeón. Las obras empezaron en 1929 y el club abrió once meses después. Morgan lo construyó íntegramente en hormigón armado, el material en que su formación de ingeniera le había enseñado a confiar, e hizo la decoración con ese mismo hormigón: moldeó cuadrifolios, arquerías lobuladas y cornisas sobre ménsulas dentro de la estructura en lugar de colgarlos de ella. La planta se organiza en torno a dos patios abiertos, de modo que las piezas interiores reciben luz por dos lados, y la pieza mayor es una piscina cubierta a doble altura bajo una hilera de arcos de hormigón. En Berkeley lo llaman el Pequeño Castillo. Está en el Registro Nacional de Lugares Históricos desde 1977 y es el hito histórico de California número 908.',
      it: 'Il Berkeley Women\'s City Club raccolse per sottoscrizione fra le socie il denaro per la propria sede e affidò l\'incarico a Julia Morgan, allora quasi sessantenne e impegnata a fondo nel cantiere di San Simeon. I lavori iniziarono nel 1929 e il circolo aprì undici mesi dopo. Morgan lo costruì interamente in calcestruzzo armato, il materiale in cui la formazione da ingegnere le aveva insegnato a confidare, e con lo stesso calcestruzzo fece la decorazione: quadrilobi, arcate lobate e cornici su mensole furono gettati nella struttura anziché appesi ad essa. La pianta si organizza attorno a due cortili aperti, così che gli ambienti interni prendano luce da due lati, e il pezzo forte è una piscina coperta a doppia altezza sotto una fila di archi in calcestruzzo. A Berkeley lo chiamano il Piccolo Castello. È nel Registro nazionale dei luoghi storici dal 1977 ed è California Historical Landmark numero 908.',
    },
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q4891996', title: 'Berkeley City Club (Q4891996)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Berkeley_City_Club', title: 'Berkeley City Club', license: 'CC BY-SA 4.0' },
      { kind: 'institution', url: 'https://berkeleycityclubconservancy.org/berkeley-city-club-building/', title: 'Berkeley City Club Conservancy — Our Building', license: null },
    ],
    tier: 'deep',
  },
  {
    id: 'solomon-r-guggenheim-museum',
    wikidataId: 'Q201469',
    name: {
      en: 'Solomon R. Guggenheim Museum',
      es: 'Museo Solomon R. Guggenheim',
      it: 'Museo Solomon R. Guggenheim',
    },
    architectId: 'frank-lloyd-wright',
    location: { city: 'New York, New York', countryCode: 'US', lat: 40.783056, lon: -73.958889 },
    inception: 1956,
    completed: 1959,
    demolished: null,
    typology: 'cultural',
    materials: ['concrete'],
    structure: {
      en: 'One continuous reinforced-concrete ramp spirals up the inside of an inverted conical drum and works structurally as a shallow arch, holding the gallery walls apart under a twelve-sided glazed dome.',
      es: 'Una única rampa continua de hormigón armado asciende en espiral por el interior de un tambor cónico invertido y trabaja estructuralmente como un arco rebajado, manteniendo separados los muros de sala bajo una cúpula acristalada de doce lados.',
      it: 'Un\'unica rampa continua di calcestruzzo armato sale a spirale dentro un tamburo conico rovesciato e lavora strutturalmente come un arco ribassato, tenendo distanziate le pareti della galleria sotto una cupola vetrata a dodici lati.',
    },
    program: {
      en: 'Built for the Solomon R. Guggenheim Foundation to show Guggenheim\'s collection of non-objective painting, on a brief from its first director Hilla Rebay for a temple of spirit.',
      es: 'Construido para la Fundación Solomon R. Guggenheim con el fin de exhibir su colección de pintura no objetiva, según el encargo de su primera directora, Hilla Rebay, de levantar un templo del espíritu.',
      it: 'Costruito per la Fondazione Solomon R. Guggenheim per esporre la sua collezione di pittura non oggettiva, su richiesta della prima direttrice Hilla Rebay di realizzare un tempio dello spirito.',
    },
    heritage: 'unesco',
    currentUse: {
      en: 'Art museum operated by the Solomon R. Guggenheim Foundation.',
      es: 'Museo de arte gestionado por la Fundación Solomon R. Guggenheim.',
      it: 'Museo d\'arte gestito dalla Fondazione Solomon R. Guggenheim.',
    },
    detailRect: { x: 0.44, y: 0.17, w: 0.30, h: 0.28 },
    image: {
      commonsFile: 'File:NYC - Guggenheim Museum.jpg',
      photographer: 'Jean-Christophe BENOIST',
      license: 'CC BY 3.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:NYC_-_Guggenheim_Museum.jpg',
      width: 0,
      height: 0,
    },
    dossier: {
      en: 'Wright took the commission in June 1943 and spent fifteen years on it, some seven hundred sketches and six sets of working drawings, dying six months before it opened. The idea never changed: one continuous ramp winding up the inside of a drum that widens as it rises, lit from a glazed dome. Visitors were to ride to the top and walk down, so that the pictures arrived as an uninterrupted sequence with the whole void always open beside them. Painters objected before a wall was hung — a curved, sloping, low surface is a hostile place for a rectangle — and twenty-one artists signed a letter of protest in 1956. Wright was unmoved, and the building has outlasted the argument. The ramp is structural as well as circulatory, acting as an arch that braces the outer wall. It became a National Historic Landmark in 2008 and part of a UNESCO World Heritage inscription of eight Wright buildings in 2019.',
      es: 'Wright aceptó el encargo en junio de 1943 y le dedicó quince años, unos setecientos croquis y seis juegos de planos de obra; murió seis meses antes de la inauguración. La idea nunca cambió: una única rampa continua que asciende por dentro de un tambor que se ensancha al subir, iluminado por una cúpula acristalada. El visitante debía subir en ascensor y bajar caminando, de modo que los cuadros llegaran en una secuencia ininterrumpida con el vacío entero siempre abierto a su lado. Los pintores protestaron antes de que se colgara nada —una superficie curva, inclinada y baja es un lugar hostil para un rectángulo— y veintiún artistas firmaron una carta de protesta en 1956. Wright no se inmutó, y el edificio ha sobrevivido a la polémica. La rampa es tanto estructura como recorrido: funciona como arco que arriostra el muro exterior. Es National Historic Landmark desde 2008 y desde 2019 forma parte de la inscripción en el Patrimonio Mundial de ocho obras de Wright.',
      it: 'Wright accettò l\'incarico nel giugno 1943 e vi dedicò quindici anni, circa settecento schizzi e sei serie di disegni esecutivi; morì sei mesi prima dell\'inaugurazione. L\'idea non cambiò mai: un\'unica rampa continua che sale dentro un tamburo che si allarga salendo, illuminato da una cupola vetrata. Il visitatore doveva salire in ascensore e scendere a piedi, così che i quadri arrivassero in una sequenza ininterrotta con l\'intero vuoto sempre aperto accanto a lui. I pittori protestarono prima ancora che si appendesse qualcosa — una superficie curva, inclinata e bassa è un luogo ostile per un rettangolo — e ventuno artisti firmarono una lettera di protesta nel 1956. Wright non si mosse, e l\'edificio è sopravvissuto alla polemica. La rampa è insieme struttura e percorso: lavora come arco che controventa il muro esterno. È National Historic Landmark dal 2008 e dal 2019 fa parte dell\'iscrizione UNESCO di otto opere di Wright.',
    },
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q201469', title: 'Solomon R. Guggenheim Museum (Q201469)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Solomon_R._Guggenheim_Museum', title: 'Solomon R. Guggenheim Museum', license: 'CC BY-SA 4.0' },
      { kind: 'institution', url: 'https://whc.unesco.org/en/list/1496/', title: 'UNESCO World Heritage List — The 20th-Century Architecture of Frank Lloyd Wright', license: null },
    ],
    tier: 'canon',
  },
  {
    id: 'salk-institute',
    wikidataId: 'Q128635401',
    name: {
      en: 'Salk Institute for Biological Studies',
      es: 'Instituto Salk de Estudios Biológicos',
      it: 'Salk Institute for Biological Studies',
    },
    architectId: 'louis-kahn',
    location: { city: 'La Jolla, San Diego, California', countryCode: 'US', lat: 32.887396, lon: -117.245343 },
    inception: 1962,
    completed: 1965,
    demolished: null,
    typology: 'educational',
    materials: ['concrete', 'timber'],
    structure: {
      en: 'Post-tensioned columns carry Vierendeel trusses spanning about nineteen metres, so each laboratory floor is free of columns and has a full-height service storey above it; the concrete was mixed with volcanic ash on a Roman recipe.',
      es: 'Pilares postesados soportan vigas Vierendeel de unos diecinueve metros de luz, de modo que cada planta de laboratorio queda libre de soportes y tiene encima un piso de instalaciones de altura completa; el hormigón se amasó con ceniza volcánica siguiendo una receta romana.',
      it: 'Pilastri post-tesi reggono travi Vierendeel di circa diciannove metri di luce, così che ogni piano di laboratorio resti privo di sostegni e abbia sopra di sé un piano impiantistico ad altezza intera; il calcestruzzo fu impastato con cenere vulcanica secondo una ricetta romana.',
    },
    program: {
      en: 'A biological research campus for Jonas Salk, who asked for laboratories that could be rebuilt at will and a place he would be willing to invite Picasso to.',
      es: 'Campus de investigación biológica para Jonas Salk, que pidió laboratorios reconfigurables a voluntad y un lugar al que no le diera reparo invitar a Picasso.',
      it: 'Campus di ricerca biologica per Jonas Salk, che chiese laboratori riconfigurabili a piacere e un luogo in cui non gli dispiacesse invitare Picasso.',
    },
    heritage: 'regional',
    currentUse: {
      en: 'Working research institute in biology, genetics and neuroscience.',
      es: 'Instituto de investigación en activo en biología, genética y neurociencia.',
      it: 'Istituto di ricerca in attività in biologia, genetica e neuroscienze.',
    },
    detailRect: { x: 0.12, y: 0.05, w: 0.22, h: 0.45 },
    image: {
      commonsFile: 'File:Louis Kahn\'s Salk Institute - 3040455466.jpg',
      photographer: 'Jason Taellious',
      license: 'CC BY-SA 2.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Louis_Kahn%27s_Salk_Institute_-_3040455466.jpg',
      width: 0,
      height: 0,
    },
    dossier: {
      en: 'Salk gave Kahn two instructions: laboratories that could be rebuilt without stopping the science, and somewhere he would be willing to invite Picasso. Kahn answered the first by putting a full-height truss floor above every laboratory, so that pipes and ducts could be rerun overhead without touching the benches, and by removing the offices from the labs altogether into separate study towers, each turned forty-five degrees so its teak-framed window catches the Pacific. He answered the second with the court between the two blocks. It was to be a garden until Luis Barragán, brought in to advise, told him to plant nothing: the space should be a plaza, a facade to the sky. What is there instead is travertine, a single narrow channel of water running west, and the horizon. The concrete was poured with volcanic ash and left exactly as the formwork released it, tie-holes and board marks included. The AIA gave the building its Twenty-five Year Award in 1992.',
      es: 'Salk dio a Kahn dos instrucciones: laboratorios que pudieran rehacerse sin detener la investigación, y un lugar al que no le diera reparo invitar a Picasso. A lo primero respondió colocando sobre cada laboratorio un piso entero de vigas por el que rehacer conductos e instalaciones sin tocar las mesas de trabajo, y sacando los despachos de los laboratorios a torres de estudio independientes, giradas cuarenta y cinco grados para que su ventana enmarcada en teca mire al Pacífico. A lo segundo respondió con el patio entre los dos bloques. Iba a ser un jardín hasta que Luis Barragán, llamado como asesor, le dijo que no plantara nada: aquello debía ser una plaza, una fachada al cielo. Lo que hay es travertino, un solo canal estrecho de agua corriendo hacia el oeste y el horizonte. El hormigón se vertió con ceniza volcánica y se dejó tal como lo soltó el encofrado, con los agujeros de los tirantes y las marcas de las tablas. El AIA le dio en 1992 su Premio de los Veinticinco Años.',
      it: 'Salk diede a Kahn due istruzioni: laboratori rifacibili senza fermare la ricerca, e un luogo in cui non gli dispiacesse invitare Picasso. Alla prima rispose collocando sopra ogni laboratorio un piano intero di travi in cui rifare condotte e impianti senza toccare i banconi, e togliendo del tutto gli uffici dai laboratori per portarli in torri-studio separate, ruotate di quarantacinque gradi perché la loro finestra incorniciata in teak guardi il Pacifico. Alla seconda rispose con la corte fra i due blocchi. Doveva essere un giardino, finché Luis Barragán, chiamato come consulente, non gli disse di non piantare nulla: quello spazio doveva essere una piazza, una facciata verso il cielo. Al suo posto ci sono il travertino, un solo stretto canale d\'acqua diretto a ovest e l\'orizzonte. Il calcestruzzo fu gettato con cenere vulcanica e lasciato come il cassero l\'aveva liberato, con i fori dei tiranti e i segni delle tavole. L\'AIA gli assegnò nel 1992 il Twenty-five Year Award.',
    },
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q128635401', title: 'Salk Institute for Biological Studies building (Q128635401)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Salk_Institute_for_Biological_Studies', title: 'Salk Institute for Biological Studies', license: 'CC BY-SA 4.0' },
      { kind: 'institution', url: 'https://www.salk.edu/about/visiting-salk/architecture/', title: 'Salk Institute — Architecture', license: null },
    ],
    tier: 'canon',
  },
  {
    id: 'habitat-67',
    wikidataId: 'Q1032248',
    name: {
      en: 'Habitat 67',
      es: 'Habitat 67',
      it: 'Habitat 67',
    },
    architectId: 'moshe-safdie',
    location: { city: 'Montréal, Québec', countryCode: 'CA', lat: 45.500000, lon: -73.543889 },
    inception: 1965,
    completed: 1967,
    demolished: null,
    typology: 'housing',
    materials: ['concrete'],
    structure: {
      en: '354 precast reinforced-concrete boxes are stacked up to twelve storeys and locked together with post-tensioning rods and steel cables, each box carrying those above it and roofing the terrace of the one below.',
      es: '354 cajas prefabricadas de hormigón armado se apilan hasta doce plantas y se traban entre sí con barras postesadas y cables de acero; cada caja soporta las que tiene encima y cubre la terraza de la de abajo.',
      it: '354 scatole prefabbricate di calcestruzzo armato sono impilate fino a dodici piani e serrate fra loro con barre post-tese e cavi d\'acciaio; ogni scatola regge quelle sovrastanti e copre la terrazza di quella sottostante.',
    },
    program: {
      en: 'A demonstration housing scheme for Expo 67, financed by the Canadian Corporation for the 1967 World Exhibition; a limited partnership of the residents took the complex over from the federal housing agency in the mid-1980s.',
      es: 'Conjunto residencial de demostración para la Expo 67, financiado por la Canadian Corporation for the 1967 World Exhibition; a mediados de los años ochenta una sociedad en comandita de los residentes se lo quedó a la agencia federal de vivienda.',
      it: 'Complesso residenziale dimostrativo per l\'Expo 67, finanziato dalla Canadian Corporation for the 1967 World Exhibition; a metà degli anni ottanta una società in accomandita dei residenti lo rilevò dall\'agenzia federale per l\'edilizia.',
    },
    heritage: 'regional',
    currentUse: {
      en: 'Private apartments owned by a limited partnership of the residents; guided tours run in summer.',
      es: 'Viviendas privadas en manos de una sociedad limitada formada por los propios residentes; en verano se realizan visitas guiadas.',
      it: 'Appartamenti privati di proprietà di una società in accomandita dei residenti; d\'estate si svolgono visite guidate.',
    },
    detailRect: { x: 0.30, y: 0.12, w: 0.30, h: 0.34 },
    image: {
      commonsFile: 'File:Habitat 67, 2600, avenue Pierre-Dupuy (Ville-Marie) (35399872943).jpg',
      photographer: 'Denis Tremblay (Parcours riverain — Ville de Montréal)',
      license: 'CC BY 2.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Habitat_67,_2600,_avenue_Pierre-Dupuy_(Ville-Marie)_(35399872943).jpg',
      width: 0,
      height: 0,
    },
    dossier: {
      en: 'Safdie\'s master\'s thesis at McGill asked whether prefabrication could give an apartment the two things a suburban house has and a slab block does not: a garden and daylight from more than one side. Habitat 67 is that thesis built, on a pier in the Saint Lawrence, for the world\'s fair, by an architect of twenty-eight. Three hundred and fifty-four concrete boxes were cast on site, fitted out complete with bathrooms and kitchens on the ground, craned into place and post-tensioned together by the engineer August Komendant into a stepped mass twelve storeys high. The stagger is the whole argument: each of the 158 dwellings as built takes the roof of the box below as a private terrace and gets light from several directions, and walkways thread through the block. The last section was not finished until 1970. The economics never repeated, since the units cost far more than public housing could carry, but the building filled and stayed full. Montréal cited it as a heritage building in 2007 and Québec classified it in 2009.',
      es: 'La tesis de máster de Safdie en McGill se preguntaba si la prefabricación podía dar a un piso las dos cosas que tiene una casa suburbana y no tiene un bloque en lámina: jardín y luz por más de un lado. Habitat 67 es esa tesis construida, sobre un espigón del San Lorenzo, para la exposición universal, por un arquitecto de veintiocho años. Trescientas cincuenta y cuatro cajas de hormigón se fundieron en obra, se equiparon a pie de suelo con baños y cocinas, se izaron con grúa y las unió mediante postesado el ingeniero August Komendant en una masa escalonada de doce plantas. El escalonamiento es todo el argumento: cada una de las 158 viviendas construidas toma como terraza privada la cubierta de la caja inferior y recibe luz por varios lados, y pasarelas peatonales atraviesan el conjunto. La última sección no se terminó hasta 1970. Los números no volvieron a cuadrar —cada unidad costó mucho más de lo que la vivienda pública podía asumir—, pero el edificio se ocupó y siguió ocupado. Montreal lo citó como inmueble patrimonial en 2007 y Quebec lo clasificó en 2009.',
      it: 'La tesi di master di Safdie alla McGill si chiedeva se la prefabbricazione potesse dare a un appartamento le due cose che una casa suburbana ha e una stecca non ha: un giardino e luce da più di un lato. Habitat 67 è quella tesi costruita, su un molo del San Lorenzo, per l\'esposizione universale, da un architetto di ventotto anni. Trecentocinquantaquattro scatole di calcestruzzo furono gettate in cantiere, allestite a terra complete di bagni e cucine, sollevate con la gru e unite per post-tensione dall\'ingegnere August Komendant in una massa a gradoni di dodici piani. Lo sfalsamento è tutto l\'argomento: ciascuna delle 158 abitazioni realizzate prende come terrazza privata la copertura della scatola sottostante e riceve luce da più direzioni, e passerelle pedonali attraversano il complesso. L\'ultima sezione fu ultimata solo nel 1970. I conti non tornarono più — ogni unità costò assai più di quanto l\'edilizia pubblica potesse sostenere — ma l\'edificio si riempì e restò pieno. Montréal lo ha citato come immobile patrimoniale nel 2007 e il Quebec lo ha classificato nel 2009.',
    },
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q1032248', title: 'Habitat 67 (Q1032248)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Habitat_67', title: 'Habitat 67', license: 'CC BY-SA 4.0' },
      { kind: 'institution', url: 'https://www.patrimoine-culturel.gouv.qc.ca/rpcq/detail.do?methode=consulter&id=98890&type=bien', title: 'Répertoire du patrimoine culturel du Québec — Habitat 67', license: null },
    ],
    tier: 'canon',
  },
  {
    id: 'dulles-main-terminal',
    wikidataId: 'Q136544402',
    name: {
      en: 'Dulles International Airport Main Terminal',
      es: 'Terminal principal del Aeropuerto Internacional de Dulles',
      it: 'Terminal principale dell\'Aeroporto Internazionale di Dulles',
    },
    architectId: 'eero-saarinen',
    location: { city: 'Dulles, Virginia', countryCode: 'US', lat: 38.952778, lon: -77.447778 },
    inception: 1960,
    completed: 1962,
    demolished: null,
    typology: 'infrastructure',
    materials: ['concrete', 'steel-and-glass'],
    structure: {
      en: 'A roof of precast concrete panels hangs in a catenary from inch-thick steel cables at ten-foot centres, slung between two rows of outward-leaning concrete piers, sixty-five feet high on the airfield side and forty on the approach.',
      es: 'Una cubierta de paneles prefabricados de hormigón cuelga en catenaria de cables de acero de una pulgada dispuestos cada tres metros, tendidos entre dos filas de pilas de hormigón inclinadas hacia fuera, de veinte metros del lado del campo de vuelo y doce del lado de la llegada.',
      it: 'Una copertura di pannelli prefabbricati in calcestruzzo pende a catenaria da cavi d\'acciaio da un pollice posti ogni tre metri, tesi fra due file di piloni in calcestruzzo inclinati verso l\'esterno, alti venti metri sul lato pista e dodici sul lato arrivi.',
    },
    program: {
      en: 'The landside terminal of a new international airport for Washington, built by the Federal Aviation Agency and served by mobile lounges that drove passengers out to aircraft parked on the apron.',
      es: 'Terminal de lado tierra de un nuevo aeropuerto internacional para Washington, construido por la Federal Aviation Agency y servido por salas móviles que llevaban a los pasajeros hasta los aviones estacionados en plataforma.',
      it: 'Terminal lato terra di un nuovo aeroporto internazionale per Washington, costruito dalla Federal Aviation Agency e servito da sale mobili che portavano i passeggeri fino agli aerei fermi in piazzale.',
    },
    heritage: 'none',
    currentUse: {
      en: 'Working airport terminal, operated by the Metropolitan Washington Airports Authority.',
      es: 'Terminal aeroportuaria en servicio, gestionada por la Metropolitan Washington Airports Authority.',
      it: 'Terminal aeroportuale in servizio, gestito dalla Metropolitan Washington Airports Authority.',
    },
    detailRect: { x: 0.22, y: 0.43, w: 0.30, h: 0.22 },
    image: {
      commonsFile: 'File:Washington Dulles International Airport at Dusk.jpg',
      photographer: 'Joe Ravi',
      license: 'CC BY-SA 3.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Washington_Dulles_International_Airport_at_Dusk.jpg',
      width: 0,
      height: 0,
    },
    dossier: {
      en: 'Saarinen described the terminal as a huge continuous hammock suspended between concrete trees, which is close to literally what it is. Two colonnades of piers lean outward against the pull of the roof; between them run steel cables carrying precast concrete panels, so the roof sags in the middle and lifts at both edges. There are no columns in the hall. The section does the work signage usually does: arriving traffic comes in under the low side, the ceiling rises toward the airfield, and the glass wall delivers the runways. Saarinen also proposed to abolish the walk to the aircraft, with mobile lounges driving passengers out to planes on the apron — an idea that survives at Dulles and almost nowhere else. He died in September 1961, fourteen months before the dedication. Skidmore, Owings and Merrill extended the building from 600 to 1,240 feet between 1996 and 2000, the length Saarinen had drawn in the first place.',
      es: 'Saarinen describió la terminal como una enorme hamaca continua colgada entre árboles de hormigón, que es casi literalmente lo que es. Dos columnatas de pilas se inclinan hacia fuera contra el tiro de la cubierta; entre ellas corren cables de acero que sostienen paneles prefabricados de hormigón, de modo que el techo se hunde en el centro y se levanta en ambos bordes. En la sala no hay un solo soporte. La sección hace el trabajo que suele hacer la señalización: el tráfico de llegada entra bajo el lado bajo, el techo asciende hacia el campo de vuelo y el muro de vidrio entrega las pistas. Saarinen propuso además suprimir el paseo hasta el avión con salas móviles que llevaran al pasaje hasta la plataforma, idea que sobrevive en Dulles y casi en ningún otro sitio. Murió en septiembre de 1961, catorce meses antes de la inauguración. Skidmore, Owings and Merrill alargó el edificio de 183 a 378 metros entre 1996 y 2000, la longitud que Saarinen había dibujado desde el principio.',
      it: 'Saarinen descrisse il terminal come un\'enorme amaca continua sospesa fra alberi di calcestruzzo, che è quasi letteralmente ciò che è. Due colonnati di piloni si inclinano verso l\'esterno contro il tiro della copertura; fra loro corrono cavi d\'acciaio che reggono pannelli prefabbricati in calcestruzzo, così che il tetto si abbassi al centro e si sollevi ai due bordi. Nella sala non c\'è un solo sostegno. La sezione fa il lavoro che di solito tocca alla segnaletica: il traffico in arrivo entra sotto il lato basso, il soffitto sale verso il campo di volo e la parete di vetro consegna le piste. Saarinen propose inoltre di abolire il percorso verso l\'aereo con sale mobili che portassero i passeggeri in piazzale, un\'idea sopravvissuta a Dulles e quasi in nessun altro luogo. Morì nel settembre 1961, quattordici mesi prima dell\'inaugurazione. Skidmore, Owings and Merrill allungò l\'edificio da 183 a 378 metri fra il 1996 e il 2000, la misura che Saarinen aveva disegnato fin dall\'inizio.',
    },
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q136544402', title: 'Dulles International Airport Main Terminal (Q136544402)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Dulles_International_Airport_Main_Terminal', title: 'Dulles International Airport Main Terminal', license: 'CC BY-SA 4.0' },
      { kind: 'institution', url: 'https://www.docomomo-us.org/register/washington-dulles-international-airport-main-terminal', title: 'Docomomo US Register — Washington Dulles International Airport Main Terminal', license: null },
    ],
    tier: 'canon',
  },
  {
    id: 'aqua-tower',
    wikidataId: 'Q622895',
    name: {
      en: 'Aqua Tower',
      es: 'Torre Aqua',
      it: 'Aqua Tower',
    },
    architectId: 'jeanne-gang',
    location: { city: 'Chicago, Illinois', countryCode: 'US', lat: 41.886497, lon: -87.619711 },
    inception: 2007,
    completed: 2009,
    demolished: null,
    typology: 'tower',
    materials: ['concrete', 'steel-and-glass'],
    structure: {
      en: 'An ordinary reinforced-concrete frame with a rectangular core; each of the eighty-two floor slabs is cut to a different outline and cantilevers between two and twelve feet, nine inches thick at the root and tapering to a thin edge.',
      es: 'Una estructura corriente de hormigón armado con núcleo rectangular; cada uno de los ochenta y dos forjados se recorta con un perfil distinto y vuela entre sesenta centímetros y casi cuatro metros, con veintitrés centímetros de canto en el arranque que se afinan hasta el borde.',
      it: 'Una comune struttura in calcestruzzo armato con nucleo rettangolare; ciascuna delle ottantadue solette è ritagliata secondo un profilo diverso e sbalza fra sessanta centimetri e quasi quattro metri, con ventitré centimetri di spessore all\'attacco che si assottigliano verso il bordo.',
    },
    program: {
      en: 'A mixed-use tower with a hotel on the lower floors, rental apartments in the middle and condominiums above, developed on Chicago\'s New Eastside by Magellan Development Group.',
      es: 'Torre de usos mixtos con hotel en las plantas bajas, apartamentos de alquiler en las intermedias y viviendas en propiedad arriba, promovida en el New Eastside de Chicago por Magellan Development Group.',
      it: 'Torre a usi misti con albergo ai piani bassi, appartamenti in affitto a quelli intermedi e residenze in proprietà in alto, promossa nel New Eastside di Chicago da Magellan Development Group.',
    },
    heritage: 'none',
    currentUse: {
      en: 'Hotel, rental apartments and condominiums, with shops at street level.',
      es: 'Hotel, apartamentos de alquiler y viviendas en propiedad, con comercios a pie de calle.',
      it: 'Albergo, appartamenti in affitto e residenze in proprietà, con negozi a piano strada.',
    },
    detailRect: { x: 0.30, y: 0.25, w: 0.34, h: 0.34 },
    image: {
      commonsFile: 'File:Aqua building, Chicago (3560163510).jpg',
      photographer: 'JohnPickenPhoto',
      license: 'CC BY 2.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Aqua_building,_Chicago_(3560163510).jpg',
      width: 0,
      height: 0,
    },
    dossier: {
      en: 'The site is boxed in by taller neighbours, so Gang designed the balconies to reach past them. Each slab edge was drawn to give particular apartments a sightline — to the lake, to Millennium Park, down a specific street — and the results were then smoothed into a continuous topography running the full eighty-two floors. Nothing about the structure is unusual: a concrete frame, a rectangular core, flat plates. That was the economy of it, since the variation lives only in the formwork at the slab edge, and the tower was built for the cost of a conventional one. The projections do several jobs at once. They shade the glass in summer, break up the wind that would otherwise organise into a vortex against a tower this slender, and give birds a visible obstacle instead of a mirror. At 262 metres it was, when it opened in 2009, the tallest building in the world designed by a woman.',
      es: 'El solar está encajonado entre vecinos más altos, así que Gang diseñó los balcones para que los sortearan. Cada borde de forjado se trazó para dar a determinados apartamentos una línea de vista —al lago, al Millennium Park, por una calle concreta— y los resultados se suavizaron después hasta formar una topografía continua que recorre las ochenta y dos plantas. Nada en la estructura es insólito: pórtico de hormigón, núcleo rectangular, losas planas. Ahí estaba la economía del asunto, porque la variación vive solo en el encofrado del borde, y la torre se construyó por el coste de una convencional. Los vuelos hacen varias cosas a la vez: dan sombra al vidrio en verano, rompen el viento que de otro modo se organizaría en un torbellino contra una torre tan esbelta y ofrecen a las aves un obstáculo visible en lugar de un espejo. Con 262 metros era, al inaugurarse en 2009, el edificio más alto del mundo proyectado por una mujer.',
      it: 'Il lotto è incastrato fra vicini più alti, così Gang ha progettato i balconi perché li scavalcassero. Ogni bordo di soletta è stato tracciato per dare a determinati appartamenti una linea di vista — al lago, al Millennium Park, lungo una via precisa — e i risultati sono poi stati raccordati in una topografia continua che percorre tutti gli ottantadue piani. Nulla nella struttura è insolito: telaio in calcestruzzo, nucleo rettangolare, solette piane. Lì stava la sua economia, perché la variazione vive soltanto nel cassero del bordo, e la torre è costata quanto una convenzionale. Gli aggetti fanno più cose insieme: ombreggiano il vetro d\'estate, spezzano il vento che altrimenti si organizzerebbe in un vortice contro una torre tanto snella e offrono agli uccelli un ostacolo visibile invece di uno specchio. Con i suoi 262 metri era, all\'apertura nel 2009, l\'edificio più alto al mondo progettato da una donna.',
    },
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q622895', title: 'Aqua (Q622895)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Aqua_(Chicago)', title: 'Aqua (Chicago)', license: 'CC BY-SA 4.0' },
      { kind: 'institution', url: 'https://studiogang.com/project/aqua-tower', title: 'Studio Gang — Aqua Tower', license: null },
    ],
    tier: 'canon',
  },
];
