import type { Building } from '@/types/building';

// Eastern Asia slice (Japan, China, South Korea, Taiwan, Hong Kong, Mongolia).
//
// Every `image.license` below was read off the live Commons file page named in
// `image.sourceUrl`, not inferred from the file being hosted on Commons.
// `image.width`/`height` are left at 0 for Task 10 to record.
export const ASIA_BUILDINGS: Building[] = [
  {
    id: 'hwaseong-fortress',
    wikidataId: 'Q482423',
    name: {
      en: 'Hwaseong Fortress',
      es: 'Fortaleza de Hwaseong',
      it: 'Fortezza di Hwaseong',
    },
    architectId: 'jeong-yak-yong',
    location: { city: 'Suwon', countryCode: 'KR', lat: 37.2807, lon: 127.0102 },
    inception: 1794,
    completed: 1796,
    demolished: null,
    typology: 'infrastructure',
    materials: ['stone', 'brick'],
    structure: {
      en: 'A piled-stone rampart 5.74 km long, following the topography and carrying fired-brick parapets, ravelins, arched watergates and timber gate pavilions on stone bases.',
      es: 'Una muralla de piedra apilada de 5,74 km que sigue la topografía y sostiene parapetos de ladrillo cocido, revellines, compuertas abovedadas y pabellones de puerta de madera sobre basamentos pétreos.',
      it: 'Una cinta di pietra a secco lunga 5,74 km che segue la topografia e regge parapetti in mattone cotto, rivellini, chiuse ad arco e padiglioni-porta lignei su basamenti in pietra.',
    },
    program: {
      en: 'Built for King Jeongjo to defend and administer a new city at Suwon, to form a new political base for his reign, and to honour the relocated remains of his father, Crown Prince Sado.',
      es: 'Levantada por orden del rey Jeongjo para defender y administrar una nueva ciudad en Suwon, formar una nueva base política para su reinado y honrar los restos trasladados de su padre, el príncipe heredero Sado.',
      it: 'Eretta per volere del re Jeongjo per difendere e amministrare una nuova città a Suwon, formare una nuova base politica per il suo regno e onorare le spoglie trasferite del padre, il principe ereditario Sado.',
    },
    heritage: 'unesco',
    currentUse: {
      en: 'A public monument and urban park still enclosing central Suwon; the walls, gates and watergates are open to walk.',
      es: 'Monumento público y parque urbano que sigue rodeando el centro de Suwon; murallas, puertas y compuertas son transitables.',
      it: 'Monumento pubblico e parco urbano che cinge tuttora il centro di Suwon; mura, porte e chiuse sono percorribili.',
    },
    detailRect: { x: 0.22, y: 0.40, w: 0.34, h: 0.32 },
    image: {
      commonsFile: 'File:Hwahongmun_01.jpg',
      photographer: 'Bernard Gagnon',
      license: 'CC0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Hwahongmun_01.jpg',
      width: 0,
      height: 0,
    },
    dossier: {
      en: 'Hwaseong is the one building for which a scholar remembered chiefly as a philosopher is also remembered as a designer. King Jeongjo gave the commission to Jeong Yak-yong, a scholar of the Silhak school, who compared Korean, Chinese and European fortification and returned a plan that refused the standard Korean arrangement of a town wall plus a separate mountain refuge. Instead, a single 5.74-kilometre circuit takes in the defences, the garrison and a functioning market town, following the hills where they help and crossing the flat ground where they do not. Fired brick, unusual in Korean military work, was used for parapets, ravelins and the arched watergates; a hoisting device called the geojunggi cut the cost of moving stone. The labourers were paid rather than conscripted. The photograph shows Hwahongmun, the north floodgate over the Suwoncheon, its pavilion set on a row of arched stone sluices. A ten-volume construction record published in 1801 allowed the fortress to be rebuilt accurately after the Korean War.',
      es: 'Hwaseong es la única obra por la que un erudito recordado sobre todo como filósofo lo es también como proyectista. El rey Jeongjo confió el encargo a Jeong Yak-yong, erudito de la escuela Silhak, que comparó la fortificación coreana, china y europea y devolvió un plan que rechazaba la disposición coreana habitual —muralla urbana más refugio de montaña separado—. En su lugar, un único recinto de 5,74 kilómetros abarca las defensas, la guarnición y una ciudad mercantil en funcionamiento, siguiendo las colinas donde ayudan y cruzando el llano donde no. El ladrillo cocido, inusual en la obra militar coreana, se empleó en parapetos, revellines y compuertas abovedadas; un aparejo de izado llamado geojunggi abarató el traslado de la piedra. A los obreros se les pagó en lugar de reclutarlos. La fotografía muestra Hwahongmun, la compuerta norte sobre el Suwoncheon, con su pabellón asentado sobre una hilera de arcos de desagüe en piedra. Un informe de obra en diez volúmenes publicado en 1801 permitió reconstruir la fortaleza con exactitud tras la guerra de Corea.',
      it: 'Hwaseong è l\'unica opera per cui uno studioso ricordato soprattutto come filosofo lo è anche come progettista. Il re Jeongjo affidò l\'incarico a Jeong Yak-yong, studioso della scuola Silhak, che confrontò la fortificazione coreana, cinese ed europea e restituì un piano che rifiutava la consueta soluzione coreana — cinta urbana più rifugio montano separato. Un unico circuito di 5,74 chilometri raccoglie invece le difese, la guarnigione e una città mercantile funzionante, seguendo le colline dove giovano e attraversando il piano dove non servono. Il mattone cotto, inconsueto nell\'edilizia militare coreana, fu impiegato per parapetti, rivellini e chiuse ad arco; un apparecchio di sollevamento detto geojunggi ridusse il costo di movimentare la pietra. Gli operai furono pagati anziché arruolati. La fotografia mostra Hwahongmun, la chiusa nord sul Suwoncheon, col padiglione posato su una fila di arcate-chiusa in pietra. Un resoconto di cantiere in dieci volumi pubblicato nel 1801 permise di ricostruire la fortezza con esattezza dopo la guerra di Corea.',
    },
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q482423', title: 'Hwaseong Fortress (Q482423)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Hwaseong_Fortress', title: 'Hwaseong Fortress', license: 'CC BY-SA 4.0' },
      { kind: 'institution', url: 'https://whc.unesco.org/en/list/817/', title: 'Hwaseong Fortress — UNESCO World Heritage Centre', license: null },
    ],
    tier: 'canon',
  },
  {
    id: 'presidential-office-building-taipei',
    wikidataId: 'Q55601',
    name: {
      en: 'Presidential Office Building, Taipei',
      es: 'Palacio Presidencial de Taipéi',
      it: 'Palazzo Presidenziale di Taipei',
    },
    architectId: 'uheiji-nagano',
    location: { city: 'Taipei', countryCode: 'TW', lat: 25.0400, lon: 121.5120 },
    inception: 1912,
    completed: 1919,
    demolished: null,
    typology: 'civic',
    materials: ['brick', 'stone'],
    structure: {
      en: 'A six-storey masonry block laid out as two linked squares around internal courtyards, banded in red brick and white render across a 130-metre east-facing front, with a sixty-metre tower on the central axis.',
      es: 'Un bloque de fábrica de seis plantas dispuesto como dos cuadrados enlazados en torno a patios interiores, con bandas de ladrillo rojo y revoco blanco en un frente de 130 metros orientado al este y una torre de sesenta metros en el eje central.',
      it: 'Un blocco in muratura di sei piani disposto come due quadrati collegati attorno a corti interne, fasciato di mattone rosso e intonaco bianco su un fronte di 130 metri rivolto a est, con una torre di sessanta metri sull\'asse centrale.',
    },
    program: {
      en: 'Built as the Office of the Governor-General of Taiwan, the administrative seat of Japanese colonial rule, and in use as the Office of the President of the Republic of China since 1950.',
      es: 'Construido como Oficina del Gobernador General de Taiwán, sede administrativa del dominio colonial japonés, y en uso como Oficina del Presidente de la República de China desde 1950.',
      it: 'Costruito come Ufficio del Governatore Generale di Taiwan, sede amministrativa del dominio coloniale giapponese, e in uso come Ufficio del Presidente della Repubblica di Cina dal 1950.',
    },
    heritage: 'national',
    currentUse: {
      en: 'Working office of the President of the Republic of China, with parts of the ground floor opened to public tours.',
      es: 'Sede en activo del Presidente de la República de China, con parte de la planta baja abierta a visitas públicas.',
      it: 'Sede operativa del Presidente della Repubblica di Cina, con parte del piano terra aperta alle visite.',
    },
    detailRect: { x: 0.40, y: 0.15, w: 0.20, h: 0.38 },
    image: {
      commonsFile: 'File:Taipei_Taiwan_Presidential-Office-Building-01.jpg',
      photographer: 'CEphoto, Uwe Aranas',
      license: 'CC BY-SA 3.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Taipei_Taiwan_Presidential-Office-Building-01.jpg',
      width: 0,
      height: 0,
    },
    dossier: {
      en: 'After fire destroyed the Governor-General\'s offices in 1905, the colonial administration held what is generally counted as Japan\'s first open architectural competition, in two rounds between 1906 and 1910. Uheiji Nagano\'s entry was selected; the drawings were then sent to Tokyo, where the scheme was revised and the executed design completed by Matsunosuke Moriyama, who raised the central tower from six storeys to eleven and reworked the corner turrets. Construction ran from June 1912 to March 1919. The result is a European historicist vocabulary — Renaissance, Baroque and neoclassical elements, Ionic and Corinthian columns at the porch — carried out in the red brick and white banding that Meiji-trained architects used across the empire, and turned to face east. The 60-metre tower was the tallest structure in the Taipei basin during Japanese rule. Allied bombing on 31 May 1945 struck the front left side, the main lobby and the northern sections; restoration financed by donation was completed at the end of 1948.',
      es: 'Tras el incendio que destruyó las oficinas del Gobernador General en 1905, la administración colonial convocó lo que suele contarse como el primer concurso abierto de arquitectura de Japón, en dos rondas entre 1906 y 1910. Se eligió la propuesta de Uheiji Nagano; los planos se enviaron después a Tokio, donde el proyecto se revisó y el diseño ejecutado lo completó Matsunosuke Moriyama, que elevó la torre central de seis a once plantas y rehízo los torreones de esquina. Las obras corrieron de junio de 1912 a marzo de 1919. El resultado es un vocabulario historicista europeo —elementos renacentistas, barrocos y neoclásicos, columnas jónicas y corintias en el porche— ejecutado en el ladrillo rojo con bandas blancas que los arquitectos formados en la era Meiji emplearon por todo el imperio, y orientado al este. La torre de 60 metros fue la construcción más alta de la cuenca de Taipéi durante el dominio japonés. El bombardeo aliado del 31 de mayo de 1945 alcanzó el frente izquierdo, el vestíbulo principal y las alas del norte; la restauración, costeada por donativos, concluyó a finales de 1948.',
      it: 'Dopo l\'incendio che nel 1905 distrusse gli uffici del Governatore Generale, l\'amministrazione coloniale bandì quello che di norma è considerato il primo concorso pubblico di architettura del Giappone, in due tornate fra il 1906 e il 1910. Fu scelta la proposta di Uheiji Nagano; i disegni furono poi inviati a Tokyo, dove il progetto venne rivisto e il disegno esecutivo completato da Matsunosuke Moriyama, che portò la torre centrale da sei a undici piani e rifece le torrette d\'angolo. Il cantiere andò dal giugno 1912 al marzo 1919. Ne risulta un lessico storicista europeo — elementi rinascimentali, barocchi e neoclassici, colonne ioniche e corinzie al portico — realizzato nel mattone rosso a fasce bianche che gli architetti di formazione Meiji impiegarono in tutto l\'impero, e rivolto a oriente. La torre di 60 metri fu la costruzione più alta del bacino di Taipei durante il dominio giapponese. Il bombardamento alleato del 31 maggio 1945 colpì il fronte sinistro, l\'atrio principale e le ali nord; il restauro, finanziato da donazioni, si concluse alla fine del 1948.',
    },
    context: {
      body: {
        en: 'The building was commissioned and built as the seat of the Office of the Governor-General of Taiwan, the administrative apparatus of Japanese colonial rule over Taiwan and the Pescadores from 1895 to 1945. It housed that administration from 1919 until Japan\'s surrender. Bombed by Allied aircraft during the raid on Taihoku on 31 May 1945, it was left unrepaired until the Taiwan Provincial Government began a donation-funded restoration in 1947, completed at the end of 1948 and named Chieh Shou Hall — "long live Chiang Kai-shek" — to mark the president\'s sixtieth birthday. It became the Office of the President of the Republic of China in 1950, was designated a national monument by the Ministry of the Interior in 1998, and the Chieh Shou Hall name was formally dropped in 2006.',
        es: 'El edificio se encargó y se construyó como sede de la Oficina del Gobernador General de Taiwán, el aparato administrativo del dominio colonial japonés sobre Taiwán y las Pescadores entre 1895 y 1945. Albergó esa administración desde 1919 hasta la rendición de Japón. Bombardeado por la aviación aliada durante el ataque a Taihoku del 31 de mayo de 1945, quedó sin reparar hasta que el Gobierno Provincial de Taiwán inició en 1947 una restauración costeada por donativos, terminada a finales de 1948 y bautizada Salón Chieh Shou —«larga vida a Chiang Kai-shek»— por el sexagésimo cumpleaños del presidente. Pasó a ser Oficina del Presidente de la República de China en 1950, fue declarado monumento nacional por el Ministerio del Interior en 1998 y el nombre de Salón Chieh Shou se retiró formalmente en 2006.',
        it: 'L\'edificio fu commissionato e costruito come sede dell\'Ufficio del Governatore Generale di Taiwan, l\'apparato amministrativo del dominio coloniale giapponese su Taiwan e le Pescadores dal 1895 al 1945. Ospitò quell\'amministrazione dal 1919 fino alla resa del Giappone. Colpito dagli aerei alleati durante l\'incursione su Taihoku del 31 maggio 1945, restò senza riparazioni finché nel 1947 il Governo Provinciale di Taiwan avviò un restauro finanziato da donazioni, concluso alla fine del 1948 e intitolato Sala Chieh Shou — «lunga vita a Chiang Kai-shek» — per il sessantesimo compleanno del presidente. Divenne Ufficio del Presidente della Repubblica di Cina nel 1950, fu dichiarato monumento nazionale dal Ministero dell\'Interno nel 1998 e il nome Sala Chieh Shou fu formalmente abbandonato nel 2006.',
      },
      sources: [
        { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Presidential_Office_Building,_Taipei', title: 'Presidential Office Building, Taipei', license: 'CC BY-SA 4.0' },
      ],
    },
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q55601', title: 'Presidential Office Building (Q55601)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Presidential_Office_Building,_Taipei', title: 'Presidential Office Building, Taipei', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://ja.wikipedia.org/wiki/%E9%95%B7%E9%87%8E%E5%AE%87%E5%B9%B3%E6%B2%BB', title: '長野宇平治', license: 'CC BY-SA 4.0' },
    ],
    tier: 'canon',
  },
  {
    id: 'sun-yat-sen-mausoleum',
    wikidataId: 'Q1338405',
    name: {
      en: 'Sun Yat-sen Mausoleum',
      es: 'Mausoleo de Sun Yat-sen',
      it: 'Mausoleo di Sun Yat-sen',
    },
    architectId: 'lu-yanzhi',
    location: { city: 'Nanjing', countryCode: 'CN', lat: 32.0644, lon: 118.8483 },
    inception: 1926,
    completed: 1929,
    demolished: null,
    typology: 'civic',
    materials: ['stone', 'concrete'],
    structure: {
      en: 'A stone sacrificial hall carrying the great roof profile of a Chinese palace, clad in blue glazed tile and built by Western structural technique, set at the head of a ceremonial route more than 700 metres long and a stair of 392 steps.',
      es: 'Un salón sacrificial de piedra que sostiene el gran perfil de cubierta de un palacio chino, revestido de teja vidriada azul y construido con técnica estructural occidental, en lo alto de un recorrido ceremonial de más de 700 metros y una escalera de 392 peldaños.',
      it: 'Una sala sacrificale in pietra che porta il grande profilo di copertura di un palazzo cinese, rivestita di tegole invetriate azzurre e costruita con tecnica strutturale occidentale, in cima a un percorso cerimoniale di oltre 700 metri e a una scalinata di 392 gradini.',
    },
    program: {
      en: 'A national tomb and pilgrimage route commissioned by the Nationalist government for Sun Yat-sen, whose remains were interred there on 1 June 1929.',
      es: 'Tumba nacional y recorrido de peregrinación encargados por el gobierno nacionalista para Sun Yat-sen, cuyos restos se inhumaron allí el 1 de junio de 1929.',
      it: 'Tomba nazionale e percorso di pellegrinaggio commissionati dal governo nazionalista per Sun Yat-sen, le cui spoglie vi furono tumulate il 1º giugno 1929.',
    },
    heritage: 'national',
    currentUse: {
      en: 'A national memorial site on Purple Mountain, open to visitors and used for official commemorations.',
      es: 'Recinto conmemorativo nacional en la Montaña Púrpura, abierto al público y utilizado para actos oficiales.',
      it: 'Sito commemorativo nazionale sul Monte Purpureo, aperto ai visitatori e usato per commemorazioni ufficiali.',
    },
    detailRect: { x: 0.30, y: 0.26, w: 0.40, h: 0.28 },
    image: {
      commonsFile: 'File:Hall_of_Sun_Yat-sen_Mausoleum.jpg',
      photographer: 'Jiong Sheng',
      license: 'CC BY-SA 2.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Hall_of_Sun_Yat-sen_Mausoleum.jpg',
      width: 0,
      height: 0,
    },
    dossier: {
      en: 'The competition brief of May 1925 was unusually explicit: the tomb was to be Chinese in spirit yet modern, memorial in substance, and buildable for 300,000 yuan. More than forty entries arrived; the committee chose Lü Yanzhi unanimously in September. What he delivered reads as one long ceremonial ascent rather than a building — a paifang, a gate, a stele pavilion, then a 392-step stair climbing between pines and ginkgos to a granite hall whose blue glazed roofs and white stone were taken to stand for the Nationalist flag. Beneath the palace roof profile are Western construction methods and a Beaux-Arts axial plan learned at Cornell and in Henry Murphy\'s office; the layout as a whole was drawn in the shape of an alarm bell, answering Sun\'s charge to awaken the people. Work began in January 1926, the hall and the main structures were finished in the spring of 1929 and the complex only in 1931; the final cost passed three million yuan. Lü died of cancer that March, months before Sun was interred. Liang Sicheng later argued the hall\'s proportions betrayed a borrowed rather than understood tradition.',
      es: 'Las bases del concurso de mayo de 1925 eran inusualmente explícitas: la tumba debía ser china de espíritu y a la vez moderna, y construible por 300.000 yuanes. Llegaron más de cuarenta propuestas; en septiembre el comité eligió por unanimidad la de Lü Yanzhi. Lo que entregó se lee más como un largo ascenso ceremonial que como un edificio: un paifang, una puerta, un pabellón de estela y una escalera de 392 peldaños que sube entre pinos y ginkgos hasta un salón de granito cuyas cubiertas vidriadas azules y piedra blanca se leyeron como la bandera nacionalista. Bajo el tejado palaciego hay técnica constructiva occidental y una planta axial Beaux-Arts aprendida en Cornell y con Henry Murphy; el trazado del conjunto dibuja una campana de alarma, en respuesta al mandato de Sun de despertar al pueblo. La obra empezó en enero de 1926; el salón quedó listo en la primavera de 1929 y el conjunto solo en 1931, con un coste final superior a tres millones de yuanes. Lü murió de cáncer aquel marzo, meses antes de la inhumación de Sun. Liang Sicheng sostuvo después que las proporciones del salón delataban una tradición tomada prestada, no comprendida.',
      it: 'Il bando del maggio 1925 era insolitamente esplicito: la tomba doveva essere cinese nello spirito e insieme moderna, e realizzabile con 300.000 yuan. Arrivarono oltre quaranta proposte; a settembre la commissione scelse all\'unanimità quella di Lü Yanzhi. Ciò che consegnò si legge più come una lunga ascesa cerimoniale che come un edificio: un paifang, una porta, un padiglione della stele e poi una scalinata di 392 gradini che sale tra pini e ginkgo fino a una sala di granito le cui coperture invetriate azzurre e la pietra bianca furono lette come la bandiera nazionalista. Sotto il profilo di tetto palaziale ci sono tecniche costruttive occidentali e un impianto assiale Beaux-Arts appreso alla Cornell e nello studio di Henry Murphy; il tracciato d\'insieme disegna una campana d\'allarme, in risposta all\'invito di Sun a destare il popolo. Il cantiere iniziò nel gennaio 1926; la sala fu ultimata nella primavera del 1929 e il complesso solo nel 1931, con un costo finale superiore ai tre milioni di yuan. Lü morì di cancro quel marzo, mesi prima della tumulazione di Sun. Liang Sicheng sostenne poi che le proporzioni della sala tradivano una tradizione presa in prestito, non compresa.',
    },
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q1338405', title: 'Sun Yat-sen Mausoleum (Q1338405)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Sun_Yat-sen_Mausoleum', title: 'Sun Yat-sen Mausoleum', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/L%C3%BC_Yanzhi', title: 'Lü Yanzhi', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://zh.wikipedia.org/wiki/%E4%B8%AD%E5%B1%B1%E9%99%B5', title: '中山陵', license: 'CC BY-SA 4.0' },
    ],
    tier: 'deep',
  },
  {
    id: 'hiroshima-peace-memorial-museum',
    wikidataId: 'Q1200076',
    name: {
      en: 'Hiroshima Peace Memorial Museum',
      es: 'Museo Memorial de la Paz de Hiroshima',
      it: 'Museo della Pace di Hiroshima',
    },
    architectId: 'kenzo-tange',
    location: { city: 'Hiroshima', countryCode: 'JP', lat: 34.3915, lon: 132.4531 },
    inception: 1951,
    completed: 1955,
    demolished: null,
    typology: 'cultural',
    materials: ['concrete'],
    structure: {
      en: 'A reinforced-concrete slab of two storeys with a partial mezzanine, lifted clear of the ground on pilotis and screened along its long faces by a grid of vertical concrete louvres.',
      es: 'Un prisma de hormigón armado de dos plantas con entreplanta parcial, levantado del suelo sobre pilotis y velado en sus caras largas por una retícula de lamas verticales de hormigón.',
      it: 'Un volume in cemento armato di due piani con mezzanino parziale, sollevato da terra su pilotis e schermato sui lati lunghi da una griglia di lamelle verticali in calcestruzzo.',
    },
    program: {
      en: 'Built by the city of Hiroshima to collect, preserve and display the material remains of the atomic bombing of 6 August 1945.',
      es: 'Construido por la ciudad de Hiroshima para reunir, conservar y exponer los restos materiales del bombardeo atómico del 6 de agosto de 1945.',
      it: 'Costruito dalla città di Hiroshima per raccogliere, conservare ed esporre i resti materiali del bombardamento atomico del 6 agosto 1945.',
    },
    heritage: 'national',
    currentUse: {
      en: 'Still the main hall of the Peace Memorial Museum, reopened in 2019 after seismic retrofitting and a redisplay of the collection.',
      es: 'Sigue siendo el edificio principal del Museo Memorial de la Paz, reabierto en 2019 tras un refuerzo sísmico y una nueva museografía.',
      it: 'È tuttora l\'edificio principale del Museo della Pace, riaperto nel 2019 dopo un adeguamento sismico e un riallestimento della collezione.',
    },
    detailRect: { x: 0.34, y: 0.38, w: 0.30, h: 0.18 },
    image: {
      commonsFile: 'File:Hiroshima_Peace_Memorial_Museum_20170310.jpg',
      photographer: 'そらみみ',
      license: 'CC BY-SA 4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Hiroshima_Peace_Memorial_Museum_20170310.jpg',
      width: 0,
      height: 0,
    },
    dossier: {
      en: 'Tange won the 1949 competition for the Peace Memorial Park with a scheme that was really one idea: an axis, running north from the museum through the cenotaph to the ruined dome of the Industrial Promotion Hall, so that the surviving wreck is framed for anyone standing under the building. The museum is the instrument of that view. Raised on pilotis, it leaves the ground open and lets the park pass beneath; the long elevations are shaded by concrete louvres proportioned on a set of mathematical ratios Tange used throughout. Construction began in 1951 and was suspended for three years when national funding fell short, resuming only when the city met the balance; the main hall opened on 6 August 1955, ten years after the bomb. It was among the first Japanese postwar buildings to be recognised internationally, and in 2006 the first to be designated an Important Cultural Property.',
      es: 'Tange ganó el concurso de 1949 para el Parque Memorial de la Paz con un esquema que era en realidad una sola idea: un eje que corre al norte desde el museo, atraviesa el cenotafio y llega a la cúpula en ruinas del Palacio de Promoción Industrial, de modo que el resto en pie queda encuadrado para quien se sitúe bajo el edificio. El museo es el instrumento de esa vista. Elevado sobre pilotis, deja el suelo libre y permite que el parque pase por debajo; los alzados largos se protegen con lamas de hormigón proporcionadas según razones matemáticas que Tange empleó en todo el conjunto. Las obras empezaron en 1951 y se interrumpieron tres años cuando la financiación estatal resultó insuficiente, y solo se reanudaron al asumir la ciudad la diferencia; el edificio principal abrió el 6 de agosto de 1955, diez años después de la bomba. Fue de las primeras obras japonesas de posguerra reconocidas fuera del país y, en 2006, la primera declarada Bien Cultural Importante.',
      it: 'Tange vinse il concorso del 1949 per il Parco della Pace con uno schema che era in realtà una sola idea: un asse che corre a nord dal museo, attraversa il cenotafio e raggiunge la cupola in rovina del Palazzo della Promozione Industriale, così che il rudere superstite risulta inquadrato per chi si trovi sotto l\'edificio. Il museo è lo strumento di quella vista. Sollevato su pilotis, lascia libero il suolo e fa passare il parco al di sotto; i prospetti lunghi sono schermati da lamelle in calcestruzzo proporzionate secondo rapporti matematici che Tange usò in tutto il complesso. Il cantiere iniziò nel 1951 e fu sospeso per tre anni quando il finanziamento statale si rivelò insufficiente, riprendendo solo quando la città coprì la differenza; l\'edificio principale aprì il 6 agosto 1955, dieci anni dopo la bomba. Fu tra le prime opere giapponesi del dopoguerra riconosciute all\'estero e, nel 2006, la prima dichiarata Bene Culturale Importante.',
    },
    context: {
      body: {
        en: 'The museum stands on the Nakajima district, before 1945 the busiest commercial and residential quarter of Hiroshima and, after the atomic bomb of 6 August 1945, an open field. Estimates of the direct and indirect dead run to around 140,000. The park was laid out on that ground; the ruin of the Prefectural Industrial Promotion Hall, the structure nearest the hypocentre left partly standing, was preserved as the A-Bomb Dome and inscribed on the World Heritage List on 7 December 1996. Between 1956 and 1967 part of the museum was given over to displays promoting the peaceful use of atomic energy, first for a travelling exhibition and later as an "Atomic Science Hall"; visitors complained of a split message, and the peaceful-use material was removed in May 1967.',
        es: 'El museo se levanta sobre el barrio de Nakajima, antes de 1945 el sector comercial y residencial más activo de Hiroshima y, tras la bomba atómica del 6 de agosto de 1945, un descampado. Las estimaciones de muertos directos e indirectos rondan los 140.000. El parque se trazó sobre ese terreno; la ruina del Palacio Prefectural de Promoción Industrial, la construcción más próxima al hipocentro que quedó parcialmente en pie, se conservó como Cúpula de la Bomba Atómica y se inscribió en la Lista del Patrimonio Mundial el 7 de diciembre de 1996. Entre 1956 y 1967 parte del museo se destinó a exposiciones sobre el uso pacífico de la energía atómica, primero para una muestra itinerante y luego como «Sala de Ciencia Atómica»; los visitantes se quejaron de un mensaje contradictorio y ese material se retiró en mayo de 1967.',
        it: 'Il museo sorge sul quartiere di Nakajima, prima del 1945 il settore commerciale e residenziale più animato di Hiroshima e, dopo la bomba atomica del 6 agosto 1945, un campo aperto. Le stime dei morti diretti e indiretti si aggirano sui 140.000. Il parco fu tracciato su quel terreno; il rudere del Palazzo Prefettizio della Promozione Industriale, la costruzione più vicina all\'ipocentro rimasta in parte in piedi, fu conservato come Cupola della Bomba Atomica e iscritto nella Lista del Patrimonio Mondiale il 7 dicembre 1996. Fra il 1956 e il 1967 una parte del museo fu destinata a mostre sull\'uso pacifico dell\'energia atomica, dapprima per un\'esposizione itinerante e poi come «Sala della Scienza Atomica»; i visitatori lamentarono un messaggio contraddittorio e quel materiale fu rimosso nel maggio 1967.',
      },
      sources: [
        { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Hiroshima_Peace_Memorial_Park', title: 'Hiroshima Peace Memorial Park', license: 'CC BY-SA 4.0' },
        { kind: 'wikipedia', url: 'https://ja.wikipedia.org/wiki/%E5%BA%83%E5%B3%B6%E5%B9%B3%E5%92%8C%E8%A8%98%E5%BF%B5%E8%B3%87%E6%96%99%E9%A4%A8', title: '広島平和記念資料館', license: 'CC BY-SA 4.0' },
      ],
    },
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q1200076', title: 'Hiroshima Peace Memorial Museum (Q1200076)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Hiroshima_Peace_Memorial_Museum', title: 'Hiroshima Peace Memorial Museum', license: 'CC BY-SA 4.0' },
      { kind: 'institution', url: 'http://hpmmuseum.jp/modules/info/index.php?action=PageView&page_id=20', title: 'Hiroshima Peace Memorial Museum — facility outline (施設概要)', license: null },
      { kind: 'institution', url: 'https://www.pref.hiroshima.lg.jp/soshiki_file/tatemonogatari/page001.html', title: '広島平和記念資料館（本館）— ひろしまたてものがたり (Hiroshima Prefecture)', license: null },
      { kind: 'publication', url: 'https://haruaki.shunjusha.co.jp/posts/6239', title: '岸佑「平和を創りだす——平和記念公園および広島平和記念資料館本館」web春秋 (Shunjusha)', license: null },
    ],
    tier: 'canon',
  },
  {
    id: 'nakagin-capsule-tower',
    wikidataId: 'Q1633586',
    name: {
      en: 'Nakagin Capsule Tower',
      es: 'Torre Cápsula Nakagin',
      it: 'Torre a capsule Nakagin',
    },
    architectId: 'kisho-kurokawa',
    location: { city: 'Tokyo', countryCode: 'JP', lat: 35.6656, lon: 139.7635 },
    inception: 1970,
    completed: 1972,
    demolished: 2022,
    typology: 'housing',
    materials: ['concrete', 'steel-and-glass'],
    structure: {
      en: 'Two rigid-frame cores of steel and reinforced concrete, eleven and thirteen storeys, from which 140 prefabricated steel capsules were cantilevered, each hung on four high-tension bolts and served by a flexible plumbing umbilical.',
      es: 'Dos núcleos de pórtico rígido en acero y hormigón armado, de once y trece plantas, de los que volaban 140 cápsulas prefabricadas de acero, colgada cada una de cuatro pernos de alta resistencia y servida por un cordón umbilical flexible de instalaciones.',
      it: 'Due nuclei a telaio rigido in acciaio e cemento armato, di undici e tredici piani, dai quali sporgevano a sbalzo 140 capsule prefabbricate in acciaio, appese ciascuna a quattro bulloni ad alta resistenza e servite da un cordone ombelicale flessibile.',
    },
    program: {
      en: 'A speculative mixed-use development in the Ginza district of Tokyo, sold as compact residential units and small offices.',
      es: 'Promoción especulativa de uso mixto en el barrio tokiota de Ginza, vendida como viviendas compactas y pequeñas oficinas.',
      it: 'Intervento speculativo a uso misto nel quartiere di Ginza, a Tokyo, venduto come unità residenziali compatte e piccoli uffici.',
    },
    heritage: 'none',
    currentUse: {
      en: 'Demolished in 2022; twenty-three capsules were removed for preservation and have since been restored for museum and exhibition use.',
      es: 'Demolida en 2022; se retiraron veintitrés cápsulas para su conservación y desde entonces se han restaurado con destino museístico y expositivo.',
      it: 'Demolita nel 2022; ventitré capsule furono rimosse per la conservazione e sono state poi restaurate per usi museali ed espositivi.',
    },
    detailRect: { x: 0.20, y: 0.50, w: 0.34, h: 0.26 },
    image: {
      commonsFile: 'File:Nakagin.jpg',
      photographer: 'Jordy Meow',
      license: 'CC BY-SA 3.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Nakagin.jpg',
      width: 0,
      height: 0,
    },
    dossier: {
      en: 'Metabolism proposed that a building should behave like an organism, with a durable frame and parts replaced as they wear out. Nakagin was the world\'s first built example of capsule architecture. Each capsule was an all-welded steel box of 2.5 by 2.5 by 4 metres — the dimensions, Kurokawa noted, of a traditional tea room — fitted out in a factory that also made shipping containers, trucked to Ginza and bolted to a core with four fasteners so that any one could be swapped without touching its neighbours. A single round window, 1.3 metres across, faced the street. The system was never exercised: no replacement capsule was ever manufactured and none was ever changed. The building fell into disrepair, fundraising and landmark campaigns failed, and it was demolished in 2022 after half a century. Twenty-three capsules were saved.',
      es: 'El metabolismo proponía que un edificio se comportara como un organismo, con una estructura duradera y piezas sustituibles a medida que se gastan. Nakagin fue el primer ejemplo construido de arquitectura de cápsulas del mundo. Cada cápsula era una caja de acero enteramente soldada de 2,5 por 2,5 por 4 metros —las medidas, señalaba Kurokawa, de una sala de té tradicional—, equipada en una fábrica que también hacía contenedores marítimos, transportada a Ginza y atornillada al núcleo con cuatro pernos, de modo que cualquiera pudiese cambiarse sin tocar las contiguas. Una única ventana circular de 1,3 metros daba a la calle. El sistema nunca se puso a prueba: jamás se fabricó una cápsula de repuesto ni se sustituyó ninguna. El edificio se fue degradando, fracasaron las campañas de recaudación y de protección patrimonial y se demolió en 2022, medio siglo después. Se salvaron veintitrés cápsulas.',
      it: 'Il metabolismo proponeva che un edificio si comportasse come un organismo, con una struttura durevole e parti sostituite man mano che si consumano. Nakagin fu il primo esempio costruito al mondo di architettura a capsule. Ogni capsula era una scatola d\'acciaio interamente saldata di 2,5 per 2,5 per 4 metri — le misure, notava Kurokawa, di una tradizionale stanza da tè — allestita in una fabbrica che produceva anche container, portata a Ginza e imbullonata al nucleo con quattro fissaggi, così che una qualsiasi potesse essere sostituita senza toccare le vicine. Un\'unica finestra circolare di 1,3 metri guardava la strada. Il sistema non fu mai messo alla prova: non fu mai prodotta una capsula di ricambio né se ne sostituì alcuna. L\'edificio si degradò, le raccolte fondi e le campagne per il vincolo fallirono e fu demolito nel 2022, mezzo secolo dopo. Ventitré capsule furono salvate.',
    },
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q1633586', title: 'Nakagin Capsule Tower (Q1633586)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Nakagin_Capsule_Tower', title: 'Nakagin Capsule Tower', license: 'CC BY-SA 4.0' },
    ],
    tier: 'canon',
  },
  {
    id: 'shonandai-culture-centre',
    wikidataId: 'Q11563318',
    name: {
      en: 'Shōnandai Culture Centre',
      es: 'Centro Cultural de Shōnandai',
      it: 'Centro Culturale di Shōnandai',
    },
    architectId: 'itsuko-hasegawa',
    location: { city: 'Fujisawa', countryCode: 'JP', lat: 35.3979, lon: 139.4696 },
    inception: 1987,
    completed: 1990,
    demolished: null,
    typology: 'cultural',
    materials: ['concrete', 'steel-and-glass'],
    structure: {
      en: 'Two basement levels sunk into the site and four storeys above them, carrying a landscape of light steel frames, perforated aluminium screens and two clad spheres of 37 and 23 metres diameter.',
      es: 'Dos plantas de sótano hundidas en el solar y cuatro sobre ellas, que sostienen un paisaje de estructuras ligeras de acero, pantallas de aluminio perforado y dos esferas revestidas de 37 y 23 metros de diámetro.',
      it: 'Due piani interrati affondati nel lotto e quattro piani soprastanti, che reggono un paesaggio di leggere strutture d\'acciaio, schermi di alluminio forato e due sfere rivestite di 37 e 23 metri di diametro.',
    },
    program: {
      en: 'A municipal complex for Fujisawa combining a community hall, a children\'s museum with planetarium, a 600-seat civic theatre and district administrative offices.',
      es: 'Complejo municipal de Fujisawa que reúne un centro cívico, un museo infantil con planetario, un teatro público de 600 plazas y oficinas administrativas de distrito.',
      it: 'Complesso municipale di Fujisawa che riunisce una casa di quartiere, un museo dei bambini con planetario, un teatro civico da 600 posti e uffici amministrativi di distretto.',
    },
    heritage: 'none',
    currentUse: {
      en: 'In municipal use as the Shōnandai Culture Centre, with the children\'s museum, the planetarium and the civic theatre all still running.',
      es: 'En uso municipal como Centro Cultural de Shōnandai, con el museo infantil, el planetario y el teatro público todavía en funcionamiento.',
      it: 'In uso municipale come Centro Culturale di Shōnandai, con il museo dei bambini, il planetario e il teatro civico tuttora attivi.',
    },
    detailRect: { x: 0.50, y: 0.26, w: 0.30, h: 0.30 },
    image: {
      commonsFile: 'File:Shonandai_bunka_center.JPG',
      photographer: 'Archs',
      license: 'CC BY-SA 3.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Shonandai_bunka_center.JPG',
      width: 0,
      height: 0,
    },
    dossier: {
      en: 'Hasegawa won this by competition and then had to argue for it: residents objected to a public building sunk below ground level. She spent long stretches in meetings with them, and by the time construction reached the surface the scheme had their backing. Two basement levels absorb much of the accommodation, which frees the ground to work as a public park rather than a forecourt. Above ground she assembled something closer to a metal thicket than a façade: perforated aluminium canopies on slender posts, faceted tent-like volumes, trees, water, and two spheres, one of 37 metres taking the motif of a celestial globe and holding the civic theatre, one of 23 metres taking a terrestrial globe and holding the planetarium. She called the result "second nature". After it opened she stayed on for ten years as director of its children\'s museum.',
      es: 'Hasegawa ganó el encargo por concurso y luego tuvo que defenderlo: los vecinos se oponían a un edificio público hundido bajo el nivel del suelo. Pasó largas temporadas reuniéndose con ellos y, cuando la obra asomó a la superficie, el proyecto contaba con su respaldo. Dos plantas de sótano absorben buena parte del programa, lo que libera el suelo para funcionar como parque público y no como antesala. Encima montó algo más parecido a una espesura metálica que a una fachada: marquesinas de aluminio perforado sobre soportes esbeltos, volúmenes facetados como tiendas de campaña, árboles, agua y dos esferas, una de 37 metros que toma el motivo de una esfera celeste y aloja el teatro público y otra de 23 metros que toma el globo terráqueo y alberga el planetario. Llamó al resultado «segunda naturaleza». Tras la inauguración se quedó diez años dirigiendo el museo infantil.',
      it: 'Hasegawa vinse l\'incarico per concorso e poi dovette difenderlo: gli abitanti si opponevano a un edificio pubblico affondato sotto il livello del suolo. Trascorse lunghi periodi in assemblee con loro e, quando il cantiere emerse dal suolo, il progetto aveva il loro appoggio. Due piani interrati assorbono buona parte del programma, il che libera il suolo perché funzioni da parco pubblico e non da anticamera. Sopra vi montò qualcosa di più simile a una boscaglia metallica che a una facciata: pensiline di alluminio forato su esili sostegni, volumi sfaccettati come tende, alberi, acqua e due sfere, una di 37 metri che riprende il motivo di una sfera celeste e accoglie il teatro civico e una di 23 metri che riprende il globo terrestre e ospita il planetario. Chiamò l\'esito «seconda natura». Dopo l\'apertura rimase dieci anni a dirigerne il museo dei bambini.',
    },
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q11563318', title: 'Shonandai Culture Center (Q11563318)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Itsuko_Hasegawa', title: 'Itsuko Hasegawa', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://ja.wikipedia.org/wiki/%E6%B9%98%E5%8D%97%E5%8F%B0%E6%96%87%E5%8C%96%E3%82%BB%E3%83%B3%E3%82%BF%E3%83%BC', title: '湘南台文化センター', license: 'CC BY-SA 4.0' },
    ],
    tier: 'deep',
  },
  {
    id: 'kanazawa-21st-century-museum',
    wikidataId: 'Q3242206',
    name: {
      en: '21st Century Museum of Contemporary Art, Kanazawa',
      es: 'Museo de Arte Contemporáneo del Siglo XXI de Kanazawa',
      it: 'Museo d\'arte contemporanea del XXI secolo di Kanazawa',
    },
    architectId: 'kazuyo-sejima',
    location: { city: 'Kanazawa', countryCode: 'JP', lat: 36.5608, lon: 136.6580 },
    inception: 2002,
    completed: 2004,
    demolished: null,
    typology: 'cultural',
    materials: ['steel-and-glass', 'concrete'],
    structure: {
      en: 'A circular plate 112.5 metres across, two storeys above ground and two below, wrapped in an unbroken curved glass wall of 122 panes, from which white-rendered gallery boxes of differing heights rise through the roof.',
      es: 'Una pieza circular de 112,5 metros de diámetro, con dos plantas sobre rasante y dos bajo ella, envuelta por un muro de vidrio curvo continuo de 122 paños, del que emergen a través de la cubierta cajas de sala revocadas en blanco de alturas distintas.',
      it: 'Una piastra circolare di 112,5 metri di diametro, con due piani fuori terra e due interrati, avvolta da una parete di vetro curva continua di 122 lastre, dalla quale emergono attraverso la copertura scatole espositive intonacate di bianco di altezze diverse.',
    },
    program: {
      en: 'A municipal museum of contemporary art for Kanazawa, built on the site of a former university school and split between a ticketed exhibition zone and a free public zone.',
      es: 'Museo municipal de arte contemporáneo de Kanazawa, construido en el solar de una antigua escuela universitaria y dividido entre una zona expositiva de pago y una zona pública gratuita.',
      it: 'Museo comunale d\'arte contemporanea di Kanazawa, costruito sull\'area di una ex scuola universitaria e diviso tra una zona espositiva a pagamento e una zona pubblica gratuita.',
    },
    heritage: 'none',
    currentUse: {
      en: 'A working municipal art museum, among the most visited in Japan; the city has announced a closure for services renewal and earthquake repairs from 2027.',
      es: 'Museo municipal de arte en activo, de los más visitados de Japón; la ciudad ha anunciado un cierre desde 2027 para renovar instalaciones y reparar daños sísmicos.',
      it: 'Museo civico d\'arte in attività, tra i più visitati del Giappone; la città ha annunciato una chiusura dal 2027 per rinnovare gli impianti e riparare i danni del terremoto.',
    },
    detailRect: { x: 0.30, y: 0.42, w: 0.30, h: 0.28 },
    image: {
      commonsFile: 'File:21st_Century_Museum_of_Contemporary_Art_in_Kanazawa_-_Takeshi_DSC_1132_(3872661475).jpg',
      photographer: 'Takeshi Kuboki',
      license: 'CC BY 2.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:21st_Century_Museum_of_Contemporary_Art_in_Kanazawa_-_Takeshi_DSC_1132_(3872661475).jpg',
      width: 0,
      height: 0,
    },
    dossier: {
      en: 'Kanazawa already had a formal provincial art museum, so the brief for this one asked for its opposite: a museum people would walk into without deciding to. Sejima and Nishizawa answered with a circle. There is no front and no back, no steps, no plinth; four entrances face four different streets, and the glass wall that closes the plan carries no visible frame, so from the lawn the building reads as a low disc of light with white boxes floating over it. Inside, the curators had asked for ideal rooms — square, rectangular, round, of many sizes — and SANAA scattered them across the disc as separate volumes with corridors and courtyards left over between, which is what makes the route ambiguous and the visit unrepeatable. Construction ran from April 2002 to August 2004; the museum opened that October and SANAA took the Golden Lion at Venice.',
      es: 'Kanazawa ya tenía un museo provincial de arte de corte solemne, de modo que el encargo pedía su contrario: un museo en el que se entrase sin haberlo decidido. Sejima y Nishizawa respondieron con un círculo. No hay frente ni trasera, ni escalinata, ni podio; cuatro accesos miran a cuatro calles distintas, y el muro de vidrio que cierra la planta no tiene carpintería visible, así que desde el césped el edificio se lee como un disco bajo de luz con cajas blancas flotando encima. Dentro, los conservadores habían pedido salas ideales —cuadradas, rectangulares, circulares, de muchos tamaños— y SANAA las dispersó por el disco como volúmenes sueltos, dejando pasillos y patios en los intersticios: de ahí que el recorrido sea ambiguo y la visita irrepetible. Las obras fueron de abril de 2002 a agosto de 2004; el museo abrió aquel octubre y SANAA obtuvo el León de Oro en Venecia.',
      it: 'Kanazawa aveva già un museo d\'arte provinciale di taglio solenne, e il programma chiedeva dunque il suo contrario: un museo in cui si entrasse senza averlo deciso. Sejima e Nishizawa risposero con un cerchio. Non c\'è fronte né retro, né gradinata, né basamento; quattro ingressi guardano quattro strade diverse, e la parete di vetro che chiude la pianta non ha telai a vista, così che dal prato l\'edificio si legge come un basso disco di luce con scatole bianche sospese sopra. All\'interno i curatori avevano chiesto sale ideali — quadrate, rettangolari, circolari, di molte misure — e SANAA le sparpagliò sul disco come volumi separati, lasciando corridoi e corti negli interstizi: per questo il percorso è ambiguo e la visita irripetibile. Il cantiere andò dall\'aprile 2002 all\'agosto 2004; il museo aprì quell\'ottobre e SANAA ottenne il Leone d\'Oro a Venezia.',
    },
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q3242206', title: '21st Century Museum of Contemporary Art (Q3242206)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/21st_Century_Museum_of_Contemporary_Art,_Kanazawa', title: '21st Century Museum of Contemporary Art, Kanazawa', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://ja.wikipedia.org/wiki/%E9%87%91%E6%B2%A221%E4%B8%96%E7%B4%80%E7%BE%8E%E8%A1%93%E9%A4%A8', title: '金沢21世紀美術館', license: 'CC BY-SA 4.0' },
      { kind: 'publication', url: 'https://archinect.com/news/article/7083/eisenman-and-sanaa-awarded-at-biennale', title: 'Eisenman and SANAA — Awarded at Biennale (Archinect, 2004)', license: null },
    ],
    tier: 'canon',
  },
  {
    id: 'ningbo-museum',
    wikidataId: 'Q1070226',
    name: {
      en: 'Ningbo Museum',
      es: 'Museo de Ningbo',
      it: 'Museo di Ningbo',
    },
    architectId: 'wang-shu',
    location: { city: 'Ningbo', countryCode: 'CN', lat: 29.8174, lon: 121.5412 },
    inception: 2006,
    completed: 2008,
    demolished: null,
    typology: 'cultural',
    materials: ['brick', 'concrete', 'stone'],
    structure: {
      en: 'A concrete block 144 metres long, 65 wide and 24 high whose upper floors split into five leaning masses, faced either in salvaged brick and tile laid up as wapan walling or in concrete cast against bamboo formwork.',
      es: 'Un bloque de hormigón de 144 metros de largo, 65 de ancho y 24 de alto cuyas plantas superiores se escinden en cinco masas inclinadas, revestidas con ladrillo y teja recuperados en aparejo wapan o con hormigón encofrado contra bambú.',
      it: 'Un blocco in calcestruzzo lungo 144 metri, largo 65 e alto 24, i cui piani superiori si scindono in cinque masse inclinate, rivestite di mattoni e tegole di recupero in apparecchio wapan oppure di calcestruzzo gettato contro casseforme di bambù.',
    },
    program: {
      en: 'A municipal museum of the history and folk customs of the Ningbo region, built for the city and Yinzhou district on a cleared site in a new administrative centre.',
      es: 'Museo municipal de la historia y las costumbres populares de la región de Ningbo, construido para la ciudad y el distrito de Yinzhou en un solar despejado de un nuevo centro administrativo.',
      it: 'Museo comunale della storia e delle tradizioni popolari della regione di Ningbo, costruito per la città e il distretto di Yinzhou su un\'area sgombrata di un nuovo centro amministrativo.',
    },
    heritage: 'none',
    currentUse: {
      en: 'A working municipal museum, rated a national first-grade museum by the State Administration of Cultural Heritage in 2012.',
      es: 'Museo municipal en activo, calificado como museo nacional de primer grado por la Administración Estatal de Patrimonio Cultural en 2012.',
      it: 'Museo comunale in attività, classificato museo nazionale di primo grado dall\'Amministrazione Statale del Patrimonio Culturale nel 2012.',
    },
    detailRect: { x: 0.34, y: 0.38, w: 0.30, h: 0.30 },
    image: {
      commonsFile: 'File:South_Gate_of_Ningbo_Museum.jpg',
      photographer: 'Siyuwj',
      license: 'CC BY-SA 3.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:South_Gate_of_Ningbo_Museum.jpg',
      width: 0,
      height: 0,
    },
    dossier: {
      en: 'The site was a district of villages until it was cleared for a new administrative centre, leaving the museum standing more than a hundred metres from anything else. Wang Shu\'s response was to make an object with its own horizon: a solid base of three floors that splits, higher up, into five leaning masses read as a fragment of mountain, with a stepped valley cut into the south side after the manner of Northern Song landscape painting. The surface is the argument. Bricks, roof tiles and stones salvaged from the demolished villages were handed to the masons, who laid them up in wapan, the regional technique used to rebuild after typhoons; where walls lean away from vertical the cladding is instead concrete cast against bamboo, which leaves the cane grain in the surface. Windows are scattered without alignment. Construction began on 31 August 2006 and the museum opened on 5 December 2008.',
      es: 'El emplazamiento fue un conjunto de aldeas hasta que se arrasó para levantar un nuevo centro administrativo, de modo que el museo quedó a más de cien metros de cualquier otra cosa. La respuesta de Wang Shu fue construir un objeto con horizonte propio: una base maciza de tres plantas que, más arriba, se escinde en cinco masas inclinadas leídas como un fragmento de montaña, con un valle escalonado abierto en el lado sur a la manera de la pintura de paisaje Song del Norte. La superficie es el argumento. Ladrillos, tejas y piedras recuperados de las aldeas derribadas se entregaron a los albañiles, que los asentaron en wapan, la técnica regional con que se reconstruía tras los tifones; donde los muros se apartan de la vertical, el revestimiento es hormigón encofrado contra bambú, que deja la fibra de la caña impresa. Las ventanas se dispersan sin alineación. La obra empezó el 31 de agosto de 2006 y el museo abrió el 5 de diciembre de 2008.',
      it: 'L\'area era un insieme di villaggi finché non fu sgombrata per un nuovo centro amministrativo, lasciando il museo a più di cento metri da qualsiasi altra cosa. La risposta di Wang Shu fu costruire un oggetto con un orizzonte proprio: un basamento massiccio di tre piani che, più in alto, si scinde in cinque masse inclinate lette come frammento di montagna, con una valle a gradoni incisa sul lato sud alla maniera della pittura di paesaggio Song settentrionale. La superficie è l\'argomento. Mattoni, tegole e pietre recuperati dai villaggi demoliti furono consegnati ai muratori, che li posarono in wapan, la tecnica regionale con cui si ricostruiva dopo i tifoni; dove le pareti si scostano dalla verticale il rivestimento è invece calcestruzzo gettato contro il bambù, che ne lascia impressa la fibra. Le finestre sono sparse senza allineamenti. Il cantiere iniziò il 31 agosto 2006 e il museo aprì il 5 dicembre 2008.',
    },
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q1070226', title: 'Ningbo Museum (Q1070226)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Ningbo_Museum', title: 'Ningbo Museum', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://zh.wikipedia.org/wiki/%E5%AE%81%E6%B3%A2%E5%8D%9A%E7%89%A9%E9%A6%86', title: '宁波博物馆', license: 'CC BY-SA 4.0' },
    ],
    tier: 'canon',
  },
];
