import type { Building } from '@/types/building';

// Wave 5 curator agent (France, Belgium, Netherlands, Luxembourg, Monaco): real, sourced Building entries for this slice.
//
// Freedom of panorama shapes this slice more than any other in Europe. France
// and Monaco have no FoP that is compatible with a free licence, so every
// French entry below is a building whose architect died well over seventy
// years ago. Belgium gained a genuine FoP exception on 15 July 2016
// (Art. XI.190, 2/1° of the Code of Economic Law) and the Netherlands has one
// under Art. 18 Auteurswet, so the modern and post-2000 entries come from
// those two countries and every one of them uses an EXTERIOR photograph.
// Luxembourg has no FoP (only incidental inclusion) and is therefore absent.
//
// `image.width` / `image.height` are left at 0 for a later pass to record.
export const EUROPE_WEST_BUILDINGS: Building[] = [
  // --- pre-1800 ---------------------------------------------------------
  {
    id: 'royal-saltworks-arc-et-senans',
    wikidataId: 'Q649055',
    name: {
      en: 'Royal Saltworks at Arc-et-Senans',
      es: 'Salinas Reales de Arc-et-Senans',
      it: 'Saline Reali di Arc-et-Senans',
    },
    architectId: 'claude-nicolas-ledoux',
    location: { city: 'Arc-et-Senans', countryCode: 'FR', lat: 47.03278, lon: 5.77778 },
    inception: 1775,
    completed: 1779,
    demolished: null,
    typology: 'industrial',
    materials: ['stone'],
    structure: {
      en: 'Load-bearing limestone ranges roofed in timber are set on a half-circle, with the director\'s house carrying a giant portico of unfluted, banded Doric columns over a rusticated ground storey.',
      es: 'Crujías portantes de piedra caliza con cubierta de madera se disponen sobre un semicírculo, y la casa del director levanta un pórtico gigante de columnas dóricas anilladas y sin estrías sobre una planta baja almohadillada.',
      it: 'Corpi portanti in pietra calcarea con coperture lignee sono disposti su un semicerchio, e la casa del direttore regge un portico gigante di colonne doriche bugnate e prive di scanalature sopra un piano terreno a bugnato.',
    },
    program: {
      en: 'Built for the royal salt monopoly of Louis XVI to boil brine piped twenty-one kilometres from Salins-les-Bains, it housed the works, its offices and the lodgings of everyone employed there.',
      es: 'Construida para el monopolio real de la sal de Luis XVI, hervía salmuera traída por conducto desde Salins-les-Bains, veintiún kilómetros más allá, y alojaba la fábrica, sus oficinas y las viviendas de todos sus empleados.',
      it: 'Costruita per il monopolio regio del sale di Luigi XVI, faceva bollire la salamoia condotta per ventun chilometri da Salins-les-Bains e ospitava l\'opificio, i suoi uffici e gli alloggi di tutti gli addetti.',
    },
    heritage: 'unesco',
    currentUse: {
      en: 'A museum and cultural centre run by the Doubs department, with gardens and a permanent display of Ledoux\'s drawings.',
      es: 'Museo y centro cultural gestionado por el departamento del Doubs, con jardines y una exposición permanente de los dibujos de Ledoux.',
      it: 'Museo e centro culturale gestito dal dipartimento del Doubs, con giardini e un\'esposizione permanente dei disegni di Ledoux.',
    },
    detailRect: { x: 0.34, y: 0.30, w: 0.30, h: 0.32 },
    image: {
      commonsFile: 'File:Saline royale d\'Arc-et-Senans 2 (Maison du Directeur).jpg',
      photographer: 'Einaz80',
      license: 'CC BY-SA 4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Saline_royale_d%27Arc-et-Senans_2_(Maison_du_Directeur).jpg',
      width: 1600,
      height: 1200,
    },
    dossier: {
      en: 'Ledoux was asked for a salt factory and delivered a diagram of authority. The works are laid out as a half-circle: the director\'s house on the axis, the two great evaporation sheds flanking it, the workers\' ranges bent round the arc so that every door faces the centre and nothing happens out of sight. The gatehouse is cut as an artificial grotto, petrified brine running down its jambs; the columns of the portico alternate square and cylindrical drums, a deliberate coarsening of the classical order to suit an industrial building. Only the half-circle was built. Ledoux kept redrawing the missing half as the ideal city of Chaux, adding a house for the river inspector shaped like a pipe and a cemetery buried under a sphere, and published the whole speculation in 1804. Production limped on until 1895; the site became a World Heritage Site in 1982.',
      es: 'A Ledoux le pidieron una fábrica de sal y entregó un diagrama de autoridad. El conjunto se despliega en semicírculo: la casa del director en el eje, las dos grandes naves de evaporación a sus lados y las crujías de los obreros plegadas sobre el arco, de modo que todas las puertas miran al centro y nada ocurre fuera de la vista. La portería está tallada como una gruta artificial, con salmuera petrificada resbalando por las jambas; las columnas del pórtico alternan tambores cuadrados y cilíndricos, un engrosamiento deliberado del orden clásico para una obra industrial. Solo se construyó el semicírculo. Ledoux siguió dibujando la mitad ausente como la ciudad ideal de Chaux —con una casa para el inspector del río en forma de tubo y un cementerio enterrado bajo una esfera— y publicó toda la especulación en 1804. La producción se arrastró hasta 1895; el conjunto es Patrimonio Mundial desde 1982.',
      it: 'A Ledoux fu chiesta una fabbrica di sale e consegnò uno schema di autorità. L\'impianto si dispiega a semicerchio: la casa del direttore sull\'asse, i due grandi capannoni di evaporazione ai suoi lati, i corpi degli operai piegati lungo l\'arco, così che ogni porta guardi al centro e nulla accada fuori vista. La portineria è intagliata come una grotta artificiale, con salamoia pietrificata che cola lungo gli stipiti; le colonne del portico alternano rocchi quadrati e cilindrici, un ingrossamento voluto dell\'ordine classico per un edificio industriale. Fu costruito solo il semicerchio. Ledoux continuò a ridisegnare la metà mancante come città ideale di Chaux — con una casa per l\'ispettore del fiume a forma di tubo e un cimitero sepolto sotto una sfera — e pubblicò l\'intera speculazione nel 1804. La produzione si trascinò fino al 1895; il sito è Patrimonio Mondiale dal 1982.',
    },
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q649055', title: 'Royal Saltworks at Arc-et-Senans (Q649055)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Royal_Saltworks_at_Arc-et-Senans', title: 'Royal Saltworks at Arc-et-Senans', license: 'CC BY-SA 4.0' },
      { kind: 'institution', url: 'https://whc.unesco.org/en/list/203/', title: 'From the Great Saltworks of Salins-les-Bains to the Royal Saltworks of Arc-et-Senans — UNESCO World Heritage Centre', license: null },
    ],
    tier: 'canon',
  },
  {
    id: 'chateau-de-vaux-le-vicomte',
    wikidataId: 'Q739976',
    name: {
      en: 'Château de Vaux-le-Vicomte',
      es: 'Palacio de Vaux-le-Vicomte',
      it: 'Castello di Vaux-le-Vicomte',
    },
    architectId: 'louis-le-vau',
    location: { city: 'Maincy', countryCode: 'FR', lat: 48.56583, lon: 2.71415 },
    inception: 1656,
    completed: 1661,
    demolished: null,
    typology: 'domestic',
    materials: ['stone'],
    structure: {
      en: 'A masonry block on a moated stone platform, its centre swelling into an oval salon that is pushed clear through the depth of the building and capped by a high slate dome.',
      es: 'Un bloque de fábrica sobre una plataforma de piedra rodeada de foso, cuyo centro se hincha en un salón oval que atraviesa todo el fondo del edificio y se remata con una alta cúpula de pizarra.',
      it: 'Un blocco murario su una piattaforma di pietra circondata dal fossato, il cui centro si gonfia in un salone ovale che attraversa tutta la profondità dell\'edificio ed è coronato da un\'alta cupola di ardesia.',
    },
    program: {
      en: 'A country seat for Nicolas Fouquet, Superintendent of Finances to Louis XIV, designed as much for entertaining the court as for living in.',
      es: 'Residencia de campo para Nicolas Fouquet, superintendente de Finanzas de Luis XIV, concebida tanto para agasajar a la corte como para habitarla.',
      it: 'Residenza di campagna per Nicolas Fouquet, sovrintendente alle Finanze di Luigi XIV, pensata tanto per ricevere la corte quanto per esservi abitata.',
    },
    heritage: 'national',
    currentUse: {
      en: 'Privately owned and open to the public, with the state rooms, kitchens and Le Nôtre gardens on show.',
      es: 'De propiedad privada y abierto al público, con las salas de aparato, las cocinas y los jardines de Le Nôtre visitables.',
      it: 'Di proprietà privata e aperto al pubblico, con le sale di rappresentanza, le cucine e i giardini di Le Nôtre visitabili.',
    },
    detailRect: { x: 0.36, y: 0.30, w: 0.28, h: 0.30 },
    image: {
      commonsFile: 'File:0 Maincy - Château de Vaux-le-Vicomte (2).JPG',
      photographer: 'Jean-Pol GRANDMONT',
      license: 'CC BY-SA 3.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:0_Maincy_-_Ch%C3%A2teau_de_Vaux-le-Vicomte_(2).JPG',
      width: 1600,
      height: 1067,
    },
    dossier: {
      en: 'Vaux is the building in which the three disciplines of the French grand siècle were first run as one operation. Le Vau took the plan, Charles Le Brun the painted interiors and André Le Nôtre the garden, and the three were coordinated so tightly that the oval salon reads as the hinge between a forecourt and a two-kilometre axis of water. The move that made the house famous is the salon itself: rather than sit behind the facade, it bulges through it, so the garden front is a single swelling mass under a dome instead of a flat screen of windows. Everything above is subordinate — pilasters stop, the roof breaks, the skyline steps down. Louis XIV attended the inauguration in August 1661, arrested Fouquet three weeks later, and took Le Vau, Le Brun and Le Nôtre to Versailles, where they built the same idea at four times the size.',
      es: 'Vaux es el edificio en el que las tres disciplinas del grand siècle francés funcionaron por primera vez como una sola operación. Le Vau se ocupó de la planta, Charles Le Brun de los interiores pintados y André Le Nôtre del jardín, y los tres se coordinaron tan estrechamente que el salón oval se lee como la bisagra entre el patio de honor y un eje de agua de dos kilómetros. El gesto que hizo célebre la casa es el propio salón: en lugar de quedar detrás de la fachada, sobresale a través de ella, de manera que el frente al jardín es una masa única y henchida bajo una cúpula, y no una pantalla plana de ventanas. Todo lo demás se subordina: las pilastras se detienen, la cubierta se quiebra, la silueta desciende. Luis XIV asistió a la inauguración en agosto de 1661, detuvo a Fouquet tres semanas después y se llevó a Le Vau, Le Brun y Le Nôtre a Versalles, donde repitieron la idea a cuádruple escala.',
      it: 'Vaux è l\'edificio in cui le tre discipline del grand siècle francese furono condotte per la prima volta come un\'unica operazione. Le Vau prese la pianta, Charles Le Brun gli interni dipinti e André Le Nôtre il giardino, e i tre furono coordinati così strettamente che il salone ovale si legge come cerniera fra la corte d\'onore e un asse d\'acqua di due chilometri. La mossa che rese celebre la casa è il salone stesso: invece di stare dietro la facciata, la attraversa sporgendo, sicché il fronte verso il giardino è una massa unica e rigonfia sotto una cupola, non uno schermo piatto di finestre. Tutto il resto si subordina: le lesene si arrestano, il tetto si spezza, la sagoma digrada. Luigi XIV assistette all\'inaugurazione nell\'agosto del 1661, fece arrestare Fouquet tre settimane dopo e portò Le Vau, Le Brun e Le Nôtre a Versailles, dove ripeterono la stessa idea a scala quadrupla.',
    },
    context: {
      body: {
        en: 'The estate was assembled by force and paid for from a contested purse. To clear ground for the garden Fouquet bought and demolished three villages, and the displaced villagers were then put to work maintaining the grounds; contemporary accounts put the workforce at 18,000 and the cost at as much as 16 million livres. Fouquet was arrested on 5 September 1661, three weeks after the inauguration, on charges of embezzlement and lèse-majesté brought by Jean-Baptiste Colbert, tried over three years, and sentenced to banishment — commuted by the king to life imprisonment. He died in the fortress of Pignerol in 1680. The house was sealed and its tapestries, statuary and orange trees carried off to Versailles.',
        es: 'La finca se reunió por la fuerza y se pagó con una bolsa impugnada. Para despejar el terreno del jardín, Fouquet compró y derribó tres aldeas, y los vecinos desplazados fueron después empleados en el mantenimiento de los parterres; las relaciones de la época cifran la mano de obra en 18.000 personas y el coste en hasta 16 millones de libras. Fouquet fue detenido el 5 de septiembre de 1661, tres semanas después de la inauguración, acusado de malversación y lesa majestad por Jean-Baptiste Colbert, juzgado durante tres años y condenado al destierro, pena que el rey conmutó por cadena perpetua. Murió en la fortaleza de Pignerol en 1680. La casa fue precintada y sus tapices, estatuas y naranjos trasladados a Versalles.',
        it: 'La tenuta fu messa insieme con la forza e pagata da una borsa contestata. Per liberare il terreno del giardino Fouquet acquistò e demolì tre villaggi, e gli abitanti sfollati furono poi impiegati nella manutenzione dei parterre; le cronache coeve stimano la manodopera in 18.000 persone e il costo fino a 16 milioni di lire. Fouquet fu arrestato il 5 settembre 1661, tre settimane dopo l\'inaugurazione, con l\'accusa di malversazione e lesa maestà mossa da Jean-Baptiste Colbert, processato per tre anni e condannato all\'esilio, pena commutata dal re in carcere a vita. Morì nella fortezza di Pinerolo nel 1680. La casa fu posta sotto sigilli e i suoi arazzi, le statue e gli aranci trasferiti a Versailles.',
      },
      sources: [
        { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Vaux-le-Vicomte', title: 'Vaux-le-Vicomte', license: 'CC BY-SA 4.0' },
        { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Nicolas_Fouquet', title: 'Nicolas Fouquet', license: 'CC BY-SA 4.0' },
      ],
    },
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q739976', title: 'Vaux-le-Vicomte (Q739976)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Vaux-le-Vicomte', title: 'Vaux-le-Vicomte', license: 'CC BY-SA 4.0' },
    ],
    tier: 'canon',
  },

  // --- 1800-1945 --------------------------------------------------------
  {
    id: 'hotel-tassel',
    wikidataId: 'Q1881679',
    name: {
      en: 'Hôtel Tassel',
      es: 'Casa Tassel',
      it: 'Hôtel Tassel',
    },
    architectId: 'victor-horta',
    location: { city: 'Brussels', countryCode: 'BE', lat: 50.82778, lon: 4.36203 },
    inception: 1892,
    completed: 1893,
    demolished: null,
    typology: 'domestic',
    materials: ['stone', 'steel-and-glass', 'brick'],
    structure: {
      en: 'Two conventional brick-and-stone blocks, one on the street and one on the garden, are linked by a steel-framed, glass-roofed core whose exposed iron columns carry the floors clear of any internal wall.',
      es: 'Dos cuerpos convencionales de ladrillo y piedra, uno a la calle y otro al jardín, se enlazan mediante un núcleo de estructura de acero y cubierta de vidrio cuyas columnas de hierro vistas sostienen los forjados sin necesidad de muros interiores.',
      it: 'Due corpi convenzionali in mattoni e pietra, uno sulla strada e uno sul giardino, sono collegati da un nucleo con struttura d\'acciaio e copertura vetrata, le cui colonne di ferro a vista reggono i solai senza alcun muro interno.',
    },
    program: {
      en: 'A town house for Émile Tassel, a scientist and professor at the Université libre de Bruxelles who wanted rooms for lecturing with lantern slides as well as for living.',
      es: 'Casa urbana para Émile Tassel, científico y profesor de la Universidad Libre de Bruselas, que quería estancias tanto para vivir como para dar conferencias con placas de linterna.',
      it: 'Casa urbana per Émile Tassel, scienziato e professore all\'Université libre de Bruxelles, che voleva ambienti tanto per abitare quanto per tenere conferenze con lanterne magiche.',
    },
    heritage: 'unesco',
    currentUse: {
      en: 'In private hands and used as offices; the interior is not generally open, and the building is visited from the street.',
      es: 'En manos privadas y usada como oficinas; el interior no suele estar abierto y el edificio se visita desde la calle.',
      it: 'In mani private e adibito a uffici; l\'interno non è di norma accessibile e l\'edificio si visita dalla strada.',
    },
    detailRect: { x: 0.24, y: 0.32, w: 0.48, h: 0.24 },
    image: {
      commonsFile: 'File:Victor Horta Hotel Tassel.JPG',
      photographer: 'Karl Stas',
      license: 'CC BY-SA 3.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Victor_Horta_Hotel_Tassel.JPG',
      width: 1013,
      height: 1600,
    },
    dossier: {
      en: 'The Brussels town house of the 1890s was a fixed thing: a narrow deep plot, three rooms in a row down one side, a corridor and stair on the other, and a dining room in the middle with no window. Horta broke it by treating the middle of the plot as a lit void. He put a steel-framed, top-lit hall where the dark room used to be, wound the stair around it, and let the floors step in half-levels so that the house has no single storey height. The iron is left visible and turned decorative: slender columns whose capitals spray into painted tendrils that run on across the mosaic floor and the wall stencilling, so structure and ornament are the same drawing. Émile Tassel, a scientist and university professor, wanted somewhere to give lectures, and got a house organised around the act of looking upward. It was listed in 1976 and inscribed by UNESCO in 2000.',
      es: 'La casa burguesa bruselense de los años noventa del siglo XIX era un tipo fijo: parcela estrecha y profunda, tres piezas en hilera a un lado, corredor y escalera al otro, y en medio un comedor sin ventana. Horta la rompió tratando el centro de la parcela como un vacío iluminado. Colocó donde estaba la pieza oscura un vestíbulo con estructura de acero y luz cenital, enroscó a su alrededor la escalera y dejó que los forjados escalonaran a media altura, de modo que la casa carece de una altura de planta única. El hierro queda a la vista y se vuelve ornamento: columnas esbeltas cuyos capiteles se desflecan en zarcillos pintados que continúan por el mosaico del suelo y el estarcido de los muros, de manera que estructura y decoración son el mismo dibujo. Émile Tassel, científico y profesor universitario, quería un lugar donde dar conferencias, y obtuvo una casa organizada en torno al acto de mirar hacia arriba. Fue protegida en 1976 e inscrita por la UNESCO en 2000.',
      it: 'La casa borghese bruxellese degli anni Novanta dell\'Ottocento era un tipo fisso: lotto stretto e profondo, tre stanze in fila su un lato, corridoio e scala sull\'altro, e in mezzo una sala da pranzo senza finestre. Horta lo ruppe trattando il centro del lotto come un vuoto illuminato. Dove stava la stanza buia mise un atrio con struttura d\'acciaio e luce zenitale, vi avvolse attorno la scala e lasciò che i solai sfalsassero di mezzo piano, sicché la casa non ha un\'unica altezza di piano. Il ferro resta a vista e diventa ornamento: colonne snelle i cui capitelli si sfrangiano in viticci dipinti che proseguono sul mosaico del pavimento e sugli stencil delle pareti, così che struttura e decorazione siano lo stesso disegno. Émile Tassel, scienziato e professore universitario, voleva un luogo dove tenere conferenze, e ottenne una casa organizzata attorno all\'atto di guardare in alto. Fu vincolata nel 1976 e iscritta dall\'UNESCO nel 2000.',
    },
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q1881679', title: 'Hôtel Tassel (Q1881679)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/H%C3%B4tel_Tassel', title: 'Hôtel Tassel', license: 'CC BY-SA 4.0' },
      { kind: 'institution', url: 'https://whc.unesco.org/en/list/1005/', title: 'Major Town Houses of the Architect Victor Horta (Brussels) — UNESCO World Heritage Centre', license: null },
    ],
    tier: 'canon',
  },
  {
    id: 'rietveld-schroder-house',
    wikidataId: 'Q914231',
    name: {
      en: 'Rietveld Schröder House',
      es: 'Casa Rietveld Schröder',
      it: 'Casa Rietveld Schröder',
    },
    architectId: 'gerrit-rietveld',
    location: { city: 'Utrecht', countryCode: 'NL', lat: 52.08533, lon: 5.14760 },
    inception: 1923,
    completed: 1924,
    demolished: null,
    typology: 'domestic',
    materials: ['brick', 'timber', 'steel-and-glass'],
    structure: {
      en: 'Load-bearing brick and rendered plaster below, timber floors and roof above, with slender steel sections taking the corners so that the glazing can open away and leave the corner unsupported.',
      es: 'Fábrica de ladrillo revocada y portante abajo, forjados y cubierta de madera arriba, y perfiles de acero esbeltos en las esquinas para que el acristalamiento pueda abrirse y dejar el ángulo sin apoyo.',
      it: 'Muratura portante in mattoni intonacata in basso, solai e copertura in legno in alto, con esili profili d\'acciaio agli spigoli perché le vetrate possano aprirsi lasciando l\'angolo privo di sostegno.',
    },
    program: {
      en: 'A house for Truus Schröder-Schräder, recently widowed, and her three children, who asked for living space that could be opened up or divided as the day required.',
      es: 'Casa para Truus Schröder-Schräder, recién enviudada, y sus tres hijos, que pidió un espacio de estar capaz de abrirse o dividirse según lo exigiera el día.',
      it: 'Casa per Truus Schröder-Schräder, da poco vedova, e i suoi tre figli, che chiese uno spazio di vita capace di aprirsi o dividersi secondo le ore della giornata.',
    },
    heritage: 'unesco',
    currentUse: {
      en: 'A house museum run by the Centraal Museum Utrecht, visited by timed guided tour.',
      es: 'Casa museo gestionada por el Centraal Museum de Utrecht, visitable con visita guiada y hora concertada.',
      it: 'Casa museo gestita dal Centraal Museum di Utrecht, visitabile con visita guidata a orario.',
    },
    detailRect: { x: 0.33, y: 0.28, w: 0.32, h: 0.34 },
    image: {
      commonsFile: 'File:Exterieur overzicht zuidwest- en zuidoostgevel - Utrecht - 20322899 - RCE.jpg',
      photographer: 'A. J. van der Wal',
      license: 'CC BY-SA 4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Exterieur_overzicht_zuidwest-_en_zuidoostgevel_-_Utrecht_-_20322899_-_RCE.jpg',
      width: 1592,
      height: 1600,
    },
    dossier: {
      en: 'The house stands at the blind end of a brick terrace and refuses to acknowledge it. Rietveld composed the exterior as separate planes and bars — white and grey slabs, a red rail, a yellow post — arranged so that none of them closes a corner; each slides past the next and stops in mid-air. The upper floor, declared an attic to satisfy the fire regulations, is a single open zone that a system of sliding and pivoting partitions can convert into three bedrooms, a bathroom and a sitting room in a few minutes, or back again. Truus Schröder-Schräder commissioned it, worked on the design alongside Rietveld, and lived in it until she died in 1985; both regarded the dissolving of fixed rooms as a way of dissolving fixed family hierarchies. It became a national monument in 1976 and a World Heritage Site in 2000, and it remains the clearest built statement of De Stijl.',
      es: 'La casa se levanta en el extremo ciego de una hilera de ladrillo y se niega a reconocerla. Rietveld compuso el exterior como planos y barras sueltos —losas blancas y grises, un pasamanos rojo, un montante amarillo— dispuestos de modo que ninguno cierre una esquina: cada uno se desliza junto al siguiente y se detiene en el aire. La planta alta, declarada desván para cumplir las ordenanzas de incendios, es una única zona abierta que un sistema de tabiques correderos y pivotantes convierte en pocos minutos en tres dormitorios, un baño y una sala, y viceversa. Truus Schröder-Schräder encargó la casa, trabajó en el proyecto junto a Rietveld y vivió en ella hasta su muerte en 1985; ambos entendían la disolución de las habitaciones fijas como una manera de disolver las jerarquías familiares fijas. Es monumento nacional desde 1976 y Patrimonio Mundial desde 2000, y sigue siendo el enunciado construido más claro de De Stijl.',
      it: 'La casa sorge all\'estremità cieca di una schiera di mattoni e si rifiuta di riconoscerla. Rietveld compose l\'esterno come piani e aste separati — lastre bianche e grigie, un corrimano rosso, un montante giallo — disposti in modo che nessuno chiuda uno spigolo: ciascuno scorre accanto al successivo e si arresta a mezz\'aria. Il piano superiore, dichiarato sottotetto per soddisfare i regolamenti antincendio, è un\'unica zona aperta che un sistema di pareti scorrevoli e girevoli trasforma in pochi minuti in tre camere, un bagno e un soggiorno, e viceversa. Truus Schröder-Schräder commissionò la casa, lavorò al progetto accanto a Rietveld e vi abitò fino alla morte nel 1985; entrambi consideravano lo scioglimento delle stanze fisse un modo di sciogliere le gerarchie familiari fisse. È monumento nazionale dal 1976 e Patrimonio Mondiale dal 2000, e resta l\'enunciato costruito più limpido di De Stijl.',
    },
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q914231', title: 'Rietveld Schröder House (Q914231)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Rietveld_Schr%C3%B6der_House', title: 'Rietveld Schröder House', license: 'CC BY-SA 4.0' },
      { kind: 'institution', url: 'https://whc.unesco.org/en/list/965/', title: 'Rietveld Schröderhuis (Rietveld Schröder House) — UNESCO World Heritage Centre', license: null },
    ],
    tier: 'canon',
  },
  {
    id: 'van-nelle-factory',
    wikidataId: 'Q2328849',
    name: {
      en: 'Van Nelle Factory',
      es: 'Factoría Van Nelle',
      it: 'Fabbrica Van Nelle',
    },
    architectId: 'leendert-van-der-vlugt',
    coArchitects: ['johannes-brinkman'],
    location: { city: 'Rotterdam', countryCode: 'NL', lat: 51.92278, lon: 4.43361 },
    inception: 1925,
    completed: 1931,
    demolished: null,
    typology: 'industrial',
    materials: ['concrete', 'steel-and-glass'],
    structure: {
      en: 'A reinforced-concrete frame of mushroom-headed columns, engineered with J. G. Wiebenga, is set back from the perimeter so the glass curtain wall hangs free of it across every floor.',
      es: 'Una estructura de hormigón armado con pilares de capitel en seta, calculada con J. G. Wiebenga, retranqueada del perímetro para que el muro cortina de vidrio cuelgue libre de ella en todas las plantas.',
      it: 'Un telaio in cemento armato con pilastri a fungo, calcolato con J. G. Wiebenga, arretrato rispetto al perimetro perché la parete continua vetrata penda libera davanti a esso su tutti i piani.',
    },
    program: {
      en: 'A factory for the Van Nelle company, commissioned by its co-owner Cees van der Leeuw, to roast, blend and pack coffee, tea and tobacco and dispatch them by canal, road and rail.',
      es: 'Fábrica de la compañía Van Nelle, encargada por su copropietario Cees van der Leeuw, para tostar, mezclar y envasar café, té y tabaco y despacharlos por canal, carretera y ferrocarril.',
      it: 'Fabbrica della società Van Nelle, commissionata dal comproprietario Cees van der Leeuw, per torrefare, miscelare e confezionare caffè, tè e tabacco e spedirli per canale, strada e ferrovia.',
    },
    heritage: 'unesco',
    currentUse: {
      en: 'Converted from 2000 under Wessel de Jonge into offices, studios, a co-working centre and an events venue.',
      es: 'Rehabilitada desde el año 2000 bajo la dirección de Wessel de Jonge como oficinas, estudios, centro de trabajo compartido y espacio para eventos.',
      it: 'Riconvertita dal 2000 sotto la direzione di Wessel de Jonge in uffici, studi, spazio di coworking e sede per eventi.',
    },
    detailRect: { x: 0.30, y: 0.30, w: 0.32, h: 0.32 },
    image: {
      commonsFile: 'File:Rotterdam van nelle fabriek.jpg',
      photographer: 'F.Eveleens',
      license: 'CC BY 3.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Rotterdam_van_nelle_fabriek.jpg',
      width: 1600,
      height: 1026,
    },
    dossier: {
      en: 'Van Nelle is a factory built as an argument that industrial work deserves daylight. Three production blocks of decreasing height line an internal road; each is a concrete frame whose columns stand back from the edge, so the floor slabs cantilever and the entire perimeter can be glazed as a continuous hung skin — claimed as the first industrially prefabricated curtain wall. Enclosed conveyor bridges leap diagonally across the space between the blocks and the despatch building, turning the movement of goods into the only ornament on the site. UNESCO credits the result to a purpose agreed in common between the entrepreneur — the co-owner Cees van der Leeuw — and his architects and engineers: daylight used to make working conditions pleasant. Le Corbusier called it the most beautiful spectacle of the modern age in 1932. Production stopped in 1996 and UNESCO inscribed the site in 2014.',
      es: 'Van Nelle es una fábrica construida como argumento a favor de que el trabajo industrial merece luz natural. Tres bloques de producción de altura decreciente flanquean una calle interior; cada uno es una estructura de hormigón cuyos pilares se retiran del borde, de modo que los forjados vuelan y todo el perímetro puede acristalarse como una piel colgada continua, reivindicada como el primer muro cortina prefabricado industrialmente. Puentes transportadores cerrados saltan en diagonal entre los bloques y el edificio de expediciones, y convierten el movimiento de la mercancía en el único ornamento del conjunto. La UNESCO atribuye el resultado a un propósito acordado en común entre el empresario —el copropietario Cees van der Leeuw— y sus arquitectos e ingenieros: la luz natural empleada para hacer gratas las condiciones de trabajo. Le Corbusier la llamó en 1932 el espectáculo más bello de la era moderna. La producción cesó en 1996 y la UNESCO inscribió el conjunto en 2014.',
      it: 'Van Nelle è una fabbrica costruita come argomento a favore del fatto che il lavoro industriale meriti luce naturale. Tre corpi di produzione di altezza decrescente fiancheggiano una strada interna; ciascuno è un telaio di calcestruzzo i cui pilastri arretrano dal bordo, così che i solai sporgano a sbalzo e l\'intero perimetro possa essere vetrato come una pelle appesa continua, rivendicata come la prima parete continua prefabbricata industrialmente. Ponti trasportatori chiusi scavalcano in diagonale lo spazio fra i corpi e l\'edificio delle spedizioni, trasformando il movimento delle merci nell\'unico ornamento del complesso. L\'UNESCO attribuisce il risultato a uno scopo concordato in comune fra l\'imprenditore — il comproprietario Cees van der Leeuw — e i suoi architetti e ingegneri: la luce naturale usata per rendere gradevoli le condizioni di lavoro. Le Corbusier la definì nel 1932 lo spettacolo più bello dell\'età moderna. La produzione cessò nel 1996 e l\'UNESCO iscrisse il sito nel 2014.',
    },
    context: {
      body: {
        en: 'The goods the building was designed around came out of colonial agriculture. UNESCO\'s own Statement of Outstanding Universal Value credits the factory with bearing witness to "the long port-related economic tradition of the Netherlands, in the processing of imported food products (coffee, tea and tobacco) and their marketing in Europe." In the 1920s and 1930s the Dutch trade in all three ran overwhelmingly through the Netherlands East Indies, whose plantation economy had been built on the compulsory-cultivation and indenture systems of the nineteenth century. The architecture of the daylit factory floor and the conditions on the estates that supplied it belong to the same enterprise, and the World Heritage listing is for the Rotterdam end of it.',
        es: 'Las mercancías en torno a las que se proyectó el edificio procedían de la agricultura colonial. La propia declaración de valor universal excepcional de la UNESCO atribuye a la fábrica ser testimonio de «la larga tradición económica portuaria de los Países Bajos en el procesado de productos alimentarios importados (café, té y tabaco) y su comercialización en Europa». En los años veinte y treinta el comercio neerlandés de los tres pasaba de manera abrumadora por las Indias Orientales Neerlandesas, cuya economía de plantación se había levantado sobre los sistemas decimonónicos de cultivo forzoso y trabajo por contrata. La arquitectura de la nave iluminada por el día y las condiciones de las haciendas que la abastecían pertenecen a la misma empresa, y la inscripción en el Patrimonio Mundial abarca solo el extremo roterdamés.',
        it: 'Le merci attorno a cui l\'edificio fu progettato venivano dall\'agricoltura coloniale. La stessa dichiarazione di valore universale eccezionale dell\'UNESCO attribuisce alla fabbrica di essere testimonianza della «lunga tradizione economica portuale dei Paesi Bassi nella lavorazione di prodotti alimentari importati (caffè, tè e tabacco) e nella loro commercializzazione in Europa». Negli anni Venti e Trenta il commercio olandese di tutti e tre passava in massima parte per le Indie orientali olandesi, la cui economia di piantagione si era costruita sui sistemi ottocenteschi di coltura obbligatoria e di lavoro a contratto vincolato. L\'architettura del piano di fabbrica illuminato dal giorno e le condizioni delle tenute che lo rifornivano appartengono alla stessa impresa, e l\'iscrizione nel Patrimonio Mondiale copre solo il capo di Rotterdam.',
      },
      sources: [
        { kind: 'institution', url: 'https://whc.unesco.org/en/list/1441/', title: 'Van Nellefabriek — UNESCO World Heritage Centre, Outstanding Universal Value', license: 'CC BY-SA IGO 3.0' },
        { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Van_Nelle_Factory', title: 'Van Nelle Factory', license: 'CC BY-SA 4.0' },
        { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Cultivation_System', title: 'Cultivation System', license: 'CC BY-SA 4.0' },
      ],
    },
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q2328849', title: 'Van Nelle Factory (Q2328849)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Van_Nelle_Factory', title: 'Van Nelle Factory', license: 'CC BY-SA 4.0' },
      { kind: 'institution', url: 'https://whc.unesco.org/en/list/1441/', title: 'Van Nellefabriek — UNESCO World Heritage Centre', license: 'CC BY-SA IGO 3.0' },
    ],
    tier: 'canon',
  },

  // --- 1945-2000 --------------------------------------------------------
  {
    id: 'burgerweeshuis-amsterdam',
    wikidataId: 'Q2787387',
    name: {
      en: 'Amsterdam Municipal Orphanage (Burgerweeshuis)',
      es: 'Orfanato Municipal de Ámsterdam (Burgerweeshuis)',
      it: 'Orfanotrofio municipale di Amsterdam (Burgerweeshuis)',
    },
    architectId: 'aldo-van-eyck',
    location: { city: 'Amsterdam', countryCode: 'NL', lat: 52.34056, lon: 4.85611 },
    inception: 1955,
    completed: 1960,
    demolished: null,
    typology: 'civic',
    materials: ['concrete', 'brick'],
    structure: {
      en: 'A field of 328 small prefabricated concrete domes, plus a handful of larger ones, carried on concrete columns and beams over walls of concrete block and glass.',
      es: 'Un campo de 328 pequeñas cúpulas prefabricadas de hormigón, con algunas mayores, sostenidas por pilares y vigas de hormigón sobre muros de bloque y vidrio.',
      it: 'Un campo di 328 piccole cupole prefabbricate in calcestruzzo, più alcune maggiori, rette da pilastri e travi di calcestruzzo su pareti di blocchi e vetro.',
    },
    program: {
      en: 'Built for the Amsterdam civic orphanage, which had outgrown its house on the Kalverstraat, to lodge and school its children in eight separate age groups.',
      es: 'Construido para el orfanato municipal de Ámsterdam, que se había quedado pequeño en su sede de la Kalverstraat, para alojar y escolarizar a sus niños en ocho grupos de edad separados.',
      it: 'Costruito per l\'orfanotrofio civico di Amsterdam, ormai troppo grande per la sua sede in Kalverstraat, per ospitare e istruire i suoi bambini in otto distinti gruppi d\'età.',
    },
    heritage: 'national',
    currentUse: {
      en: 'No longer an orphanage; after a threatened demolition and a restoration it houses offices and a design school, and is a listed national monument.',
      es: 'Ya no es orfanato: tras una amenaza de derribo y una restauración alberga oficinas y una escuela de diseño, y está declarado monumento nacional.',
      it: 'Non è più orfanotrofio: dopo una minaccia di demolizione e un restauro ospita uffici e una scuola di design, ed è monumento nazionale vincolato.',
    },
    detailRect: { x: 0.32, y: 0.36, w: 0.32, h: 0.30 },
    image: {
      commonsFile: 'File:Overzicht - Amsterdam - 20355871 - RCE.jpg',
      photographer: 'Gerard Dukker',
      license: 'CC BY-SA 4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Overzicht_-_Amsterdam_-_20355871_-_RCE.jpg',
      width: 1600,
      height: 1061,
    },
    dossier: {
      en: 'Van Eyck had spent a decade building playgrounds in bomb sites when Amsterdam asked him for an orphanage, and he refused to design an institution. Instead he laid out a low, almost single-storey settlement: 328 small precast domes on a square grid, gathered into eight houses for eight age groups, each with its own kitchen, its own courtyard and its own front door onto an internal street. Nothing is a corridor; every route is a place, and the joints between the units are treated as thresholds — a step, a low wall, a circular sitting pit — rather than as doorways. The building was the founding text of Dutch Structuralism and the point at which the Team 10 argument against functionalist planning became something you could stand inside. It was threatened with demolition in the 1980s, saved after an international campaign, and listed in 2014.',
      es: 'Van Eyck llevaba una década construyendo parques infantiles en solares bombardeados cuando Ámsterdam le pidió un orfanato, y se negó a proyectar una institución. En su lugar trazó un asentamiento bajo, casi de una sola planta: 328 pequeñas cúpulas prefabricadas sobre una retícula cuadrada, agrupadas en ocho casas para ocho grupos de edad, cada una con cocina propia, patio propio y puerta propia a una calle interior. Nada es pasillo: todo recorrido es un lugar, y las juntas entre las unidades se tratan como umbrales —un escalón, un murete, un pozo circular para sentarse— y no como puertas. El edificio fue el texto fundacional del estructuralismo neerlandés y el momento en que el alegato del Team 10 contra el urbanismo funcionalista se convirtió en algo por dentro de lo cual se podía estar. Amenazado de derribo en los años ochenta, se salvó tras una campaña internacional y fue protegido en 2014.',
      it: 'Van Eyck costruiva parchi gioco su terreni bombardati da un decennio quando Amsterdam gli chiese un orfanotrofio, e lui rifiutò di progettare un\'istituzione. Tracciò invece un insediamento basso, quasi a un solo piano: 328 piccole cupole prefabbricate su una griglia quadrata, raccolte in otto case per otto gruppi d\'età, ciascuna con cucina propria, corte propria e porta propria su una strada interna. Nulla è corridoio: ogni percorso è un luogo, e i giunti fra le unità sono trattati come soglie — un gradino, un muretto, una conca circolare per sedersi — e non come passaggi. L\'edificio fu il testo fondativo dello strutturalismo olandese e il momento in cui l\'argomento del Team 10 contro l\'urbanistica funzionalista divenne qualcosa in cui si poteva stare dentro. Minacciato di demolizione negli anni Ottanta, fu salvato dopo una campagna internazionale e vincolato nel 2014.',
    },
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q2787387', title: 'Burgerweeshuis (Q2787387)', license: null },
      { kind: 'wikipedia', url: 'https://nl.wikipedia.org/wiki/Burgerweeshuis_(Amsterdam,_IJsbaanpad)', title: 'Burgerweeshuis (Amsterdam, IJsbaanpad)', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Aldo_van_Eyck', title: 'Aldo van Eyck', license: 'CC BY-SA 4.0' },
    ],
    tier: 'canon',
  },
  {
    id: 'centraal-beheer-apeldoorn',
    wikidataId: 'Q2200376',
    name: {
      en: 'Centraal Beheer Office Building',
      es: 'Edificio de oficinas Centraal Beheer',
      it: 'Edificio per uffici Centraal Beheer',
    },
    architectId: 'herman-hertzberger',
    location: { city: 'Apeldoorn', countryCode: 'NL', lat: 52.20929, lon: 5.96007 },
    inception: 1967,
    completed: 1972,
    demolished: null,
    typology: 'commercial',
    materials: ['concrete'],
    structure: {
      en: 'Fifty-six concrete-block towers, each roughly nine metres square, carry prefabricated concrete floor units and are stacked in four staggered levels around top-lit slots of circulation.',
      es: 'Cincuenta y seis torres de bloque de hormigón, de unos nueve metros de lado cada una, sostienen forjados prefabricados de hormigón y se apilan en cuatro niveles escalonados en torno a franjas de circulación con luz cenital.',
      it: 'Cinquantasei torri di blocchi di calcestruzzo, ciascuna di circa nove metri di lato, reggono solai prefabbricati in calcestruzzo e si impilano su quattro livelli sfalsati attorno a fenditure di circolazione illuminate dall\'alto.',
    },
    program: {
      en: 'A headquarters for the Centraal Beheer insurance company, for about a thousand clerical staff, on a site beside the Apeldoorn ring road.',
      es: 'Sede de la aseguradora Centraal Beheer, para cerca de mil empleados administrativos, en un solar junto a la ronda de circunvalación de Apeldoorn.',
      it: 'Sede della compagnia assicurativa Centraal Beheer, per circa mille impiegati, su un lotto lungo la circonvallazione di Apeldoorn.',
    },
    heritage: 'national',
    currentUse: {
      en: 'Vacated by Centraal Beheer in 2013 and now, after protection as a national monument, being converted to housing and mixed use.',
      es: 'Desalojado por Centraal Beheer en 2013 y, tras su declaración como monumento nacional, en proceso de reconversión en viviendas y usos mixtos.',
      it: 'Lasciato libero da Centraal Beheer nel 2013 e, dopo il vincolo come monumento nazionale, in corso di riconversione in alloggi e usi misti.',
    },
    detailRect: { x: 0.34, y: 0.32, w: 0.32, h: 0.32 },
    image: {
      commonsFile: 'File:Centraal Beheer, Hertzberger (1).jpg',
      photographer: 'Apdency',
      license: 'CC0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Centraal_Beheer,_Hertzberger_(1).jpg',
      width: 1600,
      height: 1185,
    },
    dossier: {
      en: 'Hertzberger described the brief as building a village rather than an office, and the result behaves like one. A single unit — a square concrete-block tower with a floor slab in it and daylight down two sides — is repeated fifty-six times and offset so that the gaps between towers become streets, squares and bridges rather than corridors. The concrete blocks are left raw and the fittings deliberately unfinished, on the argument that a workplace should be completed by the people in it; staff brought in plants, lamps, carpets and bicycles, and photographs from the 1970s show an office that looks squatted rather than furnished. Critics called the facades graceless, which they are: the building has no elevation to speak of, only the ends of the same unit repeated. Centraal Beheer left in 2013; the building is now a national monument being converted to housing.',
      es: 'Hertzberger describió el encargo como construir un pueblo y no una oficina, y el resultado se comporta como tal. Una única unidad —una torre cuadrada de bloque de hormigón con un forjado dentro y luz natural por dos lados— se repite cincuenta y seis veces y se desplaza, de modo que los huecos entre torres se vuelven calles, plazas y puentes en lugar de pasillos. El bloque de hormigón queda en bruto y los acabados adrede sin rematar, con el argumento de que un lugar de trabajo debe completarlo quien lo ocupa; los empleados llevaron plantas, lámparas, alfombras y bicicletas, y las fotografías de los años setenta muestran una oficina más ocupada que amueblada. La crítica llamó torpes a las fachadas, y lo son: el edificio apenas tiene alzado, solo los extremos de la misma unidad repetida. Centraal Beheer se marchó en 2013; hoy es monumento nacional en proceso de conversión en viviendas.',
      it: 'Hertzberger descrisse l\'incarico come la costruzione di un villaggio anziché di un ufficio, e il risultato si comporta come tale. Un\'unica unità — una torre quadrata di blocchi di calcestruzzo con dentro un solaio e luce naturale su due lati — è ripetuta cinquantasei volte e sfalsata, così che gli interstizi fra le torri diventino strade, piazze e ponti invece che corridoi. I blocchi restano grezzi e le finiture volutamente incompiute, secondo l\'argomento che un luogo di lavoro debba essere completato da chi lo occupa; gli impiegati portarono piante, lampade, tappeti e biciclette, e le fotografie degli anni Settanta mostrano un ufficio più occupato che arredato. La critica definì sgraziate le facciate, e lo sono: l\'edificio non ha quasi prospetto, solo le testate della stessa unità ripetuta. Centraal Beheer se ne andò nel 2013; oggi è monumento nazionale in corso di conversione in alloggi.',
    },
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q2200376', title: 'De Rots / Centraal Beheer building (Q2200376)', license: null },
      { kind: 'wikipedia', url: 'https://nl.wikipedia.org/wiki/Centraal_Beheergebouw_van_Herman_Hertzberger', title: 'Centraal Beheergebouw van Herman Hertzberger', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Herman_Hertzberger', title: 'Herman Hertzberger', license: 'CC BY-SA 4.0' },
    ],
    tier: 'canon',
  },
  {
    id: 'de-kasbah-hengelo',
    wikidataId: 'Q2547897',
    name: {
      en: 'De Kasbah Housing',
      es: 'Conjunto residencial De Kasbah',
      it: 'Complesso residenziale De Kasbah',
    },
    architectId: 'piet-blom',
    location: { city: 'Hengelo', countryCode: 'NL', lat: 52.26620, lon: 6.82994 },
    inception: 1969,
    completed: 1973,
    demolished: null,
    typology: 'housing',
    materials: ['concrete', 'brick'],
    structure: {
      en: 'A forest of concrete columns carries a raised concrete deck on which 184 dwellings sit, leaving the whole ground plane open beneath for parking, storage and gardens.',
      es: 'Un bosque de pilares de hormigón sostiene una plataforma elevada de hormigón sobre la que se asientan 184 viviendas, dejando libre por debajo todo el plano del suelo para aparcamiento, trasteros y jardines.',
      it: 'Una selva di pilastri di calcestruzzo regge una piastra sopraelevata su cui poggiano 184 alloggi, lasciando libero al di sotto l\'intero piano di terra per parcheggi, depositi e giardini.',
    },
    program: {
      en: 'Social rented housing for the municipality of Hengelo, built as the demonstration of Blom\'s principle of "living as a general urban roof".',
      es: 'Vivienda social de alquiler para el municipio de Hengelo, construida como demostración del principio de Blom de «habitar como cubierta urbana general».',
      it: 'Alloggi sociali in affitto per il comune di Hengelo, costruiti come dimostrazione del principio di Blom dell\'«abitare come tetto urbano generale».',
    },
    heritage: 'national',
    currentUse: {
      en: 'Still rented housing; a municipal monument that was added to the national register in September 2025.',
      es: 'Sigue siendo vivienda de alquiler; monumento municipal incorporado al registro nacional en septiembre de 2025.',
      it: 'Tuttora alloggi in affitto; monumento comunale iscritto nel registro nazionale nel settembre 2025.',
    },
    detailRect: { x: 0.30, y: 0.32, w: 0.34, h: 0.32 },
    image: {
      commonsFile: 'File:De Kasbah, Hengelo (6921528471).jpg',
      photographer: 'Archangel12',
      license: 'CC BY 2.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:De_Kasbah,_Hengelo_(6921528471).jpg',
      width: 1600,
      height: 1124,
    },
    dossier: {
      en: 'Blom\'s idea was simple and total: if the houses go up on legs, the ground stays whole. At Hengelo he ran 184 dwellings across a raised deck as a dense low mat, threaded by narrow alleys and roof terraces, and left everything below it as one continuous undercroft for cars, sheds, bicycles and planting. He called the principle "living as a general urban roof", and the name Kasbah advertises the model — the packed medina street, not the tower in the park that Dutch reconstruction planning had been building for two decades. It is a Structuralist argument about density made without a single high-rise. The scheme has been criticised ever since for the gloom of the undercroft and for how hard it is to find your own front door; it has also never emptied out, and after fifty years of continuous tenancy it was added to the national monument register in 2025.',
      es: 'La idea de Blom era simple y total: si las casas se levantan sobre patas, el suelo queda entero. En Hengelo dispuso 184 viviendas sobre una plataforma elevada como un tapiz denso y bajo, recorrido por callejones estrechos y azoteas, y dejó todo lo de abajo como un único soportal continuo para coches, trasteros, bicicletas y plantaciones. Llamó al principio «habitar como cubierta urbana general», y el nombre Kasbah anuncia el modelo: la calle apretada de la medina, no la torre en el parque que la planificación neerlandesa de posguerra llevaba dos décadas construyendo. Es un alegato estructuralista sobre la densidad hecho sin una sola torre. Se le ha reprochado desde siempre la penumbra del soportal y lo difícil que resulta encontrar la propia puerta; tampoco se ha vaciado nunca, y tras cincuenta años de ocupación continua entró en el registro nacional de monumentos en 2025.',
      it: 'L\'idea di Blom era semplice e totale: se le case salgono su gambe, il suolo resta intero. A Hengelo dispose 184 alloggi su una piastra sopraelevata come un tappeto denso e basso, percorso da vicoli stretti e terrazze, e lasciò tutto ciò che sta sotto come un unico porticato continuo per automobili, depositi, biciclette e verde. Chiamò il principio «abitare come tetto urbano generale», e il nome Kasbah dichiara il modello: la strada compressa della medina, non la torre nel parco che la pianificazione olandese della ricostruzione costruiva da vent\'anni. È un argomento strutturalista sulla densità condotto senza un solo edificio alto. Al complesso si rimprovera da sempre la penombra del porticato e la difficoltà di trovare la propria porta; non si è però mai svuotato, e dopo cinquant\'anni di occupazione continua è entrato nel registro nazionale dei monumenti nel 2025.',
    },
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q2547897', title: 'De Kasbah (Q2547897)', license: null },
      { kind: 'wikipedia', url: 'https://nl.wikipedia.org/wiki/De_Kasbah', title: 'De Kasbah', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://nl.wikipedia.org/wiki/Piet_Blom', title: 'Piet Blom', license: 'CC BY-SA 4.0' },
    ],
    tier: 'deep',
  },
  {
    id: 'wooneenheid-kiel-antwerp',
    wikidataId: 'Q62083298',
    name: {
      en: 'Kiel Housing Units',
      es: 'Unidades de vivienda del Kiel',
      it: 'Unità abitative del Kiel',
    },
    architectId: 'renaat-braem',
    location: { city: 'Antwerp', countryCode: 'BE', lat: 51.19303, lon: 4.37695 },
    inception: 1950,
    completed: 1958,
    demolished: null,
    typology: 'housing',
    materials: ['concrete', 'brick'],
    structure: {
      en: 'Nine reinforced-concrete slab blocks stand on pilotis in open parkland; the second phase used prefabricated elements and paired the blocks so that one stair core serves two.',
      es: 'Nueve bloques laminares de hormigón armado se alzan sobre pilotis en un parque abierto; la segunda fase empleó elementos prefabricados y emparejó los bloques para que un solo núcleo de escaleras sirviera a dos.',
      it: 'Nove stecche in cemento armato si levano su pilotis in un parco aperto; la seconda fase impiegò elementi prefabbricati e accoppiò i blocchi perché un solo vano scala ne servisse due.',
    },
    program: {
      en: 'Eight hundred social rented dwellings for the Antwerp housing company Huisvesting-Antwerpen, part of the city\'s postwar programme against an acute housing shortage.',
      es: 'Ochocientas viviendas sociales de alquiler para la sociedad municipal Huisvesting-Antwerpen, dentro del programa de posguerra de la ciudad contra una aguda escasez de vivienda.',
      it: 'Ottocento alloggi sociali in affitto per la società comunale Huisvesting-Antwerpen, entro il programma postbellico della città contro una grave penuria abitativa.',
    },
    heritage: 'national',
    currentUse: {
      en: 'Still social housing, renovated from 1988 onwards, with a shopping block, a home for older residents and a district heating plant on the site.',
      es: 'Sigue siendo vivienda social, renovada a partir de 1988, con un bloque comercial, una residencia de mayores y una central térmica de barrio en el recinto.',
      it: 'Tuttora edilizia sociale, rinnovata a partire dal 1988, con un blocco commerciale, una casa per anziani e una centrale termica di quartiere nell\'area.',
    },
    detailRect: { x: 0.32, y: 0.28, w: 0.32, h: 0.34 },
    image: {
      commonsFile: 'File:Hoogbouw op \'t Kiel , arch. Renaat Braem - 375630 - onroerenderfgoed.jpg',
      photographer: 'Vandevorst, Kris',
      license: 'CC BY 4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Hoogbouw_op_%27t_Kiel_,_arch._Renaat_Braem_-_375630_-_onroerenderfgoed.jpg',
      width: 1600,
      height: 1214,
    },
    dossier: {
      en: 'Antwerp came out of the war short of housing and put land at the edge of the city at the disposal of its social housing companies. Braem, back from two years in Le Corbusier\'s atelier and a member of CIAM since 1937, drew the Kiel in 1950 as an orthodox application of the Athens Charter: nine slabs lifted on pilotis, set free of the street grid at angles that catch the sun, with the park running underneath and between them. Four blocks went up from 1951 and the first tenants arrived in 1954; a second phase to 1958 used prefabrication and shared one stair hall between two blocks to hold costs down. Details are Corbusian — brise-soleil, coloured panels, a roofline given sculptural treatment — but the scheme is Belgian in its scale and its clientele. It is the country\'s most influential postwar social housing and a protected monument.',
      es: 'Amberes salió de la guerra escasa de vivienda y puso terrenos del borde de la ciudad a disposición de sus sociedades de vivienda social. Braem, de vuelta de dos años en el taller de Le Corbusier y miembro de los CIAM desde 1937, dibujó el Kiel en 1950 como aplicación ortodoxa de la Carta de Atenas: nueve bloques laminares elevados sobre pilotis, sueltos de la trama viaria y girados para captar el sol, con el parque corriendo por debajo y entre ellos. Cuatro bloques se levantaron desde 1951 y los primeros inquilinos llegaron en 1954; una segunda fase, hasta 1958, recurrió a la prefabricación y compartió una caja de escaleras entre dos bloques para contener costes. Los detalles son corbusieranos —brise-soleil, paneles de color, una coronación tratada como escultura—, pero el conjunto es belga en su escala y su clientela. Es la vivienda social de posguerra más influyente del país y monumento protegido.',
      it: 'Anversa uscì dalla guerra a corto di alloggi e mise terreni ai margini della città a disposizione delle proprie società di edilizia sociale. Braem, tornato da due anni nell\'atelier di Le Corbusier e membro dei CIAM dal 1937, disegnò il Kiel nel 1950 come applicazione ortodossa della Carta d\'Atene: nove stecche sollevate su pilotis, sciolte dalla maglia stradale e ruotate per captare il sole, con il parco che scorre sotto e fra di esse. Quattro blocchi salirono dal 1951 e i primi inquilini arrivarono nel 1954; una seconda fase, fino al 1958, ricorse alla prefabbricazione e fece condividere un vano scala a due blocchi per contenere i costi. I dettagli sono corbusiani — brise-soleil, pannelli colorati, un coronamento trattato come scultura — ma l\'insieme è belga per scala e committenza. È l\'edilizia sociale del dopoguerra più influente del paese ed è monumento vincolato.',
    },
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q62083298', title: 'Wooneenheid Kiel (Q62083298)', license: null },
      { kind: 'wikipedia', url: 'https://nl.wikipedia.org/wiki/Wooneenheid_Kiel', title: 'Wooneenheid Kiel', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Renaat_Braem', title: 'Renaat Braem', license: 'CC BY-SA 4.0' },
    ],
    tier: 'deep',
  },
  {
    id: 'limburgs-museum-venlo',
    wikidataId: 'Q2798268',
    name: {
      en: 'Limburgs Museum',
      es: 'Museo de Limburgo (Limburgs Museum)',
      it: 'Museo del Limburgo (Limburgs Museum)',
    },
    architectId: 'jeanne-dekkers',
    location: { city: 'Venlo', countryCode: 'NL', lat: 51.36667, lon: 6.17194 },
    inception: 1998,
    completed: 2000,
    demolished: null,
    typology: 'cultural',
    materials: ['brick', 'steel-and-glass'],
    structure: {
      en: 'A long curved masonry volume holding the galleries is set against a straight steel-and-glass block for the entrance and offices, with bridges spanning the excavated hall between them.',
      es: 'Un largo volumen curvo de fábrica que aloja las salas se contrapone a un cuerpo recto de acero y vidrio para el acceso y las oficinas, con pasarelas que cruzan la sala excavada entre ambos.',
      it: 'Un lungo volume curvo in muratura che ospita le sale si contrappone a un corpo rettilineo in acciaio e vetro per ingresso e uffici, con passerelle che scavalcano la sala scavata fra i due.',
    },
    program: {
      en: 'A provincial museum of the history and ethnology of Limburg, built for the foundation formed in 1993 by the merger of Venlo\'s Goltzius Museum with the Limburg folklore centre.',
      es: 'Museo provincial de historia y etnología de Limburgo, construido para la fundación creada en 1993 por la fusión del Museo Goltzius de Venlo con el centro etnológico limburgués.',
      it: 'Museo provinciale di storia ed etnologia del Limburgo, costruito per la fondazione nata nel 1993 dalla fusione del Museo Goltzius di Venlo con il centro etnologico limburghese.',
    },
    heritage: 'none',
    currentUse: {
      en: 'The provincial museum of Limburg, remodelled and extended by Dekkers again from 2021.',
      es: 'Museo provincial de Limburgo, de nuevo reformado y ampliado por Dekkers a partir de 2021.',
      it: 'Museo provinciale del Limburgo, nuovamente rimaneggiato e ampliato da Dekkers a partire dal 2021.',
    },
    detailRect: { x: 0.34, y: 0.34, w: 0.32, h: 0.30 },
    image: {
      commonsFile: 'File:Limburgs-Museum-Venlo-October-2024.jpg',
      photographer: 'Acediscovery',
      license: 'CC BY 4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Limburgs-Museum-Venlo-October-2024.jpg',
      width: 1600,
      height: 1209,
    },
    dossier: {
      en: 'The museum stands on the line of Venlo\'s vanished town wall, opposite the station and beside the surviving Keulsepoort, the old gate to Cologne, and Dekkers made the building argue about that. A long curved brick volume stands for the wall that used to be there; a sheer block of steel and glass, holding the entrance and offices, stands for the present. Visitors go down through the brick to prehistory and then climb back across bridges towards the recent past, so that the section does the chronology and the twelve period rooms open off it like the doors of a cabinet. It was the first building Dekkers completed after leaving EGM to set up her own office in Delft in 1998, and it was built for a foundation formed five years earlier from two merged collections that had outgrown their old premises. She returned in 2021 to remodel it.',
      es: 'El museo se alza sobre la traza de la desaparecida muralla de Venlo, frente a la estación y junto a la Keulsepoort superviviente, la vieja puerta de Colonia, y Dekkers hizo que el edificio argumentara sobre ello. Un largo volumen curvo de ladrillo representa el lienzo que allí hubo; un cuerpo tajante de acero y vidrio, con el acceso y las oficinas, representa el presente. El visitante desciende atravesando el ladrillo hasta la prehistoria y luego remonta por pasarelas hacia el pasado reciente, de modo que la sección se encarga de la cronología y las doce salas de época se abren a ella como las puertas de un armario. Fue el primer edificio que Dekkers terminó tras dejar EGM y montar estudio propio en Delft en 1998, y se levantó para una fundación creada cinco años antes con dos colecciones fusionadas que se habían quedado sin sitio. Volvió en 2021 para reformarlo.',
      it: 'Il museo sorge sul tracciato delle mura scomparse di Venlo, di fronte alla stazione e accanto alla superstite Keulsepoort, l\'antica porta di Colonia, e Dekkers ha fatto sì che l\'edificio ne discutesse. Un lungo volume curvo in mattoni sta per la cortina che vi sorgeva; un corpo netto di acciaio e vetro, con ingresso e uffici, sta per il presente. Il visitatore scende attraversando il mattone fino alla preistoria e poi risale su passerelle verso il passato recente, sicché è la sezione a reggere la cronologia e le dodici sale d\'epoca vi si aprono come gli sportelli di un mobile. Fu il primo edificio che Dekkers completò dopo aver lasciato EGM e aperto studio proprio a Delft nel 1998, e fu costruito per una fondazione nata cinque anni prima dalla fusione di due collezioni rimaste senza spazio. È tornata nel 2021 per rimaneggiarlo.',
    },
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q2798268', title: 'Limburg Museum (Q2798268)', license: null },
      { kind: 'wikipedia', url: 'https://nl.wikipedia.org/wiki/Limburgs_Museum', title: 'Limburgs Museum', license: 'CC BY-SA 4.0' },
      { kind: 'institution', url: 'https://jeannedekkers.nl/en/limburgs-museum-venlo-en/', title: 'Limburgs Museum Venlo — Jeanne Dekkers Architecture', license: null },
    ],
    tier: 'deep',
  },

  // --- post-2000 --------------------------------------------------------
  {
    id: 'concertgebouw-brugge',
    wikidataId: 'Q1867854',
    name: {
      en: 'Concertgebouw Bruges',
      es: 'Concertgebouw de Brujas',
      it: 'Concertgebouw di Bruges',
    },
    architectId: 'hilde-daem',
    coArchitects: ['paul-robbrecht'],
    location: { city: 'Bruges', countryCode: 'BE', lat: 51.20361, lon: 3.21833 },
    inception: 1998,
    completed: 2002,
    demolished: null,
    typology: 'cultural',
    materials: ['concrete', 'brick'],
    structure: {
      en: 'A concrete mass founded on 4,669 piles, clad in thousands of small red terracotta tiles, with a separate glass lantern tower rising beside the main hall.',
      es: 'Una masa de hormigón cimentada sobre 4.669 pilotes y revestida con miles de pequeñas tejas de terracota roja, con una torre linterna de vidrio independiente junto a la sala principal.',
      it: 'Una massa di calcestruzzo fondata su 4.669 pali e rivestita di migliaia di piccole tegole di terracotta rossa, con una torre lanterna vetrata autonoma accanto alla sala principale.',
    },
    program: {
      en: 'A concert hall for the city of Bruges, seating over 1,290 in the main auditorium and 320 in the chamber hall, built for its year as European Capital of Culture.',
      es: 'Auditorio para la ciudad de Brujas, con más de 1.290 plazas en la sala grande y 320 en la de cámara, construido para su año como Capital Europea de la Cultura.',
      it: 'Auditorio per la città di Bruges, con oltre 1.290 posti nella sala grande e 320 in quella da camera, costruito per il suo anno da Capitale europea della cultura.',
    },
    heritage: 'none',
    currentUse: {
      en: 'The city\'s concert hall and arts centre, with a café and exhibition space in the lantern tower.',
      es: 'Auditorio y centro de artes de la ciudad, con cafetería y espacio expositivo en la torre linterna.',
      it: 'Auditorio e centro d\'arte della città, con caffè e spazio espositivo nella torre lanterna.',
    },
    detailRect: { x: 0.34, y: 0.30, w: 0.32, h: 0.32 },
    image: {
      commonsFile: 'File:Brugge Concertgebouw R02.jpg',
      photographer: 'Marc Ryckaert',
      license: 'CC BY-SA 4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Brugge_Concertgebouw_R02.jpg',
      width: 1600,
      height: 1076,
    },
    dossier: {
      en: 'Bruges is a medieval town that has spent a century being careful, and the concert hall Robbrecht en Daem built on \'t Zand for the Capital of Culture year is not careful. It is a single dense mass with almost no windows, standing free on the square and holding a tall separate lantern of glass beside it, and its whole surface is covered in small red terracotta tiles from Saint-Omer — the colour of the town\'s roofs, applied to a wall, at the wrong scale and therefore visibly foreign. Inside, the sobriety continues: bare surfaces, a shallow palette, acoustics carefully engineered rather than decorated. The building divides the city, which was the point; Paul Robbrecht and Hilde Daem set it against the skyline rather than into it. It is the clearest public statement of the Flemish Nieuwe Eenvoud, and the tower is climbed for the view.',
      es: 'Brujas es una ciudad medieval que lleva un siglo siendo prudente, y el auditorio que Robbrecht en Daem levantó en \'t Zand para el año de la Capitalidad Cultural no lo es. Es una masa única y densa casi sin ventanas, exenta en la plaza, con una alta linterna de vidrio independiente al lado, y toda su superficie va cubierta de pequeñas tejas de terracota roja de Saint-Omer: el color de los tejados de la ciudad, aplicado a un muro, a escala equivocada y por tanto visiblemente ajeno. Dentro continúa la sobriedad: superficies desnudas, paleta corta, una acústica cuidadosamente calculada y no decorada. El edificio divide a la ciudad, que era de lo que se trataba; Paul Robbrecht e Hilde Daem lo pusieron contra la silueta urbana y no dentro de ella. Es el enunciado público más claro de la Nieuwe Eenvoud flamenca, y a la torre se sube por la vista.',
      it: 'Bruges è una città medievale che da un secolo è prudente, e l\'auditorio che Robbrecht en Daem ha costruito su \'t Zand per l\'anno da Capitale della cultura non lo è. È una massa unica e densa, quasi priva di finestre, isolata sulla piazza, con accanto un\'alta lanterna vetrata autonoma, e tutta la sua superficie è coperta di piccole tegole di terracotta rossa di Saint-Omer: il colore dei tetti della città, applicato a un muro, alla scala sbagliata e perciò visibilmente estraneo. All\'interno la sobrietà prosegue: superfici nude, tavolozza breve, un\'acustica accuratamente calcolata e non decorata. L\'edificio divide la città, e questo era il punto; Paul Robbrecht e Hilde Daem lo hanno posto contro il profilo urbano e non dentro di esso. È l\'enunciato pubblico più limpido della Nieuwe Eenvoud fiamminga, e sulla torre si sale per la vista.',
    },
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q1867854', title: 'Concertgebouw (Q1867854)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Concertgebouw,_Bruges', title: 'Concertgebouw, Bruges', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://nl.wikipedia.org/wiki/Hilde_Daem', title: 'Hilde Daem', license: 'CC BY-SA 4.0' },
    ],
    tier: 'canon',
  },
  {
    id: 'kaap-skil-entrance-building',
    wikidataId: 'Q125679334',
    name: {
      en: 'Kaap Skil Museum Entrance Building',
      es: 'Edificio de acceso del Museo Kaap Skil',
      it: 'Edificio d\'ingresso del Museo Kaap Skil',
    },
    architectId: 'francine-houben',
    location: { city: 'Oudeschild', countryCode: 'NL', lat: 53.03917, lon: 4.84806 },
    inception: 2007,
    completed: 2011,
    demolished: null,
    typology: 'cultural',
    materials: ['timber', 'concrete'],
    structure: {
      en: 'Four linked pitched timber bays carry a facade of vertical timber louvres reclaimed from sheet piling taken out of the Noordhollandsch Kanaal.',
      es: 'Cuatro crujías de madera a dos aguas, encadenadas entre sí, sostienen una fachada de lamas verticales de madera recuperada de las tablestacas retiradas del Canal de Holanda Septentrional.',
      it: 'Quattro campate lignee a falde, concatenate fra loro, reggono una facciata di lamelle verticali di legno recuperato dalle palancole estratte dal Canale dell\'Olanda settentrionale.',
    },
    program: {
      en: 'The main and entrance building of a maritime and beachcombers\' museum on Texel, holding the ticket hall and the indoor galleries of an otherwise open-air site.',
      es: 'Edificio principal y de acceso de un museo marítimo y de raqueros en Texel, con la taquilla y las salas cubiertas de un recinto por lo demás al aire libre.',
      it: 'Edificio principale e d\'ingresso di un museo marittimo e dei recuperanti di spiaggia a Texel, con la biglietteria e le sale coperte di un complesso per il resto all\'aperto.',
    },
    heritage: 'none',
    currentUse: {
      en: 'The museum entrance and main galleries, including the large model of the Texel roadstead.',
      es: 'Acceso y salas principales del museo, con la gran maqueta de la rada de Texel.',
      it: 'Ingresso e sale principali del museo, con il grande plastico della rada di Texel.',
    },
    detailRect: { x: 0.32, y: 0.32, w: 0.34, h: 0.32 },
    image: {
      commonsFile: 'File:Kaap Skil.jpg',
      photographer: 'wim goedhart',
      license: 'CC BY 2.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Kaap_Skil.jpg',
      width: 1600,
      height: 978,
    },
    dossier: {
      en: 'Oudeschild is a fishing village of small gabled houses, and Mecanoo answered it with a building that is four gables in a row rather than one large shed. The four pointed roofs are linked in a row so that, seen from the sea, they take up the rhythm of the village and rise above the dyke like waves; the volume never becomes a box. The whole envelope is then wrapped in vertical louvres salvaged from sheet piling taken out of the Noordhollandsch Kanaal — timber already weathered by decades in the canal, reused rather than milled new. In flat light the facade is a striped screen; in low sun it becomes almost transparent, and at night the museum glows between the slats. Behind it are the galleries that hold the museum\'s wreck finds, including the silk gown from the Palmwood Wreck. The building and its interior have won several awards.',
      es: 'Oudeschild es un pueblo pesquero de casitas con hastial, y Mecanoo le respondió con un edificio que son cuatro hastiales en hilera y no un único cobertizo grande. Las cuatro cubiertas a dos aguas se encadenan en hilera de modo que, vistas desde el mar, recogen el ritmo del pueblo y asoman sobre el dique como olas; el volumen nunca llega a ser una caja. Toda la envolvente se reviste después de lamas verticales rescatadas de las tablestacas retiradas del Canal de Holanda Septentrional: madera ya curtida por décadas en el canal, reutilizada en vez de aserrada nueva. Con luz plana la fachada es una celosía rayada; con sol rasante se vuelve casi transparente, y de noche el museo brilla entre los listones. Detrás quedan las salas que guardan los hallazgos de pecios, entre ellos el vestido de seda del Pecio del Palo Brasil. Edificio e instalación han recibido varios premios.',
      it: 'Oudeschild è un villaggio di pescatori fatto di casette a timpano, e Mecanoo gli ha risposto con un edificio che è quattro timpani in fila e non un\'unica grande tettoia. Le quattro coperture a punta sono concatenate in fila così che, viste dal mare, riprendano il ritmo del villaggio e si affaccino sopra la diga come onde; il volume non diventa mai una scatola. L\'intero involucro è poi avvolto in lamelle verticali recuperate dalle palancole estratte dal Canale dell\'Olanda settentrionale: legno già stagionato da decenni nel canale, riusato anziché segato nuovo. Con luce piatta la facciata è uno schermo rigato; con sole radente si fa quasi trasparente, e di notte il museo brilla fra i listelli. Dietro stanno le sale che custodiscono i reperti dei relitti, fra cui l\'abito di seta del Relitto del legno di palma. Edificio e allestimento hanno ricevuto diversi premi.',
    },
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q125679334', title: 'Entrance building Kaap Skil (Q125679334)', license: null },
      { kind: 'wikipedia', url: 'https://nl.wikipedia.org/wiki/Museum_Kaap_Skil', title: 'Museum Kaap Skil', license: 'CC BY-SA 4.0' },
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q19827882', title: 'Kaap Skil (Q19827882)', license: null },
    ],
    tier: 'deep',
  },
];
