import type { Building } from '@/types/building';

// Wave 5 curator agent (United Kingdom, Ireland): real, sourced Building entries for this slice.
//
// Every `image` below was checked on the live Commons file page and its
// licence template read there: only CC0 / CC BY 2.0-4.0 / CC BY-SA 2.0-4.0
// files with a named author are used. `image.width` / `image.height` are
// left at 0 for the later dimension-recording pass.
//
// The twelve sites are deliberately spread across the two countries and no
// two are within 25 km of each other, so the pool's `possible-duplicate-site`
// rule stays silent on this slice.
export const EUROPE_BRITISH_BUILDINGS: Building[] = [
  {
    id: 'st-pauls-cathedral',
    wikidataId: 'Q173882',
    name: {
      en: "St Paul's Cathedral",
      es: 'Catedral de San Pablo',
      it: 'Cattedrale di San Paolo',
    },
    architectId: 'christopher-wren',
    location: { city: 'London', countryCode: 'GB', lat: 51.51378, lon: -0.09831 },
    inception: 1675,
    completed: 1711,
    demolished: null,
    typology: 'sacral',
    materials: ['stone', 'brick'],
    structure: {
      en: 'Load-bearing Portland stone walls and piers carry a triple dome in which a hidden brick cone, chained with wrought iron, takes the weight of the stone lantern between an inner masonry shell and an outer dome of timber and lead.',
      es: 'Muros y pilares portantes de piedra de Portland sostienen una cúpula triple en la que un cono de ladrillo oculto, zunchado con cadenas de hierro forjado, recibe el peso de la linterna de piedra entre una cáscara interior de fábrica y una cúpula exterior de madera y plomo.',
      it: 'Muri e pilastri portanti in pietra di Portland reggono una cupola tripla nella quale un cono di mattoni nascosto, cerchiato con catene di ferro battuto, riceve il peso della lanterna di pietra fra un guscio interno in muratura e una cupola esterna di legno e piombo.',
    },
    program: {
      en: "Built for the Dean and Chapter of St Paul's under a royal commission after the Great Fire, and paid for largely by a duty on coal entering London, it remains the cathedral church of the Diocese of London.",
      es: 'Levantada para el deán y el cabildo de San Pablo bajo una comisión real tras el Gran Incendio y financiada en gran parte con un impuesto sobre el carbón que entraba en Londres, sigue siendo la iglesia catedral de la diócesis de Londres.',
      it: 'Costruita per il decano e il capitolo di San Paolo su commissione regia dopo il Grande Incendio e finanziata in larga parte con un dazio sul carbone in entrata a Londra, resta la chiesa cattedrale della diocesi di Londra.',
    },
    heritage: 'national',
    currentUse: {
      en: "Working Anglican cathedral and one of London's most visited monuments.",
      es: 'Catedral anglicana en uso y uno de los monumentos más visitados de Londres.',
      it: 'Cattedrale anglicana in uso e uno dei monumenti più visitati di Londra.',
    },
    detailRect: { x: 0.30, y: 0.19, w: 0.36, h: 0.30 },
    image: {
      commonsFile: "St Paul's Cathedral West Front City of London England 01.jpg",
      photographer: 'Acabashi',
      license: 'CC BY-SA 4.0',
      sourceUrl: "https://commons.wikimedia.org/wiki/File:St_Paul%27s_Cathedral_West_Front_City_of_London_England_01.jpg",
      width: 0,
      height: 0,
    },
    dossier: {
      en: "Old St Paul's burned in the Great Fire of 1666, and replacing it occupied Wren for the rest of his working life. The first stone was laid in June 1675; his son set the last stone of the lantern in October 1708; Parliament declared the cathedral complete on Christmas Day 1711. The west front seen here is the part he wrestled with hardest. He had to tie a high nave to lower aisles and work two towers into the composition, and his answer was a portico rising through two storeys on paired columns, the lower stage as wide as the aisles and the upper defining the nave, flanked by clock towers whose stacked drums and paired Corinthian columns are the most baroque thing he ever built. Francis Bird carved the pediment relief of the Conversion of St Paul. Behind the façade the plan stays stubbornly medieval — long nave, deep transepts, a defined clerestory — while the dome is pure structural reasoning, three shells doing three different jobs. The building took two direct hits in the Blitz and survived, becoming in the photographs of December 1940 the image of a city refusing to fall.",
      es: 'La vieja San Pablo ardió en el Gran Incendio de 1666, y sustituirla ocupó a Wren el resto de su vida profesional. La primera piedra se colocó en junio de 1675; su hijo remató la linterna en octubre de 1708; el Parlamento declaró terminada la catedral el día de Navidad de 1711. La fachada occidental que se ve aquí es la parte con la que más peleó. Tenía que ligar una nave alta con naves bajas e integrar dos torres, y su respuesta fue un pórtico de dos pisos sobre columnas pareadas, con el cuerpo inferior tan ancho como las naves laterales y el superior ajustado a la central, flanqueado por torres de reloj cuyos tambores superpuestos son lo más barroco que llegó a construir. Francis Bird talló el relieve del frontón con la conversión de san Pablo. Tras la fachada, la planta sigue siendo tercamente medieval —nave larga, crucero profundo, triforio definido—, mientras que la cúpula es puro razonamiento estructural: tres cáscaras para tres tareas distintas. El edificio encajó dos impactos directos durante el Blitz y resistió, hasta convertirse, en las fotografías de diciembre de 1940, en la imagen de una ciudad que se negaba a caer.',
      it: "La vecchia San Paolo bruciò nel Grande Incendio del 1666, e sostituirla occupò Wren per tutto il resto della vita professionale. La prima pietra fu posata nel giugno 1675; il figlio collocò l'ultima pietra della lanterna nell'ottobre 1708; il Parlamento dichiarò conclusa la cattedrale il giorno di Natale del 1711. La facciata occidentale che si vede qui è la parte con cui lottò di più. Doveva legare una navata alta a navate laterali basse e inserire due torri, e la sua risposta fu un portico a due piani su colonne accoppiate, con il registro inferiore largo quanto le navate laterali e quello superiore commisurato alla navata centrale, affiancato da torri d'orologio i cui tamburi sovrapposti e le colonne corinzie accoppiate sono la cosa più barocca che abbia mai costruito. Francis Bird scolpì il rilievo del frontone con la conversione di san Paolo. Dietro la facciata l'impianto resta ostinatamente medievale — navata lunga, transetti profondi, cleristorio definito — mentre la cupola è puro ragionamento strutturale: tre gusci per tre compiti diversi. L'edificio incassò due colpi diretti durante il Blitz e resistette, diventando nelle fotografie del dicembre 1940 l'immagine di una città che rifiutava di cadere.",
    },
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q173882', title: "St Paul's Cathedral (Q173882)", license: null },
      { kind: 'wikipedia', url: "https://en.wikipedia.org/wiki/St_Paul%27s_Cathedral", title: "St Paul's Cathedral", license: 'CC BY-SA 4.0' },
    ],
    tier: 'canon',
  },
  {
    id: 'custom-house-dublin',
    wikidataId: 'Q2300561',
    name: {
      en: 'The Custom House',
      es: 'The Custom House',
      it: 'Dogana di Dublino',
    },
    architectId: 'james-gandon',
    location: { city: 'Dublin', countryCode: 'IE', lat: 53.34854, lon: -6.25315 },
    inception: 1781,
    completed: 1791,
    demolished: null,
    typology: 'civic',
    materials: ['stone'],
    structure: {
      en: 'A long range of load-bearing ashlar, arcaded at ground level and pedimented at the centre, carrying a drum and dome that were rebuilt in Ardbraccan limestone after the fire of 1921.',
      es: 'Un cuerpo largo de sillería portante, con arquería en planta baja y frontón en el centro, que soporta un tambor y una cúpula reconstruidos en caliza de Ardbraccan tras el incendio de 1921.',
      it: "Un corpo lungo in pietra squadrata portante, con arcata al piano terra e frontone al centro, che sorregge un tamburo e una cupola ricostruiti in calcare di Ardbraccan dopo l'incendio del 1921.",
    },
    program: {
      en: 'Commissioned by John Beresford for the Irish revenue service and opened for business in 1791, it now houses the Department of Housing, Local Government and Heritage.',
      es: 'Encargada por John Beresford para el servicio de aduanas irlandés y abierta al público en 1791, alberga hoy el Departamento de Vivienda, Gobierno Local y Patrimonio.',
      it: 'Commissionata da John Beresford per il servizio doganale irlandese e aperta al pubblico nel 1791, ospita oggi il Dipartimento per la Casa, il Governo locale e il Patrimonio.',
    },
    heritage: 'national',
    currentUse: {
      en: 'Irish government offices, with a public visitor experience opened in 2021.',
      es: 'Oficinas del Gobierno irlandés, con un centro de visitantes abierto en 2021.',
      it: 'Uffici del governo irlandese, con un percorso di visita aperto al pubblico nel 2021.',
    },
    detailRect: { x: 0.42, y: 0.24, w: 0.17, h: 0.31 },
    image: {
      commonsFile: 'Custom House from the Liffey, Dublin, Ireland, August 2025.jpg',
      photographer: 'Mathieu Chollet',
      license: 'CC BY-SA 4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Custom_House_from_the_Liffey,_Dublin,_Ireland,_August_2025.jpg',
      width: 0,
      height: 0,
    },
    dossier: {
      en: "Beresford's decision to move Dublin's customs downriver of the old city was fought by the Corporation and by merchants who saw their quays devalued, and the laying of the foundations was disrupted by a mob several thousand strong. Gandon built anyway, on reclaimed ground, with every available mason in the city engaged on the work. The result is a long river front held down by a rusticated arcade and lifted at the centre by a four-column portico and a dome carrying Henry Banks's figure of Commerce; Edward Smyth carved the keystone heads personifying Ireland's rivers, still the best-loved thing about the building. It cost £200,000 and opened in November 1791. In 1921 it was burned out and the dome collapsed; the Free State restoration rebuilt that dome in Irish Ardbraccan limestone instead of English Portland stone, so it reads distinctly darker than the walls below — a repair that was also a statement. Gandon's interiors were lost entirely, but the exterior remains the finest neoclassical composition in Ireland.",
      es: 'La decisión de Beresford de trasladar la aduana de Dublín río abajo de la ciudad vieja fue combatida por la Corporación y por los comerciantes, que veían devaluados sus muelles, y la cimentación llegó a ser interrumpida por una turba de varios miles de personas. Gandon construyó de todos modos, sobre terreno ganado al río y con todos los canteros disponibles de la ciudad ocupados en la obra. El resultado es un largo frente fluvial sujetado por una arquería almohadillada y levantado en el centro por un pórtico de cuatro columnas y una cúpula que sostiene la figura del Comercio de Henry Banks; Edward Smyth talló las claves con cabezas que personifican los ríos de Irlanda, todavía lo más querido del edificio. Costó 200.000 libras y abrió en noviembre de 1791. En 1921 quedó calcinado y la cúpula se derrumbó; la restauración del Estado Libre la rehízo en caliza irlandesa de Ardbraccan en lugar de piedra inglesa de Portland, de modo que se lee más oscura que el muro: una reparación que era también una declaración. Los interiores de Gandon se perdieron por completo.',
      it: "La decisione di Beresford di spostare la dogana di Dublino a valle della città vecchia fu contrastata dalla Corporation e dai mercanti, che vedevano svalutate le proprie banchine, e la posa delle fondazioni fu interrotta da una folla di parecchie migliaia di persone. Gandon costruì lo stesso, su terreno strappato al fiume e impiegando tutti gli scalpellini disponibili in città. Il risultato è un lungo fronte fluviale trattenuto da un'arcata bugnata e sollevato al centro da un portico di quattro colonne e da una cupola che regge la figura del Commercio di Henry Banks; Edward Smyth scolpì le chiavi di volta con le teste che personificano i fiumi d'Irlanda, tuttora la cosa più amata dell'edificio. Costò 200.000 sterline e aprì nel novembre 1791. Nel 1921 fu incendiata e la cupola crollò; il restauro dello Stato Libero la rifece in calcare irlandese di Ardbraccan anziché in pietra inglese di Portland, sicché appare nettamente più scura del muro sottostante: una riparazione che era anche una dichiarazione.",
    },
    context: {
      body: {
        en: "On 25 May 1921, during the Irish War of Independence, the Dublin Brigade of the IRA occupied and burned the Custom House, which by then housed the Local Government Board for Ireland. The object was to destroy the tax and local-government records on which British administration in Ireland depended. Gandon's interiors were destroyed, the dome collapsed, and an irreplaceable body of archives was lost. The operation achieved its aim but cost the IRA heavily: a large number of Volunteers were captured during the attack or the withdrawal. The building was restored under the Irish Free State, and the dome deliberately rebuilt in Irish limestone.",
        es: 'El 25 de mayo de 1921, durante la guerra de independencia irlandesa, la Brigada de Dublín del IRA ocupó e incendió la Custom House, que entonces albergaba el Local Government Board for Ireland. El objetivo era destruir los registros fiscales y de administración local en que se apoyaba el gobierno británico en Irlanda. Los interiores de Gandon quedaron destruidos, la cúpula se derrumbó y se perdió un fondo documental irreemplazable. La operación cumplió su propósito, pero costó cara al IRA: un gran número de voluntarios fueron capturados durante el ataque o en la retirada. El edificio se restauró bajo el Estado Libre Irlandés y la cúpula se rehízo deliberadamente en caliza irlandesa.',
        it: "Il 25 maggio 1921, durante la guerra d'indipendenza irlandese, la Brigata di Dublino dell'IRA occupò e incendiò la Custom House, che allora ospitava il Local Government Board for Ireland. L'obiettivo era distruggere gli archivi fiscali e amministrativi su cui poggiava il governo britannico in Irlanda. Gli interni di Gandon andarono distrutti, la cupola crollò e un patrimonio documentario insostituibile fu perduto. L'operazione raggiunse il suo scopo ma costò cara all'IRA: un gran numero di volontari fu catturato durante l'attacco o nel ripiegamento. L'edificio fu restaurato sotto lo Stato Libero d'Irlanda e la cupola volutamente ricostruita in calcare irlandese.",
      },
      sources: [
        { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/The_Custom_House', title: 'The Custom House', license: 'CC BY-SA 4.0' },
        { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Burning_of_the_Custom_House', title: 'Burning of the Custom House', license: 'CC BY-SA 4.0' },
      ],
    },
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q2300561', title: 'The Custom House (Q2300561)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/The_Custom_House', title: 'The Custom House', license: 'CC BY-SA 4.0' },
    ],
    tier: 'canon',
  },
  {
    id: 'saint-fin-barres-cathedral',
    wikidataId: 'Q2339141',
    name: {
      en: "Saint Fin Barre's Cathedral",
      es: 'Catedral de San Finbar',
      it: 'Cattedrale di San Finbar',
    },
    architectId: 'william-burges',
    location: { city: 'Cork', countryCode: 'IE', lat: 51.89440, lon: -8.48064 },
    inception: 1865,
    completed: 1879,
    demolished: null,
    typology: 'sacral',
    materials: ['stone'],
    structure: {
      en: 'A cruciform Gothic Revival church of load-bearing Cork limestone with Bath stone inside, its nave carried on cylindrical piers under an arcade, triforium and clerestory, and capped by three spires — two on the west front and one over the crossing.',
      es: 'Iglesia neogótica de planta de cruz, de caliza portante de Cork con piedra de Bath en el interior, cuya nave descansa sobre pilares cilíndricos bajo arquería, triforio y claristorio, y que remata en tres agujas: dos en la fachada occidental y una sobre el crucero.',
      it: "Chiesa neogotica a croce, in calcare portante di Cork con pietra di Bath all'interno, la cui navata poggia su pilastri cilindrici sotto arcata, triforio e cleristorio, ed è coronata da tre guglie: due sulla facciata occidentale e una sulla crociera.",
    },
    program: {
      en: 'Commissioned by the Church of Ireland in 1862 to replace a plain Georgian predecessor and reassert its standing after the reform of the penal laws, it is now one of three co-cathedrals of the United Dioceses of Cork, Cloyne and Ross.',
      es: 'Encargada por la Iglesia de Irlanda en 1862 para sustituir a una predecesora georgiana sin gracia y reafirmar su posición tras la reforma de las leyes penales, es hoy una de las tres cocatedrales de las diócesis unidas de Cork, Cloyne y Ross.',
      it: "Commissionata dalla Chiesa d'Irlanda nel 1862 per sostituire una spoglia predecessora georgiana e riaffermarne il rango dopo la riforma delle leggi penali, è oggi una delle tre concattedrali delle diocesi unite di Cork, Cloyne e Ross.",
    },
    heritage: 'national',
    currentUse: {
      en: 'Church of Ireland cathedral in regular use and open to visitors.',
      es: 'Catedral de la Iglesia de Irlanda en uso regular y abierta a visitantes.',
      it: "Cattedrale della Chiesa d'Irlanda in uso regolare e aperta ai visitatori.",
    },
    detailRect: { x: 0.34, y: 0.54, w: 0.31, h: 0.25 },
    image: {
      commonsFile: "Cork St. Fin Barre's Cathedral Exterior Facade 4.jpg",
      photographer: 'Zairon',
      license: 'CC BY 4.0',
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Cork_St._Fin_Barre%27s_Cathedral_Exterior_Facade_4.jpg",
      width: 0,
      height: 0,
    },
    dossier: {
      en: "Burges was thirty-five and largely unbuilt when the Church of Ireland's competition came his way. He disregarded the £15,000 budget outright, submitting a design he reckoned would cost twice as much, and won anyway in February 1863; his diary records the reaction — 'Got Cork!' The foundation stone was laid in January 1865, the unfinished cathedral was consecrated in 1870 and the spires topped out in 1879, by which point the bill had passed £100,000. The style is thirteenth-century French, used as a working grammar rather than a quotation: deeply recessed portals, a wheel window over the west door, and a bristle of gables, pinnacles and thirty-two gargoyles. What makes it exceptional is that Burges designed the whole interior too — sculpture, mosaic, glass, metalwork, furniture — some twelve hundred sculptures in all, modelled by Thomas Nicholls and carved on site. The plan is only 180 feet long, and the three spires exist largely to make a parish-sized church read as a cathedral.",
      es: 'Burges tenía treinta y cinco años y casi nada construido cuando le llegó el concurso de la Iglesia de Irlanda. Ignoró sin más el presupuesto de 15.000 libras y presentó un proyecto que él mismo calculaba al doble; aun así ganó, en febrero de 1863, y su diario recoge la reacción: «¡Cork es mío!». La primera piedra se puso en enero de 1865, la catedral inacabada se consagró en 1870 y las agujas se remataron en 1879, cuando la factura ya superaba las 100.000 libras. El estilo es el gótico francés del siglo XIII, empleado como gramática de trabajo y no como cita: portadas de profundo abocinamiento, un rosetón sobre la puerta occidental y una erizada sucesión de gabletes, pináculos y treinta y dos gárgolas. Lo excepcional es que Burges diseñó también todo el interior —escultura, mosaico, vidriera, forja, mobiliario—, unas mil doscientas piezas modeladas por Thomas Nicholls y talladas in situ. La planta mide apenas 180 pies, y las tres agujas existen sobre todo para que una iglesia de tamaño parroquial se lea como catedral.',
      it: "Burges aveva trentacinque anni e quasi nulla di costruito quando gli capitò il concorso della Chiesa d'Irlanda. Ignorò del tutto il preventivo di 15.000 sterline e presentò un progetto che egli stesso stimava al doppio; vinse comunque, nel febbraio 1863, e il suo diario registra la reazione: «Cork è mia!». La prima pietra fu posata nel gennaio 1865, la cattedrale incompiuta fu consacrata nel 1870 e le guglie ultimate nel 1879, quando il conto aveva superato le 100.000 sterline. Lo stile è il gotico francese del Duecento, usato come grammatica operativa e non come citazione: portali fortemente strombati, un rosone sopra la porta occidentale e un irto susseguirsi di timpani, pinnacoli e trentadue gargolle. L'eccezionalità sta nel fatto che Burges disegnò anche tutto l'interno — scultura, mosaico, vetrate, ferro, arredi — circa milleduecento pezzi modellati da Thomas Nicholls e intagliati in cantiere. La pianta è lunga appena 180 piedi, e le tre guglie servono soprattutto a far leggere come cattedrale una chiesa di dimensioni parrocchiali.",
    },
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q2339141', title: "Saint Fin Barre's Cathedral (Q2339141)", license: null },
      { kind: 'wikipedia', url: "https://en.wikipedia.org/wiki/Saint_Fin_Barre%27s_Cathedral", title: "Saint Fin Barre's Cathedral", license: 'CC BY-SA 4.0' },
    ],
    tier: 'canon',
  },
  {
    id: 'glasgow-school-of-art',
    wikidataId: 'Q748106',
    name: {
      en: 'Glasgow School of Art (Mackintosh Building)',
      es: 'Escuela de Arte de Glasgow (Edificio Mackintosh)',
      it: 'Glasgow School of Art (Mackintosh Building)',
    },
    architectId: 'charles-rennie-mackintosh',
    location: { city: 'Glasgow', countryCode: 'GB', lat: 55.86605, lon: -4.26375 },
    inception: 1897,
    completed: 1909,
    demolished: null,
    typology: 'educational',
    materials: ['stone', 'steel-and-glass'],
    structure: {
      en: 'Load-bearing sandstone walls carry iron and rolled-steel beams over studio openings so large that the north front is effectively a glass wall braced by masonry piers, with timber floors behind.',
      es: 'Muros portantes de arenisca sostienen vigas de hierro y acero laminado sobre unos huecos de taller tan grandes que la fachada norte es en la práctica un muro de vidrio arriostrado por machones de fábrica, con forjados de madera detrás.',
      it: 'Muri portanti in arenaria reggono travi di ferro e acciaio laminato sopra aperture di atelier così ampie che il fronte nord è di fatto una parete di vetro controventata da pilastri murari, con solai lignei alle spalle.',
    },
    program: {
      en: "Built for the Glasgow School of Art with a bequest administered by the Bellahouston Trust, it provided painting and design studios, a museum and a library, and served as the school's main teaching building until 2014.",
      es: 'Construido para la Escuela de Arte de Glasgow con un legado administrado por el Bellahouston Trust, albergó talleres de pintura y diseño, un museo y una biblioteca, y fue el edificio docente principal de la escuela hasta 2014.',
      it: 'Costruito per la Glasgow School of Art con un lascito amministrato dal Bellahouston Trust, ospitava atelier di pittura e design, un museo e una biblioteca, e fu la sede didattica principale della scuola fino al 2014.',
    },
    heritage: 'national',
    currentUse: {
      en: "A stabilised shell since the fire of June 2018; the School has committed to rebuilding it to Mackintosh's design.",
      es: 'Un cascarón apuntalado desde el incendio de junio de 2018; la escuela se ha comprometido a reconstruirlo según el proyecto de Mackintosh.',
      it: "Un guscio puntellato dopo l'incendio del giugno 2018; la scuola si è impegnata a ricostruirlo secondo il progetto di Mackintosh.",
    },
    detailRect: { x: 0.48, y: 0.24, w: 0.30, h: 0.40 },
    image: {
      commonsFile: "'Glasgow School of Art' JBU 002.jpg",
      photographer: 'Jörg Bittner Unna',
      license: 'CC BY 3.0',
      sourceUrl: "https://commons.wikimedia.org/wiki/File:%27Glasgow_School_of_Art%27_JBU_002.jpg",
      width: 0,
      height: 0,
    },
    dossier: {
      en: "The commission for a new art school on the steep Garnethill site went to Honeyman & Keppie in 1896, the school's director Francis Newbery choosing Mackintosh for the job. He was twenty-eight and still a salaried assistant. Money ran out, so it went up in two campaigns — the east half finished in 1899, the west half with the library in 1907–09 — and the ten-year gap is legible in the fabric, the later wing harder, taller and more abstract than the first. The north elevation solves what was really an engineering brief. Painting studios need vast, even light, so Mackintosh hung three enormous studio windows in the masonry, braced them with iron, and then made the ironwork itself the ornament: brackets, finials and knotted motifs that turn a structural necessity into the building's signature. The entrance bay is deliberately off-centre and deliberately odd. Fire destroyed the library in May 2014 and gutted the whole building in June 2018; the shell stands propped, awaiting a reconstruction promised but not yet begun.",
      es: 'El encargo de una nueva escuela de arte en la empinada ladera de Garnethill recayó en 1896 en Honeyman & Keppie, y el director de la escuela, Francis Newbery, eligió a Mackintosh para el trabajo. Tenía veintiocho años y seguía siendo un ayudante a sueldo. El dinero se agotó, así que se levantó en dos campañas —la mitad este terminada en 1899, la oeste con la biblioteca en 1907-09— y la pausa de diez años se lee en la fábrica: el ala tardía es más dura, más alta y más abstracta que la primera. El alzado norte resuelve lo que en realidad era un encargo de ingeniería. Los talleres de pintura necesitan una luz enorme y uniforme, de modo que Mackintosh colgó tres ventanales inmensos en la fábrica, los arriostró con hierro y convirtió después ese mismo hierro en el ornamento: ménsulas, remates y motivos anudados que hacen de una necesidad estructural la firma del edificio. El cuerpo de acceso es deliberadamente descentrado y deliberadamente extraño. El fuego destruyó la biblioteca en mayo de 2014 y vació el edificio entero en junio de 2018.',
      it: "L'incarico per una nuova scuola d'arte sul ripido pendio di Garnethill andò nel 1896 a Honeyman & Keppie, e il direttore della scuola, Francis Newbery, scelse Mackintosh per il progetto. Aveva ventotto anni ed era ancora assistente stipendiato. I fondi si esaurirono, così l'edificio sorse in due campagne — la metà est ultimata nel 1899, quella ovest con la biblioteca nel 1907-09 — e l'intervallo di dieci anni si legge nella fabbrica: l'ala tarda è più dura, più alta e più astratta della prima. Il fronte nord risolve quello che era in realtà un problema d'ingegneria. Gli atelier di pittura richiedono una luce enorme e uniforme, perciò Mackintosh sospese nella muratura tre finestroni immensi, li controventò con il ferro e fece poi di quello stesso ferro l'ornamento: mensole, terminali e motivi annodati che trasformano una necessità strutturale nella firma dell'edificio. Il corpo d'ingresso è volutamente decentrato e volutamente strano. Il fuoco distrusse la biblioteca nel maggio 2014 e svuotò l'intero edificio nel giugno 2018.",
    },
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q748106', title: 'Glasgow School of Art (Q748106)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Glasgow_School_of_Art', title: 'Glasgow School of Art', license: 'CC BY-SA 4.0' },
    ],
    tier: 'canon',
  },
  {
    id: 'royal-shakespeare-theatre',
    wikidataId: 'Q1375404',
    name: {
      en: 'Royal Shakespeare Theatre',
      es: 'Royal Shakespeare Theatre',
      it: 'Royal Shakespeare Theatre',
    },
    architectId: 'elisabeth-scott',
    location: { city: 'Stratford-upon-Avon', countryCode: 'GB', lat: 52.19040, lon: -1.70392 },
    inception: 1929,
    completed: 1932,
    demolished: null,
    typology: 'cultural',
    materials: ['brick', 'steel-and-glass'],
    structure: {
      en: 'A steel-framed theatre clad in brick and built around a full-height fly tower, its auditorium cut out and rebuilt as a thrust stage in 2007–10 inside the retained envelope.',
      es: 'Teatro de estructura de acero revestido de ladrillo y organizado en torno a una caja escénica de altura completa, cuya sala fue vaciada y reconstruida como escenario de proscenio avanzado entre 2007 y 2010 dentro de la envolvente conservada.',
      it: "Teatro con struttura in acciaio rivestita di mattoni e organizzato attorno a una torre scenica a tutta altezza, la cui sala è stata svuotata e ricostruita come palcoscenico avanzato fra il 2007 e il 2010 dentro l'involucro conservato.",
    },
    program: {
      en: 'Built for the governors of the Shakespeare Memorial Theatre after fire destroyed the 1879 building, and home since 1961 to the Royal Shakespeare Company.',
      es: 'Levantado para el patronato del Shakespeare Memorial Theatre tras el incendio del edificio de 1879, es desde 1961 la sede de la Royal Shakespeare Company.',
      it: "Costruito per il consiglio dello Shakespeare Memorial Theatre dopo l'incendio dell'edificio del 1879, dal 1961 è la sede della Royal Shakespeare Company.",
    },
    heritage: 'national',
    currentUse: {
      en: 'Main house of the Royal Shakespeare Company, seating over a thousand around a thrust stage.',
      es: 'Sala principal de la Royal Shakespeare Company, con más de mil localidades en torno a un escenario avanzado.',
      it: 'Sala principale della Royal Shakespeare Company, con oltre mille posti attorno a un palcoscenico avanzato.',
    },
    detailRect: { x: 0.34, y: 0.52, w: 0.24, h: 0.28 },
    image: {
      commonsFile: 'Royal Shakespeare Theatre east.jpg',
      photographer: 'DeFacto',
      license: 'CC BY-SA 4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Royal_Shakespeare_Theatre_east.jpg',
      width: 0,
      height: 0,
    },
    dossier: {
      en: "The Victorian Shakespeare Memorial Theatre burned down in March 1926. The governors held an open international competition, judged from anonymous drawings, and the winner announced in 1928 was Elisabeth Scott, twenty-nine years old and three years qualified — the first woman to take a major British public building competition, a fact the press reported in terms that have not aged well. The theatre she built between 1929 and 1932, with her fellow Architectural Association students Alison Sleigh and John Chiene Shepherd, is a stripped brick mass on the bank of the Avon: long horizontal courses, tall window bays recessed between shallow piers, and a fly tower treated as a plain block rather than disguised. Inside it was emphatically of its moment, with Art Deco stair halls and a proscenium auditorium seating about fourteen hundred on three tiers. Actors complained about the distance to the back row almost at once. The 2007–10 Transformation Project by Bennetts Associates cut a thrust-stage auditorium into the shell and added an observation tower, leaving Scott's exterior largely intact.",
      es: 'El Shakespeare Memorial Theatre victoriano ardió en marzo de 1926. El patronato convocó un concurso internacional abierto, juzgado sobre planos anónimos, y la ganadora anunciada en 1928 fue Elisabeth Scott, de veintinueve años y tres de título: la primera mujer que se llevaba un gran concurso público británico, algo que la prensa contó en términos que hoy resultan indefendibles. El teatro que construyó entre 1929 y 1932, junto a sus compañeros de la Architectural Association Alison Sleigh y John Chiene Shepherd, es una masa desnuda de ladrillo a orillas del Avon: hiladas horizontales largas, huecos altos retranqueados entre machones planos y una caja escénica tratada como un bloque liso, sin disimulo. Por dentro era rotundamente de su tiempo, con vestíbulos y escaleras art déco y una sala a la italiana de unas mil cuatrocientas plazas en tres niveles. Los actores se quejaron enseguida de la distancia hasta la última fila. La reforma de 2007-2010 de Bennetts Associates recortó dentro del casco una sala de escenario avanzado y añadió una torre mirador, dejando casi intacto el exterior de Scott.',
      it: "Lo Shakespeare Memorial Theatre vittoriano bruciò nel marzo 1926. Il consiglio bandì un concorso internazionale aperto, giudicato su disegni anonimi, e la vincitrice annunciata nel 1928 fu Elisabeth Scott, ventinovenne e abilitata da tre anni: la prima donna ad aggiudicarsi un grande concorso pubblico britannico, fatto che la stampa raccontò in termini oggi indifendibili. Il teatro che costruì fra il 1929 e il 1932, con i compagni dell'Architectural Association Alison Sleigh e John Chiene Shepherd, è una massa spoglia di mattoni sulla riva dell'Avon: lunghi corsi orizzontali, alte aperture arretrate fra pilastri piatti e una torre scenica trattata come un blocco liscio, senza infingimenti. All'interno era decisamente del suo tempo, con atri e scale art déco e una sala all'italiana da circa millequattrocento posti su tre ordini. Gli attori si lamentarono subito della distanza dall'ultima fila. Il Transformation Project di Bennetts Associates (2007-2010) ha ricavato nel guscio una sala a palcoscenico avanzato e aggiunto una torre panoramica, lasciando pressoché intatto l'esterno della Scott.",
    },
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q1375404', title: 'Royal Shakespeare Theatre (Q1375404)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Royal_Shakespeare_Theatre', title: 'Royal Shakespeare Theatre', license: 'CC BY-SA 4.0' },
    ],
    tier: 'canon',
  },
  {
    id: 'coventry-cathedral',
    wikidataId: 'Q1138070',
    name: {
      en: 'Coventry Cathedral',
      es: 'Catedral de Coventry',
      it: 'Cattedrale di Coventry',
    },
    architectId: 'basil-spence',
    location: { city: 'Coventry', countryCode: 'GB', lat: 52.40833, lon: -1.50722 },
    inception: 1956,
    completed: 1962,
    demolished: null,
    typology: 'sacral',
    materials: ['stone', 'concrete'],
    structure: {
      en: 'A concrete and steel frame faced in Hollington sandstone, its nave walls folded into a zig-zag so that tall windows set in the returns face the altar and are invisible to anyone walking in.',
      es: 'Estructura de hormigón y acero revestida de arenisca de Hollington, con los muros de la nave plegados en zigzag de modo que las altas vidrieras alojadas en los retranqueos miran al altar y resultan invisibles al entrar.',
      it: "Struttura in cemento e acciaio rivestita di arenaria di Hollington, con i muri della navata piegati a zig-zag così che le alte vetrate alloggiate nei risvolti guardino verso l'altare e restino invisibili a chi entra.",
    },
    program: {
      en: "Built for the Diocese of Coventry beside the bombed ruin of the medieval St Michael's, which Spence insisted be kept as a garden of remembrance so that old and new together form one church.",
      es: "Construida para la diócesis de Coventry junto a la ruina bombardeada de la medieval St Michael's, que Spence exigió conservar como jardín del recuerdo para que vieja y nueva formaran juntas una sola iglesia.",
      it: "Costruita per la diocesi di Coventry accanto al rudere bombardato della medievale St Michael's, che Spence volle conservare come giardino della memoria perché vecchia e nuova formassero insieme un'unica chiesa.",
    },
    heritage: 'national',
    currentUse: {
      en: 'Anglican cathedral and an international centre of reconciliation.',
      es: 'Catedral anglicana y centro internacional de reconciliación.',
      it: 'Cattedrale anglicana e centro internazionale di riconciliazione.',
    },
    detailRect: { x: 0.62, y: 0.36, w: 0.26, h: 0.34 },
    image: {
      commonsFile: 'Cathedral of St Michael (Coventry Cathedral), Priory Street, Coventry (NHLE Code 1342941) (April 2025) (3).jpg',
      photographer: 'Hassocks5489',
      license: 'CC0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Cathedral_of_St_Michael_(Coventry_Cathedral),_Priory_Street,_Coventry_(NHLE_Code_1342941)_(April_2025)_(3).jpg',
      width: 0,
      height: 0,
    },
    dossier: {
      en: "St Michael's was destroyed on the night of 14 November 1940, and Provost Howard had 'Father Forgive' cut into the wall behind the ruined altar. The decision to build rather than restore produced a competition in 1950 that drew more than two hundred entries; Spence won it by proposing that the ruin be kept and the new cathedral set at right angles beside it, joined by a porch, so that the old church stays visible through the glass of the new. He used Hollington sandstone for both to bind them together. The nave walls zig-zag, hiding their windows from anyone entering and showing them all on the walk back to the door; the Great West Screen is a wall of glass engraved by John Hutton with saints and angels. Spence commissioned the art as part of the architecture — Graham Sutherland's twenty-three-metre tapestry, John Piper's baptistry window made with Patrick Reyntiens, Jacob Epstein's bronze St Michael outside. The cathedral was consecrated on 25 May 1962, with Britten's War Requiem written for the occasion.",
      es: "St Michael's quedó destruida la noche del 14 de noviembre de 1940, y el deán Howard hizo grabar «Padre, perdona» en el muro tras el altar arruinado. La decisión de construir en lugar de restaurar dio lugar a un concurso convocado en 1950 al que se presentaron más de doscientas propuestas; Spence lo ganó proponiendo conservar la ruina y colocar la catedral nueva en ángulo recto junto a ella, unidas por un pórtico, de modo que la iglesia vieja siga viéndose a través del vidrio de la nueva. Empleó arenisca de Hollington en ambas para ligarlas. Los muros de la nave zigzaguean y esconden sus vidrieras a quien entra, para mostrarlas todas de golpe al volver hacia la puerta; el gran cerramiento occidental es un muro de vidrio grabado por John Hutton con santos y ángeles. Spence encargó el arte como parte de la arquitectura: el tapiz de veintitrés metros de Graham Sutherland, la vidriera del baptisterio de John Piper con Patrick Reyntiens y el san Miguel de bronce de Jacob Epstein. Se consagró el 25 de mayo de 1962.",
      it: "St Michael's fu distrutta nella notte del 14 novembre 1940, e il provost Howard fece incidere «Padre, perdona» sul muro dietro l'altare in rovina. La scelta di costruire anziché restaurare produsse un concorso bandito nel 1950 con oltre duecento proposte; Spence lo vinse proponendo di conservare il rudere e di collocare la nuova cattedrale ad angolo retto accanto a esso, unite da un portico, così che la vecchia chiesa resti visibile attraverso il vetro della nuova. Usò per entrambe l'arenaria di Hollington, a legarle. I muri della navata procedono a zig-zag e nascondono le vetrate a chi entra, per mostrarle tutte insieme nel ritorno verso la porta; la grande schermata occidentale è una parete di vetro incisa da John Hutton con santi e angeli. Spence commissionò le opere d'arte come parte dell'architettura: l'arazzo di ventitré metri di Graham Sutherland, la vetrata del battistero di John Piper con Patrick Reyntiens e il san Michele bronzeo di Jacob Epstein. La consacrazione fu il 25 maggio 1962.",
    },
    context: {
      body: {
        en: "The medieval cathedral of St Michael was destroyed by Luftwaffe incendiaries during the Coventry Blitz of 14 November 1940, a raid that killed hundreds of civilians and levelled much of the city centre; only the tower, spire and outer walls survived. Within days Provost Richard Howard had the words 'Father Forgive' inscribed behind the ruined sanctuary, and the new cathedral was conceived from the outset around a ministry of reconciliation, expressed institutionally through the Community of the Cross of Nails and post-war links with Germany. The ruins are separately listed at Grade I and are maintained as a garden of remembrance rather than rebuilt.",
        es: "La catedral medieval de St Michael's fue destruida por bombas incendiarias de la Luftwaffe durante el bombardeo de Coventry del 14 de noviembre de 1940, un ataque que mató a centenares de civiles y arrasó buena parte del centro; solo sobrevivieron la torre, la aguja y los muros exteriores. A los pocos días, el deán Richard Howard hizo grabar «Padre, perdona» tras el presbiterio arruinado, y la catedral nueva se concibió desde el principio en torno a un ministerio de reconciliación, articulado institucionalmente en la Community of the Cross of Nails y en los vínculos de posguerra con Alemania. Las ruinas están protegidas de forma independiente en grado I y se mantienen como jardín del recuerdo en vez de reconstruirse.",
        it: "La cattedrale medievale di St Michael's fu distrutta dagli spezzoni incendiari della Luftwaffe durante il bombardamento di Coventry del 14 novembre 1940, un attacco che uccise centinaia di civili e rase al suolo gran parte del centro; sopravvissero soltanto la torre, la guglia e i muri esterni. Nel giro di pochi giorni il provost Richard Howard fece incidere «Padre, perdona» dietro il presbiterio in rovina, e la nuova cattedrale fu concepita fin dall'inizio attorno a un ministero di riconciliazione, tradotto istituzionalmente nella Community of the Cross of Nails e nei legami postbellici con la Germania. Le rovine sono vincolate separatamente in grado I e mantenute come giardino della memoria anziché ricostruite.",
      },
      sources: [
        { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Coventry_Cathedral', title: 'Coventry Cathedral', license: 'CC BY-SA 4.0' },
        { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Coventry_Blitz', title: 'Coventry Blitz', license: 'CC BY-SA 4.0' },
      ],
    },
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q1138070', title: 'Coventry Cathedral (Q1138070)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Coventry_Cathedral', title: 'Coventry Cathedral', license: 'CC BY-SA 4.0' },
      { kind: 'institution', url: 'https://historicengland.org.uk/listing/the-list/list-entry/1342941', title: 'Cathedral Church of St Michael, Coventry — National Heritage List for England 1342941', license: null },
    ],
    tier: 'canon',
  },
  {
    id: 'leicester-engineering-building',
    wikidataId: 'Q115819295',
    name: {
      en: 'Engineering Building, University of Leicester',
      es: 'Edificio de Ingeniería de la Universidad de Leicester',
      it: "Edificio di Ingegneria dell'Università di Leicester",
    },
    architectId: 'james-stirling',
    location: { city: 'Leicester', countryCode: 'GB', lat: 52.62033, lon: -1.12366 },
    inception: 1959,
    completed: 1963,
    demolished: null,
    typology: 'educational',
    materials: ['brick', 'steel-and-glass', 'concrete'],
    structure: {
      en: 'A concrete-framed tower of offices and laboratories, crowned by a raised water tank and carrying two lecture theatres cantilevered out on a great corbel, stands against low workshops roofed in patent-glazed prisms rotated forty-five degrees to the plan.',
      es: 'Una torre de hormigón con oficinas y laboratorios, coronada por un depósito de agua elevado y con dos aulas en voladizo sobre una gran ménsula, se alza contra unos talleres bajos cubiertos por prismas de vidrio patentado girados cuarenta y cinco grados respecto a la planta.',
      it: "Una torre in cemento con uffici e laboratori, coronata da un serbatoio d'acqua rialzato e con due aule a sbalzo su una grande mensola, si erge contro officine basse coperte da prismi in vetratura brevettata ruotati di quarantacinque gradi rispetto alla pianta.",
    },
    program: {
      en: 'Commissioned in 1957 by the University of Leicester for its engineering department, the building had to hold offices, laboratories, two lecture theatres and heavy machine workshops on a cramped site, with a water tank raised high enough to serve the hydraulics laboratory.',
      es: 'Encargado en 1957 por la Universidad de Leicester para su departamento de ingeniería, el edificio debía reunir despachos, laboratorios, dos aulas y talleres de maquinaria pesada en un solar angosto, con un depósito de agua elevado lo bastante para alimentar el laboratorio de hidráulica.',
      it: "Commissionato nel 1957 dall'Università di Leicester per il dipartimento di ingegneria, l'edificio doveva riunire uffici, laboratori, due aule e officine con macchinari pesanti su un lotto angusto, con un serbatoio d'acqua abbastanza alto da servire il laboratorio di idraulica.",
    },
    heritage: 'national',
    currentUse: {
      en: 'University teaching and research building, its glazing and services renewed in 2016–17.',
      es: 'Edificio universitario de docencia e investigación, con carpinterías e instalaciones renovadas en 2016-17.',
      it: 'Edificio universitario per didattica e ricerca, con serramenti e impianti rinnovati nel 2016-17.',
    },
    detailRect: { x: 0.32, y: 0.58, w: 0.28, h: 0.20 },
    image: {
      commonsFile: 'Leicester University Engineering Building.jpg',
      photographer: 'NotFromUtrecht',
      license: 'CC BY-SA 3.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Leicester_University_Engineering_Building.jpg',
      width: 0,
      height: 0,
    },
    dossier: {
      en: "The brief was awkward enough to become the design. Leicester needed workshops with overhead cranes, laboratories, offices, two lecture theatres and a raised head of water for hydraulics experiments, all on a small plot beside Victoria Park. Stirling and Gowan gave each requirement its own frankly declared shape and stacked them: the water tank crowns a tower whose chamfered, crystalline glazing wraps the offices and labs; the lecture theatres cantilever out at the base on a heavy concrete corbel; the workshops spread low behind under a roof of glazed prisms turned forty-five degrees to the walls, so that the plan reads as a diamond grid. The palette is red brick and red tile against patent glazing lined with fibreglass and coated with aluminium — industrial, cheap and used with obvious relish. Completed in 1963 with Frank Newby as engineer, it closed the polite phase of British post-war modernism and is read now as both a high point of Brutalism and the first move towards Stirling's postmodernism.",
      es: 'El programa era tan incómodo que acabó convertido en el proyecto. Leicester necesitaba talleres con puentes grúa, laboratorios, despachos, dos aulas y una columna de agua elevada para los ensayos de hidráulica, todo en una parcela pequeña junto a Victoria Park. Stirling y Gowan dieron a cada exigencia una forma declarada sin disimulo y las apilaron: el depósito corona una torre cuyo acristalamiento achaflanado y cristalino envuelve despachos y laboratorios; las aulas vuelan en la base sobre una pesada ménsula de hormigón; los talleres se extienden bajos por detrás, bajo una cubierta de prismas de vidrio girados cuarenta y cinco grados respecto a los muros, de modo que la planta se lee como una retícula romboidal. La paleta es ladrillo y plaqueta rojos contra vidriería patentada forrada de fibra de vidrio y recubierta de aluminio: industrial, barata y usada con evidente gusto. Terminado en 1963 con Frank Newby como ingeniero, cerró la fase cortés del modernismo británico de posguerra.',
      it: "Il programma era così scomodo da diventare il progetto. Leicester aveva bisogno di officine con carriponte, laboratori, uffici, due aule e una colonna d'acqua rialzata per le prove di idraulica, il tutto su un lotto piccolo accanto a Victoria Park. Stirling e Gowan diedero a ciascuna esigenza una forma dichiarata senza infingimenti e le impilarono: il serbatoio corona una torre la cui vetratura smussata e cristallina avvolge uffici e laboratori; le aule sporgono alla base su una pesante mensola in cemento; le officine si distendono basse alle spalle, sotto una copertura di prismi vetrati ruotati di quarantacinque gradi rispetto ai muri, sicché la pianta si legge come una griglia romboidale. La tavolozza è mattone e piastrella rossa contro vetrature brevettate foderate di fibra di vetro e rivestite di alluminio: industriali, economiche e usate con evidente gusto. Ultimato nel 1963 con Frank Newby ingegnere, chiuse la fase garbata del moderno britannico del dopoguerra.",
    },
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q115819295', title: 'University of Leicester Engineering Building (Q115819295)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/University_of_Leicester_Engineering_Building', title: 'University of Leicester Engineering Building', license: 'CC BY-SA 4.0' },
    ],
    tier: 'canon',
  },
  {
    id: 'st-hildas-garden-building',
    wikidataId: 'Q26660048',
    name: {
      en: "The Garden Building, St Hilda's College",
      es: "Garden Building, St Hilda's College",
      it: "Garden Building, St Hilda's College",
    },
    architectId: 'alison-smithson',
    location: { city: 'Oxford', countryCode: 'GB', lat: 51.74799, lon: -1.24556 },
    inception: 1968,
    completed: 1970,
    demolished: null,
    typology: 'housing',
    materials: ['concrete', 'timber'],
    structure: {
      en: 'A four-storey block bent into a shallow U, built of precast concrete posts and beams with concrete infill panels and a pale brick entrance front, and wrapped on three sides by a freestanding hardwood trellis that shades the full-height glazing and carries none of the load.',
      es: 'Un bloque de cuatro plantas doblado en U abierta, construido con postes y vigas de hormigón prefabricado, paneles de relleno de hormigón y un frente de acceso de ladrillo claro, envuelto en tres de sus lados por una celosía exenta de madera dura que protege del sol el acristalamiento de suelo a techo sin recibir carga alguna.',
      it: "Un blocco di quattro piani piegato a U aperta, costruito con montanti e travi in cemento prefabbricato, pannelli di tamponamento in cemento e un fronte d'ingresso in mattone chiaro, avvolto su tre lati da un traliccio in legno duro autoportante che ombreggia la vetratura a tutta altezza senza portare alcun carico.",
    },
    program: {
      en: "Built for St Hilda's College, then a women's college of the University of Oxford, to provide fifty-one student rooms and a staff flat on a lawn beside the River Cherwell.",
      es: "Construido para St Hilda's College, entonces colegio femenino de la Universidad de Oxford, para alojar cincuenta y una habitaciones de estudiantes y una vivienda de personal en una pradera junto al río Cherwell.",
      it: "Costruito per il St Hilda's College, allora collegio femminile dell'Università di Oxford, per ospitare cinquantuno camere per studenti e un alloggio di servizio su un prato lungo il fiume Cherwell.",
    },
    heritage: 'national',
    currentUse: {
      en: 'Student accommodation; the college is fundraising to restore the timber screen and renew the glazing.',
      es: 'Residencia de estudiantes; el colegio recauda fondos para restaurar la celosía de madera y renovar el acristalamiento.',
      it: 'Alloggi per studenti; il collegio raccoglie fondi per restaurare il traliccio ligneo e rinnovare le vetrate.',
    },
    detailRect: { x: 0.26, y: 0.40, w: 0.28, h: 0.28 },
    image: {
      commonsFile: "Garden Building, St. Hilda's College, Oxford.jpg",
      photographer: 'seier+seier',
      license: 'CC BY 2.0',
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Garden_Building,_St._Hilda%27s_College,_Oxford.jpg",
      width: 0,
      height: 0,
    },
    dossier: {
      en: "The Smithsons built very little, and this is their only work in Oxford. St Hilda's, then a women's college, needed fifty-one rooms on a lawn hemmed in by listed houses and the Cherwell, and the answer was a compact four-storey block bent into a shallow U so that every room looks out into the trees. Each room is a generous single with a full-height window; stairs, services and a cleaner's room are packed into the middle. What everyone remembers is the veil. A hardwood trellis of verticals and diagonals stands clear of the glass on three sides, filtering sun, giving privacy from the garden without curtains, and turning what would otherwise be a plain glazed slab into something between a timber-framed building and a piece of scaffolding. Ove Arup and Partners engineered the precast frame. Built in 1968–70 and opened in 1971, the building is listed Grade II and the college is now raising money to repair it.",
      es: "Los Smithson construyeron muy poco, y esta es su única obra en Oxford. St Hilda's, entonces colegio femenino, necesitaba cincuenta y una habitaciones en una pradera encajonada entre casas protegidas y el Cherwell, y la respuesta fue un bloque compacto de cuatro plantas doblado en U abierta para que todos los cuartos miren a los árboles. Cada habitación es individual y amplia, con una ventana de suelo a techo; escaleras, instalaciones y el cuarto de limpieza se concentran en el centro. Lo que todo el mundo recuerda es el velo: una celosía de madera dura, de verticales y diagonales, separada del vidrio en tres frentes, que filtra el sol, da intimidad frente al jardín sin necesidad de cortinas y convierte lo que habría sido una losa acristalada corriente en algo entre un entramado de madera y un andamio. Ove Arup and Partners calculó la estructura prefabricada. Levantado en 1968-70 y abierto en 1971, está protegido en grado II.",
      it: "Gli Smithson costruirono pochissimo, e questa è la loro unica opera a Oxford. St Hilda's, allora collegio femminile, aveva bisogno di cinquantuno camere su un prato stretto fra case vincolate e il Cherwell, e la risposta fu un blocco compatto di quattro piani piegato a U aperta perché ogni stanza guardi verso gli alberi. Ogni camera è una singola generosa con finestra a tutta altezza; scale, impianti e il locale per le addette alle pulizie sono concentrati al centro. Ciò che tutti ricordano è il velo: un traliccio in legno duro, fatto di verticali e diagonali, staccato dal vetro su tre lati, che filtra il sole, garantisce riservatezza verso il giardino senza tende e trasforma quella che sarebbe stata una banale lastra vetrata in qualcosa fra un edificio a graticcio e un ponteggio. Ove Arup and Partners calcolò la struttura prefabbricata. Costruito nel 1968-70 e inaugurato nel 1971, è vincolato in grado II.",
    },
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q26660048', title: "The Garden Building at St Hilda's College (Q26660048)", license: null },
      { kind: 'institution', url: 'https://historicengland.org.uk/listing/the-list/list-entry/1379819', title: "The Garden Building at St Hilda's College — National Heritage List for England 1379819", license: null },
      { kind: 'institution', url: 'https://www.st-hildas.ox.ac.uk/garden-building-restoration', title: "Garden Building Restoration Project — St Hilda's College, Oxford", license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Alison_and_Peter_Smithson', title: 'Alison and Peter Smithson', license: 'CC BY-SA 4.0' },
    ],
    tier: 'deep',
  },
  {
    id: 'willis-faber-dumas-building',
    wikidataId: 'Q1134093',
    name: {
      en: 'Willis Faber & Dumas Building',
      es: 'Edificio Willis Faber & Dumas',
      it: 'Edificio Willis Faber and Dumas',
    },
    architectId: 'norman-foster',
    location: { city: 'Ipswich', countryCode: 'GB', lat: 52.05560, lon: 1.15070 },
    inception: 1970,
    completed: 1975,
    demolished: null,
    typology: 'commercial',
    materials: ['steel-and-glass', 'concrete'],
    structure: {
      en: 'A grid of concrete columns at fourteen-metre centres carries cantilevered waffle floor slabs, from which a frameless curtain wall of smoked glass is suspended in panels bolted at the corners and sealed with silicone.',
      es: 'Una retícula de pilares de hormigón a catorce metros sostiene forjados reticulares en voladizo de los que cuelga un muro cortina sin carpintería, de vidrio ahumado, en paneles atornillados por las esquinas y sellados con silicona.',
      it: 'Una griglia di pilastri in cemento a quattordici metri di interasse regge solai a cassettoni a sbalzo, dai quali pende una facciata continua senza telaio, in vetro fumé, a pannelli imbullonati agli spigoli e sigillati a silicone.',
    },
    program: {
      en: 'Built as a regional headquarters for the insurance brokers Willis, Faber & Dumas when the firm moved some 1,300 staff out of the City of London to Ipswich, with a ground-floor swimming pool, a gymnasium and a turfed roof garden included to make the move attractive.',
      es: 'Levantado como sede regional de los corredores de seguros Willis, Faber & Dumas cuando la firma trasladó a unos 1.300 empleados de la City de Londres a Ipswich, con piscina en planta baja, gimnasio y una cubierta ajardinada de césped para hacer atractivo el traslado.',
      it: 'Costruito come sede regionale dei broker assicurativi Willis, Faber & Dumas quando la società trasferì circa 1.300 dipendenti dalla City di Londra a Ipswich, con piscina al piano terra, palestra e una copertura a prato per rendere appetibile il trasloco.',
    },
    heritage: 'national',
    currentUse: {
      en: 'Offices, listed Grade I since 1991.',
      es: 'Oficinas, protegido en grado I desde 1991.',
      it: 'Uffici, vincolato in grado I dal 1991.',
    },
    detailRect: { x: 0.44, y: 0.28, w: 0.26, h: 0.34 },
    image: {
      commonsFile: 'Willis Building Ipswich.jpg',
      photographer: 'Sumit Surai',
      license: 'CC BY-SA 4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Willis_Building_Ipswich.jpg',
      width: 0,
      height: 0,
    },
    dossier: {
      en: "Willis, Faber & Dumas wanted to move its staff out of London and then keep them, so the brief included a swimming pool on the ground floor, a gymnasium and a turfed roof garden with a restaurant. Foster Associates took a site hemmed in by road junctions and simply filled it: the plan is a free curve following the pavement lines, with no corners anywhere. The wall is the argument. Panels of dark solar glass hang from the roof edge, bolted at their corners and jointed with silicone, so that from outside there are no mullions at all — by day a black mirror of the surrounding town, by night a transparent section through three open-plan floors linked by escalators. Behind it, deep waffle slabs cantilever from a fourteen-metre column grid, leaving the perimeter clear. Opened in June 1975, it was listed Grade I in 1991, when it was one of only two listed buildings in Britain under thirty years old. The pool was floored over in 1994 but never filled in.",
      es: 'Willis, Faber & Dumas quería sacar a su plantilla de Londres y luego retenerla, así que el encargo incluía una piscina en planta baja, un gimnasio y una cubierta ajardinada con restaurante. Foster Associates tomó un solar encajonado entre cruces de calles y sencillamente lo colmató: la planta es una curva libre que sigue la línea de las aceras, sin una sola esquina. El muro es el argumento. Los paneles de vidrio solar oscuro cuelgan del borde de cubierta, atornillados por las esquinas y sellados con silicona, de manera que desde fuera no hay montantes: de día, un espejo negro de la ciudad; de noche, una sección transparente de tres plantas diáfanas enlazadas por escaleras mecánicas. Detrás, unos gruesos forjados reticulares vuelan desde una retícula de pilares a catorce metros y dejan libre todo el perímetro. Inaugurado en junio de 1975, fue protegido en grado I en 1991, cuando era uno de los dos únicos edificios protegidos de Gran Bretaña con menos de treinta años.',
      it: "Willis, Faber & Dumas voleva portare il personale fuori Londra e poi trattenerlo, così il programma comprendeva una piscina al piano terra, una palestra e una copertura a prato con ristorante. Foster Associates prese un lotto stretto fra incroci stradali e semplicemente lo saturò: la pianta è una curva libera che segue la linea dei marciapiedi, senza un solo spigolo. La parete è l'argomento. I pannelli di vetro solare scuro pendono dal bordo della copertura, imbullonati agli angoli e sigillati a silicone, sicché dall'esterno non esistono montanti: di giorno uno specchio nero della città, di notte una sezione trasparente su tre piani liberi collegati da scale mobili. Dietro, spessi solai a cassettoni sporgono da una griglia di pilastri a quattordici metri lasciando sgombro il perimetro. Inaugurato nel giugno 1975, fu vincolato in grado I nel 1991, quando era uno dei due soli edifici vincolati in Gran Bretagna con meno di trent'anni.",
    },
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q1134093', title: 'Willis Building (Q1134093)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Willis_Building,_Ipswich', title: 'Willis Building, Ipswich', license: 'CC BY-SA 4.0' },
      { kind: 'institution', url: 'https://historicengland.org.uk/listing/the-list/list-entry/1237417', title: 'Willis Corroon Building, Ipswich — National Heritage List for England 1237417', license: null },
    ],
    tier: 'canon',
  },
  {
    id: 'tate-st-ives',
    wikidataId: 'Q2577210',
    name: {
      en: 'Tate St Ives',
      es: 'Tate St Ives',
      it: 'Tate St Ives',
    },
    architectId: 'eldred-evans',
    location: { city: 'St Ives', countryCode: 'GB', lat: 50.21472, lon: -5.48472 },
    inception: 1988,
    completed: 1993,
    demolished: null,
    typology: 'cultural',
    materials: ['concrete', 'stone'],
    structure: {
      en: 'A rendered concrete and blockwork structure stepped into the cliff, its entrance formed as an open drum whose curved loggia and coved head trace the footprint of the gasholder that stood on the site.',
      es: 'Una estructura de hormigón y bloque revocada que se escalona en el acantilado, con el acceso resuelto como un tambor abierto cuya logia curva y bóveda rebajada calcan la huella del gasómetro que ocupaba el solar.',
      it: "Una struttura in cemento e blocchi intonacata che si gradona nella scogliera, con l'ingresso risolto come un tamburo aperto la cui loggia curva e volta ribassata ricalcano l'impronta del gasometro che occupava il sito.",
    },
    program: {
      en: 'Built for Cornwall County Council and the Tate to show the modern British artists who worked in and around St Ives, on the site of the demolished town gasworks above Porthmeor Beach.',
      es: 'Construida para el Consejo del Condado de Cornualles y la Tate para exhibir a los artistas británicos modernos que trabajaron en St Ives y sus alrededores, en el solar de la fábrica de gas demolida sobre la playa de Porthmeor.',
      it: 'Costruita per il Cornwall County Council e la Tate per esporre gli artisti britannici moderni attivi a St Ives e dintorni, sul sito della demolita officina del gas sopra la spiaggia di Porthmeor.',
    },
    heritage: 'none',
    currentUse: {
      en: 'Public art gallery, extended in 2017 and among the most visited in the United Kingdom.',
      es: 'Galería de arte pública, ampliada en 2017 y una de las más visitadas del Reino Unido.',
      it: "Galleria d'arte pubblica, ampliata nel 2017 e fra le più visitate del Regno Unito.",
    },
    detailRect: { x: 0.34, y: 0.20, w: 0.30, h: 0.32 },
    image: {
      commonsFile: 'Tate St Ives (6647).jpg',
      photographer: 'Nilfanion',
      license: 'CC BY-SA 4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Tate_St_Ives_(6647).jpg',
      width: 0,
      height: 0,
    },
    dossier: {
      en: "The site was a gasworks on the slope above Porthmeor Beach, and Evans & Shalev kept its geometry: the circular entrance court is the plan of the demolished gasholder, opened out as a loggia so that the sea is framed the moment you arrive. From the beach the gallery reads as a white rendered cliff of stepped and sliding volumes, closer to the massing of a Cornish fishing town than to a museum; from inside, the rooms climb and turn so that the route through them keeps coming back to windows onto Porthmeor. Built between 1988 and 1993 for Cornwall County Council and the Tate, it was designed to show the modern British artists who had worked in and around St Ives, in the light they painted in; the Tate had already run the town's Barbara Hepworth Museum since 1980. It succeeded so thoroughly that visitor numbers overwhelmed it, and between 2015 and 2017 Jamie Fobert Architects doubled the gallery space by burying new rooms in the hillside behind, leaving Eldred Evans's front elevation untouched.",
      es: 'El solar era una fábrica de gas en la ladera sobre la playa de Porthmeor, y Evans & Shalev conservaron su geometría: el patio circular de acceso es la planta del gasómetro demolido, abierta como una logia para que el mar quede encuadrado nada más llegar. Desde la playa, la galería se lee como un acantilado blanco de volúmenes escalonados y deslizados, más próximo a la masa de un pueblo pesquero de Cornualles que a un museo; por dentro, las salas ascienden y giran de modo que el recorrido vuelve una y otra vez a las ventanas sobre Porthmeor. Construida entre 1988 y 1993 para el Consejo del Condado y la Tate, se pensó para mostrar a los artistas británicos modernos que habían trabajado en St Ives y sus alrededores con la luz en que pintaron; la Tate ya gestionaba desde 1980 el museo de Barbara Hepworth en el pueblo. Funcionó tan bien que el público la desbordó, y entre 2015 y 2017 Jamie Fobert Architects duplicó la superficie enterrando salas nuevas en la ladera trasera.',
      it: "Il sito era un'officina del gas sul pendio sopra la spiaggia di Porthmeor, ed Evans & Shalev ne conservarono la geometria: la corte circolare d'ingresso è la pianta del gasometro demolito, aperta come loggia perché il mare sia inquadrato nell'istante dell'arrivo. Dalla spiaggia la galleria si legge come una scogliera bianca di volumi gradonati e slittati, più vicina alla massa di un villaggio di pescatori della Cornovaglia che a un museo; all'interno le sale salgono e ruotano, così che il percorso torni di continuo alle finestre su Porthmeor. Costruita fra il 1988 e il 1993 per il Cornwall County Council e la Tate, fu pensata per mostrare gli artisti britannici moderni che avevano lavorato a St Ives e dintorni nella luce in cui dipinsero; la Tate gestiva già dal 1980 il museo di Barbara Hepworth in paese. Riuscì tanto bene che il pubblico la travolse, e fra il 2015 e il 2017 Jamie Fobert Architects ne raddoppiò la superficie interrando nuove sale nel pendio retrostante.",
    },
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q2577210', title: 'Tate St Ives (Q2577210)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Tate_St_Ives', title: 'Tate St Ives', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Eldred_Evans', title: 'Eldred Evans', license: 'CC BY-SA 4.0' },
    ],
    tier: 'deep',
  },
  {
    id: 'senedd-cardiff',
    wikidataId: 'Q3309562',
    name: {
      en: 'Senedd',
      es: 'Senedd',
      it: 'Senedd',
    },
    architectId: 'richard-rogers',
    location: { city: 'Cardiff', countryCode: 'GB', lat: 51.46390, lon: -3.16208 },
    inception: 2001,
    completed: 2006,
    demolished: null,
    typology: 'civic',
    materials: ['timber', 'steel-and-glass', 'stone'],
    structure: {
      en: 'A steel-framed pavilion on a Welsh slate plinth, roofed by a wide cantilevered plane whose undulating western red cedar ceiling funnels down into the debating chamber beneath a free-rotating wind cowl.',
      es: 'Un pabellón de estructura de acero sobre un zócalo de pizarra galesa, cubierto por un gran plano en voladizo cuyo techo ondulado de cedro rojo occidental desciende en embudo hasta la sala de plenos, bajo una cofia eólica que gira libremente.',
      it: "Un padiglione con struttura in acciaio su uno zoccolo di ardesia gallese, coperto da un ampio piano a sbalzo il cui soffitto ondulato in cedro rosso occidentale scende a imbuto nell'aula, sotto un cappello eolico che ruota liberamente.",
    },
    program: {
      en: 'Won in open international competition in 1998 and built for the National Assembly for Wales, it houses the Siambr debating chamber and three committee rooms, with the public admitted to the levels above the members.',
      es: 'Ganado en concurso internacional abierto en 1998 y construido para la Asamblea Nacional de Gales, alberga la sala de plenos Siambr y tres salas de comisión, con el público situado en los niveles superiores a los de los parlamentarios.',
      it: "Vinto in concorso internazionale aperto nel 1998 e costruito per l'Assemblea Nazionale del Galles, ospita l'aula Siambr e tre sale di commissione, con il pubblico ammesso ai livelli superiori a quelli dei parlamentari.",
    },
    heritage: 'none',
    currentUse: {
      en: 'Debating chamber and committee rooms of the Senedd, the Welsh Parliament.',
      es: 'Sala de plenos y salas de comisión del Senedd, el Parlamento de Gales.',
      it: 'Aula e sale di commissione del Senedd, il Parlamento gallese.',
    },
    detailRect: { x: 0.30, y: 0.28, w: 0.28, h: 0.30 },
    image: {
      commonsFile: 'Cardiff - National Assembly for Wales - geograph.org.uk - 6658563.jpg',
      photographer: 'Colin Smith',
      license: 'CC BY-SA 2.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Cardiff_-_National_Assembly_for_Wales_-_geograph.org.uk_-_6658563.jpg',
      width: 0,
      height: 0,
    },
    dossier: {
      en: "Ron Davies asked for a building that would 'capture the imagination of the Welsh people'; fifty-five architects registered interest and the Richard Rogers Partnership was recommended unanimously in October 1998. The idea is a single move — lift a great roof on slender steel columns above a slate plinth of steps rising from Cardiff Bay, glaze everything beneath it, and put the elected members below the public rather than above them. Visitors enter at roof level and look down through a glass floor into the Siambr, where a funnel of Canadian western red cedar draws the ceiling into the chamber and up to a cowl that rotates with the wind and ventilates it. About a thousand tonnes of Welsh slate were used; twenty-seven boreholes a hundred metres deep temper the building geothermally, a biomass boiler burns waste wood chip and rainwater flushes the lavatories. It opened on St David's Day 2006, far over its original budget and years late, and was shortlisted for the Stirling Prize that year.",
      es: 'Ron Davies pidió un edificio capaz de «capturar la imaginación del pueblo galés»; cincuenta y cinco estudios manifestaron interés y en octubre de 1998 el jurado recomendó por unanimidad a la Richard Rogers Partnership. La idea es un solo gesto: levantar una gran cubierta sobre esbeltos pilares de acero por encima de un zócalo de pizarra escalonado que asciende desde la bahía de Cardiff, acristalar todo lo que queda debajo y situar a los parlamentarios por debajo del público en vez de por encima. El visitante entra a la altura de la cubierta y mira hacia abajo, a través de un suelo de vidrio, hacia la Siambr, donde un embudo de cedro rojo occidental arrastra el techo hacia el interior de la sala y hasta una cofia que gira con el viento y la ventila. Se emplearon unas mil toneladas de pizarra galesa; veintisiete sondeos de cien metros atemperan el edificio geotérmicamente. Se inauguró el día de San David de 2006, muy por encima del presupuesto y con años de retraso.',
      it: "Ron Davies chiese un edificio capace di «catturare l'immaginazione del popolo gallese»; cinquantacinque studi manifestarono interesse e nell'ottobre 1998 la giuria raccomandò all'unanimità la Richard Rogers Partnership. L'idea è un gesto solo: sollevare una grande copertura su esili colonne d'acciaio sopra uno zoccolo di ardesia a gradoni che risale dalla baia di Cardiff, vetrare tutto ciò che sta sotto e collocare i parlamentari al di sotto del pubblico anziché al di sopra. Il visitatore entra alla quota del tetto e guarda in basso, attraverso un pavimento di vetro, verso la Siambr, dove un imbuto di cedro rosso occidentale trascina il soffitto dentro l'aula e su fino a un cappello che ruota con il vento e la ventila. Furono impiegate circa mille tonnellate di ardesia gallese; ventisette sonde profonde cento metri temperano l'edificio geotermicamente. Fu inaugurato il giorno di san David del 2006, molto oltre il preventivo e con anni di ritardo.",
    },
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q3309562', title: 'Senedd building (Q3309562)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Senedd_building', title: 'Senedd building', license: 'CC BY-SA 4.0' },
    ],
    tier: 'canon',
  },
  {
    id: 'selfridges-birmingham',
    wikidataId: 'Q7448350',
    name: {
      en: 'Selfridges Building, Birmingham',
      es: 'Edificio Selfridges de Birmingham',
      it: 'Edificio Selfridges di Birmingham',
    },
    architectId: 'amanda-levete',
    location: { city: 'Birmingham', countryCode: 'GB', lat: 52.47780, lon: -1.89226 },
    inception: 2001,
    completed: 2003,
    demolished: null,
    typology: 'commercial',
    materials: ['concrete', 'steel-and-glass', 'mixed'],
    structure: {
      en: 'A steel frame sprayed with concrete to form one continuous double-curved shell, finished in a blue-rendered surface and clad in about fifteen thousand anodised aluminium discs fixed clear of it.',
      es: 'Un esqueleto de acero proyectado con hormigón para formar una única cáscara continua de doble curvatura, acabada en un fondo revocado en azul y revestida con unos quince mil discos de aluminio anodizado fijados separados de él.',
      it: "Uno scheletro d'acciaio spruzzato di calcestruzzo a formare un unico guscio continuo a doppia curvatura, rifinito con un fondo intonacato di blu e rivestito da circa quindicimila dischi di alluminio anodizzato fissati staccati da esso.",
    },
    program: {
      en: 'Commissioned by Selfridges as the anchor store of the rebuilt Bullring, on a sloping site wrapping the corner of Moor Street and Park Street beside the medieval church of St Martin.',
      es: 'Encargado por Selfridges como tienda ancla del nuevo Bullring, en un solar en pendiente que dobla la esquina de Moor Street y Park Street junto a la iglesia medieval de St Martin.',
      it: "Commissionato da Selfridges come negozio di richiamo del nuovo Bullring, su un lotto in pendenza che gira l'angolo fra Moor Street e Park Street accanto alla chiesa medievale di St Martin.",
    },
    heritage: 'none',
    currentUse: {
      en: 'Department store.',
      es: 'Grandes almacenes.',
      it: 'Grande magazzino.',
    },
    detailRect: { x: 0.32, y: 0.26, w: 0.26, h: 0.30 },
    image: {
      commonsFile: 'Selfridges Building Birmingham.jpg',
      photographer: 'Fatih Renkligil',
      license: 'CC BY-SA 4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Selfridges_Building_Birmingham.jpg',
      width: 0,
      height: 0,
    },
    dossier: {
      en: "Birmingham demolished its 1960s Bull Ring and, in rebuilding it, Selfridges' chief executive Vittorio Radice asked Future Systems for a store worth travelling to. Amanda Levete and Jan Kaplický gave him a building with no façade, no windows and no straight lines: a soft bulging mass that leans over the pavement, drops to meet the churchyard of St Martin's, and is skinned in some fifteen thousand anodised aluminium discs mounted proud of a blue-rendered surface, so that the whole thing shifts and glitters as the light changes. The form was buildable only because computer-aided design allowed a steel frame to be wrapped in sprayed concrete, a technique closer to tunnelling than to retail. Inside, the interest is a pair of atria crossed by escalators; outside is deliberately blank, a shop that sells itself as an object on the skyline instead of through a window display. It was completed in 2003 at a cost of about £60 million, and it turned the tail end of Birmingham's city centre into a destination.",
      es: 'Birmingham demolió su Bull Ring de los años sesenta y, al reconstruirlo, el consejero delegado de Selfridges, Vittorio Radice, pidió a Future Systems una tienda por la que mereciera la pena viajar. Amanda Levete y Jan Kaplický le dieron un edificio sin fachada, sin ventanas y sin una sola línea recta: una masa blanda y abombada que se inclina sobre la acera, baja a encontrarse con el cementerio de St Martin y va forrada con unos quince mil discos de aluminio anodizado montados separados de un fondo revocado en azul, de manera que el conjunto se mueve y destella según cambia la luz. La forma solo fue construible porque el diseño asistido por ordenador permitió envolver un esqueleto de acero en hormigón proyectado, una técnica más próxima a la obra de túneles que al comercio. Se terminó en 2003 con un coste de unos sesenta millones de libras. Dentro, lo interesante son dos atrios cruzados por escaleras mecánicas; fuera, la ciega deliberación de un comercio que se vende como objeto en el perfil de la ciudad.',
      it: "Birmingham demolì il suo Bull Ring degli anni Sessanta e, nel ricostruirlo, l'amministratore delegato di Selfridges Vittorio Radice chiese a Future Systems un negozio per cui valesse la pena viaggiare. Amanda Levete e Jan Kaplický gli diedero un edificio senza facciata, senza finestre e senza una sola linea retta: una massa morbida e rigonfia che si sporge sul marciapiede, scende a incontrare il sagrato di St Martin ed è rivestita da circa quindicimila dischi di alluminio anodizzato montati staccati da un fondo intonacato di blu, sicché l'insieme si muove e scintilla al variare della luce. La forma fu costruibile solo perché la progettazione assistita permise di avvolgere uno scheletro d'acciaio in calcestruzzo spruzzato, tecnica più vicina allo scavo di gallerie che al commercio. Fu completato nel 2003 con una spesa di circa sessanta milioni di sterline. Dentro, l'interesse sta in due atri attraversati da scale mobili; fuori, la cecità voluta di un negozio che si vende come oggetto nel profilo della città.",
    },
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q7448350', title: 'Selfridges Building, Birmingham (Q7448350)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Selfridges_Birmingham', title: 'Selfridges Birmingham', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Amanda_Levete', title: 'Amanda Levete', license: 'CC BY-SA 4.0' },
    ],
    tier: 'canon',
  },
];
