import type { Building } from '@/types/building';

// Wave 5 curator agent (Central and Eastern Europe): real, sourced Building entries for this slice.
//
// Slice countries: PL, CZ, SK, HU, RO, BG, RS, HR, SI, BA, MK, AL, UA, BY, MD, RU.
// M49 note: PL/CZ/HU/RU/SK/RO/BG/BY/UA/MD are *Eastern Europe*; HR/SI/RS/BA/MK/AL
// are *Southern Europe*, the same subregion as Italy, Spain and Greece.
//
// Every image below is an EXTERIOR view. For buildings whose architect died
// less than 70 years ago the photographer's CC licence clears the photograph
// but not the architecture, so the entry additionally relies on freedom of
// panorama in the country concerned (CZ, PL, HR, RS, MK and RU-for-buildings
// all provide it). Slovenia, Romania, Belarus, Ukraine and Bulgaria do not,
// which is why no in-copyright building from those countries appears here.
export const EUROPE_CENTRAL_BUILDINGS: Building[] = [
  {
    id: 'zelena-hora-pilgrimage-church',
    wikidataId: 'Q752318',
    name: {
      en: 'Pilgrimage Church of St John of Nepomuk at Zelená hora',
      es: 'Iglesia de peregrinación de San Juan Nepomuceno en Zelená hora',
      it: 'Chiesa di pellegrinaggio di San Giovanni Nepomuceno a Zelená hora',
    },
    architectId: 'jan-santini-aichel',
    location: { city: 'Žďár nad Sázavou', countryCode: 'CZ', lat: 49.58, lon: 15.94194 },
    inception: 1719,
    completed: 1722,
    demolished: null,
    typology: 'sacral',
    materials: ['stone', 'brick'],
    structure: {
      en: 'A rendered masonry rotunda on a five-pointed star plan, its central space ringed by five pairs of piers carrying ribbed vaults and a shallow dome, with five tent-roofed chapels pushed out between them.',
      es: 'Una rotonda de fábrica revocada sobre planta de estrella de cinco puntas, cuyo espacio central rodean cinco pares de pilares que sostienen bóvedas de crucería y una cúpula rebajada, con cinco capillas de cubierta en tienda proyectadas entre ellos.',
      it: 'Una rotonda in muratura intonacata su pianta a stella a cinque punte, il cui spazio centrale è cinto da cinque coppie di pilastri che reggono volte costolonate e una cupola ribassata, con cinque cappelle a tetto conico sporgenti fra di essi.',
    },
    program: {
      en: 'Built for Václav Vejmluva, abbot of the Cistercian monastery at Žďár, as a pilgrimage church for the newly beatified John of Nepomuk, and still in use as a church.',
      es: 'Construida para Václav Vejmluva, abad del monasterio cisterciense de Žďár, como iglesia de peregrinación al recién beatificado Juan Nepomuceno, y todavía en uso como iglesia.',
      it: 'Costruita per Václav Vejmluva, abate del monastero cistercense di Žďár, come chiesa di pellegrinaggio per il neo-beatificato Giovanni Nepomuceno, ed è tuttora in uso come chiesa.',
    },
    heritage: 'unesco',
    currentUse: {
      en: 'Parish church and pilgrimage site, inscribed on the UNESCO World Heritage List in 1994.',
      es: 'Iglesia parroquial y lugar de peregrinación, inscrita en la Lista del Patrimonio Mundial de la UNESCO en 1994.',
      it: 'Chiesa parrocchiale e luogo di pellegrinaggio, iscritta nella Lista del Patrimonio Mondiale UNESCO nel 1994.',
    },
    detailRect: { x: 0.36, y: 0.40, w: 0.30, h: 0.28 },
    image: {
      commonsFile: 'File:Kostel svatého Jana Nepomuckého (3).jpg',
      photographer: 'Aqalexor',
      license: 'CC BY-SA 4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Kostel_svat%C3%A9ho_Jana_Nepomuck%C3%A9ho_(3).jpg',
      width: 0,
      height: 0,
    },
    dossier: {
      en: 'On 15 April 1719 the tomb of John of Nepomuk was opened in Prague and the tissue found inside it was declared his incorrupt tongue. Within four months the abbot of Žďár had a design. Santini built the whole church around the number five — five points to the star plan, five chapels, five altars, five stars in the vault, matching the five stars of the saint\'s halo — and set the church inside a ten-sided cloister that repeats the figure at the scale of the hill. The architecture is stranger than the programme required. Pointed arches, ribbed vaults and a rippling parapet quote the Gothic three centuries after it ended, an archaism the Cistercians read as respect for their medieval foundation. Consecrated in 1722, it was Santini\'s last work; he died the following year. A fire in 1784 destroyed the roof, which was rebuilt to a flatter profile. UNESCO inscribed it in 1994, citing the mathematical ratios that produce, in the nomination\'s phrase, an independent spatial reality.',
      es: 'El 15 de abril de 1719 se abrió en Praga la tumba de Juan Nepomuceno y el tejido hallado en su interior se declaró su lengua incorrupta. En menos de cuatro meses el abad de Žďár tenía un proyecto. Santini construyó toda la iglesia en torno al número cinco —cinco puntas de la estrella en planta, cinco capillas, cinco altares, cinco estrellas en la bóveda, como las cinco del nimbo del santo— y la situó dentro de un claustro decagonal que repite la figura a escala del cerro. La arquitectura es más extraña de lo que el programa exigía. Arcos apuntados, bóvedas de crucería y un pretil ondulante citan el gótico tres siglos después de su final, un arcaísmo que los cistercienses leyeron como respeto por su fundación medieval. Consagrada en 1722, fue la última obra de Santini, muerto al año siguiente. Un incendio destruyó la cubierta en 1784. La UNESCO la inscribió en 1994.',
      it: 'Il 15 aprile 1719 fu aperta a Praga la tomba di Giovanni Nepomuceno e il tessuto trovato al suo interno venne dichiarato la sua lingua incorrotta. In meno di quattro mesi l\'abate di Žďár aveva un progetto. Santini costruì l\'intera chiesa attorno al numero cinque — cinque punte della stella in pianta, cinque cappelle, cinque altari, cinque stelle nella volta, come le cinque del nimbo del santo — e la collocò dentro un chiostro decagonale che ripete la figura alla scala della collina. L\'architettura è più strana di quanto il programma richiedesse. Archi acuti, volte costolonate e un parapetto ondulato citano il gotico tre secoli dopo la sua fine, un arcaismo che i cistercensi lessero come rispetto per la propria fondazione medievale. Consacrata nel 1722, fu l\'ultima opera di Santini, morto l\'anno seguente. Un incendio distrusse il tetto nel 1784. L\'UNESCO la iscrisse nel 1994.',
    },
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q752318', title: 'Pilgrimage Church of Saint John of Nepomuk (Q752318)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Pilgrimage_Church_of_Saint_John_of_Nepomuk', title: 'Pilgrimage Church of Saint John of Nepomuk', license: 'CC BY-SA 4.0' },
      { kind: 'institution', url: 'https://whc.unesco.org/en/list/690/', title: 'Pilgrimage Church of St John of Nepomuk at Zelená Hora — UNESCO World Heritage Centre', license: null },
    ],
    tier: 'canon',
  },
  {
    id: 'stari-most-mostar',
    wikidataId: 'Q188528',
    name: {
      en: 'Stari Most (Old Bridge), Mostar',
      es: 'Stari Most (Puente Viejo) de Mostar',
      it: 'Stari Most (Ponte Vecchio) di Mostar',
    },
    architectId: 'mimar-hayruddin',
    location: { city: 'Mostar', countryCode: 'BA', lat: 43.33728, lon: 17.81503 },
    inception: 1557,
    completed: 1566,
    demolished: null,
    typology: 'infrastructure',
    materials: ['stone'],
    structure: {
      en: 'A single hump-backed limestone arch of about 29 metres, rising some 12 metres from abutments keyed directly into the rock of the gorge rather than founded on piers in the river.',
      es: 'Un único arco de piedra caliza de lomo de asno de unos 29 metros, con una flecha de unos 12, cuyos estribos se empotran directamente en la roca del desfiladero en lugar de apoyarse en pilas dentro del río.',
      it: 'Un\'unica arcata a schiena d\'asino in calcare di circa 29 metri, con una freccia di circa 12, le cui spalle si incastrano direttamente nella roccia della gola invece di poggiare su pile nel fiume.',
    },
    program: {
      en: 'Commissioned by Suleiman the Magnificent to replace a wooden suspension crossing on the Neretva, and still the principal pedestrian link between the two halves of Mostar.',
      es: 'Encargado por Solimán el Magnífico para sustituir un puente colgante de madera sobre el Neretva, sigue siendo el principal enlace peatonal entre las dos mitades de Mostar.',
      it: 'Commissionato da Solimano il Magnifico per sostituire un ponte sospeso in legno sulla Neretva, resta il principale collegamento pedonale fra le due metà di Mostar.',
    },
    heritage: 'unesco',
    currentUse: {
      en: 'Pedestrian bridge and the centre of the Old Bridge Area of the Old City of Mostar, inscribed by UNESCO in 2005.',
      es: 'Puente peatonal y centro del conjunto del Puente Viejo del casco antiguo de Mostar, inscrito por la UNESCO en 2005.',
      it: 'Ponte pedonale e centro dell\'area del Ponte Vecchio della città storica di Mostar, iscritta dall\'UNESCO nel 2005.',
    },
    detailRect: { x: 0.50, y: 0.36, w: 0.32, h: 0.24 },
    image: {
      commonsFile: 'File:Mostar bridge cloudy.jpg',
      photographer: 'Hibasi',
      license: 'CC BY-SA 4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Mostar_bridge_cloudy.jpg',
      width: 0,
      height: 0,
    },
    dossier: {
      en: 'The Ottoman geographer Katip Çelebi recorded that the wooden bridge Hayruddin was sent to replace "swayed so much that people crossing it did so in mortal fear". His answer was a single stone arch thrown clear across the Neretva gorge, with no pier in the water: the abutments are keyed into the limestone cliffs and rise more than six metres before the arch springs. Work began in 1557 and the inscription dates completion to the Muslim year 974, between July 1566 and July 1567. On completion it was among the widest arches yet built anywhere, and the townspeople took their name from it — mostari, the bridge keepers, who manned the two towers at either end. Almost nothing is documented about how it was made; the mortar is traditionally said to have been mixed with egg white. What survived instead were the tower gates, the ribbed roadway that still gives a foothold on the climb, and the name of the builder.',
      es: 'El geógrafo otomano Katip Çelebi anotó que el puente de madera que Hayruddin fue enviado a sustituir «se bamboleaba tanto que quienes lo cruzaban lo hacían con miedo mortal». Su respuesta fue un arco único de piedra lanzado limpiamente sobre el desfiladero del Neretva, sin ninguna pila en el agua: los estribos se empotran en los acantilados calizos y ascienden más de seis metros antes de que arranque el arco. Las obras comenzaron en 1557 y la inscripción fecha su terminación en el año musulmán 974, entre julio de 1566 y julio de 1567. Al acabarse figuraba entre los arcos más anchos construidos hasta entonces, y los habitantes tomaron de él su nombre: mostari, los guardianes del puente, que atendían las dos torres de los extremos. Casi nada se documenta sobre su ejecución; la tradición sostiene que el mortero se amasó con clara de huevo.',
      it: 'Il geografo ottomano Katip Çelebi annotò che il ponte di legno che Hayruddin fu mandato a sostituire «oscillava tanto che chi lo attraversava lo faceva con timore mortale». La sua risposta fu un\'unica arcata in pietra gettata di netto sulla gola della Neretva, senza alcuna pila in acqua: le spalle si incastrano nelle falesie calcaree e salgono per oltre sei metri prima che l\'arco si imposti. I lavori iniziarono nel 1557 e l\'iscrizione data il completamento all\'anno musulmano 974, fra il luglio 1566 e il luglio 1567. Al termine era fra le arcate più ampie mai costruite, e gli abitanti ne presero il nome: mostari, i custodi del ponte, che presidiavano le due torri alle estremità. Quasi nulla è documentato sulla sua esecuzione; la tradizione vuole che la malta fosse impastata con albume d\'uovo.',
    },
    context: {
      body: {
        en: 'During the Croat–Bosniak War the Army of the Republic of Bosnia and Herzegovina used the bridge as a supply route, and on 9 November 1993 it was shelled and destroyed by the Croatian Defence Council. The arch was rebuilt to the original design, largely from stone quarried locally and blocks recovered from the river, under a programme coordinated with UNESCO and the World Bank; it reopened on 23 July 2004, and the old town around it was inscribed as a World Heritage Site in 2005. In 2017 the appeals chamber of the International Criminal Tribunal for the former Yugoslavia found that the bridge had been a legitimate military target at the time it was destroyed.',
        es: 'Durante la guerra croato-bosnia el Ejército de la República de Bosnia y Herzegovina utilizó el puente como vía de suministro y, el 9 de noviembre de 1993, fue bombardeado y destruido por el Consejo de Defensa Croata. El arco se reconstruyó según el diseño original, en buena parte con piedra de canteras locales y sillares recuperados del río, mediante un programa coordinado con la UNESCO y el Banco Mundial; se reabrió el 23 de julio de 2004 y el casco antiguo que lo rodea fue inscrito como Patrimonio Mundial en 2005. En 2017 la sala de apelaciones del Tribunal Penal Internacional para la ex Yugoslavia concluyó que el puente había constituido un objetivo militar legítimo en el momento de su destrucción.',
        it: 'Durante la guerra croato-bosniaca l\'Esercito della Repubblica di Bosnia ed Erzegovina utilizzò il ponte come via di rifornimento e, il 9 novembre 1993, esso fu bombardato e distrutto dal Consiglio di difesa croato. L\'arcata fu ricostruita secondo il disegno originale, in larga parte con pietra di cave locali e conci recuperati dal fiume, nell\'ambito di un programma coordinato con l\'UNESCO e la Banca Mondiale; riaprì il 23 luglio 2004 e il centro storico circostante fu iscritto come Patrimonio Mondiale nel 2005. Nel 2017 la camera d\'appello del Tribunale penale internazionale per l\'ex Jugoslavia stabilì che il ponte era stato un obiettivo militare legittimo al momento della distruzione.',
      },
      sources: [
        { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Stari_Most', title: 'Stari Most', license: 'CC BY-SA 4.0' },
        { kind: 'institution', url: 'https://whc.unesco.org/en/list/946/', title: 'Old Bridge Area of the Old City of Mostar — UNESCO World Heritage Centre', license: null },
      ],
    },
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q188528', title: 'Stari Most (Q188528)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Stari_Most', title: 'Stari Most', license: 'CC BY-SA 4.0' },
      { kind: 'institution', url: 'https://whc.unesco.org/en/list/946/', title: 'Old Bridge Area of the Old City of Mostar — UNESCO World Heritage Centre', license: null },
    ],
    tier: 'canon',
  },
  {
    id: 'budapest-museum-of-applied-arts',
    wikidataId: 'Q1088467',
    name: {
      en: 'Museum of Applied Arts, Budapest',
      es: 'Museo de Artes Aplicadas de Budapest',
      it: 'Museo delle Arti Applicate di Budapest',
    },
    architectId: 'odon-lechner',
    location: { city: 'Budapest', countryCode: 'HU', lat: 47.48611, lon: 19.06833 },
    inception: 1893,
    completed: 1896,
    demolished: null,
    typology: 'cultural',
    materials: ['brick', 'steel-and-glass'],
    structure: {
      en: 'A load-bearing brick block faced in Zsolnay pyrogranite, wrapped around a top-lit central hall whose glazed vault is carried on an iron frame.',
      es: 'Un bloque de fábrica de ladrillo revestido de pirogranito de Zsolnay, dispuesto alrededor de un salón central cenital cuya bóveda acristalada descansa sobre una estructura de hierro.',
      it: 'Un blocco in muratura di mattoni rivestito di pirogranito Zsolnay, disposto attorno a una sala centrale con luce zenitale la cui volta vetrata poggia su un\'ossatura in ferro.',
    },
    program: {
      en: 'Built for the museum founded by the Hungarian parliament in 1872, and shared from 1896 with the Royal School of Applied Arts.',
      es: 'Construido para el museo fundado por el parlamento húngaro en 1872, y compartido desde 1896 con la Escuela Real de Artes Aplicadas.',
      it: 'Costruito per il museo fondato dal parlamento ungherese nel 1872, e condiviso dal 1896 con la Regia Scuola di Arti Applicate.',
    },
    heritage: 'national',
    currentUse: {
      en: 'Still the Museum of Applied Arts; the building has been closed to visitors for a reconstruction set in motion by a design competition held in 2012.',
      es: 'Sigue siendo el Museo de Artes Aplicadas; el edificio permanece cerrado al público por una reconstrucción iniciada a raíz de un concurso de proyectos convocado en 2012.',
      it: 'È tuttora il Museo delle Arti Applicate; l\'edificio è chiuso al pubblico per una ricostruzione avviata a seguito di un concorso di progettazione bandito nel 2012.',
    },
    detailRect: { x: 0.45, y: 0.18, w: 0.32, h: 0.30 },
    image: {
      commonsFile: 'File:Museum of Applied Arts. Main facade from south. BudapestDSCN3639.jpg',
      photographer: 'Yoav Dothan',
      license: 'PD',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Museum_of_Applied_Arts._Main_facade_from_south._BudapestDSCN3639.jpg',
      width: 0,
      height: 0,
    },
    dossier: {
      en: 'The third applied-arts museum in the world after London and Vienna, and the building in which Lechner first got his argument fully built. He and Gyula Pártos won the commission and worked from 1893 to 1896, finishing in time for the millennial celebrations of the Magyar conquest. The exterior is a brick box carrying an unbroken sheet of Zsolnay pyrogranite: a frost-proof glazed stoneware developed at Pécs, which let Lechner run green and gold across the roof and pull the dome up into a bulb of gilded ceramic. The ornament is not Hungarian folk art transcribed but a synthesis he assembled from embroidery motifs and from Indian and Persian sources, following a then-current belief that Magyar pattern shared an eastern ancestry. Inside, the sequence reverses: a white, top-lit central hall with pointed arcades and an iron-framed glass vault, closer to a Victorian exhibition shed than to anything on the facade.',
      es: 'El tercer museo de artes aplicadas del mundo después de los de Londres y Viena, y el edificio en que Lechner construyó por fin su tesis completa. Él y Gyula Pártos ganaron el encargo y trabajaron de 1893 a 1896, a tiempo para las celebraciones del milenario de la conquista magiar. El exterior es una caja de ladrillo cubierta por un manto continuo de pirogranito de Zsolnay, gres vidriado resistente a la helada desarrollado en Pécs, que permitió a Lechner extender verde y oro por la cubierta y rematar la cúpula en un bulbo de cerámica dorada. El ornamento no es arte popular húngaro transcrito, sino una síntesis que reunió a partir de motivos de bordado y de fuentes indias y persas, siguiendo la creencia entonces vigente de un tronco oriental común. Dentro, la secuencia se invierte: un salón blanco y cenital de arcadas apuntadas y bóveda de vidrio sobre armazón de hierro.',
      it: 'Il terzo museo di arti applicate al mondo dopo Londra e Vienna, e l\'edificio in cui Lechner riuscì finalmente a costruire per intero la propria tesi. Insieme a Gyula Pártos vinse l\'incarico e lavorò dal 1893 al 1896, in tempo per le celebrazioni del millenario della conquista magiara. L\'esterno è una scatola di mattoni ricoperta da un manto continuo di pirogranito Zsolnay, grès invetriato resistente al gelo messo a punto a Pécs, che permise a Lechner di stendere verde e oro sul tetto e di concludere la cupola in un bulbo di ceramica dorata. L\'ornato non è arte popolare ungherese trascritta, ma una sintesi raccolta da motivi di ricamo e da fonti indiane e persiane, secondo la convinzione allora corrente di un ceppo orientale comune. Dentro la sequenza si rovescia: una sala bianca a luce zenitale, con arcate acute e volta di vetro su ossatura di ferro.',
    },
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q1088467', title: 'Museum of Applied Arts (Q1088467)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Museum_of_Applied_Arts_(Budapest)', title: 'Museum of Applied Arts (Budapest)', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/%C3%96d%C3%B6n_Lechner', title: 'Ödön Lechner', license: 'CC BY-SA 4.0' },
    ],
    tier: 'canon',
  },
  {
    id: 'prague-church-of-the-most-sacred-heart',
    wikidataId: 'Q1164329',
    name: {
      en: 'Church of the Most Sacred Heart of Our Lord, Prague',
      es: 'Iglesia del Sagrado Corazón de Nuestro Señor, Praga',
      it: 'Chiesa del Sacratissimo Cuore di Nostro Signore, Praga',
    },
    architectId: 'joze-plecnik',
    location: { city: 'Prague', countryCode: 'CZ', lat: 50.078035, lon: 14.4507539 },
    inception: 1929,
    completed: 1932,
    demolished: null,
    typology: 'sacral',
    materials: ['brick', 'stone'],
    structure: {
      en: 'A single undivided hall roofed in one span, its walls built as a dark brick skin studded with projecting grey stone blocks and closed at the east by a flat 42-metre tower pierced by a glazed clock.',
      es: 'Una sala única sin dividir cubierta de un solo vano, con muros levantados como una piel de ladrillo oscuro tachonada de bloques salientes de piedra gris y cerrada al este por una torre plana de 42 metros perforada por un reloj acristalado.',
      it: 'Un\'unica sala indivisa coperta con una sola campata, con murature costruite come una pelle di mattoni scuri tempestata di blocchi sporgenti di pietra grigia e chiusa a est da una torre piatta di 42 metri traforata da un orologio vetrato.',
    },
    program: {
      en: 'A parish church for the growing Vinohrady district, commissioned by the Catholic Church as one of two new Prague churches marking the millennium of the death of St Wenceslas.',
      es: 'Iglesia parroquial para el creciente barrio de Vinohrady, encargada por la Iglesia católica como una de las dos nuevas iglesias de Praga con motivo del milenario de la muerte de san Wenceslao.',
      it: 'Chiesa parrocchiale per il crescente quartiere di Vinohrady, commissionata dalla Chiesa cattolica come una delle due nuove chiese praghesi per il millenario della morte di san Venceslao.',
    },
    heritage: 'national',
    currentUse: {
      en: 'Active Roman Catholic parish church, listed as a Czech national cultural monument since 2010.',
      es: 'Iglesia parroquial católica en uso, declarada monumento cultural nacional checo desde 2010.',
      it: 'Chiesa parrocchiale cattolica in uso, dichiarata monumento culturale nazionale ceco dal 2010.',
    },
    detailRect: { x: 0.30, y: 0.36, w: 0.30, h: 0.30 },
    image: {
      commonsFile: 'File:Praha kostel NSP bok 1.jpg',
      photographer: 'VitVit',
      license: 'CC BY-SA 4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Praha_kostel_NSP_bok_1.jpg',
      width: 0,
      height: 0,
    },
    dossier: {
      en: 'Plečnik had been working at Prague Castle for a decade when the archdiocese asked him for a parish church on the new square at Jiřího z Poděbrad. He gave Vinohrady something that reads at a distance as a Roman basilica and up close as nothing of the kind. The long walls are faced in dark brown brick into which grey stone blocks are set proud of the surface at regular intervals, a chequer he is said to have thought of as ermine, so that the whole building resembles a robe rather than a masonry box. Above it runs a broad white cornice like an entablature that has slipped its columns. The east end is a single flat tower forty-two metres high, split by a glazed clock 7.6 metres across — still the largest in the country — with a ramped stair climbing through the wall behind it. Inside there is one undivided hall, a coffered timber ceiling and a white marble altar carrying six patrons of Bohemia.',
      es: 'Plečnik llevaba una década trabajando en el Castillo de Praga cuando el arzobispado le pidió una parroquia en la nueva plaza de Jiřího z Poděbrad. Dio a Vinohrady algo que de lejos se lee como una basílica romana y de cerca como nada semejante. Los muros largos se revisten de ladrillo pardo oscuro en el que se incrustan, sobresaliendo a intervalos regulares, bloques de piedra gris: un damero que él habría concebido como armiño, de modo que el edificio entero recuerda más a un manto que a una caja de fábrica. Encima corre una ancha cornisa blanca, como un entablamento al que se le hubieran escapado las columnas. El testero oriental es una única torre plana de cuarenta y dos metros, partida por un reloj acristalado de 7,6 metros de diámetro —aún el mayor del país— con una escalera en rampa que asciende por el muro. Dentro, una sola sala, techo de casetones de madera y altar de mármol blanco.',
      it: 'Plečnik lavorava da un decennio al Castello di Praga quando l\'arcidiocesi gli chiese una parrocchiale sulla nuova piazza di Jiřího z Poděbrad. Diede a Vinohrady qualcosa che da lontano si legge come una basilica romana e da vicino come nulla del genere. Le pareti lunghe sono rivestite di mattoni bruno scuro in cui blocchi di pietra grigia sono incastonati sporgenti a intervalli regolari: una scacchiera che egli avrebbe pensato come ermellino, così che l\'intero edificio somiglia a un manto più che a una scatola muraria. Sopra corre un\'ampia cornice bianca, come una trabeazione sfuggita alle proprie colonne. Il fronte orientale è un\'unica torre piatta di quarantadue metri, spaccata da un orologio vetrato di 7,6 metri di diametro — tuttora il maggiore del paese — con una scala in rampa che sale dentro il muro. All\'interno una sola sala, soffitto ligneo a cassettoni e altare in marmo bianco.',
    },
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q1164329', title: 'Church of the Most Sacred Heart of Our Lord (Q1164329)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Church_of_the_Most_Sacred_Heart_of_Our_Lord', title: 'Church of the Most Sacred Heart of Our Lord', license: 'CC BY-SA 4.0' },
    ],
    tier: 'canon',
  },
  {
    id: 'melnikov-house-moscow',
    wikidataId: 'Q4165336',
    name: {
      en: 'Melnikov House, Moscow',
      es: 'Casa Mélnikov, Moscú',
      it: 'Casa Mel\'nikov, Mosca',
    },
    architectId: 'konstantin-melnikov',
    location: { city: 'Moscow', countryCode: 'RU', lat: 55.74806, lon: 37.58944 },
    inception: 1927,
    completed: 1929,
    demolished: null,
    typology: 'domestic',
    materials: ['brick'],
    structure: {
      en: 'Two interlocking brick cylinders under stuccoed render, the walls laid as a diagonal lattice whose gaps were either glazed as hexagonal windows or filled with rubble, so that no internal frame or beam is needed.',
      es: 'Dos cilindros de ladrillo entrelazados bajo revoco, con muros aparejados en retícula diagonal cuyos huecos se acristalaron como ventanas hexagonales o se rellenaron de cascote, de modo que no se precisa armazón ni viga interior.',
      it: 'Due cilindri di mattoni compenetrati sotto intonaco, con murature apparecchiate a reticolo diagonale i cui vuoti furono vetrati come finestre esagonali oppure riempiti di pietrame, così che non serve alcuna ossatura o trave interna.',
    },
    program: {
      en: 'Built by Melnikov as a house and studio for himself, his wife and their two children, on a private plot granted by the Moscow soviet.',
      es: 'Construida por Mélnikov como vivienda y taller para sí mismo, su mujer y sus dos hijos, en una parcela privada concedida por el sóviet de Moscú.',
      it: 'Costruita da Mel\'nikov come casa e studio per sé, la moglie e i due figli, su un lotto privato concesso dal soviet di Mosca.',
    },
    heritage: 'national',
    currentUse: {
      en: 'The Melnikov Museum, a branch of the Shchusev State Museum of Architecture since 2014; the interiors have been closed for restoration since 2022 while the garden and exterior remain accessible.',
      es: 'Museo Mélnikov, filial del Museo Estatal de Arquitectura Shchúsev desde 2014; los interiores están cerrados por restauración desde 2022, aunque el jardín y el exterior siguen accesibles.',
      it: 'Museo Mel\'nikov, sezione del Museo statale di architettura Ščusev dal 2014; gli interni sono chiusi per restauro dal 2022, mentre il giardino e l\'esterno restano accessibili.',
    },
    detailRect: { x: 0.14, y: 0.52, w: 0.32, h: 0.30 },
    image: {
      commonsFile: 'File:Melnikov House, May 2021.jpg',
      photographer: 'Paulkuz',
      license: 'CC BY-SA 4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Melnikov_House%2C_May_2021.jpg',
      width: 0,
      height: 0,
    },
    dossier: {
      en: 'A one-family house in the middle of Moscow, built in the years when private building had all but stopped, and the only such commission Melnikov ever had — from himself. He set two brick cylinders overlapping by about a third of their diameter, so the plan is a figure of eight and every room is a segment of a circle. The walls carry themselves: bricks laid in a diagonal net leave two hundred hexagonal openings, of which sixty were glazed and the rest packed with rubble and rendered over, allowing windows to be added or closed without touching the structure. The front cylinder is cut open by a two-storey sheet of glazing carrying his name and the word ARCHITECT; the rear one is pierced by rows of hexagons and lights a studio with no shadowed corner. He finished it before he was forty. Nothing else of his was built after 1936, and he lived in the house until his death in 1974.',
      es: 'Una casa unifamiliar en pleno Moscú, levantada en los años en que la construcción privada prácticamente había cesado, y el único encargo de ese tipo que Mélnikov tuvo jamás: el suyo propio. Superpuso dos cilindros de ladrillo solapados en cerca de un tercio de su diámetro, de modo que la planta es un ocho y toda habitación es un segmento de círculo. Los muros se sostienen solos: el ladrillo aparejado en red diagonal deja doscientos huecos hexagonales, sesenta de ellos acristalados y el resto rellenos de cascote y revocados, lo que permite abrir o cerrar ventanas sin tocar la estructura. El cilindro delantero lo abre un paño acristalado de dos alturas con su nombre y la palabra ARQUITECTO; el trasero, perforado por hileras de hexágonos, ilumina un taller sin un solo rincón en sombra. Vivió en ella hasta su muerte en 1974.',
      it: 'Una casa unifamiliare nel pieno di Mosca, costruita negli anni in cui l\'edilizia privata era quasi cessata, e l\'unico incarico del genere che Mel\'nikov abbia mai avuto: il proprio. Sovrappose due cilindri di mattoni intersecati per circa un terzo del diametro, così che la pianta è un otto e ogni stanza è un segmento di cerchio. Le murature si reggono da sole: i mattoni disposti a rete diagonale lasciano duecento aperture esagonali, sessanta delle quali vetrate e le altre riempite di pietrame e intonacate, il che permette di aprire o chiudere finestre senza toccare la struttura. Il cilindro anteriore è squarciato da una vetrata su due piani che porta il suo nome e la parola ARCHITETTO; quello posteriore, traforato da file di esagoni, illumina uno studio senza un solo angolo in ombra. Vi abitò fino alla morte, nel 1974.',
    },
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q4165336', title: 'Melnikov House (Q4165336)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Melnikov_House', title: 'Melnikov House', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Konstantin_Melnikov', title: 'Konstantin Melnikov', license: 'CC BY-SA 4.0' },
    ],
    tier: 'canon',
  },
  {
    id: 'jested-tower-liberec',
    wikidataId: 'Q1129608',
    name: {
      en: 'Ještěd Tower and Hotel',
      es: 'Torre y hotel de Ještěd',
      it: 'Torre e albergo dello Ještěd',
    },
    architectId: 'karel-hubacek',
    location: { city: 'Liberec', countryCode: 'CZ', lat: 50.732628, lon: 14.984592 },
    inception: 1966,
    completed: 1973,
    demolished: null,
    typology: 'tower',
    materials: ['concrete', 'steel-and-glass'],
    structure: {
      en: 'A 94-metre reinforced concrete shell in the form of a rotation hyperboloid, whose curve carries the transmitter mast, resists the summit winds and continues the profile of the mountain in one figure.',
      es: 'Una lámina de hormigón armado de 94 metros con forma de hiperboloide de revolución, cuya curva sostiene el mástil emisor, resiste los vientos de la cumbre y prolonga el perfil de la montaña en una sola figura.',
      it: 'Un guscio in cemento armato di 94 metri a forma di iperboloide di rotazione, la cui curva sorregge l\'albero del trasmettitore, resiste ai venti della vetta e prolunga il profilo della montagna in un\'unica figura.',
    },
    program: {
      en: 'Commissioned jointly by the Liberec restaurant enterprise and the Prague radio communications administration to combine a mountain hotel and restaurant with a television transmitter.',
      es: 'Encargada conjuntamente por la empresa de restauración de Liberec y la administración de radiocomunicaciones de Praga para reunir un hotel de montaña con restaurante y un emisor de televisión.',
      it: 'Commissionata congiuntamente dall\'impresa di ristorazione di Liberec e dall\'amministrazione praghese delle radiocomunicazioni per unire un albergo di montagna con ristorante e un trasmettitore televisivo.',
    },
    heritage: 'national',
    currentUse: {
      en: 'Working television transmitter, hotel and restaurant; a Czech national cultural monument since 2006 and on the country\'s UNESCO tentative list since 2007.',
      es: 'Emisor de televisión en servicio, hotel y restaurante; monumento cultural nacional checo desde 2006 y en la lista indicativa de la UNESCO desde 2007.',
      it: 'Trasmettitore televisivo in funzione, albergo e ristorante; monumento culturale nazionale ceco dal 2006 e nella lista propositiva UNESCO dal 2007.',
    },
    detailRect: { x: 0.32, y: 0.58, w: 0.34, h: 0.26 },
    image: {
      commonsFile: 'File:2022-12-15-Jested-Tower-01.jpg',
      photographer: 'Gunnar Klack',
      license: 'CC BY-SA 4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:2022-12-15-Jested-Tower-01.jpg',
      width: 0,
      height: 0,
    },
    dossier: {
      en: 'The wooden lodge on the summit of Ještěd burned down in January 1963, and the competition held a month later asked for a replacement that would also carry a television transmitter. Eleven entries came in; Hubáček\'s won because it refused to treat the two programmes as separate buildings. He proposed a single hyperboloid of revolution whose curve begins where the mountain profile ends, so that from Liberec the hill appears simply to continue upward into a mast. The same geometry solves the engineering: the shell sheds the summit wind, and a pendulum damper inside the shaft absorbs the sway. The hotel and restaurant occupy the flared base behind a continuous band of glazing; above them the cone tapers into the transmitter. Design took three years, construction seven, and it opened in July 1973. Hubáček had already received the International Union of Architects\' Auguste Perret Prize for it in 1969, four years before anyone could stand inside.',
      es: 'El refugio de madera de la cumbre del Ještěd ardió en enero de 1963, y el concurso convocado un mes después pedía un sustituto que albergara además un emisor de televisión. Se presentaron once propuestas; ganó la de Hubáček porque se negó a tratar los dos programas como edificios distintos. Propuso un único hiperboloide de revolución cuya curva arranca donde termina el perfil de la montaña, de modo que desde Liberec el cerro parece continuar sin más hacia arriba hasta convertirse en mástil. La misma geometría resuelve la ingeniería: la lámina desvía el viento de cumbre y un amortiguador de péndulo alojado en el fuste absorbe la oscilación. El hotel y el restaurante ocupan la base acampanada tras una banda continua de vidrio. El proyecto llevó tres años y la obra siete; abrió en julio de 1973. La Unión Internacional de Arquitectos ya le había dado el Premio Auguste Perret en 1969.',
      it: 'Il rifugio di legno sulla vetta dello Ještěd bruciò nel gennaio 1963, e il concorso bandito un mese dopo chiedeva un sostituto che ospitasse anche un trasmettitore televisivo. Arrivarono undici proposte; vinse quella di Hubáček perché rifiutava di trattare i due programmi come edifici distinti. Propose un unico iperboloide di rotazione la cui curva inizia dove finisce il profilo della montagna, così che da Liberec il colle sembra semplicemente proseguire verso l\'alto fino a farsi albero d\'antenna. La stessa geometria risolve l\'ingegneria: il guscio devia il vento di vetta e uno smorzatore a pendolo alloggiato nel fusto assorbe l\'oscillazione. Albergo e ristorante occupano la base svasata dietro una fascia continua di vetro. Il progetto richiese tre anni, il cantiere sette; aprì nel luglio 1973. L\'Unione Internazionale degli Architetti gli aveva già assegnato il Premio Auguste Perret nel 1969.',
    },
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q1129608', title: 'Ještěd Tower (Q1129608)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Je%C5%A1t%C4%9Bd_Tower', title: 'Ještěd Tower', license: 'CC BY-SA 4.0' },
    ],
    tier: 'canon',
  },
  {
    id: 'museum-of-contemporary-art-belgrade',
    wikidataId: 'Q1290510',
    name: {
      en: 'Museum of Contemporary Art, Belgrade',
      es: 'Museo de Arte Contemporáneo de Belgrado',
      it: 'Museo d\'arte contemporanea di Belgrado',
    },
    architectId: 'ivanka-raspopovic',
    location: { city: 'Belgrade', countryCode: 'RS', lat: 44.819444, lon: 20.442222 },
    inception: 1960,
    completed: 1965,
    demolished: null,
    typology: 'cultural',
    materials: ['concrete', 'stone'],
    structure: {
      en: 'A reinforced concrete frame divided into six square bays, each closed above by a faceted crystal of white marble panels whose four sloping faces meet a glazed roof lantern.',
      es: 'Una estructura de hormigón armado dividida en seis módulos cuadrados, cada uno cerrado en lo alto por un cristal facetado de placas de mármol blanco cuyas cuatro caras inclinadas se encuentran en un lucernario acristalado.',
      it: 'Un telaio in cemento armato diviso in sei campate quadrate, ciascuna chiusa in alto da un cristallo sfaccettato di lastre di marmo bianco le cui quattro falde inclinate si incontrano in un lucernario vetrato.',
    },
    program: {
      en: 'Built for the Belgrade Modern Gallery, founded in 1958, as the first purpose-designed museum of twentieth-century Yugoslav art.',
      es: 'Construido para la Galería Moderna de Belgrado, fundada en 1958, como primer museo concebido específicamente para el arte yugoslavo del siglo XX.',
      it: 'Costruito per la Galleria Moderna di Belgrado, fondata nel 1958, come primo museo concepito appositamente per l\'arte jugoslava del Novecento.',
    },
    heritage: 'national',
    currentUse: {
      en: 'Museum of Contemporary Art, reopened in October 2017 after a ten-year reconstruction; a protected cultural monument of Serbia.',
      es: 'Museo de Arte Contemporáneo, reabierto en octubre de 2017 tras diez años de reconstrucción; monumento cultural protegido de Serbia.',
      it: 'Museo d\'arte contemporanea, riaperto nell\'ottobre 2017 dopo dieci anni di ricostruzione; monumento culturale protetto della Serbia.',
    },
    detailRect: { x: 0.18, y: 0.12, w: 0.30, h: 0.32 },
    image: {
      commonsFile: 'File:Beograd - Muzej Savremene Umetnosti (MoCAB) (crop).jpg',
      photographer: 'Fred Romero',
      license: 'CC BY 4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Beograd_-_Muzej_Savremene_Umetnosti_(MoCAB)_(crop).jpg',
      width: 0,
      height: 0,
    },
    dossier: {
      en: 'Ivanka Raspopović and Ivan Antić were both working on factories and infrastructure when they took the museum commission in 1960, and the building keeps the discipline of that work. It stands in Ušće park near the meeting of the Sava and the Danube, on the flat ground of New Belgrade, and consists of six square cells arranged so that the galleries spiral upward around a central hall in half-level steps, giving a single continuous route with no dead ends. Each cell is capped by a faceted marble crystal whose four sloping faces run up to a glass lantern, so that all the daylight in the museum arrives from above. Belgrade nicknamed it the crystal at the confluence. The city gave the two architects its October Prize on 20 October 1965, the same day the doors opened. Raspopović was still advising on the reconstruction that closed the building from 2007 to 2017; she died two years before it reopened.',
      es: 'Ivanka Raspopović e Ivan Antić trabajaban ambos en fábricas e infraestructuras cuando aceptaron el encargo del museo en 1960, y el edificio conserva la disciplina de aquel oficio. Se alza en el parque de Ušće, cerca de la confluencia del Sava y el Danubio, sobre el llano de Nuevo Belgrado, y se compone de seis células cuadradas dispuestas de modo que las salas ascienden en espiral en torno a un vestíbulo central por medios niveles, con un recorrido continuo y sin fondos de saco. Cada célula se corona con un cristal facetado de mármol cuyas cuatro caras inclinadas suben hasta un lucernario, de manera que toda la luz natural del museo llega desde arriba. Belgrado lo apodó el cristal de la confluencia. La ciudad concedió a los dos arquitectos su Premio de Octubre el 20 de octubre de 1965, el mismo día de la apertura.',
      it: 'Ivanka Raspopović e Ivan Antić lavoravano entrambi su fabbriche e infrastrutture quando nel 1960 accettarono l\'incarico del museo, e l\'edificio conserva la disciplina di quel mestiere. Sorge nel parco di Ušće, presso la confluenza fra la Sava e il Danubio, sulla piana di Nuova Belgrado, ed è composto da sei celle quadrate disposte in modo che le sale salgano a spirale attorno a un atrio centrale per mezzi livelli, con un percorso continuo e senza vicoli ciechi. Ogni cella è coronata da un cristallo sfaccettato di marmo le cui quattro falde salgono fino a un lucernario, cosicché tutta la luce naturale del museo giunge dall\'alto. Belgrado lo soprannominò il cristallo alla confluenza. La città assegnò ai due architetti il Premio di Ottobre il 20 ottobre 1965, lo stesso giorno dell\'apertura.',
    },
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q1290510', title: 'Museum of Contemporary Art, Belgrade (Q1290510)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Museum_of_Contemporary_Art,_Belgrade', title: 'Museum of Contemporary Art, Belgrade', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Ivanka_Raspopovi%C4%87', title: 'Ivanka Raspopović', license: 'CC BY-SA 4.0' },
    ],
    tier: 'canon',
  },
  {
    id: 'manhattan-estate-wroclaw',
    wikidataId: 'Q9390467',
    name: {
      en: 'Manhattan Estate (Sedesowce), Wrocław',
      es: 'Conjunto Manhattan (Sedesowce), Breslavia',
      it: 'Complesso Manhattan (Sedesowce), Breslavia',
    },
    architectId: 'jadwiga-grabowska-hawrylak',
    location: { city: 'Wrocław', countryCode: 'PL', lat: 51.1103, lon: 17.054 },
    inception: 1970,
    completed: 1978,
    demolished: null,
    typology: 'housing',
    materials: ['concrete'],
    structure: {
      en: 'Six sixteen-storey reinforced concrete towers, each 55 metres high, standing with their commercial pavilions on a raised concrete deck carried by some 240 piles, with prefabricated rounded loggia frames hung across the facades.',
      es: 'Seis torres de hormigón armado de dieciséis plantas y 55 metros de altura que, junto a sus pabellones comerciales, se levantan sobre una plataforma de hormigón sostenida por unos 240 pilotes, con marcos prefabricados de logia redondeados colgados en las fachadas.',
      it: 'Sei torri in cemento armato di sedici piani e 55 metri di altezza che, insieme ai loro padiglioni commerciali, poggiano su una piattaforma in calcestruzzo retta da circa 240 pali, con telai prefabbricati di loggia arrotondati appesi lungo le facciate.',
    },
    program: {
      en: 'A mixed residential and commercial development on Grunwaldzki Square, begun for the city and completed by a housing cooperative.',
      es: 'Un conjunto mixto de vivienda y comercio en la plaza Grunwaldzki, iniciado por el ayuntamiento y terminado por una cooperativa de vivienda.',
      it: 'Un complesso misto residenziale e commerciale in piazza Grunwaldzki, avviato dal comune e completato da una cooperativa edilizia.',
    },
    heritage: null,
    currentUse: {
      en: 'Occupied flats and ground-floor shops; the concrete facades were repaired and painted white in a 2015 renovation.',
      es: 'Viviendas ocupadas y comercios en planta baja; las fachadas de hormigón se repararon y pintaron de blanco en una rehabilitación de 2015.',
      it: 'Alloggi occupati e negozi al piano terra; le facciate in calcestruzzo furono riparate e dipinte di bianco in un intervento del 2015.',
    },
    detailRect: { x: 0.54, y: 0.12, w: 0.32, h: 0.30 },
    image: {
      commonsFile: 'File:Wrocław - Zespół mieszkalno-usługowy przy pl. Grunwaldzkim (3).jpg',
      photographer: 'Fred Romero',
      license: 'CC BY 2.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Wroc%C5%82aw_-_Zesp%C3%B3%C5%82_mieszkalno-us%C5%82ugowy_przy_pl._Grunwaldzkim_(3).jpg',
      width: 0,
      height: 0,
    },
    dossier: {
      en: 'Grabowska-Hawrylak drew this between 1967 and 1970 as an attempt to import a warmer climate into a rebuilt German city: white towers, balconies framed by rounded concrete openings, climbing plants spilling from them, grass roofs on the shops below and communal roof terraces with washrooms on top of every block, meant to make up for the absence of any real recreation ground. Then the project was handed from the city to a housing cooperative, costs were cut, and it was built in grey concrete with the formwork marks left showing, the stair halls stripped of their windows to squeeze in more small rooms, and the plants never planted. Wrocław named it the Bunkers and the Toilet Bowls, after the shape of the loggia frames, and it entered the literature as brutalism by accident. The roof terraces survived the cuts. A 2015 renovation finally painted the towers the white she had specified forty-five years earlier.',
      es: 'Grabowska-Hawrylak lo dibujó entre 1967 y 1970 como un intento de importar un clima más benigno a una ciudad alemana reconstruida: torres blancas, balcones enmarcados por huecos redondeados de hormigón, plantas trepadoras desbordándolos, cubiertas de césped sobre los comercios y terrazas comunitarias con aseos encima de cada bloque, pensadas para suplir la falta de cualquier zona de recreo. Después el proyecto pasó del ayuntamiento a una cooperativa, se recortaron costes y se construyó en hormigón gris con las marcas del encofrado a la vista, las cajas de escalera despojadas de ventanas para encajar más habitaciones pequeñas y las plantas nunca plantadas. Breslavia lo llamó los Búnkeres y los Sedesowce —los inodoros—, por la forma de los marcos, y entró en la bibliografía como brutalismo por accidente. Una rehabilitación de 2015 pintó por fin las torres del blanco previsto cuarenta y cinco años antes.',
      it: 'Grabowska-Hawrylak lo disegnò fra il 1967 e il 1970 come un tentativo di importare un clima più mite in una città tedesca ricostruita: torri bianche, balconi incorniciati da aperture arrotondate in calcestruzzo, rampicanti che ne debordano, tetti erbosi sui negozi e terrazze comuni con servizi igienici sulla sommità di ogni blocco, pensate per compensare l\'assenza di qualsiasi spazio di svago. Poi il progetto passò dal comune a una cooperativa, i costi furono tagliati e si costruì in calcestruzzo grigio con i segni del cassero a vista, i vani scala privati delle finestre per ricavare più stanze piccole e le piante mai messe a dimora. Breslavia lo chiamò i Bunker e i Sedesowce — le tazze del water — per la forma dei telai, ed entrò nella letteratura come brutalismo per caso. Un intervento del 2015 dipinse infine le torri del bianco previsto quarantacinque anni prima.',
    },
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q9390467', title: 'Manhattan estate, Wrocław (Q9390467)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Manhattan_Estate', title: 'Manhattan Estate', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Jadwiga_Grabowska-Hawrylak', title: 'Jadwiga Grabowska-Hawrylak', license: 'CC BY-SA 4.0' },
    ],
    tier: 'deep',
  },
  {
    id: 'sady-zoliborskie-estate-warsaw',
    wikidataId: 'Q107600895',
    name: {
      en: 'Sady Żoliborskie Housing Estate, Warsaw',
      es: 'Conjunto residencial Sady Żoliborskie, Varsovia',
      it: 'Quartiere residenziale Sady Żoliborskie, Varsavia',
    },
    architectId: 'halina-skibniewska',
    location: { city: 'Warsaw', countryCode: 'PL', lat: 52.266076, lon: 20.972486 },
    inception: 1959,
    completed: 1964,
    demolished: null,
    typology: 'housing',
    materials: ['brick', 'concrete'],
    structure: {
      en: 'Low four- and five-storey slabs on a reinforced concrete skeleton, with no load-bearing walls inside the flats, so that partitions could be rearranged by the occupants.',
      es: 'Bloques bajos de cuatro y cinco plantas sobre esqueleto de hormigón armado, sin muros de carga en el interior de las viviendas, de modo que los tabiques pudieran reordenarlos los propios vecinos.',
      it: 'Blocchi bassi di quattro e cinque piani su scheletro in cemento armato, privi di muri portanti all\'interno degli alloggi, così che i tramezzi potessero essere riorganizzati dagli abitanti.',
    },
    program: {
      en: 'Built for the Warsaw Housing Cooperative on the site of old orchards in Żoliborz, as twenty-four blocks grouped into three neighbourhood units.',
      es: 'Construido para la Cooperativa de Vivienda de Varsovia sobre antiguos huertos de Żoliborz, en veinticuatro bloques agrupados en tres unidades vecinales.',
      it: 'Costruito per la Cooperativa edilizia di Varsavia sul sedime di antichi frutteti a Żoliborz, in ventiquattro blocchi raggruppati in tre unità di vicinato.',
    },
    heritage: 'regional',
    currentUse: {
      en: 'Occupied housing, entered in the Warsaw municipal register of historic monuments; a public park was laid out on the remaining orchard land in 1992.',
      es: 'Viviendas ocupadas, inscritas en el registro municipal de monumentos de Varsovia; en 1992 se trazó un parque público en el terreno de huertos restante.',
      it: 'Alloggi occupati, iscritti nel registro comunale dei monumenti di Varsavia; nel 1992 fu realizzato un parco pubblico sull\'area dei frutteti residui.',
    },
    detailRect: { x: 0.18, y: 0.28, w: 0.28, h: 0.34 },
    image: {
      commonsFile: 'File:Sady Żoliborskie w Warszawie w latach 60.jpg',
      photographer: 'Zbyszko Siemaszko',
      license: 'PD',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Sady_%C5%BBoliborskie_w_Warszawie_w_latach_60.jpg',
      width: 0,
      height: 0,
    },
    dossier: {
      en: 'The site was an orchard, and Skibniewska\'s first decision was to keep as many of the fruit trees as the building programme would allow — a refusal of the clearance-and-grid method then standard in Polish estate planning. She grouped twenty-four low blocks into three neighbourhood units of seven or eight, each enclosing a planted courtyard, and set them so that no block stands in another\'s light. Behind the plain facades the flats sit on a concrete skeleton with no internal load-bearing walls, so tenants could move partitions; one eleven-storey block is topped by a terrace serving as an open clubroom, and its ground floor holds double-height glazed studios with gardens, built for artists. The first block, on Krasińskiego, was voted Mister Warszawy in 1961. Construction ran from 1959 to 1964. The later colonies of the same estate were built to standardised state catalogue types, and the difference between the two halves is still legible from the street.',
      es: 'El solar era un huerto, y la primera decisión de Skibniewska fue conservar cuantos frutales permitiera el programa: un rechazo del método de desmonte y retícula entonces habitual en el planeamiento polaco. Agrupó veinticuatro bloques bajos en tres unidades vecinales de siete u ocho, cada una en torno a un patio arbolado, y los dispuso de modo que ningún bloque quitara luz a otro. Tras las fachadas sobrias, las viviendas descansan en un esqueleto de hormigón sin muros de carga interiores, de manera que los vecinos podían mover los tabiques; un bloque de once plantas se remata con una terraza que sirve de sala común abierta, y en su planta baja hay estudios acristalados de doble altura con jardín, construidos para artistas. El primer bloque, en la calle Krasińskiego, fue elegido Mister Warszawy en 1961. Las obras duraron de 1959 a 1964.',
      it: 'Il lotto era un frutteto, e la prima decisione di Skibniewska fu conservare quanti più alberi il programma consentisse: un rifiuto del metodo di sbancamento e griglia allora corrente nella pianificazione polacca. Raggruppò ventiquattro blocchi bassi in tre unità di vicinato di sette o otto, ciascuna attorno a una corte alberata, e li dispose in modo che nessun blocco togliesse luce a un altro. Dietro le facciate sobrie gli alloggi poggiano su uno scheletro in calcestruzzo privo di muri portanti interni, così che gli inquilini potessero spostare i tramezzi; un blocco di undici piani è coronato da una terrazza che funge da sala comune aperta, e al piano terra ospita atelier vetrati a doppia altezza con giardino, costruiti per artisti. Il primo blocco, in via Krasińskiego, fu votato Mister Warszawy nel 1961. I lavori durarono dal 1959 al 1964.',
    },
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q107600895', title: 'osiedle Sady Żoliborskie I (Q107600895)', license: null },
      { kind: 'wikipedia', url: 'https://pl.wikipedia.org/wiki/Sady_%C5%BBoliborskie', title: 'Sady Żoliborskie (Polish Wikipedia)', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Halina_Skibniewska', title: 'Halina Skibniewska', license: 'CC BY-SA 4.0' },
    ],
    tier: 'deep',
  },
  {
    id: 'skopje-telecommunications-centre',
    wikidataId: 'Q65296431',
    name: {
      en: 'Telecommunications Centre, Skopje',
      es: 'Centro de Telecomunicaciones de Skopie',
      it: 'Centro delle telecomunicazioni di Skopje',
    },
    architectId: 'janko-konstantinov',
    location: { city: 'Skopje', countryCode: 'MK', lat: 41.9975483, lon: 21.4299167 },
    inception: 1968,
    completed: 1981,
    demolished: null,
    typology: 'infrastructure',
    materials: ['concrete'],
    structure: {
      en: 'Board-marked and ribbed reinforced concrete throughout: cylindrical service and stair drums, circular window openings punched straight through the wall, and curved cantilevered fins carrying the roofs of the halls below.',
      es: 'Hormigón armado encofrado y acanalado en su totalidad: tambores cilíndricos de servicio y escaleras, huecos circulares horadados directamente en el muro y aletas curvas en voladizo que sostienen las cubiertas de las salas inferiores.',
      it: 'Cemento armato a casseratura e scanalato ovunque: tamburi cilindrici di servizio e di scala, aperture circolari forate direttamente nel muro e alette curve a sbalzo che reggono le coperture delle sale sottostanti.',
    },
    program: {
      en: 'Built for the Macedonian postal and telecommunications administration as part of the reconstruction of central Skopje after the 1963 earthquake, in the same complex as the main post office.',
      es: 'Construido para la administración macedonia de correos y telecomunicaciones dentro de la reconstrucción del centro de Skopie tras el terremoto de 1963, en el mismo complejo que la oficina central de correos.',
      it: 'Costruito per l\'amministrazione macedone delle poste e telecomunicazioni nell\'ambito della ricostruzione del centro di Skopje dopo il terremoto del 1963, nello stesso complesso dell\'ufficio postale centrale.',
    },
    heritage: null,
    currentUse: {
      en: 'Still in telecommunications and postal use; the adjoining post office counter hall has stood damaged since a fire destroyed its roof in 2013.',
      es: 'Sigue en uso postal y de telecomunicaciones; la sala de ventanillas de correos contigua permanece dañada desde que un incendio destruyó su cubierta en 2013.',
      it: 'Tuttora in uso postale e per le telecomunicazioni; l\'attigua sala sportelli delle poste resta danneggiata da quando un incendio ne distrusse il tetto nel 2013.',
    },
    detailRect: { x: 0.40, y: 0.46, w: 0.30, h: 0.30 },
    image: {
      commonsFile: 'File:Pošta vo Skopje, Macedonia.jpg',
      photographer: 'yeowatzup',
      license: 'CC BY 2.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Po%C5%A1ta_vo_Skopje%2C_Macedonia.jpg',
      width: 0,
      height: 0,
    },
    dossier: {
      en: 'The earthquake of 26 July 1963 destroyed most of central Skopje, and the reconstruction that followed was run as an international project, with a United Nations competition, a masterplan by Kenzō Tange and buildings by architects drawn back from abroad. Konstantinov was one of them: he had spent the previous decade in Copenhagen, in Finland with Alvar Aalto, and in Victor Gruen\'s office in Los Angeles. What he built on the north bank of the Vardar over the following two decades is the most sculptural thing in the new city. Cylindrical drums of board-marked concrete carry vertical ribs like fluting; walls are punched with plain circles instead of windows; curved fins spread from the centre of the adjoining post office hall like petals. The complex went up in stages from the late 1960s to 1989. MoMA showed a model of the Telecommunications Centre in 2018 in its survey of Yugoslav architecture.',
      es: 'El terremoto del 26 de julio de 1963 destruyó casi todo el centro de Skopie, y la reconstrucción que siguió se gestionó como un proyecto internacional, con un concurso de Naciones Unidas, un plan maestro de Kenzō Tange y edificios de arquitectos repatriados. Konstantinov fue uno de ellos: había pasado la década anterior en Copenhague, en Finlandia con Alvar Aalto y en el estudio de Victor Gruen en Los Ángeles. Lo que levantó en la orilla norte del Vardar durante los veinte años siguientes es lo más escultórico de la ciudad nueva. Tambores cilíndricos de hormigón encofrado llevan nervios verticales como estrías; los muros se horadan con círculos limpios en lugar de ventanas; aletas curvas se abren desde el centro de la sala de correos contigua como pétalos. El conjunto se erigió por fases desde finales de los sesenta hasta 1989.',
      it: 'Il terremoto del 26 luglio 1963 distrusse quasi tutto il centro di Skopje, e la ricostruzione che seguì fu condotta come un progetto internazionale, con un concorso delle Nazioni Unite, un piano regolatore di Kenzō Tange ed edifici di architetti richiamati dall\'estero. Konstantinov fu uno di loro: aveva passato il decennio precedente a Copenaghen, in Finlandia con Alvar Aalto e nello studio di Victor Gruen a Los Angeles. Ciò che eresse sulla riva nord del Vardar nei vent\'anni successivi è la cosa più scultorea della città nuova. Tamburi cilindrici di calcestruzzo casserato portano costole verticali come scanalature; le murature sono forate da cerchi netti invece che da finestre; alette curve si aprono dal centro dell\'attigua sala postale come petali. Il complesso fu eretto per fasi dalla fine degli anni Sessanta al 1989.',
    },
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q65296431', title: 'Telecom building, Skopje (Q65296431)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Janko_Konstantinov', title: 'Janko Konstantinov', license: 'CC BY-SA 4.0' },
      { kind: 'institution', url: 'https://www.moma.org/collection/works/205691', title: 'Janko Konstantinov. Telecommunications Center, Skopje, Macedonia. 1968–1981 — MoMA', license: null },
    ],
    tier: 'canon',
  },
  {
    id: 'museum-of-contemporary-art-zagreb',
    wikidataId: 'Q3503103',
    name: {
      en: 'Museum of Contemporary Art, Zagreb',
      es: 'Museo de Arte Contemporáneo de Zagreb',
      it: 'Museo d\'arte contemporanea di Zagabria',
    },
    architectId: 'igor-franic',
    location: { city: 'Zagreb', countryCode: 'HR', lat: 45.7788131, lon: 15.9818579 },
    inception: 2003,
    completed: 2009,
    demolished: null,
    typology: 'cultural',
    materials: ['steel-and-glass', 'concrete'],
    structure: {
      en: 'A long horizontal box of glass and metal panels lifted clear of the ground on slender concrete columns, so that the whole ground plane passes beneath it as covered public space.',
      es: 'Una caja horizontal alargada de vidrio y paneles metálicos elevada del suelo sobre esbeltos pilares de hormigón, de modo que todo el plano del terreno discurre bajo ella como espacio público cubierto.',
      it: 'Una lunga scatola orizzontale di vetro e pannelli metallici sollevata da terra su esili pilastri in calcestruzzo, così che l\'intero piano di campagna passa sotto di essa come spazio pubblico coperto.',
    },
    program: {
      en: 'The first purpose-built home for a collection begun as the City Gallery of Contemporary Art in 1954 and until then housed in a palace in Zagreb\'s upper town.',
      es: 'La primera sede de nueva planta para una colección iniciada como Galería Municipal de Arte Contemporáneo en 1954 y alojada hasta entonces en un palacio de la ciudad alta de Zagreb.',
      it: 'La prima sede appositamente costruita per una collezione avviata come Galleria civica d\'arte contemporanea nel 1954 e fino ad allora ospitata in un palazzo della città alta di Zagabria.',
    },
    heritage: 'none',
    currentUse: {
      en: 'Croatia\'s national museum of contemporary art, with about 14,600 square metres of floor area, a library, a multimedia hall and a bookshop.',
      es: 'Museo nacional croata de arte contemporáneo, con unos 14.600 metros cuadrados construidos, biblioteca, sala multimedia y librería.',
      it: 'Museo nazionale croato d\'arte contemporanea, con circa 14.600 metri quadrati di superficie, biblioteca, sala multimediale e libreria.',
    },
    detailRect: { x: 0.16, y: 0.20, w: 0.30, h: 0.30 },
    image: {
      commonsFile: 'File:Msu-museum-contemporary-art-zagreb-2.jpg',
      photographer: 'Myriam Thyes',
      license: 'CC BY-SA 3.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Msu-museum-contemporary-art-zagreb-2.jpg',
      width: 0,
      height: 0,
    },
    dossier: {
      en: 'For fifty-five years Zagreb\'s contemporary collection had no permanent display, because the Kulmer Palace in the upper town could not hold one. In 1998 the city and the Ministry of Culture decided to build across the river in Novi Zagreb, on the corner of Dubrovnik and Većeslav Holjevac avenues, and Igor Franić won the competition against eighty-four other entries. The building he delivered is deliberately undramatic from outside: a long glazed and metal-clad volume held above the ground on thin columns, leaving the site open underneath so that the museum does not close off the block. The cornerstone went down in November 2003 and the museum opened on 11 December 2009 after six years of delays, at more than twice the budgeted cost. Of its 14,600 square metres, 3,500 are given to the permanent collection and about 1,500 to temporary exhibitions, the remainder taken up by a library, a multimedia hall, a bookshop and the circulation threading them together.',
      es: 'Durante cincuenta y cinco años la colección contemporánea de Zagreb careció de exposición permanente, porque el palacio Kulmer de la ciudad alta no podía albergarla. En 1998 el ayuntamiento y el Ministerio de Cultura decidieron construir al otro lado del río, en Novi Zagreb, en la esquina de las avenidas Dubrovnik y Većeslav Holjevac, e Igor Franić ganó el concurso frente a otras ochenta y cuatro propuestas. El edificio que entregó es deliberadamente poco espectacular desde fuera: un volumen alargado de vidrio y chapa sostenido sobre pilares delgados, que deja libre el suelo para que el museo no cierre la manzana. La primera piedra se puso en noviembre de 2003 y el museo abrió el 11 de diciembre de 2009, tras seis años de retrasos y con un coste que más que duplicó lo presupuestado. De sus 14.600 metros cuadrados, 3.500 se destinan a la colección permanente y unos 1.500 a exposiciones temporales; el resto lo ocupan una biblioteca, una sala multimedia, una librería y los recorridos que los enhebran.',
      it: 'Per cinquantacinque anni la collezione contemporanea di Zagabria non ebbe un\'esposizione permanente, perché il palazzo Kulmer nella città alta non poteva ospitarla. Nel 1998 il comune e il Ministero della Cultura decisero di costruire oltre il fiume, a Novi Zagreb, all\'angolo fra i viali Dubrovnik e Većeslav Holjevac, e Igor Franić vinse il concorso contro altre ottantaquattro proposte. L\'edificio che consegnò è volutamente poco spettacolare dall\'esterno: un volume allungato di vetro e lamiera sostenuto da pilastri sottili, che lascia libero il suolo perché il museo non chiuda l\'isolato. La prima pietra fu posata nel novembre 2003 e il museo aprì l\'11 dicembre 2009, dopo sei anni di ritardi e con un costo più che raddoppiato rispetto al preventivo. Dei suoi 14.600 metri quadrati, 3.500 sono destinati alla collezione permanente e circa 1.500 alle mostre temporanee; il resto è occupato da una biblioteca, una sala multimediale, una libreria e i percorsi che li collegano.',
    },
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q3503103', title: 'Museum of Contemporary Art, Zagreb (Q3503103)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Museum_of_Contemporary_Art,_Zagreb', title: 'Museum of Contemporary Art, Zagreb', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Igor_Frani%C4%87', title: 'Igor Franić', license: 'CC BY-SA 4.0' },
    ],
    tier: 'deep',
  },
  {
    id: 'zlin-congress-centre',
    wikidataId: 'Q28758229',
    name: {
      en: 'Congress Centre, Zlín',
      es: 'Centro de Congresos de Zlín',
      it: 'Centro congressi di Zlín',
    },
    architectId: 'eva-jiricna',
    location: { city: 'Zlín', countryCode: 'CZ', lat: 49.2231514, lon: 17.6643719 },
    inception: 2007,
    completed: 2010,
    demolished: null,
    typology: 'cultural',
    materials: ['steel-and-glass', 'concrete'],
    structure: {
      en: 'A concrete drum housing the auditorium, ringed by a foyer wall of glass block and steel, and covered by a 60-metre steel roof weighing some 90 tonnes that spans the hall without intermediate support.',
      es: 'Un tambor de hormigón que aloja el auditorio, ceñido por un muro de vestíbulo de pavés y acero y cubierto por una techumbre metálica de 60 metros y unas 90 toneladas que salva la sala sin apoyos intermedios.',
      it: 'Un tamburo in calcestruzzo che ospita l\'auditorio, cinto da una parete di foyer in vetrocemento e acciaio e coperto da un tetto in acciaio di 60 metri e circa 90 tonnellate che scavalca la sala senza appoggi intermedi.',
    },
    program: {
      en: 'A concert and conference hall for the city of Zlín, forming one complex with the university centre of Tomas Bata University completed alongside it.',
      es: 'Sala de conciertos y congresos para la ciudad de Zlín, que forma un único complejo con el centro universitario de la Universidad Tomáš Baťa terminado junto a ella.',
      it: 'Sala per concerti e congressi per la città di Zlín, che forma un unico complesso con il centro universitario dell\'Università Tomáš Baťa completato accanto ad essa.',
    },
    heritage: 'none',
    currentUse: {
      en: 'Home of the Bohuslav Martinů Philharmonic and the city\'s conference venue; its two halls are named after Eva Jiřičná and the former mayor Irena Ondrová.',
      es: 'Sede de la Filarmónica Bohuslav Martinů y recinto de congresos de la ciudad; sus dos salas llevan los nombres de Eva Jiřičná y de la exalcaldesa Irena Ondrová.',
      it: 'Sede della Filarmonica Bohuslav Martinů e struttura congressuale della città; le sue due sale portano i nomi di Eva Jiřičná e dell\'ex sindaca Irena Ondrová.',
    },
    detailRect: { x: 0.42, y: 0.24, w: 0.30, h: 0.30 },
    image: {
      commonsFile: 'File:Zlín, Kongresové centrum, od severovýchodu.jpg',
      photographer: 'ŠJů',
      license: 'CC BY 4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Zl%C3%ADn%2C_Kongresov%C3%A9_centrum%2C_od_severov%C3%BDchodu.jpg',
      width: 0,
      height: 0,
    },
    dossier: {
      en: 'Zlín was built almost from nothing in the 1920s and 1930s as the company town of the Baťa shoe works, on a strict grid of red brick and reinforced concrete frames. Eva Jiřičná was born there in 1939 and left as a small child; the congress and university centre is her return, seventy years later, to the town her practice partners still call the model. The hall sits in a plain concrete drum, wrapped by a foyer whose outer wall is glass block held in a steel cage, so that the building glows rather than displays itself after dark. Over it sits a steel roof sixty metres across and about ninety tonnes in weight, spanning the auditorium in one piece; she described its structure as taken from the silica shell of a diatom. The university centre alongside was finished in 2008 and the two opened together in 2010.',
      es: 'Zlín se construyó casi de la nada en los años veinte y treinta como ciudad-fábrica de la zapatera Baťa, sobre una retícula estricta de ladrillo rojo y pórticos de hormigón armado. Eva Jiřičná nació allí en 1939 y se marchó siendo muy niña; el centro de congresos y universitario es su regreso, setenta años después, a la ciudad que sus socios siguen llamando el modelo. La sala se aloja en un tambor liso de hormigón, envuelto por un vestíbulo cuyo muro exterior es pavés sostenido en una jaula de acero, de modo que al anochecer el edificio irradia luz en vez de exhibirse. Encima descansa una cubierta de acero de sesenta metros de luz y unas noventa toneladas, que salva el auditorio de una sola pieza; ella describió su estructura como tomada del caparazón silíceo de una diatomea. Ambos edificios se inauguraron en 2010.',
      it: 'Zlín fu costruita quasi dal nulla negli anni Venti e Trenta come città-fabbrica del calzaturificio Baťa, su una griglia rigorosa di mattoni rossi e telai in cemento armato. Eva Jiřičná vi nacque nel 1939 e se ne andò ancora bambina; il centro congressi e universitario è il suo ritorno, settant\'anni dopo, alla città che i suoi soci chiamano ancora il modello. La sala è alloggiata in un tamburo liscio di calcestruzzo, avvolto da un foyer la cui parete esterna è in vetrocemento retto da una gabbia d\'acciaio, così che al buio l\'edificio irradia luce anziché esibirsi. Sopra poggia una copertura in acciaio di sessanta metri di luce e circa novanta tonnellate, che scavalca l\'auditorio in un pezzo solo; ne descrisse la struttura come ripresa dal guscio siliceo di una diatomea. I due edifici furono inaugurati insieme nel 2010.',
    },
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q28758229', title: 'Congress Center Zlín (Q28758229)', license: null },
      { kind: 'wikipedia', url: 'https://cs.wikipedia.org/wiki/Kongresov%C3%A9_centrum_Zl%C3%ADn', title: 'Kongresové centrum Zlín (Czech Wikipedia)', license: 'CC BY-SA 4.0' },
      { kind: 'institution', url: 'https://www.zlin.eu/tiskove-zpravy/saly-kongresoveho-centra-nesou-jmena-architektky-jiricne-a-byvale-primatorky-ondrove-65e7', title: 'Sály Kongresového centra nesou jména architektky Jiřičné a bývalé primátorky Ondrové — City of Zlín', license: null },
    ],
    tier: 'deep',
  },
];
