import type { Building } from '@/types/building';

// Wave 5, agent 9a — Southern Europe (Italy, Spain, Portugal, Greece, Malta).
//
// Every `image` below was checked by opening the live Commons file page and
// reading the licence box; the licence string and photographer are recorded as
// they appear there, and candidates whose licence fell outside the allowed set
// (CC0, CC BY 2.0/3.0/4.0, CC BY-SA 2.0/3.0/4.0, PD) were discarded rather than
// inferred. `image.width` and `image.height` are left at 0 for Task 10.
//
// Note on Freedom of Panorama: Italy and Greece have none, so every Italian and
// Greek entry here is a building whose architect has been dead more than
// seventy years and whose photographs are therefore unencumbered. Spain,
// Portugal and Malta do have Freedom of Panorama, which is why the twentieth-
// and twenty-first-century entries cluster in the Iberian peninsula.
export const EUROPE_BUILDINGS: Building[] = [
  {
    id: 'cupola-di-santa-maria-del-fiore',
    wikidataId: 'Q3699556',
    name: {
      en: 'Dome of Santa Maria del Fiore',
      es: 'Cúpula de Santa María del Fiore',
      it: 'Cupola di Santa Maria del Fiore',
    },
    architectId: 'filippo-brunelleschi',
    location: { city: 'Florence', countryCode: 'IT', lat: 43.7727, lon: 11.25582 },
    inception: 1420,
    completed: 1436,
    demolished: null,
    typology: 'sacral',
    materials: ['brick', 'stone'],
    structure: {
      en: 'A self-supporting double shell of herringbone brickwork, braced by eight major and sixteen minor ribs and by stone and timber tension rings, and raised without centring.',
      es: 'Un doble casco autoportante de fábrica en espina de pez, arriostrado por ocho nervios mayores y dieciséis menores y por anillos de tracción de piedra y madera, levantado sin cimbra.',
      it: 'Una doppia calotta autoportante in muratura a spina di pesce, controventata da otto costoloni maggiori e sedici minori e da anelli di trazione in pietra e legno, costruita senza centina.',
    },
    program: {
      en: 'To vault the crossing of the Florentine cathedral for the Opera del Duomo and the wool guild that paid for it, over a drum left open since 1367.',
      es: 'Abovedar el crucero de la catedral de Florencia para la Opera del Duomo y el gremio de la lana que la financiaba, sobre un tambor que seguía abierto desde 1367.',
      it: "Voltare la crociera della cattedrale fiorentina per l'Opera del Duomo e l'Arte della Lana che la finanziava, su un tamburo rimasto aperto dal 1367.",
    },
    heritage: 'unesco',
    currentUse: {
      en: 'Still the roof of a working cathedral; the cavity between the two shells carries a public stair to the lantern.',
      es: 'Sigue siendo la cubierta de una catedral en uso; la cámara entre los dos cascos aloja una escalera pública hasta la linterna.',
      it: 'È ancora la copertura di una cattedrale in uso; il vano fra le due calotte ospita una scala pubblica fino alla lanterna.',
    },
    detailRect: { x: 0.20, y: 0.58, w: 0.34, h: 0.22 },
    image: {
      commonsFile: 'File:Brunelleschi’s dome seen from the bell tower.jpg',
      photographer: 'Maksim Sokolov (maxergon.com)',
      license: 'CC BY-SA 4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Brunelleschi%E2%80%99s_dome_seen_from_the_bell_tower.jpg',
      width: 1200,
      height: 1600,
    },
    dossier: {
      en: 'The cathedral had stood open to the sky for over fifty years when the Opera del Duomo announced its competition in 1418: the octagonal drum was some 45 metres across and began 55 metres above the floor, and Tuscany had no timber long enough to centre a vault of that span. Brunelleschi’s answer, begun in 1420, was to build without centring at all. Two shells, an inner structural one and an outer weather skin, are tied together by eight major and sixteen minor ribs, with stone and timber rings acting as hoops against the outward thrust; the brickwork between them is laid in a herringbone pattern so that each course locks into the last and every ring is self-supporting as it closes. Roughly four million bricks were lifted by hoists he designed himself. The shell was closed in 1436 and the cathedral consecrated the same year; the lantern was begun only after his death. It is still the largest masonry dome ever built.',
      es: 'La catedral llevaba más de cincuenta años abierta al cielo cuando la Opera del Duomo convocó su concurso en 1418: el tambor octogonal medía unos 45 metros de luz y arrancaba a 55 metros del pavimento, y en Toscana no había madera bastante larga para cimbrar una bóveda de esa dimensión. La respuesta de Brunelleschi, iniciada en 1420, fue construir sin cimbra alguna. Dos cascos, uno interior portante y otro exterior de protección, quedan trabados por ocho nervios mayores y dieciséis menores, con anillos de piedra y de madera que trabajan como zunchos contra el empuje; la fábrica intermedia se apareja en espina de pez, de modo que cada hilada traba con la anterior y cada anillo se sostiene solo mientras se cierra. Se elevaron unos cuatro millones de ladrillos con grúas que él mismo diseñó. El casco se cerró en 1436 y la catedral se consagró ese mismo año; la linterna no se empezó hasta después de su muerte. Sigue siendo la mayor cúpula de fábrica jamás construida.',
      it: "La cattedrale era rimasta aperta al cielo per oltre cinquant'anni quando l'Opera del Duomo bandì il concorso del 1418: il tamburo ottagonale misurava circa 45 metri di luce e partiva a 55 metri dal pavimento, e in Toscana non esisteva legname abbastanza lungo per centinare una volta di quella misura. La risposta di Brunelleschi, avviata nel 1420, fu costruire senza centina. Due calotte, una interna portante e una esterna di protezione, sono legate da otto costoloni maggiori e sedici minori, con anelli di pietra e di legno che lavorano come cerchiature contro la spinta; la muratura interposta è apparecchiata a spina di pesce, così che ogni corso si incastri nel precedente e ogni anello si regga da sé mentre si chiude. Furono sollevati circa quattro milioni di mattoni con argani da lui stesso progettati. La calotta fu chiusa nel 1436 e la cattedrale consacrata lo stesso anno; la lanterna fu iniziata solo dopo la sua morte. Resta la più grande cupola in muratura mai costruita.",
    },
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q3699556', title: "Brunelleschi's dome (Q3699556)", license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Florence_Cathedral', title: 'Florence Cathedral — Wikipedia', license: 'CC BY-SA 4.0' },
      { kind: 'institution', url: 'https://whc.unesco.org/en/list/174/', title: 'Historic Centre of Florence — UNESCO World Heritage Centre', license: null },
      { kind: 'institution', url: 'https://duomo.firenze.it/en/discover/dome', title: 'Brunelleschi’s Dome — Opera di Santa Maria del Fiore', license: null },
    ],
    tier: 'canon',
  },
  {
    id: 'villa-la-rotonda',
    wikidataId: 'Q505574',
    name: {
      en: 'Villa Almerico Capra (La Rotonda)',
      es: 'Villa Almerico Capra (La Rotonda)',
      it: 'Villa Almerico Capra (La Rotonda)',
    },
    architectId: 'andrea-palladio',
    location: { city: 'Vicenza', countryCode: 'IT', lat: 45.53152, lon: 11.56027 },
    inception: 1567,
    completed: 1605,
    demolished: null,
    typology: 'domestic',
    materials: ['brick', 'stone'],
    structure: {
      en: 'Load-bearing brick walls rendered in lime, arranged as a square around a domed circular hall, with four identical stone-dressed Ionic porticoes carrying timber-framed pediments.',
      es: 'Muros portantes de ladrillo enfoscados con cal, dispuestos en cuadrado en torno a una sala circular cupulada, con cuatro pórticos jónicos idénticos labrados en piedra y frontones de armadura de madera.',
      it: 'Muri portanti in laterizio intonacati a calce, disposti a quadrato attorno a una sala circolare cupolata, con quattro portici ionici identici in pietra e frontoni a struttura lignea.',
    },
    program: {
      en: 'A suburban belvedere with no farm attached, built for Paolo Almerico, a retired official of the papal court, on a hill within sight of Vicenza.',
      es: 'Un belvedere suburbano sin explotación agrícola aneja, construido para Paolo Almerico, funcionario jubilado de la curia papal, en una colina a la vista de Vicenza.',
      it: 'Un belvedere suburbano senza azienda agricola annessa, costruito per Paolo Almerico, funzionario in pensione della corte papale, su un colle a vista di Vicenza.',
    },
    heritage: 'unesco',
    currentUse: {
      en: 'Privately owned by the Valmarana family and open to visitors on a seasonal timetable.',
      es: 'Propiedad privada de la familia Valmarana, abierta a visitas con horario estacional.',
      it: 'Proprietà privata della famiglia Valmarana, aperta alle visite con orario stagionale.',
    },
    detailRect: { x: 0.30, y: 0.33, w: 0.38, h: 0.22 },
    image: {
      commonsFile: 'File:07-Villa-Rotonda-Palladio.jpg',
      photographer: 'Quinok',
      license: 'CC BY-SA 4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:07-Villa-Rotonda-Palladio.jpg',
      width: 1600,
      height: 1067,
    },
    dossier: {
      en: 'Most Palladian villas are working farms, with barns and dovecotes in the wings and the owner’s house in the middle. La Rotonda is not one: Paolo Almerico, a retired official of the papal court, wanted a belvedere on a hill outside Vicenza, and Palladio gave him a building with no agricultural function whatever. The plan is a square containing a circle — a domed central hall lit from above, ringed by rooms — and each of the four faces carries an identical hexastyle Ionic portico reached by a broad flight of steps, so the house has four fronts and no back. The walls are brick under lime render, tooled and painted to read as stone. Building began in 1567; Palladio died in 1580 and Vincenzo Scamozzi finished the villa with a shallow saucer dome rather than the hemisphere drawn in the Quattro Libri. The Capra brothers bought it in 1592 and completed the interiors by 1605. Chiswick House, Mereworth Castle and Monticello all descend from this plan.',
      es: 'La mayoría de las villas palladianas son explotaciones agrícolas, con graneros y palomares en las alas y la casa del propietario en el centro. La Rotonda no lo es: Paolo Almerico, funcionario jubilado de la curia papal, quería un belvedere en una colina a las afueras de Vicenza, y Palladio le dio un edificio sin función agraria alguna. La planta es un cuadrado que contiene un círculo —una sala central cupulada e iluminada cenitalmente, rodeada de estancias— y cada una de las cuatro caras lleva un pórtico jónico hexástilo idéntico al que se accede por una amplia escalinata, de modo que la casa tiene cuatro frentes y ninguna trasera. Los muros son de ladrillo bajo enfoscado de cal, labrado y pintado para leerse como piedra. Las obras comenzaron en 1567; Palladio murió en 1580 y Vincenzo Scamozzi remató la villa con una cúpula rebajada en lugar de la semiesfera dibujada en los Quattro Libri. Los hermanos Capra la compraron en 1592 y terminaron los interiores hacia 1605. De esta planta descienden Chiswick House, Mereworth Castle y Monticello.',
      it: "La maggior parte delle ville palladiane sono aziende agricole, con barchesse e colombaie nelle ali e la casa del proprietario al centro. La Rotonda non lo è: Paolo Almerico, funzionario in pensione della corte papale, voleva un belvedere su un colle fuori Vicenza, e Palladio gli diede un edificio privo di qualsiasi funzione agraria. La pianta è un quadrato che contiene un cerchio — una sala centrale cupolata e illuminata dall'alto, cinta da stanze — e ciascuna delle quattro facce porta un identico portico ionico esastilo raggiunto da un'ampia scalinata, così che la casa ha quattro fronti e nessun retro. I muri sono in laterizio sotto intonaco di calce, lavorato e dipinto per leggersi come pietra. I lavori iniziarono nel 1567; Palladio morì nel 1580 e Vincenzo Scamozzi concluse la villa con una cupola ribassata anziché con la semisfera disegnata nei Quattro Libri. I fratelli Capra la acquistarono nel 1592 e completarono gli interni entro il 1605. Da questa pianta discendono Chiswick House, Mereworth Castle e Monticello.",
    },
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q505574', title: 'Villa Almerico Capra (Q505574)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Villa_La_Rotonda', title: 'Villa La Rotonda — Wikipedia', license: 'CC BY-SA 4.0' },
      { kind: 'institution', url: 'https://whc.unesco.org/en/list/712/', title: 'City of Vicenza and the Palladian Villas of the Veneto — UNESCO World Heritage Centre', license: null },
    ],
    tier: 'canon',
  },
  {
    id: 'st-johns-co-cathedral',
    wikidataId: 'Q613619',
    name: {
      en: "St John's Co-Cathedral",
      es: 'Concatedral de San Juan',
      it: 'Concattedrale di San Giovanni',
    },
    architectId: 'girolamo-cassar',
    location: { city: 'Valletta', countryCode: 'MT', lat: 35.89778, lon: 14.51278 },
    inception: 1573,
    completed: 1578,
    demolished: null,
    typology: 'sacral',
    materials: ['stone'],
    structure: {
      en: 'Load-bearing globigerina limestone walls carrying a single barrel-vaulted nave cut from the rock of the site, with side chapels between the buttresses and two flanking bell towers.',
      es: 'Muros portantes de caliza globigerina que sostienen una nave única abovedada en cañón, labrada con la propia roca del solar, con capillas laterales entre los contrafuertes y dos campanarios que flanquean la fachada.',
      it: "Muri portanti in pietra globigerina che reggono un'unica navata a botte, ricavata dalla roccia stessa del sito, con cappelle laterali fra i contrafforti e due campanili ai lati della facciata.",
    },
    program: {
      en: 'The conventual church of the Order of St John, commissioned by Grand Master Jean de la Cassière as the Order’s own church in the city it had just built after the siege of 1565.',
      es: 'La iglesia conventual de la Orden de San Juan, encargada por el gran maestre Jean de la Cassière como templo propio de la Orden en la ciudad que acababa de construir tras el sitio de 1565.',
      it: "La chiesa conventuale dell'Ordine di San Giovanni, commissionata dal gran maestro Jean de la Cassière come tempio proprio dell'Ordine nella città appena costruita dopo l'assedio del 1565.",
    },
    heritage: 'unesco',
    currentUse: {
      en: 'Co-cathedral of the Archdiocese of Malta, in liturgical use and open as a museum.',
      es: 'Concatedral de la archidiócesis de Malta, en uso litúrgico y abierta como museo.',
      it: "Concattedrale dell'arcidiocesi di Malta, in uso liturgico e aperta come museo.",
    },
    detailRect: { x: 0.38, y: 0.58, w: 0.24, h: 0.36 },
    image: {
      commonsFile: "File:Facade of St. John's Co-Cathedral, Valletta, Malta.jpg",
      photographer: 'Julian Lupyan',
      license: 'CC0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Facade_of_St._John%27s_Co-Cathedral,_Valletta,_Malta.jpg',
      width: 1600,
      height: 1069,
    },
    dossier: {
      en: 'Eight years after the Ottoman siege of 1565, the Order of St John commissioned its conventual church from Girolamo Cassar, the Maltese architect who had taken over the building of Valletta when the military engineer Francesco Laparelli left the island. Cassar had been trained on fortifications and the façade shows it: a flat cliff of pale globigerina limestone between two blunt bell towers, with almost no ornament beyond a doorway and a balcony from which grand masters were proclaimed. It was completed in 1578. What happened inside is a different building. From 1661 Mattia Preti painted the whole barrel vault, the piers were carved into high relief, and the floor was laid with some four hundred inlaid marble tomb slabs of the knights; the oratory holds Caravaggio’s Beheading of Saint John the Baptist of 1608, the only painting he signed. The austerity outside and the Baroque inside are a century apart, and only the first is Cassar’s.',
      es: 'Ocho años después del sitio otomano de 1565, la Orden de San Juan encargó su iglesia conventual a Girolamo Cassar, el arquitecto maltés que había asumido la construcción de La Valeta cuando el ingeniero militar Francesco Laparelli abandonó la isla. Cassar se había formado en fortificaciones y la fachada lo delata: un acantilado liso de caliza globigerina clara entre dos campanarios romos, casi sin más ornamento que la portada y el balcón desde el que se proclamaba a los grandes maestres. Se terminó en 1578. Lo que ocurrió dentro es otro edificio. Desde 1661 Mattia Preti pintó la bóveda de cañón entera, los pilares se labraron en altorrelieve y el pavimento se cubrió con unas cuatrocientas losas sepulcrales de mármol taraceado de los caballeros; el oratorio guarda la Decapitación de san Juan Bautista de Caravaggio, de 1608, el único cuadro que firmó. La austeridad exterior y el barroco interior distan un siglo, y solo el primero es de Cassar.',
      it: "Otto anni dopo l'assedio ottomano del 1565, l'Ordine di San Giovanni commissionò la propria chiesa conventuale a Girolamo Cassar, l'architetto maltese che aveva assunto la costruzione della Valletta quando l'ingegnere militare Francesco Laparelli lasciò l'isola. Cassar si era formato sulle fortificazioni e la facciata lo tradisce: una rupe liscia di pietra globigerina chiara fra due campanili tozzi, quasi senza ornato oltre al portale e al balcone da cui si proclamavano i gran maestri. Fu completata nel 1578. Ciò che accadde all'interno è un altro edificio. Dal 1661 Mattia Preti dipinse l'intera volta a botte, i pilastri furono scolpiti ad altorilievo e il pavimento fu rivestito con circa quattrocento lastre tombali in marmi intarsiati dei cavalieri; l'oratorio custodisce la Decollazione di san Giovanni Battista di Caravaggio, del 1608, l'unico dipinto che egli firmò. L'austerità esterna e il barocco interno distano un secolo, e solo la prima è di Cassar.",
    },
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q613619', title: "St. John's Co-Cathedral (Q613619)", license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/St_John%27s_Co-Cathedral', title: "St John's Co-Cathedral — Wikipedia", license: 'CC BY-SA 4.0' },
      { kind: 'institution', url: 'https://whc.unesco.org/en/list/131/', title: 'City of Valletta — UNESCO World Heritage Centre', license: null },
      { kind: 'institution', url: 'https://www.stjohnscocathedral.com/', title: "St John's Co-Cathedral Foundation", license: null },
    ],
    tier: 'canon',
  },
  {
    id: 'casa-mila',
    wikidataId: 'Q207870',
    name: {
      en: 'Casa Milà (La Pedrera)',
      es: 'Casa Milà (La Pedrera)',
      it: 'Casa Milà (La Pedrera)',
    },
    architectId: 'antoni-gaudi',
    location: { city: 'Barcelona', countryCode: 'ES', lat: 41.39528, lon: 2.16167 },
    inception: 1906,
    completed: 1912,
    demolished: null,
    typology: 'housing',
    materials: ['stone', 'brick'],
    structure: {
      en: 'A self-supporting limestone façade hung on steel beams and cast columns rather than carrying load, which frees every floor plan, above brick catenary arches that shape the attic and the roof terrace.',
      es: 'Una fachada autoportante de caliza colgada de vigas de acero y pilares fundidos en lugar de trabajar como muro de carga, lo que libera todas las plantas, sobre arcos catenarios de ladrillo que conforman el desván y la azotea.',
      it: "Una facciata autoportante in calcare appesa a travi d'acciaio e pilastri in ghisa anziché portante, il che libera ogni pianta, sopra archi catenari in mattoni che modellano il sottotetto e il terrazzo.",
    },
    program: {
      en: 'A speculative apartment block with the owners’ own principal floor, built for the businessman Pere Milà and his wife Roser Segimon on the Passeig de Gràcia.',
      es: 'Un edificio de viviendas de renta con el piso principal para los propietarios, levantado para el empresario Pere Milà y su esposa Roser Segimon en el paseo de Gracia.',
      it: 'Un edificio di appartamenti da reddito con il piano principale per i proprietari, costruito per l’imprenditore Pere Milà e la moglie Roser Segimon sul Passeig de Gràcia.',
    },
    heritage: 'unesco',
    currentUse: {
      en: 'Part residential, part cultural centre run by the Fundació Catalunya La Pedrera, with the attic and roof open to visitors.',
      es: 'En parte viviendas y en parte centro cultural gestionado por la Fundació Catalunya La Pedrera, con desván y azotea abiertos al público.',
      it: 'In parte residenza e in parte centro culturale gestito dalla Fundació Catalunya La Pedrera, con sottotetto e terrazzo aperti al pubblico.',
    },
    detailRect: { x: 0.46, y: 0.30, w: 0.28, h: 0.26 },
    image: {
      commonsFile: 'File:Casa Milà, general view.jpg',
      photographer: 'Thomas Ledl',
      license: 'CC BY-SA 4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Casa_Mil%C3%A0,_general_view.jpg',
      width: 1600,
      height: 1246,
    },
    dossier: {
      en: 'Barcelona nicknamed it La Pedrera, the quarry, and did not mean it kindly. Gaudí’s last private commission, built between 1906 and 1912 for Pere Milà and Roser Segimon, exceeded the height and volume the Eixample bylaws allowed and spent years in dispute with the city; Segimon disliked the result and stripped much of Gaudí’s interior work after her husband’s death. The technical argument is more radical than the surface. The undulating Garraf and Vilafranca limestone front carries no load: it hangs from steel beams tied back to a frame of iron and stone columns, so that every apartment plan is free and can be rearranged, and the two courtyards let daylight to the centre of a deep block. Wrought-iron balconies attributed to Josep Maria Jujol are fixed to it like seaweed. The attic is a run of 270 brick catenary arches, and the roof terrace turns stairs and ventilation shafts into helmeted figures. UNESCO inscribed it in 1984.',
      es: 'Barcelona la apodó La Pedrera y no fue un cumplido. El último encargo privado de Gaudí, construido entre 1906 y 1912 para Pere Milà y Roser Segimon, excedía la altura y el volumen que permitían las ordenanzas del Eixample y pasó años en litigio con el ayuntamiento; a Segimon no le gustó el resultado y desmontó buena parte del interior de Gaudí tras enviudar. El argumento técnico es más radical que la superficie. El frente ondulado de caliza del Garraf y de Vilafranca no soporta carga: cuelga de vigas de acero atadas a una estructura de pilares de hierro y piedra, de modo que cada planta de vivienda es libre y puede recomponerse, y los dos patios llevan la luz al centro de una manzana profunda. Las barandillas de forja atribuidas a Josep Maria Jujol se le adhieren como algas. El desván es una sucesión de 270 arcos catenarios de ladrillo, y la azotea convierte cajas de escalera y chimeneas en figuras con yelmo. La Unesco la inscribió en 1984.',
      it: "Barcellona la soprannominò La Pedrera, la cava, e non era un complimento. L'ultima commessa privata di Gaudí, costruita fra il 1906 e il 1912 per Pere Milà e Roser Segimon, eccedeva l'altezza e il volume consentiti dai regolamenti dell'Eixample e passò anni in contenzioso con il comune; a Segimon il risultato non piacque e dopo la morte del marito smantellò gran parte degli interni di Gaudí. L'argomento tecnico è più radicale della superficie. Il fronte ondulato in calcare del Garraf e di Vilafranca non è portante: pende da travi d'acciaio ancorate a un telaio di pilastri in ferro e pietra, così che ogni pianta d'appartamento è libera e ricomponibile, e i due cortili portano luce al centro di un isolato profondo. Le ringhiere in ferro battuto attribuite a Josep Maria Jujol vi aderiscono come alghe. Il sottotetto è una successione di 270 archi catenari in mattoni, e il terrazzo trasforma vani scala e camini in figure elmate. L'Unesco lo ha iscritto nel 1984.",
    },
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q207870', title: 'Casa Milà (Q207870)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Casa_Mil%C3%A0', title: 'Casa Milà — Wikipedia', license: 'CC BY-SA 4.0' },
      { kind: 'institution', url: 'https://whc.unesco.org/en/list/320/', title: 'Works of Antoni Gaudí — UNESCO World Heritage Centre', license: null },
      { kind: 'institution', url: 'https://www.lapedrera.com/en', title: 'La Pedrera — Fundació Catalunya La Pedrera', license: null },
    ],
    tier: 'canon',
  },
  {
    id: 'casa-del-fascio-como',
    wikidataId: 'Q2719120',
    name: {
      en: 'Casa del Fascio, Como',
      es: 'Casa del Fascio de Como',
      it: 'Casa del Fascio di Como',
    },
    architectId: 'giuseppe-terragni',
    location: { city: 'Como', countryCode: 'IT', lat: 45.81231, lon: 9.08593 },
    inception: 1932,
    completed: 1936,
    demolished: null,
    typology: 'civic',
    materials: ['concrete', 'stone'],
    structure: {
      en: 'A reinforced-concrete frame on a square plan of roughly 33 by 33 metres and half that in height, faced in Botticino marble, with the grid left visible and individual bays glazed, recessed or left as void.',
      es: 'Una estructura de hormigón armado sobre planta cuadrada de unos 33 por 33 metros y la mitad de altura, revestida de mármol de Botticino, con la retícula a la vista y cada crujía acristalada, retranqueada o dejada como hueco.',
      it: 'Un telaio in cemento armato su pianta quadrata di circa 33 per 33 metri e altezza pari alla metà, rivestito in marmo di Botticino, con la griglia lasciata a vista e ogni campata vetrata, arretrata o lasciata come vuoto.',
    },
    program: {
      en: 'Provincial headquarters of the National Fascist Party in Como, with offices, a party assembly hall and a glazed entrance hall opening directly onto the square for rallies.',
      es: 'Sede provincial del Partido Nacional Fascista en Como, con oficinas, sala de asambleas del partido y un vestíbulo acristalado que se abría directamente a la plaza para las concentraciones.',
      it: "Sede provinciale del Partito Nazionale Fascista a Como, con uffici, sala d'assemblea del partito e un atrio vetrato apribile direttamente sulla piazza per le adunate.",
    },
    heritage: 'national',
    currentUse: {
      en: 'Provincial command of the Guardia di Finanza, occupied by that service since 1957 and not generally open to the public.',
      es: 'Comandancia provincial de la Guardia di Finanza, ocupada por ese cuerpo desde 1957 y sin apertura general al público.',
      it: 'Comando provinciale della Guardia di Finanza, occupato da quel corpo dal 1957 e non aperto in generale al pubblico.',
    },
    detailRect: { x: 0.28, y: 0.28, w: 0.30, h: 0.28 },
    image: {
      commonsFile: 'File:Casa del Fascio (Como) 02.jpg',
      photographer: 'Nicola Quirico',
      license: 'CC BY-SA 4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Casa_del_Fascio_(Como)_02.jpg',
      width: 1600,
      height: 1200,
    },
    dossier: {
      en: 'Terragni set himself a geometric constraint and held to it: a square plan roughly 33 metres on a side, rising exactly half that height, so the building is half a cube. Within it a reinforced-concrete grid is left legible on all four elevations and then treated differently on each — bays are glazed, recessed into loggias, or simply left empty — so the same structure reads as solid on one front and as a cage on another. The marble facing is Botticino, thin and flush, deliberately not the rusticated stone that Italian public architecture of the 1930s otherwise favoured. Inside, a covered courtyard replaces the traditional atrium, and eighteen glazed doors were designed to open at once so that the assembly hall and the square became one space. It was inaugurated in 1936 as the provincial headquarters of the National Fascist Party. The Superintendency listed it as heritage of great historical and artistic interest in 1986.',
      es: 'Terragni se impuso una restricción geométrica y la mantuvo: planta cuadrada de unos 33 metros de lado que se eleva exactamente la mitad de esa altura, de modo que el edificio es medio cubo. Dentro de él, una retícula de hormigón armado queda legible en los cuatro alzados y se trata de manera distinta en cada uno —crujías acristaladas, retranqueadas en logia o simplemente vacías—, así que la misma estructura se lee como macizo en un frente y como jaula en otro. El revestimiento es mármol de Botticino, delgado y enrasado, deliberadamente ajeno al almohadillado que prefería la arquitectura pública italiana de los años treinta. En el interior, un patio cubierto sustituye al atrio tradicional, y dieciocho puertas acristaladas se proyectaron para abrirse a la vez, de modo que la sala de asambleas y la plaza fueran un solo espacio. Se inauguró en 1936 como sede provincial del Partido Nacional Fascista. La Superintendencia lo declaró bien de gran interés histórico y artístico en 1986.',
      it: "Terragni si impose un vincolo geometrico e lo tenne: pianta quadrata di circa 33 metri di lato che sale esattamente a metà di quella misura, sicché l'edificio è mezzo cubo. Al suo interno una griglia in cemento armato resta leggibile su tutti e quattro i prospetti e viene trattata in modo diverso su ciascuno — campate vetrate, arretrate a loggia o semplicemente vuote — così che la stessa struttura si legge come massa su un fronte e come gabbia su un altro. Il rivestimento è marmo di Botticino, sottile e a filo, deliberatamente estraneo al bugnato che l'architettura pubblica italiana degli anni Trenta preferiva. All'interno un cortile coperto sostituisce l'atrio tradizionale, e diciotto porte vetrate furono progettate per aprirsi insieme, così che la sala d'assemblea e la piazza diventassero un unico spazio. Fu inaugurata nel 1936 come sede provinciale del Partito Nazionale Fascista. La Soprintendenza la dichiarò bene di grande interesse storico e artistico nel 1986.",
    },
    context: {
      body: {
        en: 'The building was commissioned, paid for and used as the provincial headquarters of the National Fascist Party, and it stands on what was then Piazza Impero, now Piazza del Popolo; Terragni had been a party member since 1928. The glazed entrance hall and the eighteen doors that opened onto the square were designed for party assembly, and the interior originally carried a photomontage by Terragni celebrating the regime. After the fall of Fascism in 1945 the building passed to the parties of the National Liberation Committee, and since 1957 it has housed the provincial command of the Guardia di Finanza. It was listed as heritage of great historical and artistic interest by the Superintendency in 1986, and it is studied as a canonical work of Italian Rationalism and as a purpose-built instrument of a one-party state at the same time; the two facts are not separable.',
        es: 'El edificio fue encargado, pagado y usado como sede provincial del Partido Nacional Fascista, y se levanta en lo que entonces era la piazza Impero, hoy piazza del Popolo; Terragni estaba afiliado al partido desde 1928. El vestíbulo acristalado y las dieciocho puertas que se abrían a la plaza se proyectaron para las asambleas del partido, y el interior llevó originalmente un fotomontaje del propio Terragni en exaltación del régimen. Tras la caída del fascismo en 1945 el edificio pasó a los partidos del Comité de Liberación Nacional, y desde 1957 alberga la comandancia provincial de la Guardia di Finanza. La Superintendencia lo declaró bien de gran interés histórico y artístico en 1986, y se estudia a la vez como obra canónica del racionalismo italiano y como instrumento construido a propósito para un Estado de partido único; ambos hechos no son separables.',
        it: "L'edificio fu commissionato, pagato e usato come sede provinciale del Partito Nazionale Fascista, e sorge su quella che allora era piazza Impero, oggi piazza del Popolo; Terragni era iscritto al partito dal 1928. L'atrio vetrato e le diciotto porte apribili sulla piazza furono progettati per le adunate del partito, e l'interno recava in origine un fotomontaggio dello stesso Terragni in esaltazione del regime. Dopo la caduta del fascismo nel 1945 l'edificio passò ai partiti del Comitato di Liberazione Nazionale, e dal 1957 ospita il comando provinciale della Guardia di Finanza. La Soprintendenza lo dichiarò bene di grande interesse storico e artistico nel 1986, e viene studiato insieme come opera canonica del razionalismo italiano e come strumento costruito apposta per uno Stato a partito unico; i due fatti non sono separabili.",
      },
      sources: [
        { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Casa_del_Fascio_(Como)', title: 'Casa del Fascio (Como) — Wikipedia', license: 'CC BY-SA 4.0' },
        { kind: 'wikipedia', url: 'https://it.wikipedia.org/wiki/Casa_del_Fascio_(Como)', title: 'Casa del Fascio (Como) — Wikipedia (it)', license: 'CC BY-SA 4.0' },
        { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q2719120', title: 'Casa del Fascio di Como (Q2719120)', license: null },
      ],
    },
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q2719120', title: 'Casa del Fascio di Como (Q2719120)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Casa_del_Fascio_(Como)', title: 'Casa del Fascio (Como) — Wikipedia', license: 'CC BY-SA 4.0' },
    ],
    tier: 'canon',
  },
  {
    id: 'megaro-akadimias-athinon',
    wikidataId: 'Q12884476',
    name: {
      en: 'Academy of Athens building',
      es: 'Edificio de la Academia de Atenas',
      it: "Palazzo dell'Accademia di Atene",
    },
    architectId: 'theophil-hansen',
    location: { city: 'Athens', countryCode: 'GR', lat: 37.97976, lon: 23.73358 },
    inception: 1859,
    completed: 1885,
    demolished: null,
    typology: 'educational',
    materials: ['stone'],
    structure: {
      en: 'Load-bearing masonry faced entirely in Pentelic marble, organised as a central Ionic hexastyle temple front with two lower recessed wings and two free-standing votive columns.',
      es: 'Fábrica portante revestida por completo de mármol del Pentélico, organizada como un frente templario jónico hexástilo con dos alas retranqueadas más bajas y dos columnas votivas exentas.',
      it: 'Muratura portante rivestita interamente in marmo pentelico, organizzata come un fronte templare ionico esastilo con due ali arretrate più basse e due colonne votive isolate.',
    },
    program: {
      en: 'A learned academy for the new Greek state, funded by the Vienna-based Greek banker Simon Sinas and handed to the government in 1887.',
      es: 'Una academia científica para el joven Estado griego, financiada por el banquero griego de Viena Simón Sinas y entregada al gobierno en 1887.',
      it: 'Un’accademia scientifica per il giovane Stato greco, finanziata dal banchiere greco di Vienna Simon Sinas e consegnata al governo nel 1887.',
    },
    heritage: 'national',
    currentUse: {
      en: 'Seat of the Academy of Athens, Greece’s national academy, since 1926.',
      es: 'Sede de la Academia de Atenas, academia nacional de Grecia, desde 1926.',
      it: "Sede dell'Accademia di Atene, accademia nazionale della Grecia, dal 1926.",
    },
    detailRect: { x: 0.33, y: 0.32, w: 0.32, h: 0.24 },
    image: {
      commonsFile: 'File:Ακαδημία Αθηνών 5260.jpg',
      photographer: 'C messier',
      license: 'CC BY-SA 4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:%CE%91%CE%BA%CE%B1%CE%B4%CE%B7%CE%BC%CE%AF%CE%B1_%CE%91%CE%B8%CE%B7%CE%BD%CF%8E%CE%BD_5260.jpg',
      width: 1600,
      height: 1200,
    },
    dossier: {
      en: 'The building was paid for by Simon Sinas, a Greek banker in Vienna, and was known for years as the Sinaian Academy; its foundations were laid in 1859 and it took twenty-six years to finish. Hansen had spent eight years in Athens measuring and restoring ancient monuments before moving to Vienna, and the design is an archaeologist’s classicism rather than a nostalgic one. The Ionic order is taken from the Erechtheion, the whole is faced in Pentelic marble from the quarry that supplied the Parthenon, and — the point most often missed — the entablature, coffers and acroteria were painted in red, blue and gold, because nineteenth-century excavation had proved that Greek temples were polychrome. Two votive columns carry Athena and Apollo by Leonidas Drosis; Plato and Socrates sit below. Handed to the Greek state in 1887, the building waited until 1926 for the academy it had been built to house. With Hansen’s brother Christian’s University and the National Library it forms the Athenian Trilogy.',
      es: 'El edificio lo costeó Simón Sinas, banquero griego afincado en Viena, y durante años se le llamó la Academia Sineana; sus cimientos se pusieron en 1859 y tardó veintiséis años en terminarse. Hansen había pasado ocho años en Atenas midiendo y restaurando monumentos antiguos antes de instalarse en Viena, y el proyecto es un clasicismo de arqueólogo antes que de nostálgico. El orden jónico procede del Erecteión, todo el conjunto se reviste de mármol del Pentélico —la cantera que abasteció al Partenón— y, detalle que suele pasarse por alto, el entablamento, los casetones y los acróteras se pintaron de rojo, azul y oro, porque las excavaciones decimonónicas habían demostrado que los templos griegos eran policromos. Dos columnas votivas sostienen a Atenea y Apolo, de Leonidas Drosis; abajo se sientan Platón y Sócrates. Entregado al Estado griego en 1887, el edificio esperó hasta 1926 a la academia para la que se había construido. Con la Universidad del hermano de Hansen, Christian, y la Biblioteca Nacional forma la Trilogía Ateniense.',
      it: "L'edificio fu pagato da Simon Sinas, banchiere greco stabilito a Vienna, e per anni fu detto Accademia Sinaia; le fondamenta furono poste nel 1859 e ci vollero ventisei anni per finirlo. Hansen aveva trascorso otto anni ad Atene misurando e restaurando monumenti antichi prima di trasferirsi a Vienna, e il progetto è un classicismo da archeologo più che da nostalgico. L'ordine ionico deriva dall'Eretteo, l'insieme è rivestito in marmo pentelico — la cava che fornì il Partenone — e, dettaglio che spesso sfugge, la trabeazione, i cassettoni e gli acroteri furono dipinti di rosso, blu e oro, perché gli scavi ottocenteschi avevano dimostrato che i templi greci erano policromi. Due colonne votive reggono Atena e Apollo di Leonidas Drosis; sotto siedono Platone e Socrate. Consegnato allo Stato greco nel 1887, l'edificio attese fino al 1926 l'accademia per la quale era stato costruito. Con l'Università del fratello Christian e la Biblioteca Nazionale forma la Trilogia Ateniese.",
    },
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q12884476', title: 'Hall of the Academy of Athens (Q12884476)', license: null },
      { kind: 'wikipedia', url: 'https://el.wikipedia.org/wiki/%CE%9C%CE%AD%CE%B3%CE%B1%CF%81%CE%BF_%CE%91%CE%BA%CE%B1%CE%B4%CE%B7%CE%BC%CE%AF%CE%B1%CF%82_%CE%91%CE%B8%CE%B7%CE%BD%CF%8E%CE%BD', title: 'Μέγαρο Ακαδημίας Αθηνών — Wikipedia (el)', license: 'CC BY-SA 4.0' },
      { kind: 'institution', url: 'http://odysseus.culture.gr/h/2/gh251.jsp?obj_id=713', title: 'Academy of Athens — Odysseus, Hellenic Ministry of Culture', license: null },
    ],
    tier: 'deep',
  },
  {
    id: 'piscinas-de-mares-leca-da-palmeira',
    wikidataId: 'Q1750602',
    name: {
      en: 'Tidal Pools of Leça da Palmeira',
      es: 'Piscinas de Mareas de Leça da Palmeira',
      it: 'Piscine di marea di Leça da Palmeira',
    },
    architectId: 'alvaro-siza',
    location: { city: 'Leça da Palmeira, Matosinhos', countryCode: 'PT', lat: 41.19286, lon: -8.70778 },
    inception: 1960,
    completed: 1966,
    demolished: null,
    typology: 'civic',
    materials: ['concrete', 'stone'],
    structure: {
      en: 'Board-marked reinforced concrete walls and slabs laid directly against the existing rock outcrops, which close the two seawater tanks and form the ramps, changing rooms and retaining wall along the road.',
      es: 'Muros y losas de hormigón armado con huella de encofrado apoyados directamente sobre los afloramientos rocosos existentes, que cierran los dos vasos de agua de mar y forman las rampas, los vestuarios y el muro de contención junto a la carretera.',
      it: "Muri e solette in cemento armato con l'impronta del cassero appoggiati direttamente sugli affioramenti rocciosi esistenti, che chiudono le due vasche di acqua di mare e formano le rampe, gli spogliatoi e il muro di sostegno lungo la strada.",
    },
    program: {
      en: 'A municipal seawater bathing complex on the Atlantic shore, with changing rooms, a café and two pools fed by the tide, commissioned by the town of Matosinhos.',
      es: 'Un complejo municipal de baños de agua de mar en la costa atlántica, con vestuarios, cafetería y dos vasos alimentados por la marea, encargado por el municipio de Matosinhos.',
      it: "Un complesso balneare comunale ad acqua di mare sulla costa atlantica, con spogliatoi, caffetteria e due vasche alimentate dalla marea, commissionato dal comune di Matosinhos.",
    },
    heritage: 'national',
    currentUse: {
      en: 'A public swimming facility, open seasonally between June and September and run by the municipal company Matosinhos Sport.',
      es: 'Instalación de baño pública, abierta por temporada entre junio y septiembre y gestionada por la empresa municipal Matosinhos Sport.',
      it: "Impianto balneare pubblico, aperto stagionalmente fra giugno e settembre e gestito dalla società comunale Matosinhos Sport.",
    },
    detailRect: { x: 0.12, y: 0.42, w: 0.30, h: 0.24 },
    image: {
      commonsFile: 'File:Piscina das Marés.jpg',
      photographer: 'Ricardo Saraiva de Almeida',
      license: 'CC BY-SA 4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Piscina_das_Mar%C3%A9s.jpg',
      width: 1600,
      height: 1068,
    },
    dossier: {
      en: 'Siza was in his late twenties when Matosinhos asked him for a swimming complex on a rocky Atlantic beach a kilometre south of the Boa Nova tea house he had just finished. He built almost nothing that reads as a building. A long concrete retaining wall runs parallel to the coast road and hides the whole installation from traffic; behind it a ramp descends between two blank walls, turns, and delivers the visitor onto the rocks with the ocean suddenly in front. The changing rooms are a dark, low, timber-lined interval on that route. The two tanks are made by adding straight concrete walls to the outcrops that were already there, so that a section drawn through them cannot tell reliably where the geology stops and the construction starts. The pools opened in 1966; work on the complex continued until 1973 and a planned restaurant was never built. Portugal classified them a national monument in 2011.',
      es: 'Siza rondaba los veintiocho años cuando Matosinhos le pidió un complejo de baños en una playa atlántica rocosa, un kilómetro al sur de la casa de té de Boa Nova que acababa de terminar. Apenas construyó nada que se lea como edificio. Un largo muro de contención de hormigón corre paralelo a la carretera de la costa y oculta toda la instalación al tráfico; detrás, una rampa desciende entre dos paredes ciegas, gira y deposita al visitante sobre las rocas con el océano de pronto delante. Los vestuarios son un intervalo oscuro, bajo y forrado de madera en ese recorrido. Los dos vasos se forman añadiendo muros rectos de hormigón a los afloramientos que ya estaban allí, de modo que una sección trazada por ellos no distingue con fiabilidad dónde acaba la geología y empieza la construcción. Las piscinas se abrieron en 1966; las obras del conjunto siguieron hasta 1973 y el restaurante previsto nunca llegó a construirse. Portugal las declaró monumento nacional en 2011.',
      it: "Siza aveva poco meno di trent'anni quando Matosinhos gli chiese un complesso balneare su una spiaggia atlantica rocciosa, un chilometro a sud della casa da tè di Boa Nova che aveva appena terminato. Costruì quasi nulla che si legga come edificio. Un lungo muro di sostegno in calcestruzzo corre parallelo alla strada costiera e nasconde l'intero impianto al traffico; dietro, una rampa scende fra due pareti cieche, gira e consegna il visitatore alle rocce con l'oceano improvvisamente davanti. Gli spogliatoi sono un intervallo scuro, basso e foderato di legno lungo quel percorso. Le due vasche si formano aggiungendo muri retti in calcestruzzo agli affioramenti che erano già lì, così che una sezione tracciata attraverso di esse non distingue con sicurezza dove finisca la geologia e cominci la costruzione. Le piscine aprirono nel 1966; i lavori del complesso proseguirono fino al 1973 e il ristorante previsto non fu mai costruito. Il Portogallo le ha classificate monumento nazionale nel 2011.",
    },
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q1750602', title: 'Tidal pools of Leça de Palmeira (Q1750602)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Tidal_pools_of_Le%C3%A7a_de_Palmeira', title: 'Tidal pools of Leça de Palmeira — Wikipedia', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://pt.wikipedia.org/wiki/Piscinas_de_Mar%C3%A9s_de_Le%C3%A7a_da_Palmeira', title: 'Piscinas de Marés de Leça da Palmeira — Wikipedia (pt)', license: 'CC BY-SA 4.0' },
    ],
    tier: 'canon',
  },
  {
    id: 'museo-nacional-de-arte-romano',
    wikidataId: 'Q3330685',
    name: {
      en: 'National Museum of Roman Art',
      es: 'Museo Nacional de Arte Romano',
      it: 'Museo Nazionale di Arte Romana',
    },
    architectId: 'rafael-moneo',
    location: { city: 'Mérida', countryCode: 'ES', lat: 38.91731, lon: -6.33986 },
    inception: 1980,
    completed: 1986,
    demolished: null,
    typology: 'cultural',
    materials: ['brick', 'concrete'],
    structure: {
      en: 'Parallel load-bearing walls of thin Roman-format brick over a concrete core, pierced by tall semicircular relieving arches that turn the walls into a nave and aisles and carry a clerestory.',
      es: 'Muros portantes paralelos de ladrillo de formato romano sobre un núcleo de hormigón, perforados por altos arcos de descarga de medio punto que convierten los muros en nave y naves laterales y sostienen un claristorio.',
      it: 'Muri portanti paralleli in laterizio di formato romano su un nucleo in calcestruzzo, forati da alti archi di scarico a tutto sesto che trasformano i muri in navata e navatelle e reggono un cleristorio.',
    },
    program: {
      en: 'A national museum for the finds of Augusta Emerita, built directly over the excavated remains of the Roman colony so that the archaeology could be visited in a crypt below the galleries.',
      es: 'Un museo nacional para los hallazgos de Augusta Emerita, levantado directamente sobre los restos excavados de la colonia romana para que la arqueología pudiera visitarse en una cripta bajo las salas.',
      it: "Un museo nazionale per i reperti di Augusta Emerita, costruito direttamente sopra i resti scavati della colonia romana perché l'archeologia potesse essere visitata in una cripta sotto le sale.",
    },
    heritage: 'unesco',
    currentUse: {
      en: 'A national museum of Spain under the Ministry of Culture, with more than 36,000 objects; Moneo’s own extension opened in 2026.',
      es: 'Museo nacional de España dependiente del Ministerio de Cultura, con más de 36.000 piezas; la ampliación del propio Moneo se inauguró en 2026.',
      it: "Museo nazionale di Spagna dipendente dal Ministero della Cultura, con oltre 36.000 pezzi; l'ampliamento dello stesso Moneo è stato inaugurato nel 2026.",
    },
    detailRect: { x: 0.28, y: 0.40, w: 0.30, h: 0.28 },
    image: {
      commonsFile: 'File:Museo Nacional de Arte Romano 2019An002.jpg',
      photographer: 'Anual',
      license: 'CC BY-SA 4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Museo_Nacional_de_Arte_Romano_2019An002.jpg',
      width: 1600,
      height: 1208,
    },
    dossier: {
      en: 'Moneo was commissioned in 1979 and built between 1980 and 1986 on a site that turned out to contain a substantial part of Roman Mérida, including a road and houses. Rather than clear the remains or float above them, he set a series of parallel brick walls across the excavation, following the Roman grid, and let the archaeology stay in a crypt directly beneath. Above, those same walls are opened by tall semicircular arches, so that the visitor moves down a nave with aisles and top light — a Roman construction logic rather than a Roman style, since there are no orders, no cornices and no imitation. The brick is a thin Roman format laid with almost no mortar joint, which gives the interior its striped, dry, quarried quality. The building was widely read as the moment Spanish architecture returned to international attention after Franco, and Moneo dedicated it to his father, who died during the works.',
      es: 'A Moneo se le encargó el proyecto en 1979 y lo construyó entre 1980 y 1986 sobre un solar que resultó contener buena parte de la Mérida romana, con una calzada y varias casas. En lugar de despejar los restos o de flotar sobre ellos, dispuso una serie de muros paralelos de ladrillo atravesando la excavación, siguiendo la trama romana, y dejó la arqueología en una cripta justo debajo. Arriba, esos mismos muros se abren con altos arcos de medio punto, de modo que el visitante recorre una nave con naves laterales y luz cenital: una lógica constructiva romana, no un estilo romano, porque no hay órdenes, ni cornisas, ni imitación. El ladrillo es de formato romano, muy delgado y tendido casi sin junta, lo que da al interior su condición rayada, seca, de cantera. El edificio se leyó como el momento en que la arquitectura española volvió a la atención internacional tras el franquismo, y Moneo lo dedicó a su padre, fallecido durante las obras.',
      it: "A Moneo l'incarico fu affidato nel 1979 e l'edificio fu costruito fra il 1980 e il 1986 su un'area che si rivelò contenere buona parte della Mérida romana, con una strada e alcune case. Invece di sgomberare i resti o di sorvolarli, dispose una serie di muri paralleli in laterizio attraverso lo scavo, seguendo la trama romana, e lasciò l'archeologia in una cripta proprio sotto. Sopra, quegli stessi muri si aprono con alti archi a tutto sesto, così che il visitatore percorre una navata con navatelle e luce zenitale: una logica costruttiva romana, non uno stile romano, perché non ci sono ordini, né cornici, né imitazione. Il mattone è di formato romano, sottilissimo e posato quasi senza giunto, il che dà all'interno la sua qualità rigata, asciutta, di cava. L'edificio fu letto come il momento in cui l'architettura spagnola tornò all'attenzione internazionale dopo il franchismo, e Moneo lo dedicò al padre, morto durante i lavori.",
    },
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q3330685', title: 'National Museum of Roman Art (Q3330685)', license: null },
      { kind: 'wikipedia', url: 'https://es.wikipedia.org/wiki/Museo_Nacional_de_Arte_Romano', title: 'Museo Nacional de Arte Romano — Wikipedia (es)', license: 'CC BY-SA 4.0' },
      { kind: 'institution', url: 'https://www.cultura.gob.es/mnromano/inicio.html', title: 'Museo Nacional de Arte Romano — Ministerio de Cultura', license: null },
      { kind: 'institution', url: 'https://whc.unesco.org/en/list/664/', title: 'Archaeological Ensemble of Mérida — UNESCO World Heritage Centre', license: null },
    ],
    tier: 'canon',
  },
  {
    id: 'cementiri-nou-igualada',
    wikidataId: 'Q5994387',
    name: {
      en: 'New Cemetery of Igualada',
      es: 'Cementerio Nuevo de Igualada',
      it: 'Nuovo cimitero di Igualada',
    },
    architectId: 'carme-pinos',
    // Wikidata's own P84 for this building (Q5994387) lists both Miralles
    // and Pinós; the dossier below already states the joint authorship and
    // warns that crediting Miralles alone is a common error. `architectId`
    // stays the pre-existing answer key (Pinós); Miralles is credited here
    // via the display-only co-credit rather than left off entirely.
    coArchitects: ['enric-miralles'],
    location: { city: 'Igualada', countryCode: 'ES', lat: 41.59194, lon: 1.63722 },
    inception: 1985,
    completed: 1994,
    demolished: null,
    typology: 'civic',
    materials: ['concrete', 'timber'],
    structure: {
      en: 'Precast and in-situ concrete retaining walls stacked as burial niches down both sides of a cut in the hillside, with weathering-steel gates and timber sleepers set into the ground surface.',
      es: 'Muros de contención de hormigón prefabricado e in situ apilados como nichos a ambos lados de un desmonte en la ladera, con cancelas de acero corten y traviesas de madera embebidas en el pavimento.',
      it: 'Muri di sostegno in calcestruzzo prefabbricato e gettato in opera impilati come loculi su entrambi i lati di uno sbancamento nel pendio, con cancelli in acciaio corten e traversine di legno incassate nel suolo.',
    },
    program: {
      en: 'A municipal cemetery for the town of Igualada, replacing an older burial ground, won in open competition in 1984 by Enric Miralles and Carme Pinós.',
      es: 'Un cementerio municipal para la villa de Igualada, en sustitución de un camposanto anterior, ganado en concurso abierto en 1984 por Enric Miralles y Carme Pinós.',
      it: 'Un cimitero comunale per la cittadina di Igualada, in sostituzione di un camposanto precedente, vinto per concorso aperto nel 1984 da Enric Miralles e Carme Pinós.',
    },
    heritage: 'national',
    currentUse: {
      en: 'The working municipal cemetery of Igualada; Enric Miralles, who died in 2000, is buried in it.',
      es: 'Cementerio municipal en uso de Igualada; en él está enterrado Enric Miralles, fallecido en 2000.',
      it: 'Cimitero comunale in uso di Igualada; vi è sepolto Enric Miralles, morto nel 2000.',
    },
    detailRect: { x: 0.34, y: 0.36, w: 0.34, h: 0.22 },
    image: {
      commonsFile: "File:Nou cementiri d'Igualada - 2014 - 02.JPG",
      photographer: 'Jordiferrer',
      license: 'CC BY-SA 4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Nou_cementiri_d%27Igualada_-_2014_-_02.JPG',
      width: 1600,
      height: 1200,
    },
    dossier: {
      en: 'Pinós and Miralles won the competition in 1984 and built the cemetery between 1985 and 1994. Instead of a walled enclosure on flat ground, they cut a shallow ravine into the hillside and made the retaining walls themselves the burial niches, so that the visitor walks downwards between the dead rather than past them; the Catalan name for the project, a riu de vides, a river of lives, describes the section rather than a metaphor. The concrete is left raw and the niche fronts rake outwards to shed rain and take flowers, which is why the wall reads as a set of tilted shelves rather than a grid. Weathering steel is used for gates and edges and rusts deliberately; timber railway sleepers are set into the ground plane in a loose scatter. The work is jointly authored — the standard credit is Miralles–Pinós — and it is often, wrongly, attributed to Miralles alone.',
      es: 'Pinós y Miralles ganaron el concurso en 1984 y construyeron el cementerio entre 1985 y 1994. En vez de un recinto amurallado en terreno llano, abrieron un barranco poco profundo en la ladera e hicieron que los propios muros de contención fueran los nichos, de modo que el visitante desciende entre los muertos en lugar de pasar junto a ellos; el nombre catalán del proyecto, un riu de vides, un río de vidas, describe la sección antes que una metáfora. El hormigón se deja en bruto y los frentes de los nichos se inclinan hacia fuera para evacuar el agua y recibir flores, y por eso el muro se lee como una serie de anaqueles volcados y no como una retícula. El acero corten se emplea en cancelas y remates y se oxida a propósito; traviesas de ferrocarril de madera aparecen dispersas en el plano del suelo. La obra es de autoría compartida —la firma habitual es Miralles-Pinós— y con frecuencia se atribuye, erróneamente, solo a Miralles.',
      it: "Pinós e Miralles vinsero il concorso nel 1984 e costruirono il cimitero fra il 1985 e il 1994. Invece di un recinto murato in piano, incisero un vallone poco profondo nel pendio e fecero dei muri di sostegno stessi i loculi, così che il visitatore scende fra i morti anziché passare loro accanto; il nome catalano del progetto, un riu de vides, un fiume di vite, descrive la sezione più che una metafora. Il calcestruzzo è lasciato grezzo e i fronti dei loculi si inclinano verso l'esterno per smaltire la pioggia e accogliere i fiori, ed è per questo che il muro si legge come una serie di mensole ribaltate e non come una griglia. L'acciaio corten è usato per cancelli e bordi e arrugginisce di proposito; traversine ferroviarie di legno affiorano sparse nel piano di calpestio. L'opera è a firma condivisa — la dicitura consueta è Miralles-Pinós — e viene spesso, a torto, attribuita al solo Miralles.",
    },
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q5994387', title: 'New Igualada Cemetery (Q5994387)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Igualada_Cemetery', title: 'Igualada Cemetery — Wikipedia', license: 'CC BY-SA 4.0' },
      { kind: 'institution', url: 'https://www.cpinos.com/', title: 'Estudio Carme Pinós', license: null },
    ],
    tier: 'canon',
  },
  {
    id: 'torres-blancas',
    wikidataId: 'Q3995702',
    name: {
      en: 'Torres Blancas',
      es: 'Torres Blancas',
      it: 'Torres Blancas',
    },
    architectId: 'francisco-javier-saenz-de-oiza',
    location: { city: 'Madrid', countryCode: 'ES', lat: 40.4397, lon: -3.67201 },
    inception: 1964,
    completed: 1969,
    demolished: null,
    typology: 'housing',
    materials: ['concrete'],
    structure: {
      en: 'Exposed reinforced concrete in which columns and beams are replaced by load-bearing cylindrical walls, a central shaft carrying the stair and services and the dwellings cantilevered off it as stacked drums.',
      es: 'Hormigón armado visto en el que pilares y vigas se sustituyen por muros portantes cilíndricos, con un fuste central que aloja escalera e instalaciones y las viviendas voladas desde él como tambores apilados.',
      it: 'Cemento armato a vista in cui pilastri e travi sono sostituiti da muri portanti cilindrici, con un fusto centrale che ospita scala e impianti e gli alloggi a sbalzo su di esso come tamburi impilati.',
    },
    program: {
      en: 'A speculative block of luxury apartments and offices with a rooftop pool, commissioned by the industrialist Juan Huarte on the Avenida de América.',
      es: 'Un bloque de apartamentos de lujo y oficinas con piscina en cubierta, promovido por el industrial Juan Huarte en la avenida de América.',
      it: "Un blocco di appartamenti di lusso e uffici con piscina in copertura, promosso dall'industriale Juan Huarte sull'avenida de América.",
    },
    heritage: 'regional',
    currentUse: {
      en: 'Still in mixed residential and office use, and listed by the City of Madrid among its singular buildings.',
      es: 'Sigue en uso mixto residencial y de oficinas, y figura entre los edificios singulares catalogados por el Ayuntamiento de Madrid.',
      it: "Ancora in uso misto residenziale e per uffici, e figura fra gli edifici singolari catalogati dal Comune di Madrid.",
    },
    detailRect: { x: 0.22, y: 0.32, w: 0.34, h: 0.22 },
    image: {
      commonsFile: 'File:Torres Blancas (Madrid) 04.jpg',
      photographer: 'Luis García (Zaqarbal)',
      license: 'CC BY-SA 3.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Torres_Blancas_(Madrid)_04.jpg',
      width: 1159,
      height: 1600,
    },
    dossier: {
      en: 'The name is a double misnomer: there is one tower, not two, and it is not white but bare grey concrete, because the client abandoned the intended cladding. Sáenz de Oíza designed it in 1961 for Juan Huarte, a builder who spent the 1960s financing the Spanish avant-garde, and it went up between 1964 and 1969 with the young Rafael Moneo among the collaborators and Carlos Fernández Casado as engineer. The organic ambition is literal. A single cylindrical shaft holds the stair, lifts and services like a trunk; the flats branch off it as circular drums that step in and out over twenty-one storeys, each with its own curved terrace, so no two floors have the same silhouette. There are no columns or beams in the usual sense — the cylinders themselves carry the load. On the roof are a swimming pool and a restaurant. It was the building that made Oíza’s reputation outside Spain.',
      es: 'El nombre falla dos veces: hay una sola torre, no dos, y no es blanca sino de hormigón gris visto, porque la propiedad renunció al revestimiento previsto. Sáenz de Oíza la proyectó en 1961 para Juan Huarte, un constructor que se pasó los años sesenta financiando la vanguardia española, y se levantó entre 1964 y 1969 con un joven Rafael Moneo entre los colaboradores y Carlos Fernández Casado como ingeniero. La ambición orgánica es literal. Un único fuste cilíndrico aloja escalera, ascensores e instalaciones como un tronco; las viviendas se ramifican desde él como tambores circulares que entran y salen a lo largo de veintiuna plantas, cada una con su terraza curva, de modo que no hay dos pisos con la misma silueta. No hay pilares ni vigas en el sentido habitual: los propios cilindros soportan la carga. En la cubierta hay piscina y restaurante. Fue el edificio que dio a Oíza su reputación fuera de España.',
      it: "Il nome sbaglia due volte: c'è una sola torre, non due, e non è bianca ma di calcestruzzo grigio a vista, perché la proprietà rinunciò al rivestimento previsto. Sáenz de Oíza la progettò nel 1961 per Juan Huarte, un costruttore che passò gli anni Sessanta a finanziare l'avanguardia spagnola, e fu eretta fra il 1964 e il 1969 con un giovane Rafael Moneo fra i collaboratori e Carlos Fernández Casado come ingegnere. L'ambizione organica è letterale. Un unico fusto cilindrico ospita scala, ascensori e impianti come un tronco; gli alloggi si ramificano da esso come tamburi circolari che entrano ed escono lungo ventun piani, ciascuno con la propria terrazza curva, sicché non ci sono due piani con la stessa sagoma. Non ci sono pilastri né travi nel senso consueto: sono i cilindri stessi a portare il carico. In copertura ci sono una piscina e un ristorante. Fu l'edificio che diede a Oíza la sua fama fuori dalla Spagna.",
    },
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q3995702', title: 'Torres Blancas (Q3995702)', license: null },
      { kind: 'wikipedia', url: 'https://es.wikipedia.org/wiki/Torres_Blancas', title: 'Torres Blancas — Wikipedia (es)', license: 'CC BY-SA 4.0' },
      { kind: 'institution', url: 'https://patrimonioypaisaje.madrid.es/portales/monumenta/es/Monumentos-y-Edificios-Singulares/Edificios-singulares/Torres-Blancas/', title: 'Torres Blancas — Patrimonio cultural y paisaje urbano, Ayuntamiento de Madrid', license: null },
    ],
    tier: 'canon',
  },
  {
    id: 'centro-de-creacion-contemporanea-de-andalucia',
    wikidataId: 'Q5839725',
    name: {
      en: 'Andalusian Centre for Contemporary Creation (C3A)',
      es: 'Centro de Creación Contemporánea de Andalucía (C3A)',
      it: 'Centro di Creazione Contemporanea di Andalusia (C3A)',
    },
    architectId: 'fuensanta-nieto',
    // Wikidata's P84 for this building (Q5839725) credits only the firm,
    // Nieto Sobejano Arquitectos, not either partner individually — the
    // dossier already states they are joint authors of everything the
    // office builds. `architectId` stays the pre-existing answer key
    // (Nieto); Sobejano is credited via the display-only co-credit.
    coArchitects: ['enrique-sobejano'],
    location: { city: 'Córdoba', countryCode: 'ES', lat: 37.87578, lon: -4.77186 },
    inception: 2008,
    completed: 2013,
    demolished: null,
    typology: 'cultural',
    materials: ['concrete'],
    structure: {
      en: 'A low concrete-framed volume of about 12,200 square metres over four levels, wrapped in precast panels moulded with a hexagonal relief whose recessed cells are opened as windows or fitted as a media façade.',
      es: 'Un volumen bajo de estructura de hormigón, de unos 12.200 metros cuadrados en cuatro niveles, envuelto en paneles prefabricados moldeados con un relieve hexagonal cuyas celdas rehundidas se abren como ventanas o se equipan como fachada mediática.',
      it: 'Un volume basso a struttura in calcestruzzo, di circa 12.200 metri quadrati su quattro livelli, avvolto da pannelli prefabbricati modellati con un rilievo esagonale le cui celle incassate si aprono come finestre o si attrezzano come facciata mediatica.',
    },
    program: {
      en: 'A production centre and museum for contemporary art on the south bank of the Guadalquivir, commissioned by the regional government of Andalusia.',
      es: 'Un centro de producción y museo de arte contemporáneo en la orilla sur del Guadalquivir, encargado por la Junta de Andalucía.',
      it: 'Un centro di produzione e museo di arte contemporanea sulla riva sud del Guadalquivir, commissionato dal governo regionale dell’Andalusia.',
    },
    heritage: 'none',
    currentUse: {
      en: 'A contemporary art centre run by the regional government of Andalusia, opened to the public in December 2016.',
      es: 'Centro de arte contemporáneo gestionado por la Junta de Andalucía, abierto al público en diciembre de 2016.',
      it: 'Centro di arte contemporanea gestito dal governo regionale dell’Andalusia, aperto al pubblico nel dicembre 2016.',
    },
    // Fix round: the previous rect ({x:0.16,y:0.12,w:0.30,h:0.24}) framed
    // mostly sky — re-downloaded the full-resolution file (5472x3648) and
    // re-cropped by hand. This rect sits over the dense band of hexagonal
    // precast-concrete relief on the near facade, including several
    // perforated cells revealing the glazing behind, which is the
    // diagnostic detail described in the dossier.
    detailRect: { x: 0.02, y: 0.27, w: 0.27, h: 0.25 },
    image: {
      commonsFile: 'File:Centro de Creación Contemporánea de Andalucía (52019071256).jpg',
      photographer: 'Kent Wang',
      license: 'CC BY-SA 2.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Centro_de_Creaci%C3%B3n_Contempor%C3%A1nea_de_Andaluc%C3%ADa_(52019071256).jpg',
      width: 1600,
      height: 1067,
    },
    dossier: {
      en: 'Nieto Sobejano — Fuensanta Nieto with Enrique Sobejano, joint authors of everything the office builds — set the centre on the far bank of the Guadalquivir, across the water from the historic city, on ground that turned up remains of Saqunda, the Umayyad suburb of Córdoba. The building keeps low, four levels including basement and roof, and does its work through a single device: a precast concrete skin moulded into a field of hexagons, some flat, some pressed into deep cells. Where a cell is opened it becomes a window; where it is fitted with lighting and video it becomes a screen facing the river. From a distance the wall reads as an abstract, almost tiled pattern; up close it is a piece of relief casting. Construction began in 2008 and finished at the end of 2013, but a dispute between the city and the regional government over who would build the approach roads delayed the opening until December 2016.',
      es: 'Nieto Sobejano —Fuensanta Nieto con Enrique Sobejano, autores conjuntos de todo lo que construye el estudio— situó el centro en la orilla opuesta del Guadalquivir, frente a la ciudad histórica, sobre un terreno que dio restos de Saqunda, el arrabal omeya de Córdoba. El edificio se mantiene bajo, cuatro niveles contando sótano y cubierta, y hace su trabajo mediante un solo recurso: una piel de hormigón prefabricado moldeada como un campo de hexágonos, unos planos y otros hundidos en celdas profundas. Donde una celda se abre, se convierte en ventana; donde se equipa con iluminación y vídeo, se convierte en pantalla hacia el río. De lejos el muro se lee como un patrón abstracto, casi de alicatado; de cerca es una pieza de fundición en relieve. Las obras empezaron en 2008 y concluyeron a finales de 2013, pero un desacuerdo entre el ayuntamiento y la Junta sobre quién urbanizaba los accesos retrasó la apertura hasta diciembre de 2016.',
      it: "Nieto Sobejano — Fuensanta Nieto con Enrique Sobejano, autori congiunti di tutto ciò che lo studio costruisce — collocò il centro sulla riva opposta del Guadalquivir, di fronte alla città storica, su un terreno che restituì resti di Saqunda, il sobborgo omayyade di Cordova. L'edificio resta basso, quattro livelli contando interrato e copertura, e lavora attraverso un solo espediente: una pelle di calcestruzzo prefabbricato modellata come un campo di esagoni, alcuni piani, altri affondati in celle profonde. Dove una cella si apre diventa finestra; dove è attrezzata con illuminazione e video diventa schermo verso il fiume. Da lontano il muro si legge come un motivo astratto, quasi un rivestimento ceramico; da vicino è un getto a rilievo. I lavori iniziarono nel 2008 e si conclusero alla fine del 2013, ma un contrasto fra comune e governo regionale su chi dovesse urbanizzare gli accessi ritardò l'apertura al dicembre 2016.",
    },
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q5839725', title: 'Centro de Creación Contemporánea de Andalucía (Q5839725)', license: null },
      { kind: 'wikipedia', url: 'https://es.wikipedia.org/wiki/Centro_de_Creaci%C3%B3n_Contempor%C3%A1nea_de_Andaluc%C3%ADa', title: 'Centro de Creación Contemporánea de Andalucía — Wikipedia (es)', license: 'CC BY-SA 4.0' },
      { kind: 'institution', url: 'http://www.c3a.es', title: 'Centro de Creación Contemporánea de Andalucía (C3A)', license: null },
    ],
    tier: 'deep',
  },
  {
    id: 'maat-lisboa',
    wikidataId: 'Q27522479',
    name: {
      en: 'Museum of Art, Architecture and Technology (MAAT)',
      es: 'Museo de Arte, Arquitectura y Tecnología (MAAT)',
      it: 'Museo di Arte, Architettura e Tecnologia (MAAT)',
    },
    architectId: 'amanda-levete',
    location: { city: 'Lisbon', countryCode: 'PT', lat: 38.69591, lon: -9.1935 },
    inception: 2011,
    completed: 2016,
    demolished: null,
    typology: 'cultural',
    materials: ['steel-and-glass', 'concrete'],
    structure: {
      en: 'A steel frame over a concrete substructure, no more than twelve metres high, carrying a long cantilevered arch above a column-free oval gallery and clad in some 15,000 crackle-glazed three-dimensional ceramic tiles.',
      es: 'Una estructura de acero sobre subestructura de hormigón, de no más de doce metros de altura, que sostiene un largo arco en voladizo sobre una galería oval sin pilares y se reviste con unos 15.000 azulejos cerámicos tridimensionales de vidriado craquelado.',
      it: 'Un telaio in acciaio su sottostruttura in calcestruzzo, alto non più di dodici metri, che regge un lungo arco a sbalzo sopra una galleria ovale priva di pilastri e rivestito con circa 15.000 piastrelle ceramiche tridimensionali a smalto craquelé.',
    },
    program: {
      en: 'A kunsthalle for the EDP Foundation on the Tagus at Belém, built as the new pole of an art campus around the disused Tejo power station.',
      es: 'Una kunsthalle para la Fundación EDP a orillas del Tajo, en Belém, levantada como nuevo polo de un campus artístico en torno a la central eléctrica del Tajo en desuso.',
      it: 'Una kunsthalle per la Fondazione EDP sul Tago a Belém, costruita come nuovo polo di un campus artistico attorno alla centrale elettrica del Tejo dismessa.',
    },
    heritage: 'none',
    currentUse: {
      en: 'A museum of art, architecture and technology run by the EDP Foundation, paired with the Central Tejo across a garden.',
      es: 'Museo de arte, arquitectura y tecnología gestionado por la Fundación EDP, emparejado con la Central Tejo a través de un jardín.',
      it: 'Museo di arte, architettura e tecnologia gestito dalla Fondazione EDP, accoppiato alla Central Tejo attraverso un giardino.',
    },
    detailRect: { x: 0.66, y: 0.18, w: 0.28, h: 0.34 },
    image: {
      commonsFile: 'File:The MAAT (34943440096).jpg',
      photographer: 'Susanne Nilsson',
      license: 'CC BY-SA 2.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:The_MAAT_(34943440096).jpg',
      width: 1600,
      height: 1066,
    },
    dossier: {
      en: 'Levete’s design for the EDP Foundation was published in 2011 and the building opened on 5 October 2016, at the start of the Lisbon Architecture Triennale; the German record notes that construction was formally completed only in March 2017. The brief was to reconnect Belém with the Tagus across a road and a railway, and the answer is a building you are meant to walk over rather than into. It stays under twelve metres so as not to block the historic quarter, and its roof is a continuous ramped surface reached by a footbridge, so the museum doubles as a public terrace facing the water. Beneath the cantilevered arch is a column-free oval gallery. The skin is the argument: roughly 15,000 white three-dimensional tiles, crackle-glazed, set to catch and scatter the light coming off the estuary — a modern reading of the azulejo that Lisbon has used on facades for four centuries.',
      es: 'El proyecto de Levete para la Fundación EDP se publicó en 2011 y el edificio se abrió el 5 de octubre de 2016, al inicio de la Trienal de Arquitectura de Lisboa; la ficha alemana precisa que la obra no se dio formalmente por terminada hasta marzo de 2017. El encargo era volver a coser Belém con el Tajo por encima de una avenida y una vía férrea, y la respuesta es un edificio por el que se pasa por arriba antes que por dentro. No supera los doce metros para no tapar el barrio histórico, y su cubierta es una superficie continua en rampa a la que se llega por una pasarela, de modo que el museo funciona además como terraza pública sobre el agua. Bajo el arco en voladizo hay una galería oval sin pilares. La piel es el argumento: unos 15.000 azulejos blancos tridimensionales, de vidriado craquelado, dispuestos para captar y dispersar la luz del estuario; una lectura moderna del azulejo con el que Lisboa lleva cuatro siglos revistiendo fachadas.',
      it: "Il progetto di Levete per la Fondazione EDP fu pubblicato nel 2011 e l'edificio aprì il 5 ottobre 2016, all'avvio della Triennale di Architettura di Lisbona; la scheda tedesca precisa che i lavori furono formalmente conclusi solo nel marzo 2017. Il tema era ricucire Belém con il Tago scavalcando una strada e una ferrovia, e la risposta è un edificio su cui si passa sopra prima che dentro. Non supera i dodici metri per non coprire il quartiere storico, e la sua copertura è una superficie continua in rampa raggiunta da una passerella, sicché il museo funziona anche come terrazza pubblica sull'acqua. Sotto l'arco a sbalzo si apre una galleria ovale priva di pilastri. La pelle è l'argomento: circa 15.000 piastrelle bianche tridimensionali a smalto craquelé, disposte per catturare e disperdere la luce dell'estuario; una lettura moderna dell'azulejo con cui Lisbona riveste facciate da quattro secoli.",
    },
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q27522479', title: 'Museum of Art, Architecture and Technology (Q27522479)', license: null },
      { kind: 'wikipedia', url: 'https://pt.wikipedia.org/wiki/Museu_de_Arte,_Arquitetura_e_Tecnologia', title: 'Museu de Arte, Arquitetura e Tecnologia — Wikipedia (pt)', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://de.wikipedia.org/wiki/Museu_de_Arte,_Arquitetura_e_Tecnologia', title: 'Museu de Arte, Arquitetura e Tecnologia — Wikipedia (de)', license: 'CC BY-SA 4.0' },
      { kind: 'institution', url: 'https://www.ala.uk.com/projects/maat/', title: 'MAAT — AL_A project page', license: null },
      { kind: 'publication', url: 'https://www.archiweb.cz/en/n/foreign/kulturni-centrum-v-lisabonu-od-amandy-levete', title: 'EDP Foundation Cultural Centre in Lisbon by Amanda Levete Architects, archiweb, 30 August 2011', license: null },
    ],
    tier: 'deep',
  },
];
