import type { Building } from '@/types/building';

// Wave 5 curator agent (Arabian Peninsula and Iraq): real, sourced Building entries for this slice.
//
// Every `image` below was checked against the live Commons file page on
// 2026-08-26: licence string, credited author and file-page URL are recorded
// verbatim from that page. Files carrying a `NoFoP-*` copyright warning or an
// "Incidental views of …" maintenance category were discarded rather than
// used, because none of the eight countries in this slice has a freedom-of-
// panorama exception and those tags say explicitly that cropping in on the
// depicted work is not permitted.
//
// `wikidataId: ''` marks a building for which no Wikidata item exists; it is
// a recorded gap, never a placeholder QID.
export const WESTASIA_GULF_BUILDINGS: Building[] = [
  {
    id: 'imam-dur-mausoleum',
    wikidataId: 'Q112788382',
    name: {
      en: 'Imam Dur Mausoleum',
      es: 'Mausoleo del Imán al-Dur',
      it: "Mausoleo dell'Imam al-Dur",
    },
    architectId: 'abu-shakir-ibn-abi-al-faraj',
    location: { city: 'Ad-Dawr', countryCode: 'IQ', lat: 34.4575, lon: 43.7983 },
    inception: 1085,
    completed: 1085,
    demolished: 2014,
    typology: 'sacral',
    materials: ['brick'],
    structure: {
      en: 'A square baked-brick chamber carrying a tall octagonal drum, above which the dome is built as three successively narrower octagons of muqarnas cells, each rotated slightly against the one below to spiral the shell upward to a small cupola.',
      es: 'Una cámara cuadrada de ladrillo cocido que sostiene un alto tambor octogonal, sobre el cual la cúpula se construye como tres octógonos sucesivamente más estrechos de celdas de mocárabes, cada uno girado ligeramente respecto al inferior para hacer ascender la cáscara en espiral hasta una pequeña linterna.',
      it: 'Una camera quadrata in mattoni cotti che regge un alto tamburo ottagonale, sopra il quale la cupola è costruita come tre ottagoni via via più stretti di celle di muqarnas, ciascuno ruotato di poco rispetto al sottostante così da far salire il guscio a spirale fino a una piccola lanterna.',
    },
    program: {
      en: 'A funerary shrine raised over the grave of Muhammad al-Dur, a descendant of the Prophet, and commissioned by the Uqaylid chamberlain Abu Jafar Muhammad; it served for nine centuries as a place of visitation.',
      es: 'Un santuario funerario levantado sobre la tumba de Muhammad al-Dur, descendiente del Profeta, por encargo del chambelán uqaylí Abu Yafar Muhammad; sirvió durante nueve siglos como lugar de visitación.',
      it: 'Un santuario funerario eretto sulla tomba di Muhammad al-Dur, discendente del Profeta, su commissione del ciambellano uqaylide Abu Ja\'far Muhammad; per nove secoli fu luogo di visitazione.',
    },
    heritage: 'national',
    currentUse: {
      en: 'Destroyed in 2014; the site is bare.',
      es: 'Destruido en 2014; el solar está vacío.',
      it: 'Distrutto nel 2014; il sito è spoglio.',
    },
    detailRect: { x: 0.3, y: 0.2, w: 0.36, h: 0.36 },
    image: {
      commonsFile: 'File:Muhammad Al-Durri Shrine.jpg',
      photographer: 'Mustafa Wahhudi',
      license: 'CC BY-SA 4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Muhammad_Al-Durri_Shrine.jpg',
      width: 640,
      height: 480,
    },
    dossier: {
      en: 'Twenty kilometres from Samarra, on the edge of the small town of Ad-Dawr, stood the single most consequential brick dome in Islamic architecture. Built around 1085 for the Uqaylid chamberlain Abu Jafar Muhammad and signed by its architect, Abu Shakir ibn Abi al-Faraj, the Imam Dur Mausoleum carried the earliest securely dated muqarnas dome anywhere. Muqarnas — the honeycomb of small niches that would become the defining ornament of Islamic building from Morocco to Samarkand — had appeared before as surface decoration; here it was made structural, stacked in three rotating octagonal tiers so that the whole shell corbels itself into a conical spiral. The chamber below is plain square brick with banded decoration, which only sharpens the contrast. For nine hundred years it survived Mongols, Ottomans and three modern wars. In October 2014 it was detonated.',
      es: 'A veinte kilómetros de Samarra, al borde de la pequeña ciudad de Ad-Dawr, se alzaba la cúpula de ladrillo más consecuente de toda la arquitectura islámica. Construido hacia 1085 para el chambelán uqaylí Abu Yafar Muhammad y firmado por su arquitecto, Abu Shakir ibn Abi al-Faraj, el mausoleo del Imán al-Dur albergaba la cúpula de mocárabes fechada con seguridad más antigua que se conoce. Los mocárabes —el panal de pequeñas trompas que acabaría siendo el ornamento definitorio de la construcción islámica desde Marruecos hasta Samarcanda— habían aparecido antes como decoración de superficie; aquí se vuelven estructura, apilados en tres registros octogonales girados de modo que la cáscara entera se voltea sobre sí misma en espiral cónica. La cámara inferior es ladrillo liso con fajas decoradas, lo que aún agudiza el contraste. Sobrevivió novecientos años a mongoles, otomanos y tres guerras modernas. En octubre de 2014 fue volado.',
      it: 'A venti chilometri da Samarra, ai margini della piccola città di Ad-Dawr, sorgeva la cupola in mattoni più decisiva di tutta l\'architettura islamica. Costruito verso il 1085 per il ciambellano uqaylide Abu Ja\'far Muhammad e firmato dal suo architetto, Abu Shakir ibn Abi al-Faraj, il mausoleo dell\'Imam al-Dur conservava la più antica cupola a muqarnas databile con certezza. I muqarnas — il favo di piccole nicchie che sarebbe divenuto l\'ornamento distintivo della costruzione islamica dal Marocco a Samarcanda — erano già comparsi come decorazione di superficie; qui diventano struttura, impilati in tre registri ottagonali ruotati così che l\'intero guscio si aggetti su sé stesso in una spirale conica. La camera sottostante è in mattoni lisci con fasce decorate, il che acuisce il contrasto. Sopravvisse novecento anni a mongoli, ottomani e tre guerre moderne. Nell\'ottobre 2014 fu fatto saltare.',
    },
    context: {
      body: {
        en: 'The Imam Dur Mausoleum was destroyed by explosives placed by the Islamic State of Iraq and the Levant on 23 October 2014, during the group\'s occupation of Salah ad-Din Governorate. It was one of a series of shrines and tombs in northern Iraq demolished in the same campaign, including the Mausoleum of Imam Awn al-Din in Mosul in July 2014. The building is gone; the photograph used here was taken in 2005 and is one of very few free-licensed images of it. Nothing has been rebuilt on the site.',
        es: 'El mausoleo del Imán al-Dur fue destruido con explosivos colocados por el Estado Islámico de Irak y el Levante el 23 de octubre de 2014, durante la ocupación de la gobernación de Salah ad-Din por ese grupo. Formó parte de una serie de santuarios y tumbas demolidos en el norte de Irak durante la misma campaña, entre ellos el mausoleo del Imán Awn al-Din en Mosul, en julio de 2014. El edificio ya no existe; la fotografía empleada aquí se tomó en 2005 y es una de las poquísimas imágenes suyas con licencia libre. Nada se ha reconstruido en el solar.',
        it: 'Il mausoleo dell\'Imam al-Dur fu distrutto con esplosivi collocati dallo Stato Islamico dell\'Iraq e del Levante il 23 ottobre 2014, durante l\'occupazione del governatorato di Salah ad-Din da parte del gruppo. Fu uno di una serie di santuari e tombe demoliti nel nord dell\'Iraq nella stessa campagna, fra cui il mausoleo dell\'Imam Awn al-Din a Mosul nel luglio 2014. L\'edificio non esiste più; la fotografia qui impiegata risale al 2005 ed è una delle pochissime immagini con licenza libera. Nulla è stato ricostruito sul sito.',
      },
      sources: [
        {
          kind: 'wikipedia',
          url: 'https://en.wikipedia.org/wiki/Imam_Dur_Mausoleum',
          title: 'Imam Dur Mausoleum',
          license: 'CC BY-SA 4.0',
        },
        {
          kind: 'wikipedia',
          url: 'https://en.wikipedia.org/wiki/Mausoleum_of_Imam_Awn_Al-Din',
          title: 'Mausoleum of Imam Awn Al-Din',
          license: 'CC BY-SA 4.0',
        },
      ],
    },
    sources: [
      {
        kind: 'wikidata',
        url: 'https://www.wikidata.org/wiki/Q112788382',
        title: 'Imam Dur Mausoleum (Q112788382)',
        license: null,
      },
      {
        kind: 'wikipedia',
        url: 'https://en.wikipedia.org/wiki/Imam_Dur_Mausoleum',
        title: 'Imam Dur Mausoleum',
        license: 'CC BY-SA 4.0',
      },
    ],
    tier: 'canon',
  },
  {
    id: 'al-muhdhar-minaret-tarim',
    wikidataId: 'Q10951815',
    name: {
      en: 'Al-Muhdhar Mosque Minaret',
      es: 'Alminar de la mezquita de Al-Muhdhar',
      it: 'Minareto della moschea di Al-Muhdhar',
    },
    architectId: 'awad-salman-afif-al-tarimi',
    location: { city: 'Tarim', countryCode: 'YE', lat: 16.054523, lon: 48.998379 },
    inception: 1914,
    completed: 1914,
    demolished: null,
    typology: 'sacral',
    materials: ['earth'],
    structure: {
      en: 'A square shaft of sun-dried mudbrick roughly fifty metres high, its walls thinning as they rise and rendered in whitewashed lime plaster, with an internal stair climbing the full height to the muezzin\'s gallery.',
      es: 'Un fuste cuadrado de adobe secado al sol de unos cincuenta metros de altura, con muros que adelgazan al ascender y revoco de cal encalado, y una escalera interior que sube toda la altura hasta la galería del almuecín.',
      it: 'Un fusto quadrato in mattoni crudi essiccati al sole, alto circa cinquanta metri, con muri che si assottigliano salendo e intonaco di calce imbiancato, e una scala interna che sale per tutta l\'altezza fino alla galleria del muezzin.',
    },
    program: {
      en: 'The minaret of a congregational mosque named for the fifteenth-century Tarimi scholar Umar al-Mihdar, added to the much older prayer hall as a civic landmark for the town.',
      es: 'El alminar de una mezquita congregacional dedicada al sabio tarimí del siglo XV Umar al-Mihdar, añadido a una sala de oración mucho más antigua como hito cívico de la ciudad.',
      it: 'Il minareto di una moschea congregazionale intitolata al dotto tarimita del XV secolo Umar al-Mihdar, aggiunto a una sala di preghiera molto più antica come emblema civico della città.',
    },
    heritage: 'national',
    currentUse: {
      en: 'In use as the minaret of a working congregational mosque.',
      es: 'En uso como alminar de una mezquita congregacional activa.',
      it: 'In uso come minareto di una moschea congregazionale attiva.',
    },
    detailRect: { x: 0.3, y: 0.32, w: 0.4, h: 0.28 },
    image: {
      commonsFile: 'File:Minaret Al Muhdhar Mosque Tarim Yemen.jpg',
      photographer: 'Jialiang Gao www.peace-on-earth.org',
      license: 'CC BY-SA 3.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Minaret_Al_Muhdhar_Mosque_Tarim_Yemen.jpg',
      width: 1000,
      height: 1500,
    },
    dossier: {
      en: 'Tarim, in the Wadi Hadhramaut, is a town of scholars and mudbrick towers, and around 1914 it acquired the tallest earthen structure in the world. The Al-Muhdhar Mosque itself is centuries older; the minaret is a modern addition, a square shaft of sun-dried brick rising some fifty metres and finished in white lime, with the stair wound inside the thickness of the wall. Published accounts name the builder as \'Awad Salman \'Afif al-Tarimi, a local master already practised in clay lattices and domes, working under the supervision of the scholar Abu Bakr bin Shihab. That attribution is what makes the building unusual here: Hadhrami earthen architecture is normally catalogued as anonymous vernacular, and the pool that results is poorer for it. Nothing about the construction is imported — the material was dug nearby and the labour was Tarimi.',
      es: 'Tarim, en el Wadi Hadramaut, es una ciudad de sabios y de torres de adobe, y hacia 1914 adquirió la construcción de tierra más alta del mundo. La mezquita de Al-Muhdhar es en sí mucho más antigua; el alminar es un añadido moderno, un fuste cuadrado de ladrillo secado al sol que se eleva unos cincuenta metros y se remata en cal blanca, con la escalera embebida en el espesor del muro. Las fuentes publicadas nombran como constructor a \'Awad Salman \'Afif al-Tarimi, un maestro local ya experto en celosías y cúpulas de barro, bajo la supervisión del sabio Abu Bakr bin Shihab. Esa atribución es lo que hace excepcional al edificio: la arquitectura de tierra hadramí suele catalogarse como vernácula anónima. Nada de la obra es importado: el material se extrajo al lado y la mano de obra era de Tarim.',
      it: 'Tarim, nel Wadi Hadramaut, è una città di dotti e di torri in terra cruda, e intorno al 1914 acquisì la più alta struttura in terra del mondo. La moschea di Al-Muhdhar è di per sé molto più antica; il minareto è un\'aggiunta moderna, un fusto quadrato di mattoni essiccati al sole che si eleva per una cinquantina di metri e si conclude in calce bianca, con la scala ricavata nello spessore del muro. Le fonti pubblicate indicano come costruttore \'Awad Salman \'Afif al-Tarimi, un maestro locale già esperto di grate e cupole in argilla, sotto la supervisione del dotto Abu Bakr bin Shihab. È questa attribuzione a rendere insolito l\'edificio: l\'architettura in terra hadramita viene di norma catalogata come vernacolo anonimo. Nulla della costruzione è importato: il materiale fu cavato lì accanto e la manodopera era di Tarim.',
    },
    context: null,
    sources: [
      {
        kind: 'wikidata',
        url: 'https://www.wikidata.org/wiki/Q10951815',
        title: 'Al-Muhdhar Mosque (Q10951815)',
        license: null,
      },
      {
        kind: 'wikipedia',
        url: 'https://en.wikipedia.org/wiki/Al-Muhdhar_Mosque',
        title: 'Al-Muhdhar Mosque',
        license: 'CC BY-SA 4.0',
      },
      {
        kind: 'wikipedia',
        url: 'https://en.wikipedia.org/wiki/Tarim,_Hadhramaut',
        title: 'Tarim, Hadhramaut',
        license: 'CC BY-SA 4.0',
      },
    ],
    tier: 'canon',
  },
  {
    id: 'basra-memorial',
    wikidataId: 'Q6967066',
    name: {
      en: 'Basra Memorial',
      es: 'Monumento Conmemorativo de Basora',
      it: 'Memoriale di Bassora',
    },
    architectId: 'edward-prioleau-warren',
    location: { city: 'Basra', countryCode: 'IQ', lat: 30.411472, lon: 47.545861 },
    inception: 1929,
    completed: 1929,
    demolished: null,
    typology: 'civic',
    materials: ['mixed'],
    structure: {
      en: 'A long colonnaded screen enclosing a court, its bays carrying sixty-eight inscribed panels and bronze name plaques, terminated at each end by a solid pavilion.',
      es: 'Una larga pantalla porticada que encierra un patio, con sesenta y ocho placas inscritas y planchas de bronce con los nombres repartidas entre sus vanos, rematada en cada extremo por un pabellón macizo.',
      it: 'Un lungo schermo colonnato che racchiude una corte, con sessantotto lastre iscritte e targhe bronzee con i nomi distribuite fra le campate, concluso a ciascuna estremità da un padiglione pieno.',
    },
    program: {
      en: 'A memorial built for the Imperial War Graves Commission to record 40,682 Commonwealth dead of the Mesopotamian campaign of 1914–1921 who have no known grave.',
      es: 'Un monumento construido para la Imperial War Graves Commission que recoge a 40.682 muertos de la Commonwealth en la campaña de Mesopotamia de 1914-1921 sin sepultura conocida.',
      it: 'Un memoriale costruito per la Imperial War Graves Commission che registra 40.682 caduti del Commonwealth della campagna di Mesopotamia del 1914-1921 privi di sepoltura nota.',
    },
    heritage: 'none',
    currentUse: {
      en: 'A war memorial, in poor repair and difficult to reach.',
      es: 'Un monumento a los caídos, en mal estado y de difícil acceso.',
      it: 'Un memoriale di guerra, in cattivo stato e difficile da raggiungere.',
    },
    detailRect: { x: 0.25, y: 0.35, w: 0.45, h: 0.3 },
    image: {
      commonsFile: 'File:Basra Memorial Side View.jpg',
      photographer: 'BMarinca',
      license: 'CC BY-SA 4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Basra_Memorial_Side_View.jpg',
      width: 1600,
      height: 1200,
    },
    dossier: {
      en: 'Unveiled in March 1929, the Basra Memorial is the Imperial War Graves Commission\'s record of the Mesopotamian campaign, in which Britain invaded Ottoman Iraq and then governed it under mandate. It names the missing of 1914 to 1921 across sixty-eight panels, and the way it names them is part of its history: of 40,682 dead commemorated, 7,385 British personnel and Indian officers are listed individually, while 33,256 Indian non-commissioned soldiers appear only by unit. Edward Prioleau Warren, an English Gothic Revivalist with almost no other work outside Britain, gave it a long stone-and-brick colonnade around a court. The building has since been moved once and left almost unvisitable, so that a monument built to make a war legible has itself become hard to read.',
      es: 'Inaugurado en marzo de 1929, el memorial de Basora es el registro que la Imperial War Graves Commission dedicó a la campaña de Mesopotamia, en la que Gran Bretaña invadió el Irak otomano y pasó luego a administrarlo bajo mandato. Nombra a los desaparecidos entre 1914 y 1921 en sesenta y ocho placas, y el modo de nombrarlos forma parte de su historia: de los 40.682 muertos conmemorados, 7.385 británicos y oficiales indios figuran uno a uno, mientras que 33.256 soldados indios de tropa aparecen sólo por unidad. Edward Prioleau Warren, neogótico inglés sin apenas obra fuera de Gran Bretaña, le dio una larga columnata de piedra y ladrillo en torno a un patio. Desde entonces ha sido trasladado una vez y dejado casi invisitable, de modo que un monumento levantado para hacer legible una guerra se ha vuelto él mismo difícil de leer.',
      it: 'Inaugurato nel marzo 1929, il memoriale di Bassora è il registro che la Imperial War Graves Commission dedicò alla campagna di Mesopotamia, nella quale la Gran Bretagna invase l\'Iraq ottomano per poi amministrarlo sotto mandato. Nomina i dispersi fra il 1914 e il 1921 su sessantotto lastre, e il modo in cui li nomina fa parte della sua storia: dei 40.682 caduti commemorati, 7.385 militari britannici e ufficiali indiani sono elencati uno per uno, mentre 33.256 soldati indiani di truppa compaiono solo per reparto. Edward Prioleau Warren, revivalista gotico inglese quasi privo di opere fuori dalla Gran Bretagna, gli diede un lungo colonnato in pietra e mattoni attorno a una corte. Da allora è stato spostato una volta e lasciato quasi invisitabile, così che un monumento eretto per rendere leggibile una guerra è divenuto esso stesso difficile da leggere.',
    },
    context: {
      body: {
        en: 'The memorial originally stood about eight kilometres north of Basra, near the Shatt al-Arab. In 1997 the Iraqi government moved the entire structure south-west, away from the river and onto ground that had been a battlefield of the 1991 Gulf War. The Commonwealth War Graves Commission lost regular access to the site during the wars that followed; the Daily Telegraph reported vandalism in 2013, with the Cross of Remembrance and a number of bronze plaques missing, and the surrounding land has been worked for gravel and sand. Around sixty-two of the sixty-eight panels are reported to survive and remain readable.',
        es: 'El monumento se alzaba originalmente unos ocho kilómetros al norte de Basora, junto al Shatt al-Arab. En 1997 el gobierno iraquí trasladó toda la estructura hacia el suroeste, lejos del río y a un terreno que había sido campo de batalla de la Guerra del Golfo de 1991. La Commonwealth War Graves Commission perdió el acceso regular al recinto durante las guerras posteriores; el Daily Telegraph informó de actos de vandalismo en 2013, con la desaparición de la Cruz del Sacrificio y de varias planchas de bronce, y el terreno circundante se ha explotado como cantera de grava y arena. Se informa de que sobreviven y siguen siendo legibles unas sesenta y dos de las sesenta y ocho placas.',
        it: 'Il memoriale sorgeva in origine a circa otto chilometri a nord di Bassora, presso lo Shatt al-Arab. Nel 1997 il governo iracheno spostò l\'intera struttura verso sud-ovest, lontano dal fiume e su un terreno che era stato campo di battaglia della Guerra del Golfo del 1991. La Commonwealth War Graves Commission perse l\'accesso regolare al sito durante le guerre successive; il Daily Telegraph riferì di atti vandalici nel 2013, con la scomparsa della Croce del Sacrificio e di diverse targhe bronzee, e il terreno circostante è stato sfruttato come cava di ghiaia e sabbia. Si riferisce che circa sessantadue delle sessantotto lastre sopravvivano e restino leggibili.',
      },
      sources: [
        {
          kind: 'wikipedia',
          url: 'https://en.wikipedia.org/wiki/Basra_Memorial',
          title: 'Basra Memorial',
          license: 'CC BY-SA 4.0',
        },
        {
          kind: 'wikidata',
          url: 'https://www.wikidata.org/wiki/Q6967066',
          title: 'Basra Memorial (Q6967066)',
          license: null,
        },
      ],
    },
    sources: [
      {
        kind: 'wikidata',
        url: 'https://www.wikidata.org/wiki/Q6967066',
        title: 'Basra Memorial (Q6967066)',
        license: null,
      },
      {
        kind: 'wikipedia',
        url: 'https://en.wikipedia.org/wiki/Basra_Memorial',
        title: 'Basra Memorial',
        license: 'CC BY-SA 4.0',
      },
    ],
    tier: 'deep',
  },
  {
    id: 'baghdad-royal-mausoleum',
    wikidataId: 'Q16128350',
    name: {
      en: 'Royal Mausoleum, Baghdad',
      es: 'Mausoleo Real de Bagdad',
      it: 'Mausoleo Reale di Baghdad',
    },
    architectId: 'j-brian-cooper',
    location: { city: 'Baghdad', countryCode: 'IQ', lat: 33.3655, lon: 44.3578 },
    inception: 1934,
    completed: 1936,
    demolished: null,
    typology: 'sacral',
    materials: ['stone', 'brick', 'timber'],
    structure: {
      en: 'Load-bearing walls of beach-stone boulders faced in brick, carrying three domes over a central hall and its flanking chambers, with doors and window frames in teak.',
      es: 'Muros de carga de cantos rodados de playa revestidos de ladrillo, que sostienen tres cúpulas sobre una sala central y sus cámaras laterales, con puertas y marcos de ventana en teca.',
      it: 'Muri portanti in ciottoli di spiaggia rivestiti di mattoni, che reggono tre cupole sopra una sala centrale e le camere laterali, con porte e telai delle finestre in teak.',
    },
    program: {
      en: 'A dynastic burial place commissioned by the Hashemite monarchy of Iraq for King Faisal I and his successors; nine members of the royal house and its government are interred there.',
      es: 'Un panteón dinástico encargado por la monarquía hachemí de Irak para el rey Faisal I y sus sucesores; allí reposan nueve miembros de la casa real y de su gobierno.',
      it: 'Un sepolcreto dinastico commissionato dalla monarchia hascemita dell\'Iraq per re Faysal I e i suoi successori; vi sono sepolti nove membri della casa reale e del suo governo.',
    },
    heritage: 'national',
    currentUse: {
      en: 'A royal cemetery, restored and reopened to visitors in 2021.',
      es: 'Un cementerio real, restaurado y reabierto a los visitantes en 2021.',
      it: 'Un cimitero reale, restaurato e riaperto ai visitatori nel 2021.',
    },
    detailRect: { x: 0.32, y: 0.22, w: 0.36, h: 0.36 },
    image: {
      commonsFile: 'File:Royal mausoleum in baghdad.jpg',
      photographer: 'David Stanley',
      license: 'CC BY 2.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Royal_mausoleum_in_baghdad.jpg',
      width: 1024,
      height: 768,
    },
    dossier: {
      en: 'Faisal I died in 1933, eleven years into a kingdom the British had built for him, and the mausoleum raised in Adhamiyah between 1934 and 1936 had to say what that kingdom was. J. Brian Cooper, the Englishman serving as the Hashemite state\'s official architect, gave it three tiled domes over a central hall, walls of beach stone faced in brick and teak joinery, and a scale that Elizabeth Bishop reads as borrowed from Britain\'s royal burial ground at Frogmore, consecrated only a few years earlier. Onto that frame he grafted Abbasid, Ottoman and pan-Arab motifs. The result is not a hybrid by accident: a post-Ottoman monarchy under British mandate needed a building that could claim descent from the caliphs and parity with European royalty at once, and Cooper built exactly that.',
      es: 'Faisal I murió en 1933, once años después de que los británicos le construyeran un reino, y el mausoleo levantado en Adhamiya entre 1934 y 1936 tenía que decir qué era ese reino. J. Brian Cooper, el inglés que ejercía de arquitecto oficial del Estado hachemí, le dio tres cúpulas alicatadas sobre una sala central, muros de canto rodado revestidos de ladrillo, carpintería de teca y una escala que Elizabeth Bishop lee como tomada del cementerio real británico de Frogmore, consagrado apenas unos años antes. Sobre ese armazón injertó motivos abasíes, otomanos y panárabes. El resultado no es híbrido por casualidad: una monarquía posotomana bajo mandato británico necesitaba un edificio capaz de reclamar a la vez descendencia de los califas y paridad con la realeza europea, y Cooper construyó exactamente eso.',
      it: 'Faysal I morì nel 1933, undici anni dopo che i britannici gli avevano costruito un regno, e il mausoleo eretto ad Adhamiya fra il 1934 e il 1936 doveva dire che cosa quel regno fosse. J. Brian Cooper, l\'inglese che fungeva da architetto ufficiale dello Stato hascemita, gli diede tre cupole rivestite di ceramica sopra una sala centrale, muri in ciottoli faccia a mattoni, serramenti in teak e una scala che Elizabeth Bishop legge come ripresa dal cimitero reale britannico di Frogmore, consacrato solo pochi anni prima. Su quell\'ossatura innestò motivi abbasidi, ottomani e panarabi. L\'esito non è ibrido per caso: una monarchia post-ottomana sotto mandato britannico aveva bisogno di un edificio capace di rivendicare insieme la discendenza dai califfi e la parità con le case regnanti europee, e Cooper costruì esattamente questo.',
    },
    context: {
      body: {
        en: 'The mausoleum is a monument of the Iraqi monarchy installed under the British Mandate, designed by a British architect employed by that monarchy, and its architectural sources were chosen accordingly. Elizabeth Bishop\'s 2022 study reads the central dome and the overall scale as drawn from the British Royal Burial Ground at Frogmore, set deliberately alongside Abbasid, Ottoman and Egyptian references — a design argument about where the new state placed itself. The monarchy was overthrown in the revolution of 1958 and the last king, Faisal II, was killed; he is buried here. The site was restored and reopened to the public on 27 March 2021.',
        es: 'El mausoleo es un monumento de la monarquía iraquí instaurada bajo el Mandato británico, proyectado por un arquitecto británico a su servicio, y sus fuentes arquitectónicas se eligieron en consecuencia. El estudio de Elizabeth Bishop de 2022 lee la cúpula central y la escala general como tomadas del cementerio real británico de Frogmore, deliberadamente confrontadas con referencias abasíes, otomanas y egipcias: un argumento de proyecto sobre dónde se situaba el nuevo Estado. La monarquía fue derrocada en la revolución de 1958 y el último rey, Faisal II, murió entonces; está enterrado aquí. El recinto fue restaurado y reabierto al público el 27 de marzo de 2021.',
        it: 'Il mausoleo è un monumento della monarchia irachena insediata sotto il Mandato britannico, progettato da un architetto britannico al suo servizio, e le sue fonti architettoniche furono scelte di conseguenza. Lo studio di Elizabeth Bishop del 2022 legge la cupola centrale e la scala complessiva come riprese dal cimitero reale britannico di Frogmore, deliberatamente accostate a riferimenti abbasidi, ottomani ed egiziani: un argomento progettuale su dove il nuovo Stato si collocasse. La monarchia fu rovesciata nella rivoluzione del 1958 e l\'ultimo re, Faysal II, vi perse la vita; è sepolto qui. Il complesso è stato restaurato e riaperto al pubblico il 27 marzo 2021.',
      },
      sources: [
        {
          kind: 'publication',
          url: 'https://is.urd.ac.ir/article_137619.html',
          title: 'Bishop, E. (2022), "Hashemite Royal Mausoleum in Baghdad: Multi-Faceted, Cosmopolitan, and Diverse Influences", Islamic Inquiries 1(1), 27–42',
          license: null,
        },
        {
          kind: 'wikipedia',
          url: 'https://en.wikipedia.org/wiki/Iraqi_Royal_Cemetery',
          title: 'Iraqi Royal Cemetery',
          license: 'CC BY-SA 4.0',
        },
      ],
    },
    sources: [
      {
        kind: 'wikidata',
        url: 'https://www.wikidata.org/wiki/Q16128350',
        title: 'Iraq Royal Cemetery (Q16128350)',
        license: null,
      },
      {
        kind: 'wikipedia',
        url: 'https://en.wikipedia.org/wiki/Iraqi_Royal_Cemetery',
        title: 'Iraqi Royal Cemetery',
        license: 'CC BY-SA 4.0',
      },
      {
        kind: 'publication',
        url: 'https://is.urd.ac.ir/article_137619.html',
        title: 'Bishop, E. (2022), "Hashemite Royal Mausoleum in Baghdad: Multi-Faceted, Cosmopolitan, and Diverse Influences", Islamic Inquiries 1(1), 27–42',
        license: null,
      },
    ],
    tier: 'deep',
  },
  {
    id: 'unknown-soldier-monument-baghdad-1959',
    wikidataId: 'Q108173951',
    name: {
      en: 'Monument to the Unknown Soldier (1959)',
      es: 'Monumento al Soldado Desconocido (1959)',
      it: 'Monumento al Milite Ignoto (1959)',
    },
    architectId: 'rifat-chadirji',
    location: { city: 'Baghdad', countryCode: 'IQ', lat: 33.314729, lon: 44.420825 },
    inception: 1959,
    completed: 1959,
    demolished: 1982,
    typology: 'civic',
    materials: ['concrete'],
    structure: {
      en: 'A single sweeping shell of reinforced concrete, a pointed arch pulled into three dimensions, springing from a raised circular platform and covering an open memorial chamber.',
      es: 'Una única cáscara de hormigón armado, un arco apuntado llevado a las tres dimensiones, que arranca de una plataforma circular elevada y cubre una cámara conmemorativa abierta.',
      it: 'Un unico guscio di cemento armato, un arco acuto portato nelle tre dimensioni, che si imposta su una piattaforma circolare rialzata e copre una camera commemorativa aperta.',
    },
    program: {
      en: 'A national monument commissioned in the first year of the Iraqi republic to commemorate the unknown dead of the army, set in a public square in central Baghdad.',
      es: 'Un monumento nacional encargado en el primer año de la república iraquí para conmemorar a los muertos anónimos del ejército, situado en una plaza pública del centro de Bagdad.',
      it: 'Un monumento nazionale commissionato nel primo anno della repubblica irachena per commemorare i caduti ignoti dell\'esercito, collocato in una piazza pubblica nel centro di Baghdad.',
    },
    heritage: 'none',
    currentUse: {
      en: 'Demolished in 1982; the square it stood in is now Firdos Square.',
      es: 'Demolido en 1982; la plaza que ocupaba es hoy la plaza Firdos.',
      it: 'Demolito nel 1982; la piazza che occupava è oggi piazza Firdos.',
    },
    detailRect: { x: 0.3, y: 0.3, w: 0.38, h: 0.34 },
    image: {
      commonsFile: 'File:Monument to the Unknown Soldier, Baghdad.jpg',
      photographer: 'Iraqi Post',
      license: 'PD',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Monument_to_the_Unknown_Soldier,_Baghdad.jpg',
      width: 1600,
      height: 1120,
    },
    dossier: {
      en: 'The Iraqi monarchy fell in July 1958; within a year the new republic had commissioned a monument to its unknown soldier, and Rifat Chadirji, then thirty-two, built it. He took the pointed arch of Iraqi building and pulled it out of the wall into a free-standing concrete shell, so that the oldest form in the region\'s architecture arrived as a piece of mid-century engineering with nothing behind it but sky. It stood on a raised circular platform in a central Baghdad square, an open room with no walls, and it became the image of what a republican Iraq thought it looked like. It lasted twenty-three years. This photograph comes from a 1960s postcard issued by the Iraqi postal service, which is now among the few free-licensed records of the building.',
      es: 'La monarquía iraquí cayó en julio de 1958; antes de un año la nueva república había encargado un monumento a su soldado desconocido, y Rifat Chadirji, con treinta y dos años, lo construyó. Tomó el arco apuntado de la arquitectura iraquí y lo extrajo del muro hasta convertirlo en una cáscara exenta de hormigón, de modo que la forma más antigua de la región llegaba como una pieza de ingeniería de mediados de siglo sin nada detrás salvo el cielo. Se alzaba sobre una plataforma circular elevada en una plaza del centro de Bagdad: una habitación abierta y sin muros que se convirtió en la imagen de cómo el Irak republicano creía verse. Duró veintitrés años. Esta fotografía procede de una postal de los años sesenta emitida por el servicio postal iraquí, hoy uno de los pocos registros libres del edificio.',
      it: 'La monarchia irachena cadde nel luglio 1958; entro un anno la nuova repubblica aveva commissionato un monumento al proprio milite ignoto, e Rifat Chadirji, allora trentaduenne, lo costruì. Prese l\'arco acuto dell\'edilizia irachena e lo estrasse dal muro fino a farne un guscio isolato di cemento, così che la forma più antica della regione arrivava come un pezzo di ingegneria di metà secolo con nulla dietro se non il cielo. Sorgeva su una piattaforma circolare rialzata in una piazza del centro di Baghdad: una stanza aperta e senza pareti, divenuta l\'immagine di come l\'Iraq repubblicano credeva di apparire. Durò ventitré anni. Questa fotografia proviene da una cartolina degli anni Sessanta emessa dal servizio postale iracheno, oggi una delle poche testimonianze con licenza libera dell\'edificio.',
    },
    context: {
      body: {
        en: 'Chadirji\'s monument was removed in 1982 on the order of Saddam Hussein, two years into the Iran–Iraq War, and its commemorative function was transferred to a new and much larger Monument to the Unknown Soldier built between 1979 and 1982 in the Grand Festivities Square, designed by the Italian architect Marcello D\'Olivo from a concept by the Iraqi sculptor Khaled al-Rahal. Chadirji, who had been imprisoned by the same government from 1978 to 1980 and was working as its consultant on Baghdad city planning when the demolition took place, was photographed at the site with the contractor who removed it. The square where it stood, Firdos Square, later carried a statue of Saddam Hussein, pulled down in April 2003.',
        es: 'El monumento de Chadirji fue retirado en 1982 por orden de Sadam Husein, con la guerra Irán-Irak ya en su tercer año, y su función conmemorativa se trasladó a un Monumento al Soldado Desconocido nuevo y mucho mayor, construido entre 1979 y 1982 en la Plaza de las Grandes Celebraciones, proyectado por el arquitecto italiano Marcello D\'Olivo a partir de una idea del escultor iraquí Khaled al-Rahal. Chadirji, encarcelado por ese mismo gobierno entre 1978 y 1980 y que trabajaba entonces como su consultor de planeamiento urbano de Bagdad, fue fotografiado en el lugar junto al contratista que lo desmontó. La plaza que ocupaba, la plaza Firdos, albergó después una estatua de Sadam Husein, derribada en abril de 2003.',
        it: 'Il monumento di Chadirji fu rimosso nel 1982 per ordine di Saddam Hussein, con la guerra Iran-Iraq già al terzo anno, e la sua funzione commemorativa fu trasferita a un nuovo e assai più grande Monumento al Milite Ignoto, costruito fra il 1979 e il 1982 nella Piazza delle Grandi Celebrazioni, progettato dall\'architetto italiano Marcello D\'Olivo su un\'idea dello scultore iracheno Khaled al-Rahal. Chadirji, imprigionato dallo stesso governo fra il 1978 e il 1980 e allora suo consulente per la pianificazione urbanistica di Baghdad, fu fotografato sul posto insieme all\'impresario che lo smontò. La piazza che occupava, piazza Firdos, ospitò in seguito una statua di Saddam Hussein, abbattuta nell\'aprile 2003.',
      },
      sources: [
        {
          kind: 'wikipedia',
          url: 'https://en.wikipedia.org/wiki/Rifat_Chadirji',
          title: 'Rifat Chadirji',
          license: 'CC BY-SA 4.0',
        },
        {
          kind: 'wikipedia',
          url: 'https://en.wikipedia.org/wiki/Monument_to_the_Unknown_Soldier,_Baghdad',
          title: 'Monument to the Unknown Soldier, Baghdad (the 1979–1982 replacement)',
          license: 'CC BY-SA 4.0',
        },
        {
          kind: 'publication',
          url: 'https://round-city.com/rifat-chadirji-10-buildings-and-the-stories-behind-them/',
          title: 'Round City, "Rifat Chadirji: 10 buildings and the stories behind them"',
          license: null,
        },
      ],
    },
    sources: [
      {
        kind: 'wikidata',
        url: 'https://www.wikidata.org/wiki/Q108173951',
        title: 'Unknown Soldier Monument (Q108173951)',
        license: null,
      },
      {
        kind: 'institution',
        url: 'https://www.archnet.org/sites/693',
        title: 'Archnet — Unknown Soldier Monument, Baghdad, Iraq',
        license: null,
      },
      {
        kind: 'wikipedia',
        url: 'https://en.wikipedia.org/wiki/Rifat_Chadirji',
        title: 'Rifat Chadirji',
        license: 'CC BY-SA 4.0',
      },
    ],
    tier: 'canon',
  },
  {
    id: 'al-khulafa-mosque-baghdad',
    wikidataId: 'Q12204233',
    name: {
      en: 'Al-Khulafa Mosque',
      es: 'Mezquita de Al-Khulafa',
      it: 'Moschea di Al-Khulafa',
    },
    architectId: 'mohamed-makiya',
    location: { city: 'Baghdad', countryCode: 'IQ', lat: 33.339123, lon: 44.397691 },
    inception: 1960,
    completed: 1963,
    demolished: null,
    typology: 'sacral',
    materials: ['brick', 'concrete'],
    structure: {
      en: 'A domed prayer hall and three brick riwaqs set around a sahn, all sized and placed against the surviving thirteenth-century minaret, which stands in a sunken court at the south-east corner.',
      es: 'Una sala de oración cupulada y tres riwaq de ladrillo dispuestos en torno a un sahn, todos dimensionados y situados en relación con el alminar del siglo XIII que se conserva, alzado en un patio hundido en el ángulo sudeste.',
      it: 'Una sala di preghiera a cupola e tre riwaq in mattoni disposti attorno a un sahn, tutti dimensionati e collocati in rapporto al superstite minareto duecentesco, che sorge in un cortile ribassato all\'angolo sud-est.',
    },
    program: {
      en: 'A Friday mosque commissioned by the Iraqi Ministry of Awqaf on the site of a tenth-century Abbasid foundation, required to incorporate the one medieval element still standing.',
      es: 'Una mezquita aljama encargada por el Ministerio iraquí de Waqfs sobre el emplazamiento de una fundación abasí del siglo X, con la obligación de integrar el único elemento medieval en pie.',
      it: 'Una moschea del venerdì commissionata dal Ministero iracheno degli Awqaf sul sito di una fondazione abbaside del X secolo, con l\'obbligo di incorporare l\'unico elemento medievale ancora in piedi.',
    },
    heritage: 'national',
    currentUse: {
      en: 'A congregational mosque in central Baghdad.',
      es: 'Una mezquita congregacional en el centro de Bagdad.',
      it: 'Una moschea congregazionale nel centro di Baghdad.',
    },
    detailRect: { x: 0.55, y: 0.35, w: 0.16, h: 0.28 },
    image: {
      commonsFile: 'File:مسجد الخلفاء في بغداد.jpg',
      photographer: 'Osamah Ibrahim',
      license: 'CC BY-SA 3.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:%D9%85%D8%B3%D8%AC%D8%AF_%D8%A7%D9%84%D8%AE%D9%84%D9%81%D8%A7%D8%A1_%D9%81%D9%8A_%D8%A8%D8%BA%D8%AF%D8%A7%D8%AF.jpg',
      width: 1600,
      height: 1200,
    },
    dossier: {
      en: 'In 1960 the Ministry of Awqaf handed Mohamed Makiya his first major public commission and a difficult brief: build a Friday mosque on the site of a tenth-century Abbasid foundation near the Suq al-Ghazl, and keep the thirteenth-century minaret that is the only medieval fabric left in Baghdad from the caliphate. Makiya fought for two years, unsuccessfully, to enlarge the cramped site. What he built instead is a set of separate pieces — a domed prayer hall and three brick porticoes — each sized and positioned against the minaret, which he set in a sunken court so that its base could be read. The brickwork answers the medieval shaft\'s muqarnas galleries without imitating them. It is the founding statement of the argument Makiya spent fifty years making.',
      es: 'En 1960 el Ministerio de Waqfs entregó a Mohamed Makiya su primer gran encargo público con un programa difícil: construir una mezquita aljama sobre el solar de una fundación abasí del siglo X junto al Suq al-Ghazl, conservando el alminar del siglo XIII, único resto medieval del califato que queda en pie en Bagdad. Makiya peleó dos años, sin éxito, por ampliar el estrecho solar. Lo que levantó en su lugar es un conjunto de piezas separadas —una sala de oración cupulada y tres pórticos de ladrillo— dimensionadas y situadas todas en relación con el alminar, que hundió en un patio para que pudiera leerse su base. La fábrica de ladrillo responde a las galerías de mocárabes del fuste medieval sin imitarlas. Es el enunciado fundacional del argumento que Makiya defendió durante cincuenta años.',
      it: 'Nel 1960 il Ministero degli Awqaf affidò a Mohamed Makiya la sua prima grande commissione pubblica con un programma difficile: costruire una moschea del venerdì sul sito di una fondazione abbaside del X secolo presso il Suq al-Ghazl, conservando il minareto duecentesco, unica fabbrica medievale del califfato rimasta in piedi a Baghdad. Makiya lottò due anni, senza successo, per ampliare l\'angusto lotto. Ciò che costruì è invece un insieme di pezzi distinti — una sala di preghiera a cupola e tre portici in mattoni — tutti dimensionati e collocati in rapporto al minareto, che ribassò in un cortile perché se ne potesse leggere la base. La muratura in mattoni risponde alle gallerie a muqarnas del fusto medievale senza imitarle. È l\'enunciato fondativo della tesi che Makiya sostenne per cinquant\'anni.',
    },
    context: {
      body: {
        en: 'The Khulafa Mosque belongs to the building programme of the Iraqi Development Board, which in the 1950s spent oil revenue on a modern capital and commissioned foreign architects on an extraordinary scale: Frank Lloyd Wright produced an unbuilt plan for a Baghdad opera house and cultural centre, Walter Gropius and The Architects Collaborative designed the University of Baghdad, Gio Ponti built the Development Board\'s own headquarters, and Le Corbusier\'s gymnasium was completed posthumously in 1980. Iraqi architects — Makiya, Rifat Chadirji, Hisham Munir, Qahtan Awni, Ellen and Nizar Jawdat — worked alongside and against that programme, and it was Nizar Jawdat\'s family connections that brought Gropius to Baghdad in the first place.',
        es: 'La mezquita de Al-Khulafa pertenece al programa constructivo de la Junta de Desarrollo iraquí, que en los años cincuenta destinó los ingresos del petróleo a una capital moderna y contrató arquitectos extranjeros a una escala extraordinaria: Frank Lloyd Wright proyectó un plan nunca construido para una ópera y un centro cultural de Bagdad, Walter Gropius y The Architects Collaborative diseñaron la Universidad de Bagdad, Gio Ponti levantó la sede de la propia Junta de Desarrollo y el gimnasio de Le Corbusier se terminó póstumamente en 1980. Los arquitectos iraquíes —Makiya, Rifat Chadirji, Hisham Munir, Qahtan Awni, Ellen y Nizar Jawdat— trabajaron junto a ese programa y frente a él, y fueron los contactos familiares de Nizar Jawdat los que llevaron a Gropius a Bagdad.',
        it: 'La moschea di Al-Khulafa appartiene al programma edilizio del Development Board iracheno, che negli anni Cinquanta destinò le entrate petrolifere a una capitale moderna e ingaggiò architetti stranieri su scala straordinaria: Frank Lloyd Wright elaborò un piano mai costruito per un teatro d\'opera e un centro culturale a Baghdad, Walter Gropius e The Architects Collaborative progettarono l\'Università di Baghdad, Gio Ponti realizzò la sede dello stesso Development Board e la palestra di Le Corbusier fu completata postuma nel 1980. Gli architetti iracheni — Makiya, Rifat Chadirji, Hisham Munir, Qahtan Awni, Ellen e Nizar Jawdat — lavorarono accanto a quel programma e contro di esso, e furono i legami familiari di Nizar Jawdat a portare Gropius a Baghdad.',
      },
      sources: [
        {
          kind: 'publication',
          url: 'https://www.bidoun.org/articles/mohamed-makiya',
          title: 'Bidoun, "Mohamed Makiya: Deeply Baghdadi"',
          license: null,
        },
        {
          kind: 'publication',
          url: 'https://hpa.unibo.it/article/view/12154',
          title: 'Histories of Postwar Architecture, "Genius versus Expertise. Frank Lloyd Wright and The Architects Collaborative at the University of Baghdad"',
          license: null,
        },
      ],
    },
    sources: [
      {
        kind: 'wikidata',
        url: 'https://www.wikidata.org/wiki/Q12204233',
        title: 'AlKhulafa Mosque (Q12204233)',
        license: null,
      },
      {
        kind: 'institution',
        url: 'https://www.archnet.org/sites/27',
        title: "Archnet — Jami' al-Khulafa, Baghdad, Iraq",
        license: null,
      },
      {
        kind: 'publication',
        url: 'https://www.bidoun.org/articles/mohamed-makiya',
        title: 'Bidoun, "Mohamed Makiya: Deeply Baghdadi"',
        license: null,
      },
    ],
    tier: 'canon',
  },
  {
    id: 'federation-of-industries-building-baghdad',
    wikidataId: '',
    name: {
      en: 'Federation of Industries Building',
      es: 'Edificio de la Federación de Industrias',
      it: 'Palazzo della Federazione delle Industrie',
    },
    architectId: 'rifat-chadirji',
    location: { city: 'Baghdad', countryCode: 'IQ', lat: 33.3336, lon: 44.4045 },
    inception: 1966,
    completed: 1966,
    demolished: null,
    typology: 'civic',
    materials: ['brick', 'concrete'],
    structure: {
      en: 'A reinforced-concrete frame of ordinary office floors screened by a free-standing brick outer wall of projecting balconies and vertical panels, held clear of the glazing so that it shades rather than encloses.',
      es: 'Una estructura de hormigón armado con plantas de oficina corrientes, protegida por un muro exterior exento de ladrillo hecho de balcones volados y paños verticales, separado del acristalamiento de modo que da sombra en lugar de cerrar.',
      it: 'Un telaio in cemento armato con normali piani per uffici, schermato da un muro esterno indipendente in mattoni fatto di balconi aggettanti e pannelli verticali, staccato dalle vetrate così da ombreggiare anziché racchiudere.',
    },
    program: {
      en: 'Headquarters offices for the Iraqi Federation of Industries, on a dense commercial site near Khallani Square in central Baghdad.',
      es: 'Oficinas centrales de la Federación de Industrias de Irak, en un solar comercial denso junto a la plaza Khallani, en el centro de Bagdad.',
      it: 'Uffici direzionali della Federazione delle Industrie irachena, su un lotto commerciale denso presso piazza Khallani, nel centro di Baghdad.',
    },
    heritage: 'none',
    currentUse: {
      en: 'Offices.',
      es: 'Oficinas.',
      it: 'Uffici.',
    },
    detailRect: { x: 0.3, y: 0.3, w: 0.38, h: 0.34 },
    image: {
      commonsFile: 'File:مبنى اتحاد الصناعات العراقي.jpg',
      photographer: 'Mohammad Ali Huzam',
      license: 'CC BY-SA 4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:%D9%85%D8%A8%D9%86%D9%89_%D8%A7%D8%AA%D8%AD%D8%A7%D8%AF_%D8%A7%D9%84%D8%B5%D9%86%D8%A7%D8%B9%D8%A7%D8%AA_%D8%A7%D9%84%D8%B9%D8%B1%D8%A7%D9%82%D9%8A.jpg',
      width: 1600,
      height: 1393,
    },
    dossier: {
      en: 'Behind the Federation of Industries building is an ordinary stack of office floors. In front of it Rifat Chadirji hung what he called a flying wall: a free-standing brick screen of projecting balconies and vertical fins, held off the glass, reading from the street as a rhythm of arches and points, protrusions and voids. The device is borrowed from the traditional Baghdadi house, where the shaded outer layer does the environmental work; here it also hides the repetition of the plan and gives a speculative office block the weight of a public building. Chadirji built it in 1966, at the height of his practice Iraq Consult, and it remains the clearest surviving demonstration of what he meant by international regionalism: modern construction, regional shadow.',
      es: 'Detrás del edificio de la Federación de Industrias hay un apilamiento corriente de plantas de oficina. Delante, Rifat Chadirji colgó lo que llamó un muro volante: una pantalla exenta de ladrillo hecha de balcones volados y aletas verticales, separada del vidrio, que desde la calle se lee como un ritmo de arcos y puntas, salientes y vacíos. El recurso procede de la casa tradicional bagdadí, donde la capa exterior sombreada hace el trabajo ambiental; aquí oculta además la repetición de la planta y da a un bloque de oficinas especulativo el peso de un edificio público. Chadirji lo construyó en 1966, en el apogeo de su estudio Iraq Consult, y sigue siendo la demostración conservada más clara de lo que entendía por regionalismo internacional: construcción moderna, sombra regional.',
      it: 'Dietro il palazzo della Federazione delle Industrie c\'è una comune pila di piani per uffici. Davanti, Rifat Chadirji appese quello che chiamava un muro volante: uno schermo indipendente in mattoni fatto di balconi aggettanti e lame verticali, staccato dal vetro, che dalla strada si legge come un ritmo di archi e punte, sporgenze e vuoti. L\'espediente deriva dalla casa tradizionale baghdadi, dove lo strato esterno ombreggiato svolge il lavoro ambientale; qui nasconde inoltre la ripetizione della pianta e conferisce a un blocco di uffici speculativo il peso di un edificio pubblico. Chadirji lo costruì nel 1966, al culmine del suo studio Iraq Consult, e resta la dimostrazione superstite più chiara di ciò che intendeva per regionalismo internazionale: costruzione moderna, ombra regionale.',
    },
    context: null,
    sources: [
      {
        kind: 'publication',
        url: 'https://round-city.com/rifat-chadirji-10-buildings-and-the-stories-behind-them/',
        title: 'Round City, "Rifat Chadirji: 10 buildings and the stories behind them"',
        license: null,
      },
      {
        kind: 'publication',
        url: 'https://www.architecturalrecord.com/articles/12030-the-life-and-work-of-iraqs-most-influential-modernist-architect-in-photographs',
        title: 'Architectural Record, "The Life and Work of Iraq\'s Most Influential Modernist Architect, In Photographs" (22 November 2016)',
        license: null,
      },
      {
        kind: 'wikipedia',
        url: 'https://en.wikipedia.org/wiki/Rifat_Chadirji',
        title: 'Rifat Chadirji',
        license: 'CC BY-SA 4.0',
      },
    ],
    tier: 'canon',
  },
  {
    id: 'kuwait-towers',
    wikidataId: 'Q1335640',
    name: {
      en: 'Kuwait Towers',
      es: 'Torres de Kuwait',
      it: 'Kuwait Towers',
    },
    architectId: 'malene-bjorn',
    location: { city: 'Kuwait City', countryCode: 'KW', lat: 29.39, lon: 48.003056 },
    inception: 1971,
    completed: 1976,
    demolished: null,
    typology: 'tower',
    materials: ['concrete'],
    structure: {
      en: 'Three tapering shafts of prestressed and reinforced concrete on a reclaimed headland, the two taller ones threaded through spheres clad in some forty-one thousand enamelled steel discs; the upper sphere of the main shaft rotates.',
      es: 'Tres fustes ahusados de hormigón armado y pretensado sobre una punta ganada al mar; los dos más altos están ensartados por esferas revestidas con unos cuarenta y un mil discos de acero esmaltado, y la esfera superior del fuste principal gira.',
      it: 'Tre fusti rastremati in cemento armato e precompresso su un promontorio bonificato; i due più alti sono infilzati da sfere rivestite con circa quarantunomila dischi di acciaio smaltato, e la sfera superiore del fusto principale ruota.',
    },
    program: {
      en: 'Water storage for Kuwait City, commissioned by the state as the sixth group in a national water-tower programme, with a restaurant and a revolving observation deck added in the spheres.',
      es: 'Almacenamiento de agua para la ciudad de Kuwait, encargado por el Estado como sexto grupo de un programa nacional de depósitos elevados, con un restaurante y un mirador giratorio alojados en las esferas.',
      it: 'Riserva idrica per Kuwait City, commissionata dallo Stato come sesto gruppo di un programma nazionale di serbatoi pensili, con un ristorante e una terrazza panoramica girevole alloggiati nelle sfere.',
    },
    heritage: 'none',
    currentUse: {
      en: 'Water storage, restaurant and public observation deck; reopened in March 2016 after a four-year refurbishment.',
      es: 'Depósito de agua, restaurante y mirador público; reabiertas en marzo de 2016 tras cuatro años de reforma.',
      it: 'Riserva idrica, ristorante e terrazza panoramica pubblica; riaperte nel marzo 2016 dopo quattro anni di lavori.',
    },
    detailRect: { x: 0.17, y: 0.28, w: 0.18, h: 0.29 },
    image: {
      commonsFile: 'File:Kuwait tower at dusk.jpg',
      photographer: 'Samarstha45',
      license: 'CC BY-SA 4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Kuwait_tower_at_dusk.jpg',
      width: 1600,
      height: 1200,
    },
    dossier: {
      en: 'The Kuwait Towers began as plumbing. The Swedish firm VBB was building the water supply of a country transformed by oil, and its chief architect Sune Lindström had already put up five groups of blunt mushroom-headed reservoirs when the Emir asked for something better at the sixth site. Lindström\'s wife, the Danish designer Malene Bjørn, produced ten schemes; three went to the ruler and one was built between 1971 and 1976. Three concrete shafts rise from a reclaimed headland, two of them pierced by spheres skinned in some forty-one thousand enamelled steel discs in eight blues, greens and greys, spiralled in a pattern that recalls a tiled dome. The lower sphere holds a tank and a restaurant; the upper one turns. A water tower became the emblem on the currency.',
      es: 'Las Torres de Kuwait empezaron siendo fontanería. La empresa sueca VBB construía el abastecimiento de agua de un país transformado por el petróleo, y su jefe de arquitectura, Sune Lindström, había levantado ya cinco grupos de depósitos romos en forma de seta cuando el emir pidió algo mejor para el sexto emplazamiento. La esposa de Lindström, la diseñadora danesa Malene Bjørn, preparó diez propuestas; tres llegaron al gobernante y una se construyó entre 1971 y 1976. Tres fustes de hormigón se alzan sobre una punta ganada al mar; dos están atravesados por esferas revestidas con unos cuarenta y un mil discos de acero esmaltado en ocho tonos de azul, verde y gris, dispuestos en espiral como los alicatados de una cúpula. La esfera baja aloja un depósito y un restaurante; la alta gira. Un depósito de agua acabó en los billetes.',
      it: 'Le Kuwait Towers nacquero come impianto idraulico. L\'impresa svedese VBB stava realizzando l\'acquedotto di un paese trasformato dal petrolio, e il suo capo architetto Sune Lindström aveva già eretto cinque gruppi di tozzi serbatoi a fungo quando l\'emiro chiese qualcosa di meglio per il sesto sito. La moglie di Lindström, la designer danese Malene Bjørn, elaborò dieci soluzioni; tre giunsero al sovrano e una fu costruita fra il 1971 e il 1976. Tre fusti di cemento si levano da un promontorio bonificato; due sono trafitti da sfere rivestite con circa quarantunomila dischi di acciaio smaltato in otto tonalità di blu, verde e grigio, disposti a spirale come le maioliche di una cupola. La sfera inferiore ospita una cisterna e un ristorante; quella superiore gira. Un serbatoio idrico è finito sulle banconote.',
    },
    context: {
      body: {
        en: 'The towers were heavily damaged by Iraqi forces during the occupation of Kuwait from August 1990 to February 1991, and were structurally surveyed and repaired after liberation. They closed again for maintenance from March 2012 and reopened on 8 March 2016. The Kuwait water-tower programme of which they form the sixth and final group, credited to Sune Lindström, Malene Bjørn and VBB, was among the first recipients of the Aga Khan Award for Architecture in 1980.',
        es: 'Las torres sufrieron daños graves a manos de las fuerzas iraquíes durante la ocupación de Kuwait, entre agosto de 1990 y febrero de 1991, y fueron inspeccionadas estructuralmente y reparadas tras la liberación. Volvieron a cerrar por mantenimiento en marzo de 2012 y reabrieron el 8 de marzo de 2016. El programa kuwaití de depósitos elevados del que forman el sexto y último grupo, acreditado a Sune Lindström, Malene Bjørn y VBB, estuvo entre los primeros galardonados con el Premio Aga Khan de Arquitectura, en 1980.',
        it: 'Le torri furono gravemente danneggiate dalle forze irachene durante l\'occupazione del Kuwait, dall\'agosto 1990 al febbraio 1991, e furono verificate strutturalmente e riparate dopo la liberazione. Chiusero di nuovo per manutenzione dal marzo 2012 e riaprirono l\'8 marzo 2016. Il programma kuwaitiano di serbatoi pensili di cui costituiscono il sesto e ultimo gruppo, attribuito a Sune Lindström, Malene Bjørn e VBB, fu tra i primi insigniti dell\'Aga Khan Award for Architecture, nel 1980.',
      },
      sources: [
        {
          kind: 'wikipedia',
          url: 'https://en.wikipedia.org/wiki/Kuwait_Towers',
          title: 'Kuwait Towers',
          license: 'CC BY-SA 4.0',
        },
        {
          kind: 'wikidata',
          url: 'https://www.wikidata.org/wiki/Q1335640',
          title: 'Kuwait Towers (Q1335640)',
          license: null,
        },
      ],
    },
    sources: [
      {
        kind: 'wikidata',
        url: 'https://www.wikidata.org/wiki/Q1335640',
        title: 'Kuwait Towers (Q1335640)',
        license: null,
      },
      {
        kind: 'wikipedia',
        url: 'https://en.wikipedia.org/wiki/Kuwait_Towers',
        title: 'Kuwait Towers',
        license: 'CC BY-SA 4.0',
      },
    ],
    tier: 'canon',
  },
  {
    id: 'al-kindi-plaza-riyadh',
    wikidataId: 'Q117706013',
    name: {
      en: 'Al-Kindi Plaza',
      es: 'Plaza Al-Kindi',
      it: 'Piazza Al-Kindi',
    },
    architectId: 'ali-al-shuaibi',
    location: { city: 'Riyadh', countryCode: 'SA', lat: 24.681944, lon: 46.623056 },
    inception: 1983,
    completed: 1986,
    demolished: null,
    typology: 'civic',
    materials: ['stone', 'concrete'],
    structure: {
      en: 'Low load-bearing blocks of concrete faced in local limestone, ranged in a continuous line along the secondary streets and opening into shaded alleys and courtyards that step down to a central maidan.',
      es: 'Bloques bajos de hormigón revestidos de caliza local, alineados de forma continua a lo largo de las calles secundarias y abiertos a callejones y patios sombreados que descienden hasta un maidán central.',
      it: 'Bassi blocchi in calcestruzzo rivestiti di calcare locale, allineati con continuità lungo le strade secondarie e aperti su vicoli e cortili ombreggiati che digradano verso un maidan centrale.',
    },
    program: {
      en: 'A mixed civic centre of 26,000 square metres for the Arriyadh Development Authority, combining the district mosque with offices, shops, a library and a theatre around a public square.',
      es: 'Un centro cívico mixto de 26.000 metros cuadrados para la Autoridad de Desarrollo de Riad, que reúne la mezquita del barrio con oficinas, comercios, una biblioteca y un teatro en torno a una plaza pública.',
      it: 'Un centro civico misto di 26.000 metri quadrati per la Arriyadh Development Authority, che riunisce la moschea di quartiere con uffici, negozi, una biblioteca e un teatro attorno a una piazza pubblica.',
    },
    heritage: 'none',
    currentUse: {
      en: 'The civic centre of Riyadh\'s Diplomatic Quarter.',
      es: 'El centro cívico del Barrio Diplomático de Riad.',
      it: 'Il centro civico del Quartiere Diplomatico di Riad.',
    },
    detailRect: { x: 0.28, y: 0.3, w: 0.42, h: 0.32 },
    image: {
      commonsFile: 'File:أزقة ساحة الكِنْدي (8828210090).jpg',
      // Credited verbatim from the file page, including the non-breaking
      // space before the colon (U+00A0), written as an escape so it is not
      // silently normalised to a plain space by an editor.
      photographer: 'Ali from Riyadh\u00A0: ) from Riyadh, Saudi Arabia',
      license: 'CC BY 2.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:%D8%A3%D8%B2%D9%82%D8%A9_%D8%B3%D8%A7%D8%AD%D8%A9_%D8%A7%D9%84%D9%83%D9%90%D9%86%D9%92%D8%AF%D9%8A_(8828210090).jpg',
      width: 1600,
      height: 1200,
    },
    dossier: {
      en: 'Riyadh\'s Diplomatic Quarter was laid out in the early 1980s as a self-contained district of embassies and official housing, and Al-Kindi Plaza is the piece that had to make it a place rather than a compound. Ali Al-Shuaibi and Abdul-Rahman Al-Hussaini of the Riyadh practice Beeah strung twenty-six thousand square metres of limestone-faced building along the secondary streets, then cut it with shaded alleys and courtyards that funnel into a maidan facing the district mosque. Almost nothing is tall; the shade comes from mass and narrowness rather than from mechanical cooling. The Aga Khan Award jury gave it the 1989 prize for holding the traditional relationship between the mosque and the other public services, and for landscaping that works with desert plants as a self-sustaining system.',
      es: 'El Barrio Diplomático de Riad se trazó a comienzos de los años ochenta como un distrito autónomo de embajadas y vivienda oficial, y la plaza Al-Kindi es la pieza que debía convertirlo en un lugar y no en un recinto. Ali Al-Shuaibi y Abdul-Rahman Al-Hussaini, del estudio Beeah de Riad, tendieron veintiséis mil metros cuadrados de edificación revestida de caliza a lo largo de las calles secundarias y luego la horadaron con callejones y patios sombreados que desembocan en un maidán frente a la mezquita del barrio. Casi nada es alto: la sombra procede de la masa y la estrechez, no de la climatización. El jurado del Premio Aga Khan le concedió el galardón de 1989 por mantener la relación tradicional entre la mezquita y los demás servicios públicos, y por un paisajismo que emplea plantas del desierto como sistema autosostenido.',
      it: 'Il Quartiere Diplomatico di Riad fu tracciato all\'inizio degli anni Ottanta come distretto autonomo di ambasciate e alloggi ufficiali, e piazza Al-Kindi è il pezzo che doveva farne un luogo e non un recinto. Ali Al-Shuaibi e Abdul-Rahman Al-Hussaini, dello studio Beeah di Riad, distesero ventiseimila metri quadrati di edificato rivestito in calcare lungo le strade secondarie, per poi inciderlo con vicoli e cortili ombreggiati che confluiscono in un maidan affacciato sulla moschea di quartiere. Quasi nulla è alto: l\'ombra viene dalla massa e dalla strettezza, non dalla climatizzazione. La giuria dell\'Aga Khan Award gli assegnò il premio del 1989 per aver mantenuto il rapporto tradizionale fra la moschea e gli altri servizi pubblici, e per un paesaggio che impiega piante del deserto come sistema autosufficiente.',
    },
    context: null,
    sources: [
      {
        kind: 'institution',
        url: 'https://the.akdn/en/how-we-work/our-agencies/aga-khan-trust-culture/akaa/al-kindi-plaza',
        title: 'Aga Khan Development Network — Al-Kindi Plaza (Aga Khan Award for Architecture, 1987–1989 cycle)',
        license: null,
      },
      {
        kind: 'institution',
        url: 'https://www.archnet.org/sites/540',
        title: 'Archnet — Diplomatic Quarter Landscaping and Al-Kindi Plaza, Riyadh',
        license: null,
      },
      {
        kind: 'wikidata',
        url: 'https://www.wikidata.org/wiki/Q117706013',
        title: 'Al Kindi Plaza (Q117706013)',
        license: null,
      },
    ],
    tier: 'canon',
  },
  {
    id: 'sultan-qaboos-grand-mosque',
    wikidataId: 'Q1548443',
    name: {
      en: 'Sultan Qaboos Grand Mosque',
      es: 'Gran Mezquita del Sultán Qabús',
      it: 'Grande Moschea del Sultano Qabus',
    },
    architectId: 'mohamed-makiya',
    location: { city: 'Muscat', countryCode: 'OM', lat: 23.583889, lon: 58.389167 },
    inception: 1995,
    completed: 2001,
    demolished: null,
    typology: 'sacral',
    materials: ['stone'],
    structure: {
      en: 'A sandstone-clad prayer hall covered by a single high dome on a square base, set within an arcaded courtyard and marked by five minarets, one central and four at the corners of the enclosure.',
      es: 'Una sala de oración revestida de arenisca cubierta por una única cúpula alta sobre base cuadrada, inscrita en un patio porticado y señalada por cinco alminares, uno central y cuatro en las esquinas del recinto.',
      it: 'Una sala di preghiera rivestita in arenaria coperta da un\'unica alta cupola su base quadrata, inscritta in un cortile porticato e segnata da cinque minareti, uno centrale e quattro agli angoli del recinto.',
    },
    program: {
      en: 'The state mosque of Oman, commissioned by Sultan Qaboos bin Said through an international competition in 1993, holding twenty thousand worshippers and functioning as a centre of Ibadi religious teaching.',
      es: 'La mezquita del Estado de Omán, encargada por el sultán Qabús bin Said mediante un concurso internacional en 1993, con capacidad para veinte mil fieles y sede de la enseñanza religiosa ibadí.',
      it: 'La moschea di Stato dell\'Oman, commissionata dal sultano Qabus bin Said tramite un concorso internazionale nel 1993, capace di ventimila fedeli e sede dell\'insegnamento religioso ibadita.',
    },
    heritage: 'none',
    currentUse: {
      en: 'Oman\'s principal congregational mosque, open to non-Muslim visitors outside prayer times.',
      es: 'La principal mezquita congregacional de Omán, abierta a visitantes no musulmanes fuera de las horas de oración.',
      it: 'La principale moschea congregazionale dell\'Oman, aperta ai visitatori non musulmani al di fuori degli orari di preghiera.',
    },
    detailRect: { x: 0.32, y: 0.28, w: 0.36, h: 0.34 },
    image: {
      commonsFile: 'File:Muscat, moschea del sultano qaboos, esterno 01.jpg',
      photographer: 'Francesco Bini',
      license: 'CC BY-SA 4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Muscat,_moschea_del_sultano_qaboos,_esterno_01.jpg',
      width: 1600,
      height: 978,
    },
    dossier: {
      en: 'Sultan Qaboos launched an international competition for Oman\'s state mosque in 1993 and the commission went to Mohamed Makiya, working with Quad Design of London, with construction running from 1995 to 2001. Makiya was then in his eighties and had spent two decades in exile from Iraq; this is the last and largest work of the argument he had begun with the Khulafa Mosque forty years earlier. The prayer hall carries a single dome on a square base, clad throughout in sandstone, and the whole is held inside an arcaded court with five minarets. He drew on Persian and Ottoman precedent but pulled the ornament back towards the restraint that Ibadi practice in Oman expects — a large building that declines to be florid.',
      es: 'El sultán Qabús convocó en 1993 un concurso internacional para la mezquita del Estado omaní y el encargo recayó en Mohamed Makiya, en colaboración con Quad Design de Londres; las obras se desarrollaron entre 1995 y 2001. Makiya rondaba entonces los noventa años y llevaba dos décadas de exilio de Irak: esta es la última y mayor formulación del argumento que había iniciado cuarenta años antes con la mezquita de Al-Khulafa. La sala de oración se cubre con una única cúpula sobre base cuadrada, revestida por completo de arenisca, y el conjunto se encierra en un patio porticado con cinco alminares. Recurrió a precedentes persas y otomanos, pero contuvo el ornamento hacia la sobriedad que la práctica ibadí omaní espera: un edificio grande que renuncia a ser florido.',
      it: 'Il sultano Qabus bandì nel 1993 un concorso internazionale per la moschea di Stato dell\'Oman e l\'incarico andò a Mohamed Makiya, in collaborazione con Quad Design di Londra; i lavori si svolsero fra il 1995 e il 2001. Makiya aveva allora più di ottant\'anni e alle spalle due decenni di esilio dall\'Iraq: questa è l\'ultima e più ampia formulazione della tesi che aveva avviato quarant\'anni prima con la moschea di Al-Khulafa. La sala di preghiera è coperta da un\'unica cupola su base quadrata, interamente rivestita in arenaria, e l\'insieme è racchiuso in un cortile porticato con cinque minareti. Attinse a precedenti persiani e ottomani, ma trattenne l\'ornato verso la sobrietà che la pratica ibadita omanita si attende: un grande edificio che rinuncia a essere fiorito.',
    },
    context: null,
    sources: [
      {
        kind: 'wikidata',
        url: 'https://www.wikidata.org/wiki/Q1548443',
        title: 'Sultan Qaboos Grand Mosque (Q1548443)',
        license: null,
      },
      {
        kind: 'institution',
        url: 'https://www.archnet.org/sites/4818',
        title: 'Archnet — Sultan Qaboos Grand Mosque (Mohamed Makiya architect\'s archive)',
        license: null,
      },
      {
        kind: 'wikipedia',
        url: 'https://en.wikipedia.org/wiki/Sultan_Qaboos_Grand_Mosque',
        title: 'Sultan Qaboos Grand Mosque',
        license: 'CC BY-SA 4.0',
      },
    ],
    tier: 'canon',
  },
  {
    id: 'saf-art-spaces-al-mureijah',
    wikidataId: '',
    name: {
      en: 'Sharjah Art Foundation Art Spaces',
      es: 'Espacios de Arte de la Fundación de Arte de Sharjah',
      it: 'Art Spaces della Sharjah Art Foundation',
    },
    architectId: 'mona-el-mousfy',
    location: { city: 'Sharjah', countryCode: 'AE', lat: 25.3576, lon: 55.3838 },
    inception: 2013,
    completed: 2013,
    demolished: null,
    typology: 'cultural',
    materials: ['concrete', 'stone'],
    structure: {
      en: 'Five new concrete gallery volumes, top-lit and column-free, inserted between six restored coral-stone and plaster courtyard houses and linked by open alleys, ramps and roof terraces at the scale of the old quarter.',
      es: 'Cinco volúmenes nuevos de salas en hormigón, con luz cenital y sin pilares, insertados entre seis casas de patio restauradas de piedra de coral y yeso, y enlazados por callejones abiertos, rampas y azoteas a la escala del barrio antiguo.',
      it: 'Cinque nuovi volumi espositivi in calcestruzzo, illuminati dall\'alto e privi di pilastri, inseriti fra sei case a corte restaurate in pietra corallina e intonaco e collegati da vicoli aperti, rampe e terrazze alla scala del quartiere antico.',
    },
    program: {
      en: 'Permanent exhibition buildings for the Sharjah Art Foundation in the Al Mureijah heritage area, replacing the temporary fit-outs the Sharjah Biennial had used since the 1990s.',
      es: 'Edificios expositivos permanentes para la Sharjah Art Foundation en el área patrimonial de Al Mureijah, en sustitución de las adaptaciones temporales que la Bienal de Sharjah venía usando desde los años noventa.',
      it: 'Edifici espositivi permanenti per la Sharjah Art Foundation nell\'area storica di Al Mureijah, in sostituzione degli allestimenti temporanei che la Biennale di Sharjah usava dagli anni Novanta.',
    },
    heritage: 'none',
    currentUse: {
      en: 'Galleries, courtyards and public routes of the Sharjah Art Foundation.',
      es: 'Salas, patios y recorridos públicos de la Sharjah Art Foundation.',
      it: 'Sale, cortili e percorsi pubblici della Sharjah Art Foundation.',
    },
    detailRect: { x: 0.3, y: 0.32, w: 0.4, h: 0.32 },
    image: {
      commonsFile: 'File:Section of Al Mureijah Square, a part of the Sharjah Art Foundation.jpg',
      photographer: 'M.Ahmadani',
      license: 'CC BY-SA 4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Section_of_Al_Mureijah_Square,_a_part_of_the_Sharjah_Art_Foundation.jpg',
      width: 1600,
      height: 1067,
    },
    dossier: {
      en: 'The Sharjah Biennial spent two decades in borrowed rooms before the Art Foundation asked Mona El Mousfy for buildings of its own. Her answer, finished in 2013, refuses the single museum box: five new concrete galleries are threaded through six restored courtyard houses in the old Al Mureijah quarter, and the alleys, stairs and roof terraces between them stay open to the town. Inside, the new volumes are column-free and lit from above; outside, they hold the height and grain of the coral-stone houses they sit against, so that a visitor moves between 1930s plasterwork and a raw concrete gallery without a threshold announcing either. The scheme was shortlisted for the Aga Khan Award for Architecture in 2019, and it is the most sustained argument yet for building contemporary art space inside a Gulf historic centre.',
      es: 'La Bienal de Sharjah pasó dos décadas en salas prestadas antes de que la Fundación de Arte pidiera a Mona El Mousfy edificios propios. Su respuesta, terminada en 2013, rechaza la caja museística única: cinco salas nuevas de hormigón se entretejen con seis casas de patio restauradas en el viejo barrio de Al Mureijah, y los callejones, escaleras y azoteas intermedios siguen abiertos a la ciudad. Por dentro, los volúmenes nuevos carecen de pilares y se iluminan desde arriba; por fuera, mantienen la altura y el grano de las casas de piedra de coral contra las que se apoyan, de modo que el visitante pasa de un revoco de los años treinta a una sala de hormigón visto sin que ningún umbral anuncie el cambio. El proyecto fue finalista del Premio Aga Khan de Arquitectura en 2019.',
      it: 'La Biennale di Sharjah trascorse due decenni in sale prese a prestito prima che la Fondazione d\'Arte chiedesse a Mona El Mousfy edifici propri. La sua risposta, conclusa nel 2013, rifiuta la scatola museale unica: cinque nuove sale in calcestruzzo si intrecciano a sei case a corte restaurate nel vecchio quartiere di Al Mureijah, e i vicoli, le scale e le terrazze intermedie restano aperti alla città. All\'interno i nuovi volumi sono privi di pilastri e illuminati dall\'alto; all\'esterno mantengono l\'altezza e la grana delle case in pietra corallina cui si appoggiano, così che il visitatore passa da un intonaco degli anni Trenta a una sala in cemento a vista senza che alcuna soglia annunci il cambio. Il progetto fu finalista dell\'Aga Khan Award for Architecture nel 2019.',
    },
    context: null,
    sources: [
      {
        kind: 'institution',
        url: 'https://www.sharjaharchitecture.org/pages/about/contributors/mona-el-mousfy',
        title: 'Sharjah Architecture Triennial — Contributors: Mona El-Mousfy',
        license: null,
      },
      {
        kind: 'institution',
        url: 'https://www.sharjahart.org/en/march-meeting/mm-2018/speakers/details/el-mousfy-mona/',
        title: 'Sharjah Art Foundation — March Meeting 2018 speaker: Mona El Mousfy',
        license: null,
      },
      {
        kind: 'wikipedia',
        url: 'https://en.wikipedia.org/wiki/Sharjah_Art_Foundation',
        title: 'Sharjah Art Foundation',
        license: 'CC BY-SA 4.0',
      },
    ],
    tier: 'canon',
  },
  {
    id: 'mleiha-archaeological-centre',
    wikidataId: 'Q24964896',
    name: {
      en: 'Mleiha Archaeological Centre',
      es: 'Centro Arqueológico de Mleiha',
      it: 'Centro Archeologico di Mleiha',
    },
    architectId: 'sumaya-dabbagh',
    location: { city: 'Mleiha', countryCode: 'AE', lat: 25.126375, lon: 55.857547 },
    inception: 2016,
    completed: 2016,
    demolished: null,
    typology: 'cultural',
    materials: ['stone', 'concrete'],
    structure: {
      en: 'Concentric low walls of sand-coloured stone and concrete drawn as arcs around an excavated Bronze Age tomb, roofed flat and cut by slots that admit indirect light to the galleries below.',
      es: 'Muros bajos concéntricos de piedra y hormigón del color de la arena, trazados como arcos en torno a una tumba excavada de la Edad del Bronce, con cubierta plana y hendiduras que llevan luz indirecta a las salas inferiores.',
      it: 'Bassi muri concentrici in pietra e calcestruzzo color sabbia, tracciati ad arco attorno a una tomba scavata dell\'età del bronzo, con copertura piana e fenditure che portano luce indiretta alle sale sottostanti.',
    },
    program: {
      en: 'A visitor centre and museum of about two thousand square metres for the Sharjah archaeological site at Mleiha, at the foot of Fossil Rock, with galleries, a café and desert walks.',
      es: 'Un centro de visitantes y museo de unos dos mil metros cuadrados para el yacimiento arqueológico de Mleiha, en Sharjah, al pie de Fossil Rock, con salas, cafetería y recorridos por el desierto.',
      it: 'Un centro visitatori e museo di circa duemila metri quadrati per il sito archeologico di Mleiha, a Sharjah, ai piedi di Fossil Rock, con sale, caffetteria e percorsi nel deserto.',
    },
    heritage: 'national',
    currentUse: {
      en: 'Museum and visitor centre for the Mleiha archaeological site.',
      es: 'Museo y centro de visitantes del yacimiento arqueológico de Mleiha.',
      it: 'Museo e centro visitatori del sito archeologico di Mleiha.',
    },
    detailRect: { x: 0.3, y: 0.35, w: 0.4, h: 0.3 },
    image: {
      commonsFile: 'File:The Mleiha Archaeological Centre, built around a 4,500 year old Umm Al Nar Tomb.jpg',
      photographer: 'Alexandermcnabb',
      license: 'CC BY-SA 4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:The_Mleiha_Archaeological_Centre,_built_around_a_4,500_year_old_Umm_Al_Nar_Tomb.jpg',
      width: 1600,
      height: 1200,
    },
    dossier: {
      en: 'At Mleiha, in the desert interior of Sharjah below Fossil Rock, an Umm an-Nar tomb of about 2300 BCE sits in the open. Sumaya Dabbagh\'s centre, opened in January 2016, is generated from that circle: concentric low walls of sand-coloured stone swing around the tomb, setting up a processional approach and then dropping the two thousand square metres of gallery, café and service below the horizon line. The building is deliberately quiet — Dabbagh has said the point was to show the archaeology rather than take the attention — and it works by shade, mass and indirect light rather than by silhouette. It is among the first major public buildings in the Emirates by a practice founded and led by a woman, and it took a Cityscape Global award in its opening year.',
      es: 'En Mleiha, en el interior desértico de Sharjah al pie de Fossil Rock, una tumba de tipo Umm an-Nar de hacia 2300 a. C. permanece al descubierto. El centro de Sumaya Dabbagh, inaugurado en enero de 2016, se genera a partir de ese círculo: muros bajos concéntricos de piedra del color de la arena giran en torno a la tumba, organizan una aproximación ceremonial y luego hunden bajo la línea del horizonte los dos mil metros cuadrados de salas, cafetería y servicios. El edificio es deliberadamente callado —Dabbagh ha dicho que se trataba de mostrar la arqueología y no de acaparar la atención— y trabaja con la sombra, la masa y la luz indirecta antes que con la silueta. Es uno de los primeros grandes edificios públicos de los Emiratos obra de un estudio fundado y dirigido por una mujer.',
      it: 'A Mleiha, nell\'interno desertico di Sharjah ai piedi di Fossil Rock, una tomba di tipo Umm an-Nar di circa il 2300 a.C. resta allo scoperto. Il centro di Sumaya Dabbagh, inaugurato nel gennaio 2016, si genera da quel cerchio: bassi muri concentrici in pietra color sabbia ruotano attorno alla tomba, impostano un avvicinamento processionale e poi fanno scendere sotto la linea dell\'orizzonte i duemila metri quadrati di sale, caffetteria e servizi. L\'edificio è deliberatamente silenzioso — Dabbagh ha detto che si trattava di mostrare l\'archeologia e non di attirare l\'attenzione — e lavora con l\'ombra, la massa e la luce indiretta più che con la sagoma. È fra i primi grandi edifici pubblici degli Emirati realizzati da uno studio fondato e diretto da una donna.',
    },
    context: {
      body: {
        en: 'Construction in the United Arab Emirates is carried out overwhelmingly by migrant workers recruited from South Asia under the kafala sponsorship system. Human Rights Watch interviewed sixty construction workers in Dubai, Sharjah and Ajman in February 2006 and published Building Towers, Cheating Workers, documenting recruitment debt, withheld wages, confiscated passports and hazardous conditions; its 2009 report The Island of Happiness examined Saadiyat Island in Abu Dhabi. The UAE subsequently outlawed employer confiscation of passports, eased sponsorship transfer and introduced the Wage Protection System in 2009, requiring wages to be paid through banks; the International Trade Union Confederation and migrant-rights organisations have continued to report abuses and weak enforcement. No published investigation names this project, and none of the reporting cited here concerns it specifically; the sector-wide record is stated because it is how buildings in the Emirates are built.',
        es: 'La construcción en los Emiratos Árabes Unidos la ejecutan de forma abrumadora trabajadores migrantes reclutados en el sur de Asia bajo el sistema de patrocinio kafala. Human Rights Watch entrevistó a sesenta obreros de la construcción en Dubái, Sharjah y Ajmán en febrero de 2006 y publicó Building Towers, Cheating Workers, que documenta endeudamiento por reclutamiento, salarios retenidos, pasaportes confiscados y condiciones peligrosas; su informe de 2009 The Island of Happiness examinó la isla de Saadiyat, en Abu Dabi. Los Emiratos prohibieron después la confiscación de pasaportes por el empleador, flexibilizaron el traspaso de patrocinio e introdujeron en 2009 el Sistema de Protección Salarial, que obliga a pagar los salarios por vía bancaria; la Confederación Sindical Internacional y organizaciones de derechos de los migrantes han seguido denunciando abusos y una aplicación débil. Ninguna investigación publicada menciona este proyecto, y ninguna de las fuentes citadas se refiere a él en concreto; se expone el registro sectorial porque es el modo en que se construye en los Emiratos.',
        it: 'La costruzione negli Emirati Arabi Uniti è realizzata in modo schiacciante da lavoratori migranti reclutati nell\'Asia meridionale sotto il sistema di sponsorizzazione kafala. Human Rights Watch intervistò sessanta operai edili a Dubai, Sharjah e Ajman nel febbraio 2006 e pubblicò Building Towers, Cheating Workers, che documenta indebitamento per il reclutamento, salari trattenuti, passaporti confiscati e condizioni pericolose; il rapporto del 2009 The Island of Happiness esaminò l\'isola di Saadiyat, ad Abu Dhabi. Gli Emirati hanno poi vietato la confisca dei passaporti da parte del datore di lavoro, agevolato il trasferimento della sponsorizzazione e introdotto nel 2009 il Wage Protection System, che impone il pagamento dei salari per via bancaria; la Confederazione Sindacale Internazionale e le organizzazioni per i diritti dei migranti continuano a segnalare abusi e applicazione debole. Nessuna inchiesta pubblicata nomina questo progetto, e nessuna delle fonti citate lo riguarda in modo specifico; il quadro di settore è riportato perché è il modo in cui negli Emirati si costruisce.',
      },
      sources: [
        {
          kind: 'publication',
          url: 'https://www.hrw.org/report/2006/11/11/building-towers-cheating-workers/exploitation-migrant-construction-workers-united',
          title: 'Human Rights Watch, "Building Towers, Cheating Workers: Exploitation of Migrant Construction Workers in the United Arab Emirates" (November 2006)',
          license: null,
        },
        {
          kind: 'publication',
          url: 'https://www.hrw.org/report/2009/05/19/island-happiness/exploitation-migrant-workers-saadiyat-island-abu-dhabi',
          title: 'Human Rights Watch, "The Island of Happiness: Exploitation of Migrant Workers on Saadiyat Island, Abu Dhabi" (May 2009)',
          license: null,
        },
        {
          kind: 'publication',
          url: 'https://www.ituc-csi.org/uae-labour-law-reforms-fail',
          title: 'International Trade Union Confederation, "UAE labour law reforms fail to address abuses of workers\' rights"',
          license: null,
        },
        {
          kind: 'publication',
          url: 'https://www.migrationpolicy.org/article/labor-migration-united-arab-emirates-challenges-and-responses',
          title: 'Migration Policy Institute, "Labor Migration in the United Arab Emirates: Challenges and Responses"',
          license: null,
        },
      ],
    },
    sources: [
      {
        kind: 'wikidata',
        url: 'https://www.wikidata.org/wiki/Q24964896',
        title: 'Mleiha Archaeological Centre (Q24964896)',
        license: null,
      },
      {
        kind: 'publication',
        url: 'https://www.archdaily.com/994199/mleiha-archaeological-centre-dabbagh-architects',
        title: 'ArchDaily, "Mleiha Archaeological Centre / Dabbagh Architects"',
        license: null,
      },
      {
        kind: 'publication',
        url: 'https://www.middleeastarchitect.com/thoughts/sharjahs-mleiha-centre-shortlisted-for-waf-award-because-it-showcases-the-archaeology-says-architect-sumaya-dabbagh',
        title: 'Middle East Architect, "Sharjah\'s Mleiha centre shortlisted for WAF award because it \'showcases the archaeology\' says architect Sumaya Dabbagh"',
        license: null,
      },
    ],
    tier: 'deep',
  },
];
