// The hand-picked featured roster driving the v2 game (spec 2026-08-30 §2).
// The game (daily, unlimited, guess roster) draws ONLY from buildings whose
// architectId is in this list; the archive keeps the full pool. Hard
// validator rules: every id must resolve (`featured-architect-exists`) and
// hold >=2 buildings (`featured-min-buildings`).
export const FEATURED_ARCHITECT_IDS: string[] = [
  'luis-barragan',
  'lina-bo-bardi',
  'peter-zumthor',
  'frank-lloyd-wright',
  'mies-van-der-rohe',
  'philip-johnson',
  'louis-sullivan',
  'eero-saarinen',
  'louis-kahn',
  'marcel-breuer',
  'buckminster-fuller',
  'frank-gehry',
  'i-m-pei',
  'antoni-gaudi',
  'felix-candela',
  'oscar-niemeyer',
  'alvaro-siza',
  'alvar-aalto',
  'walter-gropius',
  'victor-horta',
  'charles-rennie-mackintosh',
  'gustave-eiffel',
  'jorn-utzon',
  'norman-foster',
  'richard-rogers',
  'zaha-hadid',
  'christopher-wren',
  'filippo-brunelleschi',
  'andrea-palladio',
  'michelangelo',
  'renzo-piano',
  'jean-nouvel',
  'tadao-ando',
  'kenzo-tange',
  'kazuyo-sejima',
  'toyo-ito',
  'wang-shu',
  'mimar-sinan',
];
