import type { Architect } from '@/types/architect';

// Wave 5 curator agent (West Africa): real, sourced Architect entries for this slice.
//
// Countries in scope: NG, GH, SN, BF, ML, CI, BJ, TG, GN, SL, LR, GM, NE, MR.
//
// Almost none of the metadata below could be lifted from Wikidata. A live query
// on 2026-08-26 returned 39 buildings with an attributed architect for all
// fourteen countries, and exactly two of those had a woman architect. Every
// architect here except Jane Drew, Demas Nwoko, Babban Gwani and Tosin Oshinowo
// is hand-authored from published scholarship; see the task report for the
// per-architect source list.
export const AFRICA_WEST_ARCHITECTS: Architect[] = [
  {
    id: 'al-aqib-ibn-mahmud',
    wikidataId: '',
    name: 'Al-Aqib ibn Mahmud ibn Umar',
    alternativeNames: ['Qadi al-Aqib', 'al-ʿĀqib ibn Maḥmūd ibn ʿUmar', 'Imam Al-Aqib'],
    gender: 'man',
    born: null,
    died: null,
    floruit: { start: 1570, end: 1582, override: false },
    movements: [{ id: 'earthen-vernacular', primary: true }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'sacral',
    signatureMaterial: 'earth',
    portrait: {
      en: "Al-Aqib ibn Mahmud ibn Umar was chief qadi of Timbuktu in the second half of the sixteenth century, and he is the closest thing the city's building record offers to a named architect. The Sudano-Sahelian tradition was carried by hereditary guilds of masons whose members are almost never recorded individually. What the seventeenth-century chronicle Ta'rikh al-Sudan does record is that al-Aqib directed two mosque campaigns: from 1570 he rebuilt the Djinguereber, and between 1578 and 1582 he had the sanctuary of the Sankoré mosque demolished and reconstructed to dimensions he had measured against the Kaaba while on pilgrimage. He was a jurist and not a professional builder, and the masons who executed the work are anonymous. The decision that fixed the building's form, however, is attributed to him by name.",
      es: 'Al-Aqib ibn Mahmud ibn Umar fue cadí mayor de Tombuctú en la segunda mitad del siglo XVI y es lo más parecido a un arquitecto con nombre propio que ofrece el registro constructivo de la ciudad. La tradición sudano-saheliana la sostenían gremios hereditarios de albañiles cuyos miembros casi nunca quedaron consignados uno por uno. Lo que sí consigna la crónica del siglo XVII Ta’rikh al-Sudan es que al-Aqib dirigió dos campañas de obra: desde 1570 reconstruyó la mezquita de Djinguereber y, entre 1578 y 1582, hizo demoler el santuario de la mezquita de Sankoré y levantarlo de nuevo con las medidas que él mismo había tomado de la Kaaba durante su peregrinación. Era jurista, no constructor de oficio, y los albañiles que ejecutaron la obra son anónimos; la decisión que fijó la forma del edificio, en cambio, se le atribuye a él.',
      it: "Al-Aqib ibn Mahmud ibn Umar fu il qadi capo di Timbuctù nella seconda metà del Cinquecento ed è quanto di più vicino a un architetto con un nome offra la documentazione edilizia della città. La tradizione sudano-saheliana era portata avanti da corporazioni ereditarie di muratori i cui membri quasi mai vennero registrati singolarmente. Ciò che invece la cronaca secentesca Ta'rikh al-Sudan registra è che al-Aqib diresse due campagne di lavori: dal 1570 ricostruì la moschea di Djinguereber e, tra il 1578 e il 1582, fece demolire il santuario della moschea di Sankoré e riedificarlo secondo le misure che aveva rilevato sulla Kaaba durante il pellegrinaggio. Era un giurista e non un costruttore di mestiere, e i muratori che eseguirono l'opera restano anonimi; la decisione che fissò la forma dell'edificio, però, è attribuita a lui per nome.",
    },
    awards: [],
    tier: 'deep',
    context: null,
    sources: [
      {
        kind: 'wikipedia',
        url: 'https://en.wikipedia.org/wiki/Sankor%C3%A9_Madrasah',
        title: 'Sankoré Madrasah',
        license: 'CC BY-SA 4.0',
      },
      {
        kind: 'wikipedia',
        url: 'https://en.wikipedia.org/wiki/Djinguereber_Mosque',
        title: 'Djinguereber Mosque',
        license: 'CC BY-SA 4.0',
      },
    ],
  },
  {
    id: 'nicolas-pepin',
    wikidataId: '',
    name: 'Nicolas Pépin',
    alternativeNames: ['Nicolas Pepin'],
    gender: 'man',
    born: null,
    died: null,
    floruit: { start: 1776, end: 1786, override: false },
    movements: 'unaffiliated',
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'domestic',
    signatureMaterial: 'mixed',
    portrait: {
      en: "Nicolas Pépin belonged to the Franco-African merchant elite of Gorée, off Dakar. He was a son of the signare Catherine Baudet and a brother of Anne Pépin, the companion of the Chevalier de Boufflers, governor of Senegal in 1785–87. Signares were African and mixed-race women traders who married or partnered with European merchants, held property in their own names, and dealt in slaves; the Pépins owned ships and took part in the Atlantic trade. Pépin is not an architect in any professional sense — he is the man named in the record as having had the house on rue Saint-Germain built, in about 1776–1786, in the two-storey Gorée merchant type with living quarters above and holding cells below. The building is now a UNESCO-listed memorial museum.",
      es: 'Nicolas Pépin pertenecía a la élite mercantil franco-africana de Gorea, frente a Dakar. Era hijo de la signare Catherine Baudet y hermano de Anne Pépin, compañera del caballero de Boufflers, gobernador de Senegal entre 1785 y 1787. Las signares eran comerciantes africanas y mestizas que se casaban o se unían con mercaderes europeos, poseían bienes a su nombre y traficaban con personas esclavizadas; los Pépin tenían barcos y participaron en la trata atlántica. Pépin no es un arquitecto en ningún sentido profesional: es el hombre que las fuentes señalan como quien mandó construir la casa de la rue Saint-Germain, hacia 1776-1786, según el tipo mercantil goreano de dos plantas, con vivienda arriba y celdas de retención abajo. El edificio es hoy un museo memorial inscrito por la Unesco.',
      it: "Nicolas Pépin apparteneva all'élite mercantile franco-africana di Gorée, di fronte a Dakar. Era figlio della signare Catherine Baudet e fratello di Anne Pépin, compagna del cavaliere di Boufflers, governatore del Senegal tra il 1785 e il 1787. Le signares erano commercianti africane e meticce che sposavano mercanti europei o vivevano con loro, possedevano beni a proprio nome e trafficavano in persone schiavizzate; i Pépin possedevano navi e presero parte alla tratta atlantica. Pépin non è un architetto in alcun senso professionale: è l'uomo che le fonti indicano come colui che fece costruire la casa di rue Saint-Germain, intorno al 1776-1786, secondo il tipo mercantile goreano a due piani, con l'abitazione sopra e le celle di detenzione sotto. L'edificio è oggi un museo memoriale iscritto dall'UNESCO.",
    },
    awards: [],
    tier: 'deep',
    context: null,
    sources: [
      {
        kind: 'wikipedia',
        url: 'https://en.wikipedia.org/wiki/House_of_Slaves',
        title: 'House of Slaves',
        license: 'CC BY-SA 4.0',
      },
      {
        kind: 'institution',
        url: 'https://memoire-esclavage.org/maison-des-esclaves-ile-de-goree',
        title: "Maison des esclaves, Île de Gorée — Fondation pour la mémoire de l'esclavage",
        license: null,
      },
    ],
  },
  {
    id: 'babban-gwani',
    wikidataId: 'Q122545893',
    name: 'Babban Gwani',
    alternativeNames: ['Mallam Mikhaila', 'Muhammadu Mikhaila', 'Babban Gwani Mikhaila'],
    gender: 'man',
    born: null,
    died: 1862,
    floruit: { start: 1824, end: 1846, override: false },
    movements: [{ id: 'earthen-vernacular', primary: true }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'sacral',
    signatureMaterial: 'earth',
    portrait: {
      en: "Babban Gwani — 'the great expert' — was the title borne by Mallam Mikhaila, the Hausa master builder appointed Sarkin Maigini, chief builder, in the aftermath of the Sokoto jihad. Born in Zaria to a family of craftsmen, he built in mud and azara palm timber, and he is the earliest West African builder whose individual authorship is securely and repeatedly recorded. The Scottish traveller Hugh Clapperton watched him at work on a Sokoto mosque in 1824 and described him as 'a shrewd-looking little man'. His masterpiece is the Friday Mosque of Zaria, whose ribbed mud vaults translate the geometry of Fulani nomadic tents into permanent masonry. He also worked on the Kano emir's palace. He was executed by the Emir of Birnin Gwari after building a mosque there.",
      es: 'Babban Gwani —«el gran experto»— fue el título que llevó Mallam Mikhaila, el maestro constructor hausa nombrado Sarkin Maigini, jefe de obras, tras la yihad de Sokoto. Nacido en Zaria en una familia de artesanos, construía en barro y madera de palmera azara, y es el constructor más antiguo de África Occidental cuya autoría individual está documentada de forma firme y repetida. El viajero escocés Hugh Clapperton lo vio trabajar en una mezquita de Sokoto en 1824 y lo describió como «un hombrecillo de aire perspicaz». Su obra maestra es la mezquita del viernes de Zaria, cuyas bóvedas nervadas de barro trasladan la geometría de las tiendas nómadas fulani a la fábrica permanente. Trabajó también en el palacio del emir de Kano. Fue ejecutado por el emir de Birnin Gwari tras levantar allí una mezquita.',
      it: "Babban Gwani — «il grande esperto» — era il titolo portato da Mallam Mikhaila, il capomastro hausa nominato Sarkin Maigini, costruttore capo, all'indomani della jihad di Sokoto. Nato a Zaria in una famiglia di artigiani, costruiva in terra cruda e legno di palma azara, ed è il più antico costruttore dell'Africa occidentale la cui paternità individuale sia documentata in modo sicuro e ripetuto. Il viaggiatore scozzese Hugh Clapperton lo osservò al lavoro su una moschea di Sokoto nel 1824 e lo descrisse come «un ometto dall'aria sagace». Il suo capolavoro è la moschea del venerdì di Zaria, le cui volte costolonate in terra traducono la geometria delle tende nomadi fulani in muratura permanente. Lavorò anche al palazzo dell'emiro di Kano. Fu giustiziato dall'emiro di Birnin Gwari dopo avervi costruito una moschea.",
    },
    awards: [],
    tier: 'canon',
    context: null,
    sources: [
      {
        kind: 'wikipedia',
        url: 'https://en.wikipedia.org/wiki/Babban_Gwani',
        title: 'Babban Gwani',
        license: 'CC BY-SA 4.0',
      },
      {
        kind: 'wikidata',
        url: 'https://www.wikidata.org/wiki/Q122545893',
        title: 'Babban Gwani (Q122545893)',
        license: null,
      },
    ],
  },
  {
    id: 'joao-baptista-da-costa-lagos',
    wikidataId: '',
    name: 'João Baptista da Costa',
    alternativeNames: ['Senhor João Baptista da Costa', 'Joao Batista da Costa'],
    gender: 'man',
    born: null,
    died: null,
    floruit: { start: 1891, end: 1894, override: false },
    movements: 'unaffiliated',
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'sacral',
    signatureMaterial: 'brick',
    portrait: {
      en: "João Baptista da Costa was a master builder of the Afro-Brazilian community of Lagos — the Agudá, formerly enslaved people and their descendants who returned to the Bight of Benin from Brazil across the nineteenth century, bringing with them the masonry, stucco and tile-work trades they had been forced to learn in Salvador and Recife. Almost nothing of his life is recorded; what is recorded is that he directed the building of the Shitta-Bey Mosque on Lagos Island between 1891 and 1894, assisted by a local builder named Sanusi Aka. The mosque's tiled and moulded facade is the best-preserved statement of the Brazilian style in Lagos. Note that Wikidata's architect claim for the mosque points at a same-named Brazilian painter and is a data error.",
      es: 'João Baptista da Costa fue un maestro de obras de la comunidad afrobrasileña de Lagos: los agudá, personas antes esclavizadas y sus descendientes que a lo largo del siglo XIX regresaron desde Brasil a la bahía de Benín trayendo consigo los oficios de albañilería, estuco y azulejería que se habían visto obligados a aprender en Salvador y Recife. De su vida apenas se conserva nada; lo que sí consta es que dirigió la construcción de la mezquita Shitta-Bey, en la isla de Lagos, entre 1891 y 1894, con la ayuda de un constructor local llamado Sanusi Aka. La fachada de azulejos y molduras de la mezquita es la muestra mejor conservada del estilo brasileño en Lagos. Conviene advertir que la atribución de Wikidata remite a un pintor brasileño homónimo y es un error de datos.',
      it: "João Baptista da Costa fu un capomastro della comunità afro-brasiliana di Lagos: gli agudá, persone già schiavizzate e loro discendenti che nel corso dell'Ottocento tornarono dal Brasile al golfo del Benin portando con sé i mestieri della muratura, dello stucco e della ceramica che erano stati costretti ad apprendere a Salvador e Recife. Della sua vita non resta quasi nulla; è invece documentato che diresse la costruzione della moschea Shitta-Bey, sull'isola di Lagos, tra il 1891 e il 1894, coadiuvato da un costruttore locale di nome Sanusi Aka. La facciata piastrellata e modanata della moschea è la testimonianza meglio conservata dello stile brasiliano a Lagos. Si noti che l'attribuzione presente su Wikidata rimanda a un pittore brasiliano omonimo ed è un errore dei dati.",
    },
    awards: [],
    tier: 'deep',
    context: null,
    sources: [
      {
        kind: 'wikipedia',
        url: 'https://en.wikipedia.org/wiki/Shitta-Bey_Mosque',
        title: 'Shitta-Bey Mosque',
        license: 'CC BY-SA 4.0',
      },
      {
        kind: 'wikidata',
        url: 'https://www.wikidata.org/wiki/Q48791511',
        title: 'Shitta-Bey Mosque (Q48791511)',
        license: null,
      },
    ],
  },
  {
    id: 'ismaila-traore',
    wikidataId: '',
    name: 'Ismaila Traoré',
    alternativeNames: ['Ismaila Traore'],
    gender: 'man',
    born: null,
    died: null,
    floruit: { start: 1906, end: 1907, override: false },
    movements: [{ id: 'earthen-vernacular', primary: true }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'sacral',
    signatureMaterial: 'earth',
    portrait: {
      en: "Ismaila Traoré was head of the barey ton, the hereditary masons' guild of Djenné, and in 1906–07 he directed the rebuilding of the town's Great Mosque — the largest earthen building in the world and, for most of the century since, the image by which West African architecture has been known abroad. The guild he led is a working institution rather than a memory: its members still replaster the mosque each year at the crépissage, a communal festival that is also its structural maintenance. Traoré's authorship matters because the alternative account, advanced by the French journalist Félix Dubois after his 1910 visit, credited the design to the colonial administration. Later scholarship, notably Jean-Louis Bourgeois, holds the design to be substantially Djenné's own.",
      es: 'Ismaila Traoré era el jefe del barey ton, el gremio hereditario de albañiles de Djenné, y en 1906-07 dirigió la reconstrucción de la Gran Mezquita de la ciudad: el mayor edificio de tierra del mundo y, durante casi todo el siglo transcurrido desde entonces, la imagen con la que se ha conocido fuera la arquitectura de África Occidental. El gremio que encabezaba no es un recuerdo sino una institución en activo: sus miembros siguen revocando la mezquita cada año en el crépissage, una fiesta comunitaria que es a la vez su mantenimiento estructural. La autoría de Traoré importa porque el relato alternativo, defendido por el periodista francés Félix Dubois tras su visita de 1910, atribuía el diseño a la administración colonial. La investigación posterior, sobre todo la de Jean-Louis Bourgeois, sostiene que el diseño es sustancialmente de Djenné.',
      it: "Ismaila Traoré era il capo del barey ton, la corporazione ereditaria dei muratori di Djenné, e nel 1906-07 diresse la ricostruzione della Grande Moschea della città: il più grande edificio in terra cruda del mondo e, per quasi tutto il secolo successivo, l'immagine con cui l'architettura dell'Africa occidentale è stata conosciuta all'estero. La corporazione che guidava non è un ricordo ma un'istituzione viva: i suoi membri intonacano ancora la moschea ogni anno durante il crépissage, una festa comunitaria che è al tempo stesso la sua manutenzione strutturale. La paternità di Traoré conta perché il racconto alternativo, sostenuto dal giornalista francese Félix Dubois dopo la visita del 1910, attribuiva il progetto all'amministrazione coloniale. Gli studi successivi, in particolare quelli di Jean-Louis Bourgeois, ritengono il progetto sostanzialmente opera di Djenné.",
    },
    awards: [],
    tier: 'canon',
    context: null,
    sources: [
      {
        kind: 'wikipedia',
        url: 'https://en.wikipedia.org/wiki/Great_Mosque_of_Djenn%C3%A9',
        title: 'Great Mosque of Djenné',
        license: 'CC BY-SA 4.0',
      },
      {
        kind: 'institution',
        url: 'https://whc.unesco.org/en/list/116/',
        title: 'Old Towns of Djenné — UNESCO World Heritage Centre',
        license: null,
      },
    ],
  },
  {
    id: 'jane-drew',
    wikidataId: 'Q2739603',
    name: 'Jane Drew',
    alternativeNames: ['Dame Jane Beverly Drew', 'Jane Beverly Drew'],
    gender: 'woman',
    born: 1911,
    died: 1996,
    floruit: { start: 1946, end: 1977, override: false },
    movements: [
      { id: 'tropical-modernism', primary: true },
      { id: 'international-style', primary: false },
    ],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'educational',
    signatureMaterial: 'concrete',
    portrait: {
      en: "Jane Drew was the senior partner, with her husband Maxwell Fry, of the practice that codified Tropical Modernism — a way of building for hot, humid climates in which the concrete frame is opened up with deep eaves, adjustable louvres, brise-soleil screens and cross-ventilation instead of being sealed and cooled. She worked in British West Africa from 1946, first as an assistant town-planning adviser to the colonial government of the Gold Coast, and the firm's Ghanaian and Nigerian schools, colleges and university campuses of the 1940s and 1950s are her most consequential body of work. She and Fry later brought Le Corbusier to Chandigarh, and designed housing and schools there. Her practice was based in London; the West African work was colonial commissioning, and is contested for it.",
      es: 'Jane Drew fue la socia principal, junto con su marido Maxwell Fry, del estudio que codificó el modernismo tropical: una manera de construir para climas cálidos y húmedos en la que la estructura de hormigón se abre con grandes aleros, lamas regulables, celosías brise-soleil y ventilación cruzada en lugar de sellarse y refrigerarse. Trabajó en el África Occidental Británica desde 1946, primero como asesora adjunta de urbanismo del gobierno colonial de Costa de Oro, y las escuelas, colegios y campus universitarios que el estudio construyó en Ghana y Nigeria durante los años cuarenta y cincuenta son su obra de mayor alcance. Ella y Fry llevaron después a Le Corbusier a Chandigarh, donde proyectaron viviendas y escuelas. Su estudio tenía sede en Londres; los encargos africanos fueron coloniales y por ello se discuten.',
      it: "Jane Drew fu la socia principale, insieme al marito Maxwell Fry, dello studio che codificò il modernismo tropicale: un modo di costruire per climi caldi e umidi in cui il telaio in cemento armato si apre con gronde profonde, lamelle regolabili, frangisole e ventilazione incrociata anziché essere sigillato e raffrescato. Lavorò nell'Africa occidentale britannica dal 1946, dapprima come consulente aggiunta di urbanistica per il governo coloniale della Costa d'Oro, e le scuole, i collegi e i campus universitari realizzati dallo studio in Ghana e in Nigeria negli anni Quaranta e Cinquanta costituiscono la sua opera più incisiva. Lei e Fry portarono poi Le Corbusier a Chandigarh, dove progettarono alloggi e scuole. Il suo studio aveva sede a Londra; le commesse africane furono coloniali e per questo sono discusse.",
    },
    awards: ['DBE (1996)', 'RIBA Fellow'],
    tier: 'canon',
    context: null,
    sources: [
      {
        kind: 'wikipedia',
        url: 'https://en.wikipedia.org/wiki/Jane_Drew',
        title: 'Jane Drew',
        license: 'CC BY-SA 4.0',
      },
      {
        kind: 'institution',
        url: 'https://www.vam.ac.uk/blog/museum-life/tropical-modernism-architecture-and-power-in-west-africa',
        title: 'Tropical Modernism: Architecture and power in West Africa — Victoria and Albert Museum',
        license: null,
      },
    ],
  },
  {
    id: 'demas-nwoko',
    wikidataId: 'Q5255093',
    name: 'Demas Nwoko',
    alternativeNames: ['Demas Nkiru Nwoko'],
    gender: 'man',
    born: 1935,
    died: null,
    floruit: { start: 1967, end: 1993, override: false },
    movements: 'unaffiliated',
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'cultural',
    signatureMaterial: 'concrete',
    portrait: {
      en: "Demas Nwoko came to building from painting, sculpture and stage design. A founder member of the Zaria Art Society — the 'Zaria Rebels', who argued in the late 1950s that Nigerian artists should synthesise European training with Nigerian form rather than copy either — he built without a formal architectural qualification, a fact Nigerian architectural historians have held against him and international juries have not. His materials answer the climate and the local ground: a cast sandcrete of his own devising, mixing cement and sand with pebble-filled lateritic soil, which sets the colour of Benin City's red earth into the wall. Deep overhangs, courtyards and top-lit volumes do the work that air conditioning does elsewhere. In 2023 he received the Golden Lion for Lifetime Achievement at the Venice Biennale.",
      es: 'Demas Nwoko llegó a la construcción desde la pintura, la escultura y la escenografía. Miembro fundador de la Zaria Art Society —los «rebeldes de Zaria», que a finales de los años cincuenta sostuvieron que los artistas nigerianos debían sintetizar la formación europea con la forma nigeriana en lugar de copiar ninguna de las dos—, construyó sin titulación formal de arquitecto, algo que la historiografía arquitectónica nigeriana le ha reprochado y los jurados internacionales no. Sus materiales responden al clima y al suelo local: un hormigón de arena de invención propia que mezcla cemento y arena con tierra laterítica llena de guijarros, y que fija en el muro el color de la tierra roja de Benín. Los grandes voladizos, los patios y los volúmenes con luz cenital hacen el trabajo que en otros lugares hace el aire acondicionado. En 2023 recibió el León de Oro a la trayectoria en la Bienal de Venecia.',
      it: "Demas Nwoko arrivò all'architettura dalla pittura, dalla scultura e dalla scenografia. Membro fondatore della Zaria Art Society — i «ribelli di Zaria», che alla fine degli anni Cinquanta sostennero che gli artisti nigeriani dovessero sintetizzare la formazione europea con la forma nigeriana anziché copiare l'una o l'altra — costruì senza una qualifica formale di architetto, cosa che la storiografia architettonica nigeriana gli ha rimproverato e le giurie internazionali no. I suoi materiali rispondono al clima e al suolo del luogo: un sandcrete gettato di sua invenzione, che mescola cemento e sabbia con terra lateritica ricca di ciottoli e fissa nel muro il colore della terra rossa di Benin City. Sporti profondi, corti e volumi illuminati dall'alto svolgono il compito che altrove è dell'aria condizionata. Nel 2023 ha ricevuto il Leone d'Oro alla carriera alla Biennale di Venezia.",
    },
    awards: ['Golden Lion for Lifetime Achievement, Venice Architecture Biennale (2023)'],
    tier: 'canon',
    context: null,
    sources: [
      {
        kind: 'wikipedia',
        url: 'https://en.wikipedia.org/wiki/Demas_Nwoko',
        title: 'Demas Nwoko',
        license: 'CC BY-SA 4.0',
      },
      {
        kind: 'publication',
        url: 'https://www.stirworld.com/see-features-nigerian-architect-demas-nwoko-receives-the-2023-golden-lion-for-venice-biennale',
        title: 'Nigerian architect Demas Nwoko receives the 2023 Golden Lion for Venice Biennale — STIR',
        license: null,
      },
    ],
  },
  {
    id: 'tosin-oshinowo',
    wikidataId: 'Q57017047',
    name: 'Tosin Oshinowo',
    alternativeNames: ['Oluwatosin Oshinowo'],
    gender: 'woman',
    born: null,
    died: null,
    floruit: { start: 2016, end: 2023, override: false },
    movements: 'unaffiliated',
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'commercial',
    signatureMaterial: 'concrete',
    portrait: {
      en: "Tosin Oshinowo trained in London, worked briefly at Skidmore, Owings & Merrill and at OMA in Rotterdam, and returned to Lagos in 2009, joining James Cubitt Architects before founding her own practice, cmDesign Atelier, in 2012. Her Lagos work is commercial and residential, and her wider reputation rests on an argument as much as on buildings: that African design should be read as a discipline of adaptation and reuse rather than of scarcity. She also runs the furniture line Ile Ila, which builds on Yoruba seating types. In 2023 she was curator of the Sharjah Architecture Triennial, whose theme, The Beauty of Impermanence, set out that argument at scale. She is among the very small number of West African women architects with attributed built work in open sources.",
      es: 'Tosin Oshinowo se formó en Londres, trabajó brevemente en Skidmore, Owings & Merrill y en OMA en Róterdam, y regresó a Lagos en 2009; pasó por James Cubitt Architects antes de fundar su propio estudio, cmDesign Atelier, en 2012. Su obra lagosiana es comercial y residencial, y su prestigio más amplio se apoya tanto en un argumento como en los edificios: que el diseño africano debe leerse como una disciplina de adaptación y reutilización y no de escasez. Dirige además la línea de mobiliario Ile Ila, que parte de los tipos de asiento yoruba. En 2023 comisarió la Trienal de Arquitectura de Sharjah, cuyo tema, The Beauty of Impermanence, desplegó ese argumento a gran escala. Es una de las poquísimas arquitectas de África Occidental con obra construida atribuida en fuentes abiertas.',
      it: "Tosin Oshinowo si è formata a Londra, ha lavorato brevemente da Skidmore, Owings & Merrill e all'OMA di Rotterdam ed è tornata a Lagos nel 2009, passando per James Cubitt Architects prima di fondare il proprio studio, cmDesign Atelier, nel 2012. Il suo lavoro lagosiano è commerciale e residenziale, e la sua reputazione più ampia poggia su una tesi non meno che sugli edifici: che il progetto africano vada letto come una disciplina dell'adattamento e del riuso, non della penuria. Dirige inoltre la linea di arredi Ile Ila, che rielabora le tipologie di seduta yoruba. Nel 2023 ha curato la Triennale di Architettura di Sharjah, il cui tema, The Beauty of Impermanence, ha portato quella tesi su larga scala. È tra le pochissime architette dell'Africa occidentale con opere costruite attribuite in fonti aperte.",
    },
    awards: ['Curator, Sharjah Architecture Triennial (2023)'],
    tier: 'deep',
    context: null,
    sources: [
      {
        kind: 'wikipedia',
        url: 'https://en.wikipedia.org/wiki/Tosin_Oshinowo',
        title: 'Tosin Oshinowo',
        license: 'CC BY-SA 4.0',
      },
      {
        kind: 'publication',
        url: 'https://guardian.ng/features/they-said-i-couldnt-but-i-designed-a-landmark-that-left-my-naysayers-mesmerized-tosin-oshinowo-principal-architect-cmdesign-atelier/',
        title: 'Tosin Oshinowo, principal architect, cmDesign Atelier — The Guardian Nigeria',
        license: null,
      },
    ],
  },
  {
    id: 'ayuba',
    wikidataId: '',
    name: 'Ayuba',
    alternativeNames: ['Ayub'],
    gender: 'man',
    born: null,
    died: null,
    floruit: { start: 1421, end: 1421, override: false },
    movements: [{ id: 'earthen-vernacular', primary: true }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'sacral',
    signatureMaterial: 'earth',
    portrait: {
      en: 'Almost nothing is known of Ayuba beyond the story attached to his name. Local tradition in Larabanga, in Ghana\'s Savannah Region, remembers him as a Muslim trader travelling the old caravan routes north from the Ashanti forest, who stopped to rest near a stone still shown to visitors today. He is said to have dreamed there that he was commanded to build a mosque, and to have woken to find its foundations already laid — a story that explains an origin nobody recorded at the time rather than one that can be independently verified. What is not legend is that a mosque of this form has stood at Larabanga since at least the early modern period, making it the oldest in Ghana. Ayuba is said to be buried beside it, his grave marked by a baobab the community has protected for generations.',
      es: 'Casi nada se sabe de Ayuba más allá de la historia unida a su nombre. La tradición local de Larabanga, en la Región de la Sabana de Ghana, lo recuerda como un comerciante musulmán que recorría las antiguas rutas de caravanas al norte del bosque asante y que se detuvo a descansar junto a una piedra que todavía hoy se muestra a los visitantes. Se dice que allí soñó que se le ordenaba construir una mezquita, y que al despertar encontró ya trazados los cimientos: un relato que explica un origen que nadie registró en su momento, más que un hecho verificable de forma independiente. Lo que no es leyenda es que una mezquita de esta forma se alza en Larabanga desde al menos la primera Edad Moderna, lo que la convierte en la más antigua de Ghana. Se dice que Ayuba está enterrado junto a ella, con la tumba señalada por un baobab que la comunidad ha protegido durante generaciones.',
      it: "Di Ayuba non si sa quasi nulla al di là della storia legata al suo nome. La tradizione locale di Larabanga, nella Regione della Savana del Ghana, lo ricorda come un mercante musulmano che percorreva le antiche vie carovaniere a nord della foresta ashanti e che si fermò a riposare presso una pietra ancora oggi mostrata ai visitatori. Si narra che lì sognò di essere stato incaricato di costruire una moschea, e che al risveglio trovò le fondamenta già tracciate: un racconto che spiega un'origine che nessuno registrò all'epoca, più che un fatto verificabile in modo indipendente. Ciò che non è leggenda è che una moschea di questa forma sorge a Larabanga almeno dalla prima età moderna, il che ne fa la più antica del Ghana. Si dice che Ayuba sia sepolto accanto ad essa, con la tomba segnata da un baobab che la comunità protegge da generazioni.",
    },
    awards: [],
    tier: 'deep',
    context: null,
    sources: [
      {
        kind: 'wikipedia',
        url: 'https://en.wikipedia.org/wiki/Larabanga_Mosque',
        title: 'Larabanga Mosque',
        license: 'CC BY-SA 4.0',
      },
    ],
  },
  {
    id: 'diogo-de-azambuja',
    wikidataId: 'Q1226869',
    name: 'Diogo de Azambuja',
    alternativeNames: ["Diogo d'Azambuja", 'Dom Diogo de Azambuja'],
    gender: 'man',
    born: 1432,
    died: 1518,
    floruit: { start: 1481, end: 1482, override: false },
    movements: 'unaffiliated',
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'civic',
    signatureMaterial: 'stone',
    portrait: {
      en: 'Diogo de Azambuja was a Portuguese knight of the Order of Aviz, a veteran of the succession wars in Castile and of Portugal\'s North African campaigns, when King John II gave him command of the 1481 expedition to build a fortified trading post on the Gulf of Guinea. He was not an architect by training; his task was logistical and military — land nine caravels carrying two hundred masons and carpenters and stone pre-cut in Portugal, secure a site from a wary local ruler, and see the walls assembled before the rains or resistance stopped him. He succeeded within about three weeks and stayed on as the fort\'s first captain. He later built a second Portuguese fort at Essaouira, on the Moroccan coast, in his seventies, and ended his career as a royal councillor.',
      es: 'Diogo de Azambuja fue un caballero portugués de la Orden de Avís, veterano de las guerras de sucesión en Castilla y de las campañas portuguesas en el norte de África, cuando el rey Juan II le dio el mando de la expedición de 1481 para construir un puesto comercial fortificado en el golfo de Guinea. No era arquitecto de formación; su tarea fue logística y militar: desembarcar nueve carabelas con doscientos canteros y carpinteros y piedra cortada de antemano en Portugal, asegurar un emplazamiento ante un gobernante local receloso y ver alzados los muros antes de que las lluvias o la resistencia lo impidieran. Lo logró en unas tres semanas y permaneció como primer capitán del fuerte. Más tarde, ya en la setentena, construyó una segunda fortaleza portuguesa en Essaouira, en la costa marroquí, y terminó su carrera como consejero real.',
      it: "Diogo de Azambuja fu un cavaliere portoghese dell'Ordine di Avis, veterano delle guerre di successione in Castiglia e delle campagne portoghesi nel nord Africa, quando il re Giovanni II gli affidò il comando della spedizione del 1481 per costruire un avamposto commerciale fortificato nel golfo di Guinea. Non era architetto di formazione; il suo compito fu logistico e militare: sbarcare nove caravelle con duecento tra muratori e carpentieri e pietra già tagliata in Portogallo, assicurarsi il sito da un sovrano locale diffidente e veder alzate le mura prima che le piogge o la resistenza locale lo fermassero. Ci riuscì in circa tre settimane e rimase come primo capitano del forte. Più tardi, ormai settantenne, costruì una seconda fortezza portoghese a Essaouira, sulla costa marocchina, e concluse la carriera come consigliere reale.",
    },
    awards: [],
    tier: 'canon',
    context: null,
    sources: [
      {
        kind: 'wikipedia',
        url: 'https://en.wikipedia.org/wiki/Diogo_de_Azambuja',
        title: 'Diogo de Azambuja',
        license: 'CC BY-SA 4.0',
      },
      {
        kind: 'wikidata',
        url: 'https://www.wikidata.org/wiki/Q1226869',
        title: 'Diogo de Azambuja (Q1226869)',
        license: null,
      },
    ],
  },
];
