import type { Architect } from '@/types/architect';

// Wave 5 curator agent (East and Southern Africa): real, sourced Architect entries for this slice.
//
// Wikidata's coverage of attributed architecture in this region is thin, and
// several of the people below carry almost no structured data at all: Janina
// Masojada has no Wikidata item, and neither her birth year nor Jo Noero's is
// recorded in any source consulted, so `born` is left null rather than
// guessed. Sophy Gray's authorship of her churches is itself contested in the
// literature and her portrait says so. Where Wikidata is absent or wrong the
// metadata here is hand-authored from the published sources cited on each
// entry — see the task report for the full list.
//
// `workRegions` and `workCentroid` are deliberately left empty/zeroed: the
// curation script derives both from each architect's buildings and overwrites
// whatever is typed here.
export const AFRICA_EASTSOUTH_ARCHITECTS: Architect[] = [
  {
    id: 'giovanni-battista-cairati',
    wikidataId: 'Q10289884',
    name: 'Giovanni Battista Cairati',
    alternativeNames: ['João Baptista Cairato', 'Giovanni Battista Cairato', 'João Batista Cairato'],
    gender: 'man',
    born: 1550,
    died: 1596,
    floruit: { start: 1560, end: 1596, override: false },
    movements: [{ id: 'renaissance', primary: true }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'civic',
    signatureMaterial: 'stone',
    portrait: {
      en: 'Giovanni Battista Cairati, known in Portuguese service as João Baptista Cairato, was born at Cairate in Lombardy and learned his trade fortifying Malta and Sardinia for the Knights Hospitaller before directing the defence works of Milan through the 1560s. He entered the service of Philip II in 1577 and in 1583 was appointed chief engineer of the Estado da Índia, charged with rebuilding the Portuguese fortresses of the Indian Ocean to the angled-bastion geometry of the trace italienne. For a decade he worked between Vasai, Daman, Hormuz, Muscat, Mannar and Malacca. In about 1593 he chose the site and set out the plan of Fort Jesus at Mombasa, his last known work; he died at Goa in 1596, probably without seeing it finished, and was succeeded by Julio Simão.',
      es: 'Giovanni Battista Cairati, conocido al servicio portugués como João Baptista Cairato, nació en Cairate, en Lombardía, y aprendió el oficio fortificando Malta y Cerdeña para los Caballeros Hospitalarios antes de dirigir las obras de defensa de Milán durante la década de 1560. Entró al servicio de Felipe II en 1577 y en 1583 fue nombrado ingeniero jefe del Estado da Índia, con el encargo de rehacer las fortalezas portuguesas del océano Índico según la geometría de baluartes angulares de la traza italiana. Durante una década trabajó entre Vasai, Damán, Ormuz, Mascate, Mannar y Malaca. Hacia 1593 escogió el emplazamiento y trazó la planta del fuerte Jesús de Mombasa, su última obra conocida; murió en Goa en 1596, probablemente sin verla terminada, y le sucedió Julio Simão.',
      it: "Giovanni Battista Cairati, noto al servizio portoghese come João Baptista Cairato, nacque a Cairate, in Lombardia, e imparò il mestiere fortificando Malta e la Sardegna per i Cavalieri Ospitalieri, prima di dirigere le opere difensive di Milano negli anni Sessanta del Cinquecento. Entrò al servizio di Filippo II nel 1577 e nel 1583 fu nominato ingegnere capo dell'Estado da Índia, con l'incarico di rifare le fortezze portoghesi dell'oceano Indiano secondo la geometria a bastioni angolari della trace italienne. Per un decennio lavorò fra Vasai, Daman, Hormuz, Mascate, Mannar e Malacca. Verso il 1593 scelse il sito e tracciò la pianta del Forte Gesù di Mombasa, la sua ultima opera nota; morì a Goa nel 1596, probabilmente senza vederla compiuta, e gli successe Julio Simão.",
    },
    awards: [],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q10289884', title: 'Giovanni Battista Cairati (Q10289884)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Giovanni_Battista_Cairati', title: 'Giovanni Battista Cairati', license: 'CC BY-SA 4.0' },
      { kind: 'publication', url: 'https://search.worldcat.org/title/1067327', title: 'James S. Kirkman, Fort Jesus: A Portuguese Fortress on the East African Coast (Oxford: Clarendon Press, 1974)', license: null },
    ],
  },
  {
    id: 'louis-michel-thibault',
    wikidataId: 'Q2604850',
    name: 'Louis Michel Thibault',
    alternativeNames: ['Louis-Michel Thibault'],
    gender: 'man',
    born: 1750,
    died: 1815,
    floruit: { start: 1786, end: 1815, override: false },
    movements: [{ id: 'neoclassicism', primary: true }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'civic',
    signatureMaterial: 'stone',
    portrait: {
      en: "Louis Michel Thibault trained at the royal academy of architecture in Paris under Ange-Jacques Gabriel, then studied military engineering and took a commission in the Swiss de Meuron regiment, reaching the Cape of Good Hope in 1783. He transferred to the Dutch East India Company in 1785 and was appointed its inspector of buildings the following year; until the Company's finances collapsed in 1790 he designed every new public work at the Cape, and private commissions carried him on afterwards. He was the colony's first academically trained architect, and the mannered neoclassicism he brought with him sat deliberately against the curved gables of Cape Dutch building. He worked repeatedly with the Freiburg sculptor Anton Anreith and the Bremen builder Hermann Schutte. Thibault died at the Cape in 1815.",
      es: 'Louis Michel Thibault se formó en la Real Academia de Arquitectura de París con Ange-Jacques Gabriel, estudió después ingeniería militar y obtuvo un despacho en el regimiento suizo de Meuron, con el que llegó al Cabo de Buena Esperanza en 1783. Pasó al servicio de la Compañía Neerlandesa de las Indias Orientales en 1785 y al año siguiente fue nombrado inspector de obras; hasta la quiebra de la Compañía en 1790 proyectó todos los edificios públicos nuevos del Cabo, y después siguió trabajando por encargo privado. Fue el primer arquitecto de formación académica de la colonia, y el neoclasicismo manierista que trajo consigo contrastaba a propósito con los hastiales curvos de la arquitectura neerlandesa del Cabo. Colaboró una y otra vez con el escultor friburgués Anton Anreith y el constructor bremense Hermann Schutte. Murió en el Cabo en 1815.',
      it: "Louis Michel Thibault si formò alla Reale Accademia di Architettura di Parigi sotto Ange-Jacques Gabriel, studiò poi ingegneria militare e ottenne un brevetto nel reggimento svizzero de Meuron, con cui raggiunse il Capo di Buona Speranza nel 1783. Passò alla Compagnia olandese delle Indie orientali nel 1785 e l'anno seguente ne divenne ispettore delle costruzioni; fino al tracollo finanziario della Compagnia nel 1790 progettò ogni nuovo edificio pubblico del Capo, e in seguito continuò su commissione privata. Fu il primo architetto di formazione accademica della colonia, e il neoclassicismo manierato che portò con sé si opponeva volutamente ai frontoni curvi dell'architettura olandese del Capo. Lavorò più volte con lo scultore friburghese Anton Anreith e il costruttore bremense Hermann Schutte. Morì al Capo nel 1815.",
    },
    awards: [],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q2604850', title: 'Louis Michel Thibault (Q2604850)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Louis_Michel_Thibault', title: 'Louis Michel Thibault', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'giuseppe-pettazzi',
    wikidataId: 'Q5565500',
    name: 'Giuseppe Pettazzi',
    alternativeNames: [],
    gender: 'man',
    born: 1907,
    died: 2001,
    floruit: { start: 1935, end: 1941, override: false },
    movements: [
      { id: 'art-deco', primary: true },
      { id: 'functionalism', primary: false },
    ],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'commercial',
    signatureMaterial: 'concrete',
    portrait: {
      en: 'Giuseppe Pettazzi was an Italian civil engineer who spent the late 1930s building in Italian Eritrea, in a city that Europeans, as its historians put it, used to experiment with radical new designs. He is remembered for one of them. The Fiat Tagliero service station of 1938 carries two reinforced-concrete wings, each about fifteen metres long, cantilevered from a central glazed tower with nothing at all beneath them. The story that Pettazzi settled the argument over the temporary props at gunpoint is repeated in every account of the building and cannot be verified; what is documented is that the original drawings, rediscovered in 2001, show permanent supports that were never built. He lived until 2001 and died at ninety-four, long enough to see his petrol station become the emblem of a city he had helped to make.',
      es: 'Giuseppe Pettazzi fue un ingeniero civil italiano que pasó los últimos años treinta construyendo en la Eritrea italiana, en una ciudad que los europeos, según sus historiadores, emplearon para ensayar diseños radicalmente nuevos. Se le recuerda por uno de ellos. La gasolinera Fiat Tagliero, de 1938, sostiene dos alas de hormigón armado de unos quince metros cada una, en voladizo desde una torre acristalada central y sin nada debajo. La anécdota de que Pettazzi zanjó a punta de pistola la discusión sobre los apeos provisionales se repite en todos los relatos del edificio y no puede verificarse; lo documentado es que los planos originales, reaparecidos en 2001, dibujan unos soportes permanentes que nunca se construyeron. Vivió hasta 2001 y murió a los noventa y cuatro años, el tiempo suficiente para ver su gasolinera convertida en emblema de una ciudad que él había ayudado a hacer.',
      it: "Giuseppe Pettazzi fu un ingegnere civile italiano che passò la fine degli anni Trenta a costruire nell'Eritrea italiana, in una città che gli europei, come scrivono i suoi storici, usarono per sperimentare progetti radicalmente nuovi. Di uno di questi si ricorda. La stazione di servizio Fiat Tagliero del 1938 regge due ali in cemento armato, lunghe circa quindici metri ciascuna, a sbalzo da una torre vetrata centrale e senza nulla al di sotto. L'aneddoto secondo cui Pettazzi risolse a colpi di pistola la disputa sui puntelli provvisori ricorre in ogni racconto dell'edificio e non è verificabile; è invece documentato che i disegni originali, ritrovati nel 2001, prevedevano appoggi permanenti mai costruiti. Visse fino al 2001 e morì a novantaquattro anni, in tempo per vedere il suo distributore diventare l'emblema di una città che aveva contribuito a fare.",
    },
    awards: [],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q5565500', title: 'Giuseppe Pettazzi (Q5565500)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Giuseppe_Pettazzi', title: 'Giuseppe Pettazzi', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Fiat_Tagliero_Building', title: 'Fiat Tagliero Building', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'sophy-gray',
    wikidataId: 'Q7563156',
    name: 'Sophy Gray',
    alternativeNames: ['Sophia Gray', 'Sophia Wharton Myddleton Gray'],
    gender: 'woman',
    born: 1814,
    died: 1871,
    floruit: { start: 1848, end: 1871, override: false },
    movements: [{ id: 'gothic-revival', primary: true }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'sacral',
    signatureMaterial: 'stone',
    portrait: {
      en: "Sophy Gray, born Sophia Wharton Myddleton in Yorkshire in 1814, married Robert Gray in 1836 and sailed with him to Cape Town in 1847 when he was appointed the first colonial bishop of the Cape. She took with her a stock of English church plans, largely ecclesiological Gothic Revival, and spent the next twenty-four years adapting them to Cape sites, Cape stone and Cape thatch, while also keeping the diocese's records, accounts and correspondence and riding with her husband on all but two of his visitations. Desmond Martin's research attributes at least forty of the roughly fifty churches built during Robert Gray's episcopate to her. The attribution is contested: only eleven of her drawings survive, and Martin's argument that her role was deliberately suppressed has been challenged from the bishop's own correspondence. She died at Bishopscourt in 1871.",
      es: 'Sophy Gray, nacida Sophia Wharton Myddleton en Yorkshire en 1814, se casó con Robert Gray en 1836 y se embarcó con él hacia Ciudad del Cabo en 1847, recién nombrado él primer obispo colonial del Cabo. Llevó consigo un repertorio de plantas de iglesias inglesas, casi todas de neogótico eclesiológico, y pasó veinticuatro años adaptándolas a los solares, la piedra y la paja del Cabo, mientras llevaba las actas, las cuentas y la correspondencia de la diócesis y acompañaba a caballo a su marido en todas sus visitas pastorales salvo dos. Desmond Martin le atribuye al menos cuarenta de la cincuentena de iglesias levantadas durante el episcopado de Robert Gray. La atribución está discutida: solo se conservan once de sus dibujos, y el argumento de Martin de que su papel fue deliberadamente silenciado ha sido rebatido a partir de la propia correspondencia del obispo. Murió en Bishopscourt en 1871.',
      it: "Sophy Gray, nata Sophia Wharton Myddleton nello Yorkshire nel 1814, sposò Robert Gray nel 1836 e s'imbarcò con lui per Città del Capo nel 1847, quando egli fu nominato primo vescovo coloniale del Capo. Portò con sé un repertorio di piante di chiese inglesi, quasi tutte di neogotico ecclesiologico, e passò i ventiquattro anni successivi ad adattarle ai lotti, alla pietra e alla paglia del Capo, tenendo insieme i verbali della diocesi, i conti e la corrispondenza e accompagnando a cavallo il marito in tutte le visite pastorali tranne due. Le ricerche di Desmond Martin le attribuiscono almeno quaranta della cinquantina di chiese costruite durante l'episcopato di Robert Gray. L'attribuzione è controversa: sopravvivono soltanto undici dei suoi disegni, e la tesi di Martin secondo cui il suo ruolo fu deliberatamente taciuto è stata contestata sulla base della corrispondenza dello stesso vescovo. Morì a Bishopscourt nel 1871.",
    },
    awards: [],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q7563156', title: 'Sophy Gray (Q7563156)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Sophy_Gray', title: 'Sophy Gray', license: 'CC BY-SA 4.0' },
      { kind: 'publication', url: 'https://open.uct.ac.za/handle/11427/10637', title: 'Desmond K. Martin, The churches of Bishop Robert Gray & Mrs Sophia Gray: an historical and architectural review (University of Cape Town)', license: null },
      { kind: 'publication', url: 'https://sheffieldgenderhistory.hcommons.org/?p=57', title: 'Discovering Sophia Gray (1814–1871): British Cape Colony "Architect to the Diocese", Sheffield Gender History Journal', license: null },
    ],
  },
  {
    id: 'gottlieb-redecker',
    wikidataId: 'Q77806',
    name: 'Gottlieb Redecker',
    alternativeNames: ['Gottlieb Wilhelm Eduard Redecker'],
    gender: 'man',
    born: 1871,
    died: 1945,
    floruit: { start: 1901, end: 1930, override: false },
    movements: [
      { id: 'gothic-revival', primary: true },
      { id: 'art-nouveau', primary: false },
    ],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'civic',
    signatureMaterial: 'stone',
    portrait: {
      en: 'Gottlieb Wilhelm Eduard Redecker was born in 1871 at Otjimbingwe, then the effective capital of German South West Africa, the eldest of seven children of a Rhenish missionary family from Westphalia. He was among the first pupils of the Augustineum school, spoke Herero and Damara fluently, and — having lost through long absence the German citizenship inherited from his father — was for a period classified as a Damara by the colonial administration. He trained as an engineer in Germany, returned, and in 1901 was appointed director of engineering by the imperial government, becoming in effect the territory’s first architect. The two buildings that fix Windhoek in the mind are his: the Christuskirche of 1907–10, neo-Romanesque with Jugendstil detail, and the Tintenpalast of 1912–13, still the seat of Namibia’s parliament. He died in Germany in 1945.',
      es: 'Gottlieb Wilhelm Eduard Redecker nació en 1871 en Otjimbingwe, entonces capital efectiva del África del Sudoeste Alemana, primero de los siete hijos de una familia de misioneros renanos procedentes de Westfalia. Fue de los primeros alumnos de la escuela Augustineum, hablaba herero y damara con soltura y, tras perder por larga ausencia la ciudadanía alemana heredada de su padre, la administración colonial lo clasificó durante un tiempo como damara. Se formó como ingeniero en Alemania, regresó y en 1901 fue nombrado director de obras públicas por el gobierno imperial, convirtiéndose de hecho en el primer arquitecto del territorio. Los dos edificios que fijan Windhoek en la memoria son suyos: la Christuskirche de 1907-1910, neorrománica con detalle modernista, y el Tintenpalast de 1912-1913, todavía sede del parlamento de Namibia. Murió en Alemania en 1945.',
      it: "Gottlieb Wilhelm Eduard Redecker nacque nel 1871 a Otjimbingwe, allora capitale di fatto dell'Africa Tedesca del Sud-Ovest, primo di sette figli di una famiglia di missionari renani venuti dalla Vestfalia. Fu tra i primi allievi della scuola Augustineum, parlava correntemente herero e damara e, avendo perduto per lunga assenza la cittadinanza tedesca ereditata dal padre, fu per un periodo classificato come damara dall'amministrazione coloniale. Si formò come ingegnere in Germania, tornò e nel 1901 fu nominato direttore dei lavori pubblici dal governo imperiale, diventando di fatto il primo architetto del territorio. I due edifici che fissano Windhoek nella memoria sono suoi: la Christuskirche del 1907-1910, neoromanica con dettagli Jugendstil, e il Tintenpalast del 1912-1913, tuttora sede del parlamento della Namibia. Morì in Germania nel 1945.",
    },
    awards: [],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q77806', title: 'Gottlieb Redecker (Q77806)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Gottlieb_Redecker', title: 'Gottlieb Redecker', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'karl-henrik-nostvik',
    wikidataId: 'Q11980252',
    name: 'Karl Henrik Nøstvik',
    alternativeNames: ['Karl Henrik Nostvik'],
    gender: 'man',
    born: 1925,
    died: 1992,
    floruit: { start: 1965, end: 1990, override: false },
    movements: [{ id: 'brutalism', primary: true }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'civic',
    signatureMaterial: 'concrete',
    portrait: {
      en: 'Karl Henrik Nøstvik reached Kenya in 1965 with the first group of Norwegian experts sent out by the Norwegian aid programme after independence. He stayed. When the contract ended he opened his own architectural office in Nairobi and worked from there for the rest of his life, which makes him a Kenyan architect by every measure except passport. Jomo Kenyatta asked him for a headquarters for the governing KANU party; what was built, in three phases between 1967 and 1973, was the Kenyatta International Conference Centre — a cylindrical thirty-two-storey tower faced in pale terracotta, a conical amphitheatre and a cuboid plenary hall, designed with the Kenyan architect David Mutiso. It was the tallest building in the country for twenty-six years and is still the emblem of Nairobi. Nøstvik died in 1992.',
      es: 'Karl Henrik Nøstvik llegó a Kenia en 1965 con el primer grupo de expertos noruegos enviado por la cooperación de Noruega tras la independencia. Se quedó. Al terminar el contrato abrió su propio estudio de arquitectura en Nairobi y trabajó desde allí el resto de su vida, lo que lo convierte en arquitecto keniano por todos los criterios salvo el pasaporte. Jomo Kenyatta le pidió una sede para el partido gobernante, la KANU; lo que se construyó, en tres fases entre 1967 y 1973, fue el Centro Internacional de Conferencias Kenyatta: una torre cilíndrica de treinta y dos plantas revestida de terracota clara, un anfiteatro cónico y una sala plenaria cúbica, proyectados junto al arquitecto keniano David Mutiso. Fue el edificio más alto del país durante veintiséis años y sigue siendo el emblema de Nairobi. Nøstvik murió en 1992.',
      it: "Karl Henrik Nøstvik arrivò in Kenya nel 1965 con il primo gruppo di esperti norvegesi inviato dalla cooperazione di Oslo dopo l'indipendenza. Rimase. Terminato il contratto aprì un proprio studio di architettura a Nairobi e vi lavorò per il resto della vita, il che ne fa un architetto keniano sotto ogni profilo tranne il passaporto. Jomo Kenyatta gli chiese una sede per il partito di governo, la KANU; quello che fu costruito, in tre fasi fra il 1967 e il 1973, è il Kenyatta International Conference Centre: una torre cilindrica di trentadue piani rivestita di terracotta chiara, un anfiteatro conico e un'aula plenaria cuboide, progettati insieme all'architetto keniano David Mutiso. Fu l'edificio più alto del paese per ventisei anni ed è ancora l'emblema di Nairobi. Nøstvik morì nel 1992.",
    },
    awards: [],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q11980252', title: 'Karl Henrik Nøstvik (Q11980252)', license: null },
      { kind: 'wikipedia', url: 'https://no.wikipedia.org/wiki/Karl_Henrik_N%C3%B8stvik', title: 'Karl Henrik Nøstvik (Norwegian Wikipedia)', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Kenyatta_International_Convention_Centre', title: 'Kenyatta International Convention Centre', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'pancho-guedes',
    wikidataId: 'Q7130356',
    name: 'Pancho Guedes',
    alternativeNames: ['Amâncio d’Alpoim Miranda Guedes', 'Amancio Guedes'],
    gender: 'man',
    born: 1925,
    died: 2015,
    floruit: { start: 1951, end: 1985, override: false },
    movements: 'unaffiliated',
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'housing',
    signatureMaterial: 'concrete',
    portrait: {
      en: 'Amâncio d’Alpoim Miranda Guedes, always Pancho, was born in Lisbon in 1925 and taken to Mozambique at seven. He went to the University of the Witwatersrand meaning to be an artist and settled on architecture as the trade that contained all the others. From about 1950 he produced several hundred designs, most of them in Lourenço Marques, now Maputo: apartment blocks, a bakery, churches, houses, whose forms arrive from Picasso, Miró, surrealism, Makonde carving and his own children’s drawings in roughly equal measure. He named the result Stiloguedes and refused every other label, which is why this pool assigns him none. He belonged to Team 10 from the 1950s, worked pro bono on the campus of Waterford Kamhlaba, the first multiracial school in southern Africa, and died at Graaff-Reinet in the South African Karoo in 2015.',
      es: 'Amâncio d’Alpoim Miranda Guedes, siempre Pancho, nació en Lisboa en 1925 y fue llevado a Mozambique con siete años. Entró en la Universidad de Witwatersrand queriendo ser artista y se decidió por la arquitectura como el oficio que contenía a todos los demás. Desde 1950 aproximadamente produjo varios centenares de proyectos, la mayoría en Lourenço Marques, hoy Maputo: bloques de viviendas, una panadería, iglesias, casas, cuyas formas proceden a partes casi iguales de Picasso, Miró, el surrealismo, la talla makonde y los dibujos de sus propios hijos. Llamó Stiloguedes al resultado y rechazó cualquier otra etiqueta, razón por la cual aquí no se le asigna ninguna. Perteneció al Team 10 desde los años cincuenta, trabajó sin cobrar en el campus de Waterford Kamhlaba, la primera escuela multirracial del África austral, y murió en Graaff-Reinet, en el Karoo sudafricano, en 2015.',
      it: "Amâncio d’Alpoim Miranda Guedes, per tutti Pancho, nacque a Lisbona nel 1925 e fu portato in Mozambico a sette anni. Entrò all'Università del Witwatersrand volendo fare l'artista e scelse l'architettura come il mestiere che conteneva tutti gli altri. Dal 1950 circa produsse diverse centinaia di progetti, per lo più a Lourenço Marques, oggi Maputo: palazzine, un panificio, chiese, case, le cui forme vengono in parti quasi uguali da Picasso, Miró, il surrealismo, la scultura makonde e i disegni dei suoi stessi figli. Chiamò Stiloguedes il risultato e rifiutò ogni altra etichetta: per questo qui non gliene viene attribuita alcuna. Fece parte del Team 10 dagli anni Cinquanta, lavorò gratuitamente al campus di Waterford Kamhlaba, prima scuola multirazziale dell'Africa australe, e morì a Graaff-Reinet, nel Karoo sudafricano, nel 2015.",
    },
    awards: [],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q7130356', title: 'Pancho Guedes (Q7130356)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Pancho_Guedes', title: 'Pancho Guedes', license: 'CC BY-SA 4.0' },
      { kind: 'institution', url: 'https://hpip.org/en/heritage/details/116', title: '"O Leão Que Ri" Residential Building, Heritage of Portuguese Influence Portal (HPIP), Calouste Gulbenkian Foundation', license: null },
    ],
  },
  {
    id: 'mick-pearce',
    wikidataId: 'Q2140435',
    name: 'Mick Pearce',
    alternativeNames: [],
    gender: 'man',
    born: 1938,
    died: null,
    floruit: { start: 1972, end: 2015, override: false },
    movements: [
      { id: 'sustainable-architecture', primary: true },
      { id: 'critical-regionalism', primary: false },
    ],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'commercial',
    signatureMaterial: 'concrete',
    portrait: {
      en: 'Mick Pearce was born in Salisbury, now Harare, in 1938 and took his diploma with distinction at the Architectural Association in London in 1962. He has built in Britain, Zambia, Zimbabwe, South Africa, Australia and China, and for four decades has worked almost entirely on one problem: how to condition a building without machinery. His method is biomimicry taken literally rather than decoratively — the ventilation logic of a termite mound, local materials, and old devices such as windmills in place of imported plant. The Eastgate Centre in Harare, completed in 1996 with the engineers Arup, is the demonstration piece, and uses roughly a tenth of the ventilation energy of a comparable air-conditioned building. He left Zimbabwe in 2000, co-designed Council House 2 in Melbourne, spent three years with Vanke in China and returned home in 2012.',
      es: 'Mick Pearce nació en Salisbury, hoy Harare, en 1938 y obtuvo su diploma con distinción en la Architectural Association de Londres en 1962. Ha construido en el Reino Unido, Zambia, Zimbabue, Sudáfrica, Australia y China, y desde hace cuatro décadas trabaja casi exclusivamente sobre un problema: cómo acondicionar un edificio sin máquinas. Su método es la biomímesis entendida al pie de la letra y no como ornamento: la lógica de ventilación de un termitero, los materiales locales y artefactos antiguos como los molinos de viento en lugar de instalaciones importadas. El Eastgate Centre de Harare, terminado en 1996 con los ingenieros de Arup, es la pieza demostrativa y consume alrededor de la décima parte de la energía de ventilación de un edificio climatizado equivalente. Dejó Zimbabue en 2000, codiseñó el Council House 2 de Melbourne, pasó tres años con Vanke en China y regresó a su país en 2012.',
      it: "Mick Pearce nacque a Salisbury, oggi Harare, nel 1938 e ottenne il diploma con lode all'Architectural Association di Londra nel 1962. Ha costruito in Gran Bretagna, Zambia, Zimbabwe, Sudafrica, Australia e Cina, e da quarant'anni lavora quasi esclusivamente su un problema: come climatizzare un edificio senza macchine. Il suo metodo è la biomimesi presa alla lettera e non come ornamento: la logica di ventilazione di un termitaio, i materiali locali e dispositivi antichi come i mulini a vento al posto degli impianti importati. L'Eastgate Centre di Harare, completato nel 1996 con gli ingegneri di Arup, ne è la dimostrazione e consuma circa un decimo dell'energia di ventilazione di un edificio climatizzato paragonabile. Lasciò lo Zimbabwe nel 2000, co-progettò il Council House 2 di Melbourne, passò tre anni con Vanke in Cina e tornò in patria nel 2012.",
    },
    awards: ['Prince Claus Award (2003)'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q2140435', title: 'Mick Pearce (Q2140435)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Mick_Pearce', title: 'Mick Pearce', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'dorothy-hughes',
    wikidataId: 'Q21176339',
    name: 'Dorothy Hughes',
    alternativeNames: ['Eugenie Dorothy Hughes', 'Eugenie Dorothy Ullmann'],
    gender: 'woman',
    born: 1910,
    died: 1987,
    floruit: { start: 1938, end: 1970, override: false },
    movements: [{ id: 'international-style', primary: true }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'civic',
    signatureMaterial: 'concrete',
    portrait: {
      en: 'Eugenie Dorothy Hughes, born Ullmann in London in 1910, was taken as a child to Eldoret in the Rift Valley, returned to London to study at the Architectural Association, and came back to Kenya to practise. She was the first woman to work as an architect in East Africa, became a Fellow of the Royal Institute of British Architects in 1946, and ran her own firm, Hughes and Polkinghorne, designing hospitals, hotels, schools and clubs across the colony; she was appointed MBE in 1950 for her hospital work. Her largest building is the Cathedral of the Holy Family in Nairobi, designed in 1960 and seating four thousand under non-figurative glass. She sat on Nairobi City Council and then the Legislative Council, attended the 1960 Lancaster House conference on Kenyan independence, and spent her later years on social welfare and disability work. She died in 1987.',
      es: 'Eugenie Dorothy Hughes, de soltera Ullmann, nació en Londres en 1910, creció en Eldoret, en el valle del Rift, volvió a Londres para estudiar en la Architectural Association y regresó a Kenia a ejercer. Fue la primera mujer que ejerció la arquitectura en África oriental, ingresó en el Royal Institute of British Architects en 1946 y dirigió su estudio, Hughes and Polkinghorne, con hospitales, hoteles, escuelas y clubes por toda la colonia; en 1950 fue nombrada MBE por su trabajo hospitalario. Su edificio mayor es la catedral de la Sagrada Familia de Nairobi, proyectada en 1960, con cuatro mil asientos bajo vidrieras no figurativas. Fue concejala de Nairobi y después miembro del Consejo Legislativo, asistió en 1960 a la conferencia de Lancaster House sobre la independencia de Kenia y dedicó sus últimos años a la acción social y a los derechos de las personas con discapacidad. Murió en 1987.',
      it: "Eugenie Dorothy Hughes, nata Ullmann a Londra nel 1910, fu portata da bambina a Eldoret, nella Rift Valley, tornò a Londra per studiare all'Architectural Association e rientrò in Kenya per esercitare. Fu la prima donna a lavorare come architetto in Africa orientale, divenne Fellow del Royal Institute of British Architects nel 1946 e diresse un proprio studio, Hughes and Polkinghorne, con ospedali, alberghi, scuole e circoli in tutta la colonia; nel 1950 fu nominata MBE per il lavoro ospedaliero. Il suo edificio maggiore è la cattedrale della Sacra Famiglia di Nairobi, progettata nel 1960, con quattromila posti sotto vetrate non figurative. Sedette nel consiglio comunale di Nairobi e poi nel Consiglio legislativo, partecipò nel 1960 alla conferenza di Lancaster House sull'indipendenza del Kenya e dedicò gli ultimi anni all'assistenza sociale e ai diritti delle persone con disabilità. Morì nel 1987.",
    },
    awards: ['Fellow of the Royal Institute of British Architects (1946)', 'MBE (1950)'],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q21176339', title: 'Dorothy Hughes (Q21176339)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Dorothy_Hughes_(architect)', title: 'Dorothy Hughes (architect)', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'maria-carlota-quintanilha',
    wikidataId: 'Q22344586',
    name: 'Maria Carlota Quintanilha',
    alternativeNames: ['Carlota Quintanilha'],
    gender: 'woman',
    born: 1923,
    died: 2015,
    floruit: { start: 1955, end: 1974, override: false },
    movements: [{ id: 'tropical-modernism', primary: true }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'infrastructure',
    signatureMaterial: 'concrete',
    portrait: {
      en: 'Maria Carlota Quintanilha, born in 1923, belonged to the small cohort of women who qualified as architects in Portugal and then found their openings in the African colonies, where the demand for building ran far ahead of the supply of designers. From the mid-1950s she worked for the civil aviation service of Portuguese Mozambique alongside João José Tinoco and Alberto Soeiro, and between 1959 and 1970 the three of them designed the airports of Nampula and Porto Amélia, now Pemba. Her other Mozambican work is administrative: the government headquarters at Porto Amélia of 1963, the Cabo Delgado district offices of 1965, and the Palácio das Repartições at Vila Cabral, now Lichinga, built between 1962 and 1966. She died in 2015. In 2020 the Faculty of Architecture of the University of Lisbon founded a merit award in her name.',
      es: 'Maria Carlota Quintanilha, nacida en 1923, formó parte del reducido grupo de mujeres que se titularon en arquitectura en Portugal y encontraron después su hueco en las colonias africanas, donde la demanda de construcción superaba con mucho la oferta de proyectistas. Desde mediados de los años cincuenta trabajó para el servicio de aeronáutica civil del Mozambique portugués junto a João José Tinoco y Alberto Soeiro, y entre 1959 y 1970 los tres proyectaron los aeropuertos de Nampula y Porto Amélia, hoy Pemba. El resto de su obra mozambiqueña es administrativa: la sede del gobierno de Porto Amélia de 1963, las oficinas del distrito de Cabo Delgado de 1965 y el Palácio das Repartições de Vila Cabral, hoy Lichinga, levantado entre 1962 y 1966. Murió en 2015. En 2020 la Facultad de Arquitectura de la Universidad de Lisboa creó un premio de mérito con su nombre.',
      it: "Maria Carlota Quintanilha, nata nel 1923, apparteneva al piccolo gruppo di donne che si laurearono in architettura in Portogallo e trovarono poi spazio nelle colonie africane, dove la domanda di costruzioni superava di molto l'offerta di progettisti. Dalla metà degli anni Cinquanta lavorò per il servizio di aeronautica civile del Mozambico portoghese accanto a João José Tinoco e Alberto Soeiro, e fra il 1959 e il 1970 i tre progettarono gli aeroporti di Nampula e Porto Amélia, oggi Pemba. Il resto della sua opera mozambicana è amministrativo: la sede del governo di Porto Amélia del 1963, gli uffici distrettuali di Cabo Delgado del 1965 e il Palácio das Repartições di Vila Cabral, oggi Lichinga, costruito fra il 1962 e il 1966. Morì nel 2015. Nel 2020 la Facoltà di Architettura dell'Università di Lisbona istituì un premio al merito a suo nome.",
    },
    awards: [],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q22344586', title: 'Maria Carlota Quintanilha (Q22344586)', license: null },
      { kind: 'publication', url: 'https://doi.org/10.3390/arts9030086', title: 'Patrícia Santos Pedrosa et al., "Women Architects in Portugal: Working in Colonial Africa before the Carnation Revolution (1950–1974)", Arts 9:3 (2020), 86', license: null },
    ],
  },
  {
    id: 'janina-masojada',
    wikidataId: '',
    name: 'Janina Masojada',
    alternativeNames: [],
    gender: 'woman',
    born: null,
    died: null,
    floruit: { start: 1990, end: 2020, override: false },
    movements: [{ id: 'critical-regionalism', primary: true }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'civic',
    signatureMaterial: 'brick',
    portrait: {
      en: 'Janina Masojada is a South African architect based in Durban, where she co-founded OMM Design Workshop and, later, Designworkshop. In 1997 the new Constitutional Court of South Africa was put out to open international competition; more than five hundred entries were assessed by a panel chaired by the Indian architect Charles Correa, and in 1998 the commission went to Masojada, Andrew Makin and Erik Orts-Hansen of OMM Design Workshop together with Paul Wygers of Urban Solutions in Johannesburg. Their scheme took the idea of justice under a tree literally, replacing the usual colonnade with slender canted columns and reusing brick salvaged from the demolished Awaiting Trial Block of the prison whose site the court occupies. The court opened on Human Rights Day 2004. No Wikidata item exists for her; this entry is compiled from published accounts of the competition.',
      es: 'Janina Masojada es una arquitecta sudafricana afincada en Durban, donde cofundó OMM Design Workshop y, más tarde, Designworkshop. En 1997 el nuevo Tribunal Constitucional de Sudáfrica salió a concurso internacional abierto; más de quinientas propuestas fueron valoradas por un jurado presidido por el arquitecto indio Charles Correa, y en 1998 el encargo recayó en Masojada, Andrew Makin y Erik Orts-Hansen, de OMM Design Workshop, junto con Paul Wygers, de Urban Solutions de Johannesburgo. Su proyecto tomó al pie de la letra la idea de la justicia impartida bajo un árbol: sustituyó la columnata habitual por pilares esbeltos e inclinados y reutilizó el ladrillo recuperado del demolido pabellón de presos preventivos de la cárcel cuyo solar ocupa el tribunal. El edificio se inauguró el Día de los Derechos Humanos de 2004. No existe ficha suya en Wikidata; esta entrada se ha compuesto a partir de relatos publicados del concurso.',
      it: "Janina Masojada è un'architetta sudafricana con base a Durban, dove ha cofondato OMM Design Workshop e, più tardi, Designworkshop. Nel 1997 la nuova Corte costituzionale del Sudafrica fu messa a concorso internazionale aperto; più di cinquecento proposte furono valutate da una giuria presieduta dall'architetto indiano Charles Correa e nel 1998 l'incarico andò a Masojada, Andrew Makin ed Erik Orts-Hansen di OMM Design Workshop insieme a Paul Wygers di Urban Solutions di Johannesburg. Il loro progetto prese alla lettera l'idea della giustizia amministrata sotto un albero: sostituì il consueto colonnato con esili pilastri inclinati e reimpiegò i mattoni recuperati dal demolito braccio dei detenuti in attesa di giudizio del carcere di cui la corte occupa l'area. L'edificio fu inaugurato nel Giorno dei diritti umani del 2004. Non esiste una voce Wikidata su di lei; questa scheda è composta da resoconti pubblicati del concorso.",
    },
    awards: [],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'institution', url: 'https://www.constitutionhill.org.za/pages/building-the-constitutional-court', title: 'The story of the Constitutional Court, Constitution Hill', license: null },
      { kind: 'institution', url: 'https://ccac.concourttrust.org.za/uploads/files/Light-on-a-Hill_2006.pdf', title: 'Light on a Hill: Building the Constitutional Court of South Africa (Constitutional Court Trust, 2006)', license: null },
      { kind: 'institution', url: 'https://www.designworkshop.co.za/about', title: 'Designworkshop — About', license: null },
    ],
  },
  {
    id: 'jo-noero',
    wikidataId: 'Q3342672',
    name: 'Jo Noero',
    alternativeNames: ['Joseph Noero'],
    gender: 'man',
    born: null,
    died: null,
    floruit: { start: 1980, end: 2020, override: false },
    movements: [{ id: 'critical-regionalism', primary: true }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'cultural',
    signatureMaterial: 'brick',
    portrait: {
      en: 'Jo Noero is a South African architect who has practised in Johannesburg, in Port Elizabeth and now in Cape Town, and who has built persistently in townships and informal settlements — schools, churches, clinics, community halls — across four decades. His most discussed building is the Red Location Museum in New Brighton, designed with Heinrich Wolff as Noero Wolff Architects and opened in 2006: twelve rusted steel memory boxes standing inside a shed, their form borrowed from the trunks in which migrant workers kept what they owned, arranged so that no route through the exhibition is prescribed. It won the RIBA Lubetkin Prize in 2010. It has been closed since October 2013, when residents of Red Location shut the museum in protest at the condition of their houses, and it has not reopened.',
      es: 'Jo Noero es un arquitecto sudafricano que ha ejercido en Johannesburgo, en Port Elizabeth y hoy en Ciudad del Cabo, y que ha construido de forma constante en townships y asentamientos informales —escuelas, iglesias, dispensarios, centros cívicos— a lo largo de cuatro décadas. Su edificio más comentado es el Red Location Museum de New Brighton, proyectado con Heinrich Wolff como Noero Wolff Architects e inaugurado en 2006: doce cajas de memoria de acero oxidado dentro de una nave, con la forma de los baúles en que los trabajadores migrantes guardaban lo que tenían, dispuestas de modo que ningún recorrido por la exposición esté prescrito. Ganó el Premio Lubetkin del RIBA en 2010. Está cerrado desde octubre de 2013, cuando los vecinos de Red Location clausuraron el museo en protesta por el estado de sus viviendas, y no ha vuelto a abrir.',
      it: "Jo Noero è un architetto sudafricano che ha lavorato a Johannesburg, a Port Elizabeth e oggi a Città del Capo, e che ha costruito con costanza nelle township e negli insediamenti informali — scuole, chiese, ambulatori, centri civici — nell'arco di quarant'anni. Il suo edificio più discusso è il Red Location Museum di New Brighton, progettato con Heinrich Wolff come Noero Wolff Architects e inaugurato nel 2006: dodici scatole della memoria in acciaio arrugginito dentro un capannone, di forma ripresa dai bauli in cui i lavoratori migranti custodivano ciò che possedevano, disposte in modo che nessun percorso espositivo sia prescritto. Vinse il Premio Lubetkin del RIBA nel 2010. È chiuso dall'ottobre 2013, quando gli abitanti di Red Location serrarono il museo per protesta contro lo stato delle loro case, e non ha più riaperto.",
    },
    awards: ['RIBA Lubetkin Prize (2010)'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q3342672', title: 'Jo Noero (Q3342672)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Jo_Noero', title: 'Jo Noero', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Red_Location_Museum', title: 'Red Location Museum', license: 'CC BY-SA 4.0' },
    ],
  },
];
