import type { Architect } from '@/types/architect';

// Wave 5 curator agent (Andean states and the Caribbean): real, sourced Architect entries for this slice.
//
// Four architects below carry an empty `wikidataId`: Esteban Rodríguez
// Castells, Claudia Uccelli, Daniel Hahn and Charles P. Lazarus. None has a
// Wikidata entity as of 2026-08-27 (checked against wbsearchentities in
// es/en, and by direct search for the two Caribbean names). Every other
// field for these four is hand-authored from the published sources listed
// on each record. The alternative — inventing a Q-number — is not
// acceptable, and dropping them would have removed the Caribbean's best Art
// Deco building, Trinidad and Jamaica's only entries in this slice, and one
// of only three women here with an attributed, freely-licensed building.
//
// Milton Barragán (Ecuador) was researched, drafted, and then dropped from
// this file: the building he would have anchored, Templo de la Dolorosa
// (Quito, 1967), sits on real legal risk rather than an easy win. Ecuador's
// 2016 copyright code (Organic Code of Social Economy of Knowledge,
// Creativity and Innovation, Art. 212(7)) limits free reproduction of
// architectural works in public places to scientific or educational
// purposes, and Barragán died in 2024 — his buildings are unambiguously
// still in copyright, and a CC0-tagged photographer credit does not clear
// that gap on its own. Ecuador is an honest gap in this slice, not a
// fabricated one; see the task report for the full reasoning.
export const AMERICAS_ANDEAN_ARCHITECTS: Architect[] = [
  {
    id: 'constantino-de-vasconcelos',
    wikidataId: 'Q98278153',
    name: 'Constantino de Vasconcelos',
    alternativeNames: ['Constantino de Vasconcellos'],
    gender: 'man',
    born: null,
    died: 1668,
    floruit: { start: 1650, end: 1672, override: false },
    movements: [{ id: 'baroque', primary: true }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'sacral',
    signatureMaterial: 'mixed',
    portrait: {
      en: "A Portuguese architect, cosmographer and engineer who worked in the Viceroyalty of Peru, Vasconcelos is remembered for one commission above all. After the earthquake of 4 February 1655 brought down the Franciscan convent of Lima, the order's general commissary Francisco de Borja hired him to draw the plans for its replacement; the limeño master builder Manuel de Escobar ran the site. The first stone was laid on 8 May 1657 and the new church was inaugurated on 3 October 1672, four years after Vasconcelos died. His answer to Lima's seismicity was to keep masonry low and roof the church in bóvedas de quincha — light vaults of cane and plaster carried on a timber armature — a technique that let the building ride out the earthquakes of 1687 and 1746 which flattened stone vaults elsewhere in the city. Wikidata records his death in 1668; some Peruvian sources give 1680.",
      es: "Arquitecto, cosmógrafo e ingeniero portugués activo en el Virreinato del Perú, Vasconcelos es recordado sobre todo por un encargo. Tras el terremoto del 4 de febrero de 1655, que derribó el convento franciscano de Lima, el comisario general Francisco de Borja lo contrató para trazar los planos del nuevo templo; dirigió la obra el alarife limeño Manuel de Escobar. La primera piedra se colocó el 8 de mayo de 1657 y la iglesia se inauguró el 3 de octubre de 1672, cuatro años después de morir su autor. Su respuesta a la sismicidad limeña fue mantener baja la fábrica y cubrir el templo con bóvedas de quincha —caña y yeso sobre armazón de madera—, solución que permitió resistir los terremotos de 1687 y 1746 que arruinaron bóvedas de piedra en el resto de la ciudad. Wikidata sitúa su muerte en 1668; algunas fuentes peruanas dan 1680.",
      it: "Architetto, cosmografo e ingegnere portoghese attivo nel Vicereame del Perù, Vasconcelos è ricordato soprattutto per una commissione. Dopo il terremoto del 4 febbraio 1655, che fece crollare il convento francescano di Lima, il commissario generale dell'ordine Francisco de Borja lo incaricò di disegnare i piani del nuovo tempio; il cantiere fu diretto dal capomastro limeño Manuel de Escobar. La prima pietra fu posata l'8 maggio 1657 e la chiesa venne inaugurata il 3 ottobre 1672, quattro anni dopo la morte del progettista. La sua risposta alla sismicità di Lima fu tenere bassa la muratura e coprire l'aula con bóvedas de quincha — canna e gesso su armatura lignea — soluzione che permise all'edificio di superare i terremoti del 1687 e del 1746 che rovinarono le volte in pietra altrove in città. Wikidata colloca la sua morte nel 1668; alcune fonti peruviane indicano il 1680.",
    },
    awards: [],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q98278153', title: 'Constantino de Vasconcelos (Q98278153)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Basilica_and_Convent_of_San_Francisco,_Lima', title: 'Basilica and Convent of San Francisco, Lima', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'salvador-de-villa',
    wikidataId: 'Q24937707',
    name: 'Salvador de Villa',
    alternativeNames: [],
    gender: 'man',
    born: 1694,
    died: 1764,
    floruit: { start: 1750, end: 1773, override: false },
    movements: [{ id: 'baroque', primary: true }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'industrial',
    signatureMaterial: 'stone',
    portrait: {
      en: "Born in Zaragoza, Salvador de Villa spent his working life on the mints of the Spanish empire in the Americas, moving between Mexico City and Lima before the crown sent him to Potosí. Local officials, led by governor Ventura Santelices y Venero, had argued that the Villa Imperial should simply enlarge its sixteenth-century mint; the king overruled them and Villa arrived to build a new one from nothing. Work ran from 1759 to 1773 on a block of 7,570 square metres, producing some 15,000 square metres of building around five courtyards and roughly two hundred rooms in dressed stone, river cobble and fine brick. Villa died in Potosí on 21 January 1764, four years into the job and around seventy years old; his pupil Luis Cabello took over, handing the work to Jaime San Just in 1765. The finished mint cost 1,148,452 pesos.",
      es: "Nacido en Zaragoza, Salvador de Villa dedicó su vida profesional a las casas de moneda del imperio español en América, alternando entre México y Lima antes de que la corona lo enviara a Potosí. Las autoridades locales, encabezadas por el gobernador Ventura Santelices y Venero, sostenían que bastaba con ampliar la ceca toledana del siglo XVI; el rey se impuso y Villa llegó para levantar una nueva desde los cimientos. La obra corrió de 1759 a 1773 sobre una manzana de 7.570 metros cuadrados y dio unos 15.000 metros cuadrados en torno a cinco patios y cerca de doscientos ambientes, en piedra labrada, piedra bolona y ladrillo fino. Villa murió en Potosí el 21 de enero de 1764, a los cuatro años de faena; le sucedió su discípulo Luis Cabello, que en 1765 traspasó la obra a Jaime San Just. La ceca acabada costó 1.148.452 pesos.",
      it: "Nato a Saragozza, Salvador de Villa dedicò la vita professionale alle zecche dell'impero spagnolo in America, alternando Città del Messico e Lima prima che la corona lo inviasse a Potosí. Le autorità locali, guidate dal governatore Ventura Santelices y Venero, sostenevano che bastasse ampliare la zecca cinquecentesca; il re si impose e Villa giunse per costruirne una nuova dalle fondamenta. Il cantiere andò dal 1759 al 1773 su un isolato di 7.570 metri quadrati e produsse circa 15.000 metri quadrati costruiti attorno a cinque cortili e a quasi duecento ambienti, in pietra squadrata, ciottolo di fiume e mattone fine. Villa morì a Potosí il 21 gennaio 1764, dopo quattro anni di lavoro e a circa settant'anni; gli successe il suo allievo Luis Cabello, che nel 1765 passò l'incarico a Jaime San Just. La zecca finita costò 1.148.452 pesos.",
    },
    awards: [],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q24937707', title: 'Salvador de Villa (Q24937707)', license: null },
      { kind: 'wikipedia', url: 'https://es.wikipedia.org/wiki/Salvador_de_Villa', title: 'Salvador de Villa', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://es.wikipedia.org/wiki/Casa_de_la_Moneda_de_Bolivia', title: 'Casa de la Moneda de Bolivia', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'esteban-rodriguez-castells',
    wikidataId: '',
    name: 'Esteban Rodríguez Castells',
    alternativeNames: ['Esteban Rodríguez Castell'],
    gender: 'man',
    born: null,
    died: null,
    floruit: { start: 1929, end: 1930, override: true },
    movements: [{ id: 'art-deco', primary: true }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'commercial',
    signatureMaterial: 'mixed',
    portrait: {
      en: "Cuban architect, one of the three authors — with Rafael Fernández Ruenes and José Menéndez — of the Bacardí Building in Havana, the commission for which he is remembered. Bacardí S.A. wanted a headquarters that would read as a corporate emblem, and the team delivered Cuba's fullest statement of Art Deco: a steel-framed tower on reinforced concrete slabs, twelve levels stepped back to a belvedere carrying the company's bronze bat. The cladding catalogues imported material — Bavarian granite, glazed terracotta, pressed brick, polychrome tile — its glazed ceramic panels echoing Catalan modernisme reworked into Deco geometry. Wikidata carries no entity for him; the attribution here follows the Spanish Wikipedia article on the Edificio Bacardí, and his dates are not established in the sources consulted.",
      es: "Arquitecto cubano, uno de los tres autores —junto a Rafael Fernández Ruenes y José Menéndez— del edificio Bacardí de La Habana, el encargo por el que se le recuerda. Bacardí S.A. quería una sede que funcionara como emblema corporativo, y el equipo entregó la formulación más completa del art déco en Cuba: una torre de pórticos de acero con losas de hormigón armado, doce niveles escalonados hasta un templete que sostiene el murciélago de bronce de la compañía. El revestimiento cataloga material importado —granito de Baviera, terracota esmaltada, ladrillo prensado, azulejo policromo—, con paneles cerámicos que evocan el modernismo catalán en clave geométrica. Wikidata no registra ninguna entidad suya; la atribución sigue aquí el artículo de Wikipedia en español, y sus fechas no constan en las fuentes consultadas.",
      it: "Architetto cubano, uno dei tre autori — con Rafael Fernández Ruenes e José Menéndez — dell'edificio Bacardí dell'Avana, la commissione per cui è ricordato. La Bacardí S.A. voleva una sede che funzionasse da emblema aziendale, e il gruppo consegnò la formulazione più compiuta dell'Art Déco a Cuba: una torre a telaio d'acciaio con solai in cemento armato, dodici livelli e circa 44 metri, arretrata per gradi fino a un belvedere che regge il pipistrello di bronzo della casa. Il rivestimento è un catalogo voluto di materiali d'importazione — granito rosso di Baviera, terracotta smaltata, mattone pressato, piastrella policroma — e i pannelli in ceramica invetriata conservano un'eco del modernismo catalano riscritta in geometria déco. Wikidata non registra alcuna entità su di lui; l'attribuzione e i dati dell'edificio seguono qui la voce di Wikipedia in spagnolo, e le sue date non risultano dalle fonti consultate.",
    },
    awards: [],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikipedia', url: 'https://es.wikipedia.org/wiki/Edificio_Bacard%C3%AD_(La_Habana)', title: 'Edificio Bacardí (La Habana)', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Bacardi_Building_(Havana)', title: 'Bacardi Building (Havana)', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'carlos-raul-villanueva',
    wikidataId: 'Q1043186',
    name: 'Carlos Raúl Villanueva',
    alternativeNames: ['Carlos Raúl Villanueva Astoul'],
    gender: 'man',
    born: 1900,
    died: 1975,
    floruit: { start: 1929, end: 1975, override: false },
    movements: [
      { id: 'tropical-modernism', primary: true },
      { id: 'international-style', primary: false },
    ],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'educational',
    signatureMaterial: 'concrete',
    portrait: {
      en: "Born in London to a Venezuelan diplomat and trained at the École des Beaux-Arts in Paris, Villanueva returned to Venezuela in 1929 and spent forty-six years building the country's public architecture. His career divides cleanly. The early work is historicist and stage-managed — the neo-Mudéjar bullring at Maracay of 1933, built for the Gómez regime — and gives way through the El Silencio housing scheme of 1942–45 to an outright modernism tuned to the tropics: deep brise-soleil, perforated screens, covered outdoor rooms, concrete left as struck. From 1944 he devoted himself to the Ciudad Universitaria de Caracas, where he pursued the síntesis de las artes, commissioning Léger, Arp, Vasarely, Calder and Venezuelan artists to work inside the architecture rather than on it. UNESCO inscribed the campus as a World Heritage Site on 30 November 2000.",
      es: "Nacido en Londres, hijo de un diplomático venezolano, y formado en la École des Beaux-Arts de París, Villanueva regresó a Venezuela en 1929 y dedicó cuarenta y seis años a construir la arquitectura pública del país. Su trayectoria se parte con nitidez. La obra temprana es historicista y escenográfica —la maestranza neomudéjar de Maracay, de 1933, levantada para el régimen gomecista— y da paso, a través de la reurbanización de El Silencio de 1942-45, a un modernismo pleno afinado al trópico: brise-soleil profundos, celosías, salas exteriores cubiertas, hormigón dejado tal como salió del encofrado. Desde 1944 se volcó en la Ciudad Universitaria de Caracas, donde persiguió la síntesis de las artes encargando a Léger, Arp, Vasarely, Calder y a artistas venezolanos obras que trabajaran dentro de la arquitectura y no sobre ella. La Unesco inscribió el campus como Patrimonio Mundial el 30 de noviembre de 2000.",
      it: "Nato a Londra da un diplomatico venezuelano e formatosi all'École des Beaux-Arts di Parigi, Villanueva tornò in Venezuela nel 1929 e dedicò quarantasei anni a costruire l'architettura pubblica del paese. La sua carriera si divide nettamente. L'opera giovanile è storicista e scenografica — l'arena neomudéjar di Maracay del 1933, eretta per il regime di Gómez — e lascia il posto, attraverso il quartiere di El Silencio del 1942-45, a un modernismo pieno accordato ai tropici: brise-soleil profondi, grate traforate, stanze esterne coperte, calcestruzzo lasciato come uscito dal cassero. Dal 1944 si dedicò alla Ciudad Universitaria di Caracas, dove perseguì la síntesis de las artes affidando a Léger, Arp, Vasarely, Calder e ad artisti venezuelani opere che lavorassero dentro l'architettura e non sopra di essa. L'UNESCO iscrisse il campus nel Patrimonio Mondiale il 30 novembre 2000.",
    },
    awards: ['Premio Nacional de Arquitectura de Venezuela (1963)'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q1043186', title: 'Carlos Raúl Villanueva (Q1043186)', license: null },
      { kind: 'wikipedia', url: 'https://es.wikipedia.org/wiki/Carlos_Ra%C3%BAl_Villanueva', title: 'Carlos Raúl Villanueva', license: 'CC BY-SA 4.0' },
      { kind: 'institution', url: 'https://whc.unesco.org/en/list/986/', title: 'Ciudad Universitaria de Caracas — UNESCO World Heritage Centre', license: null },
    ],
  },
  {
    id: 'ricardo-porro',
    wikidataId: 'Q1453813',
    name: 'Ricardo Porro',
    alternativeNames: ['Ricardo Porro Hidalgo'],
    gender: 'man',
    born: 1925,
    died: 2014,
    floruit: { start: 1955, end: 2010, override: false },
    movements: [
      { id: 'organic-architecture', primary: true },
      { id: 'expressionism', primary: false },
    ],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'educational',
    signatureMaterial: 'brick',
    portrait: {
      en: "Born in Camagüey, Porro returned to Cuba after the revolution of 1959 and was chosen by Fidel Castro to lead the design of the National Art Schools, the commission that defines him. Working with the Italians Roberto Gottardi and Vittorio Garatti, he set the project against the International Style, which the three read as the architecture of capitalism, and looked instead to Catalan vaulting, to Antoni Gaudí and to Afro-Cuban form. The US embargo, which made rebar and Portland cement expensive, turned that preference into a method: brick and terracotta, vaulted. Porro's School of Plastic Arts is planned as an archetypal African village of oval, top-lit studios strung along curving colonnades. He left Cuba in 1966 as the schools fell from favour, settled in Paris, and continued to build in France; he died there in 2014.",
      es: "Nacido en Camagüey, Porro volvió a Cuba tras la revolución de 1959 y fue elegido por Fidel Castro para encabezar el proyecto de las Escuelas Nacionales de Arte, el encargo que lo define. Con los italianos Roberto Gottardi y Vittorio Garatti, planteó la obra contra el estilo internacional, que los tres leían como la arquitectura del capitalismo, y miró en cambio a la bóveda catalana, a Antoni Gaudí y a la forma afrocubana. El embargo estadounidense, que encarecía el acero corrugado y el cemento portland, convirtió esa preferencia en método: ladrillo y terracota, abovedados. Su Escuela de Artes Plásticas se ordena como una aldea africana arquetípica de talleres ovales con lucernario, ensartados en galerías curvas. Porro salió de Cuba en 1966, cuando las escuelas cayeron en desgracia, se instaló en París y siguió construyendo en Francia; allí murió en 2014.",
      it: "Nato a Camagüey, Porro tornò a Cuba dopo la rivoluzione del 1959 e fu scelto da Fidel Castro per guidare il progetto delle Escuelas Nacionales de Arte, la commissione che lo definisce. Con gli italiani Roberto Gottardi e Vittorio Garatti impostò l'opera contro lo Stile Internazionale, che i tre leggevano come architettura del capitalismo, guardando invece alla volta catalana, ad Antoni Gaudí e alla forma afrocubana. L'embargo statunitense, che rendeva costosi tondino e cemento Portland, trasformò quella preferenza in metodo: mattone e terracotta, voltati. La sua Escuela de Artes Plásticas è ordinata come un villaggio africano archetipico di atelier ovali illuminati dall'alto, infilati su porticati curvi. Porro lasciò Cuba nel 1966, quando le scuole caddero in disgrazia, si stabilì a Parigi e continuò a costruire in Francia; vi morì nel 2014.",
    },
    awards: ['Commandeur des Arts et des Lettres', 'Chevalier de la Légion d\'honneur'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q1453813', title: 'Ricardo Porro (Q1453813)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/National_Art_Schools_(Cuba)', title: 'National Art Schools (Cuba)', license: 'CC BY-SA 4.0' },
      { kind: 'publication', url: 'https://www.wmf.org/project/national-art-schools', title: 'National Art Schools — World Monuments Fund', license: null },
    ],
  },
  {
    id: 'rogelio-salmona',
    wikidataId: 'Q998392',
    name: 'Rogelio Salmona',
    alternativeNames: [],
    gender: 'man',
    born: 1929,
    died: 2007,
    floruit: { start: 1959, end: 2007, override: false },
    movements: [{ id: 'critical-regionalism', primary: true }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'cultural',
    signatureMaterial: 'brick',
    portrait: {
      en: "Salmona spent nine years in Le Corbusier's atelier in Paris and came home to Bogotá in 1958 to spend the rest of his life arguing with what he had learned there. His material was fired brick, chosen for reasons he stated plainly: it is made from clay and gives work to many people; bogotano masons use it with munificence; its colour shifts with the light; and brick architecture belongs with the city's vegetation. From that one material he built ramps, spiral stairs, water courts and roof terraces that treat open space as the generator of covered space rather than its leftover. The Torres del Parque, the Museo del Oro Quimbaya and the Archivo General de la Nación show the range within a single palette. He received the Alvar Aalto Medal in 2003, the jury citing his use of authentic materials and his integration of landscape and urban planning.",
      es: "Salmona pasó nueve años en el taller de Le Corbusier en París y volvió a Bogotá en 1958 para dedicar el resto de su vida a discutir con lo aprendido allí. Su material fue el ladrillo cocido, elegido por razones que enunció sin rodeos: se hace con barro y da trabajo a mucha gente; los albañiles bogotanos lo usan con munificencia; su color varía con la luz; y la arquitectura de ladrillo está emparentada con la vegetación de la ciudad. Con ese único material levantó rampas, escaleras en caracol, patios de agua y terrazas que entienden el espacio abierto como generador del cubierto y no como su sobrante. Las Torres del Parque, el Museo del Oro Quimbaya y el Archivo General de la Nación muestran el alcance de una sola paleta. Recibió la Medalla Alvar Aalto en 2003, cuyo jurado destacó su uso de materiales auténticos.",
      it: "Salmona trascorse nove anni nell'atelier di Le Corbusier a Parigi e tornò a Bogotá nel 1958 per passare il resto della vita a discutere con quanto vi aveva appreso. Il suo materiale fu il mattone cotto, scelto per ragioni che enunciò senza giri di parole: si fa con l'argilla e dà lavoro a molte persone; i muratori bogotani lo usano con generosità; il suo colore cambia con la luce; e l'architettura in mattone è imparentata con la vegetazione della città. Con quell'unico materiale costruì rampe, scale a chiocciola, corti d'acqua e terrazze che intendono lo spazio aperto come generatore dello spazio coperto e non come suo residuo. Le Torres del Parque, il Museo del Oro Quimbaya e l'Archivo General de la Nación mostrano l'ampiezza di una sola tavolozza. Ricevette la Medaglia Alvar Aalto nel 2003; la giuria ne segnalò l'uso di materiali autentici e l'integrazione di paesaggio e urbanistica.",
    },
    awards: ['Alvar Aalto Medal (2003)', 'Prince Claus Award (2000)'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q998392', title: 'Rogelio Salmona (Q998392)', license: null },
      { kind: 'wikipedia', url: 'https://es.wikipedia.org/wiki/Torres_del_Parque', title: 'Torres del Parque', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://es.wikipedia.org/wiki/Rogelio_Salmona', title: 'Rogelio Salmona', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'sandra-barclay',
    wikidataId: 'Q27118295',
    name: 'Sandra Barclay',
    alternativeNames: ['Sandra Barclay Gálvez'],
    gender: 'woman',
    born: 1967,
    died: null,
    floruit: { start: 1994, end: 2025, override: false },
    movements: [{ id: 'critical-regionalism', primary: true }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'cultural',
    signatureMaterial: 'concrete',
    portrait: {
      en: "Barclay studied at the Universidad Ricardo Palma in Lima and at the Ecole d'Architecture de Paris-Belleville, and in 1994 founded Barclay & Crousse with Jean Pierre Crousse, first in Paris and from 2006 in Lima. The practice works the Peruvian coastal desert as a material in its own right: buildings are cut out of the ground rather than set on it, mass concrete is coloured to the tone of the sand and left rough, and the sequence of shaded courts and slots does the work that glazing does elsewhere. The Museo de Sitio de Paracas, the Edificio E at the Universidad de Piura and the Lugar de la Memoria in Lima are the best-known results. Barclay was named Woman Architect of the Year at the Architectural Review's Women in Architecture Awards in 2018; the practice holds Peru's Hexágono de Oro.",
      es: "Barclay estudió en la Universidad Ricardo Palma de Lima y en la École d'Architecture de Paris-Belleville, y en 1994 fundó Barclay & Crousse junto a Jean Pierre Crousse, primero en París y desde 2006 en Lima. El estudio trabaja el desierto costero peruano como material en sí mismo: los edificios se excavan en el terreno más que se posan sobre él, el hormigón masivo se pigmenta al tono de la arena y se deja áspero, y la secuencia de patios y rendijas en sombra cumple la función que en otras latitudes cumple el vidrio. El Museo de Sitio de Paracas, el Edificio E de la Universidad de Piura y el Lugar de la Memoria de Lima son sus resultados más conocidos. Barclay fue nombrada Arquitecta del Año en los Women in Architecture Awards de The Architectural Review en 2018; el estudio ostenta el Hexágono de Oro peruano.",
      it: "Barclay studiò alla Universidad Ricardo Palma di Lima e all'École d'Architecture de Paris-Belleville, e nel 1994 fondò Barclay & Crousse con Jean Pierre Crousse, prima a Parigi e dal 2006 a Lima. Lo studio lavora il deserto costiero peruviano come materiale a pieno titolo: gli edifici sono scavati nel terreno più che posati su di esso, il calcestruzzo massiccio è pigmentato nel tono della sabbia e lasciato ruvido, e la sequenza di corti e fenditure in ombra svolge il compito che altrove spetta al vetro. Il Museo de Sitio de Paracas, l'Edificio E della Universidad de Piura e il Lugar de la Memoria di Lima sono i risultati più noti. Barclay è stata nominata Woman Architect of the Year ai Women in Architecture Awards di The Architectural Review nel 2018; lo studio detiene l'Hexágono de Oro peruviano.",
    },
    awards: ['Woman Architect of the Year, The Architectural Review (2018)', 'Premio Hexágono de Oro'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q27118295', title: 'Sandra Barclay (Q27118295)', license: null },
      { kind: 'wikipedia', url: 'https://es.wikipedia.org/wiki/Sandra_Barclay', title: 'Sandra Barclay', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'claudia-uccelli',
    wikidataId: '',
    name: 'Claudia Uccelli Romero',
    alternativeNames: ['Claudia Uccelli'],
    gender: 'woman',
    born: 1965,
    died: null,
    floruit: { start: 2005, end: 2015, override: true },
    movements: 'unaffiliated',
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'cultural',
    signatureMaterial: 'concrete',
    portrait: {
      en: "A Peruvian architect who runs Oficina Uccelli Arquitectos in Lima and has built most consistently for archaeology, Uccelli is known above all for the Museo Cao at the El Brujo complex in La Libertad, commissioned by the Fundación Wiese and built in 2008–09 alongside three Moche pyramids. Her account of the project turns on a search for an aesthetic understanding of the cultures of Peru's north coast: the plan is organic, derived from Moche domestic layouts, and the building is assembled from five modular units whose voids are as compositional as their solids — the void, she writes, is part of the composition the way silences are part of a piece of music. Exposed concrete is the only material. Wikidata carries no entity for her; the biography and project data here are taken from the published project sheets cited below.",
      es: "Arquitecta peruana al frente de Oficina Uccelli Arquitectos en Lima, con una obra construida sobre todo para la arqueología, Uccelli es conocida ante todo por el Museo Cao, en el complejo El Brujo (La Libertad), encargado por la Fundación Wiese y levantado en 2008-09 junto a tres pirámides moche. Su relato del proyecto gira en torno a la búsqueda de una comprensión estética de las culturas asentadas en la costa norte del Perú: la planta es orgánica, derivada de la planimetría doméstica moche, y el edificio se arma con cinco unidades modulares cuyos vacíos son tan compositivos como sus llenos —el vacío, escribe, es parte de la composición como los silencios forman parte de una obra musical—. El hormigón visto es el único material. Wikidata no registra ninguna entidad suya; la biografía y los datos del proyecto proceden de las fichas publicadas que se citan.",
      it: "Architetta peruviana a capo di Oficina Uccelli Arquitectos a Lima, con un'opera costruita soprattutto per l'archeologia, Uccelli è nota anzitutto per il Museo Cao, nel complesso di El Brujo (La Libertad), commissionato dalla Fundación Wiese e realizzato nel 2008-09 accanto a tre piramidi moche. Il suo racconto del progetto ruota attorno alla ricerca di una comprensione estetica delle culture della costa settentrionale del Perù: la pianta è organica, derivata dalla planimetria domestica moche, e l'edificio è composto da cinque unità modulari i cui vuoti sono compositivi quanto i pieni — il vuoto, scrive, è parte della composizione come i silenzi fanno parte di un'opera musicale. Il calcestruzzo a vista è l'unico materiale. Wikidata non registra alcuna entità su di lei; la biografia e i dati di progetto provengono dalle schede pubblicate citate qui sotto.",
    },
    awards: ['Hexágono de Plata, Macro Región Norte, XIV Bienal de Arquitectura Peruana (2010)'],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'publication', url: 'https://arqa.com/arquitectura/museo-cao.html', title: 'Museo Cao — ARQA (project sheet, Claudia Uccelli Romero)', license: null },
      { kind: 'institution', url: 'https://www.mchap.co/mchap-2014-projects/cao-museum', title: 'Cao Museum — Mies Crown Hall Americas Prize 2014 nominated projects', license: null },
    ],
  },
  {
    id: 'rafael-carmoega',
    wikidataId: 'Q16006361',
    name: 'Rafael Carmoega',
    alternativeNames: ['Rafael Carmoega Morales'],
    gender: 'man',
    born: 1894,
    died: 1968,
    floruit: { start: 1921, end: 1960, override: true },
    movements: [
      { id: 'beaux-arts', primary: true },
      { id: 'neoclassicism', primary: false },
    ],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'civic',
    signatureMaterial: 'stone',
    portrait: {
      en: "Born in Río Piedras and trained at Cornell, graduating in 1918, Carmoega was the first Puerto Rican to hold the post of State Architect, occupied inside the Department of the Interior from 1921 to 1936. Those fifteen years placed him in charge of the island's public building just as a United States territorial administration was writing its own institutions into stone. He inherited the half-built Capitol from earlier schemes by Frank Perkins and Adrian Finlayson and finished it in marble, opening in 1929. Away from that neoclassical commission his preference ran to Spanish Baroque and neo-Mudéjar vocabularies and glazed mosaic tile, an insistence on Hispanic inheritance under American sovereignty. After 1936 he worked for the Puerto Rico Reconstruction Administration on the Universidad de Puerto Rico campus, then in private practice from 1937. His archive of 144 projects is held by that university.",
      es: "Nacido en Río Piedras y formado en Cornell, graduado en 1918, Carmoega fue el primer puertorriqueño en ocupar el cargo de Arquitecto del Estado, dentro del Departamento del Interior entre 1921 y 1936. Esos quince años lo pusieron al frente de la obra pública de la isla justo cuando una administración territorial estadounidense inscribía en piedra sus propias instituciones. Heredó el Capitolio a medio construir de los proyectos previos de Frank Perkins y Adrian Finlayson y lo remató en mármol, inaugurado en 1929. Fuera de ese encargo neoclásico, su preferencia iba hacia el barroco español y el neomudéjar y hacia el azulejo vidriado: insistencia en la herencia hispánica bajo soberanía norteamericana. Desde 1936 trabajó para la Puerto Rico Reconstruction Administration en el recinto de la Universidad de Puerto Rico, y desde 1937 por cuenta propia. Esa universidad conserva su archivo de 144 proyectos.",
      it: "Nato a Río Piedras e formatosi alla Cornell, dove si laureò nel 1918, Carmoega fu il primo portoricano a ricoprire la carica di Architetto di Stato, che occupò all'interno del Dipartimento degli Interni dal 1921 al 1936. Quei quindici anni lo misero a capo dell'edilizia pubblica dell'isola proprio mentre un'amministrazione territoriale statunitense fissava nella pietra le proprie istituzioni. Ereditò il Campidoglio a metà costruzione dai progetti precedenti di Frank Perkins e Adrian Finlayson e lo portò a termine in marmo, con l'inaugurazione del 1929. Al di fuori di quella commissione neoclassica la sua preferenza andava ai repertori del barocco spagnolo e del neomudéjar e alla piastrella invetriata: un'insistenza deliberata sull'eredità ispanica sotto sovranità statunitense. Dal 1936 lavorò per la Puerto Rico Reconstruction Administration al campus della Universidad de Puerto Rico, e dal 1937 in proprio. Quella università conserva il suo archivio di 144 progetti.",
    },
    awards: [],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q16006361', title: 'Rafael Carmoega (Q16006361)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Rafael_Carmoega', title: 'Rafael Carmoega', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Puerto_Rico_Capitol', title: 'Puerto Rico Capitol', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'libia-yusti',
    wikidataId: 'Q37331206',
    name: 'Libia Yusti',
    alternativeNames: [],
    gender: 'woman',
    born: null,
    died: null,
    floruit: { start: 1965, end: 1975, override: true },
    movements: 'unaffiliated',
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'civic',
    signatureMaterial: 'concrete',
    portrait: {
      en: "Yusti belonged to the first cohort to graduate in architecture from the Universidad del Valle, in 1958, and spent her career in Cali, in the practice Richardson y Yusti that she ran with Enrique Richardson. The commissions she is remembered for came together: the venues Cali needed for the sixth Pan American Games of 1971, among them the Coliseo El Pueblo and the Alcides Nieto Patiño velodrome, both built inside the sports precinct laid out on the western edge of the city. She also built the Palacio de San Francisco. Spanish Wikipedia describes her as one of the architects who carried modern architecture into Cali and shaped its urban expansion, and gives no birth date beyond the twentieth century; Wikidata records 1901, which the published account does not support, so no year is asserted here.",
      es: "Yusti formó parte de la primera promoción de arquitectos egresados de la Universidad del Valle, en 1958, y desarrolló su carrera en Cali, en la firma Richardson y Yusti que dirigió junto a Enrique Richardson. Los encargos por los que se la recuerda llegaron juntos: los escenarios que Cali necesitaba para los VI Juegos Panamericanos de 1971, entre ellos el Coliseo El Pueblo y el velódromo Alcides Nieto Patiño, ambos levantados dentro de la unidad deportiva trazada en el borde occidental de la ciudad. Construyó además el Palacio de San Francisco. La Wikipedia en español la describe como una de las arquitectas que introdujeron la arquitectura moderna en Cali y que orientaron su desarrollo urbano, y no da más fecha de nacimiento que el siglo XX; Wikidata registra 1901, que la fuente publicada no respalda, de modo que aquí no se afirma ningún año.",
      it: "Yusti fece parte della prima leva di architetti laureati alla Universidad del Valle, nel 1958, e svolse la carriera a Cali, nello studio Richardson y Yusti che diresse con Enrique Richardson. Le commissioni per cui è ricordata arrivarono insieme: gli impianti di cui Cali aveva bisogno per i VI Giochi Panamericani del 1971, fra cui il Coliseo El Pueblo e il velodromo Alcides Nieto Patiño, entrambi costruiti dentro il comparto sportivo tracciato sul margine occidentale della città. Realizzò inoltre il Palacio de San Francisco. La Wikipedia in spagnolo la descrive come una delle architette che portarono l'architettura moderna a Cali e ne indirizzarono lo sviluppo urbano, e non indica altra data di nascita che il XX secolo; Wikidata riporta il 1901, che la fonte pubblicata non conferma, perciò qui non si afferma alcun anno.",
    },
    awards: [],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q37331206', title: 'Libia Yusti (Q37331206)', license: null },
      { kind: 'wikipedia', url: 'https://es.wikipedia.org/wiki/Libia_Yusti', title: 'Libia Yusti', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://es.wikipedia.org/wiki/Coliseo_El_Pueblo', title: 'Coliseo El Pueblo', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'charles-p-lazarus',
    wikidataId: '',
    name: 'Charles P. Lazarus',
    alternativeNames: [],
    gender: 'man',
    born: null,
    died: null,
    floruit: { start: 1881, end: 1881, override: true },
    movements: 'unaffiliated',
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'domestic',
    signatureMaterial: 'brick',
    portrait: {
      en: "Lazarus was not a trained architect by profession — he worked as an iron founder and as engineer to the Kingston and Liguanea Water Works Company, and sat as a local political leader in colonial Jamaica — but he is the name attached to the one commission he is remembered for: Devon House, built in 1881 at Half Way Tree, Kingston, for George Stiebel, reputed to be Jamaica's first Black millionaire, made rich by mining and shipping ventures in Venezuela. The house follows the symmetrical massing of Jamaican Georgian planning, with wraparound verandahs and jalousied windows judged against the island's heat, built of brick, timber and iron gates shipped in for the purpose. The property faced demolition in 1965 before the Jamaican government intervened to preserve it as a heritage site. No birth or death date for Lazarus has been established in the sources consulted.",
      es: "Lazarus no era arquitecto de formación —trabajó como fundidor de hierro y como ingeniero de la Kingston and Liguanea Water Works Company, y ejerció como dirigente político local en la Jamaica colonial—, pero su nombre queda unido al único encargo por el que se le recuerda: Devon House, levantada en 1881 en Half Way Tree, Kingston, para George Stiebel, considerado el primer millonario negro de Jamaica, enriquecido con la minería y el transporte marítimo en Venezuela. La casa sigue la composición simétrica del estilo georgiano jamaicano, con galerías perimetrales y ventanas de celosía pensadas contra el calor de la isla, construida en ladrillo, madera y verjas de hierro traídas para la obra. La propiedad estuvo a punto de ser demolida en 1965 antes de que el gobierno de Jamaica interviniera para conservarla como sitio patrimonial. Las fuentes consultadas no registran fecha de nacimiento ni de muerte para Lazarus.",
      it: "Lazarus non era un architetto di formazione — lavorò come fonditore di ferro e come ingegnere della Kingston and Liguanea Water Works Company, ed ebbe un ruolo di dirigente politico locale nella Giamaica coloniale —, ma il suo nome resta legato all'unica commissione per cui è ricordato: Devon House, costruita nel 1881 a Half Way Tree, Kingston, per George Stiebel, ritenuto il primo milionario nero della Giamaica, arricchitosi con l'attività mineraria e marittima in Venezuela. La casa segue la composizione simmetrica dello stile georgiano giamaicano, con verande perimetrali e persiane pensate contro il caldo dell'isola, costruita in mattone, legno e cancelli in ferro fatti arrivare per l'occasione. La proprietà rischiò la demolizione nel 1965 prima che il governo giamaicano intervenisse per conservarla come sito patrimoniale. Le fonti consultate non riportano data di nascita né di morte per Lazarus.",
    },
    awards: [],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Devon_House', title: 'Devon House', license: 'CC BY-SA 4.0' },
      { kind: 'publication', url: 'https://averyreview.com/issues/59/devon-house', title: 'Devon House — The Avery Review', license: null },
      { kind: 'institution', url: 'https://www.ksamc.gov.jm/attractions/devon-house', title: 'Devon House — Kingston and St. Andrew Municipal Corporation', license: null },
    ],
  },
  {
    id: 'daniel-hahn',
    wikidataId: '',
    name: 'Daniel Meinerts Hahn',
    alternativeNames: ['Daniel Hahn', 'D. M. Hahn'],
    gender: 'man',
    born: 1867,
    died: null,
    floruit: { start: 1902, end: 1907, override: true },
    movements: [{ id: 'beaux-arts', primary: true }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'civic',
    signatureMaterial: 'stone',
    portrait: {
      en: "Born in Carúpano, Venezuela, in 1867 and raised in Trinidad, Hahn was educated at Queen's Royal College before continuing his studies in Hamburg and at Berlin's Polytechnic School of Engineering. He returned as chief draughtsman of the Public Works Department, the post from which he designed Trinidad's two most conspicuous early-twentieth-century public buildings. The Water Riots of March 1903 gutted the old Red House; Hahn rebuilt it in dressed stone, adding the central cupola and Wedgwood-blue gesso ceiling that give the reopened Parliament of 1907 its silhouette. In between, on 11 November 1902, he laid the foundation stone of his own old school, Queen's Royal College, in a German Renaissance vocabulary of twin towers rather than the Red House's Beaux-Arts idiom. No death date for Hahn has been established in the sources consulted.",
      es: "Nacido en Carúpano, Venezuela, en 1867 y criado en Trinidad, Hahn se formó en el Queen's Royal College antes de proseguir estudios en Hamburgo y en la Escuela Politécnica de Ingeniería de Berlín. Volvió como delineante jefe del Departamento de Obras Públicas, cargo desde el que proyectó los dos edificios públicos más visibles de la Trinidad de comienzos del siglo XX. Los disturbios del agua de marzo de 1903 arrasaron el antiguo Red House; Hahn lo reconstruyó en piedra labrada, añadiendo la cúpula central y el techo de yesería azul Wedgwood que dan al Parlamento reabierto en 1907 su silueta. Entretanto, el 11 de noviembre de 1902, colocó la primera piedra de su propio colegio, el Queen's Royal College, con un vocabulario de renacimiento alemán de torres gemelas, distinto del repertorio beaux-arts del Red House. Las fuentes consultadas no registran fecha de muerte para Hahn.",
      it: "Nato a Carúpano, in Venezuela, nel 1867 e cresciuto a Trinidad, Hahn si formò al Queen's Royal College prima di proseguire gli studi ad Amburgo e alla Scuola Politecnica di Ingegneria di Berlino. Tornò come disegnatore capo del Dipartimento dei Lavori Pubblici, incarico dal quale progettò i due edifici pubblici più in vista della Trinidad di inizio Novecento. I moti dell'acqua del marzo 1903 devastarono il vecchio Red House; Hahn lo ricostruì in pietra squadrata, aggiungendo la cupola centrale e il soffitto in stucco blu Wedgwood che danno al Parlamento riaperto nel 1907 la sua sagoma. Nel frattempo, l'11 novembre 1902, posò la prima pietra della propria vecchia scuola, il Queen's Royal College, con un vocabolario di rinascimento tedesco a torri gemelle, diverso dal repertorio beaux-arts del Red House. Le fonti consultate non registrano una data di morte per Hahn.",
    },
    awards: [],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Red_House_(Trinidad_and_Tobago)', title: 'Red House (Trinidad and Tobago)', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: "https://en.wikipedia.org/wiki/Queen's_Royal_College,_Trinidad", title: "Queen's Royal College, Trinidad", license: 'CC BY-SA 4.0' },
      { kind: 'institution', url: 'https://nationaltrust.tt/location/the-red-house/', title: 'The Red House — National Trust of Trinidad and Tobago', license: null },
    ],
  },
];
