import type { Architect } from '@/types/architect';

// Wave 5, agent 9c — Northern America (United States and Canada).
//
// Every entry below was checked against its live Wikidata entity page on
// 2026-08-26. `workRegions` and `workCentroid` are deliberately left empty:
// buildCuratedPool derives both from the architect's buildings and discards
// whatever is written here.
//
// Cross-file note for the controller: `moshe-safdie` is defined here because
// Habitat 67 (Montréal) is his first appearance in the pool, but his practice
// also spans Israel and Singapore. If the westasia or asia curator needs him,
// they should reference `moshe-safdie` rather than redefining him.
export const AMERICAS_ARCHITECTS: Architect[] = [
  {
    id: 'thomas-jefferson',
    wikidataId: 'Q11812',
    name: 'Thomas Jefferson',
    alternativeNames: ['Thomas Jefferson (architect)'],
    gender: 'man',
    born: 1743,
    died: 1826,
    floruit: { start: 1770, end: 1826, override: false },
    movements: [
      { id: 'palladianism', primary: true },
      { id: 'neoclassicism', primary: false },
    ],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'domestic',
    signatureMaterial: 'brick',
    portrait: {
      en: 'Jefferson was an amateur in the strict sense: he never trained as an architect, never charged a fee, and learned the discipline from books — above all from Giacomo Leoni\'s English edition of Palladio, which he called his bible. What he built from that reading was not imitation. At Monticello he spent forty years rebuilding his own house until its Palladian parts were arranged around an American plan of his own devising, with dumbwaiters, a bed alcove between two rooms, and service wings dug into the hillside. The Virginia State Capitol, drawn in Paris with Charles-Louis Clérisseau, transplanted the Maison Carrée at Nîmes into a working legislature and set the template for American public building. His last work, the University of Virginia, arranged ten pavilions and a library rotunda around a lawn as a curriculum made visible.',
      es: 'Jefferson fue un aficionado en sentido estricto: nunca se formó como arquitecto, nunca cobró honorarios y aprendió el oficio en los libros, sobre todo en la edición inglesa de Palladio de Giacomo Leoni, que llamaba su biblia. Lo que construyó a partir de esa lectura no fue imitación. En Monticello dedicó cuarenta años a rehacer su propia casa hasta que las piezas palladianas quedaron ordenadas según una planta americana de su invención, con montacargas, una alcoba encajada entre dos habitaciones y alas de servicio excavadas en la ladera. El Capitolio de Virginia, dibujado en París con Charles-Louis Clérisseau, trasplantó la Maison Carrée de Nimes a una legislatura en funcionamiento y fijó el modelo del edificio público estadounidense. Su última obra, la Universidad de Virginia, dispuso diez pabellones y una rotonda-biblioteca en torno a un césped: un plan de estudios hecho arquitectura.',
      it: 'Jefferson fu un dilettante in senso stretto: non si formò mai come architetto, non chiese mai un compenso e imparò il mestiere sui libri, soprattutto sull\'edizione inglese di Palladio curata da Giacomo Leoni, che chiamava la sua bibbia. Ciò che costruì a partire da quella lettura non fu imitazione. A Monticello impiegò quarant\'anni a rifare la propria casa finché le parti palladiane non risultarono ordinate secondo una pianta americana di sua invenzione, con montavivande, un\'alcova incassata fra due stanze e ali di servizio scavate nel pendio. Il Campidoglio della Virginia, disegnato a Parigi con Charles-Louis Clérisseau, trapiantò la Maison Carrée di Nîmes in un\'assemblea legislativa in funzione e fissò il modello dell\'edificio pubblico americano. La sua ultima opera, l\'Università della Virginia, dispose dieci padiglioni e una rotonda-biblioteca attorno a un prato: un piano di studi reso architettura.',
    },
    awards: [],
    tier: 'canon',
    context: {
      body: {
        en: 'Jefferson enslaved more than 620 people over the course of his adult life. He wrote the sentence about all men being created equal, argued in Notes on the State of Virginia for the innate inferiority of Black people, and formally freed two people during his lifetime and five in his will — all of them members of the Hemings family. His architectural practice was inseparable from that fact: the brick, joinery and nails for his buildings were produced on his own plantations by enslaved workers whose names the Thomas Jefferson Foundation has since recovered and published. In 2000 the Foundation, which owns Monticello, concluded that Jefferson was the father of Sally Hemings\'s children.',
        es: 'Jefferson esclavizó a más de 620 personas a lo largo de su vida adulta. Escribió la frase sobre la igualdad de todos los hombres, defendió en las Notas sobre el estado de Virginia la inferioridad innata de las personas negras y solo liberó formalmente a dos personas en vida y a cinco en su testamento, todas ellas de la familia Hemings. Su práctica arquitectónica es inseparable de ese hecho: el ladrillo, la carpintería y los clavos de sus edificios se produjeron en sus propias plantaciones con trabajo esclavizado, y la Thomas Jefferson Foundation ha recuperado y publicado desde entonces los nombres de quienes lo realizaron. En 2000 la fundación, propietaria de Monticello, concluyó que Jefferson fue el padre de los hijos de Sally Hemings.',
        it: 'Jefferson tenne in schiavitù più di 620 persone nel corso della sua vita adulta. Scrisse la frase sull\'uguaglianza di tutti gli uomini, sostenne nelle Note sullo Stato della Virginia l\'inferiorità innata dei neri e liberò formalmente due persone in vita e cinque per testamento, tutte della famiglia Hemings. La sua pratica architettonica è inseparabile da questo dato: i mattoni, i serramenti e i chiodi dei suoi edifici furono prodotti nelle sue piantagioni da lavoratori schiavizzati, i cui nomi la Thomas Jefferson Foundation ha in seguito ricostruito e pubblicato. Nel 2000 la fondazione, proprietaria di Monticello, concluse che Jefferson fu il padre dei figli di Sally Hemings.',
      },
      sources: [
        { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Thomas_Jefferson_and_slavery', title: 'Thomas Jefferson and slavery', license: 'CC BY-SA 4.0' },
        { kind: 'institution', url: 'https://www.monticello.org/thomas-jefferson/jefferson-slavery/', title: 'Thomas Jefferson Foundation — Jefferson and Slavery', license: null },
      ],
    },
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q11812', title: 'Thomas Jefferson (Q11812)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Thomas_Jefferson', title: 'Thomas Jefferson', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'louis-sullivan',
    wikidataId: 'Q243240',
    name: 'Louis Sullivan',
    alternativeNames: ['Louis Henry Sullivan', 'Louis H. Sullivan'],
    gender: 'man',
    born: 1856,
    died: 1924,
    floruit: { start: 1886, end: 1922, override: false },
    movements: 'unaffiliated',
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'commercial',
    signatureMaterial: 'brick',
    portrait: {
      en: 'Sullivan spent a year at MIT and a few months in the atelier of Émile Vaudremer in Paris, then went to Chicago and, in partnership with the engineer Dankmar Adler from 1883, worked out what a steel-framed office building should look like. His answer, set down in "The Tall Office Building Artistically Considered" (1896), was that it must be tall — "every inch of it tall" — and that its form should follow its function. The Wainwright and Guaranty buildings put that argument into brick and terracotta. He is conventionally filed under the Chicago School, but the label sits awkwardly: his ornament, a dense foliate geometry he drew himself, has no equivalent among his contemporaries. After the partnership ended in 1895 the commissions dried up, and his last two decades produced only the small midwestern banks that are now among his most admired works.',
      es: 'Sullivan pasó un año en el MIT y unos meses en el taller de Émile Vaudremer en París; luego se instaló en Chicago y, asociado desde 1883 con el ingeniero Dankmar Adler, resolvió qué aspecto debía tener un edificio de oficinas con estructura de acero. Su respuesta, formulada en «The Tall Office Building Artistically Considered» (1896), fue que debía ser alto —«alto en cada pulgada»— y que su forma debía seguir a su función. Los edificios Wainwright y Guaranty llevaron ese argumento al ladrillo y la terracota. Se le clasifica por costumbre en la Escuela de Chicago, pero la etiqueta le queda estrecha: su ornamento, una geometría vegetal densa que dibujaba él mismo, no tiene equivalente entre sus contemporáneos. Disuelta la sociedad en 1895, los encargos se agotaron, y sus dos últimas décadas solo dieron los pequeños bancos del Medio Oeste que hoy figuran entre sus obras más admiradas.',
      it: 'Sullivan trascorse un anno al MIT e pochi mesi nell\'atelier di Émile Vaudremer a Parigi, poi si trasferì a Chicago e, in società dal 1883 con l\'ingegnere Dankmar Adler, definì quale aspetto dovesse avere un edificio per uffici con struttura in acciaio. La sua risposta, esposta in «The Tall Office Building Artistically Considered» (1896), fu che doveva essere alto — «alto in ogni pollice» — e che la forma doveva seguire la funzione. Il Wainwright e il Guaranty tradussero quell\'argomento in mattoni e terracotta. Per convenzione lo si colloca nella Scuola di Chicago, ma l\'etichetta gli sta stretta: il suo ornato, una fitta geometria vegetale che disegnava di propria mano, non ha equivalenti fra i contemporanei. Sciolta la società nel 1895 le commissioni si esaurirono, e i suoi ultimi vent\'anni produssero soltanto le piccole banche del Midwest oggi fra le sue opere più ammirate.',
    },
    awards: ['AIA Gold Medal (1944, awarded posthumously)'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q243240', title: 'Louis Sullivan (Q243240)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Louis_Sullivan', title: 'Louis Sullivan', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'mary-colter',
    wikidataId: 'Q523888',
    name: 'Mary Colter',
    alternativeNames: ['Mary Elizabeth Jane Colter', 'Mary E. J. Colter'],
    gender: 'woman',
    born: 1869,
    died: 1958,
    floruit: { start: 1905, end: 1948, override: false },
    movements: 'unaffiliated',
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'commercial',
    signatureMaterial: 'stone',
    portrait: {
      en: 'Colter studied at the California School of Design in San Francisco and apprenticed in an architect\'s office there, then taught drawing in St Paul for fifteen years before the Fred Harvey Company took her on. From 1910 until she retired in 1948 she was its chief architect and decorator, designing the hotels, lodges and rest houses that the company ran along the Atchison, Topeka and Santa Fe Railway. She worked by research rather than by style: months of fieldwork among Ancestral Puebloan ruins, Hopi villages and Spanish mission churches preceded each design, and she specified local stone and had masons lay it to match the strata it came from. Her buildings were invented histories, complete with fictional biographies for their imagined builders, and they set the pattern for what became National Park Service rustic architecture. Four of her Grand Canyon buildings were made a National Historic Landmark in 1987.',
      es: 'Colter estudió en la California School of Design de San Francisco y se formó en un estudio de la ciudad; después enseñó dibujo en Saint Paul durante quince años, hasta que la Fred Harvey Company la contrató. Desde 1910 y hasta su retiro en 1948 fue su arquitecta y decoradora jefe, y proyectó los hoteles, albergues y casas de descanso de la empresa a lo largo del ferrocarril de Atchison, Topeka y Santa Fe. Trabajaba desde la investigación, no desde el estilo: cada proyecto venía precedido de meses de campo entre ruinas puebloanas, aldeas hopi e iglesias de misión, y prescribía piedra local que hacía asentar imitando los estratos de los que procedía. Sus edificios eran historias inventadas, con biografías ficticias para sus supuestos constructores, y fijaron el modelo del rústico del Servicio de Parques Nacionales. Cuatro de sus obras del Gran Cañón son National Historic Landmark desde 1987.',
      it: 'Colter studiò alla California School of Design di San Francisco e fece pratica in uno studio di architettura della città; insegnò poi disegno a Saint Paul per quindici anni, finché la Fred Harvey Company non la assunse. Dal 1910 fino al ritiro nel 1948 ne fu architetta e decoratrice capo, progettando gli alberghi, i rifugi e le case di sosta che l\'azienda gestiva lungo la ferrovia Atchison, Topeka and Santa Fe. Lavorava per ricerca e non per stile: ogni progetto era preceduto da mesi di sopralluoghi fra rovine ancestrali puebloane, villaggi hopi e chiese delle missioni spagnole, e prescriveva pietra locale che faceva posare imitando gli strati di provenienza. I suoi edifici erano storie inventate, complete di biografie fittizie per i costruttori immaginari, e fissarono il modello del rustico del National Park Service. Quattro sue opere al Grand Canyon sono National Historic Landmark dal 1987.',
    },
    awards: ['Arizona Women\'s Hall of Fame (1986)', 'National Cowgirl Museum and Hall of Fame (2009)'],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q523888', title: 'Mary Colter (Q523888)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Mary_Colter', title: 'Mary Colter', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'julia-morgan',
    wikidataId: 'Q601820',
    name: 'Julia Morgan',
    alternativeNames: ['Julia Hunt Morgan'],
    gender: 'woman',
    born: 1872,
    died: 1957,
    floruit: { start: 1904, end: 1947, override: false },
    movements: [
      { id: 'beaux-arts', primary: true },
      { id: 'mediterranean-vernacular', primary: false },
    ],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'civic',
    signatureMaterial: 'concrete',
    portrait: {
      en: 'Morgan took a degree in civil engineering at Berkeley, then became the first woman admitted to the architecture section of the École des Beaux-Arts in Paris and the first to leave it with a certificate, in 1902. Two years later she was the first woman licensed to practise architecture in California. Her engineering training decided her material: she built in reinforced concrete when almost nobody in California did, and when her unreinforced-masonry contemporaries lost their buildings in 1906 hers stood. Over roughly forty-five years she produced some seven hundred works — YWCA buildings, women\'s clubs, churches, schools, houses, and the long campaign at San Simeon for William Randolph Hearst. She kept no publicity office, gave no interviews, and destroyed her drawings on retirement. The AIA gave her its Gold Medal in 2014, the first woman to receive it, fifty-seven years after her death.',
      es: 'Morgan se licenció en ingeniería civil en Berkeley y fue la primera mujer admitida en la sección de arquitectura de la École des Beaux-Arts de París y la primera en salir de ella con certificado, en 1902. Dos años más tarde era la primera mujer con licencia para ejercer en California. Su formación de ingeniera decidió su material: construyó en hormigón armado cuando casi nadie lo hacía, y en 1906, cuando la fábrica sin armar de sus contemporáneos cayó, los suyos siguieron en pie. En unos cuarenta y cinco años firmó cerca de setecientas obras: sedes de la YWCA, clubes de mujeres, iglesias, escuelas, viviendas y la larga campaña de San Simeón para Hearst. No tuvo gabinete de prensa, no dio entrevistas y destruyó sus dibujos al retirarse. El AIA le dio su Medalla de Oro en 2014, primera mujer en recibirla, cincuenta y siete años después de morir.',
      it: 'Morgan si laureò in ingegneria civile a Berkeley e fu poi la prima donna ammessa alla sezione di architettura dell\'École des Beaux-Arts di Parigi e la prima a uscirne con un certificato, nel 1902. Due anni dopo era la prima donna abilitata all\'esercizio della professione in California. La formazione da ingegnere ne decise il materiale: costruì in cemento armato quando in California non lo faceva quasi nessuno, e quando nel 1906 i contemporanei persero gli edifici in muratura non armata i suoi rimasero in piedi. In circa quarantacinque anni firmò quasi settecento opere — sedi della YWCA, circoli femminili, chiese, scuole, case e la lunga campagna di San Simeon per William Randolph Hearst. Non ebbe ufficio stampa, non concesse interviste e distrusse i propri disegni al momento del ritiro. L\'AIA le assegnò la Medaglia d\'Oro nel 2014, prima donna a riceverla, cinquantasette anni dopo la morte.',
    },
    awards: ['AIA Gold Medal (2014, awarded posthumously)', 'California Hall of Fame'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q601820', title: 'Julia Morgan (Q601820)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Julia_Morgan', title: 'Julia Morgan', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'frank-lloyd-wright',
    wikidataId: 'Q5604',
    name: 'Frank Lloyd Wright',
    alternativeNames: ['Frank Lincoln Wright'],
    gender: 'man',
    born: 1867,
    died: 1959,
    floruit: { start: 1893, end: 1962, override: false },
    movements: [
      { id: 'organic-architecture', primary: true },
    ],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'domestic',
    signatureMaterial: 'concrete',
    portrait: {
      en: 'Wright left Louis Sullivan\'s office in 1893 and spent the next fifteen years dismantling the Victorian house: the Prairie plan pushed the rooms out from a central hearth, dropped the ceilings, ran the windows in bands and let the roof float. He called the result organic architecture, meaning that plan, structure, site and ornament should be generated together from one idea rather than assembled from parts. A career of about seventy years produced Unity Temple, one of the first buildings in the United States cast entirely in exposed concrete; the Imperial Hotel in Tokyo; Fallingwater, cantilevered over its waterfall; the Johnson Wax administration building with its tapered mushroom columns; some sixty low-cost Usonian houses; and finally the Guggenheim, a single ascending ramp. Eight of his buildings were inscribed together as a UNESCO World Heritage Site in 2019.',
      es: 'Wright dejó el estudio de Louis Sullivan en 1893 y pasó los quince años siguientes desarmando la casa victoriana: la planta de la pradera separó las estancias a partir de un hogar central, bajó los techos, corrió las ventanas en fajas y dejó flotar la cubierta. Llamó al resultado arquitectura orgánica, entendiendo que planta, estructura, lugar y ornamento debían generarse juntos desde una sola idea en lugar de ensamblarse por piezas. Unos setenta años de carrera dieron el Unity Temple, uno de los primeros edificios estadounidenses fundidos íntegramente en hormigón visto; el Hotel Imperial de Tokio; la Casa de la Cascada, en voladizo sobre el salto de agua; el edificio administrativo Johnson Wax con sus columnas-hongo; unas sesenta casas usonianas de bajo coste; y por último el Guggenheim, una única rampa ascendente. Ocho de sus obras fueron inscritas juntas como Patrimonio Mundial de la UNESCO en 2019.',
      it: 'Wright lasciò lo studio di Louis Sullivan nel 1893 e passò i quindici anni successivi a smontare la casa vittoriana: la pianta della prateria fece irradiare gli ambienti da un focolare centrale, abbassò i soffitti, dispose le finestre in nastri e lasciò galleggiare la copertura. Chiamò il risultato architettura organica, intendendo che pianta, struttura, luogo e ornato dovessero nascere insieme da un\'unica idea anziché essere assemblati per parti. Una carriera di circa settant\'anni produsse l\'Unity Temple, uno dei primi edifici statunitensi gettati interamente in calcestruzzo a vista; l\'Imperial Hotel di Tokyo; la Casa sulla cascata, a sbalzo sul salto d\'acqua; l\'amministrazione Johnson Wax con le colonne a fungo; una sessantina di case usoniane a basso costo; e infine il Guggenheim, un\'unica rampa ascendente. Otto sue opere sono state iscritte insieme nel Patrimonio mondiale UNESCO nel 2019.',
    },
    awards: ['RIBA Royal Gold Medal (1941)', 'AIA Gold Medal (1949)'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q5604', title: 'Frank Lloyd Wright (Q5604)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Frank_Lloyd_Wright', title: 'Frank Lloyd Wright', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'louis-kahn',
    wikidataId: 'Q210134',
    name: 'Louis Kahn',
    alternativeNames: ['Louis Isadore Kahn', 'Louis I. Kahn', 'Itze-Leib Schmuilowsky'],
    gender: 'man',
    born: 1901,
    died: 1974,
    floruit: { start: 1951, end: 1983, override: false },
    movements: [
      { id: 'brutalism', primary: true },
    ],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'educational',
    signatureMaterial: 'concrete',
    portrait: {
      en: 'Kahn was born on Saaremaa, brought to Philadelphia at four, trained in the Beaux-Arts tradition at the University of Pennsylvania, and produced almost nothing memorable until he was past fifty. A year at the American Academy in Rome in 1950–51 changed that: the ruins taught him that a building could be made of massive, singular volumes admitting daylight through openings cut in thick wall. From the Yale Art Gallery onward he built a small, dense body of work — the Salk Institute, the Kimbell with its cycloid vaults, the library at Phillips Exeter, the Indian Institute of Management at Ahmedabad, and the National Assembly at Dhaka, finished eight years after his death. He separated what he called served and servant spaces, poured concrete and laid brick as though they were being asked what they wanted to be, and left almost every surface as it came out of the formwork.',
      es: 'Kahn nació en Saaremaa, llegó a Filadelfia con cuatro años, se formó en la tradición Beaux-Arts en la Universidad de Pensilvania y no produjo casi nada memorable hasta pasados los cincuenta. Un año en la Academia Americana de Roma, en 1950-51, lo cambió todo: las ruinas le enseñaron que un edificio podía hacerse de volúmenes macizos y únicos que admiten la luz por huecos abiertos en muro grueso. Desde la Galería de Arte de Yale levantó una obra breve y densa: el Instituto Salk, el Kimbell con sus bóvedas cicloidales, la biblioteca de Phillips Exeter, el Instituto Indio de Gestión de Ahmedabad y la Asamblea Nacional de Daca, terminada ocho años después de su muerte. Distinguió lo que llamaba espacios servidos y servidores, vertió el hormigón y asentó el ladrillo como si les preguntara qué querían ser, y dejó casi todas las superficies tal como salían del encofrado.',
      it: 'Kahn nacque a Saaremaa, arrivò a Filadelfia a quattro anni, si formò nella tradizione Beaux-Arts alla University of Pennsylvania e non produsse quasi nulla di memorabile fino a oltre i cinquant\'anni. Un anno all\'Accademia Americana di Roma, nel 1950-51, cambiò tutto: le rovine gli insegnarono che un edificio poteva essere fatto di volumi massicci e singolari, illuminati da aperture tagliate nel muro spesso. Dalla Yale Art Gallery in poi costruì un corpus breve e denso: il Salk Institute, il Kimbell con le sue volte cicloidali, la biblioteca di Phillips Exeter, l\'Indian Institute of Management di Ahmedabad e l\'Assemblea Nazionale di Dacca, ultimata otto anni dopo la sua morte. Distinse quelli che chiamava spazi serviti e spazi serventi, gettò il calcestruzzo e posò il mattone come se chiedesse loro che cosa volessero essere, e lasciò quasi ogni superficie come usciva dal cassero.',
    },
    awards: ['AIA Gold Medal (1971)', 'RIBA Royal Gold Medal (1972)'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q210134', title: 'Louis Kahn (Q210134)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Louis_Kahn', title: 'Louis Kahn', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'moshe-safdie',
    wikidataId: 'Q220944',
    name: 'Moshe Safdie',
    alternativeNames: ['משה ספדיה'],
    gender: 'man',
    born: 1938,
    died: null,
    floruit: { start: 1967, end: 2025, override: false },
    movements: [
      { id: 'brutalism', primary: true },
    ],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'housing',
    signatureMaterial: 'concrete',
    portrait: {
      en: 'Safdie was born in Haifa, moved to Montréal at fifteen, and finished his architecture degree at McGill in 1961 with a thesis on a three-dimensional modular housing system. Four years later, at twenty-eight, he was building it: Habitat 67 remains the only case of a student thesis realised at full scale as a national exhibition pavilion. After a year in Louis Kahn\'s office he opened his own practice and moved it to Jerusalem, where he worked on the Old City restoration, Mamilla and Yad Vashem. His later work is large, public and geometrically ordered — the National Gallery of Canada in Ottawa, Marina Bay Sands and Jewel Changi in Singapore, the Crystal Bridges museum in Arkansas. The prefabricated repetition of Habitat has never quite been repeated: the cost per unit that the Expo 67 budget could absorb has kept the system out of ordinary housing.',
      es: 'Safdie nació en Haifa, se trasladó a Montreal a los quince años y terminó arquitectura en McGill en 1961 con una tesis sobre un sistema modular tridimensional de vivienda. Cuatro años más tarde, con veintiocho, la estaba construyendo: Habitat 67 sigue siendo el único caso de tesis estudiantil realizada a escala real como pabellón de una exposición nacional. Tras un año con Louis Kahn abrió su propio estudio y lo trasladó a Jerusalén, donde trabajó en la restauración de la Ciudad Vieja, en Mamilla y en Yad Vashem. Su obra posterior es grande, pública y de geometría ordenada: la Galería Nacional de Canadá en Ottawa, Marina Bay Sands y Jewel Changi en Singapur, el museo Crystal Bridges en Arkansas. La repetición prefabricada de Habitat no ha vuelto a darse: el coste por unidad que absorbió el presupuesto de la Expo 67 dejó el sistema fuera de la vivienda corriente.',
      it: 'Safdie nacque a Haifa, si trasferì a Montréal a quindici anni e concluse gli studi di architettura alla McGill nel 1961 con una tesi su un sistema abitativo modulare tridimensionale. Quattro anni dopo, a ventotto, lo stava costruendo: Habitat 67 resta l\'unico caso di tesi studentesca realizzata a grandezza naturale come padiglione di un\'esposizione nazionale. Dopo un anno nello studio di Louis Kahn aprì il proprio e lo trasferì a Gerusalemme, dove lavorò al restauro della Città Vecchia, a Mamilla e allo Yad Vashem. L\'opera successiva è grande, pubblica e di geometria ordinata: la Galleria nazionale del Canada a Ottawa, Marina Bay Sands e Jewel Changi a Singapore, il museo Crystal Bridges in Arkansas. La ripetizione prefabbricata di Habitat non si è più data: il costo per unità che il bilancio dell\'Expo 67 poté assorbire ha tenuto il sistema fuori dall\'edilizia ordinaria.',
    },
    awards: ['Companion of the Order of Canada', 'AIA Gold Medal (2015)', 'Wolf Prize in Architecture (2015)'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q220944', title: 'Moshe Safdie (Q220944)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Moshe_Safdie', title: 'Moshe Safdie', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'eero-saarinen',
    wikidataId: 'Q167073',
    name: 'Eero Saarinen',
    alternativeNames: [],
    gender: 'man',
    born: 1910,
    died: 1961,
    floruit: { start: 1948, end: 1965, override: false },
    movements: [
      { id: 'international-style', primary: true },
    ],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'infrastructure',
    signatureMaterial: 'concrete',
    portrait: {
      en: 'Saarinen was born outside Helsinki, brought to Michigan at thirteen when his father Eliel took over Cranbrook, and studied sculpture in Paris before architecture at Yale. He worked in his father\'s office until Eliel\'s death in 1950, by which time he had won the St Louis arch competition with a catenary curve. What followed was deliberately inconsistent: he refused a house style and gave each commission the form he thought its problem demanded. The General Motors Technical Center is a machine-finished steel-and-glass campus; the MIT chapel is a windowless brick cylinder; the TWA terminal and Dulles are thin concrete shells; the CBS Building is a granite-clad tower. Critics of the period read the range as opportunism; it is now generally read as a refusal to let a signature stand in for an argument. He died at fifty-one, and his office completed nine buildings after him.',
      es: 'Saarinen nació cerca de Helsinki, llegó a Michigan a los trece años cuando su padre Eliel se hizo cargo de Cranbrook y estudió escultura en París antes que arquitectura en Yale. Trabajó en el estudio paterno hasta la muerte de Eliel en 1950; ya había ganado el concurso del arco de San Luis con una catenaria. Lo que vino después fue deliberadamente inconsistente: rechazó un estilo propio y dio a cada encargo la forma que su problema parecía exigir. El Centro Técnico de General Motors es un campus de acero y vidrio industrial; la capilla del MIT, un cilindro ciego de ladrillo; la TWA y Dulles, láminas delgadas de hormigón; la CBS, una torre de granito. La crítica de la época leyó esa variedad como oportunismo; hoy se lee como negativa a que la firma sustituya al argumento. Murió a los cincuenta y uno; su estudio terminó nueve obras después.',
      it: 'Saarinen nacque presso Helsinki, arrivò in Michigan a tredici anni quando il padre Eliel prese la direzione di Cranbrook e studiò scultura a Parigi prima di architettura a Yale. Lavorò nello studio paterno fino alla morte di Eliel nel 1950; aveva già vinto il concorso per l\'arco di Saint Louis con una catenaria. Ciò che seguì fu volutamente incoerente: rifiutò uno stile di studio e diede a ogni incarico la forma che il problema sembrava esigere. Il General Motors Technical Center è un campus di acciaio e vetro a finitura industriale; la cappella del MIT un cilindro cieco di mattoni; il TWA e Dulles sottili gusci di calcestruzzo; il CBS Building una torre di granito. La critica lesse quella varietà come opportunismo; oggi la si legge come rifiuto di far valere una firma al posto di un argomento. Morì a cinquantun anni; lo studio completò nove edifici dopo di lui.',
    },
    awards: ['AIA Gold Medal (1962, awarded posthumously)'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q167073', title: 'Eero Saarinen (Q167073)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Eero_Saarinen', title: 'Eero Saarinen', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'jeanne-gang',
    wikidataId: 'Q444257',
    name: 'Jeanne Gang',
    alternativeNames: [],
    gender: 'woman',
    born: 1964,
    died: null,
    floruit: { start: 2004, end: 2025, override: false },
    movements: [
      { id: 'sustainable-architecture', primary: true },
    ],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'tower',
    signatureMaterial: 'concrete',
    portrait: {
      en: 'Gang grew up in Belvidere, Illinois, took an architecture degree at the University of Illinois, spent a year in Rem Koolhaas\'s office in Rotterdam, finished a master\'s at Harvard in 1993 and started Studio Gang in Chicago in 1997. Her practice treats a building as an ecological and social instrument before a formal one: the balcony slabs at Aqua were shaped for views, shade, downdraught and bird strikes at once; the Arcus Center in Kalamazoo is built of cordwood masonry laid by local crews; the Gilder Center in New York was shot in place as sprayed concrete over rebar, without formwork. She has argued consistently for reuse over demolition and for what she calls actionable idealism — measuring a design by what it changes rather than by how it looks. She was a MacArthur Fellow in 2011 and has taught at Harvard since the same year.',
      es: 'Gang creció en Belvidere, Illinois, se licenció en arquitectura por la Universidad de Illinois, pasó un año en el estudio de Rem Koolhaas en Róterdam, terminó un máster en Harvard en 1993 y fundó Studio Gang en Chicago en 1997. Su práctica entiende el edificio como instrumento ecológico y social antes que formal: los forjados-balcón de Aqua se moldearon a la vez por las vistas, la sombra, las corrientes descendentes y las colisiones de aves; el Arcus Center de Kalamazoo está levantado con mampostería de leña colocada por cuadrillas locales; el Gilder Center de Nueva York se proyectó in situ como hormigón gunitado sobre armadura, sin encofrado. Ha defendido con constancia la reutilización frente al derribo y lo que llama idealismo accionable: medir un proyecto por lo que cambia y no por su aspecto. Fue becaria MacArthur en 2011 y enseña en Harvard desde ese mismo año.',
      it: 'Gang è cresciuta a Belvidere, in Illinois, si è laureata in architettura all\'Università dell\'Illinois, ha trascorso un anno nello studio di Rem Koolhaas a Rotterdam, ha concluso un master a Harvard nel 1993 e ha fondato Studio Gang a Chicago nel 1997. La sua pratica considera l\'edificio anzitutto uno strumento ecologico e sociale, e solo poi formale: le solette-balcone di Aqua sono state modellate insieme per le viste, l\'ombra, le correnti discendenti e l\'impatto degli uccelli; l\'Arcus Center di Kalamazoo è costruito in muratura di legna posata da maestranze locali; il Gilder Center di New York è stato realizzato in opera come calcestruzzo spruzzato su armatura, senza casseri. Sostiene con coerenza il riuso contro la demolizione e quello che chiama idealismo attuabile: misurare un progetto da ciò che cambia, non da come appare. È stata MacArthur Fellow nel 2011 e insegna a Harvard dallo stesso anno.',
    },
    awards: ['MacArthur Fellowship (2011)', 'National Design Award in Architecture (2013)'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q444257', title: 'Jeanne Gang (Q444257)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Jeanne_Gang', title: 'Jeanne Gang', license: 'CC BY-SA 4.0' },
    ],
  },
];
