import type { Architect } from '@/types/architect';

// Wave 5 curator agent (Brazil and the Southern Cone): real, sourced Architect entries for this slice.
//
// workRegions / workCentroid are derived by `npm run data:curate` from each
// architect's buildings and are deliberately left empty here.
export const AMERICAS_SOUTHERN_ARCHITECTS: Architect[] = [
  {
    id: 'aleijadinho',
    wikidataId: 'Q379714',
    name: 'Aleijadinho',
    alternativeNames: ['Antônio Francisco Lisboa', 'António Francisco Lisboa', 'O Aleijadinho'],
    gender: 'man',
    born: 1738,
    died: 1814,
    floruit: { start: 1766, end: 1805, override: false },
    movements: 'unaffiliated',
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'sacral',
    signatureMaterial: 'stone',
    portrait: {
      en: 'Antônio Francisco Lisboa was born in Ouro Preto around 1738, the son of the Portuguese architect Manuel Francisco Lisboa and an enslaved African woman, and he worked his whole life in the gold towns of Minas Gerais. He designed and carved at once — soapstone portals, pulpits, altarpieces, whole church fronts — and the nickname Aleijadinho, "little cripple", comes from the degenerative illness that deformed his hands in old age. Portuguese Wikipedia is careful to note that most of the four hundred works now attached to his name were attributed by stylistic resemblance rather than by document, and that the earliest substantial biography was written forty-four years after his death; São Francisco de Assis in Ouro Preto is among the securest attributions. His curved fronts, cylindrical towers and overflowing reliefs are the high point of the Brazilian Baroque and Rococo.',
      es: 'Antônio Francisco Lisboa nació en Ouro Preto hacia 1738, hijo del arquitecto portugués Manuel Francisco Lisboa y de una mujer africana esclavizada, y trabajó toda su vida en las villas del oro de Minas Gerais. Proyectaba y tallaba a la vez —portadas de esteatita, púlpitos, retablos, fachadas enteras—, y el apodo Aleijadinho procede de la enfermedad degenerativa que le deformó las manos en la vejez. La Wikipedia en portugués advierte que la mayoría de las cuatrocientas obras hoy asociadas a su nombre se le atribuyeron por semejanza estilística y no por documento, y que la primera biografía sustancial se escribió cuarenta y cuatro años después de su muerte; São Francisco de Assis de Ouro Preto figura entre las atribuciones más firmes. Sus fachadas curvas, sus torres cilíndricas y sus relieves desbordantes son la cumbre del barroco y el rococó brasileños.',
      it: 'Antônio Francisco Lisboa nacque a Ouro Preto verso il 1738, figlio dell\'architetto portoghese Manuel Francisco Lisboa e di una donna africana ridotta in schiavitù, e lavorò per tutta la vita nelle città dell\'oro del Minas Gerais. Progettava e scolpiva insieme — portali in pietra ollare, pulpiti, altari, intere facciate — e il soprannome Aleijadinho, "storpietto", viene dalla malattia degenerativa che in vecchiaia gli deformò le mani. La Wikipedia portoghese avverte che gran parte delle quattrocento opere oggi legate al suo nome gli è stata attribuita per somiglianza stilistica e non per documento, e che la prima biografia sostanziale fu scritta quarantaquattro anni dopo la sua morte; São Francisco de Assis a Ouro Preto è fra le attribuzioni più solide. Facciate curve, torri cilindriche e rilievi debordanti sono il vertice del barocco e del rococò brasiliani.',
    },
    awards: [],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q379714', title: 'Aleijadinho (Q379714)', license: null },
      { kind: 'wikipedia', url: 'https://pt.wikipedia.org/wiki/Aleijadinho', title: 'Aleijadinho', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Church_of_Saint_Francis_of_Assisi_(Ouro_Preto)', title: 'Church of Saint Francis of Assisi (Ouro Preto)', license: 'CC BY-SA 4.0' },
    ],
  },

  {
    id: 'giovanni-battista-primoli',
    wikidataId: 'Q9015232',
    name: 'Giovanni Battista Prímoli',
    alternativeNames: ['Juan Bautista Prímoli', 'João Batista Primoli', 'Giovanni Battista Primoli'],
    gender: 'man',
    born: 1673,
    died: 1747,
    floruit: { start: 1719, end: 1747, override: false },
    movements: 'unaffiliated',
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'sacral',
    signatureMaterial: 'stone',
    portrait: {
      en: 'Trained as an architect in Milan and then admitted to the Society of Jesus, Giovanni Battista Prímoli reached Buenos Aires in 1717 and spent the remaining thirty years of his life building for the Jesuit province of Paraquaria. In Buenos Aires he finished the church of San Ignacio, begun by Johann Kraus, and worked on San Francisco, El Pilar, La Merced, San Pedro Telmo and the town cabildo; in Córdoba he raised the definitive fabric of the cathedral and worked on the Compañía de Jesús. He also designed the churches of the Guaraní mission towns of San Miguel, Concepción and Trinidad, and the layout of the Trinidad reduction as a whole. He died in 1747 at the Candelaria mission. His idiom is a plain, massive Italian Baroque cut in local sandstone by Guaraní masons.',
      es: 'Formado como arquitecto en Milán y admitido después en la Compañía de Jesús, Giovanni Battista Prímoli llegó a Buenos Aires en 1717 y dedicó los treinta años que le quedaban de vida a construir para la provincia jesuítica del Paraguay. En Buenos Aires concluyó el templo de San Ignacio, iniciado por Juan Kraus, y trabajó en San Francisco, el Pilar, la Merced, San Pedro Telmo y el cabildo porteño; en Córdoba levantó la fábrica definitiva de la catedral e intervino en la iglesia de la Compañía de Jesús. Suyas son también las iglesias de los pueblos guaraníes de San Miguel, Concepción y Trinidad, y el trazado entero de la reducción de Trinidad. Murió en 1747 en la reducción de Candelaria. Su lenguaje es un barroco italiano sobrio y macizo, labrado en arenisca local por canteros guaraníes.',
      it: 'Formatosi come architetto a Milano e poi ammesso nella Compagnia di Gesù, Giovanni Battista Primoli giunse a Buenos Aires nel 1717 e dedicò i trent\'anni che gli restavano a costruire per la provincia gesuitica del Paraguay. A Buenos Aires portò a termine la chiesa di San Ignacio, avviata da Johann Kraus, e lavorò a San Francisco, al Pilar, alla Merced, a San Pedro Telmo e al cabildo cittadino; a Córdoba innalzò la fabbrica definitiva della cattedrale e intervenne nella chiesa della Compagnia. Sue sono anche le chiese dei villaggi guaraní di San Miguel, Concepción e Trinidad, e l\'intero impianto della riduzione di Trinidad. Morì nel 1747 alla riduzione di Candelaria. Il suo linguaggio è un barocco italiano sobrio e massiccio, tagliato nell\'arenaria locale da scalpellini guaraní.',
    },
    awards: [],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q9015232', title: 'Giovanni Battista Prímoli (Q9015232)', license: null },
      { kind: 'wikipedia', url: 'https://es.wikipedia.org/wiki/Juan_Bautista_Pr%C3%ADmoli', title: 'Juan Bautista Prímoli', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://es.wikipedia.org/wiki/Misi%C3%B3n_jesu%C3%ADtica_de_La_Sant%C3%ADsima_Trinidad_de_Paran%C3%A1', title: 'Misión jesuítica de La Santísima Trinidad de Paraná', license: 'CC BY-SA 4.0' },
    ],
  },

  {
    id: 'mario-palanti',
    wikidataId: 'Q963606',
    name: 'Mario Palanti',
    alternativeNames: ['Palanti'],
    gender: 'man',
    born: 1885,
    died: 1978,
    floruit: { start: 1913, end: 1929, override: false },
    movements: 'unaffiliated',
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'tower',
    signatureMaterial: 'concrete',
    portrait: {
      en: 'Mario Palanti studied painting at the Brera Academy and architecture at the Milan Polytechnic before arriving in Argentina in 1909, where he first worked in the office of Arturo Prins and Oskar Ranzenhofer on the neo-Gothic law faculty in Buenos Aires. On his own account he built a run of extravagantly decorated apartment houses along Avenida Rivadavia from 1913, the Hotel Castelar on Avenida de Mayo, and the South American head office of the Banco Francés e Italiano. His two towers — the Palacio Barolo in Buenos Aires and its Montevideo twin, the Palacio Salvo — carried reinforced concrete higher than anything else on the River Plate and made him famous. Spanish Wikipedia describes his manner as brushing against Art Nouveau and Art Deco while remaining, in the end, an idiom of his own. He returned to Milan and died there in 1978.',
      es: 'Mario Palanti estudió pintura en la Academia de Brera y arquitectura en el Politécnico de Milán antes de llegar a la Argentina en 1909, donde trabajó primero en el estudio de Arturo Prins y Oskar Ranzenhofer, colaborando en la Facultad de Derecho neogótica de Buenos Aires. Por cuenta propia levantó desde 1913 una serie de casas de renta de decoración desbordante en la Avenida Rivadavia, el Hotel Castelar de la Avenida de Mayo y la casa matriz sudamericana del Banco Francés e Italiano. Sus dos torres —el Palacio Barolo porteño y su mellizo montevideano, el Palacio Salvo— llevaron el hormigón armado más alto que ninguna otra obra del Río de la Plata y lo hicieron célebre. La Wikipedia en español describe su manera como un roce con el art nouveau y el art déco que acaba siendo un estilo propio. Regresó a Milán, donde murió en 1978.',
      it: 'Mario Palanti studiò pittura all\'Accademia di Brera e architettura al Politecnico di Milano prima di sbarcare in Argentina nel 1909, dove lavorò dapprima nello studio di Arturo Prins e Oskar Ranzenhofer, collaborando alla neogotica Facoltà di Giurisprudenza di Buenos Aires. In proprio realizzò dal 1913 una serie di case da reddito di decorazione esuberante lungo la Avenida Rivadavia, l\'Hotel Castelar sulla Avenida de Mayo e la sede sudamericana del Banco Francés e Italiano. Le sue due torri — il Palacio Barolo di Buenos Aires e il gemello montevideano Palacio Salvo — portarono il cemento armato più in alto di qualsiasi altra opera del Río de la Plata e lo resero celebre. La Wikipedia spagnola descrive la sua maniera come uno sfiorare l\'art nouveau e l\'art déco che finisce per essere uno stile suo. Tornò a Milano, dove morì nel 1978.',
    },
    awards: [],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q963606', title: 'Mario Palanti (Q963606)', license: null },
      { kind: 'wikipedia', url: 'https://es.wikipedia.org/wiki/Mario_Palanti', title: 'Mario Palanti', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://es.wikipedia.org/wiki/Palacio_Barolo', title: 'Palacio Barolo', license: 'CC BY-SA 4.0' },
    ],
  },

  {
    id: 'lucio-costa',
    wikidataId: 'Q298926',
    name: 'Lúcio Costa',
    alternativeNames: ['Lucio Costa', 'Lúcio Marçal Ferreira Ribeiro de Lima Costa'],
    gender: 'man',
    born: 1902,
    died: 1998,
    floruit: { start: 1936, end: 1960, override: false },
    movements: [
      { id: 'international-style', primary: true },
      { id: 'tropical-modernism', primary: false },
    ],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'civic',
    signatureMaterial: 'concrete',
    portrait: {
      en: 'Born in Toulon to Brazilian parents, schooled in England and Switzerland and trained at the National School of Fine Arts in Rio, Lúcio Costa turned to Modernism in 1929 and spent the rest of his life arguing that it could be made Brazilian. Briefly director of the school he had attended, he joined the new national heritage service SPHAN in 1937 and stayed there until retirement, which left him unusually fluent in both colonial fabric and reinforced concrete. In 1936 he used his standing in government to set aside a won competition and assemble his own team for the Ministry of Education and Health; the building that followed became the template for Brazilian modern architecture. His Parque Guinle slabs of 1948 rehearsed the residential superblock, and in 1957 his Plano Piloto won the competition for Brasília.',
      es: 'Nacido en Tolón de padres brasileños, educado en Inglaterra y Suiza y formado en la Escuela Nacional de Bellas Artes de Río, Lúcio Costa se pasó al modernismo en 1929 y dedicó el resto de su vida a sostener que podía volverse brasileño. Director por poco tiempo de la escuela en que había estudiado, entró en 1937 en el flamante servicio nacional de patrimonio, el SPHAN, donde permaneció hasta jubilarse: de ahí su rara soltura tanto con la fábrica colonial como con el hormigón armado. En 1936 empleó su peso en el gobierno para anular un concurso ya fallado y armar su propio equipo para el Ministerio de Educación y Salud; el edificio resultante fijó el molde de la arquitectura moderna brasileña. Sus bloques del Parque Guinle, de 1948, ensayaron la supermanzana residencial, y en 1957 su Plano Piloto ganó el concurso de Brasilia.',
      it: 'Nato a Tolone da genitori brasiliani, educato in Inghilterra e in Svizzera e formatosi alla Scuola Nazionale di Belle Arti di Rio, Lúcio Costa passò al modernismo nel 1929 e dedicò il resto della vita a sostenere che lo si potesse rendere brasiliano. Per breve tempo direttore della scuola in cui aveva studiato, nel 1937 entrò nel nuovo servizio nazionale per il patrimonio, lo SPHAN, dove rimase fino alla pensione: di qui la sua rara dimestichezza tanto con la fabbrica coloniale quanto con il cemento armato. Nel 1936 usò il proprio peso presso il governo per annullare un concorso già aggiudicato e formare una squadra propria per il Ministero dell\'Educazione e della Sanità; l\'edificio che ne seguì fissò il modello dell\'architettura moderna brasiliana. Le stecche del Parque Guinle del 1948 provarono il superisolato residenziale, e nel 1957 il suo Plano Piloto vinse il concorso per Brasilia.',
    },
    awards: ['Sir Patrick Abercrombie Prize (UIA, 1984)', 'Ordem do Mérito Cultural (1997)'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q298926', title: 'Lúcio Costa (Q298926)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/L%C3%BAcio_Costa', title: 'Lúcio Costa', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Gustavo_Capanema_Palace', title: 'Gustavo Capanema Palace', license: 'CC BY-SA 4.0' },
    ],
  },

  {
    id: 'francisco-salamone',
    wikidataId: 'Q5483918',
    name: 'Francisco Salamone',
    alternativeNames: ['Francesco Salamone', 'Salamone'],
    gender: 'man',
    born: 1897,
    died: 1959,
    floruit: { start: 1936, end: 1940, override: false },
    movements: [{ id: 'art-deco', primary: true }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'civic',
    signatureMaterial: 'concrete',
    portrait: {
      en: 'Born in Leonforte, Sicily, and brought to Argentina as a child, Francisco Salamone qualified as architect and civil engineer in 1920 after the Otto Krause technical school and universities in La Plata and Córdoba. His whole reputation rests on four years. Between 1936 and 1940, under the provincial administration of Manuel Fresco, he won contract after contract and put up more than sixty large public works in twenty-five municipalities of Buenos Aires Province: town halls with towers taller than the parish church, monumental cemetery portals and rationalist slaughterhouses, all in reinforced concrete and all several times the height of the low pampa towns around them. English Wikipedia describes the result as Art Deco functionalism crossed with Italian Futurism at vast scale. He left public work after 1940, was largely forgotten, and died in Buenos Aires in 1959.',
      es: 'Nacido en Leonforte, Sicilia, y llevado a la Argentina de niño, Francisco Salamone se recibió de arquitecto e ingeniero civil en 1920, tras el colegio Otto Krause y las universidades de La Plata y Córdoba. Toda su fama descansa en cuatro años. Entre 1936 y 1940, bajo la administración provincial de Manuel Fresco, ganó licitación tras licitación y levantó más de sesenta grandes obras públicas en veinticinco municipios bonaerenses: palacios municipales con torres más altas que el campanario de la parroquia, portales de cementerio monumentales y mataderos racionalistas, todos en hormigón armado y todos varias veces más altos que los pueblos llanos que los rodeaban. La Wikipedia en inglés describe el resultado como un funcionalismo art déco cruzado con futurismo italiano a escala descomunal. Dejó la obra pública después de 1940, cayó en el olvido y murió en Buenos Aires en 1959.',
      it: 'Nato a Leonforte, in Sicilia, e portato in Argentina da bambino, Francisco Salamone si laureò in architettura e ingegneria civile nel 1920, dopo la scuola tecnica Otto Krause e le università di La Plata e Córdoba. Tutta la sua fama poggia su quattro anni. Fra il 1936 e il 1940, sotto l\'amministrazione provinciale di Manuel Fresco, vinse un appalto dopo l\'altro e realizzò oltre sessanta grandi opere pubbliche in venticinque comuni della provincia di Buenos Aires: municipi con torri più alte del campanile parrocchiale, portali di cimitero monumentali e mattatoi razionalisti, tutti in cemento armato e tutti molte volte più alti dei paesi bassi che li circondavano. La Wikipedia inglese descrive l\'esito come un funzionalismo art déco incrociato con il futurismo italiano a scala smisurata. Abbandonò l\'opera pubblica dopo il 1940, fu quasi dimenticato e morì a Buenos Aires nel 1959.',
    },
    awards: ['Medals at the Milan and Barcelona exhibitions (1919)'],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q5483918', title: 'Francisco Salamone (Q5483918)', license: null },
      { kind: 'wikipedia', url: 'https://es.wikipedia.org/wiki/Francisco_Salamone', title: 'Francisco Salamone', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Francisco_Salamone', title: 'Francisco Salamone', license: 'CC BY-SA 4.0' },
    ],
  },

  {
    id: 'lina-bo-bardi',
    wikidataId: 'Q272400',
    name: 'Lina Bo Bardi',
    alternativeNames: ['Achillina Bo', 'Lina Bo'],
    gender: 'woman',
    born: 1914,
    died: 1992,
    floruit: { start: 1951, end: 1990, override: false },
    movements: [
      { id: 'critical-regionalism', primary: true },
      { id: 'international-style', primary: false },
    ],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'cultural',
    signatureMaterial: 'concrete',
    portrait: {
      en: 'Achillina Bo graduated in architecture in Rome in 1939, moved to Milan to work with Carlo Pagani and Giò Ponti, lost her own studio to an air raid in 1943, joined the Italian resistance and by 1944 was deputy director of Domus. In October 1946, married to the critic Pietro Maria Bardi, she sailed for Brazil; she became a Brazilian citizen in 1951, the year she finished her first building, the Glass House in Morumbi. English Wikipedia records that she found acceptance among Brazilian architects difficult, as both a foreigner and a woman. What followed — the São Paulo Museum of Art, the Bahia museums, the SESC Pompéia factory conversion — filtered modern concrete through Brazilian popular craft and use. "I did not look for beauty," she wrote of MASP. "I looked for freedom."',
      es: 'Achillina Bo se tituló de arquitecta en Roma en 1939, se trasladó a Milán para trabajar con Carlo Pagani y Giò Ponti, perdió su propio estudio en un bombardeo aéreo en 1943, participó en la resistencia italiana y en 1944 era subdirectora de Domus. En octubre de 1946, casada con el crítico Pietro Maria Bardi, se embarcó hacia Brasil; se nacionalizó brasileña en 1951, el año en que terminó su primera obra construida, la Casa de Vidrio de Morumbi. La Wikipedia en inglés recoge que le costó ser aceptada entre los arquitectos brasileños, por extranjera y por mujer. Lo que vino después —el Museo de Arte de São Paulo, los museos de Bahía, la reconversión de la fábrica del SESC Pompéia— pasó el hormigón moderno por el tamiz del oficio y el uso populares brasileños. "No busqué la belleza —escribió del MASP—: busqué la libertad".',
      it: 'Achillina Bo si laureò in architettura a Roma nel 1939, si trasferì a Milano per lavorare con Carlo Pagani e Giò Ponti, perse il proprio studio in un bombardamento nel 1943, partecipò alla resistenza italiana e nel 1944 era vicedirettrice di Domus. Nell\'ottobre del 1946, sposata con il critico Pietro Maria Bardi, salpò per il Brasile; ottenne la cittadinanza brasiliana nel 1951, l\'anno in cui completò la sua prima opera costruita, la Casa di Vetro a Morumbi. La Wikipedia inglese ricorda quanto le fu difficile farsi accettare dagli architetti brasiliani, in quanto straniera e in quanto donna. Ciò che seguì — il Museo d\'Arte di San Paolo, i musei di Bahia, la riconversione della fabbrica del SESC Pompéia — filtrò il cemento moderno attraverso l\'artigianato e gli usi popolari brasiliani. "Non ho cercato la bellezza", scrisse del MASP: "ho cercato la libertà".',
    },
    awards: ['Ordem do Mérito Cultural (2007, posthumous)'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q272400', title: 'Lina Bo Bardi (Q272400)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Lina_Bo_Bardi', title: 'Lina Bo Bardi', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/S%C3%A3o_Paulo_Museum_of_Art', title: 'São Paulo Museum of Art', license: 'CC BY-SA 4.0' },
    ],
  },

  {
    id: 'oscar-niemeyer',
    wikidataId: 'Q134165',
    name: 'Oscar Niemeyer',
    alternativeNames: ['Oscar Ribeiro de Almeida Niemeyer Soares Filho', 'Óscar Niemeyer'],
    gender: 'man',
    born: 1907,
    died: 2012,
    floruit: { start: 1943, end: 2012, override: false },
    movements: [
      { id: 'international-style', primary: true },
      { id: 'tropical-modernism', primary: false },
    ],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'civic',
    signatureMaterial: 'concrete',
    portrait: {
      en: 'Oscar Niemeyer graduated from the National School of Fine Arts in Rio in 1934 and went to work as an intern in Lúcio Costa\'s office, joining the team for the Ministry of Education and Health. Over seventy-eight years he designed roughly six hundred projects, and from 1957 he built most of the monuments of Brasília to Costa\'s plan. A lifelong socialist, atheist and member of the Brazilian Communist Party, he left the country after the 1964 military coup and opened an office in Paris, spending time in Cuba and the Soviet Union; he returned in 1985, received the Pritzker Prize in 1988 and served as the party\'s president from 1992 to 1996. His late works include the Niterói Contemporary Art Museum of 1996 and the Oscar Niemeyer Museum of 2002. He died in Rio in 2012, aged 104.',
      es: 'Oscar Niemeyer se recibió en la Escuela Nacional de Bellas Artes de Río en 1934 y entró como pasante en el estudio de Lúcio Costa, sumándose al equipo del Ministerio de Educación y Salud. A lo largo de setenta y ocho años proyectó unas seiscientas obras, y desde 1957 construyó la mayoría de los monumentos de Brasilia sobre el plan de Costa. Socialista, ateo y militante del Partido Comunista Brasileño toda su vida, dejó el país tras el golpe militar de 1964 y abrió estudio en París, con estancias en Cuba y la Unión Soviética; regresó en 1985, recibió el Premio Pritzker en 1988 y presidió el partido entre 1992 y 1996. Entre sus obras tardías están el Museo de Arte Contemporáneo de Niterói, de 1996, y el Museo Oscar Niemeyer, de 2002. Murió en Río en 2012, a los ciento cuatro años.',
      it: 'Oscar Niemeyer si laureò alla Scuola Nazionale di Belle Arti di Rio nel 1934 ed entrò come tirocinante nello studio di Lúcio Costa, unendosi alla squadra del Ministero dell\'Educazione e della Sanità. In settantotto anni progettò circa seicento opere e dal 1957 costruì gran parte dei monumenti di Brasilia secondo il piano di Costa. Socialista, ateo e militante del Partito Comunista Brasiliano per tutta la vita, lasciò il paese dopo il colpo di Stato militare del 1964 e aprì uno studio a Parigi, con soggiorni a Cuba e in Unione Sovietica; rientrò nel 1985, ricevette il Premio Pritzker nel 1988 e presiedette il partito dal 1992 al 1996. Fra le opere tarde figurano il Museo d\'Arte Contemporanea di Niterói del 1996 e il Museo Oscar Niemeyer del 2002. Morì a Rio nel 2012, a centoquattro anni.',
    },
    awards: ['Pritzker Architecture Prize (1988)'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q134165', title: 'Oscar Niemeyer (Q134165)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Oscar_Niemeyer', title: 'Oscar Niemeyer', license: 'CC BY-SA 4.0' },
    ],
  },

  {
    id: 'eladio-dieste',
    wikidataId: 'Q1324787',
    name: 'Eladio Dieste',
    alternativeNames: ['Dieste'],
    gender: 'man',
    born: 1917,
    died: 2000,
    floruit: { start: 1955, end: 1998, override: false },
    movements: [{ id: 'critical-regionalism', primary: true }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'industrial',
    signatureMaterial: 'brick',
    portrait: {
      en: 'Eladio Dieste trained as a civil engineer in Montevideo and built almost his entire body of work in Uruguay: markets, warehouses, silos, bus stations, factories and a handful of churches. Starting from experiments with reinforced-concrete vaults, he arrived at what he called cerámica armada — thin laminar shells of ordinary fired brick with steel reinforcement laid in the joints, calculated with heavy mathematics and built with local labour and local material. The results roof spans that would normally demand steel, at roughly the cost of a shed. His own argument was economic before it was aesthetic: "a healthy architecture cannot be produced without a rational and economical use of building materials." He was made a doctor honoris causa by the Universidad de la República in 1993, and died in 2000.',
      es: 'Eladio Dieste se formó como ingeniero civil en Montevideo y construyó casi toda su obra en el Uruguay: mercados, depósitos, silos, terminales de ómnibus, fábricas y unas pocas iglesias. Partiendo de sus ensayos con bóvedas de hormigón armado, llegó a lo que llamó cerámica armada: láminas delgadas de ladrillo común con armaduras de acero alojadas en las juntas, calculadas con matemática intensa y levantadas con mano de obra y material del lugar. El resultado cubre luces que normalmente exigirían acero, a un costo parecido al de un galpón. Su argumento era económico antes que estético: "una arquitectura sana no puede producirse sin un uso racional y económico de los materiales de la construcción". La Universidad de la República lo nombró doctor honoris causa en 1993. Murió en 2000.',
      it: 'Eladio Dieste si formò come ingegnere civile a Montevideo e costruì quasi tutta la sua opera in Uruguay: mercati, magazzini, silos, autostazioni, fabbriche e poche chiese. Partendo dalle sperimentazioni sulle volte in cemento armato, arrivò a quella che chiamò cerámica armada: sottili lamine di mattone comune con armature d\'acciaio annegate nei giunti, calcolate con matematica intensa e costruite con manodopera e materiali del luogo. Il risultato copre luci che di norma richiederebbero l\'acciaio, a un costo simile a quello di un capannone. Il suo argomento era economico prima che estetico: "un\'architettura sana non può prodursi senza un uso razionale ed economico dei materiali da costruzione". L\'Universidad de la República lo nominò dottore honoris causa nel 1993. Morì nel 2000.',
    },
    awards: ['Doctor honoris causa, Universidad de la República (1993)'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q1324787', title: 'Eladio Dieste (Q1324787)', license: null },
      { kind: 'wikipedia', url: 'https://es.wikipedia.org/wiki/Iglesia_de_Cristo_Obrero_y_Nuestra_Se%C3%B1ora_de_Lourdes', title: 'Iglesia de Cristo Obrero y Nuestra Señora de Lourdes', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Eladio_Dieste', title: 'Eladio Dieste', license: 'CC BY-SA 4.0' },
    ],
  },

  {
    id: 'debora-iaroslavschi',
    wikidataId: 'Q46133648',
    name: 'Débora Iaroslavschi',
    alternativeNames: ['Débora di Veroli', 'Débora Iaroslavschi de Di Veroli'],
    gender: 'woman',
    born: 1926,
    died: 2023,
    floruit: { start: 1949, end: 1972, override: false },
    movements: [{ id: 'international-style', primary: true }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'housing',
    signatureMaterial: 'concrete',
    portrait: {
      en: 'Born in Galați, Romania, Débora Iaroslavschi followed her father to Argentina in 1936 and was one of very few women in the architecture school of the University of Buenos Aires, graduating in 1953; she went on to become one of the first Argentine women to qualify as an urban and regional planner. Her early houses — Don Torcuato 1949, Furmann 1951, Rothschild 1954, Pogré 1956 — worked out the modern lesson of open plans, planted flat roofs, ribbon windows and reinforced concrete. From 1958 she built almost continuously on the Atlantic coast with the developer Domingo Fiorentini: the first tall building in Miramar, then the Eiffel, Alsancor and Alsina blocks in Mar del Plata and the Mirador Cabo Corrientes. Late in life she turned to accessibility and architecture for ageing, publishing on Alzheimer\'s and building design.',
      es: 'Nacida en Galați, Rumania, Débora Iaroslavschi siguió a su padre a la Argentina en 1936 y fue una de las poquísimas mujeres de la escuela de arquitectura de la Universidad de Buenos Aires, donde se graduó en 1953; más tarde sería de las primeras argentinas en obtener el título de planificadora urbana y regional. Sus primeras casas —Don Torcuato en 1949, Furmann en 1951, Rothschild en 1954, Pogré en 1956— resolvieron la lección moderna de las plantas fluidas, las azoteas verdes, los ventanales corridos y el hormigón armado. Desde 1958 construyó casi sin pausa en la costa atlántica con el empresario Domingo Fiorentini: el primer edificio en altura de Miramar y luego los bloques Eiffel, Alsancor y Alsina de Mar del Plata y el Mirador Cabo Corrientes. Al final de su vida se volcó a la accesibilidad y al hábitat gerontológico.',
      it: 'Nata a Galați, in Romania, Débora Iaroslavschi raggiunse il padre in Argentina nel 1936 e fu una delle pochissime donne nella scuola di architettura dell\'Università di Buenos Aires, dove si laureò nel 1953; più tardi fu tra le prime argentine a conseguire il titolo di pianificatrice urbana e regionale. Le sue prime case — Don Torcuato 1949, Furmann 1951, Rothschild 1954, Pogré 1956 — misero a punto la lezione moderna delle piante fluide, dei tetti piani verdi, delle finestre a nastro e del cemento armato. Dal 1958 costruì quasi ininterrottamente sulla costa atlantica con l\'imprenditore Domingo Fiorentini: il primo edificio alto di Miramar, poi i blocchi Eiffel, Alsancor e Alsina a Mar del Plata e il Mirador Cabo Corrientes. In tarda età si dedicò all\'accessibilità e all\'abitare per la terza età.',
    },
    awards: [],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q46133648', title: 'Débora Iaroslavschi (Q46133648)', license: null },
      { kind: 'wikipedia', url: 'https://es.wikipedia.org/wiki/D%C3%A9bora_Iaroslavschi', title: 'Débora Iaroslavschi', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://es.wikipedia.org/wiki/Mirador_Cabo_Corrientes', title: 'Mirador Cabo Corrientes', license: 'CC BY-SA 4.0' },
    ],
  },

  {
    id: 'raquel-lejtreger',
    wikidataId: 'Q42393066',
    name: 'Raquel Lejtreger',
    alternativeNames: [],
    gender: 'woman',
    born: 1965,
    died: null,
    floruit: { start: 2018, end: 2018, override: false },
    movements: 'unaffiliated',
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'civic',
    signatureMaterial: 'concrete',
    portrait: {
      en: 'Raquel Lejtreger trained as an architect at the Universidad de la República in Montevideo and has worked mainly at the intersection of territorial planning, housing policy and disaster risk. She coordinated Uruguay\'s National Housing Plan for 2010–2014, which included a national programme to relocate families living on flood-prone and contaminated land, and from February 2012 she served as vice-minister of housing, territorial planning and the environment, representing Uruguay in international forums on habitat and climate. Her best-known built work is the Espacio Memorial Penal de Libertad on Route 1, won in open competition in 2016 with the architect Javier Olascoaga; both are children of political prisoners held at the prison the memorial commemorates. The project was later selected for the seventh Ibero-American Design Biennial in Madrid.',
      es: 'Raquel Lejtreger se formó como arquitecta en la Universidad de la República de Montevideo y ha trabajado sobre todo en el cruce entre ordenamiento territorial, política de vivienda y gestión del riesgo de desastres. Coordinó el Plan Nacional de Vivienda 2010-2014, que incluyó un programa nacional de relocalización de familias asentadas en terrenos inundables o contaminados, y desde febrero de 2012 fue subsecretaria de Vivienda, Ordenamiento Territorial y Medio Ambiente, con la representación del Uruguay en los foros internacionales de hábitat y clima. Su obra construida más conocida es el Espacio Memorial Penal de Libertad, sobre la Ruta 1, ganado por concurso abierto en 2016 junto al arquitecto Javier Olascoaga; ambos son hijos de presos políticos recluidos en el penal que la obra conmemora. El proyecto fue después seleccionado para la séptima Bienal Iberoamericana de Diseño de Madrid.',
      it: 'Raquel Lejtreger si è formata come architetta all\'Universidad de la República di Montevideo e ha lavorato soprattutto all\'incrocio fra pianificazione territoriale, politiche abitative e gestione del rischio di catastrofi. Ha coordinato il Piano Nazionale per la Casa 2010-2014, che comprendeva un programma nazionale di ricollocazione delle famiglie insediate su terreni alluvionabili o contaminati, e da febbraio 2012 è stata viceministra per la casa, il territorio e l\'ambiente, rappresentando l\'Uruguay nei fori internazionali su habitat e clima. La sua opera costruita più nota è l\'Espacio Memorial Penal de Libertad, sulla Ruta 1, vinto per concorso aperto nel 2016 insieme all\'architetto Javier Olascoaga; entrambi sono figli di prigionieri politici rinchiusi nel carcere che l\'opera commemora. Il progetto è stato poi selezionato per la settima Biennale Iberoamericana del Design di Madrid.',
    },
    awards: [],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q42393066', title: 'Raquel Lejtreger (Q42393066)', license: null },
      { kind: 'wikipedia', url: 'https://es.wikipedia.org/wiki/Espacio_Memorial_Penal_de_Libertad', title: 'Espacio Memorial Penal de Libertad', license: 'CC BY-SA 4.0' },
      { kind: 'institution', url: 'https://www.gub.uy/presidencia/comunicacion/noticias/asumio-raquel-lejtreger-subsecretaria-del-mvotma', title: 'Asumió Raquel Lejtreger en la subsecretaría del MVOTMA — Presidencia de la República (Uruguay)', license: null },
    ],
  },

  {
    id: 'smiljan-radic',
    wikidataId: 'Q12220731',
    name: 'Smiljan Radić',
    alternativeNames: ['Smiljan Radic Clarke', 'Smiljan Radic'],
    gender: 'man',
    born: 1965,
    died: null,
    floruit: { start: 1997, end: 2018, override: false },
    movements: 'unaffiliated',
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'cultural',
    signatureMaterial: 'mixed',
    portrait: {
      en: 'Smiljan Radić was born in Santiago in 1965 to a family with Croatian and British roots, graduated in architecture from the Pontifical Catholic University of Chile in 1989 and then studied history at the Istituto Universitario di Architettura in Venice. He founded his practice in Santiago in 1995 and has kept it deliberately small. His early houses — Casa Chica in the Andes, built with the sculptor Marcela Correa, then Pite House and Copper House 2 — set fragile, precisely made shells against raw boulders and rough ground, a pairing that has recurred ever since. He built the Serpentine Gallery Pavilion in London in 2014 as a translucent fibreglass shell resting on quarry stones, and founded the Fundación de Arquitectura Frágil in 2017. He received the Pritzker Architecture Prize in March 2026.',
      es: 'Smiljan Radić nació en Santiago en 1965 en una familia de raíces croatas y británicas, se tituló de arquitecto en la Pontificia Universidad Católica de Chile en 1989 y estudió después historia en el Istituto Universitario di Architettura de Venecia. Fundó su oficina en Santiago en 1995 y la ha mantenido deliberadamente pequeña. Sus primeras casas —la Casa Chica en la cordillera, construida con la escultora Marcela Correa, y luego la Casa Pite y la Casa de Cobre 2— enfrentan envolventes frágiles y de factura precisa a bolones en bruto y terrenos ásperos, un emparejamiento que no ha dejado de repetirse. En 2014 levantó el pabellón de la Serpentine Gallery de Londres como una cáscara translúcida de fibra de vidrio apoyada sobre piedras de cantera, y en 2017 fundó la Fundación de Arquitectura Frágil. Recibió el Premio Pritzker en marzo de 2026.',
      it: 'Smiljan Radić è nato a Santiago nel 1965 da una famiglia di radici croate e britanniche, si è laureato in architettura alla Pontificia Università Cattolica del Cile nel 1989 e ha poi studiato storia all\'Istituto Universitario di Architettura di Venezia. Ha fondato il proprio studio a Santiago nel 1995 e lo ha tenuto deliberatamente piccolo. Le sue prime case — la Casa Chica sulle Ande, costruita con la scultrice Marcela Correa, poi la Casa Pite e la Casa di Rame 2 — contrappongono involucri fragili e di fattura precisa a massi grezzi e terreni aspri, un accostamento che da allora non ha smesso di tornare. Nel 2014 ha realizzato il padiglione della Serpentine Gallery di Londra come un guscio traslucido in vetroresina poggiato su pietre di cava, e nel 2017 ha fondato la Fundación de Arquitectura Frágil. Ha ricevuto il Premio Pritzker nel marzo del 2026.',
    },
    awards: ['Pritzker Architecture Prize (2026)', 'National Architecture Award of Chile (2026)'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q12220731', title: 'Smiljan Radić (Q12220731)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Smiljan_Radi%C4%87_Clarke', title: 'Smiljan Radić Clarke', license: 'CC BY-SA 4.0' },
    ],
  },

  {
    id: 'gabriela-medrano',
    wikidataId: 'Q133448370',
    name: 'Gabriela Medrano',
    alternativeNames: ['Gabriela Medrano Viteri'],
    gender: 'woman',
    born: 1982,
    died: null,
    floruit: { start: 2018, end: 2018, override: false },
    movements: 'unaffiliated',
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'cultural',
    signatureMaterial: 'mixed',
    portrait: {
      en: 'Gabriela Medrano was born in Quito, Ecuador, in 1982 and later took Chilean citizenship. She trained as an architect at the Universidad Andrés Bello in Santiago, graduating in 2008, and began working with Smiljan Radić that same year. In 2011 she won, with Radić and Eduardo Castillo, the open competition for the Biobío Regional Theatre in Concepción, completed in 2018 and awarded the grand prize at the 2022 Pan-American Architecture Biennial in Quito; the Design Museum in London shortlisted it for its Beazley Designs of the Year in 2018. In 2014 she and Radić won a second competition, with Ricardo Serpell, for a telecommunications tower on Santiago\'s Cerro San Cristóbal, which was never built. Since 2013 she has taught at the Pontifical Catholic University of Chile, the University of Chile and the University of Talca, and since 2018 has made temporary civic interventions in public space.',
      es: 'Gabriela Medrano nació en Quito, Ecuador, en 1982 y más tarde se nacionalizó chilena. Se tituló de arquitecta en la Universidad Andrés Bello de Santiago en 2008 y ese mismo año empezó a trabajar con Smiljan Radić. En 2011 ganó, junto a Radić y Eduardo Castillo, el concurso abierto del Teatro Regional del Biobío en Concepción, terminado en 2018 y premiado con el Gran Premio de la Bienal Panamericana de Arquitectura de Quito de 2022; el Design Museum la preseleccionó para sus Beazley Designs of the Year de 2018. En 2014 ella y Radić ganaron, con Ricardo Serpell, un segundo concurso para una torre de telecomunicaciones en el Cerro San Cristóbal, que nunca se construyó. Desde 2013 enseña en la Pontificia Universidad Católica de Chile, la Universidad de Chile y la Universidad de Talca, y desde 2018 realiza intervenciones cívicas temporales en el espacio público.',
      it: 'Gabriela Medrano nacque a Quito, in Ecuador, nel 1982, e in seguito ottenne la cittadinanza cilena. Si formò come architetta all\'Universidad Andrés Bello di Santiago, dove si laureò nel 2008, e quello stesso anno iniziò a lavorare con Smiljan Radić. Nel 2011 vinse, insieme a Radić e Eduardo Castillo, il concorso aperto per il Teatro Regionale del Biobío a Concepción, completato nel 2018 e premiato con il Gran Premio della Biennale Panamericana di Architettura di Quito del 2022; il Design Museum di Londra lo selezionò per i suoi Beazley Designs of the Year del 2018. Nel 2014 lei e Radić vinsero, con Ricardo Serpell, un secondo concorso per una torre delle telecomunicazioni sul Cerro San Cristóbal di Santiago, mai realizzata. Dal 2013 insegna alla Pontificia Università Cattolica del Cile, all\'Università del Cile e all\'Università di Talca, e dal 2018 realizza interventi civici temporanei nello spazio pubblico.',
    },
    awards: ['Beazley Designs of the Year shortlist, Design Museum London (2018)', 'Grand Prize, Pan-American Architecture Biennial, Quito (2022)'],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q133448370', title: 'Gabriela Medrano (Q133448370)', license: null },
      { kind: 'wikipedia', url: 'https://es.wikipedia.org/wiki/Gabriela_Medrano_Viteri', title: 'Gabriela Medrano Viteri', license: 'CC BY-SA 4.0' },
      { kind: 'publication', url: 'https://www.designboom.com/architecture/smiljan-radic-eduardo-castillo-gabriela-medrano-teatro-biobio-concepcion-chile-03-14-2019/', title: 'Teatro Biobío: trio of architects design landmark theater for the city of Concepción — designboom', license: null },
    ],
  },
];
