import type { Architect } from '@/types/architect';

// Wave 5, agent 9c — Northern America (United States and Canada).
//
// Every entry below was checked against its live Wikidata entity page on
// 2026-08-26. `workRegions` and `workCentroid` are deliberately left empty:
// buildCuratedPool derives both from the architect's buildings and discards
// whatever is written here.
//
// Cross-file note for the controller: `moshe-safdie` is defined here because
// Habitat 67 (Montréal) is his first appearance in the pool, but his practice
// also spans Israel and Singapore. If the westasia or asia curator needs him,
// they should reference `moshe-safdie` rather than redefining him.
export const AMERICAS_ARCHITECTS: Architect[] = [
{
    id: 'thomas-jefferson',
    wikidataId: 'Q11812',
    name: 'Thomas Jefferson',
    alternativeNames: ['Thomas Jefferson (architect)'],
    gender: 'man',
    born: 1743,
    died: 1826,
    floruit: { start: 1770, end: 1826, override: false },
    movements: [
      { id: 'palladianism', primary: true },
      { id: 'neoclassicism', primary: false },
    ],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'domestic',
    signatureMaterial: 'brick',
    portrait: {
      en: 'Jefferson was an amateur in the strict sense: he never trained as an architect, never charged a fee, and learned the discipline from books — above all from Giacomo Leoni\'s English edition of Palladio, which he called his bible. What he built from that reading was not imitation. At Monticello he spent forty years rebuilding his own house until its Palladian parts were arranged around an American plan of his own devising, with dumbwaiters, a bed alcove between two rooms, and service wings dug into the hillside. The Virginia State Capitol, drawn in Paris with Charles-Louis Clérisseau, transplanted the Maison Carrée at Nîmes into a working legislature and set the template for American public building. His last work, the University of Virginia, arranged ten pavilions and a library rotunda around a lawn as a curriculum made visible.',
      es: 'Jefferson fue un aficionado en sentido estricto: nunca se formó como arquitecto, nunca cobró honorarios y aprendió el oficio en los libros, sobre todo en la edición inglesa de Palladio de Giacomo Leoni, que llamaba su biblia. Lo que construyó a partir de esa lectura no fue imitación. En Monticello dedicó cuarenta años a rehacer su propia casa hasta que las piezas palladianas quedaron ordenadas según una planta americana de su invención, con montacargas, una alcoba encajada entre dos habitaciones y alas de servicio excavadas en la ladera. El Capitolio de Virginia, dibujado en París con Charles-Louis Clérisseau, trasplantó la Maison Carrée de Nimes a una legislatura en funcionamiento y fijó el modelo del edificio público estadounidense. Su última obra, la Universidad de Virginia, dispuso diez pabellones y una rotonda-biblioteca en torno a un césped: un plan de estudios hecho arquitectura.',
      it: 'Jefferson fu un dilettante in senso stretto: non si formò mai come architetto, non chiese mai un compenso e imparò il mestiere sui libri, soprattutto sull\'edizione inglese di Palladio curata da Giacomo Leoni, che chiamava la sua bibbia. Ciò che costruì a partire da quella lettura non fu imitazione. A Monticello impiegò quarant\'anni a rifare la propria casa finché le parti palladiane non risultarono ordinate secondo una pianta americana di sua invenzione, con montavivande, un\'alcova incassata fra due stanze e ali di servizio scavate nel pendio. Il Campidoglio della Virginia, disegnato a Parigi con Charles-Louis Clérisseau, trapiantò la Maison Carrée di Nîmes in un\'assemblea legislativa in funzione e fissò il modello dell\'edificio pubblico americano. La sua ultima opera, l\'Università della Virginia, dispose dieci padiglioni e una rotonda-biblioteca attorno a un prato: un piano di studi reso architettura.',
    },
    awards: [],
    tier: 'canon',
    context: {
      body: {
        en: 'Jefferson enslaved more than 620 people over the course of his adult life. He wrote the sentence about all men being created equal, argued in Notes on the State of Virginia for the innate inferiority of Black people, and formally freed two people during his lifetime and five in his will — all of them members of the Hemings family. His architectural practice was inseparable from that fact: the brick, joinery and nails for his buildings were produced on his own plantations by enslaved workers whose names the Thomas Jefferson Foundation has since recovered and published. In 2000 the Foundation, which owns Monticello, concluded that Jefferson was the father of Sally Hemings\'s children.',
        es: 'Jefferson esclavizó a más de 620 personas a lo largo de su vida adulta. Escribió la frase sobre la igualdad de todos los hombres, defendió en las Notas sobre el estado de Virginia la inferioridad innata de las personas negras y solo liberó formalmente a dos personas en vida y a cinco en su testamento, todas ellas de la familia Hemings. Su práctica arquitectónica es inseparable de ese hecho: el ladrillo, la carpintería y los clavos de sus edificios se produjeron en sus propias plantaciones con trabajo esclavizado, y la Thomas Jefferson Foundation ha recuperado y publicado desde entonces los nombres de quienes lo realizaron. En 2000 la fundación, propietaria de Monticello, concluyó que Jefferson fue el padre de los hijos de Sally Hemings.',
        it: 'Jefferson tenne in schiavitù più di 620 persone nel corso della sua vita adulta. Scrisse la frase sull\'uguaglianza di tutti gli uomini, sostenne nelle Note sullo Stato della Virginia l\'inferiorità innata dei neri e liberò formalmente due persone in vita e cinque per testamento, tutte della famiglia Hemings. La sua pratica architettonica è inseparabile da questo dato: i mattoni, i serramenti e i chiodi dei suoi edifici furono prodotti nelle sue piantagioni da lavoratori schiavizzati, i cui nomi la Thomas Jefferson Foundation ha in seguito ricostruito e pubblicato. Nel 2000 la fondazione, proprietaria di Monticello, concluse che Jefferson fu il padre dei figli di Sally Hemings.',
      },
      sources: [
        { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Thomas_Jefferson_and_slavery', title: 'Thomas Jefferson and slavery', license: 'CC BY-SA 4.0' },
        { kind: 'institution', url: 'https://www.monticello.org/thomas-jefferson/jefferson-slavery/', title: 'Thomas Jefferson Foundation — Jefferson and Slavery', license: null },
      ],
    },
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q11812', title: 'Thomas Jefferson (Q11812)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Thomas_Jefferson', title: 'Thomas Jefferson', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'louis-sullivan',
    wikidataId: 'Q243240',
    name: 'Louis Sullivan',
    alternativeNames: ['Louis Henry Sullivan', 'Louis H. Sullivan'],
    gender: 'man',
    born: 1856,
    died: 1924,
    floruit: { start: 1886, end: 1922, override: false },
    movements: 'unaffiliated',
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'commercial',
    signatureMaterial: 'brick',
    portrait: {
      en: 'Sullivan spent a year at MIT and a few months in the atelier of Émile Vaudremer in Paris, then went to Chicago and, in partnership with the engineer Dankmar Adler from 1883, worked out what a steel-framed office building should look like. His answer, set down in "The Tall Office Building Artistically Considered" (1896), was that it must be tall — "every inch of it tall" — and that its form should follow its function. The Wainwright and Guaranty buildings put that argument into brick and terracotta. He is conventionally filed under the Chicago School, but the label sits awkwardly: his ornament, a dense foliate geometry he drew himself, has no equivalent among his contemporaries. After the partnership ended in 1895 the commissions dried up, and his last two decades produced only the small midwestern banks that are now among his most admired works.',
      es: 'Sullivan pasó un año en el MIT y unos meses en el taller de Émile Vaudremer en París; luego se instaló en Chicago y, asociado desde 1883 con el ingeniero Dankmar Adler, resolvió qué aspecto debía tener un edificio de oficinas con estructura de acero. Su respuesta, formulada en «The Tall Office Building Artistically Considered» (1896), fue que debía ser alto —«alto en cada pulgada»— y que su forma debía seguir a su función. Los edificios Wainwright y Guaranty llevaron ese argumento al ladrillo y la terracota. Se le clasifica por costumbre en la Escuela de Chicago, pero la etiqueta le queda estrecha: su ornamento, una geometría vegetal densa que dibujaba él mismo, no tiene equivalente entre sus contemporáneos. Disuelta la sociedad en 1895, los encargos se agotaron, y sus dos últimas décadas solo dieron los pequeños bancos del Medio Oeste que hoy figuran entre sus obras más admiradas.',
      it: 'Sullivan trascorse un anno al MIT e pochi mesi nell\'atelier di Émile Vaudremer a Parigi, poi si trasferì a Chicago e, in società dal 1883 con l\'ingegnere Dankmar Adler, definì quale aspetto dovesse avere un edificio per uffici con struttura in acciaio. La sua risposta, esposta in «The Tall Office Building Artistically Considered» (1896), fu che doveva essere alto — «alto in ogni pollice» — e che la forma doveva seguire la funzione. Il Wainwright e il Guaranty tradussero quell\'argomento in mattoni e terracotta. Per convenzione lo si colloca nella Scuola di Chicago, ma l\'etichetta gli sta stretta: il suo ornato, una fitta geometria vegetale che disegnava di propria mano, non ha equivalenti fra i contemporanei. Sciolta la società nel 1895 le commissioni si esaurirono, e i suoi ultimi vent\'anni produssero soltanto le piccole banche del Midwest oggi fra le sue opere più ammirate.',
    },
    awards: ['AIA Gold Medal (1944, awarded posthumously)'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q243240', title: 'Louis Sullivan (Q243240)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Louis_Sullivan', title: 'Louis Sullivan', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'mary-colter',
    wikidataId: 'Q523888',
    name: 'Mary Colter',
    alternativeNames: ['Mary Elizabeth Jane Colter', 'Mary E. J. Colter'],
    gender: 'woman',
    born: 1869,
    died: 1958,
    floruit: { start: 1905, end: 1948, override: false },
    movements: 'unaffiliated',
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'commercial',
    signatureMaterial: 'stone',
    portrait: {
      en: 'Colter studied at the California School of Design in San Francisco and apprenticed in an architect\'s office there, then taught drawing in St Paul for fifteen years before the Fred Harvey Company took her on. From 1910 until she retired in 1948 she was its chief architect and decorator, designing the hotels, lodges and rest houses that the company ran along the Atchison, Topeka and Santa Fe Railway. She worked by research rather than by style: months of fieldwork among Ancestral Puebloan ruins, Hopi villages and Spanish mission churches preceded each design, and she specified local stone and had masons lay it to match the strata it came from. Her buildings were invented histories, complete with fictional biographies for their imagined builders, and they set the pattern for what became National Park Service rustic architecture. Four of her Grand Canyon buildings were made a National Historic Landmark in 1987.',
      es: 'Colter estudió en la California School of Design de San Francisco y se formó en un estudio de la ciudad; después enseñó dibujo en Saint Paul durante quince años, hasta que la Fred Harvey Company la contrató. Desde 1910 y hasta su retiro en 1948 fue su arquitecta y decoradora jefe, y proyectó los hoteles, albergues y casas de descanso de la empresa a lo largo del ferrocarril de Atchison, Topeka y Santa Fe. Trabajaba desde la investigación, no desde el estilo: cada proyecto venía precedido de meses de campo entre ruinas puebloanas, aldeas hopi e iglesias de misión, y prescribía piedra local que hacía asentar imitando los estratos de los que procedía. Sus edificios eran historias inventadas, con biografías ficticias para sus supuestos constructores, y fijaron el modelo del rústico del Servicio de Parques Nacionales. Cuatro de sus obras del Gran Cañón son National Historic Landmark desde 1987.',
      it: 'Colter studiò alla California School of Design di San Francisco e fece pratica in uno studio di architettura della città; insegnò poi disegno a Saint Paul per quindici anni, finché la Fred Harvey Company non la assunse. Dal 1910 fino al ritiro nel 1948 ne fu architetta e decoratrice capo, progettando gli alberghi, i rifugi e le case di sosta che l\'azienda gestiva lungo la ferrovia Atchison, Topeka and Santa Fe. Lavorava per ricerca e non per stile: ogni progetto era preceduto da mesi di sopralluoghi fra rovine ancestrali puebloane, villaggi hopi e chiese delle missioni spagnole, e prescriveva pietra locale che faceva posare imitando gli strati di provenienza. I suoi edifici erano storie inventate, complete di biografie fittizie per i costruttori immaginari, e fissarono il modello del rustico del National Park Service. Quattro sue opere al Grand Canyon sono National Historic Landmark dal 1987.',
    },
    awards: ['Arizona Women\'s Hall of Fame (1986)', 'National Cowgirl Museum and Hall of Fame (2009)'],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q523888', title: 'Mary Colter (Q523888)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Mary_Colter', title: 'Mary Colter', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'julia-morgan',
    wikidataId: 'Q601820',
    name: 'Julia Morgan',
    alternativeNames: ['Julia Hunt Morgan'],
    gender: 'woman',
    born: 1872,
    died: 1957,
    floruit: { start: 1904, end: 1947, override: false },
    movements: [
      { id: 'beaux-arts', primary: true },
      { id: 'mediterranean-vernacular', primary: false },
    ],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'civic',
    signatureMaterial: 'concrete',
    portrait: {
      en: 'Morgan took a degree in civil engineering at Berkeley, then became the first woman admitted to the architecture section of the École des Beaux-Arts in Paris and the first to leave it with a certificate, in 1902. Two years later she was the first woman licensed to practise architecture in California. Her engineering training decided her material: she built in reinforced concrete when almost nobody in California did, and when her unreinforced-masonry contemporaries lost their buildings in 1906 hers stood. Over roughly forty-five years she produced some seven hundred works — YWCA buildings, women\'s clubs, churches, schools, houses, and the long campaign at San Simeon for William Randolph Hearst. She kept no publicity office, gave no interviews, and destroyed her drawings on retirement. The AIA gave her its Gold Medal in 2014, the first woman to receive it, fifty-seven years after her death.',
      es: 'Morgan se licenció en ingeniería civil en Berkeley y fue la primera mujer admitida en la sección de arquitectura de la École des Beaux-Arts de París y la primera en salir de ella con certificado, en 1902. Dos años más tarde era la primera mujer con licencia para ejercer en California. Su formación de ingeniera decidió su material: construyó en hormigón armado cuando casi nadie lo hacía, y en 1906, cuando la fábrica sin armar de sus contemporáneos cayó, los suyos siguieron en pie. En unos cuarenta y cinco años firmó cerca de setecientas obras: sedes de la YWCA, clubes de mujeres, iglesias, escuelas, viviendas y la larga campaña de San Simeón para Hearst. No tuvo gabinete de prensa, no dio entrevistas y destruyó sus dibujos al retirarse. El AIA le dio su Medalla de Oro en 2014, primera mujer en recibirla, cincuenta y siete años después de morir.',
      it: 'Morgan si laureò in ingegneria civile a Berkeley e fu poi la prima donna ammessa alla sezione di architettura dell\'École des Beaux-Arts di Parigi e la prima a uscirne con un certificato, nel 1902. Due anni dopo era la prima donna abilitata all\'esercizio della professione in California. La formazione da ingegnere ne decise il materiale: costruì in cemento armato quando in California non lo faceva quasi nessuno, e quando nel 1906 i contemporanei persero gli edifici in muratura non armata i suoi rimasero in piedi. In circa quarantacinque anni firmò quasi settecento opere — sedi della YWCA, circoli femminili, chiese, scuole, case e la lunga campagna di San Simeon per William Randolph Hearst. Non ebbe ufficio stampa, non concesse interviste e distrusse i propri disegni al momento del ritiro. L\'AIA le assegnò la Medaglia d\'Oro nel 2014, prima donna a riceverla, cinquantasette anni dopo la morte.',
    },
    awards: ['AIA Gold Medal (2014, awarded posthumously)', 'California Hall of Fame'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q601820', title: 'Julia Morgan (Q601820)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Julia_Morgan', title: 'Julia Morgan', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'frank-lloyd-wright',
    wikidataId: 'Q5604',
    name: 'Frank Lloyd Wright',
    alternativeNames: ['Frank Lincoln Wright'],
    gender: 'man',
    born: 1867,
    died: 1959,
    floruit: { start: 1893, end: 1962, override: false },
    movements: [
      { id: 'organic-architecture', primary: true },
    ],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'domestic',
    signatureMaterial: 'concrete',
    portrait: {
      en: 'Wright left Louis Sullivan\'s office in 1893 and spent the next fifteen years dismantling the Victorian house: the Prairie plan pushed the rooms out from a central hearth, dropped the ceilings, ran the windows in bands and let the roof float. He called the result organic architecture, meaning that plan, structure, site and ornament should be generated together from one idea rather than assembled from parts. A career of about seventy years produced Unity Temple, one of the first buildings in the United States cast entirely in exposed concrete; the Imperial Hotel in Tokyo; Fallingwater, cantilevered over its waterfall; the Johnson Wax administration building with its tapered mushroom columns; some sixty low-cost Usonian houses; and finally the Guggenheim, a single ascending ramp. Eight of his buildings were inscribed together as a UNESCO World Heritage Site in 2019.',
      es: 'Wright dejó el estudio de Louis Sullivan en 1893 y pasó los quince años siguientes desarmando la casa victoriana: la planta de la pradera separó las estancias a partir de un hogar central, bajó los techos, corrió las ventanas en fajas y dejó flotar la cubierta. Llamó al resultado arquitectura orgánica, entendiendo que planta, estructura, lugar y ornamento debían generarse juntos desde una sola idea en lugar de ensamblarse por piezas. Unos setenta años de carrera dieron el Unity Temple, uno de los primeros edificios estadounidenses fundidos íntegramente en hormigón visto; el Hotel Imperial de Tokio; la Casa de la Cascada, en voladizo sobre el salto de agua; el edificio administrativo Johnson Wax con sus columnas-hongo; unas sesenta casas usonianas de bajo coste; y por último el Guggenheim, una única rampa ascendente. Ocho de sus obras fueron inscritas juntas como Patrimonio Mundial de la UNESCO en 2019.',
      it: 'Wright lasciò lo studio di Louis Sullivan nel 1893 e passò i quindici anni successivi a smontare la casa vittoriana: la pianta della prateria fece irradiare gli ambienti da un focolare centrale, abbassò i soffitti, dispose le finestre in nastri e lasciò galleggiare la copertura. Chiamò il risultato architettura organica, intendendo che pianta, struttura, luogo e ornato dovessero nascere insieme da un\'unica idea anziché essere assemblati per parti. Una carriera di circa settant\'anni produsse l\'Unity Temple, uno dei primi edifici statunitensi gettati interamente in calcestruzzo a vista; l\'Imperial Hotel di Tokyo; la Casa sulla cascata, a sbalzo sul salto d\'acqua; l\'amministrazione Johnson Wax con le colonne a fungo; una sessantina di case usoniane a basso costo; e infine il Guggenheim, un\'unica rampa ascendente. Otto sue opere sono state iscritte insieme nel Patrimonio mondiale UNESCO nel 2019.',
    },
    awards: ['RIBA Royal Gold Medal (1941)', 'AIA Gold Medal (1949)'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q5604', title: 'Frank Lloyd Wright (Q5604)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Frank_Lloyd_Wright', title: 'Frank Lloyd Wright', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'louis-kahn',
    wikidataId: 'Q210134',
    name: 'Louis Kahn',
    alternativeNames: ['Louis Isadore Kahn', 'Louis I. Kahn', 'Itze-Leib Schmuilowsky'],
    gender: 'man',
    born: 1901,
    died: 1974,
    floruit: { start: 1951, end: 1983, override: false },
    movements: [
      { id: 'brutalism', primary: true },
    ],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'educational',
    signatureMaterial: 'concrete',
    portrait: {
      en: 'Kahn was born on Saaremaa, brought to Philadelphia at four, trained in the Beaux-Arts tradition at the University of Pennsylvania, and produced almost nothing memorable until he was past fifty. A year at the American Academy in Rome in 1950–51 changed that: the ruins taught him that a building could be made of massive, singular volumes admitting daylight through openings cut in thick wall. From the Yale Art Gallery onward he built a small, dense body of work — the Salk Institute, the Kimbell with its cycloid vaults, the library at Phillips Exeter, the Indian Institute of Management at Ahmedabad, and the National Assembly at Dhaka, finished eight years after his death. He separated what he called served and servant spaces, poured concrete and laid brick as though they were being asked what they wanted to be, and left almost every surface as it came out of the formwork.',
      es: 'Kahn nació en Saaremaa, llegó a Filadelfia con cuatro años, se formó en la tradición Beaux-Arts en la Universidad de Pensilvania y no produjo casi nada memorable hasta pasados los cincuenta. Un año en la Academia Americana de Roma, en 1950-51, lo cambió todo: las ruinas le enseñaron que un edificio podía hacerse de volúmenes macizos y únicos que admiten la luz por huecos abiertos en muro grueso. Desde la Galería de Arte de Yale levantó una obra breve y densa: el Instituto Salk, el Kimbell con sus bóvedas cicloidales, la biblioteca de Phillips Exeter, el Instituto Indio de Gestión de Ahmedabad y la Asamblea Nacional de Daca, terminada ocho años después de su muerte. Distinguió lo que llamaba espacios servidos y servidores, vertió el hormigón y asentó el ladrillo como si les preguntara qué querían ser, y dejó casi todas las superficies tal como salían del encofrado.',
      it: 'Kahn nacque a Saaremaa, arrivò a Filadelfia a quattro anni, si formò nella tradizione Beaux-Arts alla University of Pennsylvania e non produsse quasi nulla di memorabile fino a oltre i cinquant\'anni. Un anno all\'Accademia Americana di Roma, nel 1950-51, cambiò tutto: le rovine gli insegnarono che un edificio poteva essere fatto di volumi massicci e singolari, illuminati da aperture tagliate nel muro spesso. Dalla Yale Art Gallery in poi costruì un corpus breve e denso: il Salk Institute, il Kimbell con le sue volte cicloidali, la biblioteca di Phillips Exeter, l\'Indian Institute of Management di Ahmedabad e l\'Assemblea Nazionale di Dacca, ultimata otto anni dopo la sua morte. Distinse quelli che chiamava spazi serviti e spazi serventi, gettò il calcestruzzo e posò il mattone come se chiedesse loro che cosa volessero essere, e lasciò quasi ogni superficie come usciva dal cassero.',
    },
    awards: ['AIA Gold Medal (1971)', 'RIBA Royal Gold Medal (1972)'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q210134', title: 'Louis Kahn (Q210134)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Louis_Kahn', title: 'Louis Kahn', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'moshe-safdie',
    wikidataId: 'Q220944',
    name: 'Moshe Safdie',
    alternativeNames: ['משה ספדיה'],
    gender: 'man',
    born: 1938,
    died: null,
    floruit: { start: 1967, end: 2025, override: false },
    movements: [
      { id: 'brutalism', primary: true },
    ],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'housing',
    signatureMaterial: 'concrete',
    portrait: {
      en: 'Safdie was born in Haifa, moved to Montréal at fifteen, and finished his architecture degree at McGill in 1961 with a thesis on a three-dimensional modular housing system. Four years later, at twenty-eight, he was building it: Habitat 67 remains the only case of a student thesis realised at full scale as a national exhibition pavilion. After a year in Louis Kahn\'s office he opened his own practice and moved it to Jerusalem, where he worked on the Old City restoration, Mamilla and Yad Vashem. His later work is large, public and geometrically ordered — the National Gallery of Canada in Ottawa, Marina Bay Sands and Jewel Changi in Singapore, the Crystal Bridges museum in Arkansas. The prefabricated repetition of Habitat has never quite been repeated: the cost per unit that the Expo 67 budget could absorb has kept the system out of ordinary housing.',
      es: 'Safdie nació en Haifa, se trasladó a Montreal a los quince años y terminó arquitectura en McGill en 1961 con una tesis sobre un sistema modular tridimensional de vivienda. Cuatro años más tarde, con veintiocho, la estaba construyendo: Habitat 67 sigue siendo el único caso de tesis estudiantil realizada a escala real como pabellón de una exposición nacional. Tras un año con Louis Kahn abrió su propio estudio y lo trasladó a Jerusalén, donde trabajó en la restauración de la Ciudad Vieja, en Mamilla y en Yad Vashem. Su obra posterior es grande, pública y de geometría ordenada: la Galería Nacional de Canadá en Ottawa, Marina Bay Sands y Jewel Changi en Singapur, el museo Crystal Bridges en Arkansas. La repetición prefabricada de Habitat no ha vuelto a darse: el coste por unidad que absorbió el presupuesto de la Expo 67 dejó el sistema fuera de la vivienda corriente.',
      it: 'Safdie nacque a Haifa, si trasferì a Montréal a quindici anni e concluse gli studi di architettura alla McGill nel 1961 con una tesi su un sistema abitativo modulare tridimensionale. Quattro anni dopo, a ventotto, lo stava costruendo: Habitat 67 resta l\'unico caso di tesi studentesca realizzata a grandezza naturale come padiglione di un\'esposizione nazionale. Dopo un anno nello studio di Louis Kahn aprì il proprio e lo trasferì a Gerusalemme, dove lavorò al restauro della Città Vecchia, a Mamilla e allo Yad Vashem. L\'opera successiva è grande, pubblica e di geometria ordinata: la Galleria nazionale del Canada a Ottawa, Marina Bay Sands e Jewel Changi a Singapore, il museo Crystal Bridges in Arkansas. La ripetizione prefabbricata di Habitat non si è più data: il costo per unità che il bilancio dell\'Expo 67 poté assorbire ha tenuto il sistema fuori dall\'edilizia ordinaria.',
    },
    awards: ['Companion of the Order of Canada', 'AIA Gold Medal (2015)', 'Wolf Prize in Architecture (2015)'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q220944', title: 'Moshe Safdie (Q220944)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Moshe_Safdie', title: 'Moshe Safdie', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'eero-saarinen',
    wikidataId: 'Q167073',
    name: 'Eero Saarinen',
    alternativeNames: [],
    gender: 'man',
    born: 1910,
    died: 1961,
    floruit: { start: 1948, end: 1965, override: false },
    movements: [
      { id: 'international-style', primary: true },
    ],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'infrastructure',
    signatureMaterial: 'concrete',
    portrait: {
      en: 'Saarinen was born outside Helsinki, brought to Michigan at thirteen when his father Eliel took over Cranbrook, and studied sculpture in Paris before architecture at Yale. He worked in his father\'s office until Eliel\'s death in 1950, by which time he had won the St Louis arch competition with a catenary curve. What followed was deliberately inconsistent: he refused a house style and gave each commission the form he thought its problem demanded. The General Motors Technical Center is a machine-finished steel-and-glass campus; the MIT chapel is a windowless brick cylinder; the TWA terminal and Dulles are thin concrete shells; the CBS Building is a granite-clad tower. Critics of the period read the range as opportunism; it is now generally read as a refusal to let a signature stand in for an argument. He died at fifty-one, and his office completed nine buildings after him.',
      es: 'Saarinen nació cerca de Helsinki, llegó a Michigan a los trece años cuando su padre Eliel se hizo cargo de Cranbrook y estudió escultura en París antes que arquitectura en Yale. Trabajó en el estudio paterno hasta la muerte de Eliel en 1950; ya había ganado el concurso del arco de San Luis con una catenaria. Lo que vino después fue deliberadamente inconsistente: rechazó un estilo propio y dio a cada encargo la forma que su problema parecía exigir. El Centro Técnico de General Motors es un campus de acero y vidrio industrial; la capilla del MIT, un cilindro ciego de ladrillo; la TWA y Dulles, láminas delgadas de hormigón; la CBS, una torre de granito. La crítica de la época leyó esa variedad como oportunismo; hoy se lee como negativa a que la firma sustituya al argumento. Murió a los cincuenta y uno; su estudio terminó nueve obras después.',
      it: 'Saarinen nacque presso Helsinki, arrivò in Michigan a tredici anni quando il padre Eliel prese la direzione di Cranbrook e studiò scultura a Parigi prima di architettura a Yale. Lavorò nello studio paterno fino alla morte di Eliel nel 1950; aveva già vinto il concorso per l\'arco di Saint Louis con una catenaria. Ciò che seguì fu volutamente incoerente: rifiutò uno stile di studio e diede a ogni incarico la forma che il problema sembrava esigere. Il General Motors Technical Center è un campus di acciaio e vetro a finitura industriale; la cappella del MIT un cilindro cieco di mattoni; il TWA e Dulles sottili gusci di calcestruzzo; il CBS Building una torre di granito. La critica lesse quella varietà come opportunismo; oggi la si legge come rifiuto di far valere una firma al posto di un argomento. Morì a cinquantun anni; lo studio completò nove edifici dopo di lui.',
    },
    awards: ['AIA Gold Medal (1962, awarded posthumously)'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q167073', title: 'Eero Saarinen (Q167073)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Eero_Saarinen', title: 'Eero Saarinen', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'jeanne-gang',
    wikidataId: 'Q444257',
    name: 'Jeanne Gang',
    alternativeNames: [],
    gender: 'woman',
    born: 1964,
    died: null,
    floruit: { start: 2004, end: 2025, override: false },
    movements: [
      { id: 'sustainable-architecture', primary: true },
    ],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'tower',
    signatureMaterial: 'concrete',
    portrait: {
      en: 'Gang grew up in Belvidere, Illinois, took an architecture degree at the University of Illinois, spent a year in Rem Koolhaas\'s office in Rotterdam, finished a master\'s at Harvard in 1993 and started Studio Gang in Chicago in 1997. Her practice treats a building as an ecological and social instrument before a formal one: the balcony slabs at Aqua were shaped for views, shade, downdraught and bird strikes at once; the Arcus Center in Kalamazoo is built of cordwood masonry laid by local crews; the Gilder Center in New York was shot in place as sprayed concrete over rebar, without formwork. She has argued consistently for reuse over demolition and for what she calls actionable idealism — measuring a design by what it changes rather than by how it looks. She was a MacArthur Fellow in 2011 and has taught at Harvard since the same year.',
      es: 'Gang creció en Belvidere, Illinois, se licenció en arquitectura por la Universidad de Illinois, pasó un año en el estudio de Rem Koolhaas en Róterdam, terminó un máster en Harvard en 1993 y fundó Studio Gang en Chicago en 1997. Su práctica entiende el edificio como instrumento ecológico y social antes que formal: los forjados-balcón de Aqua se moldearon a la vez por las vistas, la sombra, las corrientes descendentes y las colisiones de aves; el Arcus Center de Kalamazoo está levantado con mampostería de leña colocada por cuadrillas locales; el Gilder Center de Nueva York se proyectó in situ como hormigón gunitado sobre armadura, sin encofrado. Ha defendido con constancia la reutilización frente al derribo y lo que llama idealismo accionable: medir un proyecto por lo que cambia y no por su aspecto. Fue becaria MacArthur en 2011 y enseña en Harvard desde ese mismo año.',
      it: 'Gang è cresciuta a Belvidere, in Illinois, si è laureata in architettura all\'Università dell\'Illinois, ha trascorso un anno nello studio di Rem Koolhaas a Rotterdam, ha concluso un master a Harvard nel 1993 e ha fondato Studio Gang a Chicago nel 1997. La sua pratica considera l\'edificio anzitutto uno strumento ecologico e sociale, e solo poi formale: le solette-balcone di Aqua sono state modellate insieme per le viste, l\'ombra, le correnti discendenti e l\'impatto degli uccelli; l\'Arcus Center di Kalamazoo è costruito in muratura di legna posata da maestranze locali; il Gilder Center di New York è stato realizzato in opera come calcestruzzo spruzzato su armatura, senza casseri. Sostiene con coerenza il riuso contro la demolizione e quello che chiama idealismo attuabile: misurare un progetto da ciò che cambia, non da come appare. È stata MacArthur Fellow nel 2011 e insegna a Harvard dallo stesso anno.',
    },
    awards: ['MacArthur Fellowship (2011)', 'National Design Award in Architecture (2013)'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q444257', title: 'Jeanne Gang (Q444257)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Jeanne_Gang', title: 'Jeanne Gang', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'peter-harrison',
    wikidataId: 'Q1178933',
    name: 'Peter Harrison',
    alternativeNames: ['Peter Harrison (architect)'],
    gender: 'man',
    born: 1716,
    died: 1775,
    floruit: { start: 1748, end: 1772, override: false },
    movements: [
      { id: 'palladianism', primary: true },
    ],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'sacral',
    signatureMaterial: 'timber',
    portrait: {
      en: 'Harrison went to sea as a young man, commanding merchant ships out of Newport, and picked up architecture the way an educated 18th-century amateur could: from pattern books by Palladio, Gibbs and Kent, assembled into a library he kept adding to for the rest of his life. He never trained formally and never called himself an architect in any document that survives; contemporaries described him as a gentleman who designed as a courtesy to his city. Between 1748 and 1763 he gave Newport four buildings that still stand — the Redwood Library, King\'s Chapel in Boston, Touro Synagogue and the Brick Market — each copied close to an English or European precedent but built in wood and brick rather than stone. He held Loyalist sympathies during the Revolution; after his death in New Haven in 1775, a mob burned his house, his library and every drawing he had made.',
      es: 'Harrison se echó al mar de joven, mandando barcos mercantes desde Newport, y aprendió arquitectura como podía hacerlo un aficionado culto del siglo XVIII: a partir de manuales de Palladio, Gibbs y Kent, reunidos en una biblioteca que no dejó de ampliar el resto de su vida. Nunca se formó de manera reglada ni se llamó arquitecto en documento alguno conservado; sus contemporáneos lo describían como un caballero que proyectaba por cortesía a su ciudad. Entre 1748 y 1763 dio a Newport cuatro edificios que aún siguen en pie —la Redwood Library, la King\'s Chapel de Boston, la sinagoga Touro y el Brick Market—, cada uno calcado de un precedente inglés o europeo pero construido en madera y ladrillo, no en piedra. Mantuvo simpatías lealistas durante la Revolución; tras su muerte en 1775, una turba quemó su casa, su biblioteca y todos sus dibujos.',
      it: 'Harrison si imbarcò da giovane, comandando navi mercantili da Newport, e imparò l\'architettura come poteva farlo un colto dilettante del Settecento: da manuali di Palladio, Gibbs e Kent, raccolti in una biblioteca che continuò ad ampliare per tutta la vita. Non si formò mai in modo regolare né si definì mai architetto in alcun documento giunto fino a noi; i contemporanei lo descrivevano come un gentiluomo che progettava per cortesia verso la propria città. Tra il 1748 e il 1763 diede a Newport quattro edifici tuttora in piedi — la Redwood Library, la King\'s Chapel di Boston, la sinagoga Touro e il Brick Market —, ciascuno ricalcato su un precedente inglese o europeo ma costruito in legno e mattoni, non in pietra. Durante la Rivoluzione mantenne simpatie lealiste; dopo la morte nel 1775, una folla bruciò la sua casa, la biblioteca e tutti i suoi disegni.',
    },
    awards: [],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q1178933', title: 'Peter Harrison (Q1178933)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Peter_Harrison_(architect)', title: 'Peter Harrison (architect)', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'robert-smith-1722',
    wikidataId: 'Q7349874',
    name: 'Robert Smith',
    alternativeNames: ['Robert Smith (architect)'],
    gender: 'man',
    born: 1722,
    died: 1777,
    floruit: { start: 1750, end: 1774, override: false },
    movements: [
      { id: 'palladianism', primary: true },
    ],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'educational',
    signatureMaterial: 'stone',
    portrait: {
      en: 'Smith was born into a family of masons in Dalkeith, Scotland, and emigrated to Philadelphia in 1748 already trained as a builder rather than a gentleman-amateur. He rose fast: within a few years he was designing the city\'s most prominent commissions, among them the steeple of Christ Church, St Peter\'s Church, Carpenters\' Hall and the building he raised for the College of New Jersey at Princeton. He worked exclusively in the Georgian idiom of his English pattern books and was a founding member of the Carpenters\' Company of Philadelphia, the guild that trained the city\'s builders and set its construction standards. A member of the American Philosophical Society, he turned his skill to defence when war came, designing the chevaux-de-frise sunk in the Delaware River to block British ships. He died in 1777 at Fort Billingsport, New Jersey, while building barracks for the Continental Army.',
      es: 'Smith nació en una familia de canteros en Dalkeith, Escocia, y emigró a Filadelfia en 1748 ya formado como constructor y no como aficionado. Ascendió deprisa: en pocos años proyectaba los encargos más destacados de la ciudad, entre ellos el chapitel de Christ Church, la iglesia de St. Peter, el Carpenters\' Hall y el edificio que levantó para el College of New Jersey en Princeton. Trabajó siempre en el idioma georgiano de sus manuales ingleses y fue miembro fundador de la Carpenters\' Company de Filadelfia, el gremio que formaba a los constructores de la ciudad y fijaba sus estándares de obra. Miembro de la American Philosophical Society, sirvió a la defensa cuando llegó la guerra, diseñando los chevaux-de-frise hundidos en el río Delaware para cerrar el paso a los barcos británicos. Murió en 1777 en Fort Billingsport, Nueva Jersey, mientras construía cuarteles para el Ejército Continental.',
      it: 'Smith nacque in una famiglia di scalpellini a Dalkeith, in Scozia, ed emigrò a Filadelfia nel 1748 già formato come costruttore e non come dilettante colto. Fece rapidamente carriera: in pochi anni progettava le commesse più in vista della città, fra cui il campanile di Christ Church, la chiesa di St. Peter, la Carpenters\' Hall e l\'edificio che eresse per il College of New Jersey a Princeton. Lavorò sempre nell\'idioma georgiano dei suoi manuali inglesi e fu membro fondatore della Carpenters\' Company di Filadelfia, la corporazione che formava i costruttori della città e ne fissava gli standard costruttivi. Membro dell\'American Philosophical Society, mise le proprie competenze al servizio della difesa allo scoppio della guerra, progettando i chevaux-de-frise affondati nel fiume Delaware per sbarrare il passo alle navi britanniche. Morì nel 1777 a Fort Billingsport, nel New Jersey, mentre costruiva caserme per l\'esercito continentale.',
    },
    awards: [],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q7349874', title: 'Robert Smith (Q7349874)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Robert_Smith_(architect)', title: 'Robert Smith (architect)', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'thom-mayne',
    wikidataId: 'Q312847',
    name: 'Thom Mayne',
    alternativeNames: ['Thomas Mayne'],
    gender: 'man',
    born: 1944,
    died: null,
    floruit: { start: 1978, end: 2025, override: false },
    movements: [
      { id: 'high-tech', primary: true },
    ],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'civic',
    signatureMaterial: 'steel-and-glass',
    portrait: {
      en: 'Mayne was born in Waterbury, Connecticut, in 1944, studied architecture at USC and helped found the Southern California Institute of Architecture in 1972, the same year he started Morphosis with a rotating group of USC collaborators. For two decades the practice built mostly houses and small institutional work in Los Angeles, developing a vocabulary of tilted planes, exposed structure and machined metal before computer modelling let it build at the scale of the Caltrans headquarters and the San Francisco Federal Building. Mayne has always described the work as diagnostic rather than decorative, treating a facade\'s moving parts and irregular geometry as responses to light, seismic bracing or programme rather than as style for its own sake. He has taught at SCI-Arc since its founding and received the Pritzker Prize in 2005 and the AIA Gold Medal in 2013.',
      es: 'Mayne nació en Waterbury, Connecticut, en 1944, estudió arquitectura en la USC y contribuyó a fundar el Southern California Institute of Architecture en 1972, el mismo año en que puso en marcha Morphosis con un grupo variable de colaboradores de la USC. Durante dos décadas el estudio construyó sobre todo viviendas y pequeños encargos institucionales en Los Ángeles, desarrollando un vocabulario de planos inclinados, estructura vista y metal mecanizado, antes de que el modelado por ordenador le permitiera construir a la escala de Caltrans o del Edificio Federal de San Francisco. Mayne siempre ha descrito su obra como diagnóstica y no decorativa, tratando las partes móviles y la geometría irregular de una fachada como respuesta a la luz, al arriostramiento sísmico o al programa. Enseña en el SCI-Arc desde su fundación y recibió el Premio Pritzker en 2005 y la Medalla de Oro del AIA en 2013.',
      it: 'Mayne nacque a Waterbury, nel Connecticut, nel 1944, studiò architettura alla USC e contribuì a fondare il Southern California Institute of Architecture nel 1972, lo stesso anno in cui avviò Morphosis con un gruppo variabile di collaboratori della USC. Per due decenni lo studio costruì soprattutto case e piccoli incarichi istituzionali a Los Angeles, sviluppando un vocabolario di piani inclinati, struttura a vista e metallo lavorato a macchina, prima che la modellazione al computer gli permettesse di costruire alla scala di Caltrans o del Federal Building di San Francisco. Mayne ha sempre descritto il proprio lavoro come diagnostico e non decorativo, trattando le parti mobili e la geometria irregolare di una facciata come risposta alla luce, al controventamento sismico o al programma. Insegna alla SCI-Arc dalla fondazione e ha ricevuto il Premio Pritzker nel 2005 e la AIA Gold Medal nel 2013.',
    },
    awards: ['Pritzker Architecture Prize (2005)', 'AIA Gold Medal (2013)'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q312847', title: 'Thom Mayne (Q312847)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Thom_Mayne', title: 'Thom Mayne', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'dankmar-adler',
    wikidataId: 'Q76573',
    name: 'Dankmar Adler',
    alternativeNames: [],
    gender: 'man',
    born: 1844,
    died: 1900,
    floruit: { start: 1869, end: 1895, override: false },
    movements: 'unaffiliated',
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'commercial',
    signatureMaterial: 'brick',
    portrait: {
      en: 'Adler trained as a draftsman rather than in a school of architecture, working in Chicago from the 1860s and building a practice known for structural engineering and, above all, acoustics — the auditoriums he designed were prized for how their halls carried sound. His partnership with Louis Sullivan, formed in 1883, paired that engineering command with Sullivan\'s ornament and design sense: Adler worked out the steel framing and, at the Auditorium Building, the raked seating and adjustable ceiling that made its hall renowned, while Sullivan drew the surfaces. The partnership dissolved in 1895 after the 1893 financial panic emptied their order book, and Adler briefly left architecture for elevator engineering. He returned to independent practice with his sons and died in Chicago in 1900.',
      es: 'Adler se formó como delineante y no en una escuela de arquitectura, trabajó en Chicago desde la década de 1860 y desarrolló una práctica reconocida por la ingeniería estructural y, sobre todo, por la acústica: los auditorios que proyectaba eran apreciados por cómo transmitían el sonido sus salas. Su sociedad con Louis Sullivan, formada en 1883, unió ese dominio técnico con el sentido del ornamento y del diseño de Sullivan: Adler resolvió el entramado de acero y, en el Auditorium Building, el aforo escalonado y el techo regulable que hicieron célebre su sala, mientras Sullivan dibujaba las superficies. La sociedad se disolvió en 1895, tras vaciar el pánico financiero de 1893 su cartera de encargos, y Adler abandonó brevemente la arquitectura por la ingeniería de ascensores. Volvió al ejercicio independiente junto a sus hijos y murió en Chicago en 1900.',
      it: 'Adler si formò come disegnatore e non in una scuola di architettura, lavorò a Chicago dagli anni Sessanta dell\'Ottocento e sviluppò una pratica nota per l\'ingegneria strutturale e, soprattutto, per l\'acustica: gli auditori che progettava erano apprezzati per come le loro sale trasmettevano il suono. La sua società con Louis Sullivan, formata nel 1883, unì quel dominio tecnico al senso dell\'ornato e del disegno di Sullivan: Adler risolse l\'intelaiatura d\'acciaio e, nell\'Auditorium Building, la platea degradante e il soffitto regolabile che resero celebre la sua sala, mentre Sullivan disegnava le superfici. La società si sciolse nel 1895, dopo che il panico finanziario del 1893 aveva svuotato il portafoglio di commesse, e Adler lasciò brevemente l\'architettura per l\'ingegneria degli ascensori. Tornò alla pratica indipendente insieme ai figli e morì a Chicago nel 1900.',
    },
    awards: [],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q76573', title: 'Dankmar Adler (Q76573)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Dankmar_Adler', title: 'Dankmar Adler', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'philip-johnson',
    wikidataId: 'Q183528',
    name: 'Philip Johnson',
    alternativeNames: ['Philip Cortelyou Johnson'],
    gender: 'man',
    born: 1906,
    died: 2005,
    floruit: { start: 1949, end: 1996, override: false },
    movements: [
      { id: 'international-style', primary: false },
      { id: 'postmodern-classicism', primary: true },
    ],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'tower',
    signatureMaterial: 'steel-and-glass',
    portrait: {
      en: 'Johnson trained in classics at Harvard, not architecture, and in 1930 used his family\'s fortune to found and curate the Museum of Modern Art\'s architecture department; the 1932 "Modern Architecture" show he organised with Henry-Russell Hitchcock, and the book that named it the International Style, introduced Bauhaus-derived modernism to an American audience before Johnson had designed a building of his own. After the political detour documented below, he returned to architecture in the 1940s, studying under Marcel Breuer and Walter Gropius at Harvard and building himself the Glass House at forty-three. From the late 1970s, in partnership with John Burgee, he abandoned the glass-box vocabulary he had championed for decades and turned to a historically referential Postmodernism, most visibly at 550 Madison Avenue. He was the first Pritzker Prize laureate, in 1979, and worked into his nineties.',
      es: 'Johnson se formó en clásicas en Harvard, no en arquitectura, y en 1930 empleó la fortuna familiar para fundar y comisariar el departamento de arquitectura del MoMA; la muestra «Modern Architecture» de 1932, organizada junto con Henry-Russell Hitchcock, y el libro que le dio nombre, International Style, presentaron el modernismo derivado de la Bauhaus al público estadounidense antes de que Johnson hubiera proyectado un solo edificio propio. Tras el episodio político documentado más abajo, volvió a la arquitectura en los años cuarenta, estudiando con Marcel Breuer y Walter Gropius en Harvard, y se construyó la Glass House a los cuarenta y tres años. Desde finales de los setenta, en sociedad con John Burgee, abandonó el vocabulario de caja de vidrio que había defendido durante décadas y se pasó a un posmodernismo de referencias históricas, visible sobre todo en el 550 de Madison Avenue. Fue el primer premio Pritzker, en 1979, y siguió trabajando hasta pasados los noventa años.',
      it: 'Johnson si formò in studi classici a Harvard, non in architettura, e nel 1930 usò il patrimonio di famiglia per fondare e curare il dipartimento di architettura del MoMA; la mostra «Modern Architecture» del 1932, organizzata con Henry-Russell Hitchcock, e il libro che le diede il nome, International Style, presentarono al pubblico americano il modernismo derivato dal Bauhaus prima ancora che Johnson avesse progettato un solo edificio proprio. Dopo la parentesi politica documentata più sotto, tornò all\'architettura negli anni Quaranta, studiando con Marcel Breuer e Walter Gropius a Harvard, e si costruì la Glass House a quarantatré anni. Dalla fine degli anni Settanta, in società con John Burgee, abbandonò il vocabolario della scatola di vetro che aveva difeso per decenni e passò a un postmodernismo di riferimenti storici, visibile soprattutto al 550 di Madison Avenue. Fu il primo vincitore del Pritzker, nel 1979, e continuò a lavorare fino a oltre novant\'anni.',
    },
    awards: ['Pritzker Architecture Prize (1979)', 'AIA Gold Medal (1978)'],
    tier: 'canon',
    context: {
      body: {
        en: 'In the 1930s, before his return to architecture, Johnson organised a uniformed group modelled on Nazi Brownshirts, attended a Nuremberg rally in 1932 and described being "caught up in the excitement" of Hitler\'s speech, and worked as a journalist for Father Charles Coughlin\'s antisemitic newspaper Social Justice, for which he wrote admiringly of the 1939 German invasion of Poland and dismissed reports of Nazi atrocities against Poles as "misinformed." Writing elsewhere in the same period, he blamed national weakness on Jewish influence. He also founded a short-lived political party, campaigned to recruit the Louisiana populist Huey Long to lead it, and financed the antisemitic street organiser Joe McWilliams. The FBI investigated him during the Second World War for possible ties to the German government; he was never charged, and he served in the U.S. Army from 1943. He later called the episode "the stupidest thing I ever did," while in private correspondence as late as 1964 he was still writing that Hitler was "better than Roosevelt." In 2020 Harvard removed his name from a building over the record.',
        es: 'En los años treinta, antes de volver a la arquitectura, Johnson organizó un grupo uniformado inspirado en las camisas pardas nazis, asistió a un mitin de Núremberg en 1932 y describió sentirse «arrastrado por la excitación» del discurso de Hitler, y trabajó como periodista para Social Justice, el periódico antisemita del padre Charles Coughlin, en el que escribió con admiración sobre la invasión alemana de Polonia de 1939 y calificó de «mal informados» los relatos de atrocidades nazis contra los polacos. En otros escritos de la misma época atribuyó la debilidad nacional a la influencia judía. Fundó además un partido político de vida breve, hizo campaña para atraer a su liderazgo al populista de Luisiana Huey Long, y financió al agitador callejero antisemita Joe McWilliams. El FBI lo investigó durante la Segunda Guerra Mundial por posibles vínculos con el gobierno alemán; nunca fue procesado, y sirvió en el ejército de EE. UU. desde 1943. Más tarde calificó el episodio de «lo más estúpido que hice jamás», aunque en correspondencia privada de 1964 seguía escribiendo que Hitler era «mejor que Roosevelt». En 2020, Harvard retiró su nombre de un edificio a la vista de estos hechos.',
        it: 'Negli anni Trenta, prima di tornare all\'architettura, Johnson organizzò un gruppo in uniforme ispirato alle camicie brune naziste, partecipò a un raduno di Norimberga nel 1932 e descrisse di essersi sentito «travolto dall\'eccitazione» del discorso di Hitler, e lavorò come giornalista per Social Justice, il giornale antisemita di padre Charles Coughlin, sul quale scrisse con ammirazione dell\'invasione tedesca della Polonia del 1939 e definì «mal informati» i resoconti sulle atrocità naziste contro i polacchi. In altri scritti dello stesso periodo attribuì la debolezza nazionale all\'influenza ebraica. Fondò inoltre un partito politico di breve durata, fece campagna per portarne alla guida il populista della Louisiana Huey Long, e finanziò l\'agitatore di strada antisemita Joe McWilliams. L\'FBI lo indagò durante la Seconda guerra mondiale per possibili legami con il governo tedesco; non fu mai incriminato, e prestò servizio nell\'esercito statunitense dal 1943. In seguito definì l\'episodio «la cosa più stupida che abbia mai fatto», mentre in corrispondenza privata ancora nel 1964 scriveva che Hitler era «meglio di Roosevelt». Nel 2020 Harvard ha rimosso il suo nome da un edificio alla luce di questi fatti.',
      },
      sources: [
        { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Philip_Johnson', title: 'Philip Johnson', license: 'CC BY-SA 4.0' },
        { kind: 'publication', url: 'https://www.newyorker.com/culture/cultural-comment/philip-johnsons-evil-magnetism', title: 'Nikil Saval, "Philip Johnson\'s Evil Magnetism," The New Yorker (2018)', license: null },
      ],
    },
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q183528', title: 'Philip Johnson (Q183528)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Philip_Johnson', title: 'Philip Johnson', license: 'CC BY-SA 4.0' },
    ],
  },
{
    id: 'i-m-pei',
    wikidataId: 'Q46868',
    name: 'I. M. Pei',
    alternativeNames: ['Ieoh Ming Pei', 'Pei Ieoh Ming', '貝聿銘'],
    gender: 'man',
    born: 1917,
    died: 2019,
    floruit: { start: 1955, end: 2006, override: false },
    movements: [
      { id: 'international-style', primary: true },
    ],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'cultural',
    signatureMaterial: 'stone',
    portrait: {
      en: 'Pei was born in Guangzhou in 1917 to a prominent banking family, emigrated to the United States in 1935 and trained at MIT and then at Harvard\'s Graduate School of Design under Walter Gropius and Marcel Breuer. A decade spent shaping speculative urban redevelopment for the New York developer William Zeckendorf taught him to work within a client\'s numbers before he opened his own practice in 1955; by the time he retired from day-to-day management in 1990 that practice had built some of the most recognisable museums in the world. Pei\'s buildings return again and again to hard geometric volumes — triangles, rhombuses, knife-edge angles — resolved in stone, granite or glass, and to the problem of setting a modern building beside a historically loaded one without either apologising for it or overpowering it. He won the Pritzker Prize in 1983 and the Presidential Medal of Freedom in 1992, and kept accepting museum commissions into his late eighties and nineties, ending his working life, as it had begun, in China.',
      es: 'Pei nació en Cantón en 1917 en el seno de una destacada familia de banqueros, emigró a Estados Unidos en 1935 y se formó en el MIT y después en la Graduate School of Design de Harvard bajo Walter Gropius y Marcel Breuer. Una década dedicada a dar forma a la reurbanización urbana especulativa para el promotor neoyorquino William Zeckendorf le enseñó a trabajar dentro de las cuentas de un cliente antes de abrir su propio estudio en 1955; para cuando se retiró de la gestión diaria en 1990, ese estudio había construido algunos de los museos más reconocibles del mundo. La arquitectura de Pei vuelve una y otra vez a volúmenes geométricos duros —triángulos, rombos, ángulos de filo de cuchillo— resueltos en piedra, granito o vidrio, y al problema de situar un edificio moderno junto a otro cargado de historia sin disculparse por ello ni imponerse sobre él. Ganó el Premio Pritzker en 1983 y la Medalla Presidencial de la Libertad en 1992, y siguió aceptando encargos de museos hasta bien entrados los ochenta y noventa años, cerrando su vida profesional, como la había empezado, en China.',
      it: 'Pei nacque a Canton nel 1917 in una famiglia di banchieri di rilievo, emigrò negli Stati Uniti nel 1935 e si formò al MIT e poi alla Graduate School of Design di Harvard sotto Walter Gropius e Marcel Breuer. Un decennio passato a dare forma alla riqualificazione urbana speculativa per l\'imprenditore newyorkese William Zeckendorf gli insegnò a lavorare entro i conti di un committente prima di aprire un proprio studio nel 1955; quando si ritirò dalla gestione quotidiana nel 1990, quello studio aveva costruito alcuni dei musei più riconoscibili al mondo. L\'architettura di Pei torna ripetutamente a volumi geometrici rigorosi — triangoli, rombi, spigoli a lama di coltello — risolti in pietra, granito o vetro, e al problema di collocare un edificio moderno accanto a uno carico di storia senza scusarsene né sovrastarlo. Vinse il Premio Pritzker nel 1983 e la Presidential Medal of Freedom nel 1992, e continuò ad accettare incarichi museali fino a oltre gli ottant\'anni e i novant\'anni, chiudendo la propria vita professionale, come l\'aveva iniziata, in Cina.',
    },
    awards: ['Pritzker Architecture Prize (1983)', 'AIA Gold Medal (1979)', 'Presidential Medal of Freedom (1992)', 'Praemium Imperiale (1989)'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q46868', title: 'I. M. Pei (Q46868)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/I._M._Pei', title: 'I. M. Pei', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'frank-gehry',
    wikidataId: 'Q180374',
    name: 'Frank Gehry',
    alternativeNames: ['Frank Owen Gehry', 'Frank Owen Goldberg'],
    gender: 'man',
    born: 1929,
    died: 2025,
    floruit: { start: 1962, end: 2021, override: false },
    movements: [
      { id: 'deconstructivism', primary: true },
    ],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'cultural',
    signatureMaterial: 'steel-and-glass',
    portrait: {
      en: 'Gehry was born Frank Goldberg in Toronto in 1929, moved with his family to Los Angeles at seventeen, and studied at USC and briefly at Harvard\'s Graduate School of Design before opening his own Los Angeles practice in 1962. For two decades he built modest, inexpensive work, most famously the 1978 remodel of his own Santa Monica bungalow in corrugated metal, plywood and chain-link fencing, materials chosen because a client\'s budget could afford them, not for effect. Computer-aided design borrowed from the aerospace industry let his later practice translate the same instinct for torqued, improvised-looking form into buildable curved metal at the scale of an entire museum, starting with Bilbao in 1997. He kept a working office into his nineties and died in Santa Monica in December 2025, having reshaped what a public building was allowed to look like more than once in a sixty-year career.',
      es: 'Gehry nació como Frank Goldberg en Toronto en 1929, se trasladó con su familia a Los Ángeles a los diecisiete años y estudió en la USC y brevemente en la Graduate School of Design de Harvard antes de abrir su propio estudio en Los Ángeles en 1962. Durante dos décadas construyó obra modesta y barata, sobre todo la remodelación en 1978 de su propio bungaló de Santa Mónica en chapa ondulada, contrachapado y valla de tela metálica, materiales elegidos porque el presupuesto de un cliente podía pagarlos, no por efecto. El diseño asistido por ordenador, tomado prestado de la industria aeroespacial, permitió a su estudio posterior trasladar ese mismo instinto de forma retorcida y de aire improvisado a metal curvo construible a la escala de un museo entero, empezando por Bilbao en 1997. Mantuvo un estudio en activo hasta los noventa años y murió en Santa Mónica en diciembre de 2025, habiendo cambiado más de una vez, en una carrera de sesenta años, lo que se permitía que pareciera un edificio público.',
      it: 'Gehry nacque come Frank Goldberg a Toronto nel 1929, si trasferì con la famiglia a Los Angeles a diciassette anni e studiò alla USC e brevemente alla Graduate School of Design di Harvard prima di aprire un proprio studio a Los Angeles nel 1962. Per due decenni costruì opere modeste ed economiche, in particolare la ristrutturazione del 1978 del proprio bungalow di Santa Monica in lamiera ondulata, compensato e rete metallica, materiali scelti perché il budget di un cliente poteva permetterseli, non per effetto. La progettazione assistita dal computer, presa in prestito dall\'industria aerospaziale, permise al suo studio successivo di tradurre lo stesso istinto per la forma ritorta e dall\'aria improvvisata in metallo curvo costruibile alla scala di un intero museo, a partire da Bilbao nel 1997. Mantenne uno studio attivo fino agli anni novanta e morì a Santa Monica nel dicembre 2025, avendo cambiato più di una volta, in una carriera di sessant\'anni, ciò che a un edificio pubblico era concesso somigliare.',
    },
    awards: ['Pritzker Architecture Prize (1989)', 'AIA Gold Medal (1999)', 'Presidential Medal of Freedom (2016)'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q180374', title: 'Frank Gehry (Q180374)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Frank_Gehry', title: 'Frank Gehry', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'marcel-breuer',
    wikidataId: 'Q57588',
    name: 'Marcel Breuer',
    alternativeNames: ['Marcel Lajos Breuer'],
    gender: 'man',
    born: 1902,
    died: 1981,
    floruit: { start: 1938, end: 1980, override: false },
    movements: [
      { id: 'brutalism', primary: true },
      { id: 'bauhaus', primary: false },
    ],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'cultural',
    signatureMaterial: 'concrete',
    portrait: {
      en: 'Breuer left home in Pécs, Hungary, at eighteen to study art in Vienna, lasted a few weeks, and enrolled instead at the new Bauhaus in Weimar in 1920, one of its first and youngest students. Walter Gropius made him head of the carpentry workshop at twenty-two; the tubular-steel Wassily and Cesca chairs he designed there, borrowing the idea from bicycle handlebars, remain in production a century later. He left for London in 1935 as the school\'s politics soured, then followed Gropius again in 1937, this time to Harvard\'s Graduate School of Design, where the two ran a joint practice designing houses before Breuer opened his own office in New York in 1946. His architecture, unlike his furniture, grew heavier and rougher with time: raw and board-marked concrete, sculpted into cantilevers and folded planes, on buildings for the United Nations, UNESCO and a run of American college and corporate clients. He won the AIA Gold Medal in 1968.',
      es: 'Breuer dejó su casa en Pécs, Hungría, a los dieciocho años para estudiar arte en Viena, aguantó unas semanas y se matriculó en cambio en la recién fundada Bauhaus de Weimar en 1920, uno de sus alumnos más jóvenes y tempranos. Walter Gropius lo puso al frente del taller de carpintería a los veintidós años; las sillas Wassily y Cesca de acero tubular que diseñó allí, tomando la idea del manillar de bicicleta, siguen fabricándose un siglo después. Se marchó a Londres en 1935 cuando la política de la escuela se agrió, y siguió de nuevo a Gropius en 1937, esta vez a la Graduate School of Design de Harvard, donde ambos dirigieron un estudio conjunto diseñando casas antes de que Breuer abriera su propia oficina en Nueva York en 1946. Su arquitectura, a diferencia de sus muebles, se hizo más pesada y rugosa con el tiempo: hormigón en bruto y con marcas de encofrado, esculpido en voladizos y planos plegados, en edificios para las Naciones Unidas, la UNESCO y una serie de clientes universitarios y corporativos estadounidenses. Ganó la Medalla de Oro del AIA en 1968.',
      it: 'Breuer lasciò la propria casa a Pécs, in Ungheria, a diciotto anni per studiare arte a Vienna, resistette poche settimane e si iscrisse invece al neonato Bauhaus di Weimar nel 1920, tra i suoi allievi più giovani e precoci. Walter Gropius lo mise a capo dell\'officina di falegnameria a ventidue anni; le sedie in acciaio tubolare Wassily e Cesca che vi progettò, riprendendo l\'idea dal manubrio di una bicicletta, restano in produzione un secolo dopo. Partì per Londra nel 1935 quando il clima politico della scuola peggiorò, e seguì di nuovo Gropius nel 1937, questa volta alla Graduate School of Design di Harvard, dove i due gestirono uno studio comune progettando case prima che Breuer aprisse un proprio studio a New York nel 1946. La sua architettura, a differenza dei mobili, si fece più pesante e ruvida col tempo: calcestruzzo grezzo e segnato dal cassero, scolpito in sbalzi e piani piegati, in edifici per le Nazioni Unite, l\'UNESCO e una serie di committenti universitari e aziendali statunitensi. Vinse la AIA Gold Medal nel 1968.',
    },
    awards: ['AIA Gold Medal (1968)'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q57588', title: 'Marcel Breuer (Q57588)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Marcel_Breuer', title: 'Marcel Breuer', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'buckminster-fuller',
    wikidataId: 'Q102289',
    name: 'Buckminster Fuller',
    alternativeNames: ['Richard Buckminster Fuller', 'R. Buckminster Fuller'],
    gender: 'man',
    born: 1895,
    died: 1983,
    floruit: { start: 1949, end: 1981, override: false },
    movements: 'unaffiliated',
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'cultural',
    signatureMaterial: 'steel-and-glass',
    portrait: {
      en: 'Fuller never finished a degree — Harvard expelled him twice — and never held an architecture licence, which makes him an outlier on any roster of architects and, by his own account, the point: he called himself a "comprehensive anticipatory design scientist" and worked from mathematics and materials efficiency rather than architectural training. A failed business and the death of a daughter brought him to the edge of suicide in 1927; he described what followed as a decision to treat his own life as an experiment in what one individual, stripped of inherited assumptions, could contribute. Working largely outside any single professional discipline, he patented the geodesic dome in 1954 — a structural principle, triangulating a sphere\'s surface so that stress is distributed across the whole shell rather than carried by any single member, that let a dome enclose enormous unsupported spans at a fraction of the material a conventional roof would need. He held twenty-eight US patents, wrote more than thirty books, and received the Presidential Medal of Freedom the year he died.',
      es: 'Fuller nunca terminó una carrera —Harvard lo expulsó dos veces— y nunca tuvo licencia de arquitecto, lo que lo convierte en un caso aparte en cualquier lista de arquitectos y, según él mismo, esa era la cuestión: se llamaba a sí mismo "científico del diseño anticipatorio integral" y trabajaba desde las matemáticas y la eficiencia de materiales, no desde una formación arquitectónica. Un negocio fallido y la muerte de una hija lo llevaron al borde del suicidio en 1927; describió lo que vino después como la decisión de tratar su propia vida como un experimento sobre lo que un individuo, despojado de supuestos heredados, podía aportar. Trabajando en gran medida al margen de cualquier disciplina profesional única, patentó la cúpula geodésica en 1954 —un principio estructural que triangula la superficie de una esfera para repartir la tensión por toda la cáscara en vez de cargarla sobre un solo elemento— que permitía a una cúpula cubrir enormes luces sin apoyos con una fracción del material que exigiría una cubierta convencional. Tuvo veintiocho patentes estadounidenses, escribió más de treinta libros y recibió la Medalla Presidencial de la Libertad el año de su muerte.',
      it: 'Fuller non completò mai una laurea — Harvard lo espulse due volte — e non ebbe mai un\'abilitazione da architetto, il che lo rende un caso a parte in qualunque elenco di architetti e, a suo dire, era proprio quello il punto: si definiva un "comprehensive anticipatory design scientist" e lavorava a partire dalla matematica e dall\'efficienza dei materiali, non da una formazione architettonica. Un\'attività fallita e la morte di una figlia lo portarono sull\'orlo del suicidio nel 1927; descrisse ciò che seguì come la decisione di trattare la propria vita come un esperimento su ciò che un singolo individuo, spogliato di assunti ereditati, potesse offrire. Lavorando in gran parte al di fuori di una disciplina professionale unica, brevettò la cupola geodetica nel 1954 — un principio strutturale che triangola la superficie di una sfera per distribuire lo sforzo sull\'intero guscio anziché su un singolo elemento — che permetteva a una cupola di coprire luci enormi senza appoggi con una frazione del materiale richiesto da una copertura convenzionale. Detenne ventotto brevetti statunitensi, scrisse più di trenta libri e ricevette la Presidential Medal of Freedom l\'anno della sua morte.',
    },
    awards: ['AIA Gold Medal (1970)', 'Presidential Medal of Freedom (1983)'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q102289', title: 'Buckminster Fuller (Q102289)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Buckminster_Fuller', title: 'Buckminster Fuller', license: 'CC BY-SA 4.0' },
    ],
  },

];
