import type { Architect } from '@/types/architect';

// Eastern Asia slice (Japan, China, South Korea, Taiwan, Hong Kong, Mongolia).
//
// `workRegions` and `workCentroid` are intentionally left empty here:
// buildCuratedPool derives both from each architect's buildings and discards
// whatever these fields contain.
export const ASIA_ARCHITECTS: Architect[] = [
  {
    id: 'jeong-yak-yong',
    wikidataId: 'Q256246',
    name: 'Jeong Yak-yong',
    alternativeNames: ['정약용', '丁若鏞', 'Chŏng Yagyong', 'Tasan', '다산'],
    gender: 'man',
    born: 1762,
    died: 1836,
    floruit: { start: 1794, end: 1796, override: false },
    movements: 'unaffiliated',
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'infrastructure',
    signatureMaterial: 'brick',
    portrait: {
      en: 'Jeong Yak-yong was a Joseon scholar of the Silhak, or "practical learning", school, remembered chiefly for his writing on law, government and agronomy, and in architecture for one commission that reorganised Korean fortification. Asked by King Jeongjo to design Hwaseong, he weighed Korean, Chinese and European precedents and produced a plan gathering a defensive wall, a garrison and a working market town into a single enclosure. His most consequential decisions were technical: fired brick, almost unused in Korean military building, for parapets, ravelins and watergates, and a hoisting device, the geojunggi, that cut the labour of moving cut stone. UNESCO credits the design to him by name. From 1801 he spent eighteen years in internal exile in Gangjin.',
      es: 'Jeong Yak-yong fue un erudito coreano de la escuela Silhak —el «aprendizaje práctico»—, recordado sobre todo por sus escritos de derecho, gobierno y agronomía y, en arquitectura, por un solo encargo que reordenó la fortificación coreana. Llamado por el rey Jeongjo a proyectar Hwaseong, sopesó precedentes coreanos, chinos y europeos y trazó un plan que reunía en un mismo recinto la muralla defensiva, la guarnición y una ciudad mercantil en funcionamiento. Sus decisiones más determinantes fueron técnicas: el ladrillo cocido, casi inédito en la construcción militar coreana, en parapetos, revellines y compuertas, y un aparejo de izado, el geojunggi, que redujo el trabajo de mover la piedra labrada. La UNESCO le atribuye por su nombre el diseño. Desde 1801 pasó dieciocho años desterrado en Gangjin.',
      it: 'Jeong Yak-yong fu uno studioso coreano della scuola Silhak, il «sapere pratico», ricordato soprattutto per i suoi scritti di diritto, governo e agronomia e, in architettura, per un unico incarico che riordinò la fortificazione coreana. Chiamato dal re Jeongjo a progettare Hwaseong, soppesò precedenti coreani, cinesi ed europei e mise a punto un piano che riuniva in un solo recinto la muraglia difensiva, la guarnigione e una città mercantile funzionante. Le sue scelte più incisive furono tecniche: il mattone cotto, quasi inedito nell\'edilizia militare coreana, per parapetti, rivellini e chiuse, e un apparecchio di sollevamento, il geojunggi, che ridusse la fatica di spostare la pietra lavorata. L\'UNESCO attribuisce a lui, per nome, il progetto. Dal 1801 trascorse diciotto anni in esilio a Gangjin.',
    },
    awards: [],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q256246', title: 'Jeong Yak-yong (Q256246)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Ch%C5%8Fng_Yagyong', title: 'Chŏng Yagyong', license: 'CC BY-SA 4.0' },
      { kind: 'institution', url: 'https://whc.unesco.org/en/list/817/', title: 'Hwaseong Fortress — UNESCO World Heritage Centre', license: null },
    ],
  },
  {
    id: 'uheiji-nagano',
    wikidataId: 'Q11654164',
    name: 'Uheiji Nagano',
    alternativeNames: ['長野宇平治', 'Nagano Uheiji'],
    gender: 'man',
    born: 1867,
    died: 1937,
    floruit: { start: 1895, end: 1938, override: false },
    movements: [
      { id: 'beaux-arts', primary: true },
      { id: 'neoclassicism', primary: false },
    ],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'commercial',
    signatureMaterial: 'stone',
    portrait: {
      en: 'Uheiji Nagano was a pupil of Kingo Tatsuno and, for most of his career, the house architect of a bank. He entered the Bank of Japan as an engineer in 1897 and designed or supervised its Osaka, Kyoto and Otaru branches; after fifteen years in private practice he returned in 1927 to run the head-office extension, which was finished the year after his death. His idiom was the classicism the Meiji state used to look solvent: masonry orders, rusticated bases, disciplined symmetry. He took the leading award in the competition for the Office of the Governor-General of Taiwan, generally counted as Japan\'s first open architectural contest, though the executed building was substantially revised in Tokyo. In 1917 he was elected first president of the Japan Institute of Architects, and pressed for legislation to make architecture a licensed profession.',
      es: 'Uheiji Nagano fue discípulo de Kingo Tatsuno y, durante casi toda su carrera, el arquitecto de cabecera de un banco. Entró como ingeniero en el Banco de Japón en 1897 y proyectó o dirigió sus sucursales de Osaka, Kioto y Otaru; tras quince años de estudio propio volvió en 1927 para hacerse cargo de la ampliación de la sede central, terminada el año siguiente a su muerte. Su lenguaje era el clasicismo con que el Estado Meiji quería parecer solvente: órdenes de fábrica, basamentos almohadillados, simetría severa. Obtuvo el galardón principal en el concurso para la Oficina del Gobernador General de Taiwán, que suele contarse como el primer certamen público de arquitectura de Japón, aunque el edificio construido se revisó a fondo en Tokio. En 1917 fue elegido primer presidente del Instituto de Arquitectos de Japón e impulsó una ley que diera estatuto profesional al oficio.',
      it: 'Uheiji Nagano fu allievo di Kingo Tatsuno e, per quasi tutta la carriera, l\'architetto di fiducia di una banca. Entrò come ingegnere alla Banca del Giappone nel 1897 e progettò o diresse le filiali di Osaka, Kyoto e Otaru; dopo quindici anni di studio proprio vi tornò nel 1927 per seguire l\'ampliamento della sede centrale, ultimata l\'anno successivo alla sua morte. Il suo linguaggio era il classicismo con cui lo Stato Meiji voleva apparire solido: ordini in muratura, basamenti bugnati, simmetria severa. Ottenne il premio principale nel concorso per l\'Ufficio del Governatore Generale di Taiwan, di norma considerato il primo concorso pubblico di architettura del Giappone, benché l\'edificio realizzato fosse profondamente rivisto a Tokyo. Nel 1917 fu eletto primo presidente dell\'Istituto degli Architetti del Giappone e si batté per una legge che desse statuto professionale al mestiere.',
    },
    awards: [],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q11654164', title: 'Uheiji Nagano (Q11654164)', license: null },
      { kind: 'wikipedia', url: 'https://ja.wikipedia.org/wiki/%E9%95%B7%E9%87%8E%E5%AE%87%E5%B9%B3%E6%B2%BB', title: '長野宇平治', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Presidential_Office_Building,_Taipei', title: 'Presidential Office Building, Taipei', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'lu-yanzhi',
    wikidataId: 'Q10918370',
    name: 'Lü Yanzhi',
    alternativeNames: ['呂彥直', '吕彦直', 'Lü Yen-chih'],
    gender: 'man',
    born: 1894,
    died: 1929,
    floruit: { start: 1923, end: 1931, override: false },
    movements: [{ id: 'beaux-arts', primary: true }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'civic',
    signatureMaterial: 'stone',
    portrait: {
      en: 'Lü Yanzhi took an architecture degree at Cornell in 1918, worked for Murphy & Dana on Ginling College and Yenching University, and in 1921 opened what is generally described as the first Chinese-owned architectural practice. In 1924 he co-founded China\'s first professional architectural association. He then won, in succession, the two competitions that defined republican commemorative architecture: the Sun Yat-sen Mausoleum in Nanjing in September 1925 and the Sun Yat-sen Memorial Hall in Guangzhou the following year. Both graft Chinese roofs, glazed tile and axial ceremonial sequence onto Beaux-Arts planning, a synthesis he described in writing as a way of asserting Chinese nationhood against foreign imperialism. Liang Sicheng later faulted him for borrowing only the surface of Chinese building. He died of cancer in March 1929, months before Sun was interred.',
      es: 'Lü Yanzhi se tituló en arquitectura por Cornell en 1918, trabajó para Murphy & Dana en el Ginling College y la Universidad de Yenching y en 1921 abrió lo que suele describirse como el primer estudio de arquitectura de propiedad china. En 1924 cofundó la primera asociación profesional de arquitectos del país. Ganó luego, encadenados, los dos concursos que definieron la arquitectura conmemorativa republicana: el Mausoleo de Sun Yat-sen en Nankín, en septiembre de 1925, y el Salón Conmemorativo de Sun Yat-sen en Cantón al año siguiente. Ambos injertan cubiertas chinas, teja vidriada y secuencia ceremonial axial sobre una planta Beaux-Arts, síntesis que él mismo describió por escrito como una afirmación de la nación china frente al imperialismo extranjero. Liang Sicheng le reprochó después haber tomado solo la superficie de la construcción china. Murió de cáncer en marzo de 1929, meses antes de la inhumación de Sun.',
      it: 'Lü Yanzhi si laureò in architettura alla Cornell nel 1918, lavorò per Murphy & Dana al Ginling College e all\'Università di Yenching e nel 1921 aprì quello che viene di norma descritto come il primo studio di architettura di proprietà cinese. Nel 1924 cofondò la prima associazione professionale di architetti del paese. Vinse poi, uno dopo l\'altro, i due concorsi che definirono l\'architettura commemorativa repubblicana: il Mausoleo di Sun Yat-sen a Nanchino, nel settembre 1925, e la Sala Commemorativa di Sun Yat-sen a Canton l\'anno seguente. Entrambi innestano tetti cinesi, tegole invetriate e sequenza cerimoniale assiale su un impianto Beaux-Arts, una sintesi che egli stesso descrisse per iscritto come affermazione della nazione cinese contro l\'imperialismo straniero. Liang Sicheng gli rimproverò poi di aver preso solo la superficie del costruire cinese. Morì di cancro nel marzo 1929, mesi prima della tumulazione di Sun.',
    },
    awards: [
      'First prize, Sun Yat-sen Mausoleum design competition (1925)',
      'First prize, Sun Yat-sen Memorial Hall design competition (1926)',
    ],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q10918370', title: 'Lü Yanzhi (Q10918370)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/L%C3%BC_Yanzhi', title: 'Lü Yanzhi', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'kenzo-tange',
    wikidataId: 'Q151794',
    name: 'Kenzō Tange',
    alternativeNames: ['丹下健三', 'Tange Kenzō'],
    gender: 'man',
    born: 1913,
    died: 2005,
    floruit: { start: 1955, end: 2005, override: false },
    movements: [
      { id: 'brutalism', primary: true },
      { id: 'metabolism', primary: false },
    ],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'civic',
    signatureMaterial: 'concrete',
    portrait: {
      en: 'Kenzō Tange decided to become an architect after finding drawings of Le Corbusier\'s Palace of the Soviets in a foreign journal, and spent a career arguing that a modern architecture could be specifically Japanese without being decorative about it. He trained at the University of Tokyo, worked briefly for Kunio Maekawa, and won a run of wartime national competitions before 1945. His reputation was made after the war by Hiroshima, where he planned the Peace Memorial Park and its museum, and consolidated by the Yoyogi gymnasiums of 1964 and the Tokyo Metropolitan Government Building of 1991. He taught Kisho Kurokawa, Arata Isozaki and Fumihiko Maki, and was mentor and patron to the Metabolists without joining them. Pritzker laureate in 1987; Royal Gold Medal in 1965.',
      es: 'Kenzō Tange decidió ser arquitecto al encontrar en una revista extranjera los dibujos del Palacio de los Sóviets de Le Corbusier, y dedicó su carrera a sostener que una arquitectura moderna podía ser específicamente japonesa sin recurrir al ornamento. Se formó en la Universidad de Tokio, trabajó brevemente con Kunio Maekawa y ganó una serie de concursos nacionales durante la guerra. Su reputación la hizo, tras 1945, Hiroshima, donde planificó el Parque Memorial de la Paz y su museo, y la consolidaron los gimnasios de Yoyogi de 1964 y la sede del Gobierno Metropolitano de Tokio de 1991. Fue maestro de Kisho Kurokawa, Arata Isozaki y Fumihiko Maki, y fue mentor y valedor de los metabolistas sin llegar a integrarse en el grupo. Premio Pritzker en 1987 y Medalla de Oro del RIBA en 1965.',
      it: 'Kenzō Tange decise di fare l\'architetto dopo aver trovato in una rivista straniera i disegni del Palazzo dei Soviet di Le Corbusier, e passò la carriera a sostenere che un\'architettura moderna potesse essere specificamente giapponese senza per questo farsi decorativa. Si formò all\'Università di Tokyo, lavorò brevemente con Kunio Maekawa e vinse una serie di concorsi nazionali durante la guerra. La sua fama la costruì, dopo il 1945, Hiroshima, di cui pianificò il Parco della Pace e il museo, e la consolidarono le palestre di Yoyogi del 1964 e la sede del Governo Metropolitano di Tokyo del 1991. Fu maestro di Kisho Kurokawa, Arata Isozaki e Fumihiko Maki, e fu mentore e sostenitore dei metabolisti senza mai entrare nel gruppo. Premio Pritzker nel 1987 e Royal Gold Medal nel 1965.',
    },
    awards: [
      'Pritzker Architecture Prize (1987)',
      'RIBA Royal Gold Medal (1965)',
      'AIA Gold Medal (1966)',
      'Praemium Imperiale (1993)',
      'Order of Culture (Japan)',
    ],
    tier: 'canon',
    context: {
      body: {
        en: 'Tange\'s first competition successes were commissions of the Japanese wartime state. In 1942 he took first prize in the competition for a Memorial Hall for the Greater East Asia Co-Prosperity Sphere, to stand at the foot of Mount Fuji, and in 1943 he won the competition for a Japan–Thai Cultural Hall; neither was built. Answering a 1942 questionnaire on architectural policy for the Co-Prosperity Sphere he wrote: "We must ignore both Anglo-American culture and the pre-existing cultures of the Southeast Asian Races. […] We should start out with an unshakable conviction in the tradition and the future of the Japanese races." Critics rarely raised this record in the immediate postwar years, when Tange was rebuilding Hiroshima; scholars have since traced continuities between the early nationalist projects and his lifelong search for a specifically Japanese modernism.',
        es: 'Los primeros éxitos de Tange en concurso fueron encargos del Estado japonés en guerra. En 1942 obtuvo el primer premio del concurso para un Salón Conmemorativo de la Esfera de Coprosperidad de la Gran Asia Oriental, previsto al pie del monte Fuji, y en 1943 ganó el del Salón Cultural Japonés-Tailandés; ninguno se construyó. Al responder en 1942 a un cuestionario sobre política arquitectónica para la Esfera escribió: «Debemos ignorar tanto la cultura angloamericana como las culturas preexistentes de las razas del Sudeste Asiático. […] Hemos de partir de una convicción inquebrantable en la tradición y el futuro de las razas japonesas». La crítica apenas mencionó ese historial en la inmediata posguerra, mientras Tange reconstruía Hiroshima; después, los estudiosos han rastreado continuidades entre aquellos proyectos nacionalistas y su búsqueda constante de un modernismo específicamente japonés.',
        it: 'I primi successi di Tange nei concorsi furono incarichi dello Stato giapponese in guerra. Nel 1942 vinse il primo premio per una Sala Commemorativa della Sfera di Co-prosperità della Grande Asia Orientale, prevista ai piedi del monte Fuji, e nel 1943 il concorso per una Sala Culturale nippo-thailandese; nessuna delle due fu costruita. Rispondendo nel 1942 a un questionario sulla politica architettonica per la Sfera scrisse: «Dobbiamo ignorare sia la cultura angloamericana sia le culture preesistenti delle razze del Sud-est asiatico. […] Dobbiamo partire da una convinzione incrollabile nella tradizione e nel futuro delle razze giapponesi». La critica quasi non richiamò quel percorso nell\'immediato dopoguerra, mentre Tange ricostruiva Hiroshima; in seguito gli studiosi hanno individuato continuità fra quei progetti nazionalisti e la sua ricerca costante di un modernismo specificamente giapponese.',
      },
      sources: [
        { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Kenz%C5%8D_Tange', title: 'Kenzō Tange', license: 'CC BY-SA 4.0' },
      ],
    },
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q151794', title: 'Kenzō Tange (Q151794)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Kenz%C5%8D_Tange', title: 'Kenzō Tange', license: 'CC BY-SA 4.0' },
      { kind: 'institution', url: 'https://www.pritzkerprize.com/laureates/1987', title: 'Kenzo Tange — The Pritzker Architecture Prize', license: null },
    ],
  },
  {
    id: 'kisho-kurokawa',
    wikidataId: 'Q358502',
    name: 'Kisho Kurokawa',
    alternativeNames: ['黒川紀章', 'Kurokawa Kishō'],
    gender: 'man',
    born: 1934,
    died: 2007,
    floruit: { start: 1962, end: 2007, override: false },
    movements: [{ id: 'metabolism', primary: true }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'cultural',
    signatureMaterial: 'concrete',
    portrait: {
      en: 'Kisho Kurokawa studied under Kenzō Tange at the University of Tokyo and was a founding member of the Metabolist group that announced itself at the 1960 World Design Conference in Tokyo. Metabolism held that a building should be a growing organism: a permanent frame carrying replaceable parts, sized and detailed like machine components. Kurokawa founded his own office in 1962 and spent four decades testing the idea at every scale, from the capsules of the Nakagin tower to airports at Kuala Lumpur and museums at Nagoya, Hiroshima and, finally, the National Art Center in Tokyo, completed in the year he died. He wrote extensively on symbiosis and, late in life, on ecology, standing for public office in 2007 on an environmental platform.',
      es: 'Kisho Kurokawa estudió con Kenzō Tange en la Universidad de Tokio y fue miembro fundador del grupo metabolista que se presentó en la Conferencia Mundial de Diseño de Tokio de 1960. El metabolismo sostenía que un edificio debía ser un organismo en crecimiento: una estructura permanente que soporta piezas sustituibles, dimensionadas y detalladas como componentes de máquina. Kurokawa abrió estudio propio en 1962 y dedicó cuatro décadas a ensayar la idea a todas las escalas, de las cápsulas de la torre Nakagin a los aeropuertos de Kuala Lumpur y los museos de Nagoya, Hiroshima y, finalmente, el Centro Nacional de Arte de Tokio, terminado el año de su muerte. Escribió largamente sobre la simbiosis y, ya mayor, sobre ecología, y en 2007 se presentó a elecciones con un programa ambiental.',
      it: 'Kisho Kurokawa studiò con Kenzō Tange all\'Università di Tokyo e fu tra i fondatori del gruppo metabolista che si presentò alla Conferenza Mondiale del Design di Tokyo del 1960. Il metabolismo sosteneva che un edificio dovesse essere un organismo in crescita: una struttura permanente che regge parti sostituibili, dimensionate e dettagliate come componenti di macchina. Kurokawa aprì il proprio studio nel 1962 e dedicò quarant\'anni a verificare l\'idea a ogni scala, dalle capsule della torre Nakagin agli aeroporti di Kuala Lumpur e ai musei di Nagoya, Hiroshima e infine al Centro Nazionale d\'Arte di Tokyo, ultimato nell\'anno della sua morte. Scrisse a lungo sulla simbiosi e, in tarda età, di ecologia, candidandosi nel 2007 con un programma ambientalista.',
    },
    awards: [
      'Chevalier des Arts et des Lettres',
      'Japan Art Academy Prize',
      'Order of the Lion of Finland',
    ],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q358502', title: 'Kisho Kurokawa (Q358502)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Kisho_Kurokawa', title: 'Kisho Kurokawa', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'itsuko-hasegawa',
    wikidataId: 'Q445298',
    name: 'Itsuko Hasegawa',
    alternativeNames: ['長谷川逸子', 'Hasegawa Itsuko'],
    gender: 'woman',
    born: 1941,
    died: null,
    floruit: { start: 1979, end: 2008, override: false },
    movements: 'unaffiliated',
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'cultural',
    signatureMaterial: 'steel-and-glass',
    portrait: {
      en: 'Itsuko Hasegawa graduated in architecture from Kanto Gakuin University in 1964, worked for Kiyonori Kikutake, then spent seven years with Kazuo Shinohara at the Tokyo Institute of Technology before opening her own studio in Tokyo. She describes her work as "second nature": buildings that behave like landscape and are shaped by the way a particular community actually lives. In practice that means perforated aluminium screens, light steel frames and metal spheres and canopies assembled into something closer to a park than a monument. She ran unusually long consultations with the residents who opposed the Shōnandai centre, and afterwards directed its children\'s museum for ten years. In 2018 she received the inaugural Royal Academy Architecture Prize, whose panel called her one of Japan\'s most important architects and noted how little recognised she had been.',
      es: 'Itsuko Hasegawa se licenció en arquitectura por la Universidad Kanto Gakuin en 1964, trabajó con Kiyonori Kikutake y pasó luego siete años junto a Kazuo Shinohara en el Instituto Tecnológico de Tokio antes de abrir estudio propio en la ciudad. Describe su obra como «segunda naturaleza»: edificios que se comportan como paisaje y toman forma de cómo vive realmente una comunidad concreta. En la práctica eso significa pantallas de aluminio perforado, estructuras ligeras de acero y esferas y marquesinas metálicas montadas en algo más cercano a un parque que a un monumento. Mantuvo consultas insólitamente largas con los vecinos que se oponían al centro de Shōnandai y después dirigió diez años su museo infantil. En 2018 recibió el primer Premio de Arquitectura de la Royal Academy, cuyo jurado la llamó una de las arquitectas más importantes de Japón y señaló lo poco reconocida que había estado.',
      it: 'Itsuko Hasegawa si laureò in architettura alla Kanto Gakuin University nel 1964, lavorò con Kiyonori Kikutake e trascorse poi sette anni accanto a Kazuo Shinohara al Politecnico di Tokyo prima di aprire uno studio proprio in città. Descrive il suo lavoro come «seconda natura»: edifici che si comportano come paesaggio e prendono forma dal modo in cui una determinata comunità vive davvero. In pratica significa schermi di alluminio forato, leggere strutture d\'acciaio e sfere e pensiline metalliche montate in qualcosa di più simile a un parco che a un monumento. Condusse consultazioni insolitamente lunghe con gli abitanti che si opponevano al centro di Shōnandai e ne diresse poi per dieci anni il museo dei bambini. Nel 2018 ricevette il primo Royal Academy Architecture Prize, la cui giuria la definì una delle architette più importanti del Giappone rilevando quanto poco fosse stata riconosciuta.',
    },
    awards: [
      'Architectural Institute of Japan Design Prize (1986)',
      'BCS Prize (1992)',
      'Japan Art Academy Prize (2000)',
      'Royal Academy Architecture Prize (2018)',
      'Honorary Fellow, Royal Institute of British Architects',
    ],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q445298', title: 'Itsuko Hasegawa (Q445298)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Itsuko_Hasegawa', title: 'Itsuko Hasegawa', license: 'CC BY-SA 4.0' },
      { kind: 'institution', url: 'https://www.royalacademy.org.uk/page/architecture-awards-2018', title: 'RA Architecture Awards 2018 — Royal Academy of Arts', license: null },
    ],
  },
  {
    id: 'kazuyo-sejima',
    wikidataId: 'Q253350',
    name: 'Kazuyo Sejima',
    alternativeNames: ['妹島和世', 'Sejima Kazuyo'],
    gender: 'woman',
    born: 1956,
    died: null,
    floruit: { start: 1991, end: 2026, override: false },
    movements: [{ id: 'minimalism', primary: true }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'cultural',
    signatureMaterial: 'steel-and-glass',
    portrait: {
      en: 'Kazuyo Sejima took her master\'s degree at Japan Women\'s University in 1981, spent six years with Toyo Ito, and opened Kazuyo Sejima & Associates in 1987; in 1995 she and Ryue Nishizawa founded SANAA. The work is easy to recognise and hard to imitate: thin white planes, structure reduced until it stops being read as structure, glass without visible frames, plans that keep circulation ambiguous so a visitor chooses a route rather than following one. Buildings such as the Kanazawa museum, the Zollverein school in Essen, the New Museum in New York and the Rolex Learning Center in Lausanne treat lightness as a discipline rather than an effect. She received the Pritzker Prize with Nishizawa in 2010 and directed the Venice Architecture Biennale the same year.',
      es: 'Kazuyo Sejima obtuvo el máster en la Universidad Femenina de Japón en 1981, pasó seis años con Toyo Ito y abrió Kazuyo Sejima & Associates en 1987; en 1995 fundó SANAA junto a Ryue Nishizawa. Su obra es fácil de reconocer y difícil de imitar: planos blancos delgados, estructura reducida hasta dejar de leerse como estructura, vidrio sin carpintería visible y plantas que mantienen ambigua la circulación para que el visitante elija recorrido en lugar de seguir uno. Edificios como el museo de Kanazawa, la escuela de Zollverein en Essen, el New Museum de Nueva York o el Rolex Learning Center de Lausana tratan la ligereza como disciplina y no como efecto. Recibió el Premio Pritzker con Nishizawa en 2010 y ese mismo año dirigió la Bienal de Arquitectura de Venecia.',
      it: 'Kazuyo Sejima conseguì il master alla Japan Women\'s University nel 1981, trascorse sei anni con Toyo Ito e aprì Kazuyo Sejima & Associates nel 1987; nel 1995 fondò SANAA con Ryue Nishizawa. Il suo lavoro è facile da riconoscere e difficile da imitare: sottili piani bianchi, struttura ridotta fino a non leggersi più come struttura, vetro senza telai a vista, piante che tengono ambigua la circolazione perché il visitatore scelga un percorso invece di seguirne uno. Edifici come il museo di Kanazawa, la scuola di Zollverein a Essen, il New Museum di New York o il Rolex Learning Center di Losanna trattano la leggerezza come disciplina e non come effetto. Ha ricevuto il Premio Pritzker con Nishizawa nel 2010 e nello stesso anno ha diretto la Biennale di Architettura di Venezia.',
    },
    awards: [
      'Pritzker Architecture Prize (2010)',
      'Golden Lion, 9th Venice Architecture Biennale (2004)',
      'Rolf Schock Prize in Visual Arts',
      'Jane Drew Prize',
      'Officer of the Order of Arts and Letters',
    ],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q253350', title: 'Kazuyo Sejima (Q253350)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Kazuyo_Sejima', title: 'Kazuyo Sejima', license: 'CC BY-SA 4.0' },
      { kind: 'institution', url: 'https://www.pritzkerprize.com/laureates/2010', title: 'Kazuyo Sejima and Ryue Nishizawa — The Pritzker Architecture Prize', license: null },
    ],
  },
  {
    id: 'wang-shu',
    wikidataId: 'Q336620',
    name: 'Wang Shu',
    alternativeNames: ['王澍'],
    gender: 'man',
    born: 1963,
    died: null,
    floruit: { start: 1990, end: 2026, override: false },
    movements: [
      { id: 'critical-regionalism', primary: true },
      { id: 'sustainable-architecture', primary: false },
    ],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'cultural',
    signatureMaterial: 'mixed',
    portrait: {
      en: 'Wang Shu was born in Ürümqi, studied at what is now Southeast University in Nanjing, and completed his first building — a youth centre near Hangzhou — in 1990. He then took almost no commissions for eight years, working alongside craftsmen on site and studying for a doctorate at Tongji, completed in 2000. In 1997 he and Lu Wenyu founded Amateur Architecture Studio, the name a deliberate rebuke to the professionalised practice they blamed for the erasure of old Chinese neighbourhoods. Their buildings are made largely from what demolition leaves behind: salvaged brick and roof tile laid up in the regional wapan technique, concrete cast against bamboo, walls whose surface records a village that no longer exists. He is dean of architecture at the China Academy of Art in Hangzhou and won the Pritzker Prize in 2012.',
      es: 'Wang Shu nació en Ürümqi, estudió en la actual Universidad del Sudeste de Nankín y terminó su primer edificio —una casa de la juventud cerca de Hangzhou— en 1990. Después pasó casi ocho años sin apenas encargos, trabajando a pie de obra con artesanos y cursando un doctorado en Tongji, concluido en 2000. En 1997 fundó con Lu Wenyu el estudio Amateur Architecture, cuyo nombre es un reproche deliberado a la práctica profesionalizada a la que ambos atribuían la desaparición de los barrios antiguos chinos. Sus edificios se hacen en buena medida con lo que deja el derribo: ladrillo y teja recuperados y asentados con la técnica regional del wapan, hormigón encofrado contra bambú, muros cuya superficie registra una aldea que ya no existe. Dirige la escuela de arquitectura de la Academia China de Arte en Hangzhou y ganó el Premio Pritzker en 2012.',
      it: 'Wang Shu nacque a Ürümqi, studiò all\'attuale Università del Sud-est di Nanchino e completò il suo primo edificio — una casa della gioventù presso Hangzhou — nel 1990. Trascorse poi quasi otto anni quasi senza incarichi, lavorando in cantiere con gli artigiani e preparando un dottorato alla Tongji, concluso nel 2000. Nel 1997 fondò con Lu Wenyu lo studio Amateur Architecture, il cui nome è un rimprovero deliberato alla pratica professionalizzata cui entrambi imputavano la cancellazione dei vecchi quartieri cinesi. I loro edifici sono fatti in larga parte di ciò che la demolizione lascia: mattoni e tegole di recupero posati con la tecnica regionale del wapan, calcestruzzo gettato contro il bambù, murature la cui superficie registra un villaggio che non esiste più. È preside di architettura all\'Accademia Cinese d\'Arte di Hangzhou e ha vinto il Premio Pritzker nel 2012.',
    },
    awards: [
      'Pritzker Architecture Prize (2012)',
      'Global Award for Sustainable Architecture',
    ],
    tier: 'canon',
    context: {
      body: {
        en: 'Amateur Architecture Studio was founded in 1997 by Wang Shu together with Lu Wenyu, an architect and his wife, and the two have practised jointly since. The 2012 Pritzker Prize was awarded to Wang Shu alone. The omission of Lu Wenyu drew public criticism given their years of collaboration, and Wikidata records both of them as architects of the Ningbo Museum. The prize is awarded to individuals at the jury\'s discretion and has occasionally gone to partnerships — Herzog & de Meuron in 2001 and Sejima with Nishizawa in 2010 — which is why the single citation here was read as a choice rather than a rule.',
        es: 'El estudio Amateur Architecture fue fundado en 1997 por Wang Shu junto a Lu Wenyu, arquitecta y esposa suya, y ambos ejercen desde entonces conjuntamente. El Premio Pritzker de 2012 se concedió solo a Wang Shu. La omisión de Lu Wenyu suscitó críticas públicas dados sus años de colaboración, y Wikidata registra a los dos como arquitectos del Museo de Ningbo. El galardón se otorga a individuos según el criterio del jurado y en alguna ocasión ha recaído en sociedades —Herzog & de Meuron en 2001 y Sejima con Nishizawa en 2010—, razón por la cual aquella mención única se leyó como una elección y no como una norma.',
        it: 'Lo studio Amateur Architecture fu fondato nel 1997 da Wang Shu insieme a Lu Wenyu, architetta e sua moglie, e i due esercitano da allora congiuntamente. Il Premio Pritzker del 2012 fu assegnato al solo Wang Shu. L\'esclusione di Lu Wenyu suscitò critiche pubbliche, visti gli anni di collaborazione, e Wikidata registra entrambi come architetti del Museo di Ningbo. Il premio viene conferito a singoli secondo il giudizio della giuria e in qualche caso è andato a società — Herzog & de Meuron nel 2001 e Sejima con Nishizawa nel 2010 — ed è per questo che quella menzione unica fu letta come una scelta e non come una regola.',
      },
      sources: [
        { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Wang_Shu', title: 'Wang Shu', license: 'CC BY-SA 4.0' },
        { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q1070226', title: 'Ningbo Museum (Q1070226) — architect (P84)', license: null },
        { kind: 'institution', url: 'https://www.pritzkerprize.com/laureates/2012', title: 'Wang Shu — The Pritzker Architecture Prize', license: null },
      ],
    },
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q336620', title: 'Wang Shu (Q336620)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Wang_Shu', title: 'Wang Shu', license: 'CC BY-SA 4.0' },
      { kind: 'institution', url: 'https://www.pritzkerprize.com/laureates/2012', title: 'Wang Shu — The Pritzker Architecture Prize', license: null },
    ],
  },
];
