import type { Architect } from '@/types/architect';

// Wave 5 curator agent (India, Pakistan, Bangladesh, Sri Lanka, Nepal, Iran, Afghanistan): real, sourced Architect entries for this slice.
//
// Note on the record. Wikidata carries almost nothing for the modern architects
// of this region — Balkrishna Doshi has three attributed buildings with images,
// Geoffrey Bawa two, Minnette de Silva none — so most of the metadata below is
// hand-authored from published scholarship, institutional archives and the Aga
// Khan Award documentation, with the sources recorded on each entry.
export const ASIA_SOUTH_ARCHITECTS: Architect[] = [
  {
    id: 'ustad-ahmad-lahauri',
    wikidataId: 'Q2551253',
    name: 'Ustad Ahmad Lahauri',
    alternativeNames: ['Ahmad Lahori', 'Ustad Ahmad Mimar Lahori', "Nadir al-'Asr"],
    gender: 'man',
    born: 1580,
    died: 1649,
    floruit: { start: 1631, end: 1653, override: false },
    movements: [{ id: 'mughal', primary: true }, { id: 'timurid', primary: false }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'sacral',
    signatureMaterial: 'stone',
    portrait: {
      en: 'Chief architect to Shah Jahan and, by the testimony of his own family, the designer of the Taj Mahal. Ahmad Lahauri came from Lahore, held the honorific Nadir al-Asr — "wonder of the age" — and worked as a mathematician and engineer as much as a builder; the Red Fort at Delhi is also credited to him. The Taj attribution rests on the Persian writings of his son Lutfullah Muhandis, who lists his father as the author of both the Agra tomb and the Delhi palace-fort, and it remains the strongest name attached to the building, though some scholars treat Mughal authorship as collective workshop practice. What the buildings show is a geometer: hierarchies of proportion, a double shell dome, and a plan resolved to bilateral symmetry at every scale.',
      es: 'Arquitecto jefe de Shah Jahan y, según el testimonio de su propia familia, autor del Taj Mahal. Ahmad Lahauri procedía de Lahore, ostentaba el título honorífico de Nadir al-Asr —«prodigio de la época»— y trabajó tanto de matemático e ingeniero como de constructor; también se le atribuye el Fuerte Rojo de Delhi. La atribución del Taj descansa en los escritos persas de su hijo Lutfullah Muhandis, que nombra a su padre como autor de la tumba de Agra y del palacio-fortaleza de Delhi; sigue siendo el nombre más firme vinculado al edificio, aunque parte de la crítica entiende la autoría mogola como práctica colectiva de taller. Lo que revelan sus obras es un geómetra: jerarquías de proporción, cúpula de doble casco y una planta resuelta con simetría bilateral a todas las escalas.',
      it: "Architetto capo di Shah Jahan e, secondo la testimonianza della sua stessa famiglia, autore del Taj Mahal. Ahmad Lahauri veniva da Lahore, portava il titolo onorifico di Nadir al-Asr — «prodigio dell'epoca» — e lavorò da matematico e ingegnere non meno che da costruttore; gli si attribuisce anche il Forte Rosso di Delhi. L'attribuzione del Taj poggia sugli scritti persiani del figlio Lutfullah Muhandis, che indica il padre come autore sia della tomba di Agra sia del palazzo-fortezza di Delhi: resta il nome più solido legato all'edificio, benché parte degli studiosi consideri la paternità moghul una pratica collettiva di bottega. Ciò che le opere mostrano è un geometra: gerarchie di proporzione, cupola a doppio guscio e una pianta risolta in simmetria bilaterale a ogni scala.",
    },
    awards: [],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q2551253', title: 'Ahmad Lahori (Q2551253)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Ustad_Ahmad_Lahori', title: 'Ustad Ahmad Lahori', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'ali-akbar-isfahani',
    wikidataId: 'Q29508194',
    name: 'Ali Akbar Isfahani',
    alternativeNames: ['Ostad Ali Akbar Isfahani', 'Ali Akbar Esfahani'],
    gender: 'man',
    born: null,
    died: null,
    floruit: { start: 1611, end: 1638, override: false },
    movements: 'unaffiliated',
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'sacral',
    signatureMaterial: 'brick',
    portrait: {
      en: 'The architect of the Shah Mosque at Isfahan, and one of the few Safavid builders whose name survives on the work itself: an inscription above the doorway of the entrance iwan names him, alongside Muhibb Ali Beg Lala as supervisor and donor. Almost nothing else about his life is recorded. The mosque credits him with the period’s hardest planning problem — a portal fixed to the axis of Shah Abbas’s new maidan and a prayer hall that must face Mecca — solved by turning the whole courtyard forty-five degrees behind the screen of the entrance. He is given no movement label here because the vocabulary available to this pool has no Safavid or Persian term, and inventing one to tidy the mechanic would misdescribe a tradition with its own lineage.',
      es: 'Arquitecto de la Mezquita del Sah en Isfahán y uno de los pocos constructores safávidas cuyo nombre sobrevive en la propia obra: una inscripción sobre la puerta del iwán de acceso lo nombra, junto a Muhibb Ali Beg Lala como supervisor y donante. Apenas se conserva otro dato de su vida. La mezquita le acredita el problema de planta más difícil de la época —un portal fijado al eje del nuevo maidán de Shah Abbas y una sala de oración que debe mirar a La Meca—, resuelto girando cuarenta y cinco grados todo el patio detrás del telón del portal. No se le asigna aquí ninguna etiqueta de movimiento porque el vocabulario disponible en este repertorio carece de término safávida o persa, e inventar uno para redondear la mecánica falsearía una tradición con linaje propio.',
      it: "Architetto della Moschea dello Shah a Isfahan e uno dei pochi costruttori safavidi il cui nome sopravvive sull'opera stessa: un'iscrizione sopra la porta dell'iwan d'ingresso lo nomina, insieme a Muhibb Ali Beg Lala come sovrintendente e donatore. Della sua vita non resta quasi nient'altro. La moschea gli riconosce il problema planimetrico più arduo dell'epoca — un portale vincolato all'asse del nuovo maidan di Shah Abbas e una sala di preghiera che deve guardare alla Mecca — risolto ruotando di quarantacinque gradi l'intera corte dietro il diaframma del portale. Qui non gli si assegna alcuna etichetta di movimento: il vocabolario di questo repertorio non ha un termine safavide o persiano, e inventarne uno per ordinare il meccanismo traviserebbe una tradizione con una propria discendenza.",
    },
    awards: [],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q29508194', title: 'Ali Akbar Isfahani (Q29508194)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Shah_Mosque_(Isfahan)', title: 'Shah Mosque (Isfahan)', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'fidai-khan-koka',
    wikidataId: 'Q30023941',
    name: 'Fidai Khan Koka',
    alternativeNames: ['Muzaffar Hussain', 'Fidai Khan', 'Nawab Fidai Khan Koka'],
    gender: 'man',
    born: null,
    died: 1685,
    floruit: { start: 1671, end: 1673, override: false },
    movements: [{ id: 'mughal', primary: true }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'sacral',
    signatureMaterial: 'stone',
    portrait: {
      en: 'Foster-brother to the emperor Aurangzeb, Master of Ordnance, and from 1671 governor of Lahore, Fidai Khan Koka is the name the record attaches to the Badshahi Mosque. His title is an imperial office rather than a professional one, and what he did is better described as directing the design and construction than drawing it; Mughal practice made no clean division between the two. The commission was extraordinary by any measure — the largest mosque the dynasty ever built, raised in roughly two years to face the Lahore Fort across a shared forecourt, its scale calculated as an answer to his half-brother’s Jama Masjid at Delhi. He is included here because the attribution is documented and because omitting patron-builders would erase most named authorship in Mughal architecture.',
      es: 'Hermano de leche del emperador Aurangzeb, jefe de la artillería imperial y, desde 1671, gobernador de Lahore, Fidai Khan Koka es el nombre que la documentación asocia a la Mezquita Badshahi. Su título designa un cargo imperial y no una profesión, y lo que hizo se describe mejor como dirigir el proyecto y la obra que como dibujarlos; la práctica mogola no separaba con nitidez ambas cosas. El encargo fue extraordinario en cualquier medida: la mayor mezquita construida por la dinastía, levantada en unos dos años frente al Fuerte de Lahore sobre una explanada compartida, con una escala calculada como respuesta a la Jama Masjid de Delhi. Se incluye aquí porque la atribución está documentada y porque excluir a los constructores-mecenas borraría casi toda la autoría con nombre de la arquitectura mogola.',
      it: "Fratello di latte dell'imperatore Aurangzeb, capo dell'artiglieria imperiale e dal 1671 governatore di Lahore, Fidai Khan Koka è il nome che la documentazione lega alla Moschea Badshahi. Il suo titolo indica una carica imperiale, non una professione, e ciò che fece si descrive meglio come dirigere il progetto e il cantiere che come disegnarli; la prassi moghul non separava nettamente le due cose. La commessa fu straordinaria sotto ogni misura: la più grande moschea mai costruita dalla dinastia, eretta in circa due anni di fronte al Forte di Lahore su uno spiazzo condiviso, con una scala calcolata come risposta alla Jama Masjid di Delhi. È incluso qui perché l'attribuzione è documentata e perché escludere i costruttori-committenti cancellerebbe quasi ogni paternità con nome dell'architettura moghul.",
    },
    awards: [],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q30023941', title: 'Muzaffar Hussain (Fidai Khan Koka) (Q30023941)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Fidai_Khan_Koka', title: 'Fidai Khan Koka', license: 'CC BY-SA 4.0' },
      { kind: 'institution', url: 'https://archaeology.punjab.gov.pk/badshahi_mosque', title: 'Badshahi Mosque — Directorate General of Archaeology, Government of the Punjab', license: null },
    ],
  },
  {
    id: 'edwin-lutyens',
    wikidataId: 'Q378157',
    name: 'Edwin Lutyens',
    alternativeNames: ['Sir Edwin Landseer Lutyens', 'Edwin Landseer Lutyens'],
    gender: 'man',
    born: 1869,
    died: 1944,
    floruit: { start: 1897, end: 1935, override: false },
    movements: [{ id: 'neoclassicism', primary: true }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'civic',
    signatureMaterial: 'stone',
    portrait: {
      en: 'English architect who began in the Surrey vernacular of tile and timber, moved to a rigorous classicism he called “the high game”, and spent twenty years travelling between London and Delhi to build the capital of British India. Lutyens laid out the central administrative precinct of New Delhi with Herbert Baker from 1912 and designed the Viceroy’s House at its head; the two quarrelled bitterly over the gradient of the approach, which Lutyens lost. His invented “Delhi Order” grafted Indian elements — the deep shading chujja, chhatri kiosks, a dome derived from the stupa at Sanchi — onto a classical armature. He is claimed here because New Delhi is the work in question; his London practice may equally place him with the British slice, and the pool should carry only one definition of him.',
      es: 'Arquitecto inglés que empezó en el vernáculo de teja y madera de Surrey, derivó hacia un clasicismo riguroso que él llamaba «el juego mayor» y pasó veinte años viajando entre Londres y Delhi para construir la capital de la India británica. Lutyens trazó con Herbert Baker el recinto administrativo central de Nueva Delhi desde 1912 y proyectó a su cabecera la Casa del Virrey; ambos riñeron agriamente por la pendiente del acceso, pleito que Lutyens perdió. Su «orden de Delhi» injertó elementos indios —el chujja de sombra profunda, los quioscos chhatri, una cúpula derivada de la estupa de Sanchi— sobre un armazón clásico. Se le define aquí porque Nueva Delhi es la obra en juego; su estudio londinense podría situarlo igualmente en el lote británico, y el repertorio debe conservar una sola definición suya.',
      it: "Architetto inglese che esordì nel vernacolo di tegole e legno del Surrey, approdò a un classicismo rigoroso che chiamava «il gioco grande» e passò vent'anni viaggiando fra Londra e Delhi per costruire la capitale dell'India britannica. Dal 1912 Lutyens tracciò con Herbert Baker il comparto amministrativo centrale di Nuova Delhi e ne progettò in testa la Casa del Viceré; i due litigarono aspramente sulla pendenza dell'accesso, contesa che Lutyens perse. Il suo «ordine di Delhi» innestò elementi indiani — il chujja di ombra profonda, i chioschi chhatri, una cupola derivata dallo stupa di Sanchi — su un'ossatura classica. È definito qui perché l'opera in questione è Nuova Delhi; lo studio londinese potrebbe collocarlo nella fetta britannica, e il repertorio deve conservarne una sola definizione.",
    },
    awards: ['Royal Gold Medal (1921)', 'Order of Merit (1942)', 'President of the Royal Academy (1938)'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q378157', title: 'Edwin Lutyens (Q378157)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Edwin_Lutyens', title: 'Edwin Lutyens', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: "https://en.wikipedia.org/wiki/Lutyens'_Delhi", title: "Lutyens' Delhi", license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'frederick-william-stevens',
    wikidataId: 'Q5499109',
    name: 'Frederick William Stevens',
    alternativeNames: ['F. W. Stevens'],
    gender: 'man',
    born: 1847,
    died: 1900,
    floruit: { start: 1878, end: 1900, override: false },
    movements: [{ id: 'gothic-revival', primary: true }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'infrastructure',
    signatureMaterial: 'stone',
    portrait: {
      en: 'Bath-born architect who joined the Indian Public Works Department at twenty and spent the rest of his life in Bombay, where he died in 1900. Stevens gave the city the face it still has: Victoria Terminus, the Municipal Corporation Building across the road from it, Churchgate Station and the Oriental Life Assurance Building. His method was to take the polychrome structural Gothic of Ruskin and Scott and let Indian craftsmen carve it — foliage, animals, peacocks and monkeys drawn from local ornament — over an iron-and-stone frame. The results are neither English nor Indian but the specific hybrid the Raj built with, and Bombay is where that hybrid was most confidently made. He is defined in this slice because his entire practice was based in the city his buildings shaped.',
      es: 'Arquitecto nacido en Bath que ingresó a los veinte años en el Departamento de Obras Públicas de la India y pasó el resto de su vida en Bombay, donde murió en 1900. Stevens dio a la ciudad el rostro que aún conserva: Victoria Terminus, el edificio de la Corporación Municipal frente a él, la estación de Churchgate y la Oriental Life Assurance. Su método consistía en tomar el gótico estructural y policromo de Ruskin y Scott y dejar que lo tallaran artesanos indios —follaje, animales, pavos reales y monos tomados del ornamento local— sobre un armazón de hierro y piedra. El resultado no es inglés ni indio, sino el híbrido concreto con que construyó el Raj, y Bombay es donde ese híbrido se ejecutó con mayor aplomo. Se define en este lote porque toda su práctica tuvo base en la ciudad que sus obras modelaron.',
      it: "Architetto nato a Bath, entrò a vent'anni nel Dipartimento dei Lavori Pubblici dell'India e passò il resto della vita a Bombay, dove morì nel 1900. Stevens diede alla città il volto che ancora conserva: Victoria Terminus, il palazzo della Corporazione municipale di fronte, la stazione di Churchgate e l'Oriental Life Assurance. Il suo metodo fu prendere il gotico strutturale e policromo di Ruskin e Scott e lasciarlo intagliare a maestranze indiane — fogliami, animali, pavoni e scimmie tratti dall'ornato locale — su un'ossatura di ferro e pietra. L'esito non è né inglese né indiano, ma l'ibrido specifico con cui costruì il Raj, e Bombay è il luogo dove quell'ibrido fu realizzato con maggiore sicurezza. È definito in questa fetta perché tutta la sua attività ebbe sede nella città che le sue opere hanno plasmato.",
    },
    awards: ['Companion of the Order of the Indian Empire (1898)'],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q5499109', title: 'Frederick William Stevens (Q5499109)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Frederick_William_Stevens', title: 'Frederick William Stevens', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'walter-harten',
    wikidataId: '',
    name: 'Walter Harten',
    alternativeNames: ['Walter Harten (engineer)'],
    gender: 'man',
    born: null,
    died: null,
    floruit: { start: 1925, end: 1927, override: false },
    movements: [{ id: 'neoclassicism', primary: true }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'civic',
    signatureMaterial: 'stone',
    portrait: {
      en: 'German engineer credited with the design of the Darul Aman Palace at Kabul, built for Amanullah Khan between 1925 and 1927 as the centrepiece of a new capital. Harten led a team of engineers within a larger group of twenty-two German and French architects the king invited to Afghanistan; French architects named in the record as A. and M. Godard are also credited with the design, so the authorship is shared rather than single. He has no Wikidata entity and almost no biography in the published literature — a gap recorded here rather than filled in, since the alternative was to leave Afghanistan out of this pool entirely. What survives of his work is a thirty-metre neoclassical block that outlived the reform programme it was built to announce.',
      es: 'Ingeniero alemán a quien se atribuye el proyecto del Palacio Darul Aman de Kabul, construido para Amanullah Khan entre 1925 y 1927 como pieza central de una nueva capital. Harten dirigió un equipo de ingenieros dentro del grupo mayor de veintidós arquitectos alemanes y franceses que el rey invitó a Afganistán; la documentación menciona también a los arquitectos franceses A. y M. Godard como autores, de modo que la autoría es compartida y no única. Carece de entidad en Wikidata y de biografía apenas en la literatura publicada: una laguna que aquí se consigna en vez de rellenarse, porque la alternativa era dejar Afganistán fuera de este repertorio. De su trabajo queda un bloque neoclásico de treinta metros que sobrevivió al programa reformista que debía anunciar.',
      it: "Ingegnere tedesco cui si attribuisce il progetto del Palazzo Darul Aman di Kabul, costruito per Amanullah Khan fra il 1925 e il 1927 come fulcro di una nuova capitale. Harten guidò una squadra di ingegneri dentro il gruppo più ampio di ventidue architetti tedeschi e francesi che il re invitò in Afghanistan; la documentazione cita anche gli architetti francesi A. e M. Godard fra gli autori, sicché la paternità è condivisa e non unica. Non ha una scheda Wikidata e quasi nessuna biografia nella letteratura pubblicata: una lacuna qui registrata anziché colmata, perché l'alternativa era lasciare l'Afghanistan fuori da questo repertorio. Del suo lavoro resta un blocco neoclassico di trenta metri sopravvissuto al programma riformista che doveva annunciare.",
    },
    awards: [],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Darul_Aman_Palace', title: 'Darul Aman Palace', license: 'CC BY-SA 4.0' },
      { kind: 'institution', url: 'https://www.archnet.org/sites/2735', title: 'Darulaman Palace — Archnet, Aga Khan Documentation Center', license: null },
    ],
  },
  {
    id: 'edith-langridge',
    wikidataId: 'Q18671015',
    name: 'Edith Langridge',
    alternativeNames: ['Mother Edith', 'Sister Edith Langridge'],
    gender: 'woman',
    born: 1864,
    died: 1959,
    floruit: { start: 1903, end: 1907, override: false },
    movements: 'unaffiliated',
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'sacral',
    signatureMaterial: 'brick',
    portrait: {
      en: 'A classicist from Lady Margaret Hall who wanted to be a missionary in Africa, learned Swahili for it, and was sent instead to Barishal in eastern Bengal. Langridge founded the Sisterhood of the Epiphany there in 1902 and led it for four decades as Mother Edith, running schools, an orphanage in Calcutta and medical work for women. The Epiphany Church at Barishal — one of the largest churches in Asia — was built from her sketch, inaugurated in 1903, and completed in a second phase overseen by Father E. L. Strong in 1907; the two are named together as its architects. She had no architectural training, which is precisely why she appears in almost no history of the building: an unschooled woman’s drawing is the kind of authorship the record loses first.',
      es: 'Filóloga clásica formada en Lady Margaret Hall que quiso ser misionera en África, aprendió suajili para ello y fue destinada en cambio a Barishal, en Bengala oriental. Allí fundó en 1902 la Sisterhood of the Epiphany y la dirigió cuatro décadas como Mother Edith, con escuelas, un orfanato en Calcuta y asistencia médica a mujeres. La iglesia de la Epifanía de Barishal —una de las mayores de Asia— se levantó a partir de un croquis suyo, se inauguró en 1903 y se terminó en una segunda fase supervisada por el padre E. L. Strong en 1907; ambos figuran juntos como sus arquitectos. No tuvo formación arquitectónica, y precisamente por eso apenas aparece en la historia del edificio: el dibujo de una mujer sin título es la clase de autoría que la documentación pierde antes.',
      it: "Classicista formatasi a Lady Margaret Hall, voleva farsi missionaria in Africa, imparò lo swahili a tale scopo e fu invece inviata a Barishal, nel Bengala orientale. Lì fondò nel 1902 la Sisterhood of the Epiphany e la guidò per quarant'anni come Mother Edith, fra scuole, un orfanotrofio a Calcutta e assistenza medica alle donne. La chiesa dell'Epifania di Barishal — una delle più grandi dell'Asia — nacque da un suo schizzo, fu inaugurata nel 1903 e completata in una seconda fase diretta da padre E. L. Strong nel 1907; i due sono citati insieme come architetti. Non aveva formazione architettonica, ed è proprio per questo che compare quasi mai nella storia dell'edificio: il disegno di una donna senza titolo è il tipo di paternità che la documentazione perde per prima.",
    },
    awards: [],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q18671015', title: 'Edith Langridge (Q18671015)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Edith_Langridge', title: 'Edith Langridge', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Oxford_Mission_Church', title: 'Oxford Mission Church', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'balkrishna-doshi',
    wikidataId: 'Q380449',
    name: 'Balkrishna Doshi',
    alternativeNames: ['Balkrishna Vithaldas Doshi', 'B. V. Doshi'],
    gender: 'man',
    born: 1927,
    died: 2023,
    floruit: { start: 1958, end: 2014, override: false },
    movements: [{ id: 'critical-regionalism', primary: true }, { id: 'brutalism', primary: false }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'educational',
    signatureMaterial: 'concrete',
    portrait: {
      en: 'Born in Pune, trained in Bombay, four years in Le Corbusier’s Paris atelier from 1951, then sent home to supervise the Ahmedabad projects — and he stayed, building for sixty years in a country he thought European modernism had never really looked at. Doshi founded Vastu-Shilpa in 1955 and the school that became CEPT in 1962, and worked out an architecture of shaded outdoor rooms: the covered street, the terraced courtyard, the vault half-buried against the heat. Aranya low-cost housing at Indore, IIM Bangalore, Sangath, Amdavad ni Gufa. He was the first Indian architect to win the Pritzker Prize, in 2018, at ninety, and said of the honour that it reminded him of his teacher. His work is unfailingly generous about shade, water and how people actually gather.',
      es: 'Nacido en Pune, formado en Bombay, cuatro años en el taller parisino de Le Corbusier desde 1951 y luego enviado a casa para supervisar las obras de Ahmedabad — y allí se quedó, construyendo sesenta años en un país que, según él, el modernismo europeo nunca había mirado de verdad. Doshi fundó Vastu-Shilpa en 1955 y la escuela que sería el CEPT en 1962, y elaboró una arquitectura de estancias exteriores a la sombra: la calle cubierta, el patio aterrazado, la bóveda medio enterrada contra el calor. La vivienda económica de Aranya en Indore, el IIM de Bangalore, Sangath, Amdavad ni Gufa. Fue el primer arquitecto indio en recibir el Pritzker, en 2018, con noventa años, y dijo que el premio le recordaba a su maestro. Su obra es siempre generosa con la sombra, el agua y el modo real de reunirse la gente.',
      it: 'Nato a Pune, formato a Bombay, quattro anni nell’atelier parigino di Le Corbusier dal 1951 e poi rimandato in patria a seguire i cantieri di Ahmedabad — e lì rimase, costruendo per sessant’anni in un paese che a suo giudizio il modernismo europeo non aveva mai davvero guardato. Doshi fondò Vastu-Shilpa nel 1955 e la scuola che sarebbe diventata il CEPT nel 1962, elaborando un’architettura di stanze all’aperto in ombra: la strada coperta, la corte terrazzata, la volta seminterrata contro il calore. Le case a basso costo di Aranya a Indore, l’IIM di Bangalore, Sangath, Amdavad ni Gufa. Fu il primo architetto indiano a ricevere il Pritzker, nel 2018, a novant’anni, e disse che il premio gli ricordava il suo maestro. La sua opera è sempre generosa con l’ombra, l’acqua e il modo in cui la gente si raduna davvero.',
    },
    awards: ['Pritzker Architecture Prize (2018)', 'Royal Gold Medal (2022)', 'Padma Bhushan (2020)', 'Padma Shri (1976)', 'Aga Khan Award for Architecture (1993–1995, Aranya Community Housing)'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q380449', title: 'Balkrishna Doshi (Q380449)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Balkrishna_Doshi', title: 'Balkrishna Doshi', license: 'CC BY-SA 4.0' },
      { kind: 'institution', url: 'https://www.pritzkerprize.com/laureates/balkrishna-doshi', title: 'Balkrishna Doshi — 2018 Pritzker Architecture Prize Laureate', license: null },
    ],
  },
  {
    id: 'charles-correa',
    wikidataId: 'Q699145',
    name: 'Charles Correa',
    alternativeNames: ['Charles Mark Correa'],
    gender: 'man',
    born: 1930,
    died: 2015,
    floruit: { start: 1963, end: 2010, override: false },
    movements: [{ id: 'critical-regionalism', primary: true }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'cultural',
    signatureMaterial: 'concrete',
    portrait: {
      en: 'Correa trained at Michigan and MIT and came back to Bombay in 1958 with a question that occupied him for the rest of his life: what does a warm climate do to a plan? His answer was the open-to-sky space — terrace, courtyard, stepped section — treated as a room rather than a leftover, and he pursued it from the Gandhi Smarak Sangrahalaya at Ahmedabad to the Kanchanjunga Apartments and the Jawahar Kala Kendra. He was equally an urbanist: chief architect of New Bombay from 1970, chair of the National Commission on Urbanisation, and a lifelong writer on how cities fail the poor. Late work took the Vedic mandala not as decoration but as a plan-generating diagram. He received the Royal Gold Medal in 1984 and the Praemium Imperiale in 1994.',
      es: 'Correa se formó en Michigan y el MIT y volvió a Bombay en 1958 con una pregunta que lo ocupó el resto de su vida: ¿qué le hace un clima cálido a una planta? Su respuesta fue el espacio abierto al cielo —terraza, patio, sección escalonada— tratado como una estancia y no como un sobrante, y la persiguió desde el Gandhi Smarak Sangrahalaya de Ahmedabad hasta los apartamentos Kanchanjunga y el Jawahar Kala Kendra. Fue también urbanista: arquitecto jefe de Nueva Bombay desde 1970, presidente de la Comisión Nacional de Urbanización y autor constante sobre cómo las ciudades fallan a los pobres. Su obra tardía tomó el mandala védico no como decoración sino como diagrama generador de la planta. Recibió la Royal Gold Medal en 1984 y el Praemium Imperiale en 1994.',
      it: 'Correa si formò al Michigan e al MIT e tornò a Bombay nel 1958 con una domanda che lo occupò per tutta la vita: che cosa fa un clima caldo a una pianta? La sua risposta fu lo spazio aperto al cielo — terrazza, corte, sezione a gradoni — trattato come una stanza e non come un residuo, e la inseguì dal Gandhi Smarak Sangrahalaya di Ahmedabad fino agli appartamenti Kanchanjunga e al Jawahar Kala Kendra. Fu anche urbanista: architetto capo di Nuova Bombay dal 1970, presidente della Commissione nazionale per l’urbanizzazione e autore instancabile su come le città tradiscano i poveri. L’opera tarda assunse il mandala vedico non come decoro ma come diagramma generatore della pianta. Ricevette la Royal Gold Medal nel 1984 e il Praemium Imperiale nel 1994.',
    },
    awards: ['Royal Gold Medal (1984)', 'Praemium Imperiale (1994)', 'Padma Vibhushan (2006)', 'Padma Shri (1972)', 'Aga Khan Award for Architecture (1998)'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q699145', title: 'Charles Correa (Q699145)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Charles_Correa', title: 'Charles Correa', license: 'CC BY-SA 4.0' },
      { kind: 'institution', url: 'https://charlescorreafoundation.org/2022/02/23/jawahar-kala-kendra/', title: 'Jawahar Kala Kendra — Charles Correa Foundation', license: null },
    ],
  },
  {
    id: 'geoffrey-bawa',
    wikidataId: 'Q3610582',
    name: 'Geoffrey Bawa',
    alternativeNames: ['Geoffrey Manning Bawa'],
    gender: 'man',
    born: 1919,
    died: 2003,
    floruit: { start: 1958, end: 1998, override: false },
    movements: [{ id: 'tropical-modernism', primary: true }, { id: 'critical-regionalism', primary: false }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'commercial',
    signatureMaterial: 'concrete',
    portrait: {
      en: 'Bawa qualified as a barrister in London, bought a derelict rubber estate at Bentota in 1948 meaning to make an Italian garden of it, discovered he did not know how, and went back to England at thirty-eight to train as an architect. Lunuganga became the forty-year laboratory. From Colombo he then built the case for tropical modernism as a way of thinking rather than a style: rooms with no fourth wall, courtyards that ventilate, roofs that shade, a route through a building composed like a garden walk. Parliament at Kotte, Seema Malaka, the Ruhuna campus, the Kandalama hotel. He received the Aga Khan Chairman’s Award in 2001. His practice is the reason Sri Lankan architecture is discussed at all outside Sri Lanka.',
      es: 'Bawa se hizo abogado en Londres, compró en 1948 una plantación de caucho arruinada en Bentota con la idea de convertirla en un jardín italiano, descubrió que no sabía hacerlo y volvió a Inglaterra a los treinta y ocho a estudiar arquitectura. Lunuganga fue el laboratorio de cuarenta años. Desde Colombo defendió después el modernismo tropical como forma de pensar y no como estilo: estancias sin cuarta pared, patios que ventilan, cubiertas que dan sombra, un recorrido por el edificio compuesto como un paseo de jardín. El Parlamento de Kotte, Seema Malaka, el campus de Ruhuna, el hotel Kandalama. Recibió el Premio del Presidente del Aga Khan en 2001. Su obra es la razón por la que se habla de arquitectura cingalesa fuera de Sri Lanka.',
      it: 'Bawa si abilitò avvocato a Londra, nel 1948 comprò a Bentota una piantagione di caucciù in rovina con l’idea di farne un giardino italiano, scoprì di non saperlo fare e tornò in Inghilterra a trentotto anni per studiare architettura. Lunuganga divenne il laboratorio di quarant’anni. Da Colombo sostenne poi il modernismo tropicale come modo di pensare e non come stile: stanze senza quarta parete, corti che ventilano, coperture che ombreggiano, un percorso nell’edificio composto come una passeggiata in giardino. Il Parlamento di Kotte, Seema Malaka, il campus di Ruhuna, l’albergo Kandalama. Ricevette il Premio del Presidente dell’Aga Khan nel 2001. La sua opera è la ragione per cui dell’architettura singalese si parla fuori dallo Sri Lanka.',
    },
    awards: ['Aga Khan Chairman’s Award for Architecture (2001)', 'Deshamanya (1993)', 'Sri Lanka Institute of Architects Gold Medal (1982)'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q3610582', title: 'Geoffrey Bawa (Q3610582)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Geoffrey_Bawa', title: 'Geoffrey Bawa', license: 'CC BY-SA 4.0' },
      { kind: 'institution', url: 'https://www.archnet.org/sites/3041', title: 'Kandalama Hotel — Archnet, Aga Khan Documentation Center', license: null },
    ],
  },
  {
    id: 'yahya-merchant',
    wikidataId: 'Q8046928',
    name: 'Yahya Merchant',
    alternativeNames: ['Yahya C. Merchant', 'Yahya Chandbhai Merchant'],
    gender: 'man',
    born: 1903,
    died: 1990,
    floruit: { start: 1960, end: 1975, override: false },
    movements: 'unaffiliated',
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'civic',
    signatureMaterial: 'stone',
    portrait: {
      en: 'A Bombay architect of the Dawoodi Bohra community whose best-known commission came from across a border he did not cross to live. Merchant was a personal friend of Muhammad Ali Jinnah; when Fatima Jinnah took control of the memorial fund and vetoed the 1957 competition result, she commissioned him directly to design her brother’s mausoleum at Karachi. He also built the Raudat Tahera in Mumbai for Syedna Taher Saifuddin and the Anna Nagar tower at Chennai. His work sits deliberately between idioms — a traditional funerary geometry stripped of ornament and set on a modern reinforced frame — and no movement label is applied to him here, because the published record does not support one and inventing one would tidy away exactly what makes the buildings odd.',
      es: 'Arquitecto bombayeño de la comunidad dawoodi bohra cuyo encargo más conocido llegó desde el otro lado de una frontera que no cruzó para vivir. Merchant era amigo personal de Muhammad Ali Jinnah; cuando Fatima Jinnah tomó el control del fondo conmemorativo y vetó el resultado del concurso de 1957, le encargó directamente el mausoleo de su hermano en Karachi. Construyó también la Raudat Tahera de Bombay para Syedna Taher Saifuddin y la torre de Anna Nagar en Chennai. Su obra se sitúa deliberadamente entre lenguajes —una geometría funeraria tradicional despojada de ornamento sobre una estructura moderna de hormigón armado— y aquí no se le aplica etiqueta de movimiento, porque la documentación publicada no la sostiene e inventarla borraría justo lo que hace extraños a estos edificios.',
      it: 'Architetto di Bombay della comunità dawoodi bohra, la cui commessa più nota gli venne da oltre un confine che non varcò per andarci a vivere. Merchant era amico personale di Muhammad Ali Jinnah; quando Fatima Jinnah prese il controllo del fondo commemorativo e pose il veto all’esito del concorso del 1957, gli affidò direttamente il mausoleo del fratello a Karachi. Costruì anche la Raudat Tahera a Mumbai per Syedna Taher Saifuddin e la torre di Anna Nagar a Chennai. La sua opera sta deliberatamente fra i linguaggi — una geometria funeraria tradizionale spogliata di ornato su un’ossatura moderna in cemento armato — e qui non gli si applica alcuna etichetta di movimento, perché la documentazione pubblicata non la sostiene e inventarla cancellerebbe proprio ciò che rende strani questi edifici.',
    },
    awards: [],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q8046928', title: 'Yahya Merchant (Q8046928)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Yahya_Merchant', title: 'Yahya Merchant', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Mazar-e-Quaid', title: 'Mazar-e-Quaid', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'muzharul-islam',
    wikidataId: 'Q6944447',
    name: 'Muzharul Islam',
    alternativeNames: ['Mazharul Islam', 'Muzharul Islam Chowdhury'],
    gender: 'man',
    born: 1923,
    died: 2012,
    floruit: { start: 1955, end: 1990, override: false },
    movements: [{ id: 'tropical-modernism', primary: true }, { id: 'brutalism', primary: false }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'educational',
    signatureMaterial: 'brick',
    portrait: {
      en: 'The founder of modern architecture in Bangladesh, and the man who decided the country should not build it alone. Trained in Dhaka, Oregon and at the Architectural Association, Islam returned in the 1950s and set the terms with the Faculty of Fine Arts at Dhaka University: brick, deep verandahs, a plan that runs with the monsoon rather than against it. He then used his standing to bring Louis Kahn, Paul Rudolph, Richard Neutra, Stanley Tigerman and Constantinos Doxiadis to work in East Pakistan — it was Islam who steered the National Assembly commission to Kahn rather than keep it. His own campuses at Chittagong and Jahangirnagar step down their hillsides in staggered terraces. He was also a political activist, and his work is on Bangladesh’s World Heritage tentative list.',
      es: 'Fundador de la arquitectura moderna en Bangladesh y el hombre que decidió que el país no debía construirla solo. Formado en Dacca, Oregón y la Architectural Association, Islam volvió en los años cincuenta y fijó las reglas con la Facultad de Bellas Artes de la Universidad de Dacca: ladrillo, galerías profundas, una planta que corre a favor del monzón y no en su contra. Usó luego su prestigio para traer a Louis Kahn, Paul Rudolph, Richard Neutra, Stanley Tigerman y Constantinos Doxiadis a trabajar en Pakistán Oriental —fue él quien derivó a Kahn el encargo de la Asamblea Nacional en lugar de quedárselo—. Sus campus de Chittagong y Jahangirnagar bajan por la ladera en terrazas escalonadas. Fue también activista político, y su obra figura en la lista indicativa de Patrimonio Mundial de Bangladesh.',
      it: 'Il fondatore dell’architettura moderna in Bangladesh, e l’uomo che decise che il paese non dovesse costruirla da solo. Formatosi a Dacca, in Oregon e alla Architectural Association, Islam tornò negli anni Cinquanta e fissò le regole con la Facoltà di Belle Arti dell’Università di Dacca: mattone, verande profonde, una pianta che asseconda il monsone invece di contrastarlo. Usò poi il proprio prestigio per portare Louis Kahn, Paul Rudolph, Richard Neutra, Stanley Tigerman e Constantinos Doxiadis a lavorare nel Pakistan orientale — fu lui a dirottare su Kahn la commessa dell’Assemblea nazionale anziché tenerla. I suoi campus di Chittagong e Jahangirnagar scendono lungo il pendio in terrazze sfalsate. Fu anche attivista politico, e la sua opera figura nella lista propositiva del Patrimonio Mondiale del Bangladesh.',
    },
    awards: ['Independence Day Award (1999)', 'Ekushey Padak (1972)'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q6944447', title: 'Muzharul Islam (Q6944447)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Muzharul_Islam', title: 'Muzharul Islam', license: 'CC BY-SA 4.0' },
      { kind: 'institution', url: 'https://whc.unesco.org/en/tentativelists/6674/', title: 'The Architectural Works of Muzharul Islam — UNESCO World Heritage Centre Tentative List', license: null },
      { kind: 'institution', url: 'https://en.banglapedia.org/index.php/Islam,_Muzharul', title: 'Islam, Muzharul — Banglapedia', license: null },
    ],
  },
  {
    id: 'marina-tabassum',
    wikidataId: 'Q27451427',
    name: 'Marina Tabassum',
    alternativeNames: ['Marina Tabassum Architects'],
    gender: 'woman',
    born: 1968,
    died: null,
    floruit: { start: 1997, end: 2025, override: false },
    movements: [{ id: 'critical-regionalism', primary: true }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'sacral',
    signatureMaterial: 'brick',
    portrait: {
      en: 'Tabassum graduated from BUET in 1995, co-founded URBANA with Kashef Chowdhury in 1995, and won the competition for the Independence Monument and Liberation War Museum at Dhaka two years later; the pair carried that project for sixteen years. Since setting up her own studio in 2005 she has worked almost entirely with handmade brick, daylight and the flood-prone delta ground of Bangladesh. She has won the Aga Khan Award for Architecture twice — in 2016 for the Bait Ur Rouf Mosque, commissioned by her grandmother, and in 2025 for Khudi Bari, a demountable bamboo house for families displaced by river erosion. Time listed her among its hundred most influential people in 2024. She is one of very few women to have designed a mosque anywhere in South Asia.',
      es: 'Tabassum se graduó en la BUET en 1995, cofundó URBANA con Kashef Chowdhury ese mismo año y dos después ganó el concurso del Monumento a la Independencia y Museo de la Guerra de Liberación de Dacca; ambos sostuvieron ese proyecto durante dieciséis años. Desde que abrió estudio propio en 2005 trabaja casi solo con ladrillo artesanal, luz natural y el suelo inundable del delta bengalí. Ha ganado dos veces el Premio Aga Khan de Arquitectura: en 2016 por la mezquita Bait Ur Rouf, encargo de su abuela, y en 2025 por Khudi Bari, una casa desmontable de bambú para familias desplazadas por la erosión fluvial. Time la incluyó en 2024 entre las cien personas más influyentes. Es una de las poquísimas mujeres que han proyectado una mezquita en todo el sur de Asia.',
      it: 'Tabassum si laureò alla BUET nel 1995, cofondò URBANA con Kashef Chowdhury lo stesso anno e due anni dopo vinse il concorso per il Monumento all’Indipendenza e Museo della Guerra di Liberazione a Dacca; i due portarono avanti quel progetto per sedici anni. Da quando ha aperto uno studio proprio nel 2005 lavora quasi esclusivamente con mattone artigianale, luce naturale e il suolo alluvionale del delta bengalese. Ha vinto due volte il Premio Aga Khan per l’Architettura: nel 2016 per la moschea Bait Ur Rouf, commissionata dalla nonna, e nel 2025 per Khudi Bari, una casa smontabile di bambù per famiglie sfollate dall’erosione fluviale. Nel 2024 Time l’ha inclusa fra le cento persone più influenti. È una delle pochissime donne ad aver progettato una moschea nell’intera Asia meridionale.',
    },
    awards: ['Aga Khan Award for Architecture (2016)', 'Aga Khan Award for Architecture (2025)', 'Lisbon Triennale Millennium bcp Lifetime Achievement Award (2022)', 'Ekushey Padak (2026)', 'Jameel Prize (2016, Bait Ur Rouf)'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q27451427', title: 'Marina Tabassum (Q27451427)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Marina_Tabassum', title: 'Marina Tabassum', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Bait_Ur_Rouf_Mosque', title: 'Bait Ur Rouf Mosque', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'leila-araghian',
    wikidataId: 'Q19830052',
    name: 'Leila Araghian',
    alternativeNames: ['لیلا عراقیان', 'Leila Araghian (Diba Tensile Architecture)'],
    gender: 'woman',
    born: 1983,
    died: null,
    floruit: { start: 2011, end: 2020, override: false },
    movements: 'unaffiliated',
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'infrastructure',
    signatureMaterial: 'steel-and-glass',
    portrait: {
      en: 'Araghian studied architecture at Shahid Beheshti University in Tehran and took a master’s at the University of British Columbia, where she won the Henry Elder Prize. She co-founded Diba Tensile Architecture in 2005, a practice built around membrane and lightweight structures, and was chief architect and designer of the Tabiat Bridge — a 270-metre pedestrian crossing over a Tehran expressway that she deliberately made too wide and too slow to be only a crossing. It opened in 2014 and took the Aga Khan Award for Architecture in 2016. Sanctions have limited her international exposure: she was refused entry to the World Architecture Festival on account of her nationality and said publicly that a cultural event should have nothing to do with politics.',
      es: 'Araghian estudió arquitectura en la Universidad Shahid Beheshti de Teherán y cursó un máster en la University of British Columbia, donde ganó el premio Henry Elder. En 2005 cofundó Diba Tensile Architecture, estudio dedicado a las membranas y las estructuras ligeras, y fue arquitecta jefa y autora del puente Tabiat: un paso peatonal de 270 metros sobre una autovía de Teherán que hizo adrede demasiado ancho y demasiado lento para ser solo un paso. Se inauguró en 2014 y obtuvo el Premio Aga Khan de Arquitectura en 2016. Las sanciones han limitado su proyección internacional: le negaron la entrada al World Architecture Festival por su nacionalidad y declaró en público que un acto cultural no debería tener nada que ver con la política.',
      it: 'Araghian studiò architettura alla Shahid Beheshti University di Teheran e conseguì un master alla University of British Columbia, dove vinse il premio Henry Elder. Nel 2005 cofondò Diba Tensile Architecture, studio dedicato alle membrane e alle strutture leggere, e fu architetto capo e autrice del ponte Tabiat: un attraversamento pedonale di 270 metri sopra una superstrada di Teheran, reso di proposito troppo largo e troppo lento per essere solo un attraversamento. Fu inaugurato nel 2014 e ottenne il Premio Aga Khan per l’Architettura nel 2016. Le sanzioni ne hanno limitato la visibilità internazionale: le fu negato l’ingresso al World Architecture Festival per la nazionalità, e dichiarò pubblicamente che un evento culturale non dovrebbe avere nulla a che fare con la politica.',
    },
    awards: ['Aga Khan Award for Architecture (2016)', 'Architizer A+ Awards Popular Choice, Highways & Bridges (2015)', 'Henry Elder Prize, University of British Columbia'],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q19830052', title: 'Leila Araghian (Q19830052)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Leila_Araghian', title: 'Leila Araghian', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Tabiat_Bridge', title: 'Tabiat Bridge', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'anupama-kundoo',
    wikidataId: 'Q21174063',
    name: 'Anupama Kundoo',
    alternativeNames: ['Anupama Kundoo Architects'],
    gender: 'woman',
    born: 1967,
    died: null,
    floruit: { start: 1994, end: 2024, override: false },
    movements: [{ id: 'sustainable-architecture', primary: true }, { id: 'critical-regionalism', primary: false }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'housing',
    signatureMaterial: 'brick',
    portrait: {
      en: 'Kundoo graduated from Sir J. J. College of Architecture in Bombay in 1989 and moved almost immediately to Auroville, the experimental township in Tamil Nadu, where she built for a decade on the premise that the interesting question is not what a building looks like but what it costs in labour, energy and imported material. Her answers are hand-made: fired-in-place mud houses, ferrocement shells, terracotta vault soffits, achieved with unskilled local labour. The Wall House of 2000 was rebuilt full-size by hand for the 2012 Venice Biennale. She took a doctorate at TU Berlin in 2008 and has taught at Parsons, Queensland, Camilo José Cela in Madrid and, since 2024, as professor at TU Berlin. None of her buildings has a Wikidata entity.',
      es: 'Kundoo se graduó en el Sir J. J. College of Architecture de Bombay en 1989 y se trasladó casi de inmediato a Auroville, la ciudad experimental de Tamil Nadu, donde construyó durante una década partiendo de que la pregunta interesante no es qué aspecto tiene un edificio sino cuánto cuesta en mano de obra, energía y material importado. Sus respuestas son artesanales: casas de tierra cocidas in situ, cáscaras de ferrocemento, bóvedas de terracota, ejecutadas con mano de obra local no cualificada. La Wall House de 2000 se reconstruyó a tamaño natural y a mano para la Bienal de Venecia de 2012. Se doctoró en la TU de Berlín en 2008 y ha enseñado en Parsons, Queensland, la Camilo José Cela de Madrid y, desde 2024, como catedrática en la TU de Berlín. Ninguno de sus edificios tiene ficha en Wikidata.',
      it: 'Kundoo si laureò al Sir J. J. College of Architecture di Bombay nel 1989 e si trasferì quasi subito ad Auroville, la città sperimentale del Tamil Nadu, dove costruì per un decennio partendo dal presupposto che la domanda interessante non sia che aspetto abbia un edificio, ma quanto costi in manodopera, energia e materiale d’importazione. Le sue risposte sono artigianali: case di terra cotte in loco, gusci in ferrocemento, volte in terracotta, realizzate con manodopera locale non specializzata. La Wall House del 2000 fu ricostruita a grandezza naturale e a mano per la Biennale di Venezia del 2012. Ha conseguito il dottorato alla TU di Berlino nel 2008 e ha insegnato a Parsons, in Queensland, alla Camilo José Cela di Madrid e, dal 2024, come professoressa ordinaria alla TU di Berlino. Nessuno dei suoi edifici ha una scheda su Wikidata.',
    },
    awards: ['RIBA Charles Jencks Award (2021)', 'Auguste Perret Prize nomination', 'Building Trust International Moving Schools award (2013)'],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q21174063', title: 'Anupama Kundoo (Q21174063)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Anupama_Kundoo', title: 'Anupama Kundoo', license: 'CC BY-SA 4.0' },
      { kind: 'publication', url: 'https://www.dezeen.com/2020/11/20/anupama-kundoo-architecture-projects/', title: 'Ten key projects by Indian architect Anupama Kundoo — Dezeen, 20 November 2020', license: null },
    ],
  },
  {
    // Ownership handover from europe-west, recorded in the wave 5 progress ledger:
    // europe-west could place no Le Corbusier building at all (every French work is
    // FoP-blocked; the sole Belgian building did not fit its era budget), and India
    // has usable FoP for the Chandigarh Capitol Complex, so this slice defines him
    // for the one commission below rather than leaving him out of the pool entirely.
    id: 'le-corbusier',
    wikidataId: 'Q4724',
    name: 'Le Corbusier',
    alternativeNames: ['Charles-Édouard Jeanneret', 'Charles-Édouard Jeanneret-Gris'],
    gender: 'man',
    born: 1887,
    died: 1965,
    floruit: { start: 1907, end: 1965, override: false },
    movements: [{ id: 'international-style', primary: true }, { id: 'brutalism', primary: false }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'civic',
    signatureMaterial: 'concrete',
    portrait: {
      en: "Charles-Édouard Jeanneret took the name Le Corbusier in 1920 and became the central figure of twentieth-century Modernism — the five points of a new architecture, the Unité d'Habitation, the sculptural concrete of his late churches and monasteries. Almost all of that French practice sits behind a Freedom of Panorama block this pool cannot license, so he is claimed here for the one major commission that falls outside it: the Capitol of Chandigarh, the replacement capital Jawaharlal Nehru asked him to design after Partition cost Punjab its old one, Lahore. Corbusier laid out the new city's master plan from 1951 and built the Palace of Assembly, the Secretariat and the High Court in raw board-marked concrete, working the site for the rest of his life alongside his cousin Pierre Jeanneret, the project's resident architect.",
      es: 'Charles-Édouard Jeanneret adoptó el nombre de Le Corbusier en 1920 y se convirtió en la figura central del modernismo del siglo XX: los cinco puntos de una arquitectura nueva, la Unité d’Habitation, el hormigón escultórico de sus iglesias y monasterios tardíos. Casi toda esa obra francesa queda detrás de un bloqueo por Freedom of Panorama que este repertorio no puede licenciar, así que aquí se le reivindica por el único gran encargo que escapa a esa traba: el Capitolio de Chandigarh, la capital de recambio que Jawaharlal Nehru le pidió tras perder el Punyab su antigua capital, Lahore, en la Partición. Corbusier trazó el plan maestro de la nueva ciudad desde 1951 y levantó el Palacio de la Asamblea, la Secretaría y el Tribunal Superior en hormigón bruto encofrado en tablas, trabajando en el lugar el resto de su vida junto a su primo Pierre Jeanneret, arquitecto residente del proyecto.',
      it: "Charles-Édouard Jeanneret adottò il nome Le Corbusier nel 1920 e divenne la figura centrale del modernismo del Novecento: i cinque punti di un'architettura nuova, l'Unité d'Habitation, il cemento scultoreo delle sue ultime chiese e dei suoi monasteri. Quasi tutta quella pratica francese resta dietro un blocco da Freedom of Panorama che questo repertorio non può licenziare, perciò qui gli si attribuisce l'unico grande incarico che ne resta fuori: il Campidoglio di Chandigarh, la capitale sostitutiva che Jawaharlal Nehru gli chiese di progettare dopo che la Partizione tolse al Punjab la sua vecchia capitale, Lahore. Corbusier tracciò il piano regolatore della nuova città a partire dal 1951 e costruì il Palazzo dell'Assemblea, il Segretariato e l'Alta Corte in cemento grezzo a cassero di tavole, lavorando sul sito per il resto della vita accanto al cugino Pierre Jeanneret, architetto residente del progetto.",
    },
    awards: ['Royal Gold Medal (1953)', 'AIA Gold Medal (1961)'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q4724', title: 'Le Corbusier (Q4724)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Le_Corbusier', title: 'Le Corbusier', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Chandigarh_Capitol_Complex', title: 'Chandigarh Capitol Complex', license: 'CC BY-SA 4.0' },
      { kind: 'institution', url: 'https://whc.unesco.org/en/list/1321/', title: 'The Architectural Work of Le Corbusier, an Outstanding Contribution to the Modern Movement — UNESCO World Heritage Centre', license: null },
    ],
  },
];
