import type { Architect } from '@/types/architect';

// Wave 5 curator agent (Southeast Asia): real, sourced Architect entries for this slice.
//
// Countries in scope: TH, VN, KH, LA, MM, MY, SG, ID, PH.
//
// `workRegions` and `workCentroid` are deliberately left as [] / {0,0}:
// `npm run data:curate` derives both from each architect's buildings and
// overwrites whatever is typed here.
export const ASIA_SOUTHEAST_ARCHITECTS: Architect[] = [
  // --- pre-1800 -----------------------------------------------------------
  {
    id: 'kavindrarimathana',
    // No Wikidata item exists for him; the name appears only inside the
    // items for the temples he built (see report).
    wikidataId: '',
    name: 'Kavindrarimathana',
    alternativeNames: ['Kavīndrārimathana', 'Kavindrarimathana of Angkor'],
    gender: 'man',
    born: null,
    died: null,
    floruit: { start: 950, end: 962, override: false },
    movements: 'unaffiliated',
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'sacral',
    signatureMaterial: 'brick',
    portrait: {
      en: 'Kavindrarimathana is the only builder of the Khmer Empire whose name has come down to us. A Buddhist serving as chief minister to Rajendravarman II, who ruled at Angkor between 944 and 968, he is named on the doorjambs of Bat Chum as the man who raised that temple, and the same inscriptions credit him with the reservoir of Srah Srang and with the island temple of the East Mebon; the palace from which Rajendravarman governed is also attributed to him. That a court official signed his work at all is extraordinary. The thousand sanctuaries of Angkor otherwise record their royal patrons and say nothing of the people who set the brick. He appears to have died shortly after 960, the year Bat Chum was dedicated.',
      es: 'Kavindrarimathana es el único constructor del Imperio jemer cuyo nombre ha llegado hasta nosotros. Budista y primer ministro de Rajendravarman II, que reinó en Angkor entre 944 y 968, aparece nombrado en las jambas de Bat Chum como el hombre que levantó ese templo, y las mismas inscripciones le atribuyen el embalse de Srah Srang y el templo insular de Mebon Oriental; también se le adjudica el palacio desde el que gobernaba el rey. Que un alto funcionario firmara su obra resulta excepcional: los mil santuarios de Angkor consignan a sus patronos reales y callan el nombre de quienes asentaron el ladrillo. Debió de morir poco después del 960, año en que Bat Chum fue consagrado.',
      it: "Kavindrarimathana è l'unico costruttore dell'Impero khmer di cui ci sia giunto il nome. Buddhista e primo ministro di Rajendravarman II, che regnò ad Angkor fra il 944 e il 968, è nominato sugli stipiti di Bat Chum come l'uomo che innalzò quel tempio, e le stesse iscrizioni gli attribuiscono il bacino di Srah Srang e il tempio insulare dell'East Mebon; a lui si fa risalire anche il palazzo da cui il re governava. Che un alto funzionario firmasse la propria opera è eccezionale: i mille santuari di Angkor registrano i patroni regali e tacciono su chi posava i mattoni. Morì con ogni probabilità poco dopo il 960, anno della consacrazione di Bat Chum.",
    },
    awards: [],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Bat_Chum', title: 'Bat Chum', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Rajendravarman_II', title: 'Rajendravarman II', license: 'CC BY-SA 4.0' },
      { kind: 'publication', url: 'https://brill.com/display/title/6748', title: 'Dumarçay & Royère, Cambodian Architecture, Eighth to Thirteenth Centuries (Brill, 2001)', license: null },
    ],
  },
  {
    id: 'juan-macias',
    wikidataId: '',
    name: 'Juan Macías',
    alternativeNames: ['Fray Juan Macías', 'Juan Macias'],
    gender: 'man',
    born: null,
    died: null,
    floruit: { start: 1586, end: 1607, override: false },
    movements: [{ id: 'baroque', primary: true }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'sacral',
    signatureMaterial: 'stone',
    portrait: {
      en: 'Juan Macías was the Augustinian friar who drew the stone church of San Agustín inside the walls of Manila, begun in 1586 after two earlier timber-and-thatch churches on the same ground had burned. His brief was structural before it was decorative: to build something that would outlast the earthquakes and typhoons that had already destroyed most of what the Spanish had put up in Luzon. He specified thick adobe-stone walls, massive buttresses and a barrel vault carried on transverse arches, and the building has survived every major Manila earthquake since, including 1645, 1863 and 1880. Macías died before the church was declared finished in 1607; the Augustinians formally recorded him afterwards as the builder of the edifice.',
      es: 'Juan Macías fue el fraile agustino que trazó la iglesia de piedra de San Agustín dentro de las murallas de Manila, comenzada en 1586 después de que dos templos anteriores de madera y nipa ardieran en el mismo solar. Su encargo era estructural antes que ornamental: levantar algo capaz de sobrevivir a los terremotos y tifones que ya habían arruinado casi todo lo construido por los españoles en Luzón. Dispuso muros gruesos de piedra de adobe, contrafuertes macizos y una bóveda de cañón sobre arcos fajones, y el edificio ha resistido desde entonces todos los grandes seísmos de Manila, entre ellos los de 1645, 1863 y 1880. Macías murió antes de que la obra se diera por concluida en 1607; los agustinos lo reconocieron después formalmente como constructor del edificio.',
      it: "Juan Macías fu il frate agostiniano che disegnò la chiesa in pietra di San Agustín dentro le mura di Manila, avviata nel 1586 dopo che due chiese precedenti in legno e paglia erano bruciate sullo stesso terreno. Il suo compito era strutturale prima che decorativo: costruire qualcosa che sopravvivesse ai terremoti e ai tifoni che avevano già distrutto quasi tutto ciò che gli spagnoli avevano eretto a Luzon. Prescrisse muri spessi in pietra di adobe, contrafforti massicci e una volta a botte su archi trasversali, e l'edificio ha resistito da allora a ogni grande sisma di Manila, compresi quelli del 1645, 1863 e 1880. Macías morì prima che la chiesa fosse dichiarata conclusa nel 1607; gli agostiniani lo registrarono poi ufficialmente come costruttore dell'edificio.",
    },
    awards: [],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/San_Agustin_Church_(Manila)', title: 'San Agustin Church (Manila)', license: 'CC BY-SA 4.0' },
      { kind: 'institution', url: 'https://whc.unesco.org/en/list/677/', title: 'UNESCO World Heritage Centre — Baroque Churches of the Philippines', license: null },
    ],
  },
  {
    id: 'ewout-verhagen',
    wikidataId: 'Q133870895',
    name: 'Ewout Verhagen',
    alternativeNames: ['E. Verhagen', 'Ewout Verhagen van Rotterdam'],
    gender: 'man',
    born: null,
    died: 1694,
    floruit: { start: 1692, end: 1695, override: false },
    movements: [{ id: 'baroque', primary: true }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'sacral',
    signatureMaterial: 'brick',
    portrait: {
      en: 'Ewout Verhagen came from Rotterdam to Batavia, the Dutch East India Company capital on Java, and rose to head the ambachtskwartier, the walled craft quarter where the Company kept its carpenters, masons and shipwrights. In that role he drew the permanent Portuguese Outer Church, approved by the Company on 11 July 1692 and built over the following three years for the Mardijker congregation living outside the city wall. The design is a plain Dutch Protestant preaching box translated into the tropics: a single wide hall under a timber roof, brick walls rendered white, round-arched windows tall enough to move air. Verhagen died in 1694, a year before the church was consecrated. It is the oldest building in Jakarta still doing the job it was built for.',
      es: 'Ewout Verhagen llegó de Róterdam a Batavia, la capital de la Compañía Neerlandesa de las Indias Orientales en Java, y llegó a dirigir el ambachtskwartier, el barrio amurallado de oficios donde la Compañía alojaba a sus carpinteros, albañiles y calafates. Desde ese puesto trazó la iglesia portuguesa exterior definitiva, aprobada por la Compañía el 11 de julio de 1692 y levantada en los tres años siguientes para la congregación mardijker que vivía extramuros. El proyecto es una sobria sala de predicación protestante neerlandesa trasladada al trópico: una única nave ancha bajo cubierta de madera, muros de ladrillo enlucidos en blanco y ventanas de medio punto lo bastante altas para mover el aire. Verhagen murió en 1694, un año antes de la consagración. Es el edificio más antiguo de Yakarta que sigue cumpliendo su función original.',
      it: "Ewout Verhagen giunse da Rotterdam a Batavia, capitale della Compagnia olandese delle Indie orientali a Giava, e arrivò a dirigere l'ambachtskwartier, il quartiere murato delle arti dove la Compagnia teneva falegnami, muratori e maestri d'ascia. In quella veste disegnò la chiesa portoghese esterna definitiva, approvata dalla Compagnia l'11 luglio 1692 e costruita nei tre anni successivi per la congregazione mardijker che viveva fuori le mura. Il progetto è una sobria sala di predicazione protestante olandese trapiantata ai tropici: un'unica aula larga sotto un tetto ligneo, muri in laterizio intonacati di bianco, finestre centinate alte quanto basta a far circolare l'aria. Verhagen morì nel 1694, un anno prima della consacrazione. È il più antico edificio di Giacarta che svolga ancora la funzione per cui fu eretto.",
    },
    awards: [],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Gereja_Sion', title: 'Gereja Sion', license: 'CC BY-SA 4.0' },
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q133870895', title: 'Ewout Verhagen (Q133870895)', license: null },
    ],
  },

  // --- 1800-1945 ----------------------------------------------------------
  {
    id: 'henri-maclaine-pont',
    wikidataId: 'Q2079131',
    name: 'Henri Maclaine Pont',
    alternativeNames: ['Henri Maclaine-Pont', 'H. Maclaine Pont'],
    gender: 'man',
    born: 1884,
    died: 1971,
    floruit: { start: 1911, end: 1937, override: false },
    movements: [{ id: 'timber-vernacular', primary: true }, { id: 'expressionism', primary: false }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'educational',
    signatureMaterial: 'timber',
    portrait: {
      en: 'Born in Batavia and trained as a civil engineer at Delft, Henri Maclaine Pont spent most of his working life in Java and is generally credited as the father of a modern Indonesian vernacular. His first commission was the headquarters of the Semarang–Cheribon steam tram company in 1911; he later excavated and studied the pre-Islamic architecture of Majapahit at Trowulan, and argued in print with his Bandung rival Wolff Schoemaker about how much of Java a European architect was entitled to borrow. His answer, built rather than written, was the ceremonial halls of the Technische Hoogeschool at Bandung, where a Javanese roof profile is carried on an engineered hybrid truss. He was interned by the Japanese in 1943 and left Indonesia in 1947, dying in The Hague.',
      es: 'Nacido en Batavia y formado como ingeniero civil en Delft, Henri Maclaine Pont pasó casi toda su vida profesional en Java y suele considerarse el padre de un vernáculo indonesio moderno. Su primer encargo fue la sede de la compañía de tranvías de vapor Semarang-Cheribon en 1911; más tarde excavó y estudió la arquitectura preislámica de Majapahit en Trowulan y polemizó por escrito con su rival de Bandung, Wolff Schoemaker, sobre cuánto de Java podía tomar prestado un arquitecto europeo. Su respuesta, construida y no escrita, fueron las aulas ceremoniales de la Technische Hoogeschool de Bandung, donde un perfil de cubierta javanés descansa sobre una cercha híbrida calculada. Internado por los japoneses en 1943, abandonó Indonesia en 1947 y murió en La Haya.',
      it: "Nato a Batavia e formatosi come ingegnere civile a Delft, Henri Maclaine Pont trascorse quasi tutta la vita professionale a Giava ed è generalmente considerato il padre di un vernacolo indonesiano moderno. Il primo incarico fu la sede della compagnia tranviaria a vapore Semarang-Cheribon nel 1911; scavò e studiò poi l'architettura preislamica di Majapahit a Trowulan e polemizzò a stampa con il rivale di Bandung, Wolff Schoemaker, su quanto di Giava un architetto europeo avesse diritto di prendere in prestito. La sua risposta, costruita anziché scritta, furono le aule cerimoniali della Technische Hoogeschool di Bandung, dove un profilo di tetto giavanese poggia su una capriata ibrida calcolata. Internato dai giapponesi nel 1943, lasciò l'Indonesia nel 1947 e morì all'Aia.",
    },
    awards: [],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Henri_Maclaine_Pont', title: 'Henri Maclaine Pont', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Bandung_Institute_of_Technology', title: 'Bandung Institute of Technology', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'u-tin',
    wikidataId: 'Q7876246',
    name: 'U Tin',
    alternativeNames: ['Sithu U Tin', 'ဦးတင်'],
    gender: 'man',
    born: 1890,
    died: 1972,
    floruit: { start: 1926, end: 1957, override: false },
    movements: 'unaffiliated',
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'civic',
    signatureMaterial: 'concrete',
    portrait: {
      en: 'U Tin was the Burmese architect and engineer who gave colonial Rangoon its most conspicuously Burmese public buildings. Working inside a British administration whose civic architecture was otherwise imported wholesale from London and Calcutta, he fitted tiered pyatthat roofs, peacock reliefs and naga balustrades onto reinforced-concrete frames of entirely modern construction. Yangon City Hall, begun in 1926 and finished in 1936, is the fullest statement of that syncretism; Yangon Central Railway Station and Myoma High School belong to the same argument. The honorific Sithu was conferred on him. His work is now the anchor of Yangon’s heritage list, and the reason the city’s colonial core does not read simply as a British transplant.',
      es: 'U Tin fue el arquitecto e ingeniero birmano que dotó a la Rangún colonial de sus edificios públicos más visiblemente birmanos. Trabajando dentro de una administración británica cuya arquitectura civil se importaba por lo general en bloque desde Londres y Calcuta, ajustó cubiertas escalonadas pyatthat, relieves de pavos reales y balaustradas de naga sobre estructuras de hormigón armado enteramente modernas. El Ayuntamiento de Yangón, iniciado en 1926 y terminado en 1936, es la formulación más completa de ese sincretismo; la Estación Central de Yangón y la Escuela Myoma pertenecen al mismo argumento. Recibió el título honorífico de Sithu. Su obra es hoy el eje de la lista patrimonial de Yangón y la razón de que el centro colonial de la ciudad no se lea simplemente como un trasplante británico.',
      it: "U Tin fu l'architetto e ingegnere birmano che diede alla Rangoon coloniale i suoi edifici pubblici più marcatamente birmani. Operando dentro un'amministrazione britannica la cui architettura civile veniva per lo più importata in blocco da Londra e Calcutta, innestò tetti a gradoni pyatthat, rilievi di pavoni e balaustre a naga su telai in cemento armato del tutto moderni. Il Municipio di Yangon, avviato nel 1926 e concluso nel 1936, è la formulazione più compiuta di quel sincretismo; la Stazione centrale di Yangon e la Myoma High School appartengono allo stesso discorso. Gli fu conferito il titolo onorifico di Sithu. La sua opera è oggi il cardine della lista del patrimonio di Yangon e la ragione per cui il nucleo coloniale della città non si legge come un semplice trapianto britannico.",
    },
    awards: ['Sithu (Burmese state honorific)'],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/U_Tin', title: 'U Tin', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Yangon_City_Hall', title: 'Yangon City Hall', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'juan-m-arellano',
    wikidataId: 'Q1882538',
    name: 'Juan M. Arellano',
    alternativeNames: ['Juan Marcos Arellano y de Guzmán', 'Juan Arellano'],
    gender: 'man',
    born: 1888,
    died: 1960,
    floruit: { start: 1918, end: 1940, override: false },
    movements: [{ id: 'art-deco', primary: true }, { id: 'beaux-arts', primary: false }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'civic',
    signatureMaterial: 'concrete',
    portrait: {
      en: 'Juan M. Arellano trained first as a painter under Lorenzo Guerrero and Fabián de la Rosa, then went to the United States as one of the first Filipino government pensionados in architecture, studying at the Pennsylvania Academy of the Fine Arts and Drexel and working for George B. Post & Sons in New York. Back in Manila he became a supervising architect at the Bureau of Public Works and produced the Beaux-Arts set pieces of the American colonial capital: the Legislative Building, the Manila Central Post Office, the Rizal Memorial sports complex. Sent back to America in 1927 to study under the theatre specialist Thomas W. Lamb, he returned a different designer, and the Metropolitan Theater of 1931 announced Art Deco in the Philippines with tropical foliage cast in concrete and stained glass.',
      es: 'Juan M. Arellano se formó primero como pintor con Lorenzo Guerrero y Fabián de la Rosa, y viajó después a Estados Unidos como uno de los primeros pensionados filipinos en arquitectura, estudiando en la Pennsylvania Academy of the Fine Arts y en Drexel y trabajando para George B. Post & Sons en Nueva York. De vuelta en Manila fue arquitecto supervisor de la Oficina de Obras Públicas y firmó las piezas Beaux-Arts de la capital colonial norteamericana: el Edificio Legislativo, la Oficina Central de Correos, el complejo deportivo Rizal Memorial. Enviado de nuevo a Estados Unidos en 1927 para formarse con el especialista en teatros Thomas W. Lamb, regresó convertido en otro proyectista: el Teatro Metropolitano de 1931 anunció el art déco en Filipinas con vegetación tropical fundida en hormigón y vidriera.',
      it: "Juan M. Arellano si formò dapprima come pittore con Lorenzo Guerrero e Fabián de la Rosa, poi partì per gli Stati Uniti come uno dei primi pensionados filippini in architettura, studiando alla Pennsylvania Academy of the Fine Arts e alla Drexel e lavorando per George B. Post & Sons a New York. Tornato a Manila divenne architetto sovrintendente dell'Ufficio dei Lavori Pubblici e firmò i pezzi Beaux-Arts della capitale coloniale americana: il Palazzo Legislativo, le Poste centrali, il complesso sportivo Rizal Memorial. Rimandato in America nel 1927 per formarsi con lo specialista di teatri Thomas W. Lamb, rientrò come un progettista diverso: il Teatro Metropolitano del 1931 annunciò l'Art Déco nelle Filippine con vegetazione tropicale fusa nel cemento e nelle vetrate.",
    },
    awards: [],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Juan_M._Arellano', title: 'Juan M. Arellano', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Manila_Metropolitan_Theater', title: 'Manila Metropolitan Theater', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'ernest-hebrard',
    wikidataId: 'Q1931256',
    name: 'Ernest Hébrard',
    alternativeNames: ['Ernest Michel Hébrard', 'Ernest Hebrard'],
    gender: 'man',
    born: 1875,
    died: 1933,
    floruit: { start: 1917, end: 1932, override: false },
    movements: [{ id: 'beaux-arts', primary: true }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'civic',
    signatureMaterial: 'concrete',
    portrait: {
      en: 'Ernest Hébrard won the Grand Prix de Rome in 1904 and made his reputation twice over: first with the reconstruction plan for Thessaloniki after the fire of 1917, then, from 1921, as head of the Architecture and Town Planning Service of French Indochina, based in Hanoi. There he laid out the hill station of Da Lat, redrew districts of Hanoi and Phnom Penh, and built a series of government and academic buildings in what he called the style indochinois — reinforced-concrete frames wrapped in deep verandas, louvred screens and multi-tiered tile roofs borrowed from Vietnamese and Khmer models. The style was a colonial instrument as much as an aesthetic one, arguing that French rule could be at home in Asia. He returned to Paris in 1931 and died two years later.',
      es: 'Ernest Hébrard ganó el Grand Prix de Rome en 1904 y labró su reputación dos veces: primero con el plan de reconstrucción de Salónica tras el incendio de 1917 y, desde 1921, como director del Servicio de Arquitectura y Urbanismo de la Indochina francesa, con sede en Hanói. Allí trazó la estación de altura de Da Lat, rediseñó barrios de Hanói y Nom Pen y levantó una serie de edificios oficiales y académicos en lo que llamó style indochinois: estructuras de hormigón armado envueltas en galerías profundas, celosías y cubiertas de teja de varios cuerpos tomadas de modelos vietnamitas y jemeres. El estilo fue tanto un instrumento colonial como una estética, pues sostenía que la dominación francesa podía estar en casa en Asia. Regresó a París en 1931 y murió dos años después.',
      it: "Ernest Hébrard vinse il Grand Prix de Rome nel 1904 e si costruì una reputazione due volte: prima con il piano di ricostruzione di Salonicco dopo l'incendio del 1917, poi, dal 1921, come direttore del Servizio di Architettura e Urbanistica dell'Indocina francese, con sede a Hanoi. Vi tracciò la stazione climatica di Da Lat, ridisegnò quartieri di Hanoi e Phnom Penh e realizzò una serie di edifici governativi e accademici in quello che chiamò style indochinois: telai in cemento armato avvolti da verande profonde, schermature a persiana e coperture in tegole a più ordini riprese da modelli vietnamiti e khmer. Lo stile fu uno strumento coloniale non meno che un'estetica, poiché sosteneva che il dominio francese potesse essere di casa in Asia. Rientrò a Parigi nel 1931 e morì due anni dopo.",
    },
    awards: ['Grand Prix de Rome (1904)'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Ernest_H%C3%A9brard', title: 'Ernest Hébrard', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/National_Museum_of_Vietnamese_History', title: 'National Museum of Vietnamese History', license: 'CC BY-SA 4.0' },
    ],
  },

  // --- 1945-2000 ----------------------------------------------------------
  {
    id: 'vann-molyvann',
    wikidataId: 'Q379178',
    name: 'Vann Molyvann',
    alternativeNames: ['វណ្ណ ម៉ូលីវណ្ណ', 'Van Molyvann'],
    gender: 'man',
    born: 1926,
    died: 2017,
    floruit: { start: 1957, end: 1972, override: false },
    movements: [{ id: 'tropical-modernism', primary: true }, { id: 'brutalism', primary: false }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'civic',
    signatureMaterial: 'concrete',
    portrait: {
      en: 'Vann Molyvann studied at the École des Beaux-Arts in Paris, where Le Corbusier was among his teachers, and returned to Cambodia in 1956 as one of a handful of trained Cambodian architects. Norodom Sihanouk made him State Architect and Head of Public Works, and in fourteen years he built more than a hundred structures — the Independence Monument, the Chaktomuk Conference Hall, the National Sports Complex, the Institute of Foreign Languages — in a manner now called New Khmer Architecture: raised concrete floors, vast shading canopies, ponds and channels drawn from Angkorian water management. He spent the Khmer Rouge years and the civil war in exile in Switzerland, returned in 1991, and headed the Angkor conservation authority APSARA until he was dismissed in 2001 after disputes with the government. Much of his built work has since been demolished or left to decay.',
      es: 'Vann Molyvann estudió en la École des Beaux-Arts de París, donde Le Corbusier fue uno de sus maestros, y regresó a Camboya en 1956 como uno de los poquísimos arquitectos camboyanos titulados. Norodom Sihanouk lo nombró arquitecto del Estado y jefe de Obras Públicas, y en catorce años construyó más de un centenar de obras —el Monumento a la Independencia, la sala de conferencias Chaktomuk, el Complejo Deportivo Nacional, el Instituto de Lenguas Extranjeras— en lo que hoy se llama Nueva Arquitectura Jemer: forjados elevados de hormigón, grandes parasoles, estanques y canales tomados de la hidráulica angkoriana. Pasó los años del Jemer Rojo y la guerra civil exiliado en Suiza, volvió en 1991 y dirigió la autoridad de conservación de Angkor, APSARA, hasta su destitución en 2001 tras enfrentarse al gobierno. Buena parte de su obra ha sido derribada o abandonada desde entonces.',
      it: "Vann Molyvann studiò all'École des Beaux-Arts di Parigi, dove ebbe fra i maestri Le Corbusier, e tornò in Cambogia nel 1956 come uno dei pochissimi architetti cambogiani con una formazione completa. Norodom Sihanouk lo nominò architetto di Stato e capo dei Lavori Pubblici, e in quattordici anni realizzò oltre cento opere — il Monumento all'Indipendenza, la sala congressi Chaktomuk, il Complesso Sportivo Nazionale, l'Istituto di Lingue Straniere — in quella che oggi si chiama Nuova Architettura Khmer: solai rialzati in calcestruzzo, grandi coperture ombreggianti, vasche e canali ripresi dall'idraulica angkoriana. Trascorse gli anni dei Khmer rossi e la guerra civile in esilio in Svizzera, rientrò nel 1991 e diresse l'ente di tutela di Angkor, APSARA, fino alla destituzione nel 2001 dopo contrasti con il governo. Gran parte delle sue opere è stata da allora demolita o lasciata degradare.",
    },
    awards: [],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Vann_Molyvann', title: 'Vann Molyvann', license: 'CC BY-SA 4.0' },
      { kind: 'publication', url: 'https://www.nytimes.com/2017/09/28/obituaries/vann-molyvann-dead-architect-who-shaped-cambodias-capital.html', title: 'Vann Molyvann, Architect Who Shaped Cambodia’s Capital, Dies at 90 (The New York Times, 28 September 2017)', license: null },
    ],
  },
  {
    id: 'leandro-locsin',
    wikidataId: 'Q2196637',
    name: 'Leandro Locsin',
    alternativeNames: ['Leandro Valencia Locsin', 'Lindy Locsin'],
    gender: 'man',
    born: 1928,
    died: 1994,
    floruit: { start: 1955, end: 1994, override: false },
    movements: [{ id: 'brutalism', primary: true }, { id: 'tropical-modernism', primary: false }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'cultural',
    signatureMaterial: 'concrete',
    portrait: {
      en: 'Leandro Locsin came to architecture from music: he was reading for a degree in piano at the University of Santo Tomás when he changed course. His first significant building, the round Church of the Holy Sacrifice at the University of the Philippines in 1955, put a thin concrete shell dome over an altar placed in the middle of the congregation, and was executed with a group of artists who would all later be named National Artists. A visit to the United States, and meetings with Paul Rudolph and Eero Saarinen, confirmed concrete as his material: cheap in the Philippines, easy to form, and capable of the cantilevered slabs that became his signature — a heavy volume that appears to float clear of the ground. He was named National Artist for Architecture in 1990.',
      es: 'Leandro Locsin llegó a la arquitectura desde la música: cursaba la carrera de piano en la Universidad de Santo Tomás cuando cambió de rumbo. Su primera obra importante, la iglesia circular del Santo Sacrificio en la Universidad de Filipinas, de 1955, cubrió con una lámina delgada de hormigón un altar situado en medio de la asamblea, y se ejecutó junto a un grupo de artistas que con el tiempo serían todos Artistas Nacionales. Un viaje a Estados Unidos y sus encuentros con Paul Rudolph y Eero Saarinen le confirmaron el hormigón como material: barato en Filipinas, fácil de encofrar y capaz de los forjados en voladizo que se volvieron su firma, un volumen pesado que parece flotar separado del suelo. Fue proclamado Artista Nacional de Arquitectura en 1990.',
      it: "Leandro Locsin arrivò all'architettura dalla musica: studiava pianoforte all'Università di Santo Tomás quando cambiò strada. La sua prima opera importante, la chiesa circolare del Santo Sacrificio all'Università delle Filippine, del 1955, coprì con una sottile calotta in calcestruzzo un altare collocato in mezzo all'assemblea, e fu realizzata con un gruppo di artisti che sarebbero poi divenuti tutti Artisti Nazionali. Un viaggio negli Stati Uniti e gli incontri con Paul Rudolph ed Eero Saarinen gli confermarono il calcestruzzo come materiale: economico nelle Filippine, facile da casserare e capace di quegli sbalzi che divennero la sua firma, un volume pesante che sembra galleggiare staccato dal suolo. Fu proclamato Artista Nazionale per l'Architettura nel 1990.",
    },
    awards: ['National Artist of the Philippines for Architecture (1990)'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Leandro_Locsin', title: 'Leandro Locsin', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Cultural_Center_of_the_Philippines', title: 'Cultural Center of the Philippines', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'ken-yeang',
    wikidataId: 'Q522879',
    name: 'Ken Yeang',
    alternativeNames: ['Yeang Cheng Hai', 'Kenneth Yeang'],
    gender: 'man',
    born: 1948,
    died: null,
    floruit: { start: 1984, end: 2020, override: false },
    movements: [{ id: 'sustainable-architecture', primary: true }, { id: 'high-tech', primary: false }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'tower',
    signatureMaterial: 'steel-and-glass',
    portrait: {
      en: 'Ken Yeang was born in Penang, trained at the Architectural Association in London, and took a Cambridge doctorate with a thesis on incorporating ecological reasoning into the design of the built environment — an argument he has been building ever since, in Kuala Lumpur, at the practice Hamzah & Yeang. His subject is the tropical skyscraper: how a tall building in an equatorial climate can be shaded, cross-ventilated, planted and oriented so that its envelope does the work air conditioning normally does. The devices he standardised — spiralling planted terraces, sunshades sized by solar path, naturally ventilated lift lobbies, the roof-level louvre canopy — first appeared together at Menara Mesiniaga in 1992. The Guardian listed him in 2008 among fifty people who could save the planet.',
      es: 'Ken Yeang nació en Penang, se formó en la Architectural Association de Londres y se doctoró en Cambridge con una tesis sobre la incorporación del razonamiento ecológico al proyecto del entorno construido, un argumento que no ha dejado de desarrollar desde entonces en Kuala Lumpur, en el estudio Hamzah & Yeang. Su tema es el rascacielos tropical: cómo sombrear, ventilar de forma cruzada, plantar y orientar un edificio alto en clima ecuatorial para que su envolvente haga el trabajo que normalmente hace el aire acondicionado. Los recursos que él normalizó —terrazas ajardinadas en espiral, parasoles dimensionados según el recorrido solar, vestíbulos de ascensores ventilados naturalmente, la pérgola de lamas en cubierta— aparecieron juntos por primera vez en la Menara Mesiniaga en 1992. En 2008 The Guardian lo incluyó entre cincuenta personas capaces de salvar el planeta.',
      it: "Ken Yeang è nato a Penang, si è formato all'Architectural Association di Londra e ha conseguito un dottorato a Cambridge con una tesi sull'inserimento del ragionamento ecologico nel progetto dell'ambiente costruito: un argomento che da allora non ha smesso di sviluppare a Kuala Lumpur, nello studio Hamzah & Yeang. Il suo tema è il grattacielo tropicale: come ombreggiare, ventilare in modo incrociato, piantumare e orientare un edificio alto in clima equatoriale perché il suo involucro faccia il lavoro che di norma spetta al condizionamento. I dispositivi che ha codificato — terrazze piantumate a spirale, frangisole dimensionati sul percorso solare, atri degli ascensori a ventilazione naturale, la pensilina a lamelle in copertura — comparvero insieme per la prima volta alla Menara Mesiniaga nel 1992. Nel 2008 il Guardian lo incluse fra cinquanta persone capaci di salvare il pianeta.",
    },
    awards: ['Aga Khan Award for Architecture (1995)', 'Merdeka Award (2011)'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Ken_Yeang', title: 'Ken Yeang', license: 'CC BY-SA 4.0' },
      { kind: 'institution', url: 'https://www.akdn.org/architecture/project/menara-mesiniaga', title: 'Aga Khan Development Network — Menara Mesiniaga', license: null },
    ],
  },
  {
    id: 'tep-vattho',
    wikidataId: 'Q123899786',
    name: 'Tep Vattho',
    alternativeNames: ['ទេព វត្ថូ', 'Vattho Tep'],
    gender: 'woman',
    born: 1963,
    died: 2016,
    floruit: { start: 1994, end: 2010, override: false },
    movements: [{ id: 'timber-vernacular', primary: true }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'cultural',
    signatureMaterial: 'timber',
    portrait: {
      en: 'Tep Vattho was twelve when her family, headed by the justice minister Tep Hun, left Cambodia for France in 1975; the Khmer Rouge took Phnom Penh a fortnight later. She began medicine in France, changed to architecture, and met her husband and partner Olivier Piot in the school. The two returned to Siem Reap in the early 1990s, when the town had almost no tourist infrastructure and almost no architects, and built the Angkor Village Hotel in 1994, the Angkor Village Resort, and in 1997 the Apsara Theatre — a Khmer timber pavilion built for classical dance, the town’s oldest theatre. She later directed the urban planning department of the APSARA Authority, which regulates building across the Angkor region. She died in Siem Reap in 2016; a street beside the river there carries her name.',
      es: 'Tep Vattho tenía doce años cuando su familia, encabezada por el ministro de Justicia Tep Hun, salió de Camboya rumbo a Francia en 1975; los Jemeres Rojos tomaron Nom Pen quince días después. Empezó Medicina en Francia, se pasó a Arquitectura y allí conoció a su marido y socio, Olivier Piot. Ambos regresaron a Siem Reap a principios de los noventa, cuando la ciudad casi no tenía infraestructura turística ni arquitectos, y construyeron el Angkor Village Hotel en 1994, el Angkor Village Resort y, en 1997, el Teatro Apsara: un pabellón jemer de madera concebido para la danza clásica y el teatro más antiguo de la ciudad. Dirigió después el departamento de urbanismo de la Autoridad APSARA, que regula la edificación en toda la región de Angkor. Murió en Siem Reap en 2016; una calle junto al río lleva su nombre.',
      it: "Tep Vattho aveva dodici anni quando la sua famiglia, guidata dal ministro della Giustizia Tep Hun, lasciò la Cambogia per la Francia nel 1975; i Khmer rossi presero Phnom Penh due settimane dopo. Iniziò Medicina in Francia, passò ad Architettura e lì conobbe il marito e socio Olivier Piot. I due tornarono a Siem Reap all'inizio degli anni Novanta, quando la città non aveva quasi infrastrutture turistiche né architetti, e costruirono l'Angkor Village Hotel nel 1994, l'Angkor Village Resort e, nel 1997, l'Apsara Theatre: un padiglione khmer in legno pensato per la danza classica e il più antico teatro della città. Diresse poi il dipartimento di urbanistica dell'Autorità APSARA, che regola l'edificazione in tutta la regione di Angkor. Morì a Siem Reap nel 2016; una via lungo il fiume porta il suo nome.",
    },
    awards: [],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Tep_Vattho', title: 'Tep Vattho', license: 'CC BY-SA 4.0' },
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q123899786', title: 'Tep Vattho (Q123899786)', license: null },
    ],
  },
  {
    id: 'dang-viet-nga',
    wikidataId: '',
    name: 'Đặng Việt Nga',
    alternativeNames: ['Dang Viet Nga', 'Hằng Nga'],
    gender: 'woman',
    born: null,
    died: null,
    floruit: { start: 1990, end: 2020, override: false },
    movements: [{ id: 'expressionism', primary: true }, { id: 'organic-architecture', primary: false }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'domestic',
    signatureMaterial: 'concrete',
    portrait: {
      en: 'Đặng Việt Nga took a doctorate in architecture in Moscow and is the daughter of Trường Chinh, general secretary of the Communist Party of Vietnam. She has spent more than thirty years building a single house in Đà Lạt, and she builds it without drawings: instead of plans she makes paintings, and hands them to local craftsmen who have no formal training in construction to be turned into structure. The result, the Hằng Nga guesthouse, has almost no right angles — a five-storey concrete banyan tree with caves, webs and animal rooms grown out of it, which critics have called expressionist and which she says descends from the pine forests around Đà Lạt and from Antoni Gaudí. It remains her home, her office and, since 1990, a hotel open to the public.',
      es: 'Đặng Việt Nga se doctoró en arquitectura en Moscú y es hija de Trường Chinh, secretario general del Partido Comunista de Vietnam. Lleva más de treinta años construyendo una sola casa en Đà Lạt, y la construye sin planos: en lugar de proyectos pinta cuadros y los entrega a artesanos locales sin formación constructiva para que los conviertan en estructura. El resultado, la casa de huéspedes Hằng Nga, apenas tiene ángulos rectos: un baniano de hormigón de cinco alturas del que brotan cuevas, telarañas y habitaciones-animal, que la crítica ha llamado expresionista y que ella hace descender de los pinares de Đà Lạt y de Antoni Gaudí. Sigue siendo su vivienda, su estudio y, desde 1990, un hotel abierto al público.',
      it: "Đặng Việt Nga si è addottorata in architettura a Mosca ed è figlia di Trường Chinh, segretario generale del Partito Comunista del Vietnam. Da più di trent'anni costruisce una sola casa a Đà Lạt, e la costruisce senza disegni: invece di progetti dipinge quadri e li consegna ad artigiani locali privi di formazione edilizia perché li traducano in struttura. Il risultato, la pensione Hằng Nga, non ha quasi angoli retti: un banano di calcestruzzo alto cinque piani da cui germogliano grotte, ragnatele e stanze-animale, che la critica ha definito espressionista e che lei fa discendere dalle pinete attorno a Đà Lạt e da Antoni Gaudí. Resta la sua abitazione, il suo studio e, dal 1990, un albergo aperto al pubblico.",
    },
    awards: [],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/H%E1%BA%B1ng_Nga_guesthouse', title: 'Hằng Nga guesthouse', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://vi.wikipedia.org/wiki/Bi%E1%BB%87t_th%E1%BB%B1_H%E1%BA%B1ng_Nga', title: 'Biệt thự Hằng Nga (Vietnamese Wikipedia)', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'ling-siew-may',
    wikidataId: 'Q97818823',
    name: 'Ling Siew May',
    alternativeNames: ['林秀梅', 'Mrs Ong Teng Cheong'],
    gender: 'woman',
    born: 1937,
    died: 1999,
    floruit: { start: 1972, end: 1999, override: false },
    movements: 'unaffiliated',
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'educational',
    signatureMaterial: 'concrete',
    portrait: {
      en: 'Ling Siew May was born in Shanghai in 1937, separated from her family during the war and placed in an orphanage there, and reunited with her father in Singapore in 1948. She went to Nanyang Girls’ High School, then to the University of Adelaide, and in 1963 became the first Asian woman to graduate from it in architecture. In 1972 she and her husband Ong Teng Cheong founded the practice ONG&ONG, where she was a principal partner. When Ong became President of Singapore in 1993 she kept working, the first spouse of a head of state there to hold a job. Her last project, completed while she was terminally ill, was the new campus for her own school on Linden Drive; she opened it on 6 June 1999 and died seven weeks later.',
      es: 'Ling Siew May nació en Shanghái en 1937, quedó separada de su familia durante la guerra y fue internada allí en un orfanato, hasta reunirse con su padre en Singapur en 1948. Estudió en el Nanyang Girls’ High School y después en la Universidad de Adelaida, donde en 1963 fue la primera mujer asiática en licenciarse en arquitectura. En 1972 fundó con su marido, Ong Teng Cheong, el estudio ONG&ONG, del que fue socia principal. Cuando Ong accedió a la presidencia de Singapur en 1993 ella siguió trabajando: fue la primera cónyuge de un jefe de Estado del país con empleo propio. Su último proyecto, terminado ya enferma de gravedad, fue el nuevo campus de su propio colegio en Linden Drive; lo inauguró el 6 de junio de 1999 y murió siete semanas después.',
      it: "Ling Siew May nacque a Shanghai nel 1937, fu separata dalla famiglia durante la guerra e collocata lì in un orfanotrofio, per ricongiungersi al padre a Singapore nel 1948. Studiò alla Nanyang Girls’ High School e poi all'Università di Adelaide, dove nel 1963 fu la prima donna asiatica a laurearsi in architettura. Nel 1972 fondò con il marito Ong Teng Cheong lo studio ONG&ONG, di cui fu socia principale. Quando Ong divenne presidente di Singapore nel 1993 continuò a lavorare: fu la prima consorte di un capo di Stato del paese ad avere un impiego proprio. Il suo ultimo progetto, portato a termine ormai gravemente malata, fu il nuovo campus della sua stessa scuola in Linden Drive; lo inaugurò il 6 giugno 1999 e morì sette settimane più tardi.",
    },
    awards: [],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Ling_Siew_May', title: 'Ling Siew May', license: 'CC BY-SA 4.0' },
      { kind: 'institution', url: 'https://www.nlb.gov.sg/main/article-detail?cmsuuid=5ff9dd22-4fbc-4ed6-b419-999040269dd1', title: 'National Library Board Singapore, Infopedia — Ling Siew May', license: null },
    ],
  },

  // --- post-2000 ----------------------------------------------------------
  {
    id: 'kotchakorn-voraakhom',
    wikidataId: 'Q59160125',
    name: 'Kotchakorn Voraakhom',
    alternativeNames: ['กชกร วรอาคม', 'Kotchakorn Voraakhom (Landprocess)'],
    gender: 'woman',
    born: 1981,
    died: null,
    floruit: { start: 2015, end: 2021, override: false },
    movements: [{ id: 'sustainable-architecture', primary: true }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'infrastructure',
    signatureMaterial: 'concrete',
    portrait: {
      en: 'Kotchakorn Voraakhom is a Thai landscape architect who works on a city that is sinking. Bangkok sits about a metre and a half above sea level, and her practice Landprocess designs public ground that is engineered to flood on purpose rather than to shed water into an overwhelmed drainage system. She read landscape architecture at Chulalongkorn University, took a graduate degree at Harvard, co-founded the community design non-profit Kounkuey Design Initiative, and returned to Bangkok in 2006; she has taught at Chulalongkorn since 2010 and founded the Porous City Network in 2017. Her built work — the Chulalongkorn Centenary Park, the rooftop farm at Thammasat University, the Chong Nonsi canal park — treats retention volume as the primary design material, drawing on the Thai kaem ling or "monkey cheeks" model of holding runoff for later use.',
      es: 'Kotchakorn Voraakhom es una paisajista tailandesa que trabaja sobre una ciudad que se hunde. Bangkok se asienta a metro y medio sobre el nivel del mar, y su estudio, Landprocess, proyecta suelo público calculado para inundarse a propósito en lugar de verter el agua a una red de drenaje desbordada. Estudió arquitectura del paisaje en la Universidad de Chulalongkorn, cursó un posgrado en Harvard, cofundó la organización de diseño comunitario Kounkuey Design Initiative y regresó a Bangkok en 2006; enseña en Chulalongkorn desde 2010 y fundó la Porous City Network en 2017. Su obra construida —el Parque del Centenario de Chulalongkorn, la granja en cubierta de la Universidad Thammasat, el parque del canal de Chong Nonsi— trata el volumen de retención como material de proyecto, apoyándose en el modelo tailandés del kaem ling o «carrillos de mono», que almacena la escorrentía para usarla después.',
      it: "Kotchakorn Voraakhom è una paesaggista thailandese che lavora su una città che sprofonda. Bangkok sta a circa un metro e mezzo sul livello del mare, e il suo studio Landprocess progetta suolo pubblico calcolato per allagarsi di proposito anziché scaricare l'acqua in una rete fognaria già in crisi. Ha studiato architettura del paesaggio alla Chulalongkorn University, ha conseguito un master a Harvard, ha cofondato l'organizzazione di progettazione partecipata Kounkuey Design Initiative ed è tornata a Bangkok nel 2006; insegna alla Chulalongkorn dal 2010 e nel 2017 ha fondato la Porous City Network. Le sue opere — il Parco del Centenario della Chulalongkorn, la fattoria pensile della Thammasat University, il parco del canale di Chong Nonsi — trattano il volume d'invaso come materiale di progetto, richiamando il modello thailandese del kaem ling, le «guance di scimmia» che trattengono l'acqua per usarla poi.",
    },
    awards: ['TED Fellow (2018)'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Kotchakorn_Voraakhom', title: 'Kotchakorn Voraakhom', license: 'CC BY-SA 4.0' },
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q59160125', title: 'Kotchakorn Voraakhom (Q59160125)', license: null },
    ],
  },
  {
    id: 'wong-mun-summ',
    wikidataId: 'Q115592346',
    name: 'Wong Mun Summ',
    alternativeNames: ['黄文森', 'Wong Mun Summ (WOHA)'],
    gender: 'man',
    born: null,
    died: null,
    floruit: { start: 1994, end: 2020, override: false },
    movements: [{ id: 'sustainable-architecture', primary: true }, { id: 'tropical-modernism', primary: false }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'commercial',
    signatureMaterial: 'concrete',
    portrait: {
      en: 'Wong Mun Summ is the Singaporean co-founding director of WOHA, the practice he set up in 1994 with Richard Hassell after the two met working for Kerry Hill Architects; the name is made from the first two letters of their surnames, and the work is credited to the office rather than to either partner. WOHA began with private houses, won two Mass Rapid Transit station competitions in 2000, and drew international attention when the 1 Moulmein Rise apartment tower took the Aga Khan Award for Architecture in 2007. The office argues that density and greenery are not in conflict: its towers, hotels and public housing estates carry planted terraces, sky gardens and naturally ventilated circulation as structural parts of the brief rather than landscaping added afterwards.',
      es: 'Wong Mun Summ es el director cofundador singapurense de WOHA, el estudio que creó en 1994 con Richard Hassell tras coincidir ambos en Kerry Hill Architects; el nombre se forma con las dos primeras letras de sus apellidos y la autoría se atribuye a la oficina y no a ninguno de los dos socios. WOHA empezó con casas particulares, ganó en 2000 dos concursos de estaciones del metro y alcanzó proyección internacional cuando la torre de viviendas 1 Moulmein Rise obtuvo el Premio Aga Khan de Arquitectura en 2007. El estudio sostiene que densidad y vegetación no se contraponen: sus torres, hoteles y promociones de vivienda pública incorporan terrazas plantadas, jardines en altura y circulaciones ventiladas de forma natural como partes estructurales del encargo, no como paisajismo añadido después.',
      it: "Wong Mun Summ è il direttore cofondatore singaporiano di WOHA, lo studio nato nel 1994 con Richard Hassell dopo che i due si erano conosciuti da Kerry Hill Architects; il nome si compone delle prime due lettere dei loro cognomi e la paternità delle opere è attribuita allo studio e non a uno dei due soci. WOHA cominciò con case private, vinse nel 2000 due concorsi per stazioni della metropolitana e ottenne visibilità internazionale quando la torre residenziale 1 Moulmein Rise ricevette l'Aga Khan Award for Architecture nel 2007. Lo studio sostiene che densità e verde non siano in conflitto: torri, alberghi e complessi di edilizia pubblica portano terrazze piantumate, giardini pensili e percorsi a ventilazione naturale come parti strutturali del programma, non come paesaggio aggiunto in seguito.",
    },
    awards: ['Aga Khan Award for Architecture (2007, with WOHA)'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/WOHA', title: 'WOHA', license: 'CC BY-SA 4.0' },
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q115592346', title: 'Wong Mun Summ (Q115592346)', license: null },
    ],
  },
  {
    id: 'rizal-muslimin',
    wikidataId: 'Q126689352',
    name: 'Rizal Muslimin',
    alternativeNames: ['Muhammad Rizal Muslimin'],
    gender: 'man',
    born: null,
    died: null,
    floruit: { start: 2007, end: 2014, override: false },
    movements: 'unaffiliated',
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'sacral',
    signatureMaterial: 'concrete',
    portrait: {
      en: 'Rizal Muslimin is an Indonesian architect from Makassar who took his first degree at Universitas Katolik Parahyangan in 1999 and a master’s at the Bandung Institute of Technology in 2002, taught at Institut Teknologi Nasional in Bandung, and later completed a doctorate at MIT with a thesis on computational weaving grammars for architectural design. He now teaches at the University of Sydney. He is known in Indonesia for a single competition win: in 2007 his entry beat 322 others to become the Grand Mosque of West Sumatra in Padang. The design fuses two images — the outward-curving gonjong roof of the Minangkabau rumah gadang and the cloth on which, in Islamic tradition, four quarrelling Quraysh clans carried the Black Stone together — into one roof that reads as both.',
      es: 'Rizal Muslimin es un arquitecto indonesio originario de Makassar que se licenció en la Universitas Katolik Parahyangan en 1999, obtuvo el máster en el Instituto Tecnológico de Bandung en 2002, enseñó en el Institut Teknologi Nasional de Bandung y se doctoró después en el MIT con una tesis sobre gramáticas computacionales de tejido aplicadas al proyecto arquitectónico. Hoy es profesor en la Universidad de Sídney. En Indonesia se le conoce por un único concurso ganado: en 2007 su propuesta se impuso a otras 322 y se convirtió en la Gran Mezquita de Sumatra Occidental, en Padang. El proyecto funde dos imágenes —la cubierta de cuernos gonjong de la casa minangkabau rumah gadang y el paño sobre el que, según la tradición islámica, cuatro clanes enfrentados de los Quraish llevaron juntos la Piedra Negra— en un solo tejado que se lee como ambas.',
      it: "Rizal Muslimin è un architetto indonesiano originario di Makassar: si è laureato all'Universitas Katolik Parahyangan nel 1999, ha conseguito il master all'Istituto di Tecnologia di Bandung nel 2002, ha insegnato all'Institut Teknologi Nasional di Bandung e ha poi ottenuto il dottorato al MIT con una tesi sulle grammatiche computazionali dell'intreccio applicate al progetto architettonico. Oggi insegna all'Università di Sydney. In Indonesia è noto per un unico concorso vinto: nel 2007 la sua proposta superò altre 322 e divenne la Grande Moschea di Sumatra Occidentale, a Padang. Il progetto fonde due immagini — la copertura a corna gonjong della casa minangkabau rumah gadang e il telo su cui, secondo la tradizione islamica, quattro clan rivali dei Quraysh portarono insieme la Pietra Nera — in un solo tetto che si legge come entrambe.",
    },
    awards: [],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikipedia', url: 'https://id.wikipedia.org/wiki/Rizal_Muslimin', title: 'Rizal Muslimin (Indonesian Wikipedia)', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Grand_Mosque_of_West_Sumatra', title: 'Grand Mosque of West Sumatra', license: 'CC BY-SA 4.0' },
    ],
  },
];
