import type { Architect } from '@/types/architect';

// Wave 5 curator agent (Germany, Austria, Switzerland, Liechtenstein): real, sourced Architect entries for this slice.
//
// `workRegions` and `workCentroid` are deliberately left at their empty
// defaults: `npm run data:curate` derives both from each architect's
// buildings and overwrites whatever is written here.
//
// `floruit` is the span of documented *built* work, not the lifespan. Two
// pre-modern entries carry `override: true` because a building attributed to
// them was completed posthumously by another hand (Karlskirche 1737,
// Vierzehnheiligen 1772); the reason is stated in each portrait.
export const EUROPE_GERMANIC_ARCHITECTS: Architect[] = [
  {
    id: 'johann-bernhard-fischer-von-erlach',
    wikidataId: 'Q84305',
    name: 'Johann Bernhard Fischer von Erlach',
    alternativeNames: ['Johann Bernhard Fischer', 'Fischer von Erlach der Ältere'],
    gender: 'man',
    born: 1656,
    died: 1723,
    floruit: { start: 1687, end: 1723, override: true },
    movements: [{ id: 'baroque', primary: true }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'sacral',
    signatureMaterial: 'stone',
    portrait: {
      en: 'The son of a Graz sculptor, Fischer went to Rome at fourteen or fifteen and stayed until 1686, trained in the Schor workshop and moving in a circle that included Bernini and Carlo Fontana. He came back to Austria with something no local master builder had: a scholar\'s command of antiquity. He set it down in 1721 in Entwurff Einer Historischen Architectur, a folio of engravings he said had taken him sixteen years — not a neutral survey but an argument, made as Habsburg court architect, that imperial magnificence had historical warrant. Ennobled in 1696, he built the Winter Palace of Prince Eugene, Schönbrunn, the Court Library in Vienna and the Kollegienkirche in Salzburg. In 1715 he beat Johann Lucas von Hildebrandt to the Karlskirche commission. He died in Vienna in 1723; his son finished it.',
      es: 'Hijo de un escultor de Graz, Fischer marchó a Roma con catorce o quince años y permaneció allí hasta 1686, formado en el taller de los Schor y en un ambiente que frecuentaban Bernini y Carlo Fontana. Regresó a Austria con algo que ningún maestro de obras local poseía: un dominio erudito de la Antigüedad. Lo plasmó en 1721 en Entwurff Einer Historischen Architectur, un infolio de grabados en el que, según él mismo, trabajó dieciséis años: no un repertorio neutral, sino un alegato, formulado como arquitecto de la corte, de que la magnificencia imperial tenía respaldo histórico. Ennoblecido en 1696, levantó el Palacio de Invierno del príncipe Eugenio, Schönbrunn, la Biblioteca de la Corte de Viena y la Kollegienkirche de Salzburgo. En 1715 se impuso a Johann Lucas von Hildebrandt en el concurso de la Karlskirche. Murió en Viena en 1723; la terminó su hijo.',
      it: 'Figlio di uno scultore di Graz, Fischer partì per Roma a quattordici o quindici anni e vi rimase fino al 1686, formandosi nella bottega degli Schor e in un ambiente frequentato da Bernini e Carlo Fontana. Tornò in Austria con qualcosa che nessun capomastro locale possedeva: una padronanza erudita dell\'antico. La mise per iscritto nel 1721 in Entwurff Einer Historischen Architectur, un in-folio di incisioni al quale disse di aver lavorato sedici anni: non un repertorio neutrale ma una tesi, sostenuta da architetto di corte, secondo cui la magnificenza imperiale aveva fondamento storico. Nobilitato nel 1696, costruì il Palazzo d\'Inverno del principe Eugenio, Schönbrunn, la Biblioteca di Corte a Vienna e la Kollegienkirche di Salisburgo. Nel 1715 ebbe la meglio su Johann Lucas von Hildebrandt per la Karlskirche. Morì a Vienna nel 1723; la completò suo figlio.',
    },
    awards: ['Ennobled as "von Erlach" (1696)', 'Imperial court architect to the Habsburg court'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q84305', title: 'Johann Bernhard Fischer von Erlach (Q84305)', license: null },
      { kind: 'wikipedia', url: 'https://de.wikipedia.org/wiki/Johann_Bernhard_Fischer_von_Erlach', title: 'Johann Bernhard Fischer von Erlach', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'balthasar-neumann',
    wikidataId: 'Q61349',
    name: 'Balthasar Neumann',
    alternativeNames: ['Johann Balthasar Neumann'],
    gender: 'man',
    born: 1687,
    died: 1753,
    floruit: { start: 1720, end: 1753, override: true },
    movements: [{ id: 'baroque', primary: true }, { id: 'rococo', primary: false }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'sacral',
    signatureMaterial: 'stone',
    portrait: {
      en: 'Neumann reached architecture through gunnery. Born in Eger in 1687, the seventh of nine children of a clothmaker, he was apprenticed to his godfather, a bell and metal founder, and from 1711 worked in a Würzburg foundry, qualifying as a master gunner. In 1712 he enlisted as a private in the Franconian Circle artillery, the only route by which a civilian could become an engineer. The prince-bishop appointed him building director in 1719, and from 1720 he ran the Würzburg Residence. That ballistic training shows: his churches are exercises in the geometry of intersecting ovals, vaults calculated rather than composed, at Gößweinstein, Neresheim and above all Vierzehnheiligen. He died in Würzburg in 1753, nineteen years before Vierzehnheiligen was consecrated.',
      es: 'Neumann llegó a la arquitectura desde la artillería. Nacido en Eger en 1687, séptimo de nueve hijos de un pañero, se formó con su padrino, fundidor de campanas y metales, y desde 1711 trabajó en una fundición de Wurzburgo, donde obtuvo la carta de maestro artillero. En 1712 se alistó como soldado raso en la artillería del Círculo de Franconia, única vía por la que un civil podía llegar a ingeniero. El príncipe-obispo lo nombró director de obras en 1719 y desde 1720 dirigió la Residencia de Wurzburgo. Esa formación balística se nota: sus iglesias son ejercicios de geometría de óvalos que se intersecan, bóvedas calculadas antes que compuestas, en Gößweinstein, Neresheim y sobre todo Vierzehnheiligen. Murió en Wurzburgo en 1753, diecinueve años antes de la consagración de Vierzehnheiligen.',
      it: 'Neumann arrivò all\'architettura dall\'artiglieria. Nato a Eger nel 1687, settimo di nove figli di un panniere, fece il primo apprendistato presso il padrino, fonditore di campane e metalli, e dal 1711 lavorò in una fonderia di Würzburg, dove ottenne la patente di mastro bombardiere. Nel 1712 si arruolò come soldato semplice nell\'artiglieria del Circolo di Franconia, unica via per cui un civile potesse diventare ingegnere. Il principe-vescovo lo nominò direttore delle fabbriche nel 1719 e dal 1720 diresse la Residenza di Würzburg. Quella formazione balistica si vede: le sue chiese sono esercizi di geometria di ovali intersecanti, volte calcolate più che composte, a Gößweinstein, Neresheim e soprattutto a Vierzehnheiligen. Morì a Würzburg nel 1753, diciannove anni prima della consacrazione di Vierzehnheiligen.',
    },
    awards: ['Prince-episcopal building director, Würzburg (from 1719)'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q61349', title: 'Johann Balthasar Neumann (Q61349)', license: null },
      { kind: 'wikipedia', url: 'https://de.wikipedia.org/wiki/Balthasar_Neumann', title: 'Balthasar Neumann', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'walter-gropius',
    wikidataId: 'Q61071',
    name: 'Walter Gropius',
    alternativeNames: ['Walter Adolph Georg Gropius'],
    gender: 'man',
    born: 1883,
    died: 1969,
    floruit: { start: 1911, end: 1969, override: false },
    movements: [{ id: 'bauhaus', primary: true }, { id: 'international-style', primary: false }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'educational',
    signatureMaterial: 'steel-and-glass',
    portrait: {
      en: 'Gropius built the Fagus factory at Alfeld in 1911 with Adolf Meyer, hanging glass in front of the structure rather than between piers, and spent the rest of his life arguing the consequences. In 1919 he founded the Bauhaus in Weimar and directed it until 1928, first in Weimar and, from 1925, in the building he designed for it in Dessau. His interest was less a style than a method: workshops rather than ateliers, and a curriculum that put craft training before design. He emigrated to England in 1934 and to the United States in 1937, where he taught at the Harvard Graduate School of Design and co-founded The Architects Collaborative, a practice deliberately organised so that no single name signed the work. He won the Royal Gold Medal in 1956 and the AIA Gold Medal in 1959.',
      es: 'Gropius construyó en 1911, con Adolf Meyer, la fábrica Fagus de Alfeld, colgando el vidrio por delante de la estructura en lugar de encajarlo entre pilares, y dedicó el resto de su vida a extraer las consecuencias. En 1919 fundó la Bauhaus en Weimar y la dirigió hasta 1928, primero allí y, desde 1925, en el edificio que proyectó para ella en Dessau. Le interesaba menos un estilo que un método: talleres en vez de ateliers y un plan de estudios que anteponía el oficio al proyecto. Emigró a Inglaterra en 1934 y a Estados Unidos en 1937, donde enseñó en la Harvard Graduate School of Design y cofundó The Architects Collaborative, un despacho organizado deliberadamente para que ningún nombre firmara la obra en solitario. Recibió la Royal Gold Medal en 1956 y la Medalla de Oro del AIA en 1959.',
      it: 'Nel 1911 Gropius costruì con Adolf Meyer la fabbrica Fagus ad Alfeld, appendendo il vetro davanti alla struttura anziché incastrarlo fra i pilastri, e passò il resto della vita a trarne le conseguenze. Nel 1919 fondò il Bauhaus a Weimar e lo diresse fino al 1928, prima lì e, dal 1925, nell\'edificio che progettò per la scuola a Dessau. Gli interessava meno uno stile che un metodo: officine anziché atelier, e un percorso che anteponeva il mestiere al progetto. Emigrò in Inghilterra nel 1934 e negli Stati Uniti nel 1937, dove insegnò alla Harvard Graduate School of Design e cofondò The Architects Collaborative, uno studio organizzato apposta perché nessun nome firmasse da solo il lavoro. Ottenne la Royal Gold Medal nel 1956 e la Medaglia d\'oro dell\'AIA nel 1959.',
    },
    awards: ['Royal Gold Medal (1956)', 'AIA Gold Medal (1959)', 'Goethe Prize of the City of Frankfurt (1961)'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q61071', title: 'Walter Gropius (Q61071)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Walter_Gropius', title: 'Walter Gropius', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://de.wikipedia.org/wiki/Bauhausgeb%C3%A4ude_Dessau', title: 'Bauhausgebäude Dessau', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'mies-van-der-rohe',
    wikidataId: 'Q41508',
    name: 'Ludwig Mies van der Rohe',
    alternativeNames: ['Maria Ludwig Michael Mies', 'Mies'],
    gender: 'man',
    born: 1886,
    died: 1969,
    floruit: { start: 1907, end: 1969, override: false },
    movements: [{ id: 'international-style', primary: true }, { id: 'bauhaus', primary: false }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'tower',
    signatureMaterial: 'steel-and-glass',
    portrait: {
      en: 'A stonemason\'s son from Aachen with no formal architectural training, Mies worked for Bruno Paul and Peter Behrens before the First World War and emerged in the 1920s with the Barcelona Pavilion and Haus Tugendhat: free-standing planes, continuous space, one material set against another. Much of that work was made with the interior architect Lilly Reich, his collaborator from the late 1920s, with whom he designed the Glasraum, the Velvet and Silk Café and the Tugendhat interiors. He was the Bauhaus\'s third and last director from 1930 to 1933. In the United States from 1937–38 he headed the architecture school at what became the Illinois Institute of Technology and built the tall steel-and-glass buildings — 860–880 Lake Shore Drive, the Seagram Building — that made the type. He returned to Berlin once more, for the Neue Nationalgalerie.',
      es: 'Hijo de un cantero de Aquisgrán y sin formación académica en arquitectura, Mies trabajó con Bruno Paul y Peter Behrens antes de la Primera Guerra Mundial y se reveló en los años veinte con el Pabellón de Barcelona y la casa Tugendhat: planos exentos, espacio continuo, un material enfrentado a otro. Buena parte de esa obra se hizo con la interiorista Lilly Reich, colaboradora suya desde finales de los años veinte, con quien proyectó el Glasraum, el Café de Terciopelo y Seda y los interiores de la Tugendhat. Fue el tercer y último director de la Bauhaus, entre 1930 y 1933. En Estados Unidos desde 1937-38 dirigió la escuela de arquitectura del futuro Illinois Institute of Technology y levantó los edificios altos de acero y vidrio —860-880 Lake Shore Drive, el Seagram— que fijaron el tipo. Volvió una vez más a Berlín, para la Neue Nationalgalerie.',
      it: 'Figlio di uno scalpellino di Aquisgrana e privo di formazione accademica, Mies lavorò con Bruno Paul e Peter Behrens prima della Grande Guerra e si impose negli anni Venti con il Padiglione di Barcellona e Casa Tugendhat: piani liberi, spazio continuo, un materiale contrapposto a un altro. Buona parte di quel lavoro nacque con l\'architetta d\'interni Lilly Reich, sua collaboratrice dalla fine degli anni Venti, con cui progettò il Glasraum, il Caffè di Velluto e Seta e gli interni della Tugendhat. Fu il terzo e ultimo direttore del Bauhaus, dal 1930 al 1933. Negli Stati Uniti dal 1937-38 diresse la scuola di architettura del futuro Illinois Institute of Technology e costruì gli edifici alti in acciaio e vetro — 860-880 Lake Shore Drive, il Seagram — che fissarono il tipo. Tornò a Berlino un\'ultima volta, per la Neue Nationalgalerie.',
    },
    awards: ['Pour le Mérite for Sciences and Arts (1957)', 'Royal Gold Medal (1959)', 'AIA Gold Medal (1960)', 'Presidential Medal of Freedom (1963)'],
    tier: 'canon',
    context: {
      body: {
        en: 'German Wikipedia records that the Dessau Bauhaus was closed in 1932 for political reasons by a newly elected city council with a National Socialist majority; Mies, its director, re-established it as a private institute in Berlin-Lankwitz and had to abandon it in mid-1933 under pressure from the new Reich government, which attacked the school for its socialist sympathies. The same article states that his subsequent conduct towards the regime has often been criticised as opportunistic: in 1934 he joined the Reichskulturkammer and the National Socialist People\'s Welfare; on 18 August 1934 he signed the appeal by cultural figures supporting Adolf Hitler published in the Völkischer Beobachter; he took part in the exhibition Deutsches Volk – Deutsche Arbeit; and his unbuilt design for the German contribution to the 1934 Brussels world\'s fair was commissioned by the Ministry of Public Enlightenment and Propaganda. He was nonetheless progressively excluded, and in 1937 was pushed to leave the Prussian Academy of Arts. He emigrated to the United States in 1937–38.',
        es: 'La Wikipedia alemana recoge que la Bauhaus de Dessau fue cerrada en 1932 por motivos políticos por un consistorio recién elegido con mayoría nacionalsocialista; Mies, su director, la reinstaló como instituto privado en Berlín-Lankwitz y tuvo que abandonarla a mediados de 1933 por la presión del nuevo gobierno del Reich, que atacaba a la escuela por sus simpatías socialistas. El mismo artículo señala que su conducta posterior ante el régimen ha sido criticada a menudo como oportunista: en 1934 ingresó en la Reichskulturkammer y en la Beneficencia Popular Nacionalsocialista; el 18 de agosto de 1934 firmó el llamamiento de los creadores de cultura en apoyo de Adolf Hitler publicado en el Völkischer Beobachter; participó en la exposición Deutsches Volk – Deutsche Arbeit; y su proyecto no construido para la aportación alemana a la Exposición Universal de Bruselas de 1934 fue encargado por el Ministerio de Propaganda. Aun así fue excluido de forma progresiva y en 1937 se lo empujó a dejar la Academia Prusiana de las Artes. Emigró a Estados Unidos en 1937-38.',
        it: 'La Wikipedia tedesca riporta che il Bauhaus di Dessau fu chiuso nel 1932 per ragioni politiche da un consiglio comunale appena eletto a maggioranza nazionalsocialista; Mies, che ne era direttore, lo riaprì come istituto privato a Berlino-Lankwitz e dovette rinunciarvi a metà 1933 per la pressione del nuovo governo del Reich, che attaccava la scuola per le sue simpatie socialiste. Lo stesso articolo osserva che la sua condotta successiva verso il regime è stata spesso criticata come opportunista: nel 1934 entrò nella Reichskulturkammer e nell\'Assistenza popolare nazionalsocialista; il 18 agosto 1934 firmò l\'appello degli operatori della cultura a sostegno di Adolf Hitler pubblicato sul Völkischer Beobachter; partecipò alla mostra Deutsches Volk – Deutsche Arbeit; e il suo progetto non realizzato per il contributo tedesco all\'Esposizione universale di Bruxelles del 1934 fu commissionato dal Ministero della Propaganda. Fu comunque escluso progressivamente e nel 1937 spinto a lasciare l\'Accademia prussiana delle arti. Emigrò negli Stati Uniti nel 1937-38.',
      },
      sources: [
        { kind: 'wikipedia', url: 'https://de.wikipedia.org/wiki/Ludwig_Mies_van_der_Rohe', title: 'Ludwig Mies van der Rohe — Ende der Republik und Nationalsozialismus', license: 'CC BY-SA 4.0' },
        { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Bauhaus', title: 'Bauhaus', license: 'CC BY-SA 4.0' },
      ],
    },
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q41508', title: 'Ludwig Mies van der Rohe (Q41508)', license: null },
      { kind: 'wikipedia', url: 'https://de.wikipedia.org/wiki/Ludwig_Mies_van_der_Rohe', title: 'Ludwig Mies van der Rohe', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Ludwig_Mies_van_der_Rohe', title: 'Ludwig Mies van der Rohe', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'albert-speer',
    wikidataId: 'Q60045',
    name: 'Albert Speer',
    alternativeNames: ['Berthold Konrad Hermann Albert Speer'],
    gender: 'man',
    born: 1905,
    died: 1981,
    floruit: { start: 1933, end: 1942, override: false },
    movements: [{ id: 'neoclassicism', primary: true }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'civic',
    signatureMaterial: 'stone',
    portrait: {
      en: 'Speer trained as an architect and joined the Nazi Party in 1931. Hitler commissioned him to design the Reich Chancellery and the party rally grounds at Nuremberg, and in 1937 appointed him General Building Inspector for Berlin, a post in which he was responsible for the Central Department for Resettlement that evicted Jewish tenants from their homes in the city. His built work is stripped classicism at a scale calculated for massed ranks: ashlar limestone facing, unmoulded pilaster ranges, axes hundreds of metres long. In February 1942 he became Reich Minister of Armaments and War Production. Very little of the architecture was ever finished — the Reich Chancellery was demolished after the war and the Berlin plans were never built — so the Nuremberg grandstands, themselves mutilated, are among the few surviving fragments.',
      es: 'Speer se formó como arquitecto y se afilió al partido nazi en 1931. Hitler le encargó la Nueva Cancillería del Reich y el recinto de congresos del partido en Núremberg, y en 1937 lo nombró Inspector General de Construcción de Berlín, cargo desde el que fue responsable del Departamento Central de Reasentamiento que desalojó a inquilinos judíos de sus viviendas en la ciudad. Su obra construida es un clasicismo despojado a una escala calculada para formaciones en masa: revestimiento de sillería caliza, órdenes de pilastras sin moldurar, ejes de cientos de metros. En febrero de 1942 pasó a ser ministro de Armamento y Producción de Guerra del Reich. Casi nada de aquella arquitectura llegó a terminarse —la Cancillería fue demolida tras la guerra y los planes berlineses nunca se construyeron—, de modo que las tribunas de Núremberg, ellas mismas mutiladas, son de los pocos restos que quedan.',
      it: 'Speer si formò come architetto e aderì al partito nazista nel 1931. Hitler gli commissionò la Nuova Cancelleria del Reich e l\'area dei raduni del partito a Norimberga e nel 1937 lo nominò Ispettore generale per l\'edilizia di Berlino, carica nella quale fu responsabile del Dipartimento centrale per il reinsediamento che sfrattò gli inquilini ebrei dalle loro case in città. La sua opera costruita è un classicismo spogliato a una scala calcolata per formazioni di massa: rivestimento in conci calcarei, ordini di lesene senza modanature, assi lunghi centinaia di metri. Nel febbraio 1942 divenne ministro del Reich per gli armamenti e la produzione bellica. Di quell\'architettura fu portato a termine pochissimo — la Cancelleria fu demolita dopo la guerra e i piani per Berlino non furono mai costruiti — sicché le tribune di Norimberga, esse stesse mutilate, sono fra i pochi frammenti superstiti.',
    },
    awards: [],
    tier: 'canon',
    context: {
      body: {
        en: 'Speer was one of the twenty-four major defendants charged before the International Military Tribunal at Nuremberg. He was found guilty of war crimes and crimes against humanity, principally for the use of slave labour, and narrowly avoided a death sentence; he was sentenced to twenty years, served the full term in Spandau prison and was released in 1966. English Wikipedia notes that in 1944 he had established a task force to increase fighter-aircraft production that became instrumental in exploiting slave labour for the German war effort, and that through his memoirs and interviews he carefully constructed an image of himself as a man who regretted having failed to discover the crimes of the Third Reich, continuing to deny explicit knowledge of and responsibility for the Holocaust — an image that dominated the historiography for decades and has since been challenged. He died of a stroke in 1981.',
        es: 'Speer fue uno de los veinticuatro acusados principales ante el Tribunal Militar Internacional de Núremberg. Fue declarado culpable de crímenes de guerra y crímenes contra la humanidad, sobre todo por el empleo de trabajo esclavo, y se libró por poco de la pena de muerte; fue condenado a veinte años, cumplió la pena íntegra en la prisión de Spandau y salió en libertad en 1966. La Wikipedia en inglés señala que en 1944 había creado un grupo de trabajo para aumentar la producción de cazas que resultó decisivo en la explotación de trabajo esclavo para el esfuerzo bélico alemán, y que mediante sus memorias y entrevistas construyó cuidadosamente la imagen de un hombre que lamentaba no haber descubierto los crímenes del Tercer Reich, negando siempre haber tenido conocimiento explícito del Holocausto y responsabilidad en él: una imagen que dominó la historiografía durante décadas y que después ha sido rebatida. Murió de un ictus en 1981.',
        it: 'Speer fu uno dei ventiquattro imputati principali davanti al Tribunale militare internazionale di Norimberga. Fu riconosciuto colpevole di crimini di guerra e crimini contro l\'umanità, soprattutto per l\'impiego di lavoro schiavistico, sfuggendo per poco alla condanna a morte; fu condannato a vent\'anni, scontò per intero la pena nel carcere di Spandau e fu rilasciato nel 1966. La Wikipedia inglese osserva che nel 1944 aveva istituito una task force per aumentare la produzione di caccia che divenne decisiva nello sfruttamento del lavoro schiavistico per lo sforzo bellico tedesco, e che attraverso memorie e interviste costruì con cura l\'immagine di un uomo che rimpiangeva di non essersi accorto dei crimini del Terzo Reich, continuando a negare di averne avuto conoscenza esplicita e responsabilità: un\'immagine che ha dominato la storiografia per decenni e che è stata in seguito contestata. Morì di ictus nel 1981.',
      },
      sources: [
        { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Albert_Speer', title: 'Albert Speer', license: 'CC BY-SA 4.0' },
        { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q60045', title: 'Albert Speer (Q60045)', license: null },
      ],
    },
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q60045', title: 'Albert Speer (Q60045)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Albert_Speer', title: 'Albert Speer', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://de.wikipedia.org/wiki/Zeppelintrib%C3%BCne', title: 'Zeppelintribüne', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'margarete-schuette-lihotzky',
    wikidataId: 'Q78858',
    name: 'Margarete Schütte-Lihotzky',
    alternativeNames: ['Margarete Lihotzky', 'Grete Schütte-Lihotzky'],
    gender: 'woman',
    born: 1897,
    died: 2000,
    floruit: { start: 1921, end: 1960, override: false },
    movements: [{ id: 'functionalism', primary: true }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'housing',
    signatureMaterial: 'mixed',
    portrait: {
      en: 'Schütte-Lihotzky studied at the Vienna Kunstgewerbeschule from 1915, among the first women in Austria to read architecture and probably the first to practise it fully. She later recalled that in 1916 nobody believed a woman would ever be commissioned to build a house — herself included. She worked with Adolf Loos on the Friedensstadt settlement in 1921, then joined Ernst May\'s municipal building department in Frankfurt in 1926, where she designed the Frankfurt Kitchen: a galley laid out from time-and-motion study, of which some twelve thousand were installed in the city\'s new estates. Moscow and Istanbul followed. She was the only woman among the architects of the Vienna Werkbundsiedlung in 1932. After 1945 she built schools and kindergartens in Vienna, and lived to be a hundred and two.',
      es: 'Schütte-Lihotzky estudió en la Kunstgewerbeschule de Viena desde 1915, entre las primeras mujeres que cursaron arquitectura en Austria y probablemente la primera que ejerció la profesión de forma plena. Recordaba que en 1916 nadie creía que jamás se encargaría una casa a una mujer, ni siquiera ella misma. Trabajó con Adolf Loos en la colonia Friedensstadt en 1921 y en 1926 entró en la oficina municipal de obras de Ernst May en Fráncfort, donde proyectó la cocina de Fráncfort: una cocina en línea derivada del estudio de tiempos y movimientos, de la que se instalaron unas doce mil en las nuevas barriadas de la ciudad. Después vinieron Moscú y Estambul. Fue la única mujer entre los arquitectos de la Werkbundsiedlung vienesa de 1932. Tras 1945 construyó escuelas y jardines de infancia en Viena, y vivió ciento dos años.',
      it: 'Schütte-Lihotzky studiò alla Kunstgewerbeschule di Vienna dal 1915, fra le prime donne in Austria a studiare architettura e probabilmente la prima a esercitarla pienamente. Ricordava che nel 1916 nessuno credeva che a una donna sarebbe mai stata commissionata una casa, lei compresa. Lavorò con Adolf Loos alla colonia Friedensstadt nel 1921 e nel 1926 entrò nell\'ufficio tecnico comunale di Ernst May a Francoforte, dove progettò la cucina di Francoforte: una cucina in linea ricavata dallo studio dei tempi e dei movimenti, di cui ne furono installate circa dodicimila nei nuovi quartieri della città. Seguirono Mosca e Istanbul. Fu l\'unica donna fra gli architetti della Werkbundsiedlung viennese del 1932. Dopo il 1945 costruì scuole e asili a Vienna, e visse centodue anni.',
    },
    awards: ['City of Vienna Prize for Architecture (1980)', 'Austrian Decoration for Science and Art (1992)', 'Ring of Honour of the City of Vienna'],
    tier: 'canon',
    context: {
      body: {
        en: 'In 1939, in Istanbul, Schütte-Lihotzky and her husband joined an exile group of the Austrian Communist Party founded by the architect Herbert Eichholzer to support the resistance in Austria after the Anschluss. In December 1940 she travelled to Vienna on the group\'s behalf as a courier. Weeks after her arrival, on 22 January 1941, she was arrested by the Gestapo together with Erwin Puschmann, the head of the resistance group, after being betrayed by an informer. She was charged with high treason and the prosecutor demanded the death penalty for all the accused. Three of them — Puschmann, Franz Sebek and Karl Lisetz — were executed on 5 March 1943. On 22 September 1942 the People\'s Court sentenced Schütte-Lihotzky to fifteen years; she was held in the women\'s penitentiary at Aichach in Bavaria and freed by American troops in April 1945.',
        es: 'En 1939, en Estambul, Schütte-Lihotzky y su marido se sumaron a un grupo en el exilio del Partido Comunista de Austria fundado por el arquitecto Herbert Eichholzer para apoyar a la resistencia austríaca tras el Anschluss. En diciembre de 1940 viajó a Viena por encargo del grupo, como enlace. Pocas semanas después de llegar, el 22 de enero de 1941, fue detenida por la Gestapo junto con Erwin Puschmann, responsable del grupo de resistencia, tras la delación de un confidente. Se la acusó de alta traición y el fiscal pidió la pena de muerte para todos los procesados. Tres de ellos —Puschmann, Franz Sebek y Karl Lisetz— fueron ejecutados el 5 de marzo de 1943. El 22 de septiembre de 1942 el Tribunal del Pueblo condenó a Schütte-Lihotzky a quince años; cumplió condena en el penal de mujeres de Aichach, en Baviera, y fue liberada por tropas estadounidenses en abril de 1945.',
        it: 'Nel 1939, a Istanbul, Schütte-Lihotzky e il marito aderirono a un gruppo in esilio del Partito comunista austriaco fondato dall\'architetto Herbert Eichholzer per sostenere la resistenza in Austria dopo l\'Anschluss. Nel dicembre 1940 partì per Vienna per conto del gruppo, come staffetta. Poche settimane dopo l\'arrivo, il 22 gennaio 1941, fu arrestata dalla Gestapo insieme a Erwin Puschmann, responsabile del gruppo di resistenza, in seguito alla delazione di un informatore. Fu accusata di alto tradimento e il pubblico ministero chiese la pena di morte per tutti gli imputati. Tre di loro — Puschmann, Franz Sebek e Karl Lisetz — furono giustiziati il 5 marzo 1943. Il 22 settembre 1942 il Tribunale del popolo condannò Schütte-Lihotzky a quindici anni; fu detenuta nel penitenziario femminile di Aichach, in Baviera, e liberata dalle truppe americane nell\'aprile 1945.',
      },
      sources: [
        { kind: 'wikipedia', url: 'https://de.wikipedia.org/wiki/Margarete_Sch%C3%BCtte-Lihotzky', title: 'Margarete Schütte-Lihotzky — Widerstand und Haft', license: 'CC BY-SA 4.0' },
      ],
    },
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q78858', title: 'Margarete Schütte-Lihotzky (Q78858)', license: null },
      { kind: 'wikipedia', url: 'https://de.wikipedia.org/wiki/Margarete_Sch%C3%BCtte-Lihotzky', title: 'Margarete Schütte-Lihotzky', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'peter-zumthor',
    wikidataId: 'Q123179',
    name: 'Peter Zumthor',
    alternativeNames: [],
    gender: 'man',
    born: 1943,
    died: null,
    floruit: { start: 1988, end: 2018, override: false },
    movements: [{ id: 'minimalism', primary: true }, { id: 'critical-regionalism', primary: false }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'cultural',
    signatureMaterial: 'stone',
    portrait: {
      en: 'Zumthor is a cabinetmaker\'s son who trained as a furniture joiner in his father\'s workshop at Oberwil before studying interior design in Basel and architecture at Pratt Institute in New York. He then spent ten years as a conservation officer for the canton of Graubünden, working on historic fabric in Alpine side valleys — an unusual apprenticeship that left him with a builder\'s attention to how a joint is made and how a surface ages. He opened his own office at Haldenstein in 1979 and has kept it deliberately small, refusing more work than he takes. The buildings are few and slow: the chapel at Sumvitg, the thermal baths at Vals, the Kunsthaus Bregenz, Kolumba in Cologne. He received the Pritzker Prize in 2009 and the Royal Gold Medal in 2013.',
      es: 'Zumthor es hijo de un ebanista y se formó como carpintero de muebles en el taller paterno de Oberwil antes de estudiar interiorismo en Basilea y arquitectura en el Pratt Institute de Nueva York. Después pasó diez años como técnico de patrimonio del cantón de los Grisones, trabajando sobre fábricas históricas en los valles laterales alpinos: un aprendizaje insólito que le dejó una atención de constructor al modo en que se resuelve un encuentro y a cómo envejece una superficie. Abrió su despacho en Haldenstein en 1979 y lo ha mantenido pequeño a propósito, rechazando más encargos de los que acepta. Las obras son pocas y lentas: la capilla de Sumvitg, las termas de Vals, la Kunsthaus de Bregenz, el Kolumba de Colonia. Recibió el Pritzker en 2009 y la Royal Gold Medal en 2013.',
      it: 'Zumthor è figlio di un ebanista e si formò come falegname da mobili nella bottega paterna di Oberwil prima di studiare interior design a Basilea e architettura al Pratt Institute di New York. Trascorse poi dieci anni come funzionario per la tutela del patrimonio del cantone dei Grigioni, lavorando su fabbriche storiche nelle valli laterali alpine: un tirocinio insolito che gli ha lasciato un\'attenzione da costruttore al modo in cui si risolve un giunto e a come invecchia una superficie. Aprì il proprio studio a Haldenstein nel 1979 e lo ha tenuto volutamente piccolo, rifiutando più incarichi di quanti ne accetti. Le opere sono poche e lente: la cappella di Sumvitg, le terme di Vals, la Kunsthaus di Bregenz, il Kolumba di Colonia. Ha ricevuto il Pritzker nel 2009 e la Royal Gold Medal nel 2013.',
    },
    awards: ['Pritzker Architecture Prize (2009)', 'Royal Gold Medal (2013)', 'Praemium Imperiale (2008)', 'European Union Prize for Contemporary Architecture – Mies van der Rohe Award (1998)', 'Carlsberg Architectural Prize (1998)'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q123179', title: 'Peter Zumthor (Q123179)', license: null },
      { kind: 'wikipedia', url: 'https://de.wikipedia.org/wiki/Peter_Zumthor', title: 'Peter Zumthor', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'gottfried-boehm',
    wikidataId: 'Q76841',
    name: 'Gottfried Böhm',
    alternativeNames: ['Gottfried Leo Böhm'],
    gender: 'man',
    born: 1920,
    died: 2021,
    floruit: { start: 1950, end: 2005, override: false },
    movements: [{ id: 'expressionism', primary: true }, { id: 'brutalism', primary: false }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'sacral',
    signatureMaterial: 'concrete',
    portrait: {
      en: 'Böhm was born in Offenbach in 1920 into the third generation of a family of church architects; his father Dominikus Böhm was among the most inventive German church builders of the 1920s. He trained as a sculptor as well as an architect, and it shows in work that is modelled rather than assembled. His first independent building was the Cologne chapel Madonna in den Trümmern, built into a bombed church between 1947 and 1950. What followed — Nevigeser Wallfahrtsdom, the Bensberg town hall, the Bergisch Gladbach and Bocholt churches — is a body of sculptural work in concrete, steel and glass. In 1986 he became the first German architect to receive the Pritzker Prize. He died in Cologne in 2021, aged a hundred and one.',
      es: 'Böhm nació en Offenbach en 1920, tercera generación de una familia de arquitectos de iglesias; su padre, Dominikus Böhm, fue uno de los constructores de iglesias más inventivos de la Alemania de los años veinte. Se formó también como escultor, y se nota en una obra que está modelada más que ensamblada. Su primer edificio propio fue la capilla colonesa Madonna in den Trümmern, levantada entre 1947 y 1950 dentro de una iglesia bombardeada. Lo que vino después —el santuario de Neviges, el ayuntamiento de Bensberg, las iglesias de Bergisch Gladbach y Bocholt— constituye un corpus escultórico en hormigón, acero y vidrio. En 1986 fue el primer arquitecto alemán en recibir el Premio Pritzker. Murió en Colonia en 2021, a los ciento un años.',
      it: 'Böhm nacque a Offenbach nel 1920, terza generazione di una famiglia di architetti di chiese; suo padre Dominikus Böhm fu tra i costruttori di chiese più inventivi della Germania degli anni Venti. Si formò anche come scultore, e si vede in un\'opera che è modellata più che assemblata. Il suo primo edificio autonomo fu la cappella coloniese Madonna in den Trümmern, ricavata fra il 1947 e il 1950 dentro una chiesa bombardata. Quel che seguì — il santuario di Neviges, il municipio di Bensberg, le chiese di Bergisch Gladbach e Bocholt — costituisce un corpus scultoreo in calcestruzzo, acciaio e vetro. Nel 1986 fu il primo architetto tedesco a ricevere il Premio Pritzker. Morì a Colonia nel 2021, a centouno anni.',
    },
    awards: ['Pritzker Architecture Prize (1986)', 'Berliner Kunstpreis (1974)', 'State Prize of North Rhine-Westphalia (1996)'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q76841', title: 'Gottfried Böhm (Q76841)', license: null },
      { kind: 'wikipedia', url: 'https://de.wikipedia.org/wiki/Gottfried_B%C3%B6hm', title: 'Gottfried Böhm', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'guenter-behnisch',
    wikidataId: 'Q60694',
    name: 'Günter Behnisch',
    alternativeNames: ['Behnisch & Partner'],
    gender: 'man',
    born: 1922,
    died: 2010,
    floruit: { start: 1952, end: 2005, override: false },
    movements: [{ id: 'high-tech', primary: true }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'civic',
    signatureMaterial: 'steel-and-glass',
    portrait: {
      en: 'Behnisch volunteered for the German navy at seventeen in 1939, served on U-boats, took command of U 2337 in October 1944 and spent 1945 to 1947 in British captivity. He studied architecture at Stuttgart from 1947, opened his own office there in 1952 and founded Behnisch & Partner in 1966. German Wikipedia describes him as an advocate of democratic building without any symbolism of status or power, and the description fits: schools, the Bonn Bundestag chamber, the Hysolar institute, buildings that avoid the monumental axis on principle. Worldwide recognition came with the Munich Olympic grounds of 1967–1972. He was professor at Darmstadt from 1967 to 1987 and joined the Akademie der Künste in Berlin in 1982. He died in Stuttgart in 2010.',
      es: 'Behnisch se alistó voluntario en la marina alemana con diecisiete años, en 1939, sirvió en submarinos, asumió el mando del U 2337 en octubre de 1944 y pasó de 1945 a 1947 en cautiverio británico. Estudió arquitectura en Stuttgart desde 1947, abrió allí su propio despacho en 1952 y fundó Behnisch & Partner en 1966. La Wikipedia alemana lo describe como defensor de una construcción democrática sin simbología alguna de estatus o de poder, y la descripción encaja: escuelas, el hemiciclo del Bundestag en Bonn, el instituto Hysolar, edificios que rehúyen por principio el eje monumental. El reconocimiento mundial le llegó con el recinto olímpico de Múnich de 1967-1972. Fue catedrático en Darmstadt de 1967 a 1987 y entró en la Akademie der Künste de Berlín en 1982. Murió en Stuttgart en 2010.',
      it: 'Behnisch si arruolò volontario nella marina tedesca a diciassette anni, nel 1939, prestò servizio sui sommergibili, assunse il comando dell\'U 2337 nell\'ottobre 1944 e passò dal 1945 al 1947 in prigionia britannica. Studiò architettura a Stoccarda dal 1947, vi aprì il proprio studio nel 1952 e fondò Behnisch & Partner nel 1966. La Wikipedia tedesca lo descrive come sostenitore di un costruire democratico privo di qualsiasi simbologia di status o di potere, e la descrizione calza: scuole, l\'aula del Bundestag a Bonn, l\'istituto Hysolar, edifici che rifiutano per principio l\'asse monumentale. La notorietà mondiale gli venne dall\'area olimpica di Monaco del 1967-1972. Fu professore a Darmstadt dal 1967 al 1987 ed entrò nell\'Akademie der Künste di Berlino nel 1982. Morì a Stoccarda nel 2010.',
    },
    awards: ['Member of the Akademie der Künste, Berlin (1982)', 'Honorary doctorate, University of Stuttgart (1984)'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q60694', title: 'Günter Behnisch (Q60694)', license: null },
      { kind: 'wikipedia', url: 'https://de.wikipedia.org/wiki/G%C3%BCnter_Behnisch', title: 'Günter Behnisch', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'iris-grund',
    wikidataId: 'Q48203522',
    name: 'Iris Grund',
    alternativeNames: ['Iris Dullin-Grund', 'Iris Dullin'],
    gender: 'woman',
    born: 1933,
    died: null,
    floruit: { start: 1965, end: 1990, override: false },
    movements: [{ id: 'functionalism', primary: true }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'cultural',
    signatureMaterial: 'concrete',
    portrait: {
      en: 'Grund studied architecture at the Kunsthochschule Berlin-Weißensee from 1952 to 1957, taught among others by Selman Selmanagić, who had trained at the Bauhaus. She worked for two years in Hermann Henselmann\'s office and briefly for Ernst May in Hamburg in 1959, returning to the German Democratic Republic the same year out of political conviction. That year, aged twenty-six, she won the competition for the Haus der Kultur und Bildung in Neubrandenburg, opened in 1965. From 1970 to 1990 she was Neubrandenburg\'s city architect — the highest position an architect could hold in the GDR, and one that no woman held in West Germany at the time. She was one of the most influential architects of the GDR, and published an autobiography in 2004.',
      es: 'Grund estudió arquitectura en la Kunsthochschule Berlin-Weißensee entre 1952 y 1957, con profesores como Selman Selmanagić, formado en la Bauhaus. Trabajó dos años en el estudio de Hermann Henselmann y brevemente con Ernst May en Hamburgo en 1959, para regresar ese mismo año a la República Democrática Alemana por convicción política. Ese año, con veintiséis, ganó el concurso de la Haus der Kultur und Bildung de Neubrandenburgo, inaugurada en 1965. De 1970 a 1990 fue arquitecta municipal de Neubrandenburgo: el puesto más alto al que podía aspirar un arquitecto en la RDA, y que en aquel momento ninguna mujer ocupaba en la República Federal. Fue una de las arquitectas más influyentes de la RDA y publicó una autobiografía en 2004.',
      it: 'Grund studiò architettura alla Kunsthochschule Berlin-Weißensee dal 1952 al 1957, con docenti fra cui Selman Selmanagić, formatosi al Bauhaus. Lavorò due anni nello studio di Hermann Henselmann e brevemente con Ernst May ad Amburgo nel 1959, per rientrare lo stesso anno nella Repubblica Democratica Tedesca per convinzione politica. In quell\'anno, a ventisei anni, vinse il concorso per la Haus der Kultur und Bildung di Neubrandenburg, inaugurata nel 1965. Dal 1970 al 1990 fu architetta comunale di Neubrandenburg: la posizione più alta cui un architetto potesse aspirare nella RDT, e che all\'epoca nessuna donna ricopriva nella Germania federale. Fu una delle architette più influenti della RDT e pubblicò un\'autobiografia nel 2004.',
    },
    awards: ['Schinkel Medal (1976)', 'Architecture Prize of the German Democratic Republic (1977)', 'Schinkel Medal (1981)'],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q48203522', title: 'Iris Grund (Q48203522)', license: null },
      { kind: 'wikipedia', url: 'https://de.wikipedia.org/wiki/Iris_Grund', title: 'Iris Grund', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'louisa-hutton',
    wikidataId: 'Q4955176',
    name: 'Louisa Hutton',
    alternativeNames: ['Sauerbruch Hutton'],
    gender: 'woman',
    born: 1957,
    died: null,
    floruit: { start: 1999, end: 2023, override: false },
    movements: [{ id: 'sustainable-architecture', primary: true }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'civic',
    signatureMaterial: 'steel-and-glass',
    portrait: {
      en: 'Hutton was born in Norwich in 1957, the youngest of four children of an arable farmer. She read architecture at the University of Bristol until 1980 and at the Architectural Association in London until 1985, where she later taught, and worked with Alison and Peter Smithson from 1984 to 1988. In 1989 she founded Sauerbruch Hutton in London with Matthias Sauerbruch; winning the competition for the GSW headquarters took the office to Berlin in 1992. The practice — she leads it with Sauerbruch and Juan Lucas Young — is known for treating colour as a building material and for a sustained argument that low-energy buildings need not look ascetic. She held visiting professorships at Virginia and at the Harvard Graduate School of Design, and is a Royal Academician.',
      es: 'Hutton nació en Norwich en 1957, la menor de cuatro hermanos e hija de un agricultor de cereal. Estudió arquitectura en la Universidad de Bristol hasta 1980 y en la Architectural Association de Londres hasta 1985, donde luego enseñó, y trabajó con Alison y Peter Smithson entre 1984 y 1988. En 1989 fundó Sauerbruch Hutton en Londres con Matthias Sauerbruch; ganar el concurso de la sede de la GSW llevó el estudio a Berlín en 1992. El despacho —que dirige junto a Sauerbruch y Juan Lucas Young— es conocido por tratar el color como material de construcción y por sostener con insistencia que un edificio de bajo consumo no tiene por qué parecer asceta. Fue profesora invitada en Virginia y en la Harvard Graduate School of Design, y es Royal Academician.',
      it: 'Hutton nacque a Norwich nel 1957, ultima di quattro figli di un cerealicoltore. Studiò architettura all\'Università di Bristol fino al 1980 e all\'Architectural Association di Londra fino al 1985, dove poi insegnò, e lavorò con Alison e Peter Smithson dal 1984 al 1988. Nel 1989 fondò Sauerbruch Hutton a Londra con Matthias Sauerbruch; la vittoria del concorso per la sede della GSW portò lo studio a Berlino nel 1992. Lo studio — che guida insieme a Sauerbruch e Juan Lucas Young — è noto per trattare il colore come materiale da costruzione e per sostenere con costanza che un edificio a basso consumo non debba apparire ascetico. È stata professoressa ospite in Virginia e alla Harvard Graduate School of Design, ed è Royal Academician.',
    },
    awards: ['Officer of the Order of the British Empire', 'Royal Academician, Royal Academy of Arts', 'Honorary Fellow of the American Institute of Architects', 'Honorary Fellow of the Royal Institute of the Architects of Ireland (2019)'],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q4955176', title: 'Louisa Hutton (Q4955176)', license: null },
      { kind: 'wikipedia', url: 'https://de.wikipedia.org/wiki/Louisa_Hutton', title: 'Louisa Hutton', license: 'CC BY-SA 4.0' },
      { kind: 'institution', url: 'https://www.sauerbruchhutton.de/de/project/uba', title: 'Sauerbruch Hutton — Umweltbundesamt, Dessau (project data)', license: null },
    ],
  },
  {
    // Added in the fix round for the Altes Museum (13th building): d. 1841,
    // long out of copyright, no FoP question, and lifts the slice's tight
    // 1800-1945 era bucket from 3 to 4 per contract v2 §2.
    id: 'karl-friedrich-schinkel',
    wikidataId: 'Q151759',
    name: 'Karl Friedrich Schinkel',
    alternativeNames: ['K. F. Schinkel'],
    gender: 'man',
    born: 1781,
    died: 1841,
    floruit: { start: 1816, end: 1840, override: false },
    movements: [{ id: 'neoclassicism', primary: true }, { id: 'gothic-revival', primary: false }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'cultural',
    signatureMaterial: 'stone',
    portrait: {
      en: 'Schinkel trained under Friedrich Gilly in Berlin from 1798 and began his career as a painter and stage designer, touring Italy in 1803–1805 before Prussia\'s defeat by Napoleon left little architectural work to be had. Appointed to the Prussian Building Commission in 1810 through Wilhelm von Humboldt\'s mediation, he became Geheimer Oberbaurat in 1815 and rose in 1830 to head the state\'s entire building administration, reaching the rank of Oberlandesbaudirektor in 1838. His practice ran two vocabularies at once: a Greek Doric and Ionic neoclassicism for the Neue Wache and the Altes Museum, and an English-influenced Gothic brick manner for the Friedrichswerder Church and the Bauakademie. He also designed stage sets, furniture and medals, and shaped Prussian public building for a generation of successors. He died in Berlin in 1841 after a stroke.',
      es: 'Schinkel se formó con Friedrich Gilly en Berlín desde 1798 y comenzó su carrera como pintor y escenógrafo, viajando por Italia entre 1803 y 1805 antes de que la derrota prusiana ante Napoleón dejara poco trabajo de arquitectura disponible. Incorporado a la Comisión de Obras prusiana en 1810 por mediación de Wilhelm von Humboldt, llegó a Geheimer Oberbaurat en 1815 y en 1830 asumió la dirección de toda la administración estatal de obras, alcanzando en 1838 el rango de Oberlandesbaudirektor. Su obra manejó a la vez dos lenguajes: un neoclasicismo dórico y jónico griego para la Neue Wache y el Altes Museum, y una manera gótica de ladrillo de inspiración inglesa para la Friedrichswerdersche Kirche y la Bauakademie. Diseñó también escenografías, mobiliario y medallas, y marcó la construcción pública prusiana para toda una generación de sucesores. Murió en Berlín en 1841 tras sufrir un ictus.',
      it: 'Schinkel si formò con Friedrich Gilly a Berlino dal 1798 e cominciò la carriera come pittore e scenografo, viaggiando in Italia fra il 1803 e il 1805 prima che la sconfitta prussiana contro Napoleone lasciasse pochissimo lavoro architettonico disponibile. Entrato nella Commissione edilizia prussiana nel 1810 per mediazione di Wilhelm von Humboldt, divenne Geheimer Oberbaurat nel 1815 e nel 1830 assunse la direzione dell\'intera amministrazione edilizia statale, raggiungendo nel 1838 il grado di Oberlandesbaudirektor. La sua opera tenne insieme due linguaggi: un neoclassicismo dorico e ionico di ispirazione greca per la Neue Wache e l\'Altes Museum, e una maniera gotica in laterizio di ispirazione inglese per la Friedrichswerdersche Kirche e la Bauakademie. Disegnò anche scenografie, mobili e medaglie, e orientò l\'edilizia pubblica prussiana per un\'intera generazione di successori. Morì a Berlino nel 1841 in seguito a un ictus.',
    },
    awards: ['Member of the Prussian Academy of Arts (1811)', 'Geheimer Oberbaudirektor, head of the Prussian Oberbaudeputation (from 1830)', 'Oberlandesbaudirektor — chief royal architect of Prussia (1838)'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q151759', title: 'Karl Friedrich Schinkel (Q151759)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Karl_Friedrich_Schinkel', title: 'Karl Friedrich Schinkel', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://de.wikipedia.org/wiki/Karl_Friedrich_Schinkel', title: 'Karl Friedrich Schinkel', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    // Added in the fix round: Wikidata P84 on the Munich Olympic Stadium
    // (Q131610) credits Frei Otto, Behnisch & Partner, and Carlo Weber as
    // architects — not Behnisch alone. Otto is defined here as a coArchitects
    // entry on olympiastadion-muenchen; confirmed absent from the rest of the
    // 18-slice pool (grep for frei-otto returns nothing elsewhere), and his
    // practice base (Berlin, then Stuttgart) sits squarely in this slice.
    id: 'frei-otto',
    wikidataId: 'Q64412',
    name: 'Frei Otto',
    alternativeNames: ['Frei Paul Otto'],
    gender: 'man',
    born: 1925,
    died: 2015,
    floruit: { start: 1955, end: 2000, override: false },
    movements: [{ id: 'high-tech', primary: true }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'civic',
    signatureMaterial: 'mixed',
    portrait: {
      en: 'Otto trained as an architect in Berlin, was drafted as a Luftwaffe pilot and spent 1945 to 1947 as a prisoner of war near Chartres, where a shortage of materials pushed him toward the tent structures he built for fellow prisoners — the accidental origin of a lifelong subject. He opened his own Berlin practice in 1952 and completed a doctorate on tensioned structures in 1954, the same year he began finding form for cable nets and membranes through soap-film and hanging-chain models rather than calculation alone. He founded the Institute for Lightweight Structures at Stuttgart in 1964. His West German pavilion for Expo 67 in Montreal, with Rolf Gutbrod, led directly to the Munich Olympic roof; the Multihalle at Mannheim followed in 1975. He died in Leonberg in March 2015, a day before the Pritzker jury announced his prize.',
      es: 'Otto se formó como arquitecto en Berlín, fue reclutado como piloto de la Luftwaffe y pasó de 1945 a 1947 como prisionero de guerra cerca de Chartres, donde la escasez de materiales lo empujó hacia las estructuras de tienda que construyó para sus compañeros de cautiverio: origen accidental de un tema que lo ocupó toda la vida. Abrió despacho propio en Berlín en 1952 y completó en 1954 un doctorado sobre estructuras traccionadas, buscando la forma de redes y membranas con películas de jabón y modelos de cadena, más que por cálculo. Fundó el Instituto de Estructuras Ligeras de Stuttgart en 1964. Su pabellón de Alemania Occidental en la Expo 67 de Montreal, con Rolf Gutbrod, llevó a la cubierta olímpica de Múnich; le siguió la Multihalle de Mannheim en 1975. Murió en Leonberg en marzo de 2015, un día antes de que el jurado del Pritzker anunciara su premio.',
      it: 'Otto si formò come architetto a Berlino, fu arruolato come pilota della Luftwaffe e trascorse dal 1945 al 1947 come prigioniero di guerra vicino a Chartres, dove la scarsità di materiali lo spinse verso le strutture a tenda costruite per i compagni di prigionia: origine casuale di un tema che lo avrebbe occupato per tutta la vita. Aprì studio proprio a Berlino nel 1952 e completò nel 1954 un dottorato sulle strutture tese, cercando la forma di reti e membrane con pellicole di sapone e modelli a catenaria, più che per calcolo. Fondò l\'Istituto per le strutture leggere di Stoccarda nel 1964. Il suo padiglione della Germania Ovest all\'Expo 67 di Montreal, con Rolf Gutbrod, portò alla copertura olimpica di Monaco; seguì la Multihalle di Mannheim nel 1975. Morì a Leonberg nel marzo 2015, un giorno prima che la giuria del Pritzker annunciasse il suo premio.',
    },
    awards: ['RIBA Royal Gold Medal (2005)', 'Pritzker Architecture Prize (2015, posthumous)'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q64412', title: 'Frei Otto (Q64412)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Frei_Otto', title: 'Frei Otto', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    // Added in the fix round alongside frei-otto: the same Wikidata P84 credit
    // on the Munich Olympic Stadium names Carlo Weber as a third architect.
    id: 'carlo-weber',
    wikidataId: 'Q121251',
    name: 'Carlo Weber',
    alternativeNames: ['Karlheinz Weber'],
    gender: 'man',
    born: 1934,
    died: 2014,
    floruit: { start: 1966, end: 2013, override: false },
    movements: [{ id: 'high-tech', primary: true }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'cultural',
    signatureMaterial: 'mixed',
    portrait: {
      en: 'Born Karlheinz Weber in Saarbrücken in 1934, he studied architecture at the Technical University of Stuttgart from 1954, breaking off for a DAAD scholarship at the École des Beaux-Arts in Paris in 1959–60. From 1957 he worked alongside Günter Behnisch and Bruno Lambart, and became a partner at Behnisch & Partner in 1966. It was Weber who, with Frei Otto and Heinz Isler, built the Munich Olympic Stadium competition model from wooden rods and a lady\'s stocking after a colleague proposed draping one canopy over the whole site — the sketch that became the tent roof. He left the partnership in 1979 and ran his own Stuttgart and Munich office with Fritz Auer from 1980 until his death, building the Recklinghausen Festival House and Theater Hof, and taught at Stuttgart and Dresden. He died in Stuttgart in May 2014.',
      es: 'Nacido Karlheinz Weber en Saarbrücken en 1934, estudió arquitectura en la Universidad Técnica de Stuttgart desde 1954, con una interrupción gracias a una beca del DAAD en la École des Beaux-Arts de París en 1959-60. Desde 1957 trabajó junto a Günter Behnisch y Bruno Lambart, y en 1966 fue socio de Behnisch & Partner. Fue Weber quien, con Frei Otto y Heinz Isler, construyó la maqueta de concurso del Estadio Olímpico de Múnich con varillas de madera y una media de señora, tras proponer un colega tender un solo toldo sobre todo el recinto: el boceto que dio la cubierta de lona. Dejó la sociedad en 1979 y dirigió su propio despacho en Stuttgart y Múnich con Fritz Auer desde 1980 hasta su muerte, construyendo la Casa de Festivales de Recklinghausen y el Teatro de Hof, y enseñó en Stuttgart y Dresde. Murió en Stuttgart en mayo de 2014.',
      it: 'Nato Karlheinz Weber a Saarbrücken nel 1934, studiò architettura all\'Università Tecnica di Stoccarda dal 1954, con un\'interruzione per una borsa DAAD all\'École des Beaux-Arts di Parigi nel 1959-60. Dal 1957 lavorò accanto a Günter Behnisch e Bruno Lambart, e nel 1966 divenne socio di Behnisch & Partner. Fu Weber a costruire, con Frei Otto e Heinz Isler, il modello di concorso dello Stadio Olimpico di Monaco con bacchette di legno e una calza da donna, dopo che un collega propose di stendere un unico velario su tutta l\'area: lo schizzo da cui nacque la copertura a tenda. Lasciò la società nel 1979 e diresse un proprio studio a Stoccarda e Monaco con Fritz Auer dal 1980 fino alla morte, costruendo la Casa dei Festival di Recklinghausen e il Teatro di Hof, e insegnò a Stoccarda e Dresda. Morì a Stoccarda nel maggio 2014.',
    },
    awards: ['Auguste Perret Prize (1981)', 'UIA Architecture Prize (1981)', 'German Architecture Prize (2001)'],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q121251', title: 'Carlo Weber (Q121251)', license: null },
      { kind: 'wikipedia', url: 'https://de.wikipedia.org/wiki/Carlo_Weber_(Architekt)', title: 'Carlo Weber (Architekt)', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    // Added in the fix round: Wikidata P84 on the Karlskirche (Q408847) lists
    // both Johann Bernhard Fischer von Erlach and his son Joseph Emanuel, who
    // completed the church after his father's 1723 death — the dossier itself
    // already narrates this. Defined as a coArchitects entry on
    // karlskirche-vienna.
    id: 'joseph-emanuel-fischer-von-erlach',
    wikidataId: 'Q84588',
    name: 'Joseph Emanuel Fischer von Erlach',
    alternativeNames: ['Fischer von Erlach der Jüngere'],
    gender: 'man',
    born: 1693,
    died: 1742,
    floruit: { start: 1723, end: 1742, override: false },
    movements: [{ id: 'baroque', primary: true }, { id: 'neoclassicism', primary: false }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'sacral',
    signatureMaterial: 'stone',
    portrait: {
      en: 'Baptised in Vienna in September 1693, the second son of Johann Bernhard Fischer von Erlach, Joseph Emanuel trained in his father\'s workshop, drafting projects and helping finish his father\'s engraved survey of world architecture. When the elder Fischer died in 1723 with the Karlskirche barely begun above its foundations, Joseph Emanuel took over the site and carried it to completion in 1737, along with several other paternal commissions left unfinished. He became imperial court architect in 1722 and first court architect in 1725, and was raised to Freiherr in 1735, largely for his engineering work rather than his buildings. Where his father built for tectonic effect, Joseph Emanuel favoured flatter, more rational facades, seen at the Hofburg\'s Winter Riding School, the Court Library and the Michaelertrakt. He died in Vienna in June 1742.',
      es: 'Bautizado en Viena en septiembre de 1693, segundo hijo de Johann Bernhard Fischer von Erlach, Joseph Emanuel se formó en el taller de su padre, redactando proyectos y ayudando a terminar su tratado grabado sobre la arquitectura universal. Cuando su padre murió en 1723 con la Karlskirche apenas levantada sobre sus cimientos, Joseph Emanuel se hizo cargo de la obra y la llevó a término en 1737, junto con otros encargos paternos inacabados. Fue nombrado arquitecto de la corte imperial en 1722 y primer arquitecto de la corte en 1725, y en 1735 fue elevado a Freiherr, sobre todo por sus méritos como ingeniero más que como constructor. Donde su padre buscaba el efecto tectónico, Joseph Emanuel prefirió fachadas más planas y racionales, visibles en la Escuela de Equitación Española de la Hofburg, la Biblioteca de la Corte y el Michaelertrakt. Murió en Viena en junio de 1742.',
      it: 'Battezzato a Vienna nel settembre 1693, secondo figlio di Johann Bernhard Fischer von Erlach, Joseph Emanuel si formò nella bottega paterna, redigendo progetti e aiutando a completare il trattato inciso del padre sull\'architettura universale. Quando il padre morì nel 1723 con la Karlskirche appena impostata sulle fondamenta, Joseph Emanuel prese in mano il cantiere e lo portò a termine nel 1737, insieme ad altri incarichi paterni rimasti incompiuti. Divenne architetto di corte imperiale nel 1722 e primo architetto di corte nel 1725, e nel 1735 fu elevato a Freiherr, soprattutto per i suoi meriti di ingegnere più che di costruttore. Dove il padre cercava l\'effetto tettonico, Joseph Emanuel preferì facciate più piatte e razionali, visibili nella Scuola di Equitazione Spagnola della Hofburg, nella Biblioteca di Corte e nel Michaelertrakt. Morì a Vienna nel giugno 1742.',
    },
    awards: ['Freiherr (1735)', 'Imperial court architect (from 1722)', 'First court architect (from 1725)'],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q84588', title: 'Joseph Emanuel Fischer von Erlach (Q84588)', license: null },
      { kind: 'wikipedia', url: 'https://de.wikipedia.org/wiki/Joseph_Emanuel_Fischer_von_Erlach', title: 'Joseph Emanuel Fischer von Erlach', license: 'CC BY-SA 4.0' },
    ],
  },
];
