import type { Architect } from '@/types/architect';

// Wave 5 curator agent (United Kingdom, Ireland): real, sourced Architect entries for this slice.
//
// `workRegions` and `workCentroid` are intentionally left empty/zeroed: the
// curation script (src/scripts/buildCuratedPool.ts) derives both from each
// architect's buildings and overwrites whatever is typed here.
//
// Several of the practices below are genuine partnerships, recorded per
// Ruling 25 (progress.md): `architectId` on the building carries the
// conventional/canonical credit and `coArchitects` carries the rest, so the
// joint authorship is a schema fact rather than only prose. Alison Smithson
// (building architectId) with Peter Smithson (coArchitects) — a genuinely
// symmetric partnership per Wikidata P84 order and the firm's own "Alison
// and Peter Smithson" convention. Eldred Evans (architectId) with David
// Shalev (coArchitects) — the firm's own name, "Evans & Shalev", already
// orders them this way. Jan Kaplický (architectId) with Amanda Levete
// (coArchitects) on Selfridges Birmingham — Kaplický is listed first in
// both the Wikipedia infobox and body text, the conventional credit for
// that building; Levete is owned and fully defined by the `europe` slice
// (MAAT Lisbon) and is referenced here by id only, not redefined. Yvonne
// Farrell (architectId) with Shelley McNamara (coArchitects) on the Loreto
// Community School — both women, so no Ruling 25 concern; order follows
// the practice's own conventional citation order ("Farrell and McNamara").
//
// A Task 9 re-review fix pass added Zaha Hadid, owned by this slice per
// wave5-contract-v2.md §3, on the strength of her individual P84 credit on
// the London Aquatics Centre (Q308874) — the candidate the prior fix round's
// search missed.
export const EUROPE_BRITISH_ARCHITECTS: Architect[] = [
  {
    id: 'christopher-wren',
    wikidataId: 'Q170373',
    name: 'Christopher Wren',
    alternativeNames: ['Sir Christopher Wren'],
    gender: 'man',
    born: 1632,
    died: 1723,
    floruit: { start: 1665, end: 1711, override: false },
    movements: 'unaffiliated',
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'sacral',
    signatureMaterial: 'stone',
    portrait: {
      en: "Christopher Wren came to architecture from astronomy. A Savilian Professor at Oxford and a founder of the Royal Society, he was past thirty before he designed a building, and it was the Great Fire of 1666 that handed him a city to rebuild. As Surveyor of the King's Works he carried St Paul's Cathedral and some fifty City parish churches at once, running a drawing office whose assistants included Nicholas Hawksmoor. His method was empirical rather than doctrinaire: he read Italian and French classicism through the long, transept-heavy plan of the English medieval cathedral, and he solved problems by geometry. The triple dome of St Paul's is the clearest case — a hidden brick cone carries the stone lantern that neither visible shell could bear. He built in Portland stone, kept his steeples slender and endlessly varied, and gave London a skyline that held for three centuries.",
      es: "Christopher Wren llegó a la arquitectura desde la astronomía. Catedrático saviliano en Oxford y fundador de la Royal Society, había pasado de los treinta cuando proyectó su primer edificio, y fue el Gran Incendio de 1666 el que le entregó una ciudad que reconstruir. Como Surveyor of the King's Works llevó a la vez la catedral de San Pablo y medio centenar de iglesias de la City, al frente de un estudio donde trabajó Nicholas Hawksmoor. Su método fue empírico antes que doctrinal: leyó el clasicismo italiano y francés a través de la planta medieval inglesa y resolvió los problemas por geometría. La cúpula triple de San Pablo es el caso más claro: un cono de ladrillo oculto sostiene la linterna de piedra que ninguna de las dos cáscaras visibles podría soportar. Construyó en piedra de Portland y dio a Londres un perfil que duró tres siglos.",
      it: "Christopher Wren arrivò all'architettura dall'astronomia. Professore saviliano a Oxford e fondatore della Royal Society, aveva superato i trent'anni quando progettò il primo edificio, e fu il Grande Incendio del 1666 a consegnargli una città da ricostruire. Come Surveyor of the King's Works portò avanti insieme la cattedrale di San Paolo e una cinquantina di chiese parrocchiali della City, dirigendo uno studio in cui lavorò Nicholas Hawksmoor. Il suo metodo fu empirico più che dottrinario: lesse il classicismo italiano e francese attraverso l'impianto lungo e fortemente transettato della cattedrale medievale inglese, e risolse i problemi con la geometria. La cupola tripla di San Paolo è il caso più limpido: un cono di mattoni nascosto regge la lanterna di pietra che nessuno dei due gusci visibili potrebbe sostenere. Costruì in pietra di Portland e diede a Londra un profilo durato tre secoli.",
    },
    awards: ['Knight Bachelor (1673)'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q170373', title: 'Christopher Wren (Q170373)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Christopher_Wren', title: 'Christopher Wren', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'james-gandon',
    wikidataId: 'Q964382',
    name: 'James Gandon',
    alternativeNames: ['James Gandon RHA'],
    gender: 'man',
    born: 1742,
    died: 1823,
    floruit: { start: 1781, end: 1808, override: false },
    movements: 'unaffiliated',
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'civic',
    signatureMaterial: 'stone',
    portrait: {
      en: "James Gandon was a Londoner who made Dublin. Trained in William Chambers's office and formed by the sober Roman neoclassicism of his generation, he was invited to Ireland in 1781 by John Beresford, the first revenue commissioner, who wanted a new Custom House downriver of the old city. Friends advised against it; Gandon went, and stayed for the rest of his life. Over three decades he gave Georgian Dublin its civic set pieces — the Custom House, the Four Courts, the King's Inns, and the east portico added to the Parliament House on College Green. Each is a long, low composition in ashlar, organised around a dome or a columned centrepiece and calculated to be read at distance across water or open ground. He worked with Irish masons and carvers, above all the sculptor Edward Smyth, whose riverine keystone heads are now inseparable from Gandon's façades.",
      es: "James Gandon era londinense, pero hizo Dublín. Formado en el estudio de William Chambers y educado en el neoclasicismo romano y sobrio de su generación, fue llamado a Irlanda en 1781 por John Beresford, primer comisario de aduanas, que quería una nueva Custom House río abajo de la ciudad vieja. Sus amigos le desaconsejaron el viaje; Gandon fue y ya no se marchó. En tres décadas dio al Dublín georgiano sus grandes piezas civiles: la Custom House, los Four Courts, los King's Inns y el pórtico oriental añadido al Parlamento de College Green. Todas son composiciones largas y bajas de sillería, ordenadas en torno a una cúpula o a un cuerpo de columnas y calculadas para leerse de lejos, cruzando el agua. Trabajó con canteros y talladores irlandeses, sobre todo con el escultor Edward Smyth, cuyas claves con cabezas fluviales son ya inseparables de sus fachadas.",
      it: "James Gandon era londinese, ma fu lui a fare Dublino. Formatosi nello studio di William Chambers e cresciuto nel neoclassicismo romano e severo della sua generazione, fu chiamato in Irlanda nel 1781 da John Beresford, primo commissario delle dogane, che voleva una nuova Custom House a valle della città vecchia. Gli amici lo sconsigliarono; Gandon partì e non tornò più. In tre decenni diede alla Dublino georgiana i suoi episodi civili maggiori: la Custom House, i Four Courts, i King's Inns e il portico orientale aggiunto al Parlamento di College Green. Sono tutte composizioni lunghe e basse in pietra squadrata, ordinate attorno a una cupola o a un corpo di colonne e calcolate per essere lette da lontano, oltre l'acqua. Lavorò con scalpellini e intagliatori irlandesi, soprattutto con lo scultore Edward Smyth, le cui chiavi di volta con teste fluviali sono ormai inseparabili dalle sue facciate.",
    },
    awards: [],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q964382', title: 'James Gandon (Q964382)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/James_Gandon', title: 'James Gandon', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'william-burges',
    wikidataId: 'Q186265',
    name: 'William Burges',
    alternativeNames: ['William Burges ARA'],
    gender: 'man',
    born: 1827,
    died: 1881,
    floruit: { start: 1865, end: 1881, override: false },
    movements: [{ id: 'gothic-revival', primary: true }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'sacral',
    signatureMaterial: 'stone',
    portrait: {
      en: "William Burges was the most single-minded of the High Victorian Goths. Where his contemporaries argued about which century to revive, Burges settled on thirteenth-century France and never moved, treating early French Gothic as a complete system of building, sculpture, metalwork, glass and furniture that an architect should control down to the last hinge. The son of a wealthy marine engineer, he had money enough to work slowly and refuse what bored him. Winning the competition for Saint Fin Barre's Cathedral in Cork in 1863 gave him, at thirty-five, his first large commission and the only one he saw completed to his own designs throughout. For the Marquess of Bute he then remade Cardiff Castle and Castell Coch as saturated medieval fantasies. He died at fifty-three, leaving a small body of work of exceptional density.",
      es: "William Burges fue el más obstinado de los goticistas victorianos. Mientras sus contemporáneos discutían qué siglo convenía resucitar, él eligió la Francia del XIII y no se movió de ahí: entendió el gótico francés temprano como un sistema completo de construcción, escultura, orfebrería, vidriera y mobiliario que el arquitecto debía controlar hasta la última bisagra. Hijo de un próspero ingeniero naval, tuvo dinero suficiente para trabajar despacio y rechazar lo que le aburría. Ganar en 1863 el concurso de la catedral de San Finbar en Cork le dio, a los treinta y cinco años, su primer gran encargo y el único que vio terminado íntegramente según sus propios diseños. Después rehízo para el marqués de Bute el castillo de Cardiff y Castell Coch como fantasías medievales saturadas de color. Murió a los cincuenta y tres, dejando una obra breve y densísima.",
      it: "William Burges fu il più ostinato dei gotici vittoriani. Mentre i contemporanei discutevano su quale secolo far rivivere, lui scelse la Francia del Duecento e non si spostò più: intese il gotico francese delle origini come un sistema completo di costruzione, scultura, oreficeria, vetrata e arredo, che l'architetto doveva controllare fino all'ultimo cardine. Figlio di un facoltoso ingegnere navale, ebbe denaro sufficiente per lavorare lentamente e rifiutare ciò che lo annoiava. Vincere nel 1863 il concorso per la cattedrale di San Finbar a Cork gli diede, a trentacinque anni, la prima grande commessa e l'unica che vide compiuta interamente su suo disegno. Per il marchese di Bute rifece poi il castello di Cardiff e Castell Coch come fantasie medievali sature di colore. Morì a cinquantatré anni, lasciando un'opera breve e densissima.",
    },
    awards: [],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q186265', title: 'William Burges (Q186265)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/William_Burges', title: 'William Burges', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'charles-rennie-mackintosh',
    wikidataId: 'Q220703',
    name: 'Charles Rennie Mackintosh',
    alternativeNames: ['Charles Mackintosh', 'C. R. Mackintosh'],
    gender: 'man',
    born: 1868,
    died: 1928,
    floruit: { start: 1896, end: 1917, override: false },
    movements: [{ id: 'art-nouveau', primary: true }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'educational',
    signatureMaterial: 'stone',
    portrait: {
      en: "Charles Rennie Mackintosh trained as an apprentice in Glasgow and rose inside the office of Honeyman & Keppie, where he was still a salaried assistant when the practice won the competition for the Glasgow School of Art in 1896. Everything he is remembered for was built in roughly twenty years and almost all of it within a few miles of the Clyde: the School of Art, Scotland Street School, Queen's Cross Church, the Willow Tea Rooms, and the Hill House at Helensburgh. He worked with his wife Margaret Macdonald, whose gesso panels and decorative schemes belong to the same invention as the buildings. The combination is unusual — hard, almost bleak Scottish baronial masonry outside, and inside a lyrical interior of white paint, attenuated verticals and stylised rose motifs. Commissions dried up after 1913; he spent his last years painting watercolours in France.",
      es: "Charles Rennie Mackintosh se formó como aprendiz en Glasgow y ascendió dentro del estudio Honeyman & Keppie, donde todavía era un ayudante a sueldo cuando la casa ganó en 1896 el concurso de la Escuela de Arte de Glasgow. Todo aquello por lo que se le recuerda se construyó en unos veinte años y casi siempre a pocas millas del Clyde: la Escuela de Arte, Scotland Street, Queen's Cross, los salones de té Willow y la Hill House de Helensburgh. Trabajó junto a su mujer, Margaret Macdonald, cuyos paneles de estuco y esquemas decorativos pertenecen a la misma invención que los edificios. La combinación es insólita: fuera, una fábrica de piedra dura, casi adusta, de raíz baronial escocesa; dentro, un interior lírico de pintura blanca, verticales afiladas y rosas estilizadas. Tras 1913 los encargos se agotaron y acabó pintando acuarelas en Francia.",
      it: "Charles Rennie Mackintosh si formò come apprendista a Glasgow e crebbe all'interno dello studio Honeyman & Keppie, dove era ancora un assistente stipendiato quando la casa vinse nel 1896 il concorso per la Glasgow School of Art. Tutto ciò per cui è ricordato fu costruito in una ventina d'anni e quasi sempre a poche miglia dal Clyde: la School of Art, la scuola di Scotland Street, la chiesa di Queen's Cross, le sale da tè Willow e la Hill House di Helensburgh. Lavorò con la moglie Margaret Macdonald, i cui pannelli in gesso e apparati decorativi appartengono alla stessa invenzione degli edifici. La combinazione è insolita: fuori una muratura dura, quasi spoglia, di ascendenza baronale scozzese; dentro un interno lirico fatto di bianco, di verticali assottigliate e di rose stilizzate. Dopo il 1913 le commesse si esaurirono e passò gli ultimi anni dipingendo acquerelli in Francia.",
    },
    awards: [],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q220703', title: 'Charles Rennie Mackintosh (Q220703)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Charles_Rennie_Mackintosh', title: 'Charles Rennie Mackintosh', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'elisabeth-scott',
    wikidataId: 'Q5361548',
    name: 'Elisabeth Scott',
    alternativeNames: ['Elisabeth Whitworth Scott', 'Elizabeth Scott'],
    gender: 'woman',
    born: 1898,
    died: 1972,
    floruit: { start: 1932, end: 1938, override: false },
    movements: [{ id: 'art-deco', primary: true }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'cultural',
    signatureMaterial: 'brick',
    portrait: {
      en: "Elisabeth Whitworth Scott belonged to a dynasty of English architects — George Gilbert Scott was her great-great-uncle — but she entered the profession through the Architectural Association in the first years it admitted women, and she won her one great commission anonymously. In 1928, aged twenty-nine and barely three years qualified, she took first place in the open international competition to replace the burnt Shakespeare Memorial Theatre at Stratford-upon-Avon, beating seventy-one other entries. It made her the first woman to win a major British public building competition, and the press treated it as a scandal as much as an achievement. She was then working in Maurice Chesterton's Hampstead office, and built the theatre with two fellow Architectural Association students, Alison Sleigh and John Chiene Shepherd; the practice later became Scott, Shepherd and Breakwell. No comparable public commission ever followed.",
      es: "Elisabeth Whitworth Scott pertenecía a una dinastía de arquitectos ingleses —George Gilbert Scott era su tío bisabuelo—, pero entró en la profesión por la Architectural Association, en los primeros años en que admitió mujeres, y ganó su gran encargo de forma anónima. En 1928, con veintinueve años y apenas tres de título, obtuvo el primer premio del concurso internacional abierto para sustituir el quemado Shakespeare Memorial Theatre de Stratford-upon-Avon, por delante de otras setenta y una propuestas. Fue la primera mujer que ganó un concurso público importante en Gran Bretaña, y la prensa lo trató tanto de escándalo como de mérito. Trabajaba entonces en el estudio de Maurice Chesterton en Hampstead, y construyó el teatro con dos compañeros de la Architectural Association, Alison Sleigh y John Chiene Shepherd; la firma pasaría luego a llamarse Scott, Shepherd and Breakwell. Nunca llegó otro encargo público de esa escala.",
      it: "Elisabeth Whitworth Scott apparteneva a una dinastia di architetti inglesi — George Gilbert Scott era il suo prozio in seconda — ma entrò nella professione attraverso l'Architectural Association, nei primi anni in cui ammetteva donne, e vinse la sua grande commessa in forma anonima. Nel 1928, a ventinove anni e con appena tre anni di abilitazione, si aggiudicò il primo posto nel concorso internazionale aperto per sostituire il bruciato Shakespeare Memorial Theatre di Stratford-upon-Avon, davanti ad altre settantuno proposte. Fu la prima donna a vincere un grande concorso pubblico britannico, e la stampa lo trattò come uno scandalo oltre che come un merito. Lavorava allora nello studio di Maurice Chesterton a Hampstead, e costruì il teatro con due compagni dell'Architectural Association, Alison Sleigh e John Chiene Shepherd; la firma sarebbe poi diventata Scott, Shepherd and Breakwell. Nessun'altra commessa pubblica di quella portata la raggiunse mai.",
    },
    awards: [],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q5361548', title: 'Elisabeth Scott (Q5361548)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Elisabeth_Scott', title: 'Elisabeth Scott', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'basil-spence',
    wikidataId: 'Q1172126',
    name: 'Basil Spence',
    alternativeNames: ['Sir Basil Spence', 'Basil Urwin Spence'],
    gender: 'man',
    born: 1907,
    died: 1976,
    floruit: { start: 1938, end: 1976, override: false },
    movements: 'unaffiliated',
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'sacral',
    signatureMaterial: 'stone',
    portrait: {
      en: "Basil Spence was born in Bombay to Scottish parents, trained in Edinburgh, and worked for a year in Edwin Lutyens's London office on the New Delhi drawings before setting up on his own. He made his early name on exhibition pavilions and country houses, spent the war in army camouflage and landed in Normandy in 1944, and then took the competition launched in 1950 for a new cathedral at Coventry against more than two hundred entries. His insistence that the bombed shell of the old St Michael's be kept as a ruin, with the new church alongside it, is the decision the whole design rests on. Spence was no doctrinaire modernist: he treated a building as a setting for commissioned art, coordinating Sutherland, Piper, Epstein and Hutton at Coventry as deliberately as he detailed the stone. Later work at Sussex and Hyde Park Barracks divided opinion sharply.",
      es: "Basil Spence nació en Bombay, hijo de escoceses, se formó en Edimburgo y pasó un año en el estudio de Edwin Lutyens trabajando en los planos de Nueva Delhi antes de establecerse por su cuenta. Se dio a conocer con pabellones y casas de campo, pasó la guerra en la sección de camuflaje del ejército y desembarcó en Normandía en 1944, y después ganó, frente a más de doscientas propuestas, el concurso convocado en 1950 para la nueva catedral de Coventry. Su insistencia en conservar como ruina el casco bombardeado de la vieja St Michael's y levantar la iglesia nueva a su lado es la decisión sobre la que descansa todo el proyecto. Spence no era un modernista doctrinario: entendía el edificio como marco de un arte encargado y coordinó en Coventry a Sutherland, Piper, Epstein y Hutton con el cuidado con que detalló la piedra.",
      it: "Basil Spence nacque a Bombay da genitori scozzesi, si formò a Edimburgo e passò un anno nello studio londinese di Edwin Lutyens lavorando ai disegni di Nuova Delhi prima di mettersi in proprio. Si fece conoscere con padiglioni espositivi e case di campagna, passò la guerra nel camuffamento militare e sbarcò in Normandia nel 1944, e vinse poi, contro più di duecento proposte, il concorso bandito nel 1950 per la nuova cattedrale di Coventry. La sua insistenza nel conservare come rudere il guscio bombardato della vecchia St Michael's e costruire la chiesa nuova accanto è la decisione su cui poggia tutto il progetto. Spence non era un modernista dottrinario: intendeva l'edificio come cornice di un'arte commissionata e a Coventry coordinò Sutherland, Piper, Epstein e Hutton con la cura con cui dettagliò la pietra.",
    },
    awards: ['Order of Merit', 'Officer of the Order of the British Empire', 'Royal Designer for Industry', 'Knight Bachelor'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q1172126', title: 'Basil Spence (Q1172126)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Basil_Spence', title: 'Basil Spence', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'james-stirling',
    wikidataId: 'Q159619',
    name: 'James Stirling',
    alternativeNames: ['Sir James Stirling', 'James Frazer Stirling', 'Big Jim'],
    gender: 'man',
    born: 1926,
    died: 1992,
    floruit: { start: 1958, end: 1992, override: false },
    movements: [{ id: 'postmodern-classicism', primary: true }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'educational',
    signatureMaterial: 'brick',
    portrait: {
      en: "James Stirling was raised in Liverpool, studied there, and spent his career refusing to settle into a manner. His partnership with James Gowan produced the flats at Ham Common and then the Engineering Building at Leicester, the first of what critics later called the Red Trilogy — three university buildings in red brick and red tile, each assembled out of frankly industrial parts, each more wilful than the last. The sequence runs from the tail of Brutalism into something else entirely, and by the Neue Staatsgalerie in Stuttgart, opened in 1984, Stirling was quoting cornices and drums with a straight face, which made him the most argued-over architect of his generation. He won the Pritzker Prize in 1981 and the RIBA Royal Gold Medal in 1980; the British prize for architecture now carries his name.",
      es: "James Stirling se crió en Liverpool, estudió allí y pasó su carrera negándose a asentarse en una manera. Su asociación con James Gowan produjo los apartamentos de Ham Common y después el Edificio de Ingeniería de Leicester, primero de lo que la crítica llamaría la Trilogía Roja: tres edificios universitarios en ladrillo y plaqueta rojos, montados abiertamente con piezas de catálogo industrial y cada uno más caprichoso que el anterior. La serie va desde la cola del brutalismo hasta otra cosa por completo, y en la Neue Staatsgalerie de Stuttgart, inaugurada en 1984, Stirling citaba cornisas y tambores clásicos sin pestañear, lo que lo convirtió en el arquitecto más discutido de su generación. Ganó el Pritzker en 1981 y la Royal Gold Medal del RIBA en 1980; el premio británico de arquitectura lleva hoy su nombre.",
      it: "James Stirling crebbe a Liverpool, vi studiò e passò la carriera rifiutandosi di assestarsi in una maniera. Il sodalizio con James Gowan produsse gli appartamenti di Ham Common e poi l'Edificio di Ingegneria di Leicester, primo di quella che la critica avrebbe chiamato la Trilogia Rossa: tre edifici universitari in mattone e piastrella rossa, montati apertamente con pezzi di catalogo industriale e ciascuno più capriccioso del precedente. La serie va dalla coda del brutalismo a tutt'altro, e con la Neue Staatsgalerie di Stoccarda, aperta nel 1984, Stirling citava cornici e tamburi classici senza battere ciglio, diventando l'architetto più discusso della sua generazione. Vinse il Pritzker nel 1981 e la Royal Gold Medal del RIBA nel 1980; il premio britannico di architettura porta oggi il suo nome.",
    },
    awards: ['Pritzker Architecture Prize', 'RIBA Royal Gold Medal', 'Alvar Aalto Medal', 'Praemium Imperiale', 'Knight Bachelor'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q159619', title: 'James Stirling (Q159619)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/James_Stirling_(architect)', title: 'James Stirling (architect)', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'alison-smithson',
    wikidataId: 'Q2647238',
    name: 'Alison Smithson',
    alternativeNames: ['Alison Margaret Smithson', 'Alison Margaret Gill'],
    gender: 'woman',
    born: 1928,
    died: 1993,
    floruit: { start: 1954, end: 1993, override: false },
    movements: 'unaffiliated',
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'housing',
    signatureMaterial: 'brick',
    portrait: {
      en: "Alison Smithson met Peter Smithson at Durham and worked in partnership with him from 1950 until her death; everything either of them built was published under both names. Their competition win for Hunstanton school in 1949, finished in 1954 with its steel frame and services left frankly visible, gave critics the term New Brutalism. They built very little — an embassy, an office building, a school, a few houses, one large housing estate — and wrote a great deal, and their influence ran mostly through Team 10, through the idea of the street in the air, and through a stubborn insistence that architecture should be judged by how people actually occupy it. Alison was the sharper polemicist of the two: her book «AS in DS» and the Smithsons' Team 10 primers shaped a generation's vocabulary far more than their built work did.",
      es: "Alison Smithson conoció a Peter Smithson en Durham y trabajó en sociedad con él desde 1950 hasta su muerte; todo lo que cualquiera de los dos construyó se publicó bajo ambos nombres. La escuela de Hunstanton, ganada en concurso en 1949 y terminada en 1954 con la estructura de acero y las instalaciones a la vista, dio a la crítica el término nuevo brutalismo. Construyeron muy poco —una embajada, unas oficinas, una escuela, un conjunto de viviendas— y escribieron muchísimo, y su influencia circuló a través del Team 10, de la idea de la calle en el aire y de una insistencia terca en que la arquitectura debe juzgarse por el modo en que la gente la habita. Alison fue la polemista más afilada: su «AS in DS» y los manuales del Team 10 marcaron el vocabulario de una generación mucho más que su obra construida.",
      it: "Alison Smithson conobbe Peter Smithson a Durham e lavorò in società con lui dal 1950 fino alla morte; tutto ciò che l'uno o l'altra costruirono fu pubblicato a nome di entrambi. La vittoria nel concorso per la scuola di Hunstanton nel 1949, ultimata nel 1954 con la struttura d'acciaio e gli impianti lasciati francamente a vista, diede alla critica il termine New Brutalism. Costruirono pochissimo — un'ambasciata, un edificio per uffici, una scuola, qualche casa, un grande complesso residenziale — e scrissero moltissimo, e la loro influenza passò soprattutto attraverso il Team 10, l'idea della strada in aria e l'ostinata convinzione che l'architettura vada giudicata da come le persone la abitano davvero. Alison fu la polemista più tagliente dei due: il suo «AS in DS» e i manuali del Team 10 formarono il vocabolario di una generazione assai più delle opere costruite.",
    },
    awards: [],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q2647238', title: 'Alison Smithson (Q2647238)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Alison_and_Peter_Smithson', title: 'Alison and Peter Smithson', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'norman-foster',
    wikidataId: 'Q104898',
    name: 'Norman Foster',
    alternativeNames: ['Lord Foster of Thames Bank', 'Norman Robert Foster', 'Sir Norman Foster'],
    gender: 'man',
    born: 1935,
    died: null,
    floruit: { start: 1967, end: 2026, override: false },
    movements: [{ id: 'high-tech', primary: true }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'commercial',
    signatureMaterial: 'steel-and-glass',
    portrait: {
      en: "Norman Foster grew up in working-class Manchester, paid his own way through the Manchester School of Architecture, and won a fellowship to Yale, where he met Richard Rogers. The two returned to found Team 4 with Su Brumwell and Wendy Cheesman; when it dissolved, Foster and Cheesman continued as Foster Associates. The early work argued a single case with unusual clarity — that a building should be an engineered, serviced, light-weight enclosure that could be assembled fast and changed later — and the Willis Faber headquarters at Ipswich and the Sainsbury Centre at Norwich made that case decisively in the 1970s. The practice grew into one of the largest in the world, delivering the Hongkong and Shanghai Bank, the Reichstag dome, Stansted, and Hong Kong's airport. He received the Pritzker Prize in 1999.",
      es: "Norman Foster creció en un Manchester obrero, se costeó él mismo la Escuela de Arquitectura de la ciudad y obtuvo una beca para Yale, donde conoció a Richard Rogers. Ambos volvieron para fundar Team 4 junto a Su Brumwell y Wendy Cheesman; al disolverse el grupo, Foster y Cheesman continuaron como Foster Associates. La obra temprana defiende una sola tesis con claridad poco común: que un edificio debe ser un cerramiento ligero, calculado y servido, montable deprisa y modificable después. La sede de Willis Faber en Ipswich y el Sainsbury Centre de Norwich lo demostraron de forma concluyente en los años setenta. El estudio se convirtió en uno de los mayores del mundo y firmó el banco de Hong Kong y Shanghái, la cúpula del Reichstag, la terminal de Stansted y el aeropuerto de Hong Kong. Recibió el Pritzker en 1999.",
      it: "Norman Foster crebbe in una Manchester operaia, si pagò da sé la scuola di architettura della città e ottenne una borsa per Yale, dove conobbe Richard Rogers. I due tornarono in Inghilterra per fondare Team 4 con Su Brumwell e Wendy Cheesman; sciolto il gruppo, Foster e Cheesman proseguirono come Foster Associates. Le opere iniziali sostengono una sola tesi con rara chiarezza: che un edificio debba essere un involucro leggero, calcolato e impiantisticamente servito, montabile in fretta e modificabile poi. La sede della Willis Faber a Ipswich e il Sainsbury Centre a Norwich lo dimostrarono in modo decisivo negli anni Settanta. Lo studio è diventato uno dei maggiori al mondo, firmando la banca di Hong Kong e Shanghai, la cupola del Reichstag, il terminal di Stansted e l'aeroporto di Hong Kong. Ha ricevuto il Pritzker nel 1999.",
    },
    awards: ['Pritzker Architecture Prize', 'RIBA Royal Gold Medal', 'Praemium Imperiale', 'Stirling Prize', 'Order of Merit'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q104898', title: 'Norman Foster (Q104898)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Norman_Foster', title: 'Norman Foster', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'eldred-evans',
    wikidataId: 'Q116767067',
    name: 'Eldred Evans',
    alternativeNames: ['Eldred Ann Oliver Evans'],
    gender: 'woman',
    born: 1937,
    died: 2022,
    floruit: { start: 1964, end: 2008, override: false },
    movements: 'unaffiliated',
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'cultural',
    signatureMaterial: 'concrete',
    portrait: {
      en: "Eldred Evans was born in London to the painter Merlyn Evans and grew up in South Africa. She returned to study at the Architectural Association and then spent a year at Yale alongside Norman Foster and Richard Rogers. In 1963 she met the Israeli architect David Shalev; from 1964 until 2008 they lived and worked together, and the practice of Evans & Shalev produced some hundred and fifty projects under both their names. Their reputation rests on a small number of quietly monumental public buildings in the west of England — Truro Crown Courts, the Quincentenary Library at Jesus College, Cambridge, and above all Tate St Ives, where a rendered drum set into the cliff turns the plan of a demolished gasholder into a gallery. She was appointed OBE and died in 2022.",
      es: "Eldred Evans nació en Londres, hija del pintor Merlyn Evans, y se crió en Sudáfrica. Volvió para estudiar en la Architectural Association y pasó después un año en Yale junto a Norman Foster y Richard Rogers. En 1963 conoció al arquitecto israelí David Shalev; desde 1964 hasta 2008 vivieron y trabajaron juntos, y el estudio Evans & Shalev produjo unos ciento cincuenta proyectos firmados por ambos. Su prestigio descansa en un puñado de edificios públicos discretamente monumentales en el oeste de Inglaterra: los juzgados de Truro, la Quincentenary Library del Jesus College de Cambridge y, sobre todo, la Tate St Ives, donde un tambor revocado incrustado en el acantilado convierte la planta de un gasómetro demolido en una galería. Fue nombrada OBE y murió en 2022.",
      it: "Eldred Evans nacque a Londra, figlia del pittore Merlyn Evans, e crebbe in Sudafrica. Tornò per studiare all'Architectural Association e trascorse poi un anno a Yale insieme a Norman Foster e Richard Rogers. Nel 1963 conobbe l'architetto israeliano David Shalev; dal 1964 al 2008 vissero e lavorarono insieme, e lo studio Evans & Shalev produsse circa centocinquanta progetti firmati da entrambi. La sua reputazione poggia su pochi edifici pubblici sommessamente monumentali nell'Inghilterra occidentale: il tribunale di Truro, la Quincentenary Library del Jesus College a Cambridge e soprattutto la Tate St Ives, dove un tamburo intonacato incassato nella scogliera trasforma la pianta di un gasometro demolito in una galleria. Fu nominata OBE e morì nel 2022.",
    },
    awards: ['Officer of the Order of the British Empire'],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q116767067', title: 'Eldred Evans (Q116767067)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Eldred_Evans', title: 'Eldred Evans', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'richard-rogers',
    wikidataId: 'Q237412',
    name: 'Richard Rogers',
    alternativeNames: ['Lord Rogers of Riverside', 'Richard George Rogers'],
    gender: 'man',
    born: 1933,
    died: 2021,
    floruit: { start: 1967, end: 2020, override: false },
    movements: [{ id: 'high-tech', primary: true }, { id: 'sustainable-architecture', primary: false }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'civic',
    signatureMaterial: 'steel-and-glass',
    portrait: {
      en: "Richard Rogers was born in Florence to an Anglo-Italian family that left for England in 1939. Dyslexic and unhappy at school, he found his footing at the Architectural Association and then at Yale, where he met Norman Foster; the two founded Team 4 on their return. Winning the Centre Pompidou competition with Renzo Piano in 1971 made him internationally famous at thirty-eight and fixed the terms of his architecture: structure, ducts and circulation pushed to the outside, the interior left as free, serviced floor. The Lloyd's building in London repeated the argument at higher intensity. Rogers was also a persistent public advocate — chairman of the Urban Task Force, adviser on London's planning, and a consistent voice for compact, mixed, walkable cities. He received the Pritzker Prize in 2007.",
      es: "Richard Rogers nació en Florencia, en una familia angloitaliana que se trasladó a Inglaterra en 1939. Disléxico y desdichado en el colegio, encontró su sitio en la Architectural Association y después en Yale, donde conoció a Norman Foster; al volver fundaron juntos Team 4. Ganar en 1971 el concurso del Centro Pompidou con Renzo Piano lo hizo internacionalmente célebre a los treinta y ocho años y fijó los términos de su arquitectura: estructura, conductos y circulaciones expulsados al exterior, y el interior dejado como planta libre y servida. El edificio del Lloyd's en Londres repitió el argumento con mayor intensidad. Rogers fue además un activista público constante: presidió el Urban Task Force, asesoró el planeamiento de Londres y defendió sin descanso la ciudad compacta, mixta y caminable. Recibió el Pritzker en 2007.",
      it: "Richard Rogers nacque a Firenze da una famiglia anglo-italiana che si trasferì in Inghilterra nel 1939. Dislessico e infelice a scuola, trovò la propria strada all'Architectural Association e poi a Yale, dove conobbe Norman Foster; al ritorno fondarono insieme Team 4. Vincere nel 1971 il concorso per il Centre Pompidou con Renzo Piano lo rese celebre a trentotto anni e fissò i termini della sua architettura: struttura, condotti e percorsi spinti all'esterno, l'interno lasciato come piano libero e servito. Il Lloyd's building di Londra ripeté l'argomento con intensità maggiore. Rogers fu anche un tenace protagonista del dibattito pubblico: presiedette l'Urban Task Force, fu consulente per la pianificazione di Londra e sostenne senza sosta la città compatta, mista e percorribile a piedi. Ricevette il Pritzker nel 2007.",
    },
    awards: ['Pritzker Architecture Prize', 'RIBA Royal Gold Medal', 'Praemium Imperiale', 'Stirling Prize'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q237412', title: 'Richard Rogers (Q237412)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Richard_Rogers', title: 'Richard Rogers', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'jan-kaplicky',
    wikidataId: 'Q555682',
    name: 'Jan Kaplický',
    alternativeNames: ['Jan Kaplicky'],
    gender: 'man',
    born: 1937,
    died: 2009,
    floruit: { start: 1979, end: 2003, override: false },
    movements: [{ id: 'neo-futurism', primary: true }, { id: 'high-tech', primary: false }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'commercial',
    signatureMaterial: 'mixed',
    portrait: {
      en: "Jan Kaplický was born in Prague in 1937 to a sculptor and a botanical illustrator, trained at the city's College of Applied Arts, and left for London in September 1968 rather than live under the Soviet occupation that followed the Prague Spring. He worked successively for Denys Lasdun, for Piano & Rogers on the Centre Pompidou team, and for Foster Associates before founding Future Systems in 1979 with David Nixon, joined from 1989 by Amanda Levete as partner. Kaplický distrusted the rectangular room on principle — he liked to ask where it was written that buildings had to be boxes — and pursued organic, aerodynamic forms through the Lord's Media Centre and the Selfridges store in Birmingham. A late commission to rebuild Prague's National Library collapsed in 2008 under fierce local opposition to its bulging form; he died in his native city in January 2009.",
      es: "Jan Kaplický nació en Praga en 1937, hijo de un escultor y una ilustradora botánica, se formó en la Escuela de Artes Aplicadas de la ciudad y se marchó a Londres en 1968 antes que vivir bajo la ocupación soviética. Trabajó para Denys Lasdun, para Piano & Rogers en el equipo del Centro Pompidou y para Foster Associates antes de fundar Future Systems en 1979 junto a David Nixon, a quienes se unió desde 1989 Amanda Levete como socia. Desconfiaba por principio de la habitación rectangular —le gustaba preguntar dónde estaba escrito que los edificios debían ser cajas— y persiguió formas orgánicas y aerodinámicas en el Media Centre de Lord's y en los almacenes Selfridges de Birmingham. Un encargo tardío para reconstruir la Biblioteca Nacional de Praga se hundió en 2008 ante la oposición local a su forma abultada; murió en su ciudad natal en enero de 2009.",
      it: "Jan Kaplický nacque a Praga nel 1937, figlio di uno scultore e di un'illustratrice botanica, si formò alla Scuola di Arti Applicate della città e partì per Londra nel settembre 1968 piuttosto che vivere sotto l'occupazione sovietica seguita alla Primavera di Praga. Lavorò successivamente per Denys Lasdun, per Piano & Rogers nel gruppo del Centre Pompidou e per Foster Associates prima di fondare Future Systems nel 1979 insieme a David Nixon, cui si unì dal 1989 Amanda Levete come socia. Kaplický diffidava per principio della stanza rettangolare — amava chiedere dove fosse scritto che gli edifici dovessero essere scatole — e inseguì forme organiche e aerodinamiche nel Media Centre di Lord's e nel negozio Selfridges di Birmingham. Un tardo incarico per ricostruire la Biblioteca Nazionale di Praga naufragò nel 2008 di fronte a una forte opposizione locale alla sua forma rigonfia; morì nella sua città natale nel gennaio 2009.",
    },
    awards: ['Stirling Prize', 'RIBA Award for Architecture'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q555682', title: 'Jan Kaplický (Q555682)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Jan_Kaplick%C3%BD', title: 'Jan Kaplický', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'peter-smithson',
    wikidataId: 'Q15056051',
    name: 'Peter Smithson',
    alternativeNames: ['Peter Denham Smithson'],
    gender: 'man',
    born: 1923,
    died: 2003,
    floruit: { start: 1954, end: 1993, override: false },
    movements: 'unaffiliated',
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'housing',
    signatureMaterial: 'brick',
    portrait: {
      en: "Peter Smithson was born in Stockton-on-Tees in 1923 and studied architecture and town planning at King's College, Durham, his training interrupted by wartime service with the Madras Sappers and Miners in India and Burma. He met Alison Gill at Durham; they married in 1949 and opened a joint practice the following year, working together until her death in 1993 with every commission published under both names. Winning the competition for Hunstanton School in 1949 gave the pair, and the term New Brutalism, their first public identity; the Economist Building and Robin Hood Gardens followed, alongside a large body of writing and teaching that carried their arguments further than their small built output could. Peter was the more active theorist of Team 10's 1953 revolt against orthodox CIAM planning, and later taught at Bath and the Architectural Association.",
      es: "Peter Smithson nació en Stockton-on-Tees en 1923 y estudió arquitectura y urbanismo en el King's College de Durham, formación interrumpida por el servicio con los zapadores de Madrás en la India y Birmania. Conoció a Alison Gill en Durham; se casaron en 1949 y abrieron un estudio conjunto al año siguiente, y trabajaron juntos hasta la muerte de ella en 1993, con cada encargo publicado bajo ambos nombres. Ganar el concurso de Hunstanton en 1949 dio a la pareja, y al término nuevo brutalismo, su primera identidad pública; siguieron el edificio del Economist y Robin Hood Gardens, junto a una obra escrita y docente que llevó sus argumentos más lejos de lo que pudo su reducida obra construida. Peter fue el teórico más activo en la revuelta del Team 10 de 1953 contra el planeamiento ortodoxo del CIAM, y después enseñó en Bath y en la Architectural Association.",
      it: "Peter Smithson nacque a Stockton-on-Tees nel 1923 e studiò architettura e urbanistica al King's College di Durham, formazione interrotta dal servizio bellico con gli zappatori di Madras in India e Birmania. Conobbe Alison Gill a Durham; si sposarono nel 1949 e aprirono uno studio comune l'anno seguente, lavorando insieme fino alla morte di lei nel 1993, con ogni incarico pubblicato a nome di entrambi. Vincere il concorso per la scuola di Hunstanton nel 1949 diede alla coppia, e al termine New Brutalism, la loro prima identità pubblica; seguirono l'Economist Building e Robin Hood Gardens, insieme a una vasta opera scritta e didattica che portò le loro tesi più lontano di quanto potesse la loro esigua opera costruita. Peter fu il teorico più attivo nella rivolta del Team 10 del 1953 contro la pianificazione ortodossa del CIAM, e insegnò poi a Bath e all'Architectural Association.",
    },
    awards: [],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q15056051', title: 'Peter Smithson (Q15056051)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Peter_Smithson', title: 'Peter Smithson', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'david-shalev',
    wikidataId: 'Q20965915',
    name: 'David Shalev',
    alternativeNames: [],
    gender: 'man',
    born: 1934,
    died: 2018,
    floruit: { start: 1964, end: 2008, override: false },
    movements: 'unaffiliated',
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'cultural',
    signatureMaterial: 'concrete',
    portrait: {
      en: "David Shalev was born in Jerusalem in 1934 and trained in Haifa, in a school he later described as an outpost of the Bauhaus set down beside an ancient landscape. He moved to London and met Eldred Evans in 1963; from 1964 until 2008 they lived and worked together as Evans & Shalev, producing some hundred and fifty projects credited to both partners. Newport High School, won in open competition in 1967, gave the practice its first major public commission; the Crown Courts at Truro and the Quincentenary Library at Jesus College, Cambridge, followed, and Tate St Ives, built into a cliff on the site of a demolished gasholder, became its best-known work. Shalev also taught at the Architectural Association and later at Bath, and died in London in January 2018.",
      es: "David Shalev nació en Jerusalén en 1934 y se formó en Haifa, en una escuela que más tarde describió como un puesto avanzado de la Bauhaus asentado junto a un paisaje milenario. Se trasladó a Londres y conoció a Eldred Evans en 1963; desde 1964 hasta 2008 vivieron y trabajaron juntos como Evans & Shalev, produciendo un centenar y medio de proyectos firmados por ambos socios. La escuela secundaria de Newport, ganada en concurso abierto en 1967, dio al estudio su primer gran encargo público; siguieron los juzgados de Truro y la Quincentenary Library del Jesus College de Cambridge, y la Tate St Ives, construida en un acantilado sobre el solar de un gasómetro demolido, se convirtió en su obra más conocida. Shalev enseñó también en la Architectural Association y después en Bath, y murió en Londres en enero de 2018.",
      it: "David Shalev nacque a Gerusalemme nel 1934 e si formò a Haifa, in una scuola che in seguito descrisse come un avamposto del Bauhaus posato accanto a un paesaggio millenario. Si trasferì a Londra e conobbe Eldred Evans nel 1963; dal 1964 al 2008 vissero e lavorarono insieme come Evans & Shalev, producendo circa centocinquanta progetti firmati da entrambi i soci. La scuola secondaria di Newport, vinta in concorso aperto nel 1967, diede allo studio il suo primo grande incarico pubblico; seguirono il tribunale di Truro e la Quincentenary Library del Jesus College a Cambridge, e la Tate St Ives, costruita in una scogliera sul sito di un gasometro demolito, ne divenne l'opera più nota. Shalev insegnò anche all'Architectural Association e poi a Bath, e morì a Londra nel gennaio 2018.",
    },
    awards: [],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q20965915', title: 'David Shalev (Q20965915)', license: null },
      { kind: 'publication', url: 'https://www.architectsjournal.co.uk/news/obituary-tate-st-ives-architect-david-shalev', title: 'Obituary: Tate St Ives architect David Shalev', license: null },
    ],
  },
  {
    id: 'yvonne-farrell',
    wikidataId: 'Q16151248',
    name: 'Yvonne Farrell',
    alternativeNames: [],
    gender: 'woman',
    born: 1951,
    died: null,
    floruit: { start: 1985, end: 2026, override: false },
    movements: 'unaffiliated',
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'educational',
    signatureMaterial: 'concrete',
    portrait: {
      en: "Yvonne Farrell was born in Tullamore, County Offaly, in 1951 and trained at University College Dublin, where she has taught since 1976. In 1978 she and Shelley McNamara founded Grafton Architects, naming the practice after the Dublin street of their first office rather than after themselves. Ireland's building programme in the 1980s and 1990s gave the young practice little to build, and its reputation grew instead through teaching and through small, exacting commissions — schools, a library, a health centre — before the Milan economics university Bocconi and the engineering campus UTEC in Lima brought international recognition for a manner of building in raw concrete, section and light rather than surface. Farrell and McNamara shared the 2020 Pritzker Prize, the first won by an Irish practice, and the RIBA Royal Gold Medal the same year.",
      es: "Yvonne Farrell nació en Tullamore, condado de Offaly, en 1951 y se formó en el University College de Dublín, donde enseña desde 1976. En 1978 fundó junto a Shelley McNamara el estudio Grafton Architects, con un nombre tomado de la calle dublinesa de su primer despacho y no de ellas mismas. El programa constructivo de Irlanda en los ochenta y noventa dio poco trabajo al joven estudio, y su prestigio creció más bien por la docencia y por encargos pequeños y exigentes —escuelas, una biblioteca, un centro de salud— antes de que la universidad Bocconi de Milán y el campus de ingeniería UTEC de Lima trajeran reconocimiento internacional a una manera de construir en hormigón crudo, sección y luz antes que en superficie. Farrell y McNamara compartieron el Pritzker de 2020, el primero ganado por un estudio irlandés, y la Royal Gold Medal del RIBA el mismo año.",
      it: "Yvonne Farrell nacque a Tullamore, contea di Offaly, nel 1951 e si formò allo University College di Dublino, dove insegna dal 1976. Nel 1978 fondò con Shelley McNamara lo studio Grafton Architects, chiamato non da loro stesse ma dalla via dublinese del loro primo ufficio. Il programma edilizio irlandese degli anni Ottanta e Novanta diede poco lavoro al giovane studio, e la sua fama crebbe piuttosto attraverso l'insegnamento e commesse piccole ed esigenti — scuole, una biblioteca, un centro sanitario — prima che l'università economica Bocconi di Milano e il campus di ingegneria UTEC di Lima portassero un riconoscimento internazionale a un modo di costruire fondato sul cemento grezzo, sulla sezione e sulla luce più che sulla superficie. Farrell e McNamara condivisero il Pritzker 2020, il primo vinto da uno studio irlandese, e la Royal Gold Medal del RIBA lo stesso anno.",
    },
    awards: ['Pritzker Architecture Prize', 'RIBA Royal Gold Medal'],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q16151248', title: 'Yvonne Farrell (Q16151248)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Yvonne_Farrell', title: 'Yvonne Farrell', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'shelley-mcnamara',
    wikidataId: 'Q21132821',
    name: 'Shelley McNamara',
    alternativeNames: [],
    gender: 'woman',
    born: 1952,
    died: null,
    floruit: { start: 1985, end: 2026, override: false },
    movements: 'unaffiliated',
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'educational',
    signatureMaterial: 'concrete',
    portrait: {
      en: "Shelley McNamara was born in Lisdoonvarna, County Clare, in 1952 and studied architecture at University College Dublin, where she began teaching in 1976 alongside her studio partner Yvonne Farrell. The two founded Grafton Architects in 1978 and spent two quiet decades on modest Irish commissions — the Urban Institute at UCD, a community school at Milford in Donegal, an arts centre at Navan — while building an international teaching career that took McNamara to Yale's Louis Kahn chair and to visiting posts in Switzerland. She has described the practice's method as building the structure first and letting the space follow from it rather than the reverse, a principle legible in the terraced, top-lit halls of the Bocconi University extension in Milan. She and Farrell received the Pritzker Prize and the RIBA Royal Gold Medal in 2020.",
      es: "Shelley McNamara nació en Lisdoonvarna, condado de Clare, en 1952 y estudió arquitectura en el University College de Dublín, donde empezó a enseñar en 1976 junto a su socia de estudio Yvonne Farrell. Ambas fundaron Grafton Architects en 1978 y pasaron dos décadas discretas en encargos irlandeses modestos —el Urban Institute del UCD, una escuela comunitaria en Milford, condado de Donegal, un centro de arte en Navan— mientras construían una carrera docente internacional que llevó a McNamara a la cátedra Louis Kahn de Yale y a estancias en Suiza. Ha descrito el método del estudio como levantar primero la estructura y dejar que el espacio nazca de ella, y no al revés, un principio legible en las salas escalonadas e iluminadas cenitalmente de la ampliación de la Universidad Bocconi en Milán. Ella y Farrell recibieron el Pritzker y la Royal Gold Medal del RIBA en 2020.",
      it: "Shelley McNamara nacque a Lisdoonvarna, contea di Clare, nel 1952 e studiò architettura allo University College di Dublino, dove iniziò a insegnare nel 1976 accanto alla socia di studio Yvonne Farrell. Le due fondarono Grafton Architects nel 1978 e trascorsero due decenni discreti in commesse irlandesi modeste — l'Urban Institute dello UCD, una scuola comunitaria a Milford, contea di Donegal, un centro d'arte a Navan — costruendo intanto una carriera didattica internazionale che portò McNamara alla cattedra Louis Kahn di Yale e a incarichi in Svizzera. Ha descritto il metodo dello studio come costruire prima la struttura e lasciare che lo spazio ne nasca, e non il contrario, principio leggibile nelle sale digradanti e illuminate dall'alto dell'ampliamento dell'Università Bocconi a Milano. Lei e Farrell hanno ricevuto il Pritzker e la Royal Gold Medal del RIBA nel 2020.",
    },
    awards: ['Pritzker Architecture Prize', 'RIBA Royal Gold Medal'],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q21132821', title: 'Shelley McNamara (Q21132821)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Shelley_McNamara', title: 'Shelley McNamara', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    // Task 9 re-review Important finding: this slice is pre-assigned ownership
    // of Zaha Hadid (wave5-contract-v2.md §3) and the prior fix round's search
    // stopped one candidate short. London Aquatics Centre (Q308874) carries an
    // individual P84 credit to Hadid, independently re-confirmed here via the
    // live Wikidata entity JSON, closing the slice's Hadid gap.
    id: 'zaha-hadid',
    wikidataId: 'Q47780',
    name: 'Zaha Hadid',
    alternativeNames: ['Dame Zaha Hadid'],
    gender: 'woman',
    born: 1950,
    died: 2016,
    floruit: { start: 1993, end: 2016, override: false },
    movements: [{ id: 'deconstructivism', primary: true }, { id: 'parametricism', primary: false }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'cultural',
    signatureMaterial: 'concrete',
    portrait: {
      en: "Zaha Hadid was born in Baghdad in 1950 to a prominent Iraqi family, studied mathematics at the American University of Beirut, and moved to London in 1972 to train at the Architectural Association under Rem Koolhaas and Elia Zenghelis. She worked briefly at Koolhaas's Office for Metropolitan Architecture before opening her own practice in 1980, spending nearly two decades known chiefly through fractured, exploded drawings shown at MoMA's 1988 Deconstructivist Architecture exhibition while almost nothing of hers got built. The Vitra Fire Station of 1993 was her first completed building. Parametric software later let her practice realise at scale the continuously curved geometry she had drawn for years, at the MAXXI in Rome and the Heydar Aliyev Center in Baku. In 2004 she became the first woman to win the Pritzker Prize alone. She died suddenly in Miami in March 2016, mid-career.",
      es: 'Zaha Hadid nació en Bagdad en 1950, en una familia iraquí destacada, estudió matemáticas en la Universidad Americana de Beirut y se trasladó a Londres en 1972 para formarse en la Architectural Association con Rem Koolhaas y Elia Zenghelis. Trabajó brevemente en la Office for Metropolitan Architecture de Koolhaas antes de abrir su propio estudio en 1980, y pasó casi dos décadas conocida sobre todo por dibujos fracturados y estallados, expuestos en la muestra Deconstructivist Architecture del MoMA en 1988, mientras apenas nada suyo se construía. La estación de bomberos de Vitra, de 1993, fue su primer edificio terminado. El software paramétrico permitió después realizar a gran escala la geometría de curva continua que llevaba años dibujando, en el MAXXI de Roma y el Centro Heydar Aliyev de Bakú. En 2004 fue la primera mujer en ganar el Pritzker en solitario. Murió repentinamente en Miami en marzo de 2016.',
      it: "Zaha Hadid nacque a Baghdad nel 1950 in una famiglia irachena in vista, studiò matematica all'Università Americana di Beirut e si trasferì a Londra nel 1972 per formarsi alla Architectural Association con Rem Koolhaas ed Elia Zenghelis. Lavorò brevemente nell'Office for Metropolitan Architecture di Koolhaas prima di aprire nel 1980 un proprio studio, e trascorse quasi due decenni conosciuta soprattutto per disegni frammentati ed esplosi, esposti nella mostra Deconstructivist Architecture del MoMA nel 1988, mentre quasi nulla di suo veniva costruito. La stazione dei vigili del fuoco di Vitra, del 1993, fu il suo primo edificio realizzato. Il software parametrico permise poi di realizzare su grande scala la geometria a curva continua che disegnava da anni, al MAXXI di Roma e al Centro Heydar Aliyev di Baku. Nel 2004 fu la prima donna a vincere da sola il Pritzker. Morì improvvisamente a Miami nel marzo 2016.",
    },
    awards: ['Pritzker Architecture Prize', 'RIBA Royal Gold Medal', 'Praemium Imperiale', 'Stirling Prize', 'Dame Commander of the Order of the British Empire'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q47780', title: 'Zaha Hadid (Q47780)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Zaha_Hadid', title: 'Zaha Hadid', license: 'CC BY-SA 4.0' },
    ],
  },
];
