import type { Architect } from '@/types/architect';

// Wave 5 curator agent (Central and Eastern Europe): real, sourced Architect entries for this slice.
//
// Slice countries: PL, CZ, SK, HU, RO, BG, RS, HR, SI, BA, MK, AL, UA, BY, MD, RU.
// `workRegions` and `workCentroid` are deliberately left empty/zeroed: the
// curation script derives both from each architect's buildings and overwrites
// whatever is typed here.
export const EUROPE_CENTRAL_ARCHITECTS: Architect[] = [
  {
    id: 'jan-santini-aichel',
    wikidataId: 'Q472688',
    name: 'Jan Blažej Santini-Aichel',
    alternativeNames: ['Johann Blasius Santini Aichel', 'Giovanni Santini', 'Jan Santini Aichel'],
    gender: 'man',
    born: 1677,
    died: 1723,
    floruit: { start: 1703, end: 1723, override: false },
    movements: [
      { id: 'baroque', primary: true },
      { id: 'gothic', primary: false },
    ],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'sacral',
    signatureMaterial: 'stone',
    portrait: {
      en: 'Born in Prague to a family of Italian stonemasons, Santini-Aichel was lame from birth and took up drawing rather than the chisel. A journey through Austria to Rome in the late 1690s put him in front of Borromini, and from 1703 he ran a Prague practice that worked almost exclusively for the Bohemian and Moravian Cistercian and Benedictine abbeys. What he built for them has no real parallel. He set out plans as stars, pentagons and interlocking circles, then roofed them with ribbed vaults and pointed arches quoted from the Gothic — a deliberate archaism his monastic clients read as loyalty to their medieval foundations, and which later scholarship named Baroque Gothic. He worked without pause for twenty years and died at forty-six.',
      es: 'Nacido en Praga en una familia de canteros italianos, Santini-Aichel fue cojo de nacimiento y se dedicó al dibujo antes que al cincel. Un viaje por Austria hasta Roma a finales de la década de 1690 lo puso frente a Borromini, y desde 1703 dirigió en Praga un estudio que trabajó casi en exclusiva para las abadías cistercienses y benedictinas de Bohemia y Moravia. Lo que construyó para ellas no tiene equivalente. Trazó plantas en forma de estrella, de pentágono y de círculos entrelazados, y las cubrió con bóvedas de crucería y arcos apuntados citados del gótico: un arcaísmo deliberado que sus clientes monásticos leyeron como fidelidad a sus fundaciones medievales y que la crítica posterior llamó gótico barroco. Trabajó sin pausa veinte años y murió a los cuarenta y seis.',
      it: 'Nato a Praga in una famiglia di scalpellini italiani, Santini-Aichel era zoppo dalla nascita e si dedicò al disegno anziché allo scalpello. Un viaggio attraverso l\'Austria fino a Roma alla fine degli anni Novanta del Seicento lo mise davanti a Borromini, e dal 1703 diresse a Praga uno studio che lavorò quasi esclusivamente per le abbazie cistercensi e benedettine di Boemia e Moravia. Ciò che costruì per loro non ha veri paralleli. Impostò piante a stella, a pentagono e a cerchi intrecciati, coprendole poi con volte costolonate e archi acuti citati dal gotico: un arcaismo voluto che i committenti monastici lessero come fedeltà alle proprie fondazioni medievali e che gli studi successivi chiamarono gotico barocco. Lavorò senza sosta per vent\'anni e morì a quarantasei.',
    },
    awards: [],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q472688', title: 'Jan Santini Aichel (Q472688)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Jan_Santini_Aichel', title: 'Jan Santini Aichel', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'mimar-hayruddin',
    wikidataId: 'Q11882869',
    name: 'Mimar Hayruddin',
    alternativeNames: ['Mimar Hajrudin', 'Mimar Hayreddin', 'Мимар Хајрудин'],
    gender: 'man',
    born: null,
    died: null,
    floruit: { start: 1557, end: 1566, override: true },
    movements: [{ id: 'ottoman-classical', primary: true }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'infrastructure',
    signatureMaterial: 'stone',
    portrait: {
      en: 'Almost nothing survives about Hayruddin except one bridge and the tradition attached to it. Ottoman sources name him an apprentice of Mimar Sinan, the chief court architect whose office standardised imperial building across the empire, and record that Suleiman the Magnificent sent him to Mostar in 1557 to replace a swaying wooden suspension crossing over the Neretva. The single stone arch he raised there was, on completion, among the widest ever built. The best-known story about him — that he made arrangements for his own funeral on the day the centring was struck, expecting the span to fall and his execution to follow — is legend rather than record, but it has attached itself so firmly to the bridge that the two are told together. No other work is securely attributed to him.',
      es: 'De Hayruddin apenas sobrevive nada salvo un puente y la tradición que lo acompaña. Las fuentes otomanas lo nombran aprendiz de Mimar Sinan, el arquitecto mayor de la corte cuya oficina normalizó la construcción imperial, y registran que Solimán el Magnífico lo envió a Mostar en 1557 para sustituir un bamboleante puente colgante de madera sobre el Neretva. El arco único de piedra que levantó allí figuraba, al terminarse, entre los más anchos jamás construidos. El relato más conocido sobre él —que dispuso su propio funeral el día en que se retiró la cimbra, esperando que el arco cayera y que su ejecución siguiera— es leyenda y no documento, pero se ha adherido al puente con tal firmeza que ambos se cuentan juntos. Ninguna otra obra se le atribuye con seguridad.',
      it: 'Di Hayruddin non sopravvive quasi nulla se non un ponte e la tradizione che lo accompagna. Le fonti ottomane lo dicono apprendista di Mimar Sinan, l\'architetto capo di corte il cui ufficio normalizzò l\'edilizia imperiale, e registrano che Solimano il Magnifico lo inviò a Mostar nel 1557 per sostituire un oscillante ponte sospeso di legno sulla Neretva. L\'unica arcata in pietra che vi innalzò era, al momento del completamento, fra le più ampie mai costruite. Il racconto più noto sul suo conto — che avesse predisposto il proprio funerale il giorno in cui fu tolta la centina, aspettandosi il crollo dell\'arco e la propria esecuzione — è leggenda e non documento, ma si è saldato al ponte al punto che i due si narrano insieme. Nessun\'altra opera gli è attribuita con certezza.',
    },
    awards: [],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q11882869', title: 'Mimar Hayruddin (Q11882869)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Stari_Most', title: 'Stari Most', license: 'CC BY-SA 4.0' },
      { kind: 'institution', url: 'https://whc.unesco.org/en/list/946/', title: 'Old Bridge Area of the Old City of Mostar — UNESCO World Heritage Centre', license: null },
    ],
  },
  {
    id: 'odon-lechner',
    wikidataId: 'Q294065',
    name: 'Ödön Lechner',
    alternativeNames: ['Lechner Ödön', 'János Ödön Lechner'],
    gender: 'man',
    born: 1845,
    died: 1914,
    floruit: { start: 1872, end: 1913, override: false },
    movements: [{ id: 'art-nouveau', primary: true }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'civic',
    signatureMaterial: 'brick',
    portrait: {
      en: 'Lechner trained in Pest and Berlin and spent his early career on competent French-inflected apartment blocks before deciding that Hungary needed a modern architecture that was recognisably its own. He looked for it first in Hungarian folk embroidery and later, following the linguistic theories current in Budapest, in Indian and Persian ornament, which he believed shared an ancestry with Magyar pattern. The vehicle was ceramic: he worked repeatedly with the Zsolnay factory at Pécs, whose frost-proof pyrogranite let him carry saturated colour and relief across roofs and facades that would otherwise have gone grey in the Danube winter. Beneath the tilework his buildings are matter-of-fact iron-and-brick structures. He died largely unbuilt in his last decade, having failed to convert the profession he had scandalised.',
      es: 'Lechner se formó en Pest y Berlín y pasó sus primeros años proyectando competentes bloques de viviendas de aire francés, hasta que decidió que Hungría necesitaba una arquitectura moderna reconociblemente propia. La buscó primero en el bordado popular húngaro y después, siguiendo las teorías lingüísticas en boga en Budapest, en el ornamento indio y persa, en el que creía ver un tronco común con el motivo magiar. El vehículo fue la cerámica: trabajó una y otra vez con la fábrica Zsolnay de Pécs, cuyo pirogranito resistente a la helada le permitió llevar color saturado y relieve a cubiertas y fachadas que de otro modo habrían quedado grises en el invierno danubiano. Bajo el alicatado, sus edificios son estructuras prosaicas de hierro y ladrillo. Murió tras una última década casi sin obra construida.',
      it: 'Lechner si formò a Pest e a Berlino e passò i primi anni a progettare competenti case da reddito di gusto francese, finché decise che l\'Ungheria aveva bisogno di un\'architettura moderna riconoscibilmente propria. La cercò dapprima nel ricamo popolare ungherese e poi, seguendo le teorie linguistiche allora in voga a Budapest, nell\'ornato indiano e persiano, in cui credeva di riconoscere un ceppo comune con il motivo magiaro. Il veicolo fu la ceramica: lavorò più volte con la manifattura Zsolnay di Pécs, il cui pirogranito resistente al gelo gli permise di portare colore saturo e rilievo su tetti e facciate che altrimenti sarebbero rimasti grigi nell\'inverno danubiano. Sotto il rivestimento, i suoi edifici sono prosaiche strutture in ferro e mattoni. Morì dopo un ultimo decennio quasi privo di opere costruite.',
    },
    awards: ['Hungarian Heritage Award'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q294065', title: 'Ödön Lechner (Q294065)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/%C3%96d%C3%B6n_Lechner', title: 'Ödön Lechner', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    // Co-architect of the Museum of Applied Arts, Budapest (see coArchitects
    // on that building). Wikipedia's own text credits the museum jointly as
    // "designed by Ödön Lechner and Gyula Pártos" with neither named senior;
    // Pártos's own biography records the two dividing artistic and
    // organisational leadership rather than one simply assisting the other.
    id: 'gyula-partos',
    wikidataId: 'Q713731',
    name: 'Gyula Pártos',
    alternativeNames: ['Julius Puntzmann'],
    gender: 'man',
    born: 1845,
    died: 1916,
    floruit: { start: 1871, end: 1912, override: false },
    movements: [{ id: 'art-nouveau', primary: true }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'civic',
    signatureMaterial: 'brick',
    portrait: {
      en: 'Pártos, born Julius Puntzmann at Apatin, trained under Antal Szkalnitzky in Pest and took an architecture degree in Berlin in 1870, then formed a Budapest partnership with Ödön Lechner that lasted a quarter-century. Their own account of the division of labour has Lechner leading the artistic side and Pártos running the practice\'s organisational side, though the buildings they produced — culminating in the Museum of Applied Arts, opened for the Hungarian millennial celebrations of 1896 — carry both their names jointly in the record. The partnership dissolved that year. Pártos then worked independently for sixteen years, mostly on churches, chapels and municipal buildings across Hungary, Slovakia and Serbia, in a manner closer to conventional historicism than to the Hungarian Art Nouveau he had helped Lechner build.',
      es: 'Pártos, nacido Julius Puntzmann en Apatin, se formó con Antal Szkalnitzky en Pest y se tituló en arquitectura en Berlín en 1870; formó después en Budapest una sociedad con Ödön Lechner que duró un cuarto de siglo. Según su propio relato del reparto de tareas, Lechner llevaba la parte artística y Pártos la organización del estudio, aunque los edificios que produjeron juntos —culminados en el Museo de Artes Aplicadas, inaugurado para las celebraciones del milenario húngaro de 1896— figuran en el registro con ambos nombres. La sociedad se disolvió ese año. Pártos trabajó después dieciséis años en solitario, sobre todo en iglesias, capillas y edificios municipales de Hungría, Eslovaquia y Serbia, en un estilo más cercano al historicismo convencional que al modernismo húngaro que había ayudado a construir junto a Lechner.',
      it: 'Pártos, nato Julius Puntzmann ad Apatin, si formò con Antal Szkalnitzky a Pest e si laureò in architettura a Berlino nel 1870; costituì poi a Budapest una società con Ödön Lechner durata un quarto di secolo. Secondo il loro stesso resoconto della divisione dei compiti, Lechner guidava la parte artistica e Pártos l\'organizzazione dello studio, sebbene gli edifici realizzati insieme — culminati nel Museo delle Arti Applicate, inaugurato per le celebrazioni del millenario ungherese del 1896 — rechino nel registro entrambi i nomi. La società si sciolse quell\'anno. Pártos lavorò poi per sedici anni da solo, soprattutto su chiese, cappelle ed edifici municipali in Ungheria, Slovacchia e Serbia, in uno stile più vicino allo storicismo convenzionale che al modernismo ungherese che aveva contribuito a costruire accanto a Lechner.',
    },
    awards: [],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q713731', title: 'Gyula Pártos (Q713731)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Gyula_P%C3%A1rtos', title: 'Gyula Pártos', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Museum_of_Applied_Arts_(Budapest)', title: 'Museum of Applied Arts (Budapest)', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'joze-plecnik',
    wikidataId: 'Q314886',
    name: 'Jože Plečnik',
    alternativeNames: ['Josip Plečnik', 'Joseph Plecnik'],
    gender: 'man',
    born: 1872,
    died: 1957,
    floruit: { start: 1903, end: 1952, override: false },
    movements: 'unaffiliated',
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'sacral',
    signatureMaterial: 'stone',
    portrait: {
      en: 'A joiner\'s son from Ljubljana, Plečnik was picked out by Otto Wagner in Vienna and built the Zacherlhaus there before the First World War. He then worked in three cities in succession: Prague, where Masaryk gave him the rebuilding of the castle for the new republic, and Ljubljana, which he redrew almost single-handedly with bridges, embankments, a market, a cemetery and a library. He refused the label the century offered him. Trained inside the Secession, he kept the column, the architrave and the axis, then handled them with such freedom — a Doric order in raw brick, a pediment carried on stacked stone drums — that the result reads neither as revival nor as modernism. Comparisons to Gaudí in Barcelona are commonplace and roughly fair.',
      es: 'Hijo de un ebanista de Liubliana, Plečnik fue distinguido por Otto Wagner en Viena, donde construyó la Zacherlhaus antes de la Primera Guerra Mundial. Trabajó después en tres ciudades sucesivas: Praga, donde Masaryk le encomendó la reforma del castillo para la nueva república, y Liubliana, que rediseñó casi en solitario con puentes, malecones, un mercado, un cementerio y una biblioteca. Rechazó la etiqueta que el siglo le ofrecía. Formado dentro de la Secesión, conservó la columna, el arquitrabe y el eje, pero los manejó con tal libertad —un orden dórico en ladrillo crudo, un frontón sostenido por tambores de piedra apilados— que el resultado no se lee ni como historicismo ni como modernidad. La comparación con Gaudí en Barcelona es habitual y aproximadamente justa.',
      it: 'Figlio di un falegname di Lubiana, Plečnik fu notato da Otto Wagner a Vienna, dove costruì la Zacherlhaus prima della Grande Guerra. Lavorò poi in tre città successive: Praga, dove Masaryk gli affidò la risistemazione del castello per la nuova repubblica, e Lubiana, che ridisegnò quasi da solo con ponti, argini, un mercato, un cimitero e una biblioteca. Rifiutò l\'etichetta che il secolo gli offriva. Formatosi dentro la Secessione, conservò la colonna, l\'architrave e l\'asse, ma li maneggiò con tale libertà — un ordine dorico in mattone crudo, un frontone retto da rocchi di pietra sovrapposti — che il risultato non si legge né come revival né come modernismo. Il paragone con Gaudí a Barcellona è frequente e sostanzialmente giusto.',
    },
    awards: [],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q314886', title: 'Jože Plečnik (Q314886)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Jo%C5%BEe_Ple%C4%8Dnik', title: 'Jože Plečnik', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'konstantin-melnikov',
    wikidataId: 'Q930',
    name: 'Konstantin Melnikov',
    alternativeNames: ['Konstantin Stepanovich Melnikov', 'Константин Степанович Мельников'],
    gender: 'man',
    born: 1890,
    died: 1974,
    floruit: { start: 1923, end: 1936, override: false },
    movements: [{ id: 'constructivism', primary: true }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'cultural',
    signatureMaterial: 'brick',
    portrait: {
      en: 'Melnikov was born into a peasant family on the northern edge of Moscow and reached architecture through a patron who noticed a boy who drew. His entire built career fits into a single decade. Between 1923 and 1933 he produced the Soviet pavilion for the Paris exhibition of 1925, five workers\' clubs in and around Moscow, four bus garages and one house — his own. Critics file him with the Constructivists and he shared their clients, but he never accepted the group\'s discipline, preferring geometric figures pushed until they became strange: interlocking cylinders, a fan of seating cantilevered over a street, a diagonal parking ramp. When Stalinist neoclassicism closed the argument in the mid-1930s he refused to convert, and spent forty years painting portraits and teaching.',
      es: 'Melnikov nació en una familia campesina del extremo norte de Moscú y llegó a la arquitectura gracias a un protector que reparó en un niño que dibujaba. Toda su carrera construida cabe en una década. Entre 1923 y 1933 levantó el pabellón soviético de la exposición de París de 1925, cinco clubes obreros en Moscú y sus alrededores, cuatro cocheras de autobuses y una casa: la suya. La crítica lo agrupa con los constructivistas y compartió clientela con ellos, pero nunca aceptó la disciplina del grupo: prefería figuras geométricas forzadas hasta volverse extrañas —cilindros encajados, un abanico de gradas en voladizo sobre la calle, una rampa diagonal de aparcamiento—. Cuando el neoclasicismo estalinista cerró el debate hacia 1935 se negó a convertirse y pasó cuarenta años pintando retratos y enseñando.',
      it: 'Melnikov nacque in una famiglia contadina all\'estremità settentrionale di Mosca e arrivò all\'architettura grazie a un protettore che notò un ragazzo capace di disegnare. Tutta la sua carriera costruita sta in un decennio. Fra il 1923 e il 1933 realizzò il padiglione sovietico all\'esposizione di Parigi del 1925, cinque club operai a Mosca e dintorni, quattro rimesse per autobus e una casa: la propria. La critica lo accosta ai costruttivisti e ne condivise la committenza, ma non accettò mai la disciplina del gruppo: preferiva figure geometriche spinte fino a diventare estranee — cilindri incastrati, un ventaglio di gradinate a sbalzo sulla strada, una rampa diagonale per il parcheggio. Quando il neoclassicismo staliniano chiuse la discussione, a metà anni Trenta, rifiutò di convertirsi e passò quarant\'anni a dipingere ritratti e a insegnare.',
    },
    awards: [],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q930', title: 'Konstantin Melnikov (Q930)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Konstantin_Melnikov', title: 'Konstantin Melnikov', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'karel-hubacek',
    wikidataId: 'Q699642',
    name: 'Karel Hubáček',
    alternativeNames: [],
    gender: 'man',
    born: 1924,
    died: 2011,
    floruit: { start: 1958, end: 1998, override: false },
    movements: [
      { id: 'brutalism', primary: true },
      { id: 'high-tech', primary: false },
    ],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'civic',
    signatureMaterial: 'concrete',
    portrait: {
      en: 'Hubáček spent his working life in Liberec rather than Prague, and in 1968 turned the state design office he led into SIAL, briefly one of the few semi-independent architectural practices in Czechoslovakia. He worked by starting from the engineering. His method was to find a structural idea specific enough that the plan, the profile and the cladding all followed from it, then hold the client to it: at Ještěd the hyperboloid does the work of silhouette, wind resistance and antenna mast at once. The International Union of Architects gave him its Auguste Perret Prize in 1969, the first to a Czechoslovak architect. Normalisation broke SIAL up in 1971 and much of his later output was housing and civic work in North Bohemia. In 2000 Czech architects voted Ještěd the country\'s finest twentieth-century building.',
      es: 'Hubáček desarrolló su vida profesional en Liberec y no en Praga, y en 1968 convirtió la oficina estatal de proyectos que dirigía en SIAL, durante un breve tiempo uno de los escasos estudios de arquitectura semiindependientes de Checoslovaquia. Trabajaba partiendo de la ingeniería. Su método consistía en hallar una idea estructural lo bastante precisa para que de ella se dedujeran la planta, el perfil y el revestimiento, y en obligar después al cliente a mantenerla: en el Ještěd, el hiperboloide resuelve a la vez la silueta, la resistencia al viento y el mástil de antena. La Unión Internacional de Arquitectos le concedió el Premio Auguste Perret en 1969, el primero a un arquitecto checoslovaco. La normalización disolvió SIAL en 1971. En 2000, los arquitectos checos votaron el Ještěd como la mejor obra checa del siglo XX.',
      it: 'Hubáček trascorse la vita professionale a Liberec e non a Praga, e nel 1968 trasformò l\'ufficio statale di progettazione che dirigeva in SIAL, per breve tempo uno dei pochi studi di architettura semi-indipendenti della Cecoslovacchia. Lavorava partendo dall\'ingegneria. Il suo metodo consisteva nel trovare un\'idea strutturale abbastanza precisa perché da essa discendessero pianta, profilo e rivestimento, e nel tenervi poi fermo il committente: allo Ještěd l\'iperboloide risolve insieme la sagoma, la resistenza al vento e l\'albero d\'antenna. L\'Unione Internazionale degli Architetti gli assegnò il Premio Auguste Perret nel 1969, il primo a un architetto cecoslovacco. La normalizzazione sciolse SIAL nel 1971. Nel 2000 gli architetti cechi votarono lo Ještěd come la migliore opera ceca del Novecento.',
    },
    awards: ['Auguste Perret Prize, International Union of Architects (1969)'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q699642', title: 'Karel Hubáček (Q699642)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Karel_Hub%C3%A1%C4%8Dek', title: 'Karel Hubáček', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'ivanka-raspopovic',
    wikidataId: 'Q3156244',
    name: 'Ivanka Raspopović',
    alternativeNames: ['Иванка Распоповић'],
    gender: 'woman',
    born: 1930,
    died: 2015,
    floruit: { start: 1955, end: 1976, override: false },
    movements: [{ id: 'international-style', primary: true }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'cultural',
    signatureMaterial: 'concrete',
    portrait: {
      en: 'Raspopović graduated in Belgrade and spent her first decade inside the Yugoslav state design enterprises, where the work was industrial and unglamorous: a textile mill at Loznica, factory complexes at Jagodina, a cold store near Tetovo, a tuberculosis hospital at Prizren, the second phase of Belgrade airport, transmitter stations at Zlatibor. That grounding in production buildings shows in the two works that made her name. From 1960 she partnered Ivan Antić on the Museum of Contemporary Art in New Belgrade and the 21 October Museum at Kragujevac, both built from a repeated geometric cell — a faceted crystal in Belgrade, a cluster of cubes in Kragujevac — resolved with the flat efficiency of a factory shed. The partnership was short and produced nothing else. She was still consulting on the museum\'s restoration in her eighties.',
      es: 'Raspopović se licenció en Belgrado y pasó su primera década en las empresas estatales yugoslavas de proyectos, donde el trabajo era industrial y poco lucido: una fábrica textil en Loznica, complejos fabriles en Jagodina, una cámara frigorífica cerca de Tetovo, un hospital antituberculoso en Prizren, la segunda fase del aeropuerto de Belgrado, estaciones repetidoras en Zlatibor. Esa formación en edificios de producción se advierte en las dos obras que la hicieron conocida. Desde 1960 se asoció con Ivan Antić en el Museo de Arte Contemporáneo de Nuevo Belgrado y en el Museo del 21 de Octubre de Kragujevac, ambos construidos a partir de una célula geométrica repetida —un cristal facetado en Belgrado, un racimo de cubos en Kragujevac— resuelta con la eficacia plana de una nave industrial. La sociedad fue breve y no produjo nada más.',
      it: 'Raspopović si laureò a Belgrado e passò il primo decennio nelle imprese statali jugoslave di progettazione, dove il lavoro era industriale e poco appariscente: un cotonificio a Loznica, complessi di fabbriche a Jagodina, una cella frigorifera presso Tetovo, un ospedale per tubercolotici a Prizren, la seconda fase dell\'aeroporto di Belgrado, stazioni ripetitrici a Zlatibor. Quella formazione su edifici produttivi si vede nelle due opere che la resero nota. Dal 1960 si associò a Ivan Antić per il Museo d\'arte contemporanea di Nuova Belgrado e per il Museo del 21 ottobre a Kragujevac, entrambi costruiti a partire da una cellula geometrica ripetuta — un cristallo sfaccettato a Belgrado, un grappolo di cubi a Kragujevac — risolta con l\'efficienza piana di un capannone. Il sodalizio fu breve e non produsse altro.',
    },
    awards: ['October Prize of the City of Belgrade (1965, with Ivan Antić)'],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q3156244', title: 'Ivanka Raspopović (Q3156244)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Ivanka_Raspopovi%C4%87', title: 'Ivanka Raspopović', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Museum_of_Contemporary_Art,_Belgrade', title: 'Museum of Contemporary Art, Belgrade', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    // Co-architect of the Museum of Contemporary Art, Belgrade (see coArchitects
    // on that building). Wikipedia and the museum's own record name Antić
    // first in the conventional credit; he is defined here in full — not left
    // as a bare id — precisely so that crediting him does not erase Raspopović
    // (architectId stays hers) while still naming her equal partner honestly.
    id: 'ivan-antic',
    wikidataId: 'Q3156060',
    name: 'Ivan Antić',
    alternativeNames: ['Иван Антић'],
    gender: 'man',
    born: 1923,
    died: 2005,
    floruit: { start: 1957, end: 1965, override: true },
    movements: [{ id: 'brutalism', primary: true }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'cultural',
    signatureMaterial: 'concrete',
    portrait: {
      en: 'Antić graduated from the Belgrade faculty of architecture in 1950, after years split between study and a post at the Ministry of Transportation, and worked at the state Jugoprojekt office until 1953 before starting independent practice in 1957. His reputation rests chiefly on a partnership with Ivanka Raspopović, with whom he designed the Museum of Contemporary Art in New Belgrade and, in the same years, the 21 October Museum at the Šumarice memorial park in Kragujevac — both built from repeated geometric cells resolved with an engineer\'s plainness rather than a monument\'s rhetoric. He later taught at the Belgrade faculty, becoming a full professor in 1973, and was elected to the Serbian Academy of Sciences and Arts, first as a corresponding member in 1976 and a full member in 1983.',
      es: 'Antić se licenció en la facultad de arquitectura de Belgrado en 1950, tras años repartidos entre el estudio y un puesto en el Ministerio de Transporte, y trabajó en la oficina estatal Jugoprojekt hasta 1953 antes de iniciar el ejercicio independiente en 1957. Su reputación descansa sobre todo en una sociedad con Ivanka Raspopović, con quien proyectó el Museo de Arte Contemporáneo de Nuevo Belgrado y, en los mismos años, el Museo del 21 de Octubre en el parque conmemorativo de Šumarice, en Kragujevac —ambos construidos a partir de células geométricas repetidas y resueltos con la sobriedad de un ingeniero antes que con la retórica de un monumento. Enseñó después en la facultad de Belgrado, llegando a catedrático en 1973, y fue elegido para la Academia Serbia de Ciencias y Artes, primero como miembro correspondiente en 1976 y como miembro de número en 1983.',
      it: 'Antić si laureò alla facoltà di architettura di Belgrado nel 1950, dopo anni divisi fra lo studio e un incarico al Ministero dei Trasporti, e lavorò presso l\'ufficio statale Jugoprojekt fino al 1953 prima di avviare la pratica indipendente nel 1957. La sua fama poggia soprattutto su un sodalizio con Ivanka Raspopović, con cui progettò il Museo d\'arte contemporanea di Nuova Belgrado e, negli stessi anni, il Museo del 21 ottobre nel parco commemorativo di Šumarice, a Kragujevac — entrambi costruiti a partire da cellule geometriche ripetute e risolti con la sobrietà di un ingegnere piuttosto che con la retorica di un monumento. Insegnò poi alla facoltà di Belgrado, diventando professore ordinario nel 1973, e fu eletto all\'Accademia serba delle scienze e delle arti, dapprima come membro corrispondente nel 1976 e poi come membro effettivo nel 1983.',
    },
    awards: ['October Prize of the City of Belgrade (1965, with Ivanka Raspopović)'],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q3156060', title: 'Ivan Antić (Q3156060)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Ivan_Anti%C4%87', title: 'Ivan Antić', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://sr.wikipedia.org/wiki/%D0%98%D0%B2%D0%B0%D0%BD_%D0%90%D0%BD%D1%82%D0%B8%D1%9B', title: 'Иван Антић (Serbian Wikipedia)', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'jadwiga-grabowska-hawrylak',
    wikidataId: 'Q1515676',
    name: 'Jadwiga Grabowska-Hawrylak',
    alternativeNames: [],
    gender: 'woman',
    born: 1920,
    died: 2018,
    floruit: { start: 1954, end: 1993, override: false },
    movements: [{ id: 'brutalism', primary: true }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'housing',
    signatureMaterial: 'concrete',
    portrait: {
      en: 'Grabowska-Hawrylak arrived in Wrocław in 1945, a year after Breslau had been fought over street by street, and graduated from the local technical university in 1950. Her first job was reconstructing burgher houses on the market square; she then joined Miastoprojekt, the state design office, and stayed for a working life spent on housing and schools. She is remembered for a reputation she never sought. The Plac Grunwaldzki estate was drawn as white towers with planting spilling from rounded balcony frames, a Mediterranean idea for a grey city; the budget was cut, the concrete went up unpainted, and the result was catalogued as brutalism. She kept designing until 1993 and lived long enough to see the estate repainted white in 2015, close to what she had drawn.',
      es: 'Grabowska-Hawrylak llegó a Breslavia en 1945, un año después de que la ciudad hubiera sido disputada calle por calle, y se tituló en la politécnica local en 1950. Su primer encargo fue la reconstrucción de casas burguesas de la plaza mayor; entró después en Miastoprojekt, la oficina estatal de proyectos, y allí pasó una vida profesional dedicada a la vivienda y a las escuelas. Se la recuerda por una fama que nunca buscó. El conjunto de la plaza Grunwaldzki se dibujó como torres blancas con vegetación desbordando marcos redondeados de balcón, una idea mediterránea para una ciudad gris; se recortó el presupuesto, el hormigón se levantó sin pintar y el resultado quedó catalogado como brutalismo. Siguió proyectando hasta 1993 y vivió lo bastante para ver el conjunto pintado de blanco en 2015.',
      it: 'Grabowska-Hawrylak arrivò a Breslavia nel 1945, un anno dopo che la città era stata contesa strada per strada, e si laureò al politecnico locale nel 1950. Il primo incarico fu la ricostruzione di case borghesi sulla piazza del mercato; entrò poi in Miastoprojekt, l\'ufficio statale di progettazione, e vi trascorse una vita professionale dedicata all\'edilizia residenziale e alle scuole. È ricordata per una fama che non aveva cercato. Il complesso di piazza Grunwaldzki fu disegnato come torri bianche con vegetazione debordante da cornici arrotondate di balcone, un\'idea mediterranea per una città grigia; il bilancio fu tagliato, il calcestruzzo restò senza pittura e il risultato venne catalogato come brutalismo. Continuò a progettare fino al 1993 e visse abbastanza per vedere il complesso ridipinto di bianco nel 2015.',
    },
    awards: ['SARP Honorary Award', 'Commander\'s Cross of the Order of Polonia Restituta'],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q1515676', title: 'Jadwiga Grabowska-Hawrylak (Q1515676)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Jadwiga_Grabowska-Hawrylak', title: 'Jadwiga Grabowska-Hawrylak', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'halina-skibniewska',
    wikidataId: 'Q1571180',
    name: 'Halina Skibniewska',
    alternativeNames: ['Halina Erentz'],
    gender: 'woman',
    born: 1921,
    died: 2011,
    floruit: { start: 1951, end: 1985, override: false },
    movements: [
      { id: 'functionalism', primary: true },
      { id: 'international-style', primary: false },
    ],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'housing',
    signatureMaterial: 'brick',
    portrait: {
      en: 'Skibniewska spent the German occupation of Warsaw in the resistance and in Żegota, the underground council for aid to Jews, then studied under Romuald Gutt and graduated in 1948 into the Warsaw Reconstruction Office. From 1957 she worked for the Warsaw Housing Cooperative, heir to the interwar functionalist estates of Żoliborz, and made her career there rather than in monumental commissions. Her preoccupations were unfashionable and durable: keeping the trees that were already on a site, giving flats an unbraced interior that tenants could rearrange, and designing dwellings usable by disabled and elderly people — the first Polish architect to do so systematically. She taught at Warsaw University of Technology from 1975 and sat in the Sejm from 1965 to 1985, from 1971 as its first woman deputy marshal.',
      es: 'Skibniewska pasó la ocupación alemana de Varsovia en la resistencia y en Żegota, el consejo clandestino de ayuda a los judíos; estudió después con Romuald Gutt y se tituló en 1948 para incorporarse a la Oficina de Reconstrucción de la Capital. Desde 1957 trabajó en la Cooperativa de Vivienda de Varsovia, heredera de las colonias funcionalistas de entreguerras de Żoliborz, y allí hizo su carrera, no en encargos monumentales. Sus preocupaciones eran poco lucidas y duraderas: conservar los árboles que ya existían en el solar, dar a los pisos un interior sin muros de carga que los vecinos pudieran reordenar y proyectar viviendas utilizables por personas mayores y con discapacidad, la primera arquitecta polaca en hacerlo de forma sistemática. Enseñó en la Politécnica de Varsovia desde 1975 y fue diputada entre 1965 y 1985.',
      it: 'Skibniewska trascorse l\'occupazione tedesca di Varsavia nella resistenza e in Żegota, il consiglio clandestino di aiuto agli ebrei; studiò poi con Romuald Gutt e si laureò nel 1948 entrando nell\'Ufficio per la Ricostruzione della Capitale. Dal 1957 lavorò per la Cooperativa edilizia di Varsavia, erede delle colonie funzionaliste fra le due guerre di Żoliborz, e lì fece carriera, non in incarichi monumentali. I suoi interessi erano poco appariscenti e duraturi: conservare gli alberi già presenti sul lotto, dare agli alloggi un interno privo di muri portanti che gli inquilini potessero riorganizzare, progettare abitazioni utilizzabili da anziani e persone con disabilità — prima architetta polacca a farlo sistematicamente. Insegnò al Politecnico di Varsavia dal 1975 e sedette nel Sejm dal 1965 al 1985.',
    },
    awards: ['SARP Honorary Award', 'Lenin Peace Prize', 'Commander\'s Cross of the Order of Polonia Restituta'],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q1571180', title: 'Halina Skibniewska (Q1571180)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Halina_Skibniewska', title: 'Halina Skibniewska', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://pl.wikipedia.org/wiki/Halina_Skibniewska', title: 'Halina Skibniewska (Polish Wikipedia)', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'janko-konstantinov',
    wikidataId: 'Q3083426',
    name: 'Janko Konstantinov',
    alternativeNames: ['Јанко Константинов'],
    gender: 'man',
    born: 1926,
    died: 2010,
    floruit: { start: 1965, end: 1989, override: false },
    movements: [{ id: 'brutalism', primary: true }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'civic',
    signatureMaterial: 'concrete',
    portrait: {
      en: 'Konstantinov was born in Bitola, graduated from the Belgrade faculty of architecture in 1952, then went abroad for a decade — a specialisation at the Royal Danish Academy in Copenhagen, a period in Finland working with Alvar Aalto, and from 1958 six years in the United States, much of it in Victor Gruen\'s office in Los Angeles. The earthquake that levelled central Skopje in July 1963 brought him home. He stayed for the rebuilding and produced the works he is known for: the Post Office and the Telecommunications Centre, raised in stages between the late 1960s and 1989, in which cylindrical concrete drums, ribbed shafts and circular openings are assembled into something closer to sculpture than to a service building. He painted watercolours throughout, and gave over a hundred of them to the museum at Bitola in 2009.',
      es: 'Konstantinov nació en Bitola, se licenció en la facultad de arquitectura de Belgrado en 1952 y pasó luego una década fuera: una especialización en la Real Academia Danesa de Copenhague, una temporada en Finlandia junto a Alvar Aalto y, desde 1958, seis años en Estados Unidos, buena parte de ellos en el estudio de Victor Gruen en Los Ángeles. El terremoto que arrasó el centro de Skopie en julio de 1963 lo hizo volver. Se quedó para la reconstrucción y produjo las obras por las que se le conoce: la Oficina Central de Correos y el Centro de Telecomunicaciones, levantados por fases entre finales de los años sesenta y 1989, donde tambores cilíndricos de hormigón, fustes acanalados y huecos circulares se ensamblan en algo más cercano a la escultura que a un edificio de servicio.',
      it: 'Konstantinov nacque a Bitola, si laureò alla facoltà di architettura di Belgrado nel 1952 e trascorse poi un decennio all\'estero: una specializzazione alla Reale Accademia Danese di Copenaghen, un periodo in Finlandia accanto ad Alvar Aalto e, dal 1958, sei anni negli Stati Uniti, in gran parte nello studio di Victor Gruen a Los Angeles. Il terremoto che rase al suolo il centro di Skopje nel luglio 1963 lo fece tornare. Rimase per la ricostruzione e produsse le opere per cui è noto: l\'Ufficio postale centrale e il Centro delle telecomunicazioni, eretti per fasi fra la fine degli anni Sessanta e il 1989, dove tamburi cilindrici in calcestruzzo, fusti scanalati e aperture circolari si compongono in qualcosa di più vicino alla scultura che a un edificio di servizio.',
    },
    awards: [],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q3083426', title: 'Janko Konstantinov (Q3083426)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Janko_Konstantinov', title: 'Janko Konstantinov', license: 'CC BY-SA 4.0' },
      { kind: 'institution', url: 'https://www.moma.org/artists/49951-janko-konstantinov', title: 'Janko Konstantinov — MoMA', license: null },
    ],
  },
  {
    id: 'igor-franic',
    wikidataId: 'Q100502858',
    name: 'Igor Franić',
    alternativeNames: [],
    gender: 'man',
    born: 1963,
    died: null,
    floruit: { start: 2003, end: 2020, override: false },
    movements: 'unaffiliated',
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'cultural',
    signatureMaterial: 'steel-and-glass',
    portrait: {
      en: 'Franić was born in Zagreb, studied and now teaches at the city\'s faculty of architecture, and belongs to the generation of Croatian architects whose careers began in the wake of the war of the early 1990s, when public commissions restarted after a decade of almost none. His reputation rests on one building. In 1998 the City of Zagreb and the Ministry of Culture decided to move the Museum of Contemporary Art out of a cramped palace in the upper town into a purpose-built home in Novi Zagreb; Franić\'s entry won a competition of eighty-five submissions. He worked on it for eleven years through repeated delays and a budget that more than doubled. He also designed the Kocka mora monument at Dubrovnik, erected in 2007 and removed in 2020, and holds the Viktor Kovačić Award.',
      es: 'Franić nació en Zagreb, estudió y hoy enseña en la facultad de arquitectura de la ciudad, y pertenece a la generación de arquitectos croatas cuya carrera comenzó a la salida de la guerra de principios de los noventa, cuando el encargo público se reanudó tras una década casi vacía. Su reputación descansa en un solo edificio. En 1998 la ciudad de Zagreb y el Ministerio de Cultura decidieron trasladar el Museo de Arte Contemporáneo desde un palacio angosto de la ciudad alta a una sede de nueva planta en Novi Zagreb; la propuesta de Franić se impuso en un concurso de ochenta y cinco participantes. Trabajó en ella once años, entre retrasos sucesivos y un presupuesto que más que se duplicó. Ha recibido el Premio Viktor Kovačić.',
      it: 'Franić è nato a Zagabria, ha studiato e oggi insegna alla facoltà di architettura della città, e appartiene alla generazione di architetti croati la cui carriera è iniziata all\'uscita dalla guerra dei primi anni Novanta, quando la committenza pubblica riprese dopo un decennio quasi vuoto. La sua reputazione si regge su un solo edificio. Nel 1998 la città di Zagabria e il Ministero della Cultura decisero di trasferire il Museo d\'arte contemporanea da un angusto palazzo della città alta a una sede di nuova costruzione a Novi Zagreb; la proposta di Franić si impose in un concorso con ottantacinque partecipanti. Vi lavorò undici anni, fra rinvii successivi e un bilancio più che raddoppiato. Ha ricevuto il Premio Viktor Kovačić.',
    },
    awards: ['Viktor Kovačić Award'],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q100502858', title: 'Igor Franić (Q100502858)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Igor_Frani%C4%87', title: 'Igor Franić', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'eva-jiricna',
    wikidataId: 'Q2589897',
    name: 'Eva Jiřičná',
    alternativeNames: ['Eva Jiricna'],
    gender: 'woman',
    born: 1939,
    died: null,
    floruit: { start: 1985, end: 2020, override: false },
    movements: [{ id: 'high-tech', primary: true }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'commercial',
    signatureMaterial: 'steel-and-glass',
    portrait: {
      en: 'Jiřičná was born in Zlín twelve days before the German occupation of Bohemia and Moravia, studied architecture in Prague, and went to London in 1968 on a temporary placement with the Greater London Council. The Warsaw Pact invasion that August cancelled her travel permit and she stayed, spending eight years on Brighton Marina before opening her own practice around 1980. The work that made her name was small and exacting — shops for Joseph, interiors, and above all staircases in glass and stainless steel, detailed to the bolt. She returned to Czech practice after 1989, heading the architecture department at Prague\'s applied arts academy from 1996 and co-founding AI Design there in 1999, through which most of her later Czech buildings, including the Zlín congress and university centre, were delivered.',
      es: 'Jiřičná nació en Zlín doce días antes de la ocupación alemana de Bohemia y Moravia, estudió arquitectura en Praga y viajó a Londres en 1968 con un contrato temporal en el Greater London Council. La invasión del Pacto de Varsovia de aquel agosto anuló su permiso de viaje y se quedó; dedicó ocho años al puerto deportivo de Brighton antes de abrir estudio propio hacia 1980. La obra que la hizo conocida fue pequeña y exigente: tiendas para Joseph, interiores y, sobre todo, escaleras de vidrio y acero inoxidable detalladas hasta el perno. Volvió a ejercer en Chequia tras 1989, dirigiendo desde 1996 el departamento de arquitectura de la academia de artes aplicadas de Praga y cofundando allí AI Design en 1999, estudio a través del cual se construyeron sus obras checas posteriores.',
      it: 'Jiřičná nacque a Zlín dodici giorni prima dell\'occupazione tedesca di Boemia e Moravia, studiò architettura a Praga e andò a Londra nel 1968 con un incarico temporaneo al Greater London Council. L\'invasione del Patto di Varsavia di quell\'agosto le annullò il permesso di viaggio e rimase; dedicò otto anni al porto turistico di Brighton prima di aprire uno studio proprio intorno al 1980. Il lavoro che la rese nota fu minuto ed esigente: negozi per Joseph, interni e soprattutto scale in vetro e acciaio inossidabile, dettagliate fino al bullone. Tornò a esercitare in Cechia dopo il 1989, dirigendo dal 1996 il dipartimento di architettura dell\'accademia di arti applicate di Praga e cofondandovi nel 1999 AI Design, studio attraverso cui furono realizzate le sue opere ceche successive.',
    },
    awards: ['Jane Drew Prize', 'Royal Designer for Industry', 'Commander of the Order of the British Empire'],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q2589897', title: 'Eva Jiřičná (Q2589897)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Eva_Ji%C5%99i%C4%8Dn%C3%A1', title: 'Eva Jiřičná', license: 'CC BY-SA 4.0' },
    ],
  },
];
