import type { Architect } from '@/types/architect';

// Wave 5 curator agent (France, Belgium, Netherlands, Luxembourg, Monaco): real, sourced Architect entries for this slice.
//
// `workRegions` and `workCentroid` are deliberately left at [] / {0,0}: the
// curation script derives both from each architect's buildings and overwrites
// whatever is written here.
export const EUROPE_WEST_ARCHITECTS: Architect[] = [
  {
    id: 'claude-nicolas-ledoux',
    wikidataId: 'Q552700',
    name: 'Claude-Nicolas Ledoux',
    alternativeNames: ['Claude Nicolas Ledoux'],
    gender: 'man',
    born: 1736,
    died: 1806,
    floruit: { start: 1766, end: 1789, override: false },
    movements: [{ id: 'neoclassicism', primary: true }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'civic',
    signatureMaterial: 'stone',
    portrait: {
      en: 'Ledoux trained under Jacques-François Blondel and built his career on royal and speculative commissions in Paris and the Franche-Comté. His architecture strips classical language back to elementary solids — cylinders, cubes, pediments carried on unfluted banded columns — and then loads those solids with programme: a saltworks laid out as a half-circle of supervision, toll gates ringing Paris like propylaea, a theatre at Besançon whose stepped auditorium did away with the boxes of privilege. Imprisoned during the Terror as an architect of the hated tax farm, he spent his last years elaborating an unbuilt ideal city at Chaux, published as engravings in 1804. Nineteenth-century critics read those plates as megalomania; twentieth-century ones read them as the beginning of modern architecture. Both were looking at the same drawings.',
      es: 'Ledoux se formó con Jacques-François Blondel y levantó su carrera sobre encargos reales y especulativos en París y el Franco Condado. Su arquitectura reduce el lenguaje clásico a sólidos elementales —cilindros, cubos, frontones sostenidos por columnas anilladas sin estrías— y carga esos sólidos de programa: una salina dispuesta como un semicírculo de vigilancia, barreras de arbitrios que rodean París como propileos, un teatro en Besançon cuyo graderío escalonado suprimió los palcos del privilegio. Encarcelado durante el Terror por su vinculación con los odiados arrendatarios de impuestos, dedicó sus últimos años a la ciudad ideal nunca construida de Chaux, publicada en grabados en 1804. La crítica del siglo XIX vio en esas láminas pura megalomanía; la del XX, el arranque de la arquitectura moderna. Ambas miraban los mismos dibujos.',
      it: 'Ledoux si formò con Jacques-François Blondel e costruì la propria carriera su commesse regie e speculative fra Parigi e la Franca Contea. La sua architettura riduce il linguaggio classico a solidi elementari — cilindri, cubi, frontoni retti da colonne bugnate e prive di scanalature — e carica poi quei solidi di programma: una salina disposta come un semicerchio di sorveglianza, barriere daziarie che cingono Parigi come propilei, un teatro a Besançon la cui gradinata continua abolì i palchi del privilegio. Incarcerato durante il Terrore in quanto architetto dell\'odiata appaltatura fiscale, passò gli ultimi anni a elaborare la città ideale mai costruita di Chaux, pubblicata in incisioni nel 1804. La critica ottocentesca lesse quelle tavole come megalomania, quella novecentesca come l\'inizio dell\'architettura moderna. Guardavano gli stessi disegni.',
    },
    awards: [],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q552700', title: 'Claude Nicolas Ledoux (Q552700)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Claude_Nicolas_Ledoux', title: 'Claude Nicolas Ledoux', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'louis-le-vau',
    wikidataId: 'Q310530',
    name: 'Louis Le Vau',
    alternativeNames: ['Louis Levau'],
    gender: 'man',
    born: 1613,
    died: 1670,
    floruit: { start: 1642, end: 1670, override: false },
    movements: [{ id: 'baroque', primary: true }, { id: 'renaissance', primary: false }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'domestic',
    signatureMaterial: 'stone',
    portrait: {
      en: 'Le Vau came out of a Paris family of master masons and made his name on the Île Saint-Louis, building hôtels for financiers before Nicolas Fouquet handed him Vaux-le-Vicomte. There he assembled the team — Charles Le Brun for the painted interiors, André Le Nôtre for the garden — that Louis XIV would take over intact after Fouquet\'s fall. Appointed Premier architecte du roi in 1654, he rebuilt the court of the Louvre, raised the domed Collège des Quatre-Nations on the opposite bank of the Seine, and wrapped Versailles in the stone envelope that turned a hunting lodge into a palace. His plans push oval and domed salons straight through the depth of the block, so that the centre of a building swells outward and can be read from the garden in a single glance.',
      es: 'Le Vau procedía de una familia parisina de maestros albañiles y se dio a conocer en la Isla de San Luis, construyendo hôtels para financieros antes de que Nicolas Fouquet le encargara Vaux-le-Vicomte. Allí reunió al equipo —Charles Le Brun para los interiores pintados, André Le Nôtre para el jardín— que Luis XIV heredaría entero tras la caída de Fouquet. Nombrado Premier architecte du roi en 1654, rehízo el patio del Louvre, levantó el Collège des Quatre-Nations con su cúpula en la orilla opuesta del Sena y envolvió Versalles en la envoltura de piedra que convirtió un pabellón de caza en palacio. Sus plantas atraviesan el fondo del edificio con salones ovales y abovedados, de modo que el centro se hincha hacia fuera y se lee desde el jardín de una sola mirada.',
      it: 'Le Vau proveniva da una famiglia parigina di capomastri e si fece un nome sull\'Île Saint-Louis, costruendo hôtels per finanzieri prima che Nicolas Fouquet gli affidasse Vaux-le-Vicomte. Lì mise insieme la squadra — Charles Le Brun per gli interni dipinti, André Le Nôtre per il giardino — che Luigi XIV avrebbe rilevato intatta dopo la caduta di Fouquet. Nominato Premier architecte du roi nel 1654, rifece la corte del Louvre, innalzò il cupolato Collège des Quatre-Nations sulla riva opposta della Senna e avvolse Versailles nell\'involucro di pietra che trasformò un padiglione di caccia in reggia. Le sue piante attraversano lo spessore del corpo di fabbrica con saloni ovali e cupolati, così che il centro dell\'edificio si gonfia verso l\'esterno e si legge dal giardino in un solo colpo d\'occhio.',
    },
    awards: [],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q310530', title: 'Louis Le Vau (Q310530)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Louis_Le_Vau', title: 'Louis Le Vau', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'victor-horta',
    wikidataId: 'Q49744',
    name: 'Victor Horta',
    alternativeNames: ['Victor Pierre Horta', 'Baron Horta'],
    gender: 'man',
    born: 1861,
    died: 1947,
    floruit: { start: 1890, end: 1939, override: false },
    movements: [{ id: 'art-nouveau', primary: true }, { id: 'art-deco', primary: false }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'domestic',
    signatureMaterial: 'steel-and-glass',
    portrait: {
      en: 'Horta studied in Ghent and Paris before entering the office of Alphonse Balat, the classicist who built the royal glasshouses at Laeken — an apprenticeship in iron and glass that underwrites everything he did later. From 1892 he produced a run of Brussels town houses for liberal, freemason and scientific clients in which the plan is organised around a top-lit stair hall and exposed iron columns branch into painted tendrils. He carried the same language into the Maison du Peuple for the Belgian Workers\' Party and into department stores, then turned severe after 1918: the Centre for Fine Arts and Brussels Central Station are stripped and classical. He directed the Académie royale des Beaux-Arts, was made a baron in 1932, and lived long enough to watch his Art Nouveau go out of fashion.',
      es: 'Horta estudió en Gante y en París antes de entrar en el estudio de Alphonse Balat, el clasicista que construyó los invernaderos reales de Laeken: un aprendizaje en hierro y vidrio que sostiene todo lo que hizo después. Desde 1892 encadenó una serie de casas burguesas en Bruselas para clientes liberales, masones y científicos, en las que la planta se organiza en torno a una caja de escalera cenital y las columnas de hierro vistas se ramifican en zarcillos pintados. Llevó ese mismo lenguaje a la Maison du Peuple del Partido Obrero Belga y a los grandes almacenes, y después de 1918 se volvió severo: el Palacio de Bellas Artes y la Estación Central de Bruselas son desnudos y clásicos. Dirigió la Académie royale des Beaux-Arts, fue nombrado barón en 1932 y vivió lo bastante para ver pasar de moda su Art Nouveau.',
      it: 'Horta studiò a Gand e a Parigi prima di entrare nello studio di Alphonse Balat, il classicista autore delle serre reali di Laeken: un tirocinio in ferro e vetro che regge tutto ciò che fece in seguito. Dal 1892 produsse una serie di case borghesi a Bruxelles per committenti liberali, massoni e scienziati, in cui la pianta si organizza attorno a un vano scala illuminato dall\'alto e le colonne di ferro a vista si ramificano in viticci dipinti. Portò lo stesso linguaggio nella Maison du Peuple del Partito Operaio Belga e nei grandi magazzini, poi dopo il 1918 si fece severo: il Palazzo delle Belle Arti e la Stazione Centrale di Bruxelles sono spogli e classici. Diresse l\'Académie royale des Beaux-Arts, fu creato barone nel 1932 e visse abbastanza da vedere il proprio Art Nouveau passare di moda.',
    },
    awards: ['Officer of the Order of the Crown (Belgium)', 'Baron (Belgian nobility, 1932)'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q49744', title: 'Victor Horta (Q49744)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Victor_Horta', title: 'Victor Horta', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'gerrit-rietveld',
    wikidataId: 'Q160435',
    name: 'Gerrit Rietveld',
    alternativeNames: ['Gerrit Thomas Rietveld'],
    gender: 'man',
    born: 1888,
    died: 1964,
    floruit: { start: 1924, end: 1964, override: false },
    movements: [{ id: 'de-stijl', primary: true }, { id: 'functionalism', primary: false }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'domestic',
    signatureMaterial: 'timber',
    portrait: {
      en: 'Rietveld learned his trade in his father\'s Utrecht joinery and was still a cabinetmaker when he made the Red and Blue Chair around 1918 — a frame of standard laths in which no member is cut short by another. Joining De Stijl in 1919, he transferred that logic to building: planes and bars that slide past one another instead of meeting in a settled corner. After the Schröder House he spent decades on prefabricated terraces, cheap core dwellings and factory work, chasing serial construction rather than the single art object. Late commissions included the Dutch pavilion in Venice, the sculpture pavilion at Sonsbeek and the Van Gogh Museum, completed by his partners after his death. He taught, argued for standardisation, and never entirely stopped being a joiner.',
      es: 'Rietveld aprendió el oficio en la ebanistería de su padre en Utrecht y todavía era ebanista cuando hizo, hacia 1918, la silla Roja y Azul: una estructura de listones normalizados en la que ninguna pieza interrumpe a otra. Al incorporarse a De Stijl en 1919 trasladó esa lógica a la arquitectura: planos y barras que se deslizan unos junto a otros en vez de encontrarse en una esquina cerrada. Después de la casa Schröder dedicó décadas a hileras prefabricadas, viviendas mínimas y encargos industriales, persiguiendo la construcción en serie más que la pieza única. Entre sus obras tardías están el pabellón neerlandés de Venecia, el pabellón de escultura de Sonsbeek y el Museo Van Gogh, terminado por sus socios tras su muerte. Enseñó, defendió la normalización y nunca dejó del todo de ser carpintero.',
      it: 'Rietveld imparò il mestiere nella falegnameria paterna a Utrecht ed era ancora ebanista quando realizzò, verso il 1918, la sedia Rossa e Blu: un telaio di listelli normalizzati in cui nessun elemento viene interrotto da un altro. Entrato in De Stijl nel 1919, trasferì quella logica all\'edificio: piani e aste che scorrono l\'uno accanto all\'altro invece di incontrarsi in uno spigolo concluso. Dopo la casa Schröder passò decenni su schiere prefabbricate, alloggi minimi e commesse industriali, inseguendo la costruzione in serie più che il pezzo unico. Fra le opere tarde figurano il padiglione olandese a Venezia, il padiglione della scultura a Sonsbeek e il Van Gogh Museum, completato dai suoi soci dopo la sua morte. Insegnò, difese la standardizzazione e non smise mai del tutto di essere un falegname.',
    },
    awards: ['Sikkens Prize', 'Officer of the Order of Orange-Nassau', 'Honorary Medal of the City of Utrecht (1948)'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q160435', title: 'Gerrit Rietveld (Q160435)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Gerrit_Rietveld', title: 'Gerrit Rietveld', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'leendert-van-der-vlugt',
    wikidataId: 'Q1812135',
    name: 'Leendert van der Vlugt',
    alternativeNames: ['Leendert Cornelis van der Vlugt', 'Brinkman & Van der Vlugt'],
    gender: 'man',
    born: 1894,
    died: 1936,
    floruit: { start: 1925, end: 1936, override: false },
    movements: [{ id: 'functionalism', primary: true }, { id: 'international-style', primary: false }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'industrial',
    signatureMaterial: 'steel-and-glass',
    portrait: {
      en: 'Van der Vlugt trained in Rotterdam and taught in Groningen before joining Michiel Brinkman\'s practice in 1925; Brinkman died that year and Van der Vlugt inherited both the office and its largest commission. Working with the reinforced-concrete engineer Jan Gerko Wiebenga and, briefly, with the draughtsman Mart Stam, he produced the Van Nelle Factory, the Bergpolder slab block and a pair of glass villas for the Van Nelle directors. His buildings set mushroom-headed concrete columns behind a glass skin hung clear of the frame, so that floors read from outside as continuous horizontal bands and the structure never touches the facade. He died at forty-two. Authorship of the factory was disputed for decades afterwards, and Stam left the office over it.',
      es: 'Van der Vlugt se formó en Róterdam y enseñó en Groninga antes de incorporarse en 1925 al estudio de Michiel Brinkman; Brinkman murió ese mismo año y Van der Vlugt heredó tanto la oficina como su mayor encargo. Con el ingeniero de hormigón armado Jan Gerko Wiebenga y, brevemente, con el delineante Mart Stam, levantó la fábrica Van Nelle, el bloque Bergpolder y un par de villas de vidrio para los directores de Van Nelle. Sus edificios sitúan pilares de hormigón con capitel de seta detrás de una piel de vidrio colgada por delante de la estructura, de modo que los forjados se leen desde fuera como bandas horizontales continuas y la estructura nunca toca la fachada. Murió a los cuarenta y dos años. La autoría de la fábrica se discutió durante décadas, y Stam abandonó el estudio por ello.',
      it: 'Van der Vlugt si formò a Rotterdam e insegnò a Groninga prima di entrare nel 1925 nello studio di Michiel Brinkman; Brinkman morì quello stesso anno e Van der Vlugt ereditò tanto l\'ufficio quanto la sua commessa maggiore. Con l\'ingegnere del cemento armato Jan Gerko Wiebenga e, per un breve periodo, con il disegnatore Mart Stam, realizzò la fabbrica Van Nelle, la stecca Bergpolder e due ville di vetro per i direttori della Van Nelle. I suoi edifici collocano pilastri di calcestruzzo a fungo dietro una pelle di vetro appesa in avanti rispetto al telaio, così che i solai si leggano dall\'esterno come fasce orizzontali continue e la struttura non tocchi mai la facciata. Morì a quarantadue anni. La paternità della fabbrica fu contesa per decenni, e per questo Stam lasciò lo studio.',
    },
    awards: [],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q1812135', title: 'Leendert van der Vlugt (Q1812135)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Van_Nelle_Factory', title: 'Van Nelle Factory', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'johannes-brinkman',
    wikidataId: 'Q962993',
    name: 'Johannes Brinkman',
    alternativeNames: ['Johannes Andreas Brinkman', 'J.A. Brinkman', 'Jan Brinkman', 'Brinkman & Van der Vlugt'],
    gender: 'man',
    born: 1902,
    died: 1949,
    floruit: { start: 1930, end: 1949, override: false },
    movements: [{ id: 'functionalism', primary: true }, { id: 'international-style', primary: false }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'industrial',
    signatureMaterial: 'steel-and-glass',
    portrait: {
      en: 'Brinkman trained as a civil engineer at Delft before entering his father Michiel Brinkman\'s Rotterdam office. When Michiel died in 1925, the twenty-three-year-old Johannes took over the practice and, that same year, formed a partnership with Leendert van der Vlugt — the firm traded as Brinkman & Van der Vlugt until Van der Vlugt\'s death in 1936. Brinkman handled engineering and construction while Van der Vlugt led design on the Van Nelle Factory, the Van der Leeuw and Sonneveld houses, and the Bergpolder flats; historians still debate how credit should divide between the two of them and the draughtsman Mart Stam. After 1936 Brinkman partnered with Johannes van den Broek, completed Feyenoord\'s stadium in 1937, and died in 1949 still working on Rotterdam\'s cruise terminal.',
      es: 'Brinkman se formó como ingeniero civil en Delft antes de incorporarse a la oficina rotterdamesa de su padre, Michiel Brinkman. Cuando Michiel murió en 1925, Johannes, con veintitrés años, asumió el estudio y ese mismo año se asoció con Leendert van der Vlugt; la firma operó como Brinkman & Van der Vlugt hasta la muerte de Van der Vlugt en 1936. Brinkman se ocupaba de la ingeniería y la obra mientras Van der Vlugt dirigía el diseño de la fábrica Van Nelle, las casas Van der Leeuw y Sonneveld y los bloques de Bergpolder; los historiadores aún discuten cómo repartir la autoría entre ambos y el delineante Mart Stam. Tras 1936 Brinkman se asoció con Johannes van den Broek, terminó el estadio del Feyenoord en 1937, y murió en 1949 todavía trabajando en la terminal de cruceros de Róterdam.',
      it: 'Brinkman si formò come ingegnere civile a Delft prima di entrare nello studio rotterdamese del padre, Michiel Brinkman. Quando Michiel morì nel 1925, Johannes, ventitreenne, rilevò lo studio e quello stesso anno si associò con Leendert van der Vlugt; la ditta operò come Brinkman & Van der Vlugt fino alla morte di Van der Vlugt nel 1936. Brinkman curava l\'ingegneria e il cantiere mentre Van der Vlugt guidava il progetto della fabbrica Van Nelle, delle case Van der Leeuw e Sonneveld e delle stecche di Bergpolder; gli storici discutono ancora come dividere il merito fra i due e il disegnatore Mart Stam. Dopo il 1936 Brinkman si associò con Johannes van den Broek, completò lo stadio del Feyenoord nel 1937, e morì nel 1949 mentre lavorava ancora al terminal crociere di Rotterdam.',
    },
    awards: [],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q962993', title: 'Johannes Brinkman (Q962993)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Johannes_Brinkman', title: 'Johannes Brinkman', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'aldo-van-eyck',
    wikidataId: 'Q444571',
    name: 'Aldo van Eyck',
    alternativeNames: [],
    gender: 'man',
    born: 1918,
    died: 1999,
    floruit: { start: 1947, end: 1999, override: false },
    movements: 'unaffiliated',
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'civic',
    signatureMaterial: 'concrete',
    portrait: {
      en: 'Van Eyck sat out the war studying in Zurich, returned to Amsterdam in 1946 and spent the next two decades designing several hundred municipal playgrounds — small, exact interventions in bombed and leftover ground. Through CIAM and then Team 10 he attacked functionalist planning for treating inhabitants as statistics, arguing instead for places and occasions with a clear threshold between them. He edited the magazine Forum with Herman Hertzberger and Jaap Bakema, taught at Delft, and read the ethnography of the Dogon and the Pueblo closely without imitating their forms. His buildings — the Amsterdam orphanage, the Sonsbeek sculpture pavilion, the Hubertus House for single mothers — are assembled from repeated small units gathered around thresholds rather than composed as single objects. He refused every label offered him.',
      es: 'Van Eyck pasó la guerra estudiando en Zúrich, volvió a Ámsterdam en 1946 y dedicó las dos décadas siguientes a proyectar varios centenares de parques infantiles municipales: intervenciones pequeñas y exactas en solares bombardeados y sobrantes. Desde los CIAM y luego desde el Team 10 atacó el urbanismo funcionalista por tratar a los habitantes como estadística, y reclamó en su lugar lugares y ocasiones separados por un umbral nítido. Codirigió la revista Forum con Herman Hertzberger y Jaap Bakema, enseñó en Delft y leyó con atención la etnografía dogón y pueblo sin imitar sus formas. Sus edificios —el orfanato de Ámsterdam, el pabellón de escultura de Sonsbeek, la Casa Hubertus para madres solteras— se montan con unidades pequeñas repetidas y agrupadas en torno a umbrales, no se componen como objetos únicos. Rechazó cuantas etiquetas le ofrecieron.',
      it: 'Van Eyck passò la guerra studiando a Zurigo, tornò ad Amsterdam nel 1946 e dedicò i due decenni successivi a progettare diverse centinaia di parchi gioco comunali: interventi minuti ed esatti su terreni bombardati e di risulta. Attraverso i CIAM e poi il Team 10 attaccò l\'urbanistica funzionalista perché trattava gli abitanti come statistica, rivendicando invece luoghi e occasioni separati da una soglia netta. Diresse con Herman Hertzberger e Jaap Bakema la rivista Forum, insegnò a Delft e lesse con attenzione l\'etnografia dogon e pueblo senza imitarne le forme. I suoi edifici — l\'orfanotrofio di Amsterdam, il padiglione della scultura di Sonsbeek, la Casa Hubertus per madri sole — sono montati con piccole unità ripetute e raccolte attorno a soglie, non composti come oggetti unitari. Rifiutò ogni etichetta che gli venne proposta.',
    },
    awards: ['RIBA Royal Gold Medal', 'Wolf Prize in Architecture', 'Rotterdam-Maaskant Prize', 'Sikkens Prize'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q444571', title: 'Aldo van Eyck (Q444571)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Aldo_van_Eyck', title: 'Aldo van Eyck', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'herman-hertzberger',
    wikidataId: 'Q318319',
    name: 'Herman Hertzberger',
    alternativeNames: [],
    gender: 'man',
    born: 1932,
    died: null,
    floruit: { start: 1966, end: 2020, override: false },
    movements: 'unaffiliated',
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'educational',
    signatureMaterial: 'concrete',
    portrait: {
      en: 'Hertzberger graduated from Delft in 1958 and joined Aldo van Eyck and Jaap Bakema on the editorial board of Forum, the magazine that pulled Dutch architecture away from postwar functionalism. His own work turns those arguments into a method: a neutral structural order of concrete blocks and repeated prefabricated units, deliberately left unfinished, into which the people who use the building are expected to build their own occupation. Offices, Montessori schools, the experimental Diagoon houses and theatres all follow the same rule — the architect supplies the frame and then stops. Critics have called the results graceless; he has answered that legibility and appropriation matter more than facades. He taught at Delft for thirty years and received the RIBA Royal Gold Medal in 2012.',
      es: 'Hertzberger se tituló en Delft en 1958 y entró en el consejo de redacción de Forum junto a Aldo van Eyck y Jaap Bakema, la revista que apartó a la arquitectura neerlandesa del funcionalismo de posguerra. Su propia obra convierte aquellos argumentos en un método: un orden estructural neutro de bloques de hormigón y elementos prefabricados repetidos, dejado adrede sin terminar, para que quienes usan el edificio construyan dentro su propia ocupación. Oficinas, escuelas Montessori, las viviendas experimentales Diagoon y teatros siguen la misma regla: el arquitecto aporta el armazón y se detiene. La crítica ha llamado torpes a los resultados; él ha respondido que importan más la legibilidad y la apropiación que las fachadas. Enseñó treinta años en Delft y recibió la Royal Gold Medal del RIBA en 2012.',
      it: 'Hertzberger si laureò a Delft nel 1958 ed entrò nella redazione di Forum accanto ad Aldo van Eyck e Jaap Bakema, la rivista che allontanò l\'architettura olandese dal funzionalismo del dopoguerra. La sua opera traduce quegli argomenti in un metodo: un ordine strutturale neutro di blocchi di calcestruzzo ed elementi prefabbricati ripetuti, lasciato di proposito incompiuto, perché chi usa l\'edificio vi costruisca dentro la propria occupazione. Uffici, scuole Montessori, le case sperimentali Diagoon e teatri seguono la stessa regola: l\'architetto fornisce il telaio e si ferma. La critica ha definito sgraziati i risultati; lui ha risposto che leggibilità e appropriazione contano più delle facciate. Insegnò trent\'anni a Delft e ricevette la Royal Gold Medal del RIBA nel 2012.',
    },
    awards: ['Richard Neutra Award for Professional Excellence (1989)', 'RIBA Royal Gold Medal (2012)', 'Thomas Jefferson Medal in Architecture (2015)'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q318319', title: 'Herman Hertzberger (Q318319)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Herman_Hertzberger', title: 'Herman Hertzberger', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'piet-blom',
    wikidataId: 'Q1397864',
    name: 'Piet Blom',
    alternativeNames: ['Pieter Blom'],
    gender: 'man',
    born: 1934,
    died: 1999,
    floruit: { start: 1969, end: 1993, override: false },
    movements: 'unaffiliated',
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'housing',
    signatureMaterial: 'concrete',
    portrait: {
      en: 'Blom trained first as a carpenter and building draughtsman and only then took a degree at Amsterdam\'s Academie van Bouwkunst, graduating in 1959 as a pupil of Aldo van Eyck. He spent his career on one idea, which he called living as a general urban roof: lift the dwellings onto columns and let shops, parking, workshops and gardens run continuously underneath. The students\' building at Twente, the Kasbah at Hengelo, the burnt Speelhuis theatre at Helmond, the Rotterdam cube houses and the Closed City at Amersfoort are all versions of it. Because he would not compromise the principle, commissions thinned in the 1980s. He is grouped with Van Eyck and Hertzberger as one of the three architects who carried Dutch Structuralism abroad.',
      es: 'Blom se formó primero como carpintero y delineante de obra, y solo después estudió en la Academie van Bouwkunst de Ámsterdam, donde se tituló en 1959 como alumno de Aldo van Eyck. Dedicó su carrera a una sola idea, que llamó habitar como cubierta urbana general: elevar las viviendas sobre pilares y dejar que comercios, aparcamiento, talleres y jardines corran de forma continua por debajo. El edificio de estudiantes de Twente, la Kasbah de Hengelo, el incendiado teatro Speelhuis de Helmond, las casas cubo de Róterdam y la Ciudad Cerrada de Amersfoort son variantes de lo mismo. Por no ceder en el principio, los encargos escasearon en los años ochenta. Se le agrupa con Van Eyck y Hertzberger como uno de los tres arquitectos que llevaron fuera el estructuralismo neerlandés.',
      it: 'Blom si formò dapprima come falegname e disegnatore edile e solo in seguito studiò all\'Academie van Bouwkunst di Amsterdam, laureandosi nel 1959 come allievo di Aldo van Eyck. Dedicò la carriera a una sola idea, che chiamava abitare come tetto urbano generale: sollevare gli alloggi su pilastri e lasciare che negozi, parcheggi, botteghe e giardini corrano senza interruzione al di sotto. L\'edificio degli studenti a Twente, la Kasbah di Hengelo, il bruciato teatro Speelhuis di Helmond, le case cubo di Rotterdam e la Città Chiusa di Amersfoort ne sono altrettante versioni. Poiché non volle cedere sul principio, negli anni ottanta le commesse si diradarono. È accostato a Van Eyck e Hertzberger come uno dei tre architetti che portarono all\'estero lo strutturalismo olandese.',
    },
    awards: [],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q1397864', title: 'Piet Blom (Q1397864)', license: null },
      { kind: 'wikipedia', url: 'https://nl.wikipedia.org/wiki/Piet_Blom', title: 'Piet Blom', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'renaat-braem',
    wikidataId: 'Q1965216',
    name: 'Renaat Braem',
    alternativeNames: [],
    gender: 'man',
    born: 1910,
    died: 2001,
    floruit: { start: 1948, end: 1980, override: false },
    movements: [{ id: 'functionalism', primary: true }, { id: 'brutalism', primary: false }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'housing',
    signatureMaterial: 'concrete',
    portrait: {
      en: 'Braem left Antwerp\'s Royal Academy in 1935 with a linear-city project stretched between Antwerp and Liège, won the Prix Godecharle on the strength of it, and spent 1936 and 1937 in Le Corbusier\'s Paris atelier. He joined CIAM in 1937 and held to the Athens Charter longer than most of his generation: separated functions, slabs raised on pilotis, green space running underneath and between. Antwerp gave him the commissions that made his name — the Kiel housing units, the police tower left over from an unbuilt administrative centre, the Arena sports hall — and in 1968 he published a polemic, The Ugliest Country in the World, attacking Belgian building culture wholesale. His later work loosens into curves, colour and sculptural concrete.',
      es: 'Braem salió de la Real Academia de Amberes en 1935 con un proyecto de ciudad lineal tendido entre Amberes y Lieja, ganó con él el Prix Godecharle y pasó 1936 y 1937 en el taller parisino de Le Corbusier. Ingresó en los CIAM en 1937 y se mantuvo fiel a la Carta de Atenas más tiempo que casi nadie de su generación: funciones separadas, bloques sobre pilotis, verde corriendo por debajo y entre ellos. Amberes le dio los encargos que lo hicieron conocido —las unidades de vivienda del Kiel, la torre de la policía sobrante de un centro administrativo nunca terminado, el pabellón deportivo Arena— y en 1968 publicó un panfleto, El país más feo del mundo, contra la cultura constructiva belga en bloque. Su obra tardía se suelta en curvas, color y hormigón escultórico.',
      it: 'Braem uscì dalla Reale Accademia di Anversa nel 1935 con un progetto di città lineare tesa fra Anversa e Liegi, vinse grazie a esso il Prix Godecharle e passò il 1936 e il 1937 nell\'atelier parigino di Le Corbusier. Entrò nei CIAM nel 1937 e restò fedele alla Carta d\'Atene più a lungo di quasi tutti i suoi coetanei: funzioni separate, stecche su pilotis, verde che scorre sotto e fra di esse. Anversa gli diede le commesse che lo resero noto — le unità abitative del Kiel, la torre della polizia rimasta da un centro amministrativo mai compiuto, il palazzetto Arena — e nel 1968 pubblicò un pamphlet, Il paese più brutto del mondo, contro l\'intera cultura edilizia belga. L\'opera tarda si scioglie in curve, colore e calcestruzzo scultoreo.',
    },
    awards: ['Prix Godecharle (1935)'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q1965216', title: 'Renaat Braem (Q1965216)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Renaat_Braem', title: 'Renaat Braem', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'jeanne-dekkers',
    wikidataId: 'Q18433700',
    name: 'Jeanne Dekkers',
    alternativeNames: [],
    gender: 'woman',
    born: 1953,
    died: null,
    floruit: { start: 1998, end: 2022, override: false },
    movements: 'unaffiliated',
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'cultural',
    signatureMaterial: 'brick',
    portrait: {
      en: 'Dekkers was born in Venlo, took her degree at the Eindhoven Institute of Technology in 1978 and worked at EGM architecten, joining its board in 1988, before founding Jeanne Dekkers Architectuur in Delft in January 1998. The Limburgs Museum in her home town, finished in 2000, was the first building she completed under her own name. Her work is usually organised as an argument about its site: a museum shaped as a town gate where a gate once stood, civic buildings that set curved masonry against sheer glass to separate what is old from what is new. She has built mainly for public clients — museums, schools, police stations, town halls — and has been professor of architecture at Eindhoven since 2010.',
      es: 'Dekkers nació en Venlo, se tituló en la Escuela Superior Técnica de Eindhoven en 1978 y trabajó en EGM architecten, cuya dirección integró desde 1988, antes de fundar Jeanne Dekkers Architectuur en Delft en enero de 1998. El Limburgs Museum de su ciudad natal, terminado en 2000, fue el primer edificio que completó con firma propia. Su obra suele organizarse como un argumento sobre el lugar: un museo con forma de puerta de ciudad donde antes hubo una puerta, edificios públicos que enfrentan la fábrica curva de ladrillo al vidrio liso para separar lo antiguo de lo nuevo. Ha construido sobre todo para clientes públicos —museos, escuelas, comisarías, ayuntamientos— y es catedrática de arquitectura en Eindhoven desde 2010.',
      it: 'Dekkers è nata a Venlo, si è laureata alla Scuola superiore tecnica di Eindhoven nel 1978 e ha lavorato presso EGM architecten, entrandone nel consiglio direttivo dal 1988, prima di fondare a Delft, nel gennaio 1998, lo studio Jeanne Dekkers Architectuur. Il Limburgs Museum della sua città natale, concluso nel 2000, è il primo edificio da lei completato a proprio nome. Il suo lavoro si organizza di solito come un\'argomentazione sul luogo: un museo a forma di porta urbana là dove sorgeva una porta, edifici pubblici che contrappongono la muratura curva al vetro liscio per separare l\'antico dal nuovo. Ha costruito soprattutto per committenti pubblici — musei, scuole, commissariati, municipi — ed è professoressa di architettura a Eindhoven dal 2010.',
    },
    awards: ['Knight of the Order of Orange-Nassau (2012)'],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q18433700', title: 'Jeanne Dekkers (Q18433700)', license: null },
      { kind: 'wikipedia', url: 'https://nl.wikipedia.org/wiki/Jeanne_Dekkers', title: 'Jeanne Dekkers', license: 'CC BY-SA 4.0' },
      { kind: 'institution', url: 'https://jeannedekkers.nl/en/limburgs-museum-venlo-en/', title: 'Limburgs Museum Venlo — Jeanne Dekkers Architecture', license: null },
    ],
  },
  {
    id: 'francine-houben',
    wikidataId: 'Q2009000',
    name: 'Francine Houben',
    alternativeNames: ['Francine Marie Jeanne Houben', 'Mecanoo'],
    gender: 'woman',
    born: 1955,
    died: null,
    floruit: { start: 1985, end: 2022, override: false },
    movements: 'unaffiliated',
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'cultural',
    signatureMaterial: 'mixed',
    portrait: {
      en: 'Houben graduated cum laude from Delft and is the founding partner and creative director of Mecanoo, the Delft practice that grew out of a student team\'s winning entry for youth housing on Rotterdam\'s Kruisplein. Her range is deliberately wide — libraries above all, but also theatres, stations, housing, museums and hotels — and she describes her method as fusing architecture, urbanism and landscape and asks that a building appeal to all the senses rather than resolve into a single image. The library she completed at Delft University of Technology in 1997, a grass-covered slope pinned by a cone, made the practice\'s reputation and led to work in Britain, the United States and Taiwan. She directed the first International Architecture Biennale Rotterdam in 2003.',
      es: 'Houben se tituló cum laude en Delft y es socia fundadora y directora creativa de Mecanoo, el estudio de Delft nacido de la propuesta ganadora de un equipo de estudiantes para viviendas jóvenes en el Kruisplein de Róterdam. Su repertorio es deliberadamente amplio —bibliotecas sobre todo, pero también teatros, estaciones, vivienda, museos y hoteles— y describe su método como una fusión de arquitectura, urbanismo y paisaje, pidiendo que un edificio apele a todos los sentidos en lugar de resolverse en una sola imagen. La biblioteca que terminó en la Universidad Técnica de Delft en 1997, una ladera cubierta de césped clavada por un cono, dio nombre al estudio y le abrió encargos en Gran Bretaña, Estados Unidos y Taiwán. Dirigió en 2003 la primera Bienal Internacional de Arquitectura de Róterdam.',
      it: 'Houben si è laureata cum laude a Delft ed è socia fondatrice e direttrice creativa di Mecanoo, lo studio di Delft nato dalla proposta vincente di un gruppo di studenti per alloggi giovanili al Kruisplein di Rotterdam. Il suo repertorio è volutamente ampio — biblioteche soprattutto, ma anche teatri, stazioni, residenze, musei e alberghi — e descrive il proprio metodo come una fusione di architettura, urbanistica e paesaggio, chiedendo che un edificio parli a tutti i sensi anziché risolversi in una sola immagine. La biblioteca completata all\'Università tecnica di Delft nel 1997, un pendio erboso trafitto da un cono, fece la fama dello studio e aprì commesse in Gran Bretagna, Stati Uniti e Taiwan. Nel 2003 ha diretto la prima Biennale internazionale di architettura di Rotterdam.',
    },
    awards: ['Amsterdamse Architectuurprijs', 'Prins Bernhard Cultuurfonds Prijs', 'Knight of the Order of the Netherlands Lion'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q2009000', title: 'Francine Houben (Q2009000)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Francine_Houben', title: 'Francine Houben', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'hilde-daem',
    wikidataId: 'Q2551835',
    name: 'Hilde Daem',
    alternativeNames: ['Robbrecht en Daem'],
    gender: 'woman',
    born: 1950,
    died: null,
    floruit: { start: 1990, end: 2015, override: false },
    movements: [{ id: 'minimalism', primary: true }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'cultural',
    signatureMaterial: 'brick',
    portrait: {
      en: 'Daem studied architecture at the Hoger Sint-Lucasinstituut in Ghent and founded Robbrecht en Daem with Paul Robbrecht in 1975. Dutch-language criticism places her among the architects — with Marie-José Van Hee, Christian Kieckens and the critic Marc Dubois — who put Flemish architecture back on the European map through what it calls the Nieuwe Eenvoud, a new simplicity resting on exact proportion, restrained colour and a deliberately small set of materials. The office works at both extremes of scale: exhibition furniture for Documenta, houses and conversions, the Boijmans wing in Rotterdam, the Cinematek in Brussels, and the Bruges concert hall. Daem also trained as a printmaker and, later, in photography, and the practice\'s drawings carry that.',
      es: 'Daem estudió arquitectura en el Hoger Sint-Lucasinstituut de Gante y fundó Robbrecht en Daem con Paul Robbrecht en 1975. La crítica en lengua neerlandesa la sitúa entre los arquitectos —con Marie-José Van Hee, Christian Kieckens y el crítico Marc Dubois— que devolvieron la arquitectura flamenca al mapa europeo mediante lo que llama Nieuwe Eenvoud, una nueva sencillez apoyada en la proporción exacta, el color contenido y un repertorio de materiales deliberadamente corto. El estudio trabaja en los dos extremos de escala: mobiliario expositivo para Documenta, casas y rehabilitaciones, el ala del Boijmans en Róterdam, la Cinematek de Bruselas y el auditorio de Brujas. Daem se formó además como grabadora y, más tarde, en fotografía, y los dibujos del estudio lo delatan.',
      it: 'Daem studiò architettura all\'Hoger Sint-Lucasinstituut di Gand e fondò con Paul Robbrecht lo studio Robbrecht en Daem nel 1975. La critica di lingua neerlandese la colloca fra gli architetti — con Marie-José Van Hee, Christian Kieckens e il critico Marc Dubois — che riportarono l\'architettura fiamminga sulla carta europea attraverso ciò che chiama Nieuwe Eenvoud, una nuova semplicità fondata su proporzione esatta, colore trattenuto e un repertorio di materiali volutamente ristretto. Lo studio lavora a entrambi gli estremi di scala: arredi espositivi per Documenta, case e riconversioni, l\'ala del Boijmans a Rotterdam, la Cinematek di Bruxelles e l\'auditorio di Bruges. Daem si è formata anche come incisora e, più tardi, in fotografia, e i disegni dello studio lo rivelano.',
    },
    awards: [],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q2551835', title: 'Hilde Daem (Q2551835)', license: null },
      { kind: 'wikipedia', url: 'https://nl.wikipedia.org/wiki/Hilde_Daem', title: 'Hilde Daem', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'paul-robbrecht',
    wikidataId: 'Q4429032',
    name: 'Paul Robbrecht',
    alternativeNames: ['Robbrecht en Daem'],
    gender: 'man',
    born: 1950,
    died: null,
    floruit: { start: 1990, end: 2015, override: false },
    movements: [{ id: 'minimalism', primary: true }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'cultural',
    signatureMaterial: 'brick',
    portrait: {
      en: 'Robbrecht studied at Ghent\'s Sint-Lucasinstituut from 1969 to 1974 and, the following year, founded Robbrecht en Daem with Hilde Daem, whom he later married. He also trained and continued to work as a visual artist, and taught for years at Ghent University alongside running the practice; the two strands meet in the exhibition architecture he designed for Documenta in Kassel. Dutch-language critics group him with Daem, Marie-José Van Hee and Christian Kieckens as architects who gave Flanders\' Nieuwe Eenvoud its European standing, built from exact proportion and a short list of materials. Beyond houses and the Boijmans wing in Rotterdam, the Bruges concert hall is the practice\'s clearest public statement. He won the Prix de Rome in 1979 and is a member of the Royal Flemish Academy of Belgium.',
      es: 'Robbrecht estudió en el Sint-Lucasinstituut de Gante entre 1969 y 1974 y, al año siguiente, fundó con Hilde Daem, con quien más tarde se casó, el estudio Robbrecht en Daem. Se formó también como artista visual y siguió ejerciendo como tal, y durante años enseñó en la Universidad de Gante junto con la práctica profesional; ambas vertientes se cruzan en la arquitectura expositiva que diseñó para la Documenta de Kassel. La crítica en neerlandés lo agrupa con Daem, Marie-José Van Hee y Christian Kieckens como los arquitectos que dieron a la Nieuwe Eenvoud flamenca su prestigio europeo, construida sobre la proporción exacta y un repertorio corto de materiales. Además de viviendas y el ala del Boijmans en Róterdam, el auditorio de Brujas es el enunciado público más claro del estudio. Ganó el Prix de Rome en 1979 y es miembro de la Real Academia Flamenca de Bélgica.',
      it: 'Robbrecht studiò al Sint-Lucasinstituut di Gand dal 1969 al 1974 e, l\'anno seguente, fondò con Hilde Daem, che avrebbe poi sposato, lo studio Robbrecht en Daem. Si formò anche come artista visivo e continuò a esercitare quella pratica, insegnando per anni all\'Università di Gand accanto al lavoro professionale; le due vie si incontrano nell\'architettura espositiva che disegnò per Documenta a Kassel. La critica di lingua neerlandese lo colloca insieme a Daem, Marie-José Van Hee e Christian Kieckens fra gli architetti che diedero alla Nieuwe Eenvoud fiamminga il suo prestigio europeo, costruito su proporzione esatta e un repertorio ristretto di materiali. Oltre a case e all\'ala del Boijmans a Rotterdam, l\'auditorio di Bruges è l\'enunciato pubblico più limpido dello studio. Vinse il Prix de Rome nel 1979 ed è membro della Reale Accademia Fiamminga del Belgio.',
    },
    awards: ['Prix de Rome (1979)'],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q4429032', title: 'Paul Robbrecht (Q4429032)', license: null },
      { kind: 'wikipedia', url: 'https://nl.wikipedia.org/wiki/Paul_Robbrecht', title: 'Paul Robbrecht', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    // Wave V2-3, batch B6 — Italy/France featured top-up. Full curate: not
    // previously in the pool. Living; France (and, for his non-featured
    // work, the UAE and Qatar) have no FoP or block outright, ruling out
    // his most photographed French buildings (Institut du Monde Arabe,
    // Fondation Cartier) and the Gulf museums. The three buildings below
    // are all in FoP-clear jurisdictions (Spain, Switzerland, US).
    id: 'jean-nouvel',
    wikidataId: 'Q214317',
    name: 'Jean Nouvel',
    alternativeNames: [],
    gender: 'man',
    born: 1945,
    died: null,
    floruit: { start: 1987, end: 2026, override: false },
    // Nouvel explicitly rejects being read through a school or movement —
    // "unaffiliated" per the project's own rule, not a gap left to fill:
    // no reliable source groups him under a single label the way Foster or
    // Rogers get 'high-tech'.
    movements: 'unaffiliated',
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'cultural',
    signatureMaterial: 'steel-and-glass',
    portrait: {
      en: 'Nouvel was born in Fumel, in southwestern France, to two teachers, and topped the entrance examination for the École des Beaux-Arts in Paris in 1966. He co-founded the "Mars 1976" collective and France\'s first architects\' union before the Institut du Monde Arabe, its south facade a mechanical screen of light-sensing apertures modelled on a mashrabiya, made him internationally known in 1987. Nouvel has since resisted any fixed style or signature form, arguing instead that each building should answer its own site, culture and programme — a position that has produced buildings as different as the colour-shifting Torre Glòries in Barcelona, the lakefront concert hall of Lucerne\'s KKL and the dark, image-printed Guthrie Theater in Minneapolis. He received the Royal Gold Medal, the Praemium Imperiale and the Borromini Prize in 2001, the Wolf Prize in 2005, and the Pritzker Prize in 2008.',
      es: 'Nouvel nació en Fumel, en el suroeste de Francia, hijo de dos profesores, y encabezó el examen de ingreso en la École des Beaux-Arts de París en 1966. Cofundó el colectivo "Mars 1976" y el primer sindicato de arquitectos de Francia antes de que el Instituto del Mundo Árabe, con su fachada sur convertida en una pantalla mecánica de aperturas sensibles a la luz inspirada en una mashrabiya, lo diera a conocer internacionalmente en 1987. Desde entonces Nouvel ha rehuido todo estilo o forma firmados, defendiendo en cambio que cada edificio debe responder a su propio emplazamiento, cultura y programa: una postura que ha dado edificios tan distintos como la cambiante Torre Glòries de Barcelona, la sala de conciertos junto al lago del KKL de Lucerna y el oscuro Guthrie Theater de Mineápolis, impreso con imágenes. Recibió la Royal Gold Medal, el Praemium Imperiale y el Premio Borromini en 2001, el Wolf Prize en 2005 y el Pritzker en 2008.',
      it: 'Nouvel nacque a Fumel, nel sud-ovest della Francia, da due insegnanti, e risultò primo all\'esame di ammissione all\'École des Beaux-Arts di Parigi nel 1966. Cofondò il collettivo "Mars 1976" e il primo sindacato di architetti di Francia prima che l\'Institut du Monde Arabe, con la sua facciata sud trasformata in uno schermo meccanico di aperture sensibili alla luce ispirato a una mashrabiya, lo rendesse noto a livello internazionale nel 1987. Da allora Nouvel ha rifiutato ogni stile o forma firmati, sostenendo invece che ogni edificio debba rispondere al proprio sito, alla propria cultura e al proprio programma: una posizione che ha prodotto edifici diversissimi come la mutevole Torre Glòries di Barcellona, la sala da concerti sul lago del KKL di Lucerna e lo scuro Guthrie Theater di Minneapolis, stampato con immagini. Ricevette la Royal Gold Medal, il Praemium Imperiale e il Premio Borromini nel 2001, il Wolf Prize nel 2005 e il Pritzker nel 2008.',
    },
    awards: ['Royal Gold Medal (2001)', 'Praemium Imperiale (2001)', 'Borromini Prize (2001)', 'Wolf Prize in Arts (2005)', 'Pritzker Prize (2008)'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q214317', title: 'Jean Nouvel (Q214317)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Jean_Nouvel', title: 'Jean Nouvel — Wikipedia', license: 'CC BY-SA 4.0' },
      { kind: 'institution', url: 'https://www.pritzkerprize.com/laureates/2008', title: 'Jean Nouvel — The Pritzker Architecture Prize', license: null },
    ],
  },
];
