import type { Architect } from '@/types/architect';

// Wave 5 curator agent (Nordics and Baltics): real, sourced Architect entries for this slice.
//
// Scope: practices based in Sweden, Norway, Denmark, Finland, Iceland, Estonia,
// Latvia and Lithuania. `workRegions` and `workCentroid` are deliberately left
// empty/zeroed — `npm run data:curate` derives both from each architect's
// buildings and overwrites whatever is written here.
export const EUROPE_NORDIC_ARCHITECTS: Architect[] = [
  {
    id: 'nicodemus-tessin-the-elder',
    wikidataId: 'Q61188',
    name: 'Nicodemus Tessin the Elder',
    alternativeNames: ['Nicodemus Tessin den äldre', 'Nicodemus Tessin I', 'Nicodemus Tessin'],
    gender: 'man',
    born: 1615,
    died: 1681,
    // Override: Drottningholm was finished by his son after his death in 1681,
    // so the building's completion year sits outside his own working span.
    floruit: { start: 1652, end: 1681, override: true },
    movements: [{ id: 'baroque', primary: true }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'domestic',
    signatureMaterial: 'stone',
    portrait: {
      en: "Born in Stralsund in Swedish Pomerania, Nicodemus Tessin the Elder came to Stockholm as a young man and worked alongside Simon de la Vallée before travelling through Germany, Italy, France and the Netherlands to study the new Baroque at first hand. He returned to a country enlarged and enriched by the Peace of Westphalia, and became the architect of its self-image: Skokloster and Borgholm castles, the Bonde and Wrangel palaces in Stockholm, Kalmar Cathedral, and — for the dowager queen Hedwig Eleonora — Drottningholm Palace, begun in 1662 and inscribed as a World Heritage Site in 1991. His manner is Italian and French in vocabulary but Swedish in temper: long, evenly ranked façades, restrained rustication, a giant order used sparingly. He founded a dynasty. When he died in 1681 his son Nicodemus Tessin the Younger inherited both the office and its unfinished commissions.",
      es: "Nacido en Stralsund, en la Pomerania sueca, Nicodemus Tessin el Viejo llegó a Estocolmo siendo joven y trabajó junto a Simon de la Vallée antes de recorrer Alemania, Italia, Francia y los Países Bajos para estudiar de primera mano el nuevo Barroco. Regresó a un país ensanchado y enriquecido por la Paz de Westfalia y se convirtió en el arquitecto de su propia imagen: los castillos de Skokloster y Borgholm, los palacios Bonde y Wrangel en Estocolmo, la catedral de Kalmar y, para la reina viuda Hedvig Eleonora, el palacio de Drottningholm, iniciado en 1662 e inscrito como Patrimonio Mundial en 1991. Su lenguaje es italiano y francés, pero su temple es sueco: fachadas largas y de ritmo uniforme, almohadillado contenido, orden gigante empleado con parquedad. Fundó una dinastía: a su muerte, en 1681, su hijo Nicodemus Tessin el Joven heredó el taller y los encargos inacabados.",
      it: "Nato a Stralsunda, nella Pomerania svedese, Nicodemus Tessin il Vecchio giunse a Stoccolma da giovane e lavorò accanto a Simon de la Vallée prima di viaggiare in Germania, Italia, Francia e Paesi Bassi per studiare di persona il nuovo Barocco. Tornò in un paese ingrandito e arricchito dalla Pace di Vestfalia e ne divenne l'architetto dell'autorappresentazione: i castelli di Skokloster e Borgholm, i palazzi Bonde e Wrangel a Stoccolma, la cattedrale di Kalmar e, per la regina vedova Edvige Eleonora, il castello di Drottningholm, iniziato nel 1662 e iscritto nel Patrimonio Mondiale nel 1991. Il suo lessico è italiano e francese, ma il temperamento è svedese: facciate lunghe e scandite con regolarità, bugnato misurato, ordine gigante usato con parsimonia. Fondò una dinastia: alla sua morte, nel 1681, il figlio Nicodemus Tessin il Giovane ereditò lo studio e i cantieri incompiuti.",
    },
    awards: [],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q61188', title: 'Nicodemus Tessin the Elder (Q61188)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Nicodemus_Tessin_the_Elder', title: 'Nicodemus Tessin the Elder', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Drottningholm_Palace', title: 'Drottningholm Palace', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'laurynas-gucevicius',
    wikidataId: 'Q1808445',
    name: 'Laurynas Gucevičius',
    alternativeNames: ['Wawrzyniec Gucewicz', 'Laurynas Stuoka-Gucevičius', 'Laurynas Masiulis'],
    gender: 'man',
    born: 1753,
    died: 1798,
    // Override: he died in 1798; the Town Hall (1799) and Vilnius Cathedral
    // (1801) were both completed after his death.
    floruit: { start: 1782, end: 1798, override: true },
    movements: [{ id: 'neoclassicism', primary: true }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'civic',
    signatureMaterial: 'stone',
    portrait: {
      en: "Laurynas Gucevičius was born Laurynas Masiulis, son of a Lithuanian peasant, in a village near Kupiškis in the Grand Duchy of Lithuania, and took the surname of the godmother who paid for his schooling. He entered the Academy of Vilnius in 1773 and studied architecture under Marcin Knackfus; his patron, Bishop Ignacy Massalski, sent him first to Warsaw and then to Rome. He spent a year and a half in Paris in the orbit of Jacques-Germain Soufflot and Claude-Nicolas Ledoux, and came home carrying French Neoclassicism into a city still thick with Baroque. Everything he designed was built in the Grand Duchy: the Verkiai palace complex outside Vilnius, the recasting of Vilnius Cathedral as a colonnaded temple, and the Vilnius Town Hall. He saw neither of the last two finished — he died in 1798, aged forty-five.",
      es: "Laurynas Gucevičius nació como Laurynas Masiulis, hijo de un campesino lituano, en una aldea cercana a Kupiškis, en el Gran Ducado de Lituania, y adoptó el apellido de la madrina que costeó sus estudios. Ingresó en la Academia de Vilna en 1773 y estudió arquitectura con Marcin Knackfus; su protector, el obispo Ignacy Massalski, lo envió primero a Varsovia y después a Roma. Pasó año y medio en París, en la órbita de Jacques-Germain Soufflot y Claude-Nicolas Ledoux, y regresó trayendo el neoclasicismo francés a una ciudad todavía densamente barroca. Todo lo que proyectó se levantó en el Gran Ducado: el conjunto palaciego de Verkiai, la refundición de la catedral de Vilna como templo columnado y la Casa Consistorial. No llegó a ver terminadas las dos últimas: murió en 1798, a los cuarenta y cinco años.",
      it: "Laurynas Gucevičius nacque come Laurynas Masiulis, figlio di un contadino lituano, in un villaggio presso Kupiškis, nel Granducato di Lituania, e prese il cognome della madrina che ne finanziò gli studi. Entrò all'Accademia di Vilnius nel 1773 e studiò architettura con Marcin Knackfus; il suo protettore, il vescovo Ignacy Massalski, lo inviò prima a Varsavia e poi a Roma. Trascorse un anno e mezzo a Parigi nell'orbita di Jacques-Germain Soufflot e Claude-Nicolas Ledoux, e tornò portando il neoclassicismo francese in una città ancora fittamente barocca. Tutto ciò che progettò fu costruito nel Granducato: il complesso di Verkiai fuori Vilnius, la rifusione della cattedrale in forma di tempio colonnato e il Municipio. Non vide terminate le ultime due opere: morì nel 1798, a quarantacinque anni.",
    },
    awards: ['Merentibus Medal'],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q1808445', title: 'Laurynas Gucevičius (Q1808445)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Laurynas_Gucevi%C4%8Dius', title: 'Laurynas Gucevičius', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://lt.wikipedia.org/wiki/Vilniaus_rotu%C5%A1%C4%97', title: 'Vilniaus rotušė', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'mikhail-eisenstein',
    wikidataId: 'Q463464',
    name: 'Mikhail Eisenstein',
    alternativeNames: ['Mihails Eizenšteins', 'Mikhail Osipovich Eisenstein', 'Михаил Осипович Эйзенштейн'],
    gender: 'man',
    born: 1867,
    died: 1920,
    floruit: { start: 1897, end: 1911, override: false },
    movements: [{ id: 'art-nouveau', primary: true }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'housing',
    signatureMaterial: 'stone',
    portrait: {
      en: "Mikhail Eisenstein was a civil engineer, not a trained architect. Born into a Jewish merchant family in Bila Tserkva, he qualified in Saint Petersburg in 1893, moved to Riga, and rose to head the road department of the Governorate of Livonia while designing tenement houses on the side. Between 1901 and 1906 that sideline produced the most photographed façades in the Baltic: some twenty buildings, clustered on and around Alberta iela, in a form of Art Nouveau so lavish that it reads as an argument with its neighbours. Sphinxes, masks, griffins, peacocks and colossal female heads are hung on conventional, even conservative, tenement plans. He drew on French and Viennese sources and on pattern books; his son Sergei Eisenstein became the Soviet film director. He left Riga in 1917 and died in Berlin.",
      es: "Mijaíl Eisenstein fue ingeniero de caminos, no arquitecto de formación. Nacido en una familia judía de comerciantes en Bila Tserkva, se tituló en San Petersburgo en 1893, se instaló en Riga y llegó a dirigir el departamento de carreteras de la gobernación de Livonia mientras proyectaba casas de vecindad como actividad paralela. Entre 1901 y 1906 esa actividad paralela produjo las fachadas más fotografiadas del Báltico: una veintena de edificios, agrupados en Alberta iela y sus alrededores, en un modernismo tan pródigo que se lee como una discusión con los vecinos. Esfinges, máscaras, grifos, pavos reales y cabezas femeninas colosales cuelgan sobre plantas de alquiler convencionales, incluso conservadoras. Bebió de fuentes francesas y vienesas y de repertorios de láminas; su hijo Serguéi Eisenstein sería el cineasta soviético. Abandonó Riga en 1917 y murió en Berlín.",
      it: "Michail Ėjzenštejn era un ingegnere civile, non un architetto di formazione. Nato da una famiglia ebraica di mercanti a Bila Cerkva, si laureò a San Pietroburgo nel 1893, si stabilì a Riga e arrivò a dirigere il dipartimento stradale del governatorato di Livonia, progettando nel frattempo case da reddito come attività secondaria. Fra il 1901 e il 1906 quell'attività secondaria produsse le facciate più fotografate del Baltico: una ventina di edifici, raccolti in Alberta iela e dintorni, in un Art Nouveau tanto sontuoso da sembrare una discussione con i vicini. Sfingi, mascheroni, grifoni, pavoni e teste femminili colossali sono appesi a piante d'affitto convenzionali, persino conservatrici. Attinse a fonti francesi e viennesi e a repertori di modelli; suo figlio Sergej Ėjzenštejn divenne il regista sovietico. Lasciò Riga nel 1917 e morì a Berlino.",
    },
    awards: ['Order of Saint Stanislaus, 3rd class (1900)'],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q463464', title: 'Mikhail Eisenstein (Q463464)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Mikhail_Eisenstein', title: 'Mikhail Eisenstein', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'wivi-lonn',
    wikidataId: 'Q3737312',
    name: 'Wivi Lönn',
    alternativeNames: ['Olivia Mathilda Lönn', 'Viivi Lönn'],
    gender: 'woman',
    born: 1872,
    died: 1966,
    floruit: { start: 1900, end: 1933, override: false },
    movements: [{ id: 'art-nouveau', primary: true }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'educational',
    signatureMaterial: 'stone',
    portrait: {
      en: "Wivi Lönn needed a special permit to enter the Tampere industrial school as the only woman in her class, and another to read architecture at the Polytechnic in Helsinki, where she qualified in 1896. She was the fourth woman in Finland to become an architect and the first to open her own office — the first woman in the country to practise independently rather than inside someone else's firm. She won open competitions repeatedly: Tampere's central fire station, girls' schools in Tampere and Jyväskylä, and, with Armas Lindgren, the Estonia Theatre in Tallinn and the New Student House in Helsinki. School buildings were her speciality and her instinct in them was anti-institutional — daylight, warmth, rooms scaled to children. In 1956 she became the first woman awarded the honorary title of Professor by the Finnish Association of Architects.",
      es: "Wivi Lönn necesitó un permiso especial para entrar en la escuela industrial de Tampere como única mujer de su clase, y otro para cursar arquitectura en el Politécnico de Helsinki, donde se tituló en 1896. Fue la cuarta arquitecta de Finlandia y la primera en abrir estudio propio: la primera del país que ejerció por su cuenta y no dentro del despacho de otro. Ganó concursos abiertos una y otra vez: el parque central de bomberos de Tampere, escuelas de niñas en Tampere y Jyväskylä y, junto a Armas Lindgren, el Teatro Estonia de Tallin y la Casa Nueva del Estudiante en Helsinki. Los edificios escolares fueron su especialidad, y en ellos su instinto era antiinstitucional: luz natural, calidez, estancias a escala de los niños. En 1956 fue la primera mujer nombrada Profesora honoraria por la Asociación Finlandesa de Arquitectos.",
      it: "Wivi Lönn ebbe bisogno di un permesso speciale per entrare alla scuola industriale di Tampere come unica donna della sua classe, e di un altro per studiare architettura al Politecnico di Helsinki, dove si laureò nel 1896. Fu la quarta donna architetto in Finlandia e la prima ad aprire uno studio proprio: la prima nel paese a esercitare in modo indipendente e non all'interno dello studio altrui. Vinse ripetutamente concorsi pubblici: la caserma centrale dei vigili del fuoco di Tampere, le scuole femminili di Tampere e Jyväskylä e, con Armas Lindgren, il Teatro Estonia di Tallinn e la Casa dello Studente di Helsinki. Gli edifici scolastici furono la sua specialità e vi mise un istinto antistituzionale: luce naturale, calore, ambienti a misura di bambino. Nel 1956 fu la prima donna insignita del titolo onorario di Professore dall'Associazione finlandese degli architetti.",
    },
    awards: ['Honorary Professor, Finnish Association of Architects (SAFA), 1956', 'Architecta medal, 1957'],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q3737312', title: 'Wivi Lönn (Q3737312)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Wivi_L%C3%B6nn', title: 'Wivi Lönn', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://fi.wikipedia.org/wiki/Ebeneser-talo', title: 'Ebeneser-talo', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'aino-aalto',
    wikidataId: 'Q273511',
    name: 'Aino Aalto',
    alternativeNames: ['Aino Marsio-Aalto', 'Aino Marsio', 'Aino Maria Mandelin', 'Aino and Alvar Aalto'],
    gender: 'woman',
    born: 1894,
    died: 1949,
    floruit: { start: 1926, end: 1949, override: false },
    movements: [
      { id: 'functionalism', primary: true },
      { id: 'organic-architecture', primary: false },
    ],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'domestic',
    signatureMaterial: 'timber',
    portrait: {
      en: "Aino Marsio qualified as an architect at the Helsinki Institute of Technology in 1920, worked for Oiva Kallio and Gunnar Wahlroos, joined Alvar Aalto's office in 1924 and married him in 1925. For the next twenty-five years the practice was a partnership. In 1935 she co-founded Artek with Alvar, Maire Gullichsen and Nils-Gustav Hahl, became its head designer and later its managing director, and oversaw more than eighty interiors; of the hundreds of Artek furniture designs, only a handful are her husband's. Her pressed-glass Bölgeblick series won a prize at the 1936 Milan Triennale and is still in production. Villa Flora at Alajärvi (1926) was credited to her alone; the Villa Mairea interiors were her responsibility. She died of cancer in 1949, aged fifty-four, having spent her career being measured against her husband.",
      es: "Aino Marsio se tituló como arquitecta en el Instituto Politécnico de Helsinki en 1920, trabajó para Oiva Kallio y Gunnar Wahlroos, entró en el estudio de Alvar Aalto en 1924 y se casó con él en 1925. Durante los veinticinco años siguientes el estudio fue una sociedad de dos. En 1935 fundó Artek junto a Alvar, Maire Gullichsen y Nils-Gustav Hahl, fue su directora de diseño y más tarde su directora gerente, y supervisó más de ochenta interiores; de los cientos de muebles de Artek, apenas un puñado son de su marido. Su serie de vidrio prensado Bölgeblick obtuvo premio en la Trienal de Milán de 1936 y sigue fabricándose. Villa Flora, en Alajärvi (1926), se le atribuyó en exclusiva; los interiores de Villa Mairea fueron responsabilidad suya. Murió de cáncer en 1949, a los cincuenta y cuatro años, tras una carrera entera medida frente a la de su marido.",
      it: "Aino Marsio si laureò in architettura all'Istituto politecnico di Helsinki nel 1920, lavorò per Oiva Kallio e Gunnar Wahlroos, entrò nello studio di Alvar Aalto nel 1924 e lo sposò nel 1925. Per i venticinque anni successivi lo studio fu una società fra due. Nel 1935 fondò Artek con Alvar, Maire Gullichsen e Nils-Gustav Hahl, ne fu capo progettista e poi amministratrice delegata, e seguì oltre ottanta interni; delle centinaia di arredi Artek solo pochissimi sono del marito. La sua serie in vetro pressato Bölgeblick fu premiata alla Triennale di Milano del 1936 ed è tuttora in produzione. Villa Flora ad Alajärvi (1926) le fu attribuita per intero; gli interni di Villa Mairea furono di sua responsabilità. Morì di cancro nel 1949, a cinquantaquattro anni, dopo una carriera intera misurata su quella del marito.",
    },
    awards: ['Grand Prix, VI Triennale di Milano, 1936'],
    tier: 'canon',
    context: {
      body: {
        en: "The scale of Aino Aalto's authorship inside the Aalto office is contested because the office rarely distinguished the two hands: English Wikipedia notes that her role in the architecture attributed to Alvar Aalto \"has never been specifically verified\". Where the record is explicit it is generous — the Villa Mairea Foundation, which owns and runs the house, credits it as \"designed by Aino and Alvar Aalto\" and states that \"the interior design was the responsibility of Aino Aalto\". Attributing Villa Mairea to her here follows that institutional credit rather than the shorthand of the textbooks; the joint authorship is stated in the building's own entry.",
        es: "El alcance de la autoría de Aino Aalto dentro del estudio Aalto es discutido, porque el despacho rara vez distinguió las dos manos: la Wikipedia en inglés señala que su papel en la arquitectura atribuida a Alvar Aalto «nunca ha sido verificado de forma específica». Allí donde el registro es explícito, resulta generoso: la Fundación Villa Mairea, propietaria y gestora de la casa, la acredita como «proyectada por Aino y Alvar Aalto» y afirma que «el diseño de los interiores fue responsabilidad de Aino Aalto». Atribuirle aquí Villa Mairea sigue ese crédito institucional y no el atajo de los manuales; la coautoría se declara en la ficha del propio edificio.",
        it: "La misura della paternità di Aino Aalto all'interno dello studio Aalto è discussa, perché lo studio distinse di rado le due mani: la Wikipedia inglese osserva che il suo ruolo nell'architettura attribuita ad Alvar Aalto «non è mai stato verificato in modo specifico». Dove il documento è esplicito, però, è generoso: la Fondazione Villa Mairea, che possiede e gestisce la casa, la accredita come «progettata da Aino e Alvar Aalto» e afferma che «la progettazione degli interni fu responsabilità di Aino Aalto». Attribuirle qui Villa Mairea segue quel credito istituzionale e non la scorciatoia dei manuali; la coautoria è dichiarata nella scheda dell'edificio stesso.",
      },
      sources: [
        { kind: 'institution', url: 'https://www.villamairea.fi/en/architecture/', title: 'Villa Mairea Foundation — Architecture', license: null },
        { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Aino_Aalto', title: 'Aino Aalto', license: 'CC BY-SA 4.0' },
      ],
    },
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q273511', title: 'Aino Aalto (Q273511)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Aino_Aalto', title: 'Aino Aalto', license: 'CC BY-SA 4.0' },
      { kind: 'institution', url: 'https://www.alvaraalto.fi/en/alvar-aalto/aino-aalto/', title: 'Alvar Aalto Foundation — Aino Aalto', license: null },
      { kind: 'institution', url: 'https://www.villamairea.fi/en/architecture/', title: 'Villa Mairea Foundation — Architecture', license: null },
    ],
  },
  {
    id: 'alvar-aalto',
    wikidataId: 'Q82840',
    name: 'Alvar Aalto',
    alternativeNames: ['Hugo Alvar Henrik Aalto'],
    gender: 'man',
    born: 1898,
    died: 1976,
    floruit: { start: 1923, end: 1978, override: false },
    movements: [
      { id: 'functionalism', primary: true },
      { id: 'organic-architecture', primary: false },
    ],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'civic',
    signatureMaterial: 'brick',
    portrait: {
      en: "Alvar Aalto came out of Nordic Classicism in the 1920s, converted to Functionalism with the Turun Sanomat building, the Viipuri Library and the Paimio Sanatorium, and then spent forty years dismantling the movement's severity from inside it. From the late 1930s his work bends: undulating timber screens, fan-shaped plans, brick left rough, light brought down through shafts rather than pushed through glass walls. He worked in partnership with Aino Marsio-Aalto from 1924 until her death in 1949, and with Elissa Mäkiniemi from 1952. Furniture, glass and lighting were part of the same practice — the bent-plywood stool and the Savoy vase are as widely known as the buildings. He won the RIBA Royal Gold Medal in 1957 and the AIA Gold Medal in 1963; thirteen of his works were inscribed together as a World Heritage Site in 2026.",
      es: "Alvar Aalto salió del clasicismo nórdico de los años veinte, se convirtió al funcionalismo con el edificio del Turun Sanomat, la biblioteca de Víborg y el sanatorio de Paimio, y dedicó luego cuarenta años a desmontar desde dentro la severidad del movimiento. Desde finales de los treinta su obra se curva: celosías onduladas de madera, plantas en abanico, ladrillo dejado áspero, luz conducida por lucernarios en vez de empujada a través de muros de vidrio. Trabajó en sociedad con Aino Marsio-Aalto desde 1924 hasta la muerte de esta en 1949, y con Elissa Mäkiniemi desde 1952. El mueble, el vidrio y la luminaria formaban parte del mismo oficio: el taburete de contrachapado curvado y el jarrón Savoy son tan conocidos como los edificios. Recibió la Medalla de Oro del RIBA en 1957 y la del AIA en 1963; trece de sus obras fueron inscritas conjuntamente como Patrimonio Mundial en 2026.",
      it: "Alvar Aalto uscì dal classicismo nordico degli anni Venti, passò al funzionalismo con l'edificio del Turun Sanomat, la biblioteca di Viipuri e il sanatorio di Paimio, e impiegò poi quarant'anni a smontare dall'interno la severità del movimento. Dalla fine degli anni Trenta la sua opera si incurva: schermi ondulati di legno, piante a ventaglio, mattone lasciato ruvido, luce calata da pozzi anziché spinta attraverso pareti di vetro. Lavorò in società con Aino Marsio-Aalto dal 1924 fino alla morte di lei nel 1949, e con Elissa Mäkiniemi dal 1952. Mobili, vetro e apparecchi di illuminazione facevano parte dello stesso mestiere: lo sgabello in compensato curvato e il vaso Savoy sono noti quanto gli edifici. Ottenne la Royal Gold Medal del RIBA nel 1957 e la Gold Medal dell'AIA nel 1963; tredici sue opere sono state iscritte insieme nel Patrimonio Mondiale nel 2026.",
    },
    awards: ['RIBA Royal Gold Medal, 1957', 'AIA Gold Medal, 1963', 'Prince Eugen Medal, 1954', 'Sonning Prize, 1962'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q82840', title: 'Alvar Aalto (Q82840)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Alvar_Aalto', title: 'Alvar Aalto', license: 'CC BY-SA 4.0' },
      { kind: 'institution', url: 'https://www.alvaraalto.fi/en/alvar-aalto-foundation/alvar-aalto-and-unesco-world-heritage/', title: 'Alvar Aalto Foundation — Alvar Aalto and UNESCO World Heritage', license: null },
    ],
  },
  {
    id: 'valve-pormeister',
    wikidataId: 'Q544537',
    name: 'Valve Pormeister',
    alternativeNames: ['Valve Ulm', 'Valve Pormeister-Ulm'],
    gender: 'woman',
    born: 1922,
    died: 2002,
    floruit: { start: 1960, end: 1992, override: false },
    movements: [
      { id: 'organic-architecture', primary: true },
      { id: 'functionalism', primary: false },
    ],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'cultural',
    signatureMaterial: 'brick',
    portrait: {
      en: "Valve Pormeister trained as a landscape architect at the Tallinn State Institute of Applied Art and came to buildings sideways: hired to landscape the slope below the new Song Festival Grounds, she talked her way into designing the exhibition hall as well. The Flower Pavilion that resulted, finished in 1960, made her reputation at a stroke and became the emblem of post-Stalinist architecture in Estonia — light, glazed, low, threaded between trees that were left standing. She spent her career inside the state agricultural design institute and turned its least glamorous programmes into architecture: poultry research stations, plant-protection laboratories, farm canteens, agricultural faculties. Critics read Aalto in her work; she said the influence was Richard Neutra. She is routinely called the grand old lady of Estonian architecture and the first woman to shape it.",
      es: "Valve Pormeister se formó como paisajista en el Instituto Estatal de Arte Aplicado de Tallin y llegó a la edificación de lado: contratada para ajardinar la ladera bajo el nuevo recinto de la Fiesta de la Canción, se las arregló para proyectar también el pabellón de exposiciones. El Pabellón de las Flores resultante, terminado en 1960, la consagró de golpe y se convirtió en el emblema de la arquitectura postestalinista en Estonia: ligero, acristalado, bajo, enhebrado entre los árboles que se dejaron en pie. Pasó su carrera dentro del instituto estatal de proyectos agrarios y convirtió sus programas menos lucidos en arquitectura: estaciones de investigación avícola, laboratorios fitosanitarios, comedores de koljós, facultades agronómicas. La crítica leía a Aalto en su obra; ella decía que la influencia era Richard Neutra. Se la llama habitualmente la gran dama de la arquitectura estonia y la primera mujer que la moldeó.",
      it: "Valve Pormeister si formò come architetta paesaggista all'Istituto statale di arte applicata di Tallinn e arrivò all'edificio di traverso: assunta per sistemare il pendio sotto il nuovo campo delle Feste del Canto, ottenne di progettare anche la sala espositiva. Il Padiglione dei Fiori che ne nacque, ultimato nel 1960, la impose di colpo e divenne l'emblema dell'architettura post-staliniana in Estonia: leggero, vetrato, basso, infilato fra alberi lasciati in piedi. Trascorse la carriera dentro l'istituto statale di progettazione agraria e trasformò in architettura i suoi programmi meno prestigiosi: stazioni di ricerca avicola, laboratori fitosanitari, mense di fattoria, facoltà agrarie. La critica leggeva Aalto nel suo lavoro; lei diceva che l'influenza era Richard Neutra. È abitualmente chiamata la grande signora dell'architettura estone e la prima donna che l'abbia plasmata.",
    },
    awards: ['Prize of Soviet Estonia, 1965 and 1967', 'Honoured Architect of the Estonian SSR', 'USSR State Prize', 'Order of the White Star, 5th Class'],
    tier: 'deep',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q544537', title: 'Valve Pormeister (Q544537)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Valve_Pormeister', title: 'Valve Pormeister', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://et.wikipedia.org/wiki/Lillepaviljon', title: 'Lillepaviljon', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'sigurd-lewerentz',
    wikidataId: 'Q550245',
    name: 'Sigurd Lewerentz',
    alternativeNames: ['Sigurd Lewerentz (1885–1975)'],
    gender: 'man',
    born: 1885,
    died: 1975,
    floruit: { start: 1914, end: 1975, override: false },
    movements: [
      { id: 'functionalism', primary: true },
      { id: 'neoclassicism', primary: false },
    ],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'sacral',
    signatureMaterial: 'brick',
    portrait: {
      en: "Sigurd Lewerentz trained first as a mechanical engineer at Chalmers, then apprenticed in Germany and studied under Westman, Östberg and Tengbom. In 1915 he and Gunnar Asplund won the competition for Stockholm's Woodland Cemetery, a landscape of pine and grass that remains one of the century's great works; Lewerentz built the Chapel of the Resurrection there and laid out the Way of the Cross. He fell out with the profession after the 1930 Stockholm Exhibition and spent much of the next two decades running a factory that made his own patented steel windows and fittings. Two churches at the very end of his life — St Mark's at Björkhagen and St Peter's at Klippan — reopened his career and made him a cult figure: brick laid without cutting, glass clipped to the outside of the wall, nothing explained.",
      es: "Sigurd Lewerentz se formó primero como ingeniero mecánico en Chalmers, después se instruyó en Alemania y estudió con Westman, Östberg y Tengbom. En 1915 ganó junto a Gunnar Asplund el concurso del Cementerio del Bosque de Estocolmo, un paisaje de pinos y hierba que sigue siendo una de las grandes obras del siglo; allí construyó la Capilla de la Resurrección y trazó el Camino de la Cruz. Se distanció de la profesión tras la Exposición de Estocolmo de 1930 y pasó buena parte de las dos décadas siguientes al frente de una fábrica que producía sus propias ventanas y herrajes de acero patentados. Dos iglesias del final de su vida —San Marcos en Björkhagen y San Pedro en Klippan— reabrieron su carrera y lo convirtieron en figura de culto: ladrillo colocado sin cortar, vidrio sujeto por fuera del muro, nada explicado.",
      it: "Sigurd Lewerentz si formò dapprima come ingegnere meccanico a Chalmers, poi fece apprendistato in Germania e studiò con Westman, Östberg e Tengbom. Nel 1915 vinse con Gunnar Asplund il concorso per il Cimitero nel Bosco di Stoccolma, un paesaggio di pini ed erba che resta una delle grandi opere del secolo; vi costruì la Cappella della Resurrezione e tracciò la Via Crucis. Si allontanò dalla professione dopo l'Esposizione di Stoccolma del 1930 e passò gran parte dei due decenni successivi a dirigere una fabbrica che produceva finestre e ferramenta d'acciaio di suo brevetto. Due chiese della vecchiaia — San Marco a Björkhagen e San Pietro a Klippan — riaprirono la sua carriera e ne fecero una figura di culto: mattoni posati senza tagli, vetri fissati all'esterno del muro, nulla spiegato.",
    },
    awards: ['Prince Eugen Medal, 1950'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q550245', title: 'Sigurd Lewerentz (Q550245)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Sigurd_Lewerentz', title: 'Sigurd Lewerentz', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://sv.wikipedia.org/wiki/Sankt_Petri_kyrka,_Klippan', title: 'Sankt Petri kyrka, Klippan', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'jorn-utzon',
    wikidataId: 'Q180398',
    name: 'Jørn Utzon',
    alternativeNames: ['Jørn Oberg Utzon', 'Jorn Utzon'],
    gender: 'man',
    born: 1918,
    died: 2008,
    floruit: { start: 1952, end: 2008, override: false },
    movements: [
      { id: 'organic-architecture', primary: true },
      { id: 'expressionism', primary: false },
    ],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'cultural',
    signatureMaterial: 'concrete',
    portrait: {
      en: "Jørn Utzon studied at the Royal Danish Academy under Kay Fisker and Steen Eiler Rasmussen, worked for Gunnar Asplund in Stockholm, visited Alvar Aalto in 1946, and then travelled — Morocco, Mexico, the United States, later China and Nepal — collecting the platforms, courtyards and tiled roofs that recur through his work. He called his method additive architecture: standardised parts multiplied like the elements of a language rather than composed once. The Kingo courtyard houses at Helsingør, Bagsværd Church, the Kuwait National Assembly and Can Lis on Mallorca all argue it. The Sydney Opera House, won in competition in 1957, made him famous and then broke him; he resigned in 1966 and never returned to Australia. The Pritzker Prize came in 2003, five years before his death.",
      es: "Jørn Utzon estudió en la Real Academia Danesa con Kay Fisker y Steen Eiler Rasmussen, trabajó para Gunnar Asplund en Estocolmo, visitó a Alvar Aalto en 1946 y después viajó —Marruecos, México, Estados Unidos, más tarde China y Nepal— recogiendo las plataformas, los patios y las cubiertas de teja que reaparecen en toda su obra. Llamó a su método arquitectura aditiva: piezas normalizadas multiplicadas como los elementos de una lengua, no compuestas de una sola vez. Las casas patio de Kingo en Helsingør, la iglesia de Bagsværd, la Asamblea Nacional de Kuwait y Can Lis en Mallorca lo demuestran. La Ópera de Sídney, ganada en concurso en 1957, lo hizo famoso y luego lo quebró: dimitió en 1966 y jamás regresó a Australia. El Premio Pritzker llegó en 2003, cinco años antes de su muerte.",
      it: "Jørn Utzon studiò alla Reale Accademia danese con Kay Fisker e Steen Eiler Rasmussen, lavorò per Gunnar Asplund a Stoccolma, visitò Alvar Aalto nel 1946 e poi viaggiò — Marocco, Messico, Stati Uniti, più tardi Cina e Nepal — raccogliendo le piattaforme, le corti e i tetti in laterizio che ritornano in tutta la sua opera. Chiamò il proprio metodo architettura additiva: parti standardizzate moltiplicate come gli elementi di una lingua, non composte una volta per tutte. Le case a corte di Kingo a Helsingør, la chiesa di Bagsværd, l'Assemblea Nazionale del Kuwait e Can Lis a Maiorca ne sono la dimostrazione. L'Opera House di Sydney, vinta per concorso nel 1957, lo rese celebre e poi lo spezzò: si dimise nel 1966 e non tornò mai in Australia. Il Pritzker arrivò nel 2003, cinque anni prima della morte.",
    },
    awards: ['Pritzker Architecture Prize, 2003', 'RIBA Royal Gold Medal, 1978', 'Wolf Prize in Architecture, 1992', 'Sonning Prize, 1998', 'C. F. Hansen Medal, 1967'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q180398', title: 'Jørn Utzon (Q180398)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/J%C3%B8rn_Utzon', title: 'Jørn Utzon', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Bagsv%C3%A6rd_Church', title: 'Bagsværd Church', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'raili-pietila',
    wikidataId: 'Q3417698',
    name: 'Raili Pietilä',
    alternativeNames: ['Raili Paatelainen', 'Raili Inkeri Marjatta Pietilä', 'Raili and Reima Pietilä'],
    gender: 'woman',
    born: 1926,
    died: 2021,
    floruit: { start: 1961, end: 1993, override: false },
    movements: [
      { id: 'organic-architecture', primary: true },
      { id: 'brutalism', primary: false },
    ],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'cultural',
    signatureMaterial: 'concrete',
    portrait: {
      en: "Raili Paatelainen graduated in architecture from the Helsinki University of Technology in 1956, worked for the planner Olli Kivinen and for Olaf Küttner, and in 1960 founded an office with Reima Pietilä; they married in 1963. From that point every work of the practice was officially attributed to both of them, and in 1975 the office was renamed Raili and Reima Pietilä Architects. Together they produced the strangest and most inventive Finnish buildings of the postwar decades — Kaleva Church in Tampere, the Dipoli student union at Otaniemi, Hervanta's civic and congregational centre, Tampere's Metso library, and Mäntyniemi, the Finnish president's residence, which Raili carried to completion after Reima's death in 1993. Popular accounts still shorten the pair to his name alone.",
      es: "Raili Paatelainen se licenció en arquitectura en la Universidad Politécnica de Helsinki en 1956, trabajó para el urbanista Olli Kivinen y para Olaf Küttner y en 1960 fundó un estudio con Reima Pietilä; se casaron en 1963. Desde entonces toda la obra del despacho se atribuyó oficialmente a los dos, y en 1975 el estudio pasó a llamarse Raili y Reima Pietilä Arquitectos. Juntos produjeron los edificios finlandeses más extraños e inventivos de las décadas de posguerra: la iglesia de Kaleva en Tampere, la casa del estudiante Dipoli en Otaniemi, el centro cívico y parroquial de Hervanta, la biblioteca Metso de Tampere y Mäntyniemi, la residencia del presidente de Finlandia, que Raili llevó a término tras la muerte de Reima en 1993. Los relatos divulgativos siguen reduciendo la pareja al nombre de él.",
      it: "Raili Paatelainen si laureò in architettura all'Università politecnica di Helsinki nel 1956, lavorò per l'urbanista Olli Kivinen e per Olaf Küttner e nel 1960 fondò uno studio con Reima Pietilä; si sposarono nel 1963. Da quel momento ogni opera dello studio fu ufficialmente attribuita a entrambi, e nel 1975 lo studio fu ribattezzato Raili e Reima Pietilä Architetti. Insieme realizzarono gli edifici finlandesi più strani e inventivi dei decenni del dopoguerra: la chiesa di Kaleva a Tampere, la casa dello studente Dipoli a Otaniemi, il centro civico e parrocchiale di Hervanta, la biblioteca Metso di Tampere e Mäntyniemi, la residenza del presidente di Finlandia, che Raili portò a termine dopo la morte di Reima nel 1993. I racconti divulgativi continuano a ridurre la coppia al nome di lui.",
    },
    awards: ['Knight First Class of the Order of the White Rose of Finland'],
    tier: 'deep',
    context: {
      body: {
        en: "English Wikipedia records that Reima Pietilä won the 1959 Kaleva Church competition and that Raili Paatelainen \"later became involved in the project\", while also stating that after 1963 all the office's works were officially attributed to \"Raili and Reima Pietilä\". Kaleva Church was built in 1964–66, inside that period, and Wikidata lists both architects. This entry files the building under Raili Pietilä and states the joint authorship in its dossier, because the shorthand that survives in guidebooks — \"Reima Pietilä's church\" — is a later compression of a credit the practice itself gave to two people.",
        es: "La Wikipedia en inglés registra que Reima Pietilä ganó el concurso de la iglesia de Kaleva en 1959 y que Raili Paatelainen «se incorporó después al proyecto», y señala al mismo tiempo que a partir de 1963 toda la obra del estudio se atribuyó oficialmente a «Raili y Reima Pietilä». La iglesia de Kaleva se construyó entre 1964 y 1966, dentro de ese periodo, y Wikidata consigna a ambos arquitectos. Esta ficha adscribe el edificio a Raili Pietilä y declara la coautoría en su dosier, porque el atajo que sobrevive en las guías —«la iglesia de Reima Pietilä»— es una compresión posterior de un crédito que el propio estudio otorgaba a dos personas.",
        it: "La Wikipedia inglese registra che Reima Pietilä vinse il concorso per la chiesa di Kaleva nel 1959 e che Raili Paatelainen «fu coinvolta nel progetto in seguito», affermando al tempo stesso che dopo il 1963 tutte le opere dello studio furono ufficialmente attribuite a «Raili e Reima Pietilä». La chiesa di Kaleva fu costruita fra il 1964 e il 1966, dentro quel periodo, e Wikidata elenca entrambi gli architetti. Questa scheda assegna l'edificio a Raili Pietilä e dichiara la coautoria nel dossier, perché la scorciatoia che sopravvive nelle guide — «la chiesa di Reima Pietilä» — è una compressione posteriore di un credito che lo studio stesso attribuiva a due persone.",
      },
      sources: [
        { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Raili_Pietil%C3%A4', title: 'Raili Pietilä', license: 'CC BY-SA 4.0' },
        { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Kaleva_Church', title: 'Kaleva Church', license: 'CC BY-SA 4.0' },
        { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q2577991', title: 'Kaleva Church (Q2577991)', license: null },
      ],
    },
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q3417698', title: 'Raili Pietilä (Q3417698)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Raili_Pietil%C3%A4', title: 'Raili Pietilä', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Kaleva_Church', title: 'Kaleva Church', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'snohetta',
    wikidataId: 'Q511335',
    name: 'Snøhetta',
    alternativeNames: ['Snøhetta AS', 'Snohetta', 'Snøhetta arkitektur landskap'],
    gender: 'unknown',
    born: 1989,
    died: null,
    floruit: { start: 2002, end: 2026, override: false },
    movements: [
      { id: 'sustainable-architecture', primary: true },
      { id: 'minimalism', primary: false },
    ],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'cultural',
    signatureMaterial: 'stone',
    portrait: {
      en: "Snøhetta began in 1987 as a group of young architects and landscape architects sharing an office in Storgata, Oslo, united by the complaint that landscape was always designed last, with whatever money the building had not spent. Their answer was to design building and ground as one thing. They took the name of the highest peak in Dovrefjell, and in 1989 won the open competition for the Bibliotheca Alexandrina in Egypt — a tilted disc cut into the ground, decided before the practice had built anything at all. The Oslo Opera House, the Norwegian National Opera and Ballet's home in Bjørvika, applied the same move at home: a roof you walk up. The office now works from Oslo and New York and describes sustainability, following the 1987 Brundtland report, as its founding brief.",
      es: "Snøhetta empezó en 1987 como un grupo de jóvenes arquitectos y paisajistas que compartían oficina en Storgata, en Oslo, unidos por la queja de que el paisaje se proyectaba siempre el último, con el dinero que el edificio no hubiera gastado. Su respuesta fue proyectar edificio y suelo como una sola cosa. Tomaron el nombre de la cumbre más alta del Dovrefjell y en 1989 ganaron el concurso abierto de la Bibliotheca Alexandrina, en Egipto: un disco inclinado incrustado en el terreno, decidido antes de que el estudio hubiera construido nada. La Ópera de Oslo, sede de la Ópera y el Ballet Nacionales de Noruega en Bjørvika, repitió el gesto en casa: una cubierta por la que se sube andando. El estudio trabaja hoy desde Oslo y Nueva York y describe la sostenibilidad, siguiendo el informe Brundtland de 1987, como su encargo fundacional.",
      it: "Snøhetta nacque nel 1987 come gruppo di giovani architetti e paesaggisti che condividevano un ufficio in Storgata, a Oslo, uniti dalla constatazione che il paesaggio veniva sempre progettato per ultimo, con i soldi che l'edificio non aveva speso. La loro risposta fu progettare edificio e suolo come una cosa sola. Presero il nome della vetta più alta del Dovrefjell e nel 1989 vinsero il concorso aperto per la Bibliotheca Alexandrina in Egitto: un disco inclinato incastrato nel terreno, deciso prima che lo studio avesse costruito alcunché. L'Opera di Oslo, sede dell'Opera e del Balletto nazionali norvegesi a Bjørvika, ripeté in patria la stessa mossa: un tetto su cui si sale a piedi. Lo studio lavora oggi da Oslo e New York e indica nella sostenibilità, sulla scia del rapporto Brundtland del 1987, il proprio mandato fondativo.",
    },
    awards: ['European Union Prize for Contemporary Architecture — Mies van der Rohe Award, 2009 (Oslo Opera House)', 'World Architecture Festival culture award, 2008', 'Global Award for Sustainable Architecture, 2010'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q511335', title: 'Snøhetta (Q511335)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Sn%C3%B8hetta_(company)', title: 'Snøhetta (company)', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Oslo_Opera_House', title: 'Oslo Opera House', license: 'CC BY-SA 4.0' },
    ],
  },
  {
    id: 'henning-larsen-architects',
    wikidataId: 'Q1339465',
    name: 'Henning Larsen Architects',
    alternativeNames: ['Henning Larsen', 'Henning Larsens Tegnestue', 'HLA'],
    gender: 'unknown',
    born: 1959,
    died: null,
    floruit: { start: 1978, end: 2026, override: false },
    movements: [
      { id: 'high-tech', primary: true },
      { id: 'sustainable-architecture', primary: false },
    ],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'cultural',
    signatureMaterial: 'steel-and-glass',
    portrait: {
      en: "Henning Larsen Architects was founded in Copenhagen in 1959 by Henning Larsen (1925–2013) and is now one of the largest practices in Scandinavia, with offices from Oslo and the Faroe Islands to Riyadh, Munich, New York and Hong Kong. Its reputation rests on cultural and educational buildings in which daylight is the primary material — a Nordic preoccupation carried into climates that have far too much of it. The Copenhagen Opera House of 2004, the Moesgaard Museum outside Aarhus and the Ministry of Foreign Affairs in Riyadh mark the range. Harpa in Reykjavík, designed with the artist Olafur Eliasson and the Icelandic office Batteríið, won the Mies van der Rohe Award in 2013. The firm runs its own doctoral research on sustainable building design and is part of the Ramboll Group.",
      es: "Henning Larsen Architects se fundó en Copenhague en 1959 por Henning Larsen (1925-2013) y es hoy uno de los mayores estudios de Escandinavia, con oficinas desde Oslo y las Islas Feroe hasta Riad, Múnich, Nueva York y Hong Kong. Su prestigio se apoya en edificios culturales y docentes en los que la luz natural es el material primero: una obsesión nórdica trasladada a climas que la tienen de sobra. La Ópera de Copenhague de 2004, el Museo Moesgaard, a las afueras de Aarhus, y el Ministerio de Asuntos Exteriores de Riad marcan el registro. Harpa, en Reikiavik, proyectada con el artista Olafur Eliasson y el estudio islandés Batteríið, obtuvo el Premio Mies van der Rohe en 2013. La firma mantiene investigación doctoral propia sobre diseño sostenible y forma parte del grupo Ramboll.",
      it: "Henning Larsen Architects fu fondato a Copenaghen nel 1959 da Henning Larsen (1925-2013) ed è oggi uno dei maggiori studi scandinavi, con sedi da Oslo e dalle Fær Øer fino a Riad, Monaco, New York e Hong Kong. La sua reputazione poggia su edifici culturali e universitari in cui la luce naturale è il materiale primario: un'ossessione nordica trasportata in climi che ne hanno fin troppa. L'Opera di Copenaghen del 2004, il Museo Moesgaard alle porte di Aarhus e il Ministero degli Esteri di Riad ne segnano l'ampiezza. Harpa, a Reykjavík, progettata con l'artista Olafur Eliasson e lo studio islandese Batteríið, ha vinto il premio Mies van der Rohe nel 2013. Lo studio conduce ricerca dottorale propria sulla progettazione sostenibile e fa parte del gruppo Ramboll.",
    },
    awards: ['European Union Prize for Contemporary Architecture — Mies van der Rohe Award, 2013 (Harpa)'],
    tier: 'canon',
    context: null,
    sources: [
      { kind: 'wikidata', url: 'https://www.wikidata.org/wiki/Q1339465', title: 'Henning Larsen Architects (Q1339465)', license: null },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Henning_Larsen_Architects', title: 'Henning Larsen Architects', license: 'CC BY-SA 4.0' },
      { kind: 'wikipedia', url: 'https://en.wikipedia.org/wiki/Harpa_(concert_hall)', title: 'Harpa (concert hall)', license: 'CC BY-SA 4.0' },
    ],
  },
];
