import type { Architect } from '@/types/architect';

// Wave 5 curator agent (Arabian Peninsula and Iraq): real, sourced Architect entries for this slice.
//
// `wikidataId: ''` marks an architect for whom no Wikidata item could be
// found on 2026-08-26. Those entries are hand-authored from the published
// sources listed in each record rather than from Wikidata, and the empty
// string is a recorded gap, never a placeholder QID.
//
// `workRegions` and `workCentroid` are deliberately left at [] / 0,0 —
// `data:curate` derives both from this slice's buildings and overwrites
// whatever is typed here.
export const WESTASIA_GULF_ARCHITECTS: Architect[] = [
  {
    id: 'abu-shakir-ibn-abi-al-faraj',
    wikidataId: '',
    name: 'Abu Shakir ibn Abi al-Faraj',
    alternativeNames: ['أبو شاكر بن أبي الفرج', 'Abū Shākir ibn Abī al-Faraj'],
    gender: 'man',
    born: null,
    died: null,
    floruit: { start: 1085, end: 1085, override: false },
    movements: 'unaffiliated',
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'sacral',
    signatureMaterial: 'brick',
    portrait: {
      en: 'Almost nothing is known of Abu Shakir ibn Abi al-Faraj beyond the one thing that matters: his name survives attached to the Imam Dur Mausoleum at Ad-Dawr, north of Samarra, built for an Uqaylid chamberlain around 1085. That building carries the earliest securely dated muqarnas dome anywhere, and the fact that a builder is named at all in eleventh-century Iraq is itself unusual — the overwhelming majority of medieval Iraqi and Arabian architecture reaches us anonymous, credited to its patron rather than its designer. No second work, no dates of birth or death, and no biography have been recovered. He is included here precisely because the attribution is documented rather than inferred, and because the alternative — leaving the pre-1800 architecture of this region entirely unnamed — would misrepresent what the record actually contains.',
      es: 'Casi nada se sabe de Abu Shakir ibn Abi al-Faraj salvo lo único que importa: su nombre sobrevive unido al mausoleo del Imán al-Dur, en Ad-Dawr, al norte de Samarra, levantado hacia 1085 para un chambelán uqaylí. Ese edificio conserva la cúpula de mocárabes fechada con seguridad más antigua que se conoce, y que un constructor aparezca nombrado en el Irak del siglo XI resulta de por sí excepcional: la inmensa mayoría de la arquitectura medieval iraquí y arábiga nos llega anónima, atribuida a su comitente y no a su autor. No se ha recuperado ninguna segunda obra, ni fechas de nacimiento o muerte, ni biografía alguna. Se le incluye aquí justamente porque la atribución está documentada y no inferida.',
      it: "Di Abu Shakir ibn Abi al-Faraj non si sa quasi nulla, tranne l'unica cosa che conta: il suo nome sopravvive legato al mausoleo dell'Imam al-Dur ad Ad-Dawr, a nord di Samarra, eretto verso il 1085 per un ciambellano uqaylide. Quell'edificio conserva la più antica cupola a muqarnas databile con certezza, e il fatto stesso che un costruttore venga nominato nell'Iraq dell'XI secolo è eccezionale: la grande maggioranza dell'architettura medievale irachena e araba ci giunge anonima, attribuita al committente e non al progettista. Non è stata recuperata alcuna seconda opera, né date di nascita o di morte, né una biografia. Lo si include qui proprio perché l'attribuzione è documentata e non dedotta.",
    },
    awards: [],
    tier: 'deep',
    context: null,
    sources: [
      {
        kind: 'wikipedia',
        url: 'https://en.wikipedia.org/wiki/Imam_Dur_Mausoleum',
        title: 'Imam Dur Mausoleum',
        license: 'CC BY-SA 4.0',
      },
      {
        kind: 'wikidata',
        url: 'https://www.wikidata.org/wiki/Q112788382',
        title: 'Imam Dur Mausoleum (Q112788382)',
        license: null,
      },
    ],
  },
  {
    id: 'awad-salman-afif-al-tarimi',
    wikidataId: '',
    name: "'Awad Salman 'Afif al-Tarimi",
    alternativeNames: ['عَوَض سَلْمَان عَفِيْف ٱلتَّرِيْمِي', 'Awad Salman Afif al-Tarimi'],
    gender: 'man',
    born: null,
    died: null,
    floruit: { start: 1914, end: 1914, override: false },
    movements: [{ id: 'earthen-vernacular', primary: true }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'sacral',
    signatureMaterial: 'earth',
    portrait: {
      en: "'Awad Salman 'Afif al-Tarimi was a master builder of Tarim, in the Wadi Hadhramaut of southern Yemen, working in the mudbrick tradition that gave the valley its towered towns. He is recorded as the designer of the minaret of the Al-Muhdhar Mosque, raised around 1914 and, at some fifty metres, the tallest earthen structure in the world; the published account notes that he had already carried out many clay lattices and domes before the commission, with the scholar Abu Bakr bin Shihab supervising the work. Beyond that, the record is thin — no dates, no second attributed building. He belongs in this pool because Hadhrami mudbrick architecture is usually presented as anonymous vernacular, and here, unusually, the man who built it is named.",
      es: "'Awad Salman 'Afif al-Tarimi fue un maestro de obras de Tarim, en el Wadi Hadramaut del sur de Yemen, formado en la tradición del adobe que dio a ese valle sus ciudades de torres. Consta como autor del alminar de la mezquita de Al-Muhdhar, levantado hacia 1914 y, con unos cincuenta metros, la construcción de tierra más alta del mundo; la fuente publicada señala que ya había ejecutado numerosas celosías y cúpulas de barro antes del encargo, y que el sabio Abu Bakr bin Shihab supervisó la obra. Más allá de eso el registro es escaso: sin fechas, sin una segunda obra atribuida. Figura aquí porque la arquitectura hadramí de adobe suele presentarse como vernácula anónima y, excepcionalmente, aquí sí se nombra a quien la construyó.",
      it: "'Awad Salman 'Afif al-Tarimi fu un capomastro di Tarim, nel Wadi Hadramaut, nello Yemen meridionale, formatosi nella tradizione dei mattoni crudi che diede a quella valle le sue città-torre. È documentato come autore del minareto della moschea di Al-Muhdhar, innalzato intorno al 1914 e, con circa cinquanta metri, la più alta struttura in terra cruda al mondo; la fonte pubblicata precisa che aveva già realizzato molte grate e cupole in argilla prima della commissione, e che il dotto Abu Bakr bin Shihab ne sovrintese i lavori. Oltre a questo la documentazione è esigua: nessuna data, nessuna seconda opera attribuita. Compare qui perché l'architettura hadramita in terra cruda viene di solito presentata come vernacolo anonimo mentre, eccezionalmente, qui il costruttore ha un nome.",
    },
    awards: [],
    tier: 'deep',
    context: null,
    sources: [
      {
        kind: 'wikipedia',
        url: 'https://en.wikipedia.org/wiki/Al-Muhdhar_Mosque',
        title: 'Al-Muhdhar Mosque',
        license: 'CC BY-SA 4.0',
      },
      {
        kind: 'wikidata',
        url: 'https://www.wikidata.org/wiki/Q10951815',
        title: 'Al-Muhdhar Mosque (Q10951815)',
        license: null,
      },
    ],
  },
  {
    id: 'edward-prioleau-warren',
    wikidataId: 'Q5344906',
    name: 'Edward Prioleau Warren',
    alternativeNames: ['E. P. Warren'],
    gender: 'man',
    born: 1856,
    died: 1937,
    floruit: { start: 1890, end: 1929, override: false },
    movements: [{ id: 'gothic-revival', primary: true }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'sacral',
    signatureMaterial: 'stone',
    portrait: {
      en: 'Edward Prioleau Warren (1856–1937) trained under George Frederick Bodley and spent most of his career on English churches and Oxford college work in the late Gothic Revival and Arts and Crafts manner. He appears in this pool for a single commission far outside that world: the Basra Memorial, unveiled in 1929 for the Imperial War Graves Commission, which records more than forty thousand Commonwealth dead of the Mesopotamian campaign of 1914–1921. Warren is one of a group of British architects the Commission engaged to give its memorials in the newly mandated Middle East an architectural language, and his presence in Iraq is inseparable from the imperial administration that put him there. He never practised in the region and is defined here only because he is the credited designer of a building in it.',
      es: 'Edward Prioleau Warren (1856-1937) se formó con George Frederick Bodley y dedicó casi toda su carrera a iglesias inglesas y a obras en los colegios de Oxford, dentro del neogótico tardío y del movimiento Arts and Crafts. Figura en este conjunto por un único encargo muy alejado de ese mundo: el memorial de Basora, inaugurado en 1929 para la Imperial War Graves Commission, que recuerda a más de cuarenta mil muertos de la Commonwealth en la campaña de Mesopotamia de 1914-1921. Warren pertenece al grupo de arquitectos británicos que la Comisión contrató para dar lenguaje arquitectónico a sus monumentos en el Oriente Próximo recién mandatado, y su presencia en Irak es inseparable de la administración imperial que lo llevó allí. Nunca ejerció en la región.',
      it: 'Edward Prioleau Warren (1856-1937) si formò con George Frederick Bodley e dedicò quasi tutta la carriera a chiese inglesi e a lavori nei college di Oxford, entro il tardo revival gotico e il movimento Arts and Crafts. Compare in questa raccolta per una sola commissione lontanissima da quel mondo: il memoriale di Bassora, inaugurato nel 1929 per la Imperial War Graves Commission, che ricorda oltre quarantamila caduti del Commonwealth nella campagna di Mesopotamia del 1914-1921. Warren appartiene al gruppo di architetti britannici che la Commissione ingaggiò per dare un linguaggio architettonico ai propri monumenti nel Medio Oriente appena posto sotto mandato, e la sua presenza in Iraq è inseparabile dall\'amministrazione imperiale che ve lo condusse. Non esercitò mai nella regione.',
    },
    awards: [],
    tier: 'deep',
    context: null,
    sources: [
      {
        kind: 'wikidata',
        url: 'https://www.wikidata.org/wiki/Q5344906',
        title: 'Edward Prioleau Warren (Q5344906)',
        license: null,
      },
      {
        kind: 'wikipedia',
        url: 'https://en.wikipedia.org/wiki/Edward_Prioleau_Warren',
        title: 'Edward Prioleau Warren',
        license: 'CC BY-SA 4.0',
      },
      {
        kind: 'wikipedia',
        url: 'https://en.wikipedia.org/wiki/Basra_Memorial',
        title: 'Basra Memorial',
        license: 'CC BY-SA 4.0',
      },
    ],
  },
  {
    id: 'j-brian-cooper',
    wikidataId: '',
    name: 'John Brian Cooper',
    alternativeNames: ['J. B. Cooper', 'J. Brian Cooper'],
    gender: 'man',
    born: 1899,
    died: 1983,
    floruit: { start: 1936, end: 1957, override: false },
    movements: 'unaffiliated',
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'civic',
    signatureMaterial: 'stone',
    portrait: {
      en: 'John Brian Cooper (1899–1983) was the British architect who served King Faisal I as official architect to the Hashemite state in Iraq, and he worked from Baghdad across three decades of the monarchy. His documented Iraqi output is small but consequential: the Royal Mausoleum of 1934–36, a parliament building of 1951–57, and the palace of 1956–57 now known as the Republican Palace. Elizabeth Bishop reads the mausoleum as a deliberately cosmopolitan object, taking the scale and central dome of Britain\'s royal burial ground at Frogmore and setting them against Abbasid, Ottoman and pan-Arab references. Cooper is one of the very few named designers of Iraq\'s Mandate and monarchy period, and his career is a reminder that state architecture there was, for a generation, commissioned from Britons.',
      es: 'John Brian Cooper (1899-1983) fue el arquitecto británico que sirvió al rey Faisal I como arquitecto oficial del Estado hachemí en Irak, con estudio en Bagdad a lo largo de tres décadas de monarquía. Su obra iraquí documentada es breve pero decisiva: el mausoleo real de 1934-36, un edificio parlamentario de 1951-57 y el palacio de 1956-57 hoy conocido como Palacio Republicano. Elizabeth Bishop lee el mausoleo como un objeto deliberadamente cosmopolita, que toma la escala y la cúpula central del cementerio real británico de Frogmore y las confronta con referencias abasíes, otomanas y panárabes. Cooper es uno de los poquísimos proyectistas con nombre del periodo del Mandato y la monarquía en Irak, y su carrera recuerda que durante una generación la arquitectura de Estado se encargó allí a británicos.',
      it: 'John Brian Cooper (1899-1983) fu l\'architetto britannico che servì re Faysal I come architetto ufficiale dello Stato hascemita in Iraq, operando da Baghdad lungo tre decenni di monarchia. La sua opera irachena documentata è breve ma decisiva: il mausoleo reale del 1934-36, un edificio parlamentare del 1951-57 e il palazzo del 1956-57 oggi noto come Palazzo Repubblicano. Elizabeth Bishop legge il mausoleo come un oggetto deliberatamente cosmopolita, che riprende la scala e la cupola centrale del cimitero reale britannico di Frogmore e le confronta con riferimenti abbasidi, ottomani e panarabi. Cooper è uno dei pochissimi progettisti con un nome del periodo del Mandato e della monarchia in Iraq, e la sua carriera ricorda che per una generazione l\'architettura di Stato vi fu commissionata a britannici.',
    },
    awards: [],
    tier: 'deep',
    context: null,
    sources: [
      {
        kind: 'publication',
        url: 'https://is.urd.ac.ir/article_137619.html',
        title: 'Bishop, E. (2022), "Hashemite Royal Mausoleum in Baghdad: Multi-Faceted, Cosmopolitan, and Diverse Influences", Islamic Inquiries 1(1), 27–42',
        license: null,
      },
      {
        kind: 'wikipedia',
        url: 'https://en.wikipedia.org/wiki/Iraqi_Royal_Cemetery',
        title: 'Iraqi Royal Cemetery',
        license: 'CC BY-SA 4.0',
      },
    ],
  },
  {
    id: 'rifat-chadirji',
    wikidataId: 'Q7333210',
    name: 'Rifat Chadirji',
    alternativeNames: ['رفعة الجادرجي', 'Rifat al-Chadirji', 'Rifaat Chadirji'],
    gender: 'man',
    born: 1926,
    died: 2020,
    floruit: { start: 1952, end: 1982, override: false },
    movements: [
      { id: 'critical-regionalism', primary: true },
      { id: 'brutalism', primary: false },
    ],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'civic',
    signatureMaterial: 'brick',
    portrait: {
      en: 'Rifat Chadirji (Baghdad 1926 – London 2020) is the central figure of modern Iraqi architecture. He returned to Baghdad in 1952, joined the Modern Baghdad Group and founded the practice Iraq Consult, and over the next quarter-century designed more than a hundred buildings — banks, post offices, villas, monuments — worked out in the local fired brick and reinforced concrete. He called the result "international regionalism": modern in construction, regional in the arch, the screen and the deep shadow that answer Baghdad\'s heat and light. He was equally important as a photographer, documenting with his father Kamil tens of thousands of Iraqi and regional buildings, an archive that became the foundation of the field after decades of war destroyed much of what it recorded. He received the Aga Khan Chairman\'s Award in 1986.',
      es: 'Rifat Chadirji (Bagdad, 1926 – Londres, 2020) es la figura central de la arquitectura iraquí moderna. Regresó a Bagdad en 1952, se sumó al Grupo de Bagdad Moderno y fundó el estudio Iraq Consult; en el cuarto de siglo siguiente proyectó más de cien edificios —bancos, oficinas de correos, villas, monumentos— resueltos en ladrillo cocido local y hormigón armado. Llamó al resultado "regionalismo internacional": moderno en la construcción y regional en el arco, la celosía y la sombra profunda que responden al calor y a la luz de Bagdad. Fue igualmente importante como fotógrafo: junto a su padre Kamil documentó decenas de miles de edificios iraquíes y de la región, un archivo que se convirtió en el cimiento de la disciplina cuando las guerras destruyeron buena parte de lo retratado. En 1986 recibió el Premio del Presidente Aga Khan.',
      it: 'Rifat Chadirji (Baghdad 1926 – Londra 2020) è la figura centrale dell\'architettura irachena moderna. Tornò a Baghdad nel 1952, entrò nel Gruppo di Baghdad Moderna e fondò lo studio Iraq Consult; nel quarto di secolo successivo progettò più di cento edifici — banche, uffici postali, ville, monumenti — risolti nel mattone cotto locale e nel cemento armato. Chiamò il risultato "regionalismo internazionale": moderno nella costruzione e regionale nell\'arco, nella grata e nell\'ombra profonda che rispondono al calore e alla luce di Baghdad. Fu altrettanto importante come fotografo: con il padre Kamil documentò decine di migliaia di edifici iracheni e regionali, un archivio divenuto il fondamento della disciplina dopo che decenni di guerra hanno distrutto molto di ciò che vi era registrato. Nel 1986 ricevette il Chairman\'s Award dell\'Aga Khan.',
    },
    awards: ['Aga Khan Award for Architecture — Chairman\'s Award (1986)', 'Sheikh Zayed Book Award (2008)', 'Tamayouz Lifetime Achievement Award (2015)'],
    tier: 'canon',
    context: {
      body: {
        en: 'Chadirji\'s career runs directly through the Ba\'ath state. In 1978, under the presidency of Ahmed Hassan al-Bakr, he was jailed for life on charges his biographers describe as unfounded, and served twenty months in Abu Ghraib. He was released in 1980 after Saddam Hussein took power, and Hussein then engaged him as architectural consultant to Baghdad city planning in 1982–83, overseeing reconstruction ahead of a summit the capital was to host. He left Iraq in 1983 for an academic post at Harvard and did not return to practice there. The same regime that imprisoned him and then employed him also demolished his 1959 Monument to the Unknown Soldier in 1982.',
        es: 'La carrera de Chadirji atraviesa de lleno el Estado baazista. En 1978, bajo la presidencia de Ahmed Hassan al-Bakr, fue condenado a cadena perpetua por cargos que sus biógrafos describen como infundados y cumplió veinte meses en Abu Ghraib. Fue liberado en 1980, tras la llegada de Sadam Husein al poder, y este lo contrató como consultor de planeamiento urbano de Bagdad en 1982-83, al frente de las obras previas a una cumbre que la capital debía acoger. Abandonó Irak en 1983 para ocupar un puesto académico en Harvard y no volvió a ejercer allí. El mismo régimen que lo encarceló y después lo empleó derribó en 1982 su Monumento al Soldado Desconocido de 1959.',
        it: 'La carriera di Chadirji attraversa in pieno lo Stato baathista. Nel 1978, sotto la presidenza di Ahmed Hassan al-Bakr, fu condannato all\'ergastolo con accuse che i suoi biografi descrivono come infondate e scontò venti mesi ad Abu Ghraib. Fu liberato nel 1980, dopo l\'ascesa al potere di Saddam Hussein, che lo ingaggiò come consulente per la pianificazione urbanistica di Baghdad nel 1982-83, a capo dei lavori preparatori di un vertice che la capitale doveva ospitare. Lasciò l\'Iraq nel 1983 per un incarico accademico a Harvard e non vi esercitò più. Lo stesso regime che lo imprigionò e poi lo impiegò demolì nel 1982 il suo Monumento al Milite Ignoto del 1959.',
      },
      sources: [
        {
          kind: 'wikipedia',
          url: 'https://en.wikipedia.org/wiki/Rifat_Chadirji',
          title: 'Rifat Chadirji',
          license: 'CC BY-SA 4.0',
        },
        {
          kind: 'publication',
          url: 'https://www.architecturalrecord.com/articles/12030-the-life-and-work-of-iraqs-most-influential-modernist-architect-in-photographs',
          title: 'Architectural Record, "The Life and Work of Iraq\'s Most Influential Modernist Architect, In Photographs" (22 November 2016)',
          license: null,
        },
      ],
    },
    sources: [
      {
        kind: 'wikidata',
        url: 'https://www.wikidata.org/wiki/Q7333210',
        title: 'Rifat Chadirji (Q7333210)',
        license: null,
      },
      {
        kind: 'wikipedia',
        url: 'https://en.wikipedia.org/wiki/Rifat_Chadirji',
        title: 'Rifat Chadirji',
        license: 'CC BY-SA 4.0',
      },
      {
        kind: 'publication',
        url: 'https://www.architecturalrecord.com/articles/12030-the-life-and-work-of-iraqs-most-influential-modernist-architect-in-photographs',
        title: 'Architectural Record, "The Life and Work of Iraq\'s Most Influential Modernist Architect, In Photographs" (22 November 2016)',
        license: null,
      },
    ],
  },
  {
    id: 'mohamed-makiya',
    wikidataId: 'Q1942781',
    name: 'Mohamed Saleh Makiya',
    alternativeNames: ['محمد مكية', 'Mohamed Makiya', 'Muhammad Salih Makiyya'],
    gender: 'man',
    born: 1914,
    died: 2015,
    floruit: { start: 1946, end: 2001, override: false },
    movements: [{ id: 'critical-regionalism', primary: true }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'sacral',
    signatureMaterial: 'brick',
    portrait: {
      en: 'Mohamed Saleh Makiya (Baghdad 1914 – London 2015) was among the first Iraqis to qualify formally as an architect, taking a degree at Liverpool in 1941 and a Cambridge doctorate in 1946 on climate and architecture in the Mediterranean. Back in Baghdad he opened Makiya Associates, and in 1959 founded Iraq\'s first school of architecture at the University of Baghdad, serving as its dean until 1968. His work is a sustained argument that the vocabulary of Islamic building — the arch, the courtyard, the brick surface, the muqarnas — could carry modern programmes without becoming pastiche. Offices in Bahrain, Muscat and London followed, and after falling out of favour with the Ba\'athist regime in the early 1970s he practised from exile, ending with the Sultan Qaboos Grand Mosque in Muscat.',
      es: 'Mohamed Saleh Makiya (Bagdad, 1914 – Londres, 2015) fue uno de los primeros iraquíes con titulación formal en arquitectura: se graduó en Liverpool en 1941 y se doctoró en Cambridge en 1946 con una tesis sobre clima y arquitectura en el Mediterráneo. De vuelta en Bagdad abrió Makiya Associates y en 1959 fundó la primera escuela de arquitectura de Irak en la Universidad de Bagdad, que dirigió como decano hasta 1968. Su obra sostiene con insistencia que el vocabulario de la construcción islámica —el arco, el patio, el paramento de ladrillo, los mocárabes— podía asumir programas modernos sin caer en el pastiche. Abrió después oficinas en Baréin, Mascate y Londres, y tras caer en desgracia ante el régimen baazista a comienzos de los setenta ejerció desde el exilio, culminando con la Gran Mezquita del Sultán Qabús.',
      it: 'Mohamed Saleh Makiya (Baghdad 1914 – Londra 2015) fu tra i primi iracheni a conseguire una formale abilitazione in architettura: laureato a Liverpool nel 1941 e dottorato a Cambridge nel 1946 con una tesi su clima e architettura nel Mediterraneo. Tornato a Baghdad aprì Makiya Associates e nel 1959 fondò la prima scuola di architettura dell\'Iraq all\'Università di Baghdad, di cui fu preside fino al 1968. La sua opera sostiene con costanza che il vocabolario della costruzione islamica — l\'arco, il cortile, la superficie in mattoni, i muqarnas — potesse reggere programmi moderni senza scadere nel pastiche. Seguirono uffici in Bahrein, a Mascate e a Londra; caduto in disgrazia presso il regime baathista nei primi anni Settanta, esercitò dall\'esilio, culminando nella Grande Moschea del Sultano Qabus.',
    },
    awards: ['Mohamed Makiya Prize established in his name by the Tamayouz Excellence Award (2014)'],
    tier: 'canon',
    context: {
      body: {
        en: 'By the early 1970s Makiya had fallen from favour with the Ba\'athist government and his name appeared on an arrest list; he moved to London, where he founded the Kufa Gallery for Islamic and Arab art. He returned briefly to Baghdad in 1980 for reconstruction work while his family stayed in England, and thereafter built almost entirely outside Iraq — Bahrain, Qatar, Kuwait, the Emirates, Tunis and finally Oman. The bulk of a career devoted to Iraqi architecture was therefore spent in exile from it, a pattern he shared with Rifat Chadirji and with the generation of Iraqi architects formed in the 1950s.',
        es: 'A comienzos de los años setenta Makiya había caído en desgracia ante el gobierno baazista y su nombre figuraba en una lista de detención; se trasladó a Londres, donde fundó la Kufa Gallery de arte islámico y árabe. Volvió brevemente a Bagdad en 1980 para trabajos de reconstrucción mientras su familia permanecía en Inglaterra, y a partir de entonces construyó casi por completo fuera de Irak: Baréin, Catar, Kuwait, los Emiratos, Túnez y finalmente Omán. El grueso de una carrera dedicada a la arquitectura iraquí transcurrió por tanto en el exilio, una pauta que compartió con Rifat Chadirji y con toda la generación de arquitectos iraquíes formada en los años cincuenta.',
        it: 'All\'inizio degli anni Settanta Makiya era caduto in disgrazia presso il governo baathista e il suo nome figurava in una lista di arresto; si trasferì a Londra, dove fondò la Kufa Gallery di arte islamica e araba. Tornò brevemente a Baghdad nel 1980 per lavori di ricostruzione mentre la famiglia restava in Inghilterra, e da allora costruì quasi interamente fuori dall\'Iraq: Bahrein, Qatar, Kuwait, Emirati, Tunisi e infine Oman. Il grosso di una carriera dedicata all\'architettura irachena si svolse dunque in esilio da essa, una vicenda che condivise con Rifat Chadirji e con l\'intera generazione di architetti iracheni formatasi negli anni Cinquanta.',
      },
      sources: [
        {
          kind: 'wikipedia',
          url: 'https://en.wikipedia.org/wiki/Mohamed_Makiya',
          title: 'Mohamed Makiya',
          license: 'CC BY-SA 4.0',
        },
        {
          kind: 'publication',
          url: 'https://www.bidoun.org/articles/mohamed-makiya',
          title: 'Bidoun, "Mohamed Makiya: Deeply Baghdadi"',
          license: null,
        },
      ],
    },
    sources: [
      {
        kind: 'wikidata',
        url: 'https://www.wikidata.org/wiki/Q1942781',
        title: 'Mohamed Makiya (Q1942781)',
        license: null,
      },
      {
        kind: 'wikipedia',
        url: 'https://en.wikipedia.org/wiki/Mohamed_Makiya',
        title: 'Mohamed Makiya',
        license: 'CC BY-SA 4.0',
      },
      {
        kind: 'publication',
        url: 'https://www.bidoun.org/articles/mohamed-makiya',
        title: 'Bidoun, "Mohamed Makiya: Deeply Baghdadi"',
        license: null,
      },
    ],
  },
  {
    id: 'malene-bjorn',
    wikidataId: 'Q16163112',
    name: 'Malene Bjørn',
    alternativeNames: ['Malene Bjoern', 'Malene Bjorn'],
    gender: 'woman',
    born: 1914,
    died: 2016,
    floruit: { start: 1971, end: 1976, override: false },
    movements: 'unaffiliated',
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'tower',
    signatureMaterial: 'concrete',
    portrait: {
      en: 'Malene Bjørn (1914–2016) was a Danish designer and architect whose single most visible work stands not in Denmark but on a spit of reclaimed land in Kuwait City. She was married to the Swedish architect Sune Lindström, chief architect of the engineering firm VBB, which was building Kuwait\'s post-oil water supply; Lindström had already put up five groups of his characteristic mushroom-headed water towers when the Emir asked for something more memorable at the sixth site. Bjørn produced ten schemes, three went to the ruler, and the chosen design became the Kuwait Towers, completed in 1976. Her contribution is often folded into VBB\'s corporate credit, and recovering it matters: she is one of very few women with a securely attributed landmark anywhere in the Gulf.',
      es: 'Malene Bjørn (1914-2016) fue una diseñadora y arquitecta danesa cuya obra más visible no se encuentra en Dinamarca sino sobre una lengua de terreno ganado al mar en la ciudad de Kuwait. Estaba casada con el arquitecto sueco Sune Lindström, jefe de arquitectura de la ingeniería VBB, que construía el abastecimiento de agua del Kuwait posterior al petróleo; Lindström había levantado ya cinco grupos de sus característicos depósitos en forma de seta cuando el emir pidió algo más memorable para el sexto emplazamiento. Bjørn preparó diez propuestas, tres llegaron al gobernante y la elegida se convirtió en las Torres de Kuwait, terminadas en 1976. Su aportación suele diluirse en el crédito corporativo de VBB, y recuperarla importa: es una de las poquísimas mujeres con un hito atribuido con seguridad en todo el Golfo.',
      it: 'Malene Bjørn (1914-2016) fu una designer e architetta danese la cui opera più visibile non si trova in Danimarca ma su una lingua di terra bonificata a Kuwait City. Era sposata con l\'architetto svedese Sune Lindström, capo architetto della società di ingegneria VBB, che stava realizzando l\'acquedotto del Kuwait post-petrolifero; Lindström aveva già eretto cinque gruppi dei suoi caratteristici serbatoi a fungo quando l\'emiro chiese qualcosa di più memorabile per il sesto sito. Bjørn elaborò dieci soluzioni, tre giunsero al sovrano e quella prescelta divenne le Kuwait Towers, completate nel 1976. Il suo contributo viene spesso assorbito nella firma collettiva di VBB, e recuperarlo conta: è una delle pochissime donne con un\'opera-simbolo attribuita con certezza in tutto il Golfo.',
    },
    awards: ['Aga Khan Award for Architecture (1980), for the Kuwait water towers, with Sune Lindström and VBB'],
    tier: 'canon',
    context: null,
    sources: [
      {
        kind: 'wikidata',
        url: 'https://www.wikidata.org/wiki/Q16163112',
        title: 'Malene Bjørn (Q16163112)',
        license: null,
      },
      {
        kind: 'wikipedia',
        url: 'https://en.wikipedia.org/wiki/Kuwait_Towers',
        title: 'Kuwait Towers',
        license: 'CC BY-SA 4.0',
      },
    ],
  },
  {
    id: 'ali-al-shuaibi',
    wikidataId: '',
    name: 'Ali Al-Shuaibi',
    alternativeNames: ['علي الشعيبي', 'Ali Shuaibi'],
    gender: 'man',
    born: null,
    died: null,
    floruit: { start: 1979, end: 2010, override: false },
    movements: [{ id: 'critical-regionalism', primary: true }],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'civic',
    signatureMaterial: 'stone',
    portrait: {
      en: 'Ali Al-Shuaibi took his architecture degree at King Saud University in 1972 and a master\'s in urban design at MIT in 1975, and in that same year founded the Riyadh practice Beeah with Abdul-Rahman Al-Hussaini. Beeah has since built across Saudi Arabia, Oman, Yemen, Pakistan and Djibouti, and Al-Shuaibi has taught design at King Saud University, chaired the Saudi Society for Architecture and co-edited an encyclopaedia of urban heritage. His best-known work is Al-Kindi Plaza in Riyadh\'s Diplomatic Quarter, which took the Aga Khan Award for Architecture in 1989 for reasserting the traditional relationship between the mosque and the civic square. Wikidata carries no item for him; the record here is assembled from the Aga Khan Trust, Archnet and his practice.',
      es: 'Ali Al-Shuaibi se tituló en arquitectura por la Universidad Rey Saúd en 1972 y obtuvo un máster en diseño urbano en el MIT en 1975; ese mismo año fundó en Riad el estudio Beeah junto a Abdul-Rahman Al-Hussaini. Beeah ha construido desde entonces en Arabia Saudí, Omán, Yemen, Pakistán y Yibuti, y Al-Shuaibi ha enseñado proyectos en la Universidad Rey Saúd, presidido la Sociedad Saudí de Arquitectura y codirigido una enciclopedia del patrimonio urbano. Su obra más conocida es la plaza Al-Kindi, en el Barrio Diplomático de Riad, que recibió el Premio Aga Khan de Arquitectura en 1989 por restituir la relación tradicional entre la mezquita y la plaza cívica. Wikidata no recoge ninguna entrada suya; esta ficha se ha compuesto a partir del Aga Khan Trust, Archnet y su propio estudio.',
      it: 'Ali Al-Shuaibi si laureò in architettura alla King Saud University nel 1972 e conseguì un master in disegno urbano al MIT nel 1975; nello stesso anno fondò a Riad lo studio Beeah con Abdul-Rahman Al-Hussaini. Beeah ha da allora costruito in Arabia Saudita, Oman, Yemen, Pakistan e Gibuti, e Al-Shuaibi ha insegnato progettazione alla King Saud University, presieduto la Società Saudita di Architettura e curato un\'enciclopedia del patrimonio urbano. La sua opera più nota è la piazza Al-Kindi, nel Quartiere Diplomatico di Riad, che nel 1989 ottenne l\'Aga Khan Award for Architecture per aver restituito il rapporto tradizionale fra la moschea e la piazza civica. Wikidata non registra alcuna voce su di lui; questa scheda è composta da fonti dell\'Aga Khan Trust, di Archnet e del suo studio.',
    },
    awards: ['Aga Khan Award for Architecture (1989), for Al-Kindi Plaza, with Abdul-Rahman Al-Hussaini and Beeah Group Consultants'],
    tier: 'deep',
    context: null,
    sources: [
      {
        kind: 'institution',
        url: 'https://the.akdn/en/how-we-work/our-agencies/aga-khan-trust-culture/akaa/al-kindi-plaza',
        title: 'Aga Khan Development Network — Al-Kindi Plaza (Aga Khan Award for Architecture, 1987–1989 cycle)',
        license: null,
      },
      {
        kind: 'institution',
        url: 'https://www.archnet.org/authorities/328',
        title: 'Archnet — Authority record: Ali Shuaibi',
        license: null,
      },
      {
        kind: 'institution',
        url: 'https://beeah.sa/about/',
        title: 'Beeah Planners, Architects and Engineers — About',
        license: null,
      },
    ],
  },
  {
    id: 'mona-el-mousfy',
    wikidataId: '',
    name: 'Mona El Mousfy',
    alternativeNames: ['Mona El-Mousfy', 'منى الموصفي'],
    gender: 'woman',
    born: null,
    died: null,
    floruit: { start: 2005, end: 2020, override: false },
    movements: 'unaffiliated',
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'cultural',
    signatureMaterial: 'concrete',
    portrait: {
      en: 'Mona El Mousfy is a Lebanese architect who moved from Paris to the United Arab Emirates in 2002, taught for twelve years at the American University of Sharjah, and founded SpaceContinuum, a research-led practice concerned with how space carries shared social practice. She has been architecture consultant to the Sharjah Art Foundation since 2005, designing successive Biennial installations and then the Foundation\'s permanent Art Spaces at Al Mureijah, five new buildings threaded through six restored historic houses, which was shortlisted for the Aga Khan Award for Architecture in 2019. Her later work is largely adaptive reuse, including the 2020 conversion of Sharjah\'s 1970s Flying Saucer. She helped found the Sharjah Architecture Triennial in 2017 and remains its adviser. No Wikidata item exists for her.',
      es: 'Mona El Mousfy es una arquitecta libanesa que se trasladó de París a los Emiratos Árabes Unidos en 2002, enseñó doce años en la Universidad Americana de Sharjah y fundó SpaceContinuum, un estudio de base investigadora centrado en cómo el espacio sostiene la práctica social compartida. Es consultora de arquitectura de la Sharjah Art Foundation desde 2005: proyectó sucesivas ediciones de la Bienal y, después, los Art Spaces permanentes de la Fundación en Al Mureijah, cinco edificios nuevos entretejidos con seis casas históricas restauradas, finalistas del Premio Aga Khan de Arquitectura en 2019. Su obra reciente es sobre todo de reutilización adaptativa, como la conversión en 2020 del Platillo Volante de Sharjah, de los años setenta. Cofundó en 2017 la Trienal de Arquitectura de Sharjah, de la que sigue siendo asesora. No existe entrada suya en Wikidata.',
      it: 'Mona El Mousfy è un\'architetta libanese che nel 2002 si trasferì da Parigi negli Emirati Arabi Uniti, insegnò dodici anni all\'American University of Sharjah e fondò SpaceContinuum, uno studio a base di ricerca dedicato al modo in cui lo spazio sostiene la pratica sociale condivisa. È consulente per l\'architettura della Sharjah Art Foundation dal 2005: ha progettato successive edizioni della Biennale e poi gli Art Spaces permanenti della Fondazione ad Al Mureijah, cinque edifici nuovi intrecciati a sei case storiche restaurate, finalisti dell\'Aga Khan Award for Architecture nel 2019. Il suo lavoro più recente è soprattutto di riuso adattivo, come la conversione nel 2020 del Disco Volante di Sharjah, degli anni Settanta. Nel 2017 ha contribuito a fondare la Triennale di Architettura di Sharjah, di cui resta consulente. Non esiste una voce Wikidata su di lei.',
    },
    awards: ['Shortlisted, Aga Khan Award for Architecture (2019), for the Sharjah Art Foundation Art Spaces'],
    tier: 'deep',
    context: null,
    sources: [
      {
        kind: 'institution',
        url: 'https://www.sharjaharchitecture.org/pages/about/contributors/mona-el-mousfy',
        title: 'Sharjah Architecture Triennial — Contributors: Mona El-Mousfy',
        license: null,
      },
      {
        kind: 'institution',
        url: 'https://www.sharjahart.org/en/march-meeting/mm-2018/speakers/details/el-mousfy-mona/',
        title: 'Sharjah Art Foundation — March Meeting 2018 speaker: Mona El Mousfy',
        license: null,
      },
      {
        kind: 'institution',
        url: 'https://www.archnet.org/authorities/8741',
        title: 'Archnet — Authority record: Mona El Mousfy',
        license: null,
      },
    ],
  },
  {
    id: 'sumaya-dabbagh',
    wikidataId: 'Q131468783',
    name: 'Sumaya Dabbagh',
    alternativeNames: ['سمية دباغ'],
    gender: 'woman',
    born: null,
    died: null,
    floruit: { start: 2008, end: 2023, override: false },
    movements: [
      { id: 'critical-regionalism', primary: true },
      { id: 'minimalism', primary: false },
    ],
    workRegions: [],
    workCentroid: { lat: 0, lon: 0 },
    primaryTypology: 'cultural',
    signatureMaterial: 'concrete',
    portrait: {
      en: 'Sumaya Dabbagh was born in Jeddah, studied architecture at Bath under the supervision of Peter Smithson and Ted Happold, and began her career in London and Paris in the early 1990s before settling in the Gulf. In 2008 she founded Dabbagh Architects in Dubai, among the first architectural practices in the Emirates led by a woman and among the first RIBA-chartered practices in the region. Her buildings are quiet, low and heavily shaded, working with concrete and desert-coloured stone against strong light: the Mleiha Archaeological Centre in Sharjah, wrapped around a Bronze Age tomb, and the Mosque of the Late Mohamed Abdulkhaliq Gargash in Dubai, one of the first mosques in the UAE designed by a woman.',
      es: 'Sumaya Dabbagh nació en Yeda, estudió arquitectura en Bath bajo la tutela de Peter Smithson y Ted Happold y comenzó su carrera en Londres y París a comienzos de los años noventa, antes de instalarse en el Golfo. En 2008 fundó Dabbagh Architects en Dubái, uno de los primeros estudios de arquitectura de los Emiratos dirigidos por una mujer y de los primeros de la región inscritos en el RIBA. Sus edificios son bajos, callados y profundamente sombreados, y trabajan el hormigón y la piedra del color del desierto contra una luz muy dura: el Centro Arqueológico de Mleiha, en Sharjah, envuelto en torno a una tumba de la Edad del Bronce, y la mezquita del difunto Mohamed Abdulkhaliq Gargash, en Dubái, una de las primeras mezquitas de los Emiratos proyectadas por una mujer.',
      it: 'Sumaya Dabbagh è nata a Gedda, ha studiato architettura a Bath sotto la guida di Peter Smithson e Ted Happold e ha iniziato la carriera a Londra e Parigi nei primi anni Novanta, prima di stabilirsi nel Golfo. Nel 2008 ha fondato a Dubai lo studio Dabbagh Architects, fra i primi degli Emirati diretti da una donna e fra i primi della regione iscritti al RIBA. I suoi edifici sono bassi, silenziosi e fortemente ombreggiati, e lavorano il calcestruzzo e la pietra color deserto contro una luce durissima: il Centro Archeologico di Mleiha, a Sharjah, avvolto attorno a una tomba dell\'età del bronzo, e la moschea del defunto Mohamed Abdulkhaliq Gargash a Dubai, una delle prime moschee degli Emirati progettate da una donna.',
    },
    awards: ['Architecture MasterPrize (2020), for the Mleiha Archaeological Centre', 'Cityscape Global Award (2016), for the Mleiha Archaeological Centre'],
    tier: 'deep',
    context: null,
    sources: [
      {
        kind: 'wikidata',
        url: 'https://www.wikidata.org/wiki/Q131468783',
        title: 'Sumaya Dabbagh (Q131468783)',
        license: null,
      },
      {
        kind: 'institution',
        url: 'https://www.dabbagharchitects.com/biography-2/',
        title: 'Dabbagh Architects — Biography',
        license: null,
      },
      {
        kind: 'publication',
        url: 'https://www.ribaj.com/intelligence/profile-sumaya-dabbagh-dubai-uae-international-local-design-community-context/',
        title: 'RIBA Journal, "Profile: Dubai-based Sumaya Dabbagh on UAE\'s widening architectural scene"',
        license: null,
      },
    ],
  },
];
